DFE-Digital/publish-teacher-training

README.md
app/controllers/api/v1/courses_controller.rb
app/controllers/api/v1/subjects_controller.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/requests/api/v1/subject_spec.rb

Ensure `subjects` and `courses` inherit from correct controller
Basic auth should kick in for the `subjects` and `courses` endpoint as well as `providers`

Course and subject controller inherit from app controller

---

app/serializers/site_status_serializer.rb

Broken endpoint https://manage-courses-support.herokuapp.com/api/v1/courses?page=18
Check presence of `applications_accepted_from` with `.present?`
`course_open_date` should return null when `applications_accepted_from` isn't present

Correctly check presence of applications_accepted_from

---

spec/requests/api/v1/course_spec.rb

The `course_spec` expectation has quite a few `nil` values.
This change adds test coverage and helps document the API's output data types.

Explicitly specify test data in course spec

---

app/serializers/course_serializer.rb
spec/requests/api/v1/course_spec.rb

Downstream API consumer asked for the start date month to be included in the API.

Add explicit start month string to course API

---

app/models/course.rb
app/serializers/course_serializer.rb
spec/requests/api/v1/course_spec.rb

Some of the database fields (like `course.profpost_flag`) are abbreviated down to the point that it's hard to see what the values mean at first glance. This problem can be overcome with some Rails syntactic sugar which makes at least the code more readable.
This allows us to keep the domain definitions of the field in the Course model, while still sending the more cryptic variants downstream to consumers of the API.
If we like this approach, I can do the same for other enums in the schema.

Define and use enum for profpost_flag on Course

---

app/models/provider.rb
app/serializers/provider_serializer.rb
spec/factories/provider_enrichment.rb
spec/factories/providers.rb
spec/factory_specs/providers_spec.rb
spec/models/provider_spec.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

Providers endpoint
Add contact details i.e. `address1`, `address2`, `address3`, `address4`, `postcode`
`/api/v1/providers`

Add contact details to provider

---

.dockerignore
.travis.yml
Dockerfile
README.md
config.sh
config/database.yml
docker-compose.yml
docker-login.sh
docker-push.sh

This builds a docker image of the app when we push to CI, runs the tests inside, and then pushes it to the Azure Container Registry under the `master|staging|production` tags respectively.
Also includes instructions on running the app locally using `docker-compose` to better mimic the live environment, and simplify the setup by not requiring specific versions of Ruby or Postgres installed locally.
Paired with @defong.

Dockerise the app, build the container on CI, and push it to Azure

---

app/models/provider.rb
app/serializers/provider_serializer.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb

The `provider.provider_type` attribute was wired up on #27.
Introduce an enum to decode the attribute (similar to #21 and #22). Also fix up some test data for consistency.

Provider type enum

---

.rubocop.yml

This just makes it a lot easier to integrate with existing tools, such as
editor integrations with rubocop.
Move the rubocop configs from [alphagov/govuk-lint](https://github.com/alphagov/govuk-lint) repo into our ours.
One reason against is that if `govuk-lint` is updated we'll miss those changes. If we continue to use `govuk-lint` in our CI, though, we'll catch those and be able to update the configs in the repo.

Add rubocop configs from govuk-lint.

---

app/serializers/site_serializer.rb
db/schema.rb
spec/requests/api/v1/provider_spec.rb
spec/serializers/site_serializer_spec.rb

site `region_code`
Added `region_code` to site
region_code can be a nullable int

Added site region code

---

app/serializers/site_serializer.rb
spec/requests/api/v1/provider_spec.rb

Before this change, the `region_code` datatype didn't match the docs.

Change region_code to be a 2-digit string as specified in API docs

---

app/models/site.rb

This was overlooked in the prior PR which added the enum (#35).

Add missing region_code enum for zero value

---

app/models/course.rb
app/models/site.rb
app/models/site_status.rb
app/serializers/course_serializer.rb
app/serializers/site_serializer.rb
app/serializers/site_status_serializer.rb
config/routes.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/requests/api/v1/subject_spec.rb

`recruitment_cycle`
Add `recruitment_cycle` into route
`http://localhost:3000/api/v1/2019/courses`
`http://localhost:3000/api/v1/2019/providers`
`http://localhost:3000/api/v1/2019/subjects`

Include recruitment_year into routes

---

app/models/provider.rb
app/models/provider_enrichment.rb
spec/factories/provider_enrichments.rb
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/requests/api/v1/provider_spec.rb

Lack of ordering of provider enrichment where by older version of enrichment details are used instead of new version.
The address section of the enrichment can be empty/blank, ie only enriched the section concerning their accrediting provider, the blanked values are used.
Added ordering of provider enrichment based on created_at date as default
Fixed the address to hydrate based on using provider details if enrichment is not available

Missing address for provider

---

app/controllers/api/v1/providers_controller.rb
app/models/provider.rb
docs/api.md
spec/controllers/api/v1/providers_controller_spec.rb
spec/factories/providers.rb
spec/requests/api/v1/provider_spec.rb
spec/spec_helper.rb

This brings the API in line with our documentation, by querying the database with the necessary ordering, limiting, and then adding a custom response header with the correctly formed URL.
Also enables focusing by using `fit`, `fdescribe`, `fcontext` in rspec; see the first commit.
Paired with @timabell.

Implement changed_since-based pagination for providers

---

app/models/provider.rb
spec/models/provider_spec.rb
spec/requests/api/v1/provider_spec.rb

Provider `changed_since`
The c# api is going to deal with this i.e. update the Provider `updated_at` column everytime a site is updated or an enrichment is created.
Example - `http://localhost:3000/api/v1/2019/providers?changed_since=20190206`

Simplify provider changed_since

---

app/controllers/api/v1/providers_controller.rb
spec/controllers/api/v1/providers_controller_spec.rb

`changed_since` query parameter
- Render `400` when `changed_since` is invalid
`http://localhost:3000/api/v1/2019/providers?changed_since=2019`

Rescue changed since param

---

db/schema.rb

This work was done on the .NET app but not reflected here in Rails, hence
the update.
Update the schema.rb to remove old indexes and foreign keys.
Basically indexes with `*_mc_*` and `*_ucas_*` were old and duplicated similarly-named indexes that didn't include those strings. See:
https://trello.com/c/Wh8TLfwJ/683-duplicate-foreign-keys-in-manage

683 Remove old indexes and foreign keys

---

app/controllers/api/v1/providers_controller.rb
app/models/provider.rb
db/schema.rb
spec/controllers/api/v1/providers_controller_spec.rb
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/requests/api/v1/provider_spec.rb

To ensure providers are exported whenever they, or any entities that indicate the the provider info has changed.
To support the incremental results in the API providers endpoint we want to update the last_published_at column on the provider when a related entity, site or provider enrichments for example. This will be needed in the future once the Rails backend takes on the work of updating the providers and their related entities.
The C# has already been updated to populate this data. https://github.com/DFE-Digital/manage-courses-api/pull/267
* Switch to `provider.last_published_at` instead of `updated_at`
* Schema has been manually modified to match changes from .NET app.
~~Until the c# schema change has shipped to prod https://github.com/DFE-Digital/manage-courses-api/pull/267~~

953 change changed_since scope to use last_published_at

---

app/controllers/api/v1/courses_controller.rb
app/controllers/api/v1/providers_controller.rb
app/controllers/concerns/first_item_from_next_page.rb
app/controllers/concerns/next_link_header.rb
app/models/course.rb
app/models/provider_enrichment.rb
app/serializers/course_serializer.rb
db/schema.rb
spec/factories/courses.rb
spec/factories/provider_enrichments.rb
spec/models/course_spec.rb
spec/requests/api/v1/course_spec.rb
spec/serializers/course_serializer_spec.rb

This allows users to only fetch a specific set of courses from a passed in changed_since time.
- Pull in database changes based on the C# API changes
- Implement changed_since scope on the course model
- Implement changed_since param and Link header on course controller similarly to the one in the provider controller; Link header logic is abstracted into a concern
The tests are almost a complete carbon copy of the tests from the provider controller. This isn't DRY, but can be made if so requested, it just feels like the correct abstraction for this didn't naturally appear while writing them. Suggestions welcome.
The `rescue` call in the controller is ported from a previous PR by Dan, and is also not DRY. Suggestions welcome once more.
No docs changes were needed for this.
This entire PR …

[850] Implement incremental fetching on CourseController index

---

app/controllers/api/v1/application_controller.rb
app/controllers/api/v1/courses_controller.rb
app/controllers/api/v1/providers_controller.rb
app/controllers/api/v1/subjects_controller.rb
app/controllers/api/v2/application_controller.rb
config/initializers/inflections.rb
spec/controllers/api/v1/courses_controller_spec.rb
spec/controllers/api/v1/providers_controller_spec.rb
spec/controllers/api/v1/subjects_controller_spec.rb
spec/controllers/api/v2/application_controller_spec.rb

Purely for esthetics.
`Api` just looks weird.
Rename `Api` to `API`. Requires an addition to the inflector.

capitalise Api module to API

---

Dockerfile
README.md
app/models/provider.rb
app/serializers/provider_serializer.rb
db/migrate/20190213160920_add_changed_at_to_provider.rb
db/schema.rb
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

`provider.changed_at` is going to be used to track any change that would cause a re-export for the ucas apply system. It's an amalgamation of last_published and updated_at along with dependent record changes
Doing this as a separate PR as it's our first ever migration on the rails side to avoid tying it up with the functionality to update it.
* First migration - adds new column.
* Baseline schema.rb version (done automatically by the rails tools)
Test migration from clean setup of db, and with sanitized backup from prod. I've done both and it worked for me.

953 add provider changed at & configure docker to run migrations in prod etc

---

.rspec
azure-pipelines.yml

#128 changed RSpec to output results as JUnit-formatted XML. However this makes it really hard to see what's going on when running specs during development.
Re-enable rspec printing dots when running specs locally. This includes changes to the CI build to preserve the JUnit-formatted output.
Not sure I've got the escaping correct in `azure-pipelines.yml`?

Re-enable rspec printing dots when running specs locally

---

lib/tasks/create_dev_user.rake

When we currently do `rake -T` we don't see the `create_dev_user` task.
Add it to the `rake -T` by giving it a `desc`.

Add desc to create-dev-user rake task so it shows up with rake -T

---

app/controllers/api/v1/providers_controller.rb
app/models/provider.rb
db/migrate/20190222063449_add_opted_in_to_provider.rb
db/schema.rb
spec/factories/providers.rb
spec/models/provider_spec.rb

UCAS Transition
Add `opted_in` to providers and scope v1/providers to only return when `true`

[1015] Add opted_in for providers

---

app/serializers/course_serializer.rb
spec/requests/api/v1/course_spec.rb
spec/serializers/course_serializer_spec.rb

This field is not documented, nor used by the downstream consumer.
Remove it from the serialiser.

[1024] Remove 'Course#qualification' from V1 API

---

app/models/concerns/with_qualifications.rb
app/models/pgde_course.rb
db/seeds.rb
spec/factories/courses.rb
spec/factories/pgde_course.rb
spec/factory_specs/course_spec.rb
spec/models/concerns/with_qualifications_spec.rb

#135 introduced a lot of logic to derive qualifications, based on UCAS information and the `pgde_course` overlay table. However, what I've since learned is that the UCAS importer already does this and persists an enum into the `course#qualification` column. We can just use this column in a much more direct way for the Course API v2.
Once the UCAS transition happens and the UCAS importer is turned off, we can probably stop using the `profpost_flag` and the `pgde_course` table, and just use `course#qualification` instead.
* use the `qualification` enum on `course`
* throw away a lot of the complexity
* document qualification-related fields in order for the learnings to not get lost
* leave `TODO`s to simplify (i.e. delete) this logic even further, post-transition

[1014] Simplify qualifications logic

---

app/models/site.rb
app/models/site_status.rb
app/serializers/site_serializer.rb
app/serializers/site_status_serializer.rb
docs/api.md
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb

`recruitment_cycle` only applies to `course`
- Remove `recruitment_cycle` from `site`
- Remove `recruitment_cycle` from `site_status`
`/api/v1/courses`

Remove recruitment_cycle from site and site_status

---

Gemfile
Gemfile.lock

Pulled this out of #131 since that PR was getting rather big. Timecop allows us to freeze time in tests so that we aren't sensitive to timing issues / race conditions.
Add timecop gem
#131 relies on this being merged.

[953] add Timecop gem

---

README.md
Rakefile
app/models/provider.rb
app/serializers/provider_serializer.rb
lib/tasks/govuk_lint.rake
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

Running several commands to keep our code clean and happy is a hassle
- Override `rake` to run the specs, linter and annotate
```
bundle exec rake
```

Improve default rake task

---

app/controllers/api/v1/providers_controller.rb
app/models/concerns/changed_at.rb
app/models/provider.rb
app/models/site.rb
config/routes.rb
db/schema.rb
docs/api.md
spec/controllers/api/v1/providers_controller_spec.rb
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/models/site_spec.rb
spec/requests/api/v1/provider_spec.rb

We need to track this for the incremental API so that it can include all related data that might have changed. I.e. if a site has changed then that provider needs to be included in the relevant `changed_since` range even though the provider record hasn't changed.
`provider.changed_at` is updated when site is updated, while `provider.updated_at` is unaffected.
We also change the implementation of the incremental load by `from_provider_id` from the `Next` link, and using sub-second values for `changed_since` manages to achieve the desired goal of ordering the set of changed providers with a resolution higher then seconds. This is supported by the `changed_at` column without any modifications, we just need to format the timestamp with the `strftime` format `%FT%T.%6N` instead of using …

[953] update provider.changed_at when site changes

---

README.md
app/controllers/api/v2/sessions_controller.rb
config/routes.rb
spec/requests/api/v2/session_spec.rb

The ability to create a session and update the user last login time as will as the first and last name. 
Endpoint exists and frontend is able to "create" a session for new user login.
The last_login timestamp is incremented after this endpoint is accessed
This needs to work with frontend.

[993] Create new endpoint in for user session

---

config/environments/development.rb

UCAS env is now in dev mode, so it had reverted to the default token
which is not what we want.
This patch means that local development still gets the default token,
and we can run development mode in azure with a custom token (for
pre-production environments).
This will go away when we switch to the settings gem for the v1 api.

Use auth token from environment if available in dev

---

app/models/concerns/touch_provider.rb
app/models/provider.rb
app/models/provider_enrichment.rb
app/models/site.rb
spec/models/provider_enrichment_spec.rb

Linked to the [953] changed_at pull request. 
https://github.com/DFE-Digital/manage-courses-backend/pull/131
Changes to the provider enrichment model now update changed_at.
- touch_provider implemented in the provider enrichment model
- touch_provider refactored into a concern
- Tests to check that changed_at is updated when provider enrichment is touched, while leaving updated_at unaffected.

[1011] Update changed_at when provider enrichment is updated

---

app/serializers/api/v2/serializable_provider.rb
spec/requests/api/v2/providers_spec.rb

On the frontend we display the number of courses for each provider
Add `course_count` to v2 providers endpoint
`/api/v2/providers`

Add courses count to v2 providers endpoint

---

app/controllers/api/v1/courses_controller.rb
app/models/course.rb
spec/models/course_spec.rb

The courses endpoint should only return courses where their providers are opted in
Add scope to courses endpoint
`/api/v1/courses`

Add course scope for opted in providers

---

app/controllers/api/v1/courses_controller.rb
app/controllers/concerns/next_link_header.rb
app/models/course.rb
docs/api.md
spec/controllers/api/v1/courses_controller_spec.rb
spec/factories/courses.rb
spec/models/course_spec.rb
spec/requests/api/v1/course_spec.rb

This brings it inline with the implementation of the provider incremental api
endpoint. Changes include:
- remove from_course_id param from next link header and Course scope
- format changed_since param in next link header to include micro-seconds
We want to add some more thorough tests that exercise larger page sizes and counts, it seems the existing tests didn't catch certain failures, but the implementation seems solid and can be reviewed independently of those tests.
We plan to make another PR to use `changed_at` instead of `updated_at`, which is required to record updates done to course enrichments.

[1043] change course incremental api to use sub-second changed_since

---

config/initializers/raven.rb

Raven is configured to ignore `ActiveRecord::RecordNotFound` errors by default.
Stop ignoring these for the purposes of reporting to Sentry.
We considered testing this but then thought it was a bit too trivial.

[1058] configure Raven not to ignore RecordNotFound errors

---

docs/api.md

`updated_at` is already inaccurate on provider and soon will be on course
Update the docs to be more future-proof on this.
Removed hand-wavy edge cases, it was a list of what we wanted to cover, but now we have some but not all so it's become just misleading.

[1052] documentation updated to remove reference to updated_at

---

app/models/concerns/with_qualifications.rb
app/models/course.rb
app/serializers/api/v2/serializable_course.rb
spec/models/concerns/with_qualifications_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb

Courses have a consistently worded description (e.g. `PGCE with QTS full time with salary`) which are used in many places in the service. 
Add a `description` attribute to the `Course` model and expose it in the Courses API V2 for frontend consumption (most immediately in the courses table in Publish).
I debated whether the course description is a presentation or a backend concern. My conclusion is that this is a backend concern because:
- it's tightly coupled to the domain
- there is only one representation of this across the entire service
- it needs to be consistent across Publish and Find and hence is part of publishing

[1087] Course description

---

app/controllers/concerns/next_link_header.rb
app/models/course.rb
app/serializers/course_serializer.rb
db/migrate/20190301114503_add_changed_at_to_course.rb
db/schema.rb
spec/controllers/api/v1/courses_controller_spec.rb
spec/factories/courses.rb
spec/models/course_spec.rb
spec/requests/api/v1/course_spec.rb
spec/serializers/course_serializer_spec.rb

Incremental fetch is live on prod for provider. This pr refactors course to be in line with provider. 
- Migration to add changed_at to the course model.
- Added monkey patch to Activerecord to ensure changed_at is updated when a course is created or updated
- Refactored scope to use changed_at rather than updated_at
- Refactored course model, controller and tests to use changed_at

1052 add changed at migration to course

---

app/models/provider_enrichment.rb
spec/models/provider_enrichment_spec.rb

Touch provider logic needs to be ported to V2 for provider enrichment
- Remove hook from the provider enrichment model
- Remove tests for hook
- Add an association test

1083 remove provider enrichment hook

---

app/controllers/api/v2/providers_controller.rb
app/models/provider.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers_spec.rb

This is the ordering that the frontend needs to display them correctly.

[1105] Return providers in alphabetical order

---

app/controllers/api/v2/sessions_controller.rb
app/controllers/application_controller.rb

Controller actions should be checking that authorisations has been performed to make sure we don't accidentally create controller actions that don't authorize.
Re-add this authorizaton verification, it was removed accidentally in #124.
Now that we-ve re-added authorizaton verification we need to explicitly skip
authorization for `SessionsController#create`.

1109 re add verify authorized

---

README.md

`users.json` returns a 404 and Tim and I found this a bit confusing.

Update authentication example to use a real endpoint

---

app/controllers/api/v1/courses_controller.rb
app/controllers/api/v1/providers_controller.rb
app/controllers/api/v1/subjects_controller.rb
app/controllers/api/v2/courses_controller.rb
app/controllers/api/v2/providers_controller.rb
app/controllers/api/v2/sessions_controller.rb
app/controllers/api/v2/users_controller.rb

Trello ticket: https://trello.com/c/AiWztw9a/1126-tests-failing-when-run-in-a-certain-order
We have more than one `ApplicationController` class:
- ::ApplicationController
- ::API::V1::ApplicationController
- ::API::V2::ApplicationController
Because of this, Rails can get confused when trying to autoload constants. For
example:
module API
module V1
class ProvidersController < ApplicationController
could pull in the wrong ApplicationController. At least, this has been the case
with RSpec tests where running the V2 specs before running the V1 specs were
causing most V1 specs to fail. This change fully quaifies ApplicationController
when used as a base class like this.

[1126] use fully-qualified ApplicationController class

---

db/schema.rb

These extensions are present in a recent pg_dump from production,
so they should be here too.
They re-appeared on my machine, seems everyone is in a different state. Realised that I'm running from a sanitized restore of prod, which brings the enabled extensions across.

Re-add pg_* extensions to schema.rb

---

app/controllers/api/v2/providers_controller.rb
spec/requests/api/v2/providers_spec.rb

Always uppercase the parameter for the database lookup as that is the canonical name.

[1127] Make provider lookup be case insensitive

---

Gemfile
Gemfile.lock
README.md
bin/mcb
lib/mcb/commands/apiv1.rb
lib/mcb/commands/apiv1/find.rb
lib/mcb/commands/provider.rb
lib/mcb/commands/provider/list.rb
lib/mcb/commands/provider/show.rb
mcb

cmdline util to help use the app db and apis
Add a cmdline helper script to perform common functions on the API. For example:
* display the data presented by the v1 api for a given provider (pages through all the data to find the provider code given)
* display data help for a provider in the db including attributes, enrichments, courses, etc
The goal is to provide access to the data and functionality in a guided way that is safer and better sign-posted than using the raw Rails console. This can be useful for people who aren't as familiar with the data, or with certain complex operations that just aren't already packaged up in the app.
This was done as a quick stab to see if it's viable and useful. We should move commands out into separate modules in `lib` or similar.

[1050] Add mcb

---

Gemfile
Gemfile.lock
app/controllers/api/v2/courses_controller.rb
app/controllers/api/v2/providers_controller.rb
app/models/provider.rb

Cleaning up find by `provider_code`
Remove `friendly_id`
`/api/v2/providers/A9/courses`
`/api/v2/providers/A9`
Check the mcf still works `/organisations`

[1145] Remove friendly_id

---

app/controllers/api/v2/application_controller.rb
spec/controllers/api/v2/application_controller_spec.rb

In line with the API design philosophy of "be permissive in what you accept and strict with what you return".
This change allows the V2 API to authenticate successfully in cases where the email address in the database (which is all lowercase by convention) doesn't match a mixed-case email coming through on the Authorization header from DfE Sign-in.

[1150] Handle user email matching case-insensitively

---

config/routes.rb
spec/requests/api/v2/providers/courses_spec.rb

Courses are unique to a provider
Nest courses within provider
Example endpoint to test `/api/v2/providers/T92/courses/X130`

[1162] nest course routes with provider

---

docs/api.md

https://trello.com/c/Flx0PnGG/1069-spec-api-for-ucas-contact-details
We need to spec out how we serve out contact detail information to UCAS in the API.
Add contacts detail information.
I couldn't help myself and added a brief description to the top, and a table of contents.
This PR is draft because we may be adding another contact type to the contacts for existing contact information which is being imported directly into the provider table.

[1069] ucas contact details api spec

---

app/serializers/provider_serializer.rb
lib/mcb/commands/apiv1/find.rb
spec/requests/api/v1/provider_spec.rb

https://trello.com/c/0HJdbyrA/1119-emit-static-contacts-data-for-ucas-api-testing
UCAS would like to have some data to illustrate how the contacts will show up in the API endpoint the will use. This adds generated contacts data that doesn't rely on us implementing the whole contacts thing.
Change the providers serialiser to generate contacts data.
Also added some extra support for contacts and to the `apiv1 find` subcommand to `mcb`. And also raw-json support.

[1119] emit static contact data

---

db/migrate/20190313153617_change_changed_at_to_unique.rb
db/schema.rb
spec/factories/courses.rb
spec/factories/providers.rb
spec/models/site_spec.rb
spec/requests/api/v1/course_spec.rb

To prevent bulk updates from breaking incremental fetch a unique constraint has been added to changed_at for provider and course.
Migration created for unique constraint implemented on changed_at column for provider
Migration created for unique constraint implemented on changed_at column for course
Changed provider factory bots default course count from 2 to 0

1045 make changed at unique

---

app/controllers/api/v2/application_controller.rb
spec/factories/users.rb
spec/requests/api/v2/providers/courses_spec.rb

We need to return a 403 Forbidden if the user hasn't accepted the terms and conditions. The frontend  can then use this to redirect them to manage-courses-ui so that they can choose  to accept.
Refactors the email retrieval logic and then adds the check for the `accept_terms_date_utc` field.
~Not sure if this is where this bit of logic should go; I've thought about creating another `before_action` but then I need to get the token again, which is cumbersome. It's easier to insert the new logic into this existing check.~

[1165] Check for accept_terms_date_utc on every request

---

app/models/concerns/touch_course.rb
app/models/site_status.rb
spec/models/site_status_spec.rb
spec/requests/api/v1/course_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/touch_course_spec.rb

Course changed_at is updated when updating site status
Added ability to update change at for course when site statuses changes.
This is done via a reusable concern, through a call back.

[1131] Update course changed_at when updating site status

---

app/models/provider_ucas_preference.rb
app/serializers/provider_serializer.rb
spec/factories/provider_ucas_preferences.rb
spec/factories/providers.rb
spec/factory_specs/provider_ucas_preferences_spec.rb
spec/models/provider_ucas_preference_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

https://trello.com/c/kezSZblP/1173-provider-preferences-serialiser
We need to expose the provider preferences that are in the DB in the V1 API, right now they are being semi-randomly chosen.
This change pulls these values from the DB in the serialiser, and fixes a bunch of related tests.

[1173] add ucas preferences serialiser

---

app/controllers/api/v2/site_statuses_controller.rb
app/policies/site_status_policy.rb
config/routes.rb
spec/factories/courses.rb
spec/factories/providers.rb
spec/factories/site_statuses.rb
spec/policies/site_status_policy_spec.rb
spec/requests/api/v2/site_statuses_spec.rb

The API needs to have an endpoint for the frontend to update vacancy statuses. This is done via the site status, which now has an endpoint to update any of its attributes.
An update endpoint on `SiteStatus` that takes an HTTP PATCH request with any attributes to update.
Please take a look at the specs, there is a lot of setup required there for creating organisations, providers, and users. It might be a good idea to clean that up by making the setup reusable, as a precursor to this PR?

[1131] API endpoint for updating vacancy status

---

app/controllers/api/v1/courses_controller.rb
app/controllers/api/v1/providers_controller.rb
spec/controllers/api/v1/courses_controller_spec.rb
spec/controllers/api/v1/providers_controller_spec.rb

UCAS are expecting to see no data returned for future recruitment years. This is a reasonable expectation until the API can handle courses from multiple cycles.
https://trello.com/c/D9OBiECj/1025-ensure-recruitmentcycle-2020-endpoints-are-returning-empty-data-sets
Return a hardcoded empty list when the recruitment year isn't 2019.
This is a temporary state of affairs until rollover and multi-year courses are supported.

[1025] Don't return 2020 data through the V1 API yet

---

app/serializers/contact_serializer.rb
app/serializers/provider_serializer.rb
spec/factories/contacts.rb
spec/requests/api/v1/provider_spec.rb
spec/serializers/contact_serializer_spec.rb
spec/serializers/provider_serializer_spec.rb

We need to expose the provider contacts/application alert recipient  in the V1 API.
- Attributes added to the contact factory bot
- Creates a contact serialiser 
- Removes dummy data logic from the provider serializer
- Adds application alert recipient as an attribute to the provider serialiser
- Adds contacts as an attribute to the alert serialiser
Application alert recipient is an anomalous contact as it is simply an email address that is contacted on application receipt. Due to this it has been added a column by UCAS preferences model and is exposed in the api via adding it manually to the Provider Serialiser contacts attribute.
Lines 38-43 of provider serialiser (see bold)
attribute :contacts do
object.contacts.map { |c| c.attributes.slice('type', 'name', 'email', 'telephone') } + …

1179 add provider contact serializer

---

azure/template.json

This gives manage-courses-backend the information it needs to trigger course republishing on manage-courses-api.
Terraform prior art: https://github.com/DFE-Digital/bat-infrastructure/pull/119
I don't understand VSTS very well so don't know if adding this without going and poking the interface to define values for `settingsManageApiBaseUrl` and `settingsManageApiSecret` will cause everything to break.

[1133] Add env vars for course republishing to VSTS

---

config/initializers/jsonapi.rb

This was introduced with the 0.3.1 -> 0.4.0 bump (++git bisect).
Since updating `jsonapi-rails` from 0.3.1 -> 0.4.0, logging has been added and enabled for all environments.
```
.I, [2019-03-26T21:47:55.947742 #80214]  INFO -- : Completed JSON API rendering (31.21ms)
.I, [2019-03-26T21:47:55.987199 #80214]  INFO -- : Completed JSON API rendering (3.02ms)
.I, [2019-03-26T21:47:56.035756 #80214]  INFO -- : Completed JSON API rendering (4.55ms)
.I, [2019-03-26T21:47:56.084163 #80214]  INFO -- : Completed JSON API rendering (3.23ms)
.I, [2019-03-26T21:47:56.176322 #80214]  INFO -- : Completed JSON API rendering (5.1ms)
.I, [2019-03-26T21:47:56.211181 #80214]  INFO -- : Completed JSON API rendering (2.33ms)
.I, [2019-03-26T21:47:56.264898 #80214]  INFO -- : Completed JSON API rendering …
```

quiet down jsonapi-rails' logging

---

app/serializers/provider_serializer.rb
spec/serializers/provider_serializer_spec.rb

The serialiser shouldn't fall over if the UCAS preferences aren't set for
some reason (they should be, theoretically, but it's impossible to guarantee this
given the state of the existing data).
Guard against missing UCAS preferences.

[1173] Make the provider serialiser more resilient

---

spec/serializers/contact_serializer_spec.rb

The contact serialiser was missing an annotation.
Added missing annotation, generated by `rake`.

Add missing annotation

---

app/models/provider.rb
app/serializers/provider_serializer.rb
spec/models/provider_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

We have been conflating the external, candidate-facing contact (that's the
data on the enrichment) with the admin/back-office contact that DfE/UCAS use
to get in touch with the provider.
This change separates the two pieces of data; from now on, the Provider API V1
will use the provider contact details that are on the Provider record.
So much red.

[1180] Don't use enrichments to generate provider admin contacts

---

lib/mcb/commands/apiv2.rb
lib/mcb/commands/apiv2/token.rb
lib/mcb/commands/apiv2/token/generate.rb

Generating JWT tokens is a bit of a pain
Add an `mcb` command which helps generate tokens.

[1212] Add mcb command to generate JWT tokens

---

app/serializers/provider_serializer.rb
spec/factories/providers.rb
spec/serializers/provider_serializer_spec.rb

https://trello.com/c/WRv7HyW0/1181-provider-contacts-use-table-for-admin-contact-with-fallback
To facilitate the gradual transition of providers to the separation of front-office contacts (for candidates) and back-office admin contact (for UCAS), we want to support either retrieving the admin contact from the provider record (our old model) or retrieving the admin contact from the contacts table (the new model).
When serialising the provider use the admin contact from the provider record if present.

[1181] use admin contact in provider record if not in contacts table

---

.travis.yml
Gemfile
Gemfile.lock
README.md
azure-pipelines.yml
lib/tasks/govuk_lint.rake

GOV.UK Lint is being deperacated, this is the new way of using it.
GOV.UK Lint is being deprecated, it's recommended to be used in this way instead.
I haven left the SCSS listing in there, they recommend using node based tooling for that instead.
Switch from govuk-lint-ruby to Rubocop configured to use govuk-lint's rules.

Switch to Rubocop for linting Ruby

---

docs/api.md

Contact type values don't match what's documented in https://github.com/DFE-Digital/manage-courses-backend/blob/master/docs/api.md
Documentation now matches the type enum values in `app/models/contact.rb`.
The spec change was agreed with UCAS.

Update contact types in API spec

---

app/controllers/api/v2/courses_controller.rb
app/policies/course_policy.rb
app/services/manage_courses_api.rb
config/routes.rb
spec/factories/apiv2_token.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/services/manage_courses_api_spec.rb

When a course is updated, e.g. vacancy statuses are changed, it needs to be pushed out to the `search_and_compare` system.
Implement an API endpoint that can be used to trigger the syncing of a course to `search_and_compare`.

[1160] publish course

---

app/models/provider_enrichment.rb

Since 40a4577, this scope is not longer used anywhere.

[1180] Remove redundant scope

---

app/services/manage_courses_api.rb
spec/services/manage_courses_api_spec.rb

Without this fix, Faraday throws an exception:
```
NoMethodError: undefined method `bytesize' for {:email=>"xxxx"}:Hash
```
According to https://github.com/lostisland/faraday/issues/726, we should be calling
a `to_json` on the body.

[1160] Fix how Faraday is used

---

app/models/course.rb
app/models/course_enrichment.rb
app/serializers/api/v2/serializable_course.rb
spec/factories/course_enrichments.rb
spec/factories/courses.rb
spec/factory_specs/course_enrichment_spec.rb
spec/factory_specs/course_spec.rb
spec/models/course_enrichment_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

The course enrichment status is shown to publishers in the course table
Add `content_status` to Course API V2.
This does a query per-course, which means N+1 queries on the courses table. We may need to consider performance going forward.

[1216] Add content status

---

app/controllers/api/v2/providers_controller.rb
app/serializers/api/v2/serializable_provider.rb
spec/requests/api/v2/providers_spec.rb

Training locations.
We need to expose `sites` on the provider#show endpoint in order to allow users access to update the `sites` aka training locations
- Optionally include `sites` on provider#show endpoint
Example url to test `localhost:3001/api/v2/providers/A9?include=sites`

[1234] optionally include sites with provider show endpoint

---

app/serializers/api/v2/serializable_provider.rb
spec/requests/api/v2/providers_spec.rb

We need to know if a provider is opted in to display different functionality for users on the frontend
Expose opted in attribute to providers endpoint

Expose opted in providers

---

app/controllers/api/v2/courses_controller.rb
app/serializers/api/v2/serializable_course.rb

This will be used to fetch accrediting providers in the frontend.
Also reverse the has_one to belongs_to on the serializable_course, because that's more logical.

1210] Allow include parameter on courses index lookup

---

azure/template.json

Second part to transitioning to ucas rails env environment, this env var in the template is causing errors on deploys in VSTS

[1256] remove manage api base url from azure template

---

app/serializers/api/v2/serializable_provider.rb
spec/requests/api/v2/providers_spec.rb
spec/serializers/api/v2/serializable_provider_spec.rb

The frontend is wired up to use `provider_code` to connect courses and providers, but the backend was returning an `institution_code` instead of a `provider_code`.
Provider resources now have a `provider_code` instead of an `institution_code`.
Frontend PR https://github.com/DFE-Digital/manage-courses-frontend/pull/154

[1259] Rename institution_code to provider_code

---

app/controllers/api/v2/courses_controller.rb
spec/factories/courses.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

We need to expose `provider` and `accrediting_provider` on the course endpoint.
Rather than hard coding the course endpoint to return `site_statuses` and `sites`, we now rely on the `include` parameter.
Added a bunch of tests for the serializer to make sure we can render out everything we need.
I originally included a request spec in this that brings in provider and accredited_provider, but decided it was overkill in the end.

[1259] Expose provider in courses

---

lib/mcb.rb
lib/mcb/azure.rb
lib/mcb/commands/az/apps/config.rb
lib/mcb/commands/az/apps/psql.rb
lib/mcb/commands/providers.rb
lib/mcb/commands/providers/list.rb
lib/mcb/commands/providers/show.rb
lib/mcb/commands/providers/ucas_preferences/import.rb
lib/mcb/commands/providers/ucas_preferences/show.rb
spec/lib/mcb/azure_spec.rb
spec/lib/mcb/commands/providers/ucas_preferences/import_spec.rb
spec/lib/mcb/providers_spec.rb
spec/lib/providers_spec.rb
spec/support/with_stubbed_stdout.rb

When running against a remote app's db there is always the possibility that an unexpected result would be had should the wrong environment be targeted.
Require the user to enter in the correct `RAILS_ENV` for the application that is being targeted.

[1205] request confirmation when running against Azure app

---

app/controllers/api/v2/sites_controller.rb
app/policies/provider_policy.rb
app/policies/site_policy.rb
app/serializers/api/v2/serializable_site.rb
config/routes.rb
spec/factories/sites.rb
spec/policies/site_policy_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/serializers/api/v2/serializable_site_spec.rb

sites aka training locations
- Add address data to sites serializer
- Setup `sites#index` and `sites#show`
e.g. `http://localhost:3001/api/v2/providers/T92?include=sites`
```ruby
{
"id": "10324702",
"type": "sites",
"attributes": {
"code": "O",
"location_name": "Oakthorpe Primary School",
"address1": "Tile Kiln Lane",
"address2": "",
"address3": "",
"address4": "",
"postcode": "N13 6BY",
"region_code": "london"
}
}
```

[1266] add address to sites serializer

---

app/serializers/api/v2/serializable_provider.rb
spec/requests/api/v2/providers_spec.rb

The frontend is wired up to use `provider_name` to connect courses and providers, but the backend was returning an `institution_name` instead of a `provider_name`.
Provider resources now have a `provider_name` instead of an `institution_name`.
Frontend PR to follow

[1260] Rename institution_name to provider_name

---

app/models/course.rb
spec/models/course_spec.rb

Course vacancy logic currently looks at suspended and discontinued sites.
Fix the above, and make some spec improvements.

[1276] Vacancies should be derived only from open sites

---

Gemfile
Gemfile.lock
app/controllers/api/v2/sites_controller.rb
app/models/concerns/postcode_normalize.rb
app/models/site.rb
app/validators/postcode_validator.rb
config/routes.rb
spec/models/concerns/postcode_normalize_spec.rb
spec/models/site_spec.rb
spec/rails_helper.rb
spec/requests/api/v1/provider_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/validators/postcode_validator_spec.rb

Provider needs to be able to update site information.
And update endpoint for sites that allows updating all attributes, except `code`.

[1265] Endpoint for updating sites

---

app/services/manage_courses_api.rb
spec/services/manage_courses_api_spec.rb

https://github.com/DFE-Digital/manage-courses-api/blob/1e84f8b42e4b365e43fef0109ddbd34efc747b21/src/ManageCourses.Api/Controllers/PublishController.cs#L76
Fixed publishing courses typo in endpoint (there should be a `s` for course)

[1288] Fixed publishing courses typo in endpoint

---

app/controllers/api/v2/sites_controller.rb
spec/requests/api/v2/providers/sites_spec.rb

Courses should be published to find when we edit a site.
Call the service to publish the course once a site has been successfully edited.
We don't care if this fails, so we silently handle it.

[1289] Publish course when location is edited

---

Gemfile
Gemfile.lock
app/models/contact.rb
app/models/course.rb
app/models/provider.rb
app/models/site.rb
app/models/site_status.rb
db/migrate/20190409230916_install_audited.rb
db/schema.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/models/site_spec.rb
spec/models/site_status_spec.rb
spec/spec_helper.rb

https://trello.com/c/exkrR2wQ/1279-add-auditing
We need to have some kind of auditing tool so that we can see what's changing on providers.
Add the `audited` gem and enable auditing for `providers` and `contacts`.

[1279] add audited for providers and contacts

---

lib/mcb/commands/providers/optin.rb
lib/mcb/commands/providers/optout.rb
spec/lib/mcb/commands/providers/optin_spec.rb
spec/lib/mcb/commands/providers/optout_spec.rb

We want to have a convenient method to optin/optout providers to the DfE find platform.
Add the mcb commands:
```
mcb provider optin <provider_code>
mcb provider optout <provider_code>
```
We need to start opting in tomorrow morning. Just sayin'.

[1281] add mcb provider opt in

---

spec/factories/provider_enrichments.rb
spec/factories/providers.rb
spec/factories/sites.rb
spec/serializers/provider_serializer_spec.rb
spec/serializers/site_serializer_spec.rb

The factories were calling a region_code method on the provider enrichment model with `ProviderEnrichment.region_code['London']`. As it was returning `nil` the serialiser tests were still passing. 
The provider factory has a default site count of 1. This causes factory bot issues that don't occur on live.
When the provider serialiser attempts to build the course it cannot convert the enum key ie. london into an integer.
This bug only affects our tests and not live.
- Changes the factories to generate region code by the enum key ie. london, eastern etc.
- Alters the providers in the provider serialiser spec to have `site_count 0` allowing serialisation without errors occurring 
Bit more context.
In the console 
`s = Site.create(region_code: 1)`
`p = Provider.create(site: [s])` …

[1272] fix region codes in factories

---

config/settings/production.yml

As part of the work of using Settings instead of envvars for non-secret settings,
bring the settings file in line with the environment variable value.

[1223] Workaround for missing DNS entry

---

spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

#272 inadvertently introduced filtering to the spec suite which meant only 3 specs were running after it was merged:
This was also obscuring some failing specs.
- remove the filtering
- fix the failures

[1314] reenable and fix specs

---

spec/factories/courses.rb

This keeps the cryptic codes consigned to the model enum.

[1314] Switch factory to use more readable values

---

app/controllers/api/v2/users_controller.rb
app/models/user.rb
app/policies/user_policy.rb
app/serializers/api/v2/serializable_user.rb
config/routes.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/requests/api/v2/session_spec.rb
spec/requests/api/v2/users_spec.rb

In readiness for the transition screen (and t&c's) that will require a user to "update" their record.
- Add `users#update` controller action
Testing "time" is hard so had to remove the json match and check for individual attributes. Then using the `be_within` matcher is impossible to test when the json output is a string 🤷‍♂️ 
Open to feedback/suggestions..

[1247] add update endpoint to user

---

app/serializers/api/v2/serializable_course.rb
spec/factories/subjects.rb
spec/factory_specs/subject_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

Send field
Added bool to denote is a course a Sen/Send course
retained the naming of `Sen` vs `Send` this is partly due to original naming as well as `Send` is an acronym and an actual word.
subject_code is hardcoded as it was from 
https://github.com/DFE-Digital/manage-courses-api/blob/e5c4f2a6ebe3644e322c4ff71d65ce7e83b3e403/src/ManageCourses.Domain/Models/Course.cs#L37

[1322] Added send field on course serializer

---

app/services/subject_mapper.rb
spec/services/subject_mapper_spec.rb

The `SubjectMapper` is difficult to understand and reason about.
- extract `*Mapping` classes for particularly gnarly bits of logic so they're a lot more encapsulated
- bring the code closer to common ruby conventions (it started its life as C#)

[1269] Simplify subject mapper

---

app/serializers/api/v2/serializable_course.rb
app/services/subject_mapper.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

Course level can only be really one of 3, `primary`, `secondary` and `further education`
Added course level derived from course subject and/or course title

[1327] Added level to the course serializer

---

app/models/course_enrichment.rb
app/serializers/api/v2/serializable_course.rb
spec/README.md
spec/factories/course_enrichments.rb
spec/factories/courses.rb
spec/factories/providers.rb
spec/factories/site_statuses.rb
spec/factories/subjects.rb
spec/models/course_enrichment_spec.rb
spec/rails_helper.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/strategies/find_or_create_strategy.rb

https://trello.com/c/1wLgwBkl/1307-expose-latest-enrichment-on-the-course-api-v2
The course details page needs the course enrichments data.
Add course enrichments to the course attributes on the API V2 endpoint.
This commit is a bit big, but there was much flailing about with the specs and
factories .... we need a separate card to actually fix this all up.
The file `spec/README.md` isn't quite complete, but I thought it was worth including in it's rough state and the new ticket to clean up the factories should include fixing up that REAMDE.

[1307] add course enrichments to the api v2 courses endpoint

---

lib/mcb/commands/providers/optin.rb
spec/lib/mcb/commands/providers/optin_spec.rb

After transition, a bunch (50+) courses will have a UCAS status 'new' but content status of 'published'. This state inconsistency has arisen because pre-transition, these steps were carried out on separate systems.
Since the "publish" button only appears on courses that are in "draft" or "published with unpublished changes" states, these aforementioned courses won't have a publish button, meaning it's not obvious how to publish them.
When 'mcb provider optin' is run, it unpublishes the content enrichments for any course that's in the 'new' with 'published' enrichments state.

[1345] Set enrichments as draft for new courses when opting in

---

app/models/course_enrichment.rb
lib/mcb/commands/providers/optin.rb
spec/lib/mcb/commands/providers/optin_spec.rb
spec/lib/mcb/commands/providers/ucas_preferences/import_spec.rb
spec/models/course_enrichment_spec.rb

When we opt in providers that have a course that is new in UCAS, we mark all of the enrichments as draft. We only want to mark the latest enrichment as draft, if it's published.
- Only latest enrichment gets marked as draft, not all of them
- Some text is output to the screen to indicate what happened
There's a failing test, will fix tomorrow. I have no idea why it fails. :(

[1351] Only mark latest enrichment as draft

---

app/models/user.rb
app/serializers/api/v2/serializable_user.rb
spec/factories/users.rb
spec/models/user_spec.rb
spec/requests/api/v2/users_spec.rb

Is a user "opted_in" i.e. do they have access to any providers that are opted_in?
Expose user#opted_in? 
Example - `http://localhost:3001/api/v2/users/10345`

[1355] include opted in attr on user endpoint

---

app/controllers/api/v2/application_controller.rb

We are getting sporadic Pundit::NotAuthorisedError. This change tries to up our visibility to try to understand the cause.
Add the id for the current user to the Raven user context.
Wasn't sure this change was worth testing, the rest of the tests should (hopefully) ensure we don't break anything.

[1358] add current user id to Raven user context for Sentry

---

lib/mcb/commands/providers/optin.rb
spec/lib/mcb/commands/providers/optin_spec.rb

`optin` command was blowing up when processing new courses without enrichments.

[1345] optin mcb command handles new courses without enrichments

---

app/models/course_enrichment.rb
lib/mcb/commands/providers/optin.rb
spec/lib/mcb/commands/providers/optin_spec.rb
spec/models/course_enrichment_spec.rb

There are two flavours of draft, it's appropriate for optin to set published
enrichments for new courses back to initial draft.
- encapsulate unpublishing on the `CourseEnrichment` model
- `optin` should unpublish back to initial draft

[1345] optin should unpublish to initial draft

---

app/controllers/api/v2/courses_controller.rb
app/controllers/api/v2/sites_controller.rb
app/serializers/api/v2/serializable_course.rb
app/services/manage_courses_api_service.rb
app/services/subject_mapper_service.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/services/manage_courses_api_service_spec.rb
spec/services/subject_mapper_service_spec.rb

It's confusing af to not have this as only models in Rails don't have a suffix. 🤔 
All service classes are now renamed to end with `Service`.

Rename service classes to have Service suffix

---

app/models/course.rb
app/serializers/api/v2/serializable_course.rb
spec/requests/api/v2/providers/courses_spec.rb

Course last published date
Expose `last_published_at` for courses which is the `last_published_timestamp_utc` value from the latest `course_enrichment`.
Example - http://localhost:3001/api/v2/providers/2AT/courses/35L8

[1255] expose course changed at

---

spec/services/subject-mapper-test-data.csv
spec/services/subject_mapper_service_spec.rb

The prod-data subject mapping spec ensures that the subject mapping in this app behaves in the same way as the C# version that does the actual subject mapping between Publish and Find.
This PR aims to improve both the spec code, as well as making the CSV data more useful on its own, without losing any test coverage in the process.
- Improve the prod data CSV:
- for each row, sort the input UCAS subjects and the expected DfE subjects alphabetically, which allows to de-duplicate the file (that's where the large number of deletions has come from)
- do away with the custom delimiter within the CSV cells to make the doc easier to scan
- sort the CSV alphabetically to make it easier to scan
- process the CSV file a bit more concisely in the spec's Ruby code, making it a bit easier to parse …

[1269] Improvements to the subjects prod-data spec

---

config/settings/development.yml
lib/mcb.rb
lib/mcb/commands/apiv2/token/generate.rb
spec/lib/mcb/commands/apiv2/token/generate_spec.rb
spec/lib/mcb_spec.rb

Previously we handled authentication without JWT decoding on the backend when running in development.
If you need to create a secret for some reason, then there's an mcb command for that.
Now it works the same as prod, with the secret set to `secret`.
Also removed the MCB command option for plain-text tokens.
Tested on Mac OS Mojave (10.14.4)
Frontend still needs updating for this to work.

[1337] Make development authentication consistent with production

---

README.md

APIv2 authentication changed in development and the README instructions didn't reflect that.
Updated APIv2 authentication instructions to show how to use the MCB command to generate a JWT token and pass it to the backend.

[1337] Update APIv2 authentication instructions

---

config/initializers/raven.rb

The parameters we filter out for sensitive information in logs, etc. isn't respected by Sentry.
Make Sentry filter out the same attributes as Rails does.
Need to test if this actually works.

[1354] Remove sensitive information from Sentry

---

spec/services/subject_mapper_service_spec.rb

The subject specs were ported from the C# version. These weren't written in a Rails house style, and also didn't specify the subject level (primary, secondary, etc).
- introduce a custom matcher to bring the specs closer to Rails house style
- add extra coverage by specifying the expected subject level
This follows up on #305 and #282. I aim to raise more clean-up PRs later, this change is focussed on re-engineering the specs.

[1269] Make subject specs more readable with a custom matcher

---

Guardfile

Stop linter errors when running `guard`.
```bash
$ bundle exec rubocop app config db lib spec Guardfile Gemfile --format clang
[Warn] Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.
https://github.com/rubocop-hq/rubocop/tree/master/manual/migrate_performance_cops.md
Guardfile:28:1: W: Lint/UnneededCopDisableDirective: Unnecessary disabling of Metrics/BlockLength.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
222 files inspected, 1 offense detected
```
```bash
$ bundle exec rubocop app config db lib spec Guardfile Gemfile --format clang
[Warn] Performance Cops will be removed from RuboCop 0.68. Use rubocop-performance gem instead.
https://github.com/rubocop-hq/rubocop/tree/master/manual/migrate_performance_cops.md
222 files inspected, no offenses detected …
```

[1400] Remove unnecessary disabling of Metrics/BlockLength in Guardfile

---

app/models/course.rb
app/models/subject.rb
app/serializers/api/v2/serializable_course.rb
spec/models/course_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

The `Course` model will be called from `mcb` in order to build and create new courses.
- pull subject-related logic (`dfe_subjects`, `level` and `is_send?`) into model code out of the serializer, so it can be reused
- add a validation for course codes to reduce the risk of duplicates being added

[1407] Course model improvements

---

lib/mcb.rb
spec/lib/mcb/commands/apiv2/token/generate_spec.rb
spec/lib/mcb_spec.rb

Local testing shows that auth fails when the email is wrapped in json
syntax, but the bare email address gets through to the next stage
(terms not accepted).

Don't jsonify the JWT payload in mcb

---

bin/mcb
lib/mcb.rb
lib/mcb/commands/config.rb
lib/mcb/commands/config/set.rb
lib/mcb/commands/config/show.rb
lib/mcb/config.rb
spec/bin/mcb_spec.rb
spec/lib/mcb/azure_spec.rb
spec/lib/mcb/commands/apiv1/token/show_spec.rb
spec/lib/mcb/commands/apiv2/token/generate_spec.rb
spec/lib/mcb/commands/az/apps/config_spec.rb
spec/lib/mcb/commands/az/apps/list_spec.rb
spec/lib/mcb/commands/config/set_spec.rb
spec/lib/mcb/commands/providers/optin_spec.rb
spec/lib/mcb/commands/providers/optout_spec.rb
spec/lib/mcb/config_spec.rb
spec/lib/mcb/providers_spec.rb
spec/lib/mcb_spec.rb
spec/mcb_helper.rb

https://trello.com/c/11v4CXhF/1346-mcb-provider-optin-should-audit-which-user-ran-the-command
When admins make changes via `mcb` we want to ensure there is an audit trail for who did the changes. This also requires some kind of a config system to keep track of the admin's email address, and which will also be useful for future features.
This PR introduces a config mechanism that will be used in a near-future PR to add the audit stuff. It also does a little bit of specs tidying up that fell out of the work of adding the config stuff.
Config mechanism has it's own PR since it's grown a bit big. Another PR for auditing system to follow later.

[1346] add mcb config system

---

Gemfile
Gemfile.lock
lib/mcb.rb
lib/mcb/commands/providers/audit.rb
spec/lib/mcb_spec.rb

https://trello.com/c/11v4CXhF/1346-mcb-provider-optin-should-audit-which-user-ran-the-command
When an admin makes changes to a remote system they should be added to the audit trail as the user that performed the change.
Record the user making changes when connecting to a remote system.
This work is built off of the PR to add a configuration system (#319) which should be merged before this one is.
The gem `tabulo` has been added in addition to the 2 other table-printing gems. At least `table_print` should be superceded by this eventually, if not both of the table-printing gems.

[1346] add user to audit info

---

bin/mcb
lib/mcb/commands/providers/show.rb
lib/mcb/course_show.rb

`mcb` output for complex records (e.g. courses) can be hard to parse visually.
Add an explicit renderer for courses, that can be reused across multiple `mcb` commands.
```sh
UCAS Preferences:
no preferences found
Provider Enrichments:
No data.
Provider Courses:
id | age_range | course_code | name          | profpost_flag             | program_type                   | qualification | start_date              | study_mode | accrediting_provider_id | provider_id | modular | english | maths | science | created_at              | updated_at              | changed_at
---|-----------|-------------|---------------|---------------------------|--------------------------------|---------------|-------------------------|------------|-------------------------|-------------|---------|---------|-------|---- …
```

[1407] Course preview flag for 'mcb providers show'

---

app/services/access_request_approval_service.rb
spec/services/access_request_approval_service_spec.rb

Only add new orgs to the target user. This comes up in production because publishers lodge duplicate access requests that get approved.
- fix unit test that was obscuring the issue
- fix issue

[1362] Access requests shouldn't duplicate orgs for a user

---

app/controllers/api/v2/application_controller.rb
spec/requests/api/v2/application_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/providers/sites_spec.rb

Backend API doesn't handle 404s gracefully.
Rescue from `ActiveRecord::RecordNotFound` and show an empty JSONAPI response with an HTTP status of 404.

[1431] Handle not found errors

---

app/services/access_request_approval_service.rb
spec/services/access_request_approval_service_spec.rb

Access requests contain email addresses typed in by publishers. They can contain mixed case letters. Our database assumes that all emails in it are lower case.
The functionality for approving the access requests currently:
- doesn't match emails case-insensitively
- inserts email addresses with upper-case letters
The knock-on effects are:
- duplicate user records
- users not being able to log in
- lowercase the recipient email from the access request
- add specs for this case

[1432] Handle access requests with mixed-case recipient addresses

---

Dockerfile
Gemfile
Gemfile.lock
app/models/course.rb
app/validators/postcode_validator.rb
app/validators/words_count_validator.rb
config/locales/en.yml
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/validators/words_count_validator_spec.rb

This removes part of the work that the frontend has to do to display validation errors.
Add `custom_error_message` as a dependency. It allows us to prefix error messages with `^` when they should not use the attribute as a prefix for the full_message.
This modifies the `course#validate_enrichment` method. Before, all enrichment errors would be hoisted under the `latest_enrichment` key. This isn't enough information to be able to determine which field this error belongs to. The new key is computed as `latest_enrichment__FIELD`.
Updated tests and adds better validation messages for course enrichments and sites via `en.yml` overrides.
I really tried to find a way to do this without `custom_error_message` which is a very dirty monkey patch of an unmaintained library, but I couldn't due to the …

[1406] Improve course enrichment and site validation errors

---

app/models/course_enrichment.rb
spec/models/course_enrichment_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb

Courses are not being sent to "find" because are "publish" validation rules don't match with the current implementation in the UI.
Remove numerical validation from fees since this is handled by the input itself at present (not ideal) and the current behavior of our c# implementation

[1422] Don't validate numericality for fees

---

app/models/provider.rb
app/serializers/provider_serializer.rb
db/migrate/20190507150812_remove_opted_in_from_provider.rb
db/schema.rb
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

All providers are now opted in
Remove `opted_in` column from the provider table
`rails db:migrate`

[1417] remove opted_in from provider

---

app/services/authentication_service.rb
app/services/authentication_service/duplicate_user_error.rb
spec/services/authentication_service_spec.rb

The database constraint for email uniqeness on users causes ActiveRecord
to raise an error whenever we try to update the email to one that
already exists.
This happens for some users that have a DfE-SignIn ID on a user record
with an email address different from the one that we get from
DfE-SignIn, and the email from DfE-SignIn matches another record.
When we look up the user by the ID and the email doesn't match the
user's email, we want to update their email to the one we get from
DfE-SignIn.
Sometimes though, there's already another user on the system with the
same email, so we get an error. Instead of just not updating and moving
on with authenticatation, we want to send an exception to Sentry with
the details of the users.
This allows us to start collecting some data about the users …

[1413] Fix email already in use error during user sign in

---

app/controllers/api/v2/access_requests_controller.rb
app/models/access_request.rb
app/policies/access_request_policy.rb
app/serializers/api/v2/serializable_access_request.rb
config/routes.rb
spec/factories/access_requests.rb
spec/models/access_request_spec.rb
spec/policies/access_request_policy_spec.rb
spec/requests/api/v2/access_request_spec.rb
spec/serializers/api/v2/serializable_access_request_spec.rb

MC support currently hits the db directly for to list the access requests.  This pr creates an endpoint on MCBE for the support app to hit instead
- endpoint created
- list of 'requested' access requests returned when endpoint is hit
The support app still needs to be refactored to hit the mcbe endpoint.

1364 Expose list of access requests in mcbe to mc support

---

lib/mcb/commands/providers/sync_to_find.rb
spec/lib/mcb/commands/providers/sync_to_find_spec.rb

Tech support needs to help providers with course and training location editing because not all that functionality is available as self-serve.
When tech support makes several changes to courses of a particular provider and wants to update Find, they don't want to do it through Publish.
Add an `mcb` task.

[1407] Add mcb command to sync all of a provider's courses to Find

---

db/seeds.rb

Once you've actioned one it's gone, so useful to have more for testing.
Cleaner code suggestions would be appreciated.

[1363] Add more access_request records when seeding

---

lib/mcb/commands/courses.rb
lib/mcb/commands/courses/sync_to_find.rb
spec/lib/mcb/commands/courses/sync_to_find_spec.rb

Similar to #347.
Tech support needs to help providers with course and training location editing because not all that functionality is available as self-serve.
When tech support changes a particular course and wants to push it to Find, they'd rather do it on the command line rather than through Publish.
Add an mcb task to sync a single course to Find.

[1407] Add mcb command to sync a particular course to Find

---

app/models/course_enrichment.rb
spec/factories/course_enrichments.rb
spec/models/course_enrichment_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb

Validation for 
`qualification`
`about_course`
`how_school_placements_work`
Added validation for 
`qualification`,  (presence & word count)
`about_course` (presence)
`how_school_placements_work` (presence)
Split the tests to smaller chucks for lack presence and exceed word count vs only invalid content

1310 fixed missing validations for pub

---

lib/mcb/azure.rb
spec/lib/mcb/azure_spec.rb
spec/lib/mcb/commands/az/apps/config_spec.rb

When attempting to run `mcb` on windows, spaces in the subscription name were tripping the command up on Windows.

[1407] Fix mcb azure integration on Windows

---

app/models/provider.rb
app/models/site.rb
spec/factories/sites.rb
spec/models/provider_spec.rb
spec/models/site_spec.rb
spec/requests/api/v2/providers/sites_spec.rb

The UCAS Apply system uses training location codes and so each training location assigned to a provider needs one. There's a maximum of 37 single-character codes per provider: `0-9`, `A-Z`, `-`
When a provider creates a new location:
- we need to assign that location a valid campus code
- we should also validate that the code is one that will be accepted downstream
- we want to assign easily-confused codes last
- `Site` model sets `code` value by default
- active record validations added

[1469] Training location code: validations and automatic assignment

---

Gemfile
Gemfile.lock
README.md
bin/mcb

It's getting harder to find where a command is given the depth and
number of things. Run `bin/mcb -v -h` to see the full list.

Add help for all subcommands with `-v -h`

---

app/models/course.rb
app/models/site.rb
app/models/site_status.rb
spec/models/course_spec.rb
spec/models/site_spec.rb
spec/models/site_status_spec.rb

These are various model methods that are used by the forthcoming new MCB scripts.
This allows us to toggle sites on courses through MCB as well as present different kinds of data, such as the potential sites that can be attached to a course.
Implements the new methods, alongside tests.
Easiest reviewed commit by commit.
I have not ticked the "Cleaned commit history" because I don't know if I should add more context to the existing 6 commits, or squash them into one. They all do one small method each which I find pleasing but maybe not all reviewers agree.

[1472] Add course.toggle_site method, and more

---

README.md
bin/mcb

Having slept on it I realise the final output isn't that long anyway.
When I did the -v thing I was imagining showing the full help for every
subcommand.
See #360 for screenshot

Always show subcommands in help

---

app/models/course.rb
spec/models/course_spec.rb

The status of a course influences the `add_site!` logic whereby added sites shouldn't be set to running automatically.
Courses without any training locations should have a status of `new`.

[1407] Courses without any training locations should have 'new' status

---

lib/mcb.rb
lib/mcb/commands/users.rb
lib/mcb/commands/users/audit.rb
lib/mcb/commands/users/list.rb
lib/mcb/commands/users/show.rb
spec/lib/mcb/commands/users/audit_spec.rb
spec/lib/mcb/commands/users/list_spec.rb
spec/lib/mcb/commands/users/show_spec.rb
spec/support/matchers/have_text_table_row.rb

When debugging production problems it's handy to be able to view the user info in production without having to make a db connection.
Add commands to mcb:
- `mcb user list`
- `mcb user show <id>`
- `mcb user audit <id>`
Not sure why CodeClimate is failing, ignoring for now.

[1470] add mcb user show

---

lib/mcb/commands/users/audit.rb
spec/lib/mcb/commands/users/audit_spec.rb

This was done for `mcb user show` and `mcb user list` in a previous PR, but forgot to do it with `audit`.
Allow users to be specified by email address or sign-in user id with the `mcb user audit` command.

[1470] allow mcb user audit to use email or sign-in id

---

azure-pipelines.yml

Some tasks were reporting the dockerHubUsername variable was not set
Add env var for this value

Add env username

---

app/models/course.rb
spec/models/course_spec.rb

If a publisher adds and then removes a training location on a course
before course is published, they wouldn't expect it to come back once
they've set the course to running.
To achieve this, we need to delete the site status, but only when the
course is new. If it's being removed post-publication, it should be suspended
as before.

[1472] Delete site status when removing site for new courses

---

app/controllers/api/v2/access_requests_controller.rb
app/policies/access_request_policy.rb
config/routes.rb
spec/policies/access_request_policy_spec.rb
spec/requests/api/v2/access_request_spec.rb

* C# based manual access request creation in the support console is broken
* Add new rails endpoint for creating access requests
:ship: 
example payload for testing with postman:
```json
{
"email_address": "eee@example.org",
"first_name": "firsty first",
"last_name": "McSecond",
"organisation": "some org",
"reason": "just because"
}
```
This is an asynchronous tim/david collaboration

1365 create access request endpoint in mc be

---

app/controllers/api/v2/sites_controller.rb
app/policies/site_policy.rb
config/routes.rb
spec/requests/api/v2/providers/sites_spec.rb

Adds a create endpoint which is similar to the other endpoints.
The validations and response are not exhaustively tested as the `update` endpoint already covers them and this endpoint does not differ significantly.
- Adds the `sites#create` controller action, route, authorisation

[1493] Add create endpoint for sites

---

app/models/provider.rb
app/serializers/api/v2/serializable_provider.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers_spec.rb
spec/serializers/api/v2/serializable_provider_spec.rb

We need to hide the button to add new locations when this is false.

[1497] Add can_add_more_sites? to provider serializer

---

app/controllers/api/v2/access_requests_controller.rb
spec/requests/api/v2/access_request_spec.rb

The create endpoint should return an access request when hit. This is needed in the support app to hit the approve endpoint.
Returns the access request created via jsonapi.

[1491] Create endpoint returns the created access request

---

app/controllers/api/v2/access_requests_controller.rb

This is necessary to correctly interpret the parameters sent in by the support app.
Paired with @davidgisbey.

[1491] Add deserializable_resource call to AccessRequestsController

---

app/serializers/search_and_compare/course_serializer.rb
app/serializers/search_and_compare/provider_serializer.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/search_and_compare/mappings.yaml
spec/serializers/search_and_compare/provider_serializer_spec.rb
spec/serializers/search_and_compare/test_data.json

search and compare serialiizer part 1
Added the easy part for a course serializing inclusive of
the course default values, 
the course direct simple values,
the course's provider
the course's accrediting provider
part 1 ot x

1429 snc serializer part 1

---

app/models/user.rb
lib/mcb/commands/users/list.rb
spec/factories/users.rb
spec/lib/mcb/commands/users/list_spec.rb
spec/models/user_spec.rb

We need a list of active, non-admin users when we send out service comms via Notify.
Extend the `mcb users list` command to:
- return specifically active, non-admin users
- write the output to a CSV (we can't pipe to `$stdout` since that's used for the `-E` environment confirmation)

[1502] Automate comms list

---

app/serializers/search_and_compare/course_serializer.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/search_and_compare/mappings.yaml

search and compare serialiizer part 3
subject matters
Added course subject serializing using dfe subjects (calculated subset of `course's subject`)
Added is sen for course as its part of the `course's subject`
part 3 ot x
FYI 
Part 1
Part 2
https://github.com/DFE-Digital/manage-courses-backend/pull/387

1429 snc serializer part 3

---

app/serializers/api/v2/serializable_provider.rb
spec/requests/api/v2/providers_spec.rb

Course#preview
Add `train_with_us` and `train_with_disability` to the V2 provider endpoint
Example - `/api/v2/providers/12K`

[1503] Expose provider enrichments

---

lib/tasks/govuk_lint.rake

`rake lint` does not return an error code when `rubocop` fails.
Make `rake lint` return an error code when `rubocop` fails.

[1502] make 'rake lint' return error of rubocop fails

---

app/models/provider.rb
spec/factories/provider_enrichments.rb
spec/models/provider_spec.rb

The contact info on the provider record is for internal/UCAS use. We need to expose the contact info from the enrichment if it's there.
Expose the contact info from the latest published provider enrichment as "external_contact_info", if exists.
Although this method should do more (fall-back to the contact info in the provider for example), this is a temporary measure to just get it in there for course syncing and preview generation. Another PR will be created for the rest of the work.
Also, ignore the wrong card number in the branch name. Doh!

[1508] add Provider#external_contact_info

---

app/controllers/api/v2/sessions_controller.rb
app/controllers/api/v2/site_statuses_controller.rb
app/controllers/api/v2/sites_controller.rb
app/controllers/api/v2/users_controller.rb
config/environment.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/requests/api/v2/session_spec.rb
spec/requests/api/v2/users_spec.rb

This changes the behaviour from the default which ignores mass-assigns to
unpermitted attribute, to one that raises an error. For an API it seems
sensible to be more strict about what's coming in and going out this way.
This really starts to make sense for course updates where we are only allowed to update attributes that are in the enrichments, but even so there are fields such as code that we won't allow updating.
By raising an exceptions here it'll be more obvious in our testing that we haven't enabled it. If this gets noisy in production with false negatives, then we can always revert to just logging there.
Change configuration to raise when an unpermitted parameter is being set. Change tests that broke as a result.
Some testing was done locally to ensure that sign-ins, location …

[1464] raise error when assigning to unpermitted attributes

---

app/controllers/api/v2/access_requests_controller.rb
spec/requests/api/v2/access_request_spec.rb

The support app needs the requesting users details when listing access requests on the index page.
It's currently hitting the db directly for this. 
Add includes to pass in the requesting users details when the mc-be index route is hit.

[1367] Add include to access request index

---

app/models/provider.rb
spec/factories/providers.rb
spec/models/provider_spec.rb

When a provider doesn't have any enrichments we default to using their "internal" contact info for the "external" contact info.

[1508] fallback to provider info for external contact info

---

app/serializers/search_and_compare/course_serializer.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/search_and_compare/mappings.yaml

search and compare serializer part 5
course variant interplay of `program_type`, `study_mode` & `qualification`
Added serialization of related course variant touch points
Its going to get mess from henceforth, PR to make it better is welcome
part 5 ot x
FYI 
Part 1
Part 2
https://github.com/DFE-Digital/manage-courses-backend/pull/387
Part 3
https://github.com/DFE-Digital/manage-courses-backend/pull/390
Part 4
https://github.com/DFE-Digital/manage-courses-backend/pull/401

[1429] snc serializer part 5

---

app/models/course.rb
app/models/dfe_subject.rb
app/models/subjects/ucas_to_dfe_subject_mapping.rb
app/serializers/api/v2/serializable_course.rb
app/serializers/search_and_compare/course_serializer.rb
spec/models/course_spec.rb
spec/models/dfe_subject_spec.rb
spec/models/subjects/ucas_to_dfe_subject_mapping_collection_spec.rb
spec/models/subjects/ucas_to_dfe_subject_mapping_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/services/subject_mapper_service_spec.rb

We need financial incentive information for rendering the course details page preview. Currently this information resides only on Find.
- extract a `DFESubject` plain-old-Ruby-object model
- define financial incentives data as a Ruby structure on `DFESubject` (this would only get updated at most once a year so should be fine being hard-coded)
- expose `has_bursary?` and `has_scholarship_and_bursary?` on `Course` through the Course API V2

[1520] Financial incentives

---

lib/mcb/commands/courses/sync_to_find.rb
spec/lib/mcb/commands/courses/sync_to_find_spec.rb

The `mcb` tooling allows editing multiple courses at the same time. It should also allow syncing multiple courses to Find.
Extend `mcb courses sync_to_find` to sync multiple courses for a given provider.

[XXX] 'mcb courses sync_to_find' syncs multiple courses

---

app/controllers/api/v2/access_requests_controller.rb
spec/requests/api/v2/access_request_spec.rb

Manual access requests give users God access.
Read the `requester_email` from the params, and pass it into the update. Do not use the super admin. Oops.

[1528] Fix manual access requests

---

app/serializers/site_status_serializer.rb
spec/requests/api/v1/course_spec.rb
spec/serializers/site_status_serializer_spec.rb

If a training location has no vacancies, it's still selectable on UCAS Apply
but the candidate is informed several steps into their application journey
that it's full.
This change makes the training location suspended in the V1 API. The end effect
of this change is that the location is no longer listed on UCAS Apply, so candidates
don't inadvertently select them anymore.

[1527] Training locations without vacancies should be suspended

---

app/controllers/api/v2/providers_controller.rb
app/models/provider.rb
app/serializers/api/v2/serializable_provider.rb
spec/models/provider_spec.rb

Improving our performance by optimising out N+1 and slow db queries.
Uses a bit of raw SQL on the provider model to only include the course counts.
This vastly improves response times, two-fold:
- Cuts the database/ActiveRecord time 2.5x, by not fetching the entire course information as part of the call, only the count
- Cuts the view/json rendering time 5x, because `JSONAPI::Serializable::Resource` seems to do unnecessary work when the entire course information is fetched in
Before:
```
Completed 200 OK in 519ms (Views: 481.4ms | ActiveRecord: 36.4ms)
Completed 200 OK in 649ms (Views: 608.0ms | ActiveRecord: 38.9ms)
Completed 200 OK in 513ms (Views: 473.4ms | ActiveRecord: 38.4ms)
Completed 200 OK in 636ms (Views: 594.4ms | ActiveRecord: 39.6ms)
Completed 200 OK in 535ms (Views: 492.8ms …
```

[1529] Include only course counts on provider index

---

Gemfile
Gemfile.lock
app/models/user.rb
bin/mcb
lib/mcb/commands/users/grant_access_to_provider.rb
lib/mcb/grant_access_wizard.rb
spec/lib/mcb/commands/users/grant_access_to_provider_spec.rb
spec/models/user_spec.rb

We need to be able to add new users to organisations. It's possible to use access requests for this, but only as long as there is an existing user in the organisation.
- Add an `mcb` command which adds new users to an organisation, or gives existing users access to that organisation.
- Add some validations on `User` to help catch any mistakes while using `mcb`

[1506] Grant user access to provider

---

bin/mcb

So that you can more easily copy-paste a deep sub-command.
Also omitted repeated help for top commands and added spacing.
small iteration - I needed to generate a token for local testing and wanted to copy-paste the full command
:ship:

mcb help - show subcommands in full

---

azure/template.json

Add resource deployment to ensure ASP outbound IP's are added to the relevant PostgreSQL firewall rules
- Add firewall rule resource deployment
- Add databaseServiceName name parameter and related variables
- Formatted document so styling is consistent
Change enables ability to add ASP outbound IP's to PostgreSQL firewall rules. New parameter is optional.

Add asp ip to pg sql firewall whitelist

---

app/controllers/api/v2/providers_controller.rb
app/models/provider.rb

Fixing N+1 queries.
Creates a new `has_many` relationship which can be independently `included` to fetch the latest enrichment.
There should already be adequate test coverage for this.
Before:
```
Started GET "/api/v2/providers/2AT" for ::1 at 2019-05-28 15:28:01 +0100
Processing by API::V2::ProvidersController#show as JSONAPI
Parameters: {"code"=>"2AT"}
User Load (0.4ms)  SELECT  "user".* FROM "user" WHERE "user"."sign_in_user_id" = $1 LIMIT $2  [["sign_in_user_id", "135AEC82-DA17-40E8-A280-1B20460475EC"], ["LIMIT", 1]]
↳ app/services/authentication_service.rb:53
Provider Load (0.5ms)  SELECT  "provider".* FROM "provider" WHERE "provider"."provider_code" = $1 LIMIT $2  [["provider_code", "2AT"], ["LIMIT", 1]]
↳ app/controllers/api/v2/providers_controller.rb:15
Provider Exists (0.7ms) …
```

[1533] Optimise providers show

---

app/serializers/search_and_compare/course_serializer.rb
spec/factories/courses.rb
spec/factories/provider_enrichments.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/search_and_compare/mappings.yaml

search and compare serializer part 7
Provider enrichment/fallback for contact info related fields
Added provider related contact info related serialization
part 7 of 8
FYI 
Part 1
Part 2
https://github.com/DFE-Digital/manage-courses-backend/pull/387
Part 3
https://github.com/DFE-Digital/manage-courses-backend/pull/390
Part 4
https://github.com/DFE-Digital/manage-courses-backend/pull/401
Part 5
https://github.com/DFE-Digital/manage-courses-backend/pull/403
Part 6
https://github.com/DFE-Digital/manage-courses-backend/pull/406

[1429] snc serializer part 7

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/provider_enrichment.rb
spec/factories/provider_enrichments.rb
spec/models/course_spec.rb

A course may have an accrediting provider
An accrediting provider description may be enriched via provider enrichment
Expose the accrediting provider description if the course has accrediting provider and it has been enriched

[1538] Added accrediting body description on course model using provider enrichment

---

app/models/course.rb
app/serializers/api/v2/serializable_course.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb

Follow up to https://github.com/DFE-Digital/manage-courses-backend/pull/423
Expose a provider's accrediting body description from provider enrichment
Example - `/api/v2/providers/153/courses`

[1538] Expose about accrediting body on courses

---

app/controllers/api/v1/courses_controller.rb

Change the query used to generate the results for `/api/v1/2019/courses` to include the `sites` that belong to the `site_statuses`.
This speeds up the generation of these results by about 33%.
This is an N+1 query that can be fixed by simply including the data being used when making the original SQL request.

[1540] include site_status sites when generating api v1 courses

---

app/deserializers/api/v2/deserializable_course.rb

This is needed to receive course sites on the update endpoint, to allow users to edit locations.

[1513] Add has_many :sites to deserializable course

---

config/settings/qa.yml

Update QA settings so that the Azure DevOps deployed QA environment can be used in place of the Travis CI deployed environment.
Supercedes: https://github.com/DFE-Digital/manage-courses-backend/pull/400
Update QA yaml file

Update QA base URL's

---

app/serializers/api/v2/serializable_course.rb
spec/requests/api/v2/providers/courses_spec.rb

Entry requirement options i.e. English, maths and science
Expose the options as they already live in our course model
Example endpoint `/api/v2/providers/13E/courses/386H`

[1531] Expose entry requirement options to course

---

bin/mcb
lib/mcb.rb
lib/mcb/azure.rb
lib/mcb/commands/apiv1.rb
lib/mcb/commands/apiv1/courses/find.rb
lib/mcb/commands/apiv1/courses/list.rb
lib/mcb/commands/apiv1/providers/find.rb
lib/mcb/commands/apiv1/providers/list.rb
lib/mcb/commands/az/apps/config.rb
lib/mcb/render.rb
spec/lib/mcb/azure_spec.rb
spec/lib/mcb/commands/apiv1/courses/find_spec.rb
spec/lib/mcb_spec.rb
spec/serializers/api/v2/serializable_access_request_spec.rb

###Why are we doing this?
To allow admins to view what a course looks like as it's being sent to UCAS.
###What are we adding or changing?
A command to`mcb` to find a course in the output generated by the api v1.
###Background
Useful for investigating issues with the system.

[1542] add mcb apiv1 course find command

---

app/models/course.rb
app/serializers/api/v2/serializable_course.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

These are needed for the locations feature in the frontend. Also, filter only the running and new sites.

[1517] Send down sites courses serializer

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb

Pairing @davidgisbey & @timabell & @tvararu 
* Extend the `course#update` endpoint to support supplying a list of sites.
* Remove some dead code that was in the way after discussing with @benilovj 
* Hide more of the exposed `site_status` inside `sites` in the API surface.

[1517] Add/remove/suspend course sites

---

lib/mcb.rb
lib/mcb/commands/apiv1.rb
lib/mcb/commands/apiv1/courses/find.rb
lib/mcb/commands/apiv1/courses/list.rb
lib/mcb/commands/apiv1/providers/find.rb
lib/mcb/commands/apiv1/providers/list.rb

In many of the mcb commands that query the apiv1, the max-pages isn't respected and hard-set to 1.
Fix this. This was fixed in 1542 for the `mcb apiv1 course find` command, the same approach needs to be copied to the other apiv1 commands.

[1585] fix use of max-pages and page reporting in apiv1 mcb commands

---

bin/mcb
lib/mcb/commands/courses/edit.rb
lib/mcb/courses_editor.rb
spec/lib/mcb/commands/courses/edit_spec.rb
spec/lib/mcb/courses_editor_spec.rb

Until we've built all course editing features for publishers to self-serve, we need support tooling to be able to action support requests for changes.
- add a new `mcb courses edit` command
- allow editing individual courses or all courses for a provider
- some basic validation on the provider, course codes and the user making the changes
- editing of course title
I will add the editing of other aspects of course in subsequent PRs, I wanted to lay the groundwork with this one and get feedback.

[1586] mcb courses edit: edit title

---

lib/mcb/commands/courses/touch.rb
lib/mcb/commands/providers/touch.rb
spec/lib/mcb/commands/courses/touch_spec.rb
spec/lib/mcb/commands/providers/touch_spec.rb

So that we can "push" a course to UCAS to update their records, could be used to address a support issue, for example.
Add the commands `mcb course touch` and `mcb provider touch`.

[1566] force course to update to ucas

---

lib/mcb/courses_editor.rb
spec/lib/mcb/courses_editor_spec.rb

Follow-up to #446.
Until we've built all course editing features for publishers to self-serve, we need support tooling to be able to action support requests for changes.
- edit equivalency settings (maths, english, science)
- edit route
More PRs to follow.

[1586] mcb courses edit: part 2

---

bin/mcb
lib/mcb/commands/apiv1/courses/find.rb
lib/mcb/commands/apiv1/providers/find.rb
lib/mcb/commands/courses/show.rb
lib/mcb/commands/providers/show.rb
lib/mcb/render.rb
lib/mcb/render/active_record.rb
lib/mcb/render/apiv1.rb
spec/lib/mcb/commands/apiv1/courses/find_spec.rb
spec/lib/mcb/commands/courses/show_spec.rb
spec/lib/mcb/commands/users/audit_spec.rb
spec/support/matchers/have_text_table_row.rb

When handling support requests it's handy to be able to easily view the state a course is in quickly and through the CLI.
Add a `mcb course show` command to mcb. Also cleans up the rendering a little bit so that there is more common code between `course show` and `apiv1 course find`.
```
% be bin/mcb course show 2K5 3B55
Course:
+-------------------------+---------------------------------------------+
| id                      | 8252934                                     |
| age_range               | secondary                                   |
| course_code             | 3B55                                        |
| name                    | Chemistry                                   |
| profpost_flag           | recommendation_for_qts                      |
| program_type …
```

[1541] add mcb course show

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb

This will allow us to display an appropriate error message on the frontend when the user submits an empty array of sites.
Pushes a validation message to `@course.errors` and checks for its presence before rendering the response.
The validation is done at the controller level instead of the model. This is because `sites = []` is something that we can validate against, but we can't actually revert easily from what I can tell because of the `remove_site!` side effects that occur when it's called.

[1580] Add validations to edit locations

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/update_spec.rb

Currently the courses#update action always creates an enrichment when called. This leads to two bugs:
- When updating the sites, the course is set to draft
- When the user opens the enrichment pages but makes no changes and
hits "Save", the course changes state
This wraps the enrichment logic in a guard so that it isn't run unnecessarily.
The enrichment and site update logic are both wrapped in private methods to make the update action a bit easier to parse.

[1587] Create enrichment in courses#update only when necessary

---

app/serializers/api/v2/serializable_course.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

Having to manually set this on the frontend as a workaround every time is
annoying. The course endpoint in APIv2 should show the provider_code of the
course to make the relationship between provider and course work smoothly.
Expose `provider_code` in the APIv2 course endpoint.

[1610] Expose provider_code in course endpoint

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb

The frontend doesn't necessarily know when a course is due to be synced with search-and-compare, the concern for that knowledge should be in the backend.
Call `ManageCoursesAPIService` in courses update.
🚢

[1608] Sync courses when updating courses and site_statuses

---

spec/factories/providers.rb
spec/policies/course_policy_spec.rb
spec/policies/site_policy_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/requests/api/v2/providers_spec.rb

**This has been rebased onto the previous pr removing site_count do not merge until that PR has been approved and merged**
We've decided to remove dependencies from the factories where possible. This PR removes site_count from the provider factory.
- Removes course_count from the provider factory.

[1460] Remove course_count from provider factory

---

app/models/course.rb
spec/models/course_spec.rb

The previous logic failed to account for courses that were already  published.

[1616] Use ucas_status when adding/removing sites

---

lib/mcb/courses_editor.rb
lib/mcb/courses_editor_cli.rb
spec/lib/mcb/courses_editor_spec.rb

Accidentally set a requirement because 1 is usually exit.
Not spending too long on this.
Make exit an option
Suggestions for why exit isn't a symbol would be nice, also how to apply it to the other editing bits of course (route etc) as they don't follow the same pattern.

Allow exiting requirements selection

---

Gemfile
spec/serializers/api/v2/serializable_provider_spec.rb
spec/serializers/api/v2/serializable_site_spec.rb
spec/serializers/api/v2/serializable_site_status_spec.rb
spec/serializers/api/v2/serializable_user_spec.rb
spec/spec_helper.rb

It's not necessary for checking types and attributes on jsonapi hashes. `jsonapi-rspec` has better matchers which we already bundle.
Replace calls to the library matchers and remove the library.
SHIP IT

[1571] Remove rspec-json_matchers

---

lib/mcb/render/apiv1.rb
spec/lib/mcb/commands/apiv1/providers/find_spec.rb
spec/mcb_helper.rb

The previous commit to add `mcb courses show` tweaked and broke rendering for `mcb apiv1 provider find`.
Re-add campus table rendering.

[1599] fix apiv1 provider find campuses rendering

---

app/controllers/api/v2/courses_controller.rb
app/services/manage_courses_api_service.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb

We're getting errors when we try to sync a course with search and compare.
Ensure an error is raised when we try to sync a course so we have a better understanding of what's gone wrong.

[1606] raise error when sync to sac fails

---

config/initializers/mcb_audit.rb
lib/mcb.rb
lib/mcb/commands/console.rb

Part of supporting the live product involves making data changes on production. In order to allow making safe, audited changes we need to be able to connect the Rails console to production environments.
Add an `mcb` command for launching the Rails console:
```ruby
$ bundle exec mcb console -E qa -v
As a safety measure, please enter the expected RAILS_ENV for bat-qa-mcbe-as: qa
Loading qa environment (Rails 5.2.3)
irb(main):001:0>
```

[1619] mcb console with environmental config

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/course_enrichment.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/update_spec.rb

We need to add validations for saving enrichments and for publishing them.
First PR of a few.
Splits up the `course_enrichment` validations into two scopes: `:publish` which is same as before, and `:save` which skips the presence validations.
Also some miscellaneous refactors.
Best reviewed commit by commit.

[1571] Split course_enrichment validations

---

app/deserializers/api/v2/deserializable_course.rb
spec/desieralizers/api/v2/deserializable_course_spec.rb

`qualifications` vs `required_qualifications`
😑 
n/a

[1681] Fix course enrichment qualifications attribute

---

spec/factories/courses.rb
spec/lib/mcb/commands/apiv1/courses/find_spec.rb
spec/lib/mcb/commands/courses/show_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb

Subject creation in course factory
Removed unneeded chaos of having subject_count and its related usage in course factory

[1460] Removed subjects from course factory

---

app/models/course.rb
app/models/site_status.rb
spec/models/course_spec.rb
spec/models/site_status_spec.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb

We should be able to add or remove sites to a course without having to resort to custom methods like add_site! or remove_site!.
Replace the functionality in those methods with callbacks in SiteStatus.
This code was done as a proof of concept and, on account of it being pretty late and me not being able to see straight, could probably use a little tidying up. It also doesn't remove the mentioned methods, that might be slightly more work.

[1598] use callbacks to add or remote sites to course

---

lib/mcb/courses_editor.rb
lib/mcb/courses_editor_cli.rb
spec/lib/mcb/courses_editor_spec.rb

Follow-up to #446, #449 and #456 
Until we've built all course editing features for publishers to self-serve, we need support tooling to be able to action support requests for changes and new courses.
- extract out a method for handling multiple choice questions in `CoursesEditorCLI`
As a precursor to the new course creation:
- edit the age range on a record
- edit the course code

[1586] mcb courses edit: part 4

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/update_spec.rb

JSONAPI requests can come in with an empty set of attributes, if there are no attributes to update. When this happens, the deserializer doesn't even bother to create the root parameter (e.g. `course` in this case).
Default the course update attributes to an empty hash instead of requiring it to be present. i.e. we usually expect the params to come in as:
```
{
course: {
about_course: "This is a great course.",
...
}
}
```
so we can do `params.require(:course)`. But now, when `course:` isn't present, we default it to `{}`.

[1626] accomodate empty attributes when updating from jsonapi

---

lib/mcb/commands/apiv1/providers/find.rb
lib/mcb/commands/providers/audit.rb
lib/mcb/commands/providers/list.rb
lib/mcb/commands/providers/sync_to_find.rb
lib/mcb/commands/providers/ucas_preferences/show.rb
lib/mcb/commands/users/grant_access_to_provider.rb

All provider and course codes are upper-case in production.
Upper-case all provider and course codes that are passed into the `mcb` tooling, so the tooling is more resilient to fat-fingering by the user.
This commit has been part-ported across from the extra tooling branch.

Ensure that course and provider code params are upper-cased

---

spec/requests/api/v2/access_request_spec.rb

This test was too specific, checking each and every attribute. This
caused it to be too brittle.
I've replaced comparing the complete JSON output to using JSONAPI RSpec
matchers to check if the correct objects are rendered out, with the
relationships and attributes we expect.
There's no need to test this further than that, the serializer is unit
tested to make sure it gives us the correct data.

[1455] Use JSONAPI matchers instead of equality

---

app/models/course_enrichment.rb
spec/factories/course_enrichments.rb
spec/models/course_enrichment_spec.rb
spec/requests/api/v2/providers/courses/update_spec.rb

Revert of https://github.com/DFE-Digital/manage-courses-backend/pull/338/files
Ensure we validate numerically of uk and international fees
Try and submit a non-numerical character

[1623] Validate numericality of course fees

---

spec/lib/mcb/courses_editor_spec.rb

One of the specs for `mcb courses edit` freezes time and fails on the day boundary.
Freeze time, rather than freeze date.

[1586] Fix mcb spec as it fails at a particular point in time

---

spec/factories/courses.rb
spec/factories/site_statuses.rb
spec/models/course_spec.rb
spec/models/site_status_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/providers/sites_spec.rb

Pull request No. 6 to clean up the associations in our factories. This PR removes with_site_statuses from the course factory.
- Remove with_site_statuses from the course factory

1460 remove with site status from course factory

---

app/controllers/api/v2/sites_controller.rb
app/deserializers/api/v2/deserializable_site.rb
spec/desieralizers/api/v2/deserializable_site_spec.rb
spec/requests/api/v2/providers/sites_spec.rb

json-api will auto-generate one for us, but it's better to use an explicit one instead because that way we have more finely grained control over what attributes get exposed.
Add DeserializableSite and use it in the site_controller.

[1624] Add deserializable site class

---

app/models/course.rb
spec/requests/api/v2/providers/courses/update_spec.rb

These were initially added with the idea that without them, the frontend will not be able to differentiate which errors belong to the course and which errors belong to the course enrichment.
In practice, they actually end up confusing json-api, which will not automatically assign `source: { pointer }`s which are used to then associate validation errors to the appropriate field.
Because the frontend doesn't need to know about enrichments, it's better if we simply remove this prefix.

[1624] Remove latest_enrichment prefix on enrichment errors

---

lib/mcb/commands/users/show.rb
lib/mcb/render.rb
lib/mcb/render/active_record.rb

Working towards providing ability to revoke a user's access to an organisation
Update `user show` command to new style. This will allow us to preview the changes when we get to access modification.
```
tim@fox:~/repo/dfe/manage/backend(1651-mcb-use-grid-for-user-show)
$ be bin/mcb users show "larae@dicki.info"            
User:
+------------------------+------------------+
| id                     | 102              |
| email                  | larae@dicki.info |
| first_name             | Mandie           |
| last_name              | Hilll            |
| first_login_date_utc   |                  |
| last_login_date_utc    |                  |
| sign_in_user_id        |                  |
| welcome_email_date_utc |                  |
| invite_date_utc        |                  |
| …
```

[1651] Use render system for showing user info

---

spec/factories/providers.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/serializers/provider_serializer_spec.rb

**Do not merge in until #477 #479 have been merged in as this PR is rebased onto #479** 
This is the final PR to clean up the dependencies in the factory. 
- Removes a ucas_preference being built into the provider in the provider factory
- Fix tests that began to flake post change

1460 Remove ucas preferences from provider factory

---

app/controllers/api/v2/access_requests_controller.rb
app/models/access_request.rb
spec/models/access_request_spec.rb

The access request controller currently has the logic for adding the requester_id, request_date_utc and the status to the access_request object upon instantiation. 
- Move updating the above 3 attributes from the controller to the model.

[1530] Move create logic to controller

---

app/models/course.rb
app/serializers/course_serializer.rb
spec/models/course_spec.rb

So we can add a `belongs_to` recruitment_cycle_year to Course later.
- Refactor Course#recruitment_year to Course#recruitment_cycle_year

[1644] Refactor course recruitment_year to recruitment_cycle_year

---

Gemfile
Gemfile.lock
app/validators/words_count_validator.rb

Apparently counting words is hard. Have a play http://rubywordcount.com/
Add [words_counted](https://github.com/abitdodgy/words_counted) gem and remove home grown regex
```ruby
pry(main)> ce = CourseEnrichment.new(provider: Provider.first, course: Course.first)
pry(main)> ce.about_course = 'foo ' * 451
pry(main)> ce.valid? :save
=> false
pry(main)> ce.errors.messages
=> {:about_course=>["^Reduce the word count for about course"]}
pry(main)> ce.about_course = 'foo\n' * 451
pry(main)> ce.valid? :save
=> false # previsouly this was true 
pry(main)> ce.errors.messages
=> {:about_course=>["^Reduce the word count for about course"]}
```

[1635] Make word count validation more robust

---

spec/support/with_stubbed_stdout.rb

param errors in mcb usage of cri are hard to debug due to our use of stderr/out redirection in the test harness
extracted this PR while working on #500
Add environment variable `WITHOUT_STUBBED_STDOUT` to bypass stderr redirection for debugging
introduce a local diff that adds a new cri param
```
diff --git a/lib/mcb/commands/users/grant_access_to_provider.rb b/lib/mcb/commands/users/grant_access_to_provider.rb
index eac9372..e510221 100644
--- a/lib/mcb/commands/users/grant_access_to_provider.rb
+++ b/lib/mcb/commands/users/grant_access_to_provider.rb
@@ -1,5 +1,6 @@
summary 'Attach a user to an organisation/provider in the DB'
param :provider_code, transform: ->(code) { code.upcase }
+param :xxx
usage 'grant_access_to_provider <provider_code>'
run do |opts, args, _cmd|
```
without the …

[1651] mcb specs - env var for disabling stderr redirection

---

db/data/20190619132129_create_recruitment_cycles.rb
db/data_schema.rb
db/seeds.rb

We need `RecruitmentCycle`'s in our database
Data migration to add the 2019 and 2020 recruitment cycles
Run `bundle exec rake db:migrate:with_data`
```
$ bundle exec rails c
$ RecruitmentCycle.all
[#<RecruitmentCycle:0x00007fa9d00f3f30
id: 2,
year: "2019",
application_start_date: nil,
application_end_date: nil,
created_at: Wed, 19 Jun 2019 13:27:46 UTC +00:00,
updated_at: Wed, 19 Jun 2019 13:27:46 UTC +00:00>,
#<RecruitmentCycle:0x00007fa9d00e0188
id: 3,
year: "2020",
application_start_date: nil,
application_end_date: nil,
created_at: Wed, 19 Jun 2019 13:27:46 UTC +00:00,
updated_at: Wed, 19 Jun 2019 13:27:46 UTC +00:00>]
```

[1643] Add recruitment cycles to database

---

Gemfile.lock
lib/mcb.rb

We want to keep gem dependencies updated. `cri` 2.15.8 changed how default values are set in the `cri` options, meaning some of our `mcb` commands broke.
Ensure that default values are passed around in the `mcb` code as before.
There's more background reading on https://github.com/ddfreyne/cri/pull/99

Update to cri 2.15.9

---

app/models/course.rb
app/models/site.rb
app/models/site_status.rb
app/models/subject.rb
spec/models/course_spec.rb
spec/models/site_spec.rb
spec/models/site_status_spec.rb
spec/models/subject_spec.rb

The support tooling displays sites and subjects to the support agents in various places.
- remove `SiteStatus#description` (no longer used)
- add `Site#to_s` and `Subject#to_s`

[1657] Improved string representation of models

---

lib/mcb/commands/users/grant.rb
lib/mcb/grant_access_wizard.rb
spec/lib/mcb/commands/users/grant_access_to_provider_spec.rb
spec/lib/mcb/commands/users/grant_spec.rb

Improving `bin/mcb users grant` ready for adding revoke after discussions with @misaka 
* rename the command to be shorter
* move email address into command arguments instead of prompting for it
* use the new output format, this shows more information about what is being done before prompting to continue
new usage:
```
tim@fox:~/repo/dfe/manage/backend(1651-mcb-refactor-user-grant)
$ be bin/mcb users grant bobby.tables@digital.education.gov.uk A1
bobby.tables@digital.education.gov.uk appears to be a new user
First name?  bobby
Last name?  tables
User:
+------------------------+---------------------------------------+
| id                     |                                       |
| email                  | bobby.tables@digital.education.gov.uk |
| first_name             | bobby …
```

1651 mcb refactor user grant

---

app/models/course.rb
app/models/recruitment_cycle.rb
app/serializers/course_serializer.rb
db/data/20190619144634_add_2019_recruitment_cycle_to_courses.rb
db/data_schema.rb
db/migrate/20190619142449_add_recruitment_cycle_to_course.rb
db/schema.rb
db/seeds.rb
spec/factories/courses.rb
spec/models/course_spec.rb
spec/models/recruitment_cycle_spec.rb
spec/serializers/course_serializer_spec.rb

Add the 2019 recruitment cycle to ALL courses
- Setup association between course and recruitment cycle
- Add data migration to add 2019 recruitment cycle to all courses
Run `bundle exec rake db:migrate:with_data`

[1640] Add recruitment cycle to courses

---

spec/lib/mcb/commands/users/revoke_spec.rb

Follow up to #513 with extra coverage.
I wasn't happy that the tests wouldn't catch accidentally deleting unrelated access.
* More coverage
:ship:

[1651] mcb users revoke - add test for over-deletion

---

app/controllers/api/v2/sites_controller.rb
app/models/recruitment_cycle.rb
app/models/site.rb
app/serializers/site_serializer.rb
config/settings.yml
db/data/20190620121519_add2019_recruitment_cycle_to_sites.rb
db/data_schema.rb
db/migrate/20190620120944_add_recruitment_cycle_to_site.rb
db/schema.rb
db/seeds.rb
spec/factories/sites.rb
spec/models/recruitment_cycle_spec.rb
spec/models/site_spec.rb
spec/serializers/site_serializer_spec.rb

Add the 2019 recruitment cycle to ALL sites
- Setup association between site and recruitment cycle
- Add data migration to add 2019 recruitment cycle to all sites
Run `bundle exec rake db:migrate:with_data`
Follow up PR to make recruitment cycle not nullable for sites AND courses

[1558] Add recruitment cycle to sites

---

db/data/20190620121519_add2019_recruitment_cycle_to_sites.rb

This make the update succeed in <1s (versus ~60s when using AR updates)
Issue caught in product review, so this is a tweak to what's already in master.

[1558] use raw SQL when updating recruitment_cycle on sites

---

Gemfile
Gemfile.lock
app/validators/words_count_validator.rb
spec/validators/words_count_validator_spec.rb

The word count component in the frontend isn't doing anything as sophisticated as the word count library, which causes a mismatch between the frontend and the backend when submitting e.g. markdown tokens.
This changes to the same [RegExp used in the frontend](https://github.com/alphagov/govuk-frontend/blob/063cd8e2470b62b824c6e50ca66342ac7a95d2d8/src/govuk/components/character-count/character-count.js#L80), and removes the words_counted library.

[1624] Match word count validator to frontend

---

app/models/nctl_organisation.rb
config/initializers/inflections.rb
lib/mcb/commands/nctl/import.rb

We need UKPRN (provider reference numbers) in the courses report.
- attach a UKPRN to the NCTL organisation if it's specified in the import
Each NCTL ID will always be either a UKPRN or a URN, but not both.

[XXX] Extend NCTL data importer to bring in UKPRNs

---

app/models/concerns/allocations_report.rb
app/models/course.rb

The Course model is getting too big to manage, and this is an obvious grouping of functionality.
Move methods and data related to allocation report generation to a separate concern.

Move allocation report to concern

---

app/models/concerns/allocations_report.rb
app/models/provider.rb
spec/factories/subjects.rb
spec/models/concerns/allocations_report_spec.rb
spec/models/provider_spec.rb

Some providers have no organisations.
Don't generate an allocations report for providers that don't belong to an organisation.

[AL-11] skip providers with no args

---

app/models/concerns/with_qualifications.rb
app/models/course.rb
spec/models/concerns/with_qualifications_spec.rb
spec/models/course_spec.rb

When new courses are created, we need to ensure that the correct downstream data is derived. In future we should move these attributes to the API V1 serialisers and drop the underlying columns.
- add a default for `Course#modular`
- set `Course#profpost_flag` when `Course#qualification` is set

[1657] Course defaults and aligned data

---

app/models/provider.rb
app/serializers/course_provider_serializer.rb
app/serializers/provider_serializer.rb
spec/models/provider_spec.rb
spec/serializers/course_provider_serializer_spec.rb
spec/serializers/provider_serializer_spec.rb

Providers are either accredited bodies or they're not. There is information stored on the record to interrogate this.
Replace an existing helper method with an enum, in order to get the scope and both possible values.

[1670] Introduce enum for Provider#accrediting_provider

---

app/models/course.rb
app/serializers/course_serializer.rb
lib/mcb/courses_editor_cli.rb
spec/models/course_spec.rb
spec/serializers/course_serializer_spec.rb

RE: The `courses` endpoint on the V1 API. 
At present, we return a hardcoded year stored in the course model but we now have a recruitment cycle model.
Replace hardcoded value with the dynamic value from `course.recruitment_cycle`
`/api/v1/2019/courses`

[1645] Return dynamic recruitment year for V1 courses

---

app/models/user.rb
lib/mcb/commands/users/revoke.rb
lib/mcb/render.rb
lib/mcb/revoke_access_wizard.rb
spec/lib/mcb/commands/users/revoke_spec.rb
spec/models/user_spec.rb

We have users with access to many orgs, when they leave it takes too long to loop through removing access. We can't just kill their sign-in acc because they might use it for other things, we need to control our own access.
cri params can't be optional, but options can so the provider code is now a named parameter - `-p XYZ` so the usage of the existing `users revoke` has changed from `users revoke email@address XY1` to `users revoke email@address -p XY1`
Make provider code for revoke optional and named. If not supplied all access will be removed.
```
tim@fox:~/repo/dfe/manage/backend(1651-mcb-revoke-god-user)
$ be bin/mcb user revoke x@y      
User:
+------------------------+-----+
| id                     | 114 |
| email                  | x@y |
| first_name             | x   |
| …
```

1651 mcb revoke god user

---

app/models/course.rb
spec/models/course_spec.rb

This field is very important for for investigating sync process issues with downstream, even if
it will probably generate quite a bit of data.
- audit `Course#changed_at`

[1680] Enable auditing on the Course#changed_at timestamp

---

config/initializers/mcb_audit.rb
lib/mcb.rb
spec/lib/mcb_spec.rb

Commands that use Rails are busted in mcb.
Fix the way the audited user is loaded in the mcb Rails initialiser.

[1684] fix mcb audit user

---

lib/mcb/courses_editor.rb
spec/lib/mcb/courses_editor_spec.rb

`mcb courses edit` picks the wrong course to edit when there are two courses with the same course code across two different providers.
Use the provider when filtering courses to edit.
😞

[1687] 'mcb courses edit' should pick the right course to edit

---

app/controllers/api/v1/courses_controller.rb
app/models/course.rb
spec/controllers/api/v1/courses_controller_spec.rb
spec/models/course_spec.rb
spec/requests/api/v1/course_spec.rb

Rollover
Add a model scope to filter courses by recruitment year passed into the endpoint
No change to current year i.e. `http://localhost:3001/api/v1/2019/courses` but if you update the `recruitment_cycle` on a course to another year then change the endpoint you'll see a filtered list of courses

[1646] Make recruitment year dynamic for V1 API

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/course_enrichment.rb
spec/models/course_enrichment_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb

Currently, it is possible to save enrichments even though they do not pass validations. This is incorrect behaviour when compared to the C# app.
The changes the `:save` scoped validations to always run whenever we validate enrichments.
Review commit by commit.
TODO:

[1656] Always run enrichment save validations

---

lib/mcb/commands/courses/audit.rb
spec/lib/mcb/commands/courses/audit_spec.rb

It's helpful seeing the audit trail on courses when investigating some discrepancy between Find, Publish and Apply.
Introduce an `mcb courses audit` command which prints out the audit log for the specified course.

[XXX] 'mcb courses audit' to see the audit trail on courses

---

app/serializers/search_and_compare/course_serializer.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/search_and_compare/test_data.json

c# vs rails pub testing
Campus address needs commas instead of new line, and space separated postcode
Accrediting Provider Enrichment descriptions always return empty string
https://github.com/DFE-Digital/manage-courses-api/blob/4b851b14c504dca8d11e77b8dcce9ac514612d46/src/ManageCourses.Api/Mapping/CourseMapper.cs#L251
https://github.com/DFE-Digital/manage-courses-api/blob/4b851b14c504dca8d11e77b8dcce9ac514612d46/src/ManageCourses.Api/Mapping/CourseMapper.cs#L229

[1658] Fixed issues found from testing

---

Dockerfile

We've removed the data migrations and gem, but not it being run.
Remove 'rails data:migrate' from Dockerfile.

[1682] remove rails data:migrate from Dockerfile

---

config/settings/new_staging.yml

Update new staging environment to use non-Azure domains
Change base_url value in New_staging.yml file from default azure web app .azurewebsites.net urls to service domains
base_url updated in new_staging.yml file only. New staging service domain urls are as follows:
mcapi: https://api.staging.publish-teacher-training-courses.service.gov.uk
mcbe: https://api2.staging.publish-teacher-training-courses.service.gov.uk
mcfe: https://www2.staging.publish-teacher-training-courses.service.gov.uk
mcspt: https://support.staging.publish-teacher-training-courses.service.gov.uk
mcui: https://www.staging.publish-teacher-training-courses.service.gov.uk
sacapi: https://api.staging.find-postgraduate-teacher-training.service.gov.uk
sacui: https://www.staging.find-postgraduate-teacher-training.service.gov.uk

Updated base_url to use service domain in new_staging.yml

---

app/models/course_enrichment.rb
spec/models/course_enrichment_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb

We didn’t have validations for word count for:
- personal qualities
- other qualifications
This means users could save long answers to these.
- Add missing validations
- Group validations by enrichment page, and order based on order they appear in form – this means the error messages shown to users will also appear in the correct order

[1690] Add word count validations for personal qualities and other requirements

---

config/locales/en.yml
spec/requests/api/v2/providers/courses/publish_spec.rb

Users get a message which relates to "enrichments," which is confusing.
Change the validation message.
:shipit:

[1685] Update validation when enrichments are blank

---

app/models/course.rb
spec/requests/api/v2/providers/courses/update_spec.rb

Because of the `has_many :enrichments` relationship, Rails will add a `Enrichments is invalid` message on the `Course` model when a new `CourseEnrichment` is created but fails to be saved due to validation issues. This behaviour can occur when users attempt to save a new enrichment (as opposed to updating an already draft one) which has errors.
Adds an `after_validation` to manually clear the unnecessary validation.
I can't seem to find a more idiomatic way of doing this.

[1685] Remove unnecessary "Enrichments is invalid" message

---

app/models/course.rb
app/models/course_enrichment.rb
db/migrate/20190626132627_add_course_ref_to_course_enrichment.rb
db/schema.rb
spec/factories/course_enrichments.rb
spec/factories/courses.rb
spec/models/course_enrichment_spec.rb
spec/models/course_spec.rb

The course enrichment can be 2019 or 2020 recruitment cycle
The course enrichment is now associated with a course, making the need for `ucas_course_code` & `provider_code` redundant as well as making it possible deterministic to get a 2019 or 2020 recruitment cycle for course enrichments.
`ucas_course_code` & `provider_code` needs to stay for backwards compatibility with its C# counterpart. 
`ucas_course_code` & `provider_code` original purpose was due to the course records being dropped and imported therefore the `course_id` was not usable.

[1679] The course enrichments can be 2019 or 2020 recruitment cycle

---

lib/mcb.rb
lib/mcb/commands/az/apps/pg_dump.rb
lib/mcb/commands/az/apps/psql.rb
spec/lib/mcb/commands/az/apps/pg_dump_spec.rb
spec/lib/mcb/commands/az/apps/psql_spec.rb

Needed to reset qa database to eliminate drift before testing.
* Add pg_dump to apps command
* Add input file / sql-string to psql command
new things:
```
be bin/mcb az apps psql -h
...
-c --sql_command[=<value>]      sql string to run
-f --source_file[=<value>]      source sql file to pass to psql to run
be bin/mcb az apps -h     
...
SUBCOMMANDS
...
pg_dump     backup the psql server for an app
...
```
Comments on desired test coverage might be handy
```
$ be bin/mcb az apps psql -v -E qa -c "select * from recruitment_cycle;"
$ be bin/mcb az apps pg_dump -E qa qa-dump.sql
```

1645 mcb add pg dump

---

app/models/provider.rb
app/models/provider_enrichment.rb
db/migrate/20190627151832_add_provider_ref_to_provider_enrichment.rb
db/schema.rb
spec/factories/provider_enrichments.rb
spec/models/provider_enrichment_spec.rb

The provider enrichment can be 2019 or 2020 recruitment cycle
The provider enrichment is now associated with a provider, making the need for provider_code redundant as well as making it possible deterministic to get a 2019 or 2020 recruitment cycle for provider enrichments.
There is no provider_enrichment creation...

[1677] The provider enrichments 2019 vs 2020 recruitment cycle

---

lib/mcb/courses_editor.rb
lib/mcb/courses_editor_cli.rb
spec/factories/subjects.rb
spec/lib/mcb/courses_editor_cli_spec.rb
spec/lib/mcb/courses_editor_spec.rb
spec/models/course_spec.rb
spec/models/subject_spec.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/subject_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

New course creation is currently being done through user support using `mcb` dev tooling. The tooling itself is sitting on a code branch that isn't the `master` branch and needs constant updating/rebasing.
The code is also missing automated tests, meaning it needs to be manually tested after every change.
Introduce editing subjects to `mcb courses edit` which is both useful for editing courses, as well as being a stepping stone towards the new course creation.
This PR is best reviewed commit by commit.

[1657] mcb courses edit subjects

---

config/locales/en.yml

Follow guidance from the design system: https://design-system.service.gov.uk/components/text-input/#error-messages
Removes the "must be an integer" warning, which was too technical.

Make integer warnings more friendly for fees

---

app/models/recruitment_cycle.rb
lib/mcb.rb
lib/mcb/courses_editor.rb
lib/mcb/courses_editor_cli.rb
lib/mcb/render.rb
lib/mcb/render/active_record.rb
lib/mcb/render/apiv1.rb
spec/lib/mcb/courses_editor_spec.rb
spec/models/recruitment_cycle_spec.rb

We need to be able to create new courses against different course cycles. 
- Fix the `-c` flag for the V1 API mcb commands (it was broken when `rubocop-rails` was introduced)
- Print the recruitment cycle when printing the course
- Allow the courses editor to edit recruitment cycle (this will be reused as part of the new course wizard).

[1657] mcb courses edit: recruitment cycle

---

app/controllers/api/v2/courses_controller.rb
app/deserializers/api/v2/deserializable_course.rb
spec/deserializers/api/v2/deserializable_course_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb

Publish validations are hacky on the frontend because the backend does not give us source pointers which map the errors to their appropriate fields.
`reverse_mapping` is responsible for generating the `pointer` attributes in a JSON API response which contains validation errors. The way it works is `jsonapi-rails` will inspect the `params` and based on the attributes provided, populate `reverse_mapping`. This means that the only attributes that can be associated with errors are ones that get passed in as part of the request.
When we do the `publish` action, we don't pass in any attributes, because they already exist on the model. This means that without help, `jsonapi-rails` can't figure out to which attributes the fields we're showing errors on should map back to. In this scenario, it …

[1664] Override reverse_mapping in deserializable_course

---

db/migrate/20190704134543_make_provider_id_nullable.rb
db/schema.rb

Previous pr was merged too soon:
https://github.com/DFE-Digital/manage-courses-backend/pull/561
This rollback making the provider_id not nullable as it's preventing providers
from editing their information (new provider enrichments can't be created).

Make provider_enrichment.provider_id nullable

---

spec/factories/courses.rb
spec/factories/sites.rb

Course and site factories create duplicate recruitment cycles. 
Find or create associated recruitment cycles.

[1657] Don't create duplicate recruitment cycles in factories

---

bin/mcb
lib/mcb.rb
lib/mcb/commands/courses.rb
lib/mcb/commands/courses/list.rb
lib/mcb/commands/providers/list.rb
spec/mcb_helper.rb

`mcb` is currently slow to startup and running it many times in a row, especially when it comes to connecting to a remote env, can be slow.
Add a REPL mode to `mcb` so that you only have to startup Rails, and connect to a remote environment, once for a session.
```
% be bin/mcb -E production
As a safety measure, please enter the expected RAILS_ENV for bat-prod-manage-courses-backend-app: production
Audit user: Misha Gorodnitzky <misha.gorodnitzky@digital.education.gov.uk>
Raven 2.9.0 configured not to capture errors: DSN not set
production> course show 2BD 39C8
Course:
+-------------------------+----------------------------------+
| id                      | 12910035                         |
| age_range               | secondary                        |
| course_code             | 39C8 …
```

[1713] mcb repl

---

app/controllers/api/v2/courses_controller.rb
app/policies/course_policy.rb
config/routes.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb

Deep linking validations.
This checks whether a course is publishable and replies with either a 200 or a 422 with the errors. Unlike `publish`, it doesn't actually publish.
This maybe should be a `GET` and not a `POST` but `jsonapi-rb` will not populate `source: { pointer }`s with a `GET`... I've spent too much time in that library already so am feeling weary about figuring out why.

[1664] Add #publishable endpoint on courses API

---

app/controllers/api/v2/users_controller.rb
app/models/user.rb
app/policies/user_policy.rb
config/routes.rb
db/seeds.rb
spec/models/user_spec.rb
spec/requests/api/v2/users/accept_rollover_screen_spec.rb

- Use user state to determine if they've seen the rollover screen
- They must have seen the transition screen first
Goes with https://github.com/DFE-Digital/manage-courses-frontend/pull/430

[1387] Add a rolled_over state for users

---

db/migrate/20190703120737_add_foreign_key_to_course_and_course_enrichment.rb
db/migrate/20190703120855_add_foreign_key_to_provider_and_provider_enrichment.rb
db/schema.rb

Database integrity
Add foreign keys for -
```ruby
provider_enrichment.provider_id
course_enrichment.course.id
```
🚢

[1716] Missing foreign keys

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/provider_enrichment.rb
spec/factories/provider_enrichments.rb
spec/models/course_spec.rb
spec/models/provider_enrichment_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb

**Part 1** 
We want to do all the course publishing in Rails instead of C#. This PR focuses on syncing a single course to search and compare.
- Uses the new S&C service to hit S&C directly rather than via ManageAPI
- Adds validations to only sync valid courses (findable & a DfE subject)

1489 Sync a single course to S&C from mc-be

---

app/controllers/api/v2/courses_controller.rb
app/controllers/api/v2/providers_controller.rb
app/controllers/api/v2/recruitment_cycles_controller.rb
app/controllers/api/v2/sites_controller.rb
app/policies/recruitment_cycle_policy.rb
app/serializers/api/v2/serializable_recruitment_cycle.rb
config/routes.rb
spec/policies/recruitment_cycle_policy_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/requests/api/v2/providers_spec.rb
spec/requests/api/v2/recruitment_cycle_spec.rb
spec/serializers/api/v2/serializable_recruitment_cycle_spec.rb

This work is to support rollover and this builds on the first PR by adding routes and changing controllers that operate within a recruitment cycle to instantiate a recruitment cycle, defaulting to the current one if none is provided.
The route added looks like this:
```
/api/v2/recruitment_cycles/:recruitment_cycle_year/providers/:provider_code/courses/:code
/api/v2/recruitment_cycles/:recruitment_cycle_year/providers/:provider_code/sites/:id
```
(not sure why site has `id`, that feels like it's wrong, but that's outside the scope of this PR)
This is being merged into the intermediary branch until this whole package is ready to merge into master. It's been cut up into multiple PRs to be easier to review.
I've tried to keep the commits pretty isolated, try reviewing them individually if …

[1564] [Part 2] add routes and recruitment cycles to controller

---

lib/mcb/commands/courses/edit.rb
spec/lib/mcb/commands/courses/edit_spec.rb

As we implement rollover by creating duplicate providers and courses, mcb will begin to return duplicate results for providers list or courses list. Also, when expecting to retrieve a single provider, course, site, it will receive multiple which is bound to break things.
Change the current behaviour in `mcb courses edit` to edit only providers in the current recruitment cycle so that things don't break.

[1732] make mcb courses edit default to current recruitment cycle

---

app/controllers/api/v2/recruitment_cycles_controller.rb
app/policies/recruitment_cycle_policy.rb
config/routes.rb
spec/factories/providers.rb
spec/policies/recruitment_cycle_policy_spec.rb
spec/requests/api/v2/recruitment_cycle_spec.rb

@dankmitchell pointed out that he could use a list of the recruitment cycles available for a provider in the front-end.
Add an index view for `recruitment_cycles`, both a global list and a provider-specific list.

[1564] add /recruitment_cycle index listing

---

spec/requests/api/v2/providers/sites_spec.rb

Test is flagging as sites are building an extra provider when created.
- Sites are now built into the provider.

[1761] Build sites to stop duplicate code validation error

---

app/models/site.rb
spec/models/site_spec.rb
spec/requests/api/v2/providers/sites_spec.rb

We have a bunch of legacy sites in the db that are invalid because they're missing a value for `address3`, and it's becoming increasingly difficult to work-around this validation. Fox example for the rollover, copying the sites is failing because they're invalid, and even creating the data in a spec is painful.
Remove the presence validation we have on `site.address3`.
I'm looking for some validation that this is a good idea, let me know if you think that there's a better approach to this, or if we should just suck it up and do the work to disable validations for tests & rollover.

[1765] remove site address3 validation

---

app/controllers/api/v1/courses_controller.rb
app/models/course.rb
app/models/provider.rb
app/models/site.rb
app/serializers/course_serializer.rb
db/migrate/20190711074433_change_course_accrediting_provider_id_to_code.rb
db/schema.rb
spec/factories/courses.rb
spec/models/course_spec.rb
spec/models/site_spec.rb
spec/requests/api/v2/providers/courses/update_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/serializers/course_serializer_spec.rb

Because when we link it by ID, we link it to a provider in a specific recruitment cycle, which makes rolling-over a bit more complicated. By changing this to provider_code it becomes a simpler relationship that doesn't risk being out-of-sync.
Change `accrediting_provider_id` to `accrediting_provider_code` in `Course`.
Because `Course#accrediting_provider` is now a dynamic association, we can't pre-load it, which leads to a degradation in performance which will probably be most felt on the courses endpoint for api v1. However, with local testing it doesn't seem to bad since Rails can cache these SQL lookups when we're looking up the same provider.
```
[active_model_serializers]   Provider Load (0.2ms)  SELECT  "provider".* FROM "provider" WHERE "provider"."provider_code" = $1 AND …
```

[1763] change accrediting provider assocation to use code

---

db/migrate/20190711074433_change_course_accrediting_provider_id_to_code.rb
db/schema.rb

Just to keep the C# app happy for now, we'll remove it once we've deployed the
change to use accrediting_provider_code.
Re-add the `accrediting_provider_id` to the `courses` table until we've re-deployed the new C# changes to not use it. It's values will be populated using the associated `accrediting_provider` on a course.

[1564] re-add accrediting_provider_id on courses

---

app/models/course.rb
db/schema.rb
spec/models/course_spec.rb

Super handy at the console, and maybe other places too!
Add a command to conveniently get a course using it's recruitment cycle, provider code and course code.
The `schema.rb` change came along for the ride and I can't be bothered to see if there's a better way to sort it.

Add Course.get_by_codes convenience method

---

lib/mcb.rb
lib/mcb/commands/apiv1/courses.rb
lib/mcb/commands/apiv1/courses/list.rb
lib/mcb/commands/apiv1/providers.rb
lib/mcb/commands/courses/list.rb
lib/mcb/commands/providers/list.rb
spec/lib/mcb/commands/apiv1/courses/find_spec.rb
spec/lib/mcb/commands/apiv1/courses/list_spec.rb
spec/lib/mcb/commands/apiv1/providers/find_spec.rb
spec/lib/mcb/commands/apiv1/providers/list_spec.rb
spec/lib/mcb/commands/courses/list_spec.rb
spec/lib/mcb/commands/providers/list_spec.rb

Rollover wasn't yet reflected in MCB.
Allow the specification of the current recruitment year, or default to the current recruitment year.
Main concern is test style.

[1731] Add option to change recruitment year for list commands

---

lib/mcb/base_cli.rb
lib/mcb/commands/courses/create.rb
lib/mcb/courses_editor.rb
spec/lib/mcb/commands/courses/create_spec.rb
spec/lib/mcb/courses_editor_spec.rb

New course creation is currently being done through user support using `mcb` dev tooling. The tooling itself is sitting on a code branch that isn't the `master` branch and needs constant updating/rebasing.
The tooling branch code is also missing automated tests, meaning it needs to be manually tested after every change.
Add an `mcb` command for creating new courses on a given provider.
It was a slog getting here 😅 
~This PR ought to be reviewed but probably not merged until the Rollover stuff has been merged, because the recruitment cycle stuff will conflict.~ The `mcb` command adds a new course to the current cycle by default.

[1657] Add 'mcb courses create' subcommand for creating new courses

---

lib/mcb.rb

This verbosity makes the commands that use apiv1 nearly unusable. The raw JSON results can already be displayed with the `--json` option.
Remove unnecessary verbose output.

Remove extra verbose of request response from apiv1 iterator

---

lib/mcb.rb
lib/mcb/commands/az/apps/psql.rb
spec/lib/mcb/commands/az/apps/psql_spec.rb

Restoring an azure postgres backup keeps all the settings and passwords but gives a new hostname.
replaces #575 
Make it easy to use mcb psql to connect to one of the backups.
:ship:

1740 mcb psql connect to backup

---

lib/mcb/commands/courses/create.rb
spec/lib/mcb/commands/courses/create_spec.rb

We will be seeing course creation requests from current and next recruitment cycles from now on.
Make `mcb courses create` cycle-aware.
Inspired by #614

[1732] Make 'mcb courses create' cycle-aware

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/course_enrichment.rb
spec/factories/course_enrichments.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/update_spec.rb

Rolled-over courses should have their content-status of "Rolled-Over".
Change the content-status on courses to display "Rolled-Over" if their enrichments have the status "rolled-over".
#589 needs to be merged and this rebased before this can be merged.

[1805] rolled over course status

---

spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb

Course does not currently have a test to check behaviour if recruitment cycle is in the PR
Add the test.

[1721] Add test to course for recruitment year in params

---

app/controllers/api/v2/courses_controller.rb
app/models/recruitment_cycle.rb
spec/models/recruitment_cycle_spec.rb

This is to allow users to manage their course sites without seeing an error due to the sync currently failing.
Checks for the recruitment cycle in the controller. Adds a helper method to the model to check if it's current.
I fruitlessly attempted to write a request spec for this but could not figure out why the request would result in a 404 when I would set the provider to the 2020 cycle.

[1797] Don't sync courses not in current recycle

---

app/serializers/provider_serializer.rb
spec/lib/mcb/commands/apiv1/providers/find_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

https://github.com/DFE-Digital/manage-courses-backend/blob/master/docs/api.md#example-response-body-2  
This document specifies 'admin_contact' be the admin type however we are producing 'admin'.  
This pull request serialises the 'admin' type as 'admin_contact'.  
Because MCB's displayed types are coupled to the serialiser this has had he knock-on effect of changing the type displayed for MCB but I believe this is minor.

[1826] Fix mismatch between api v1 docs and api v1 implementation

---

app/models/course.rb
app/serializers/api/v2/serializable_course.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

Standards are defined in the ITT criteria:
https://www.gov.uk/government/publications/initial-teacher-training-criteria/initial-teacher-training-itt-criteria-and-supporting-advice#c11-gcse-standard-equivalent
Further education has no minimum requirements (they don't award QTS)
Secondary requires Maths and English
Primary requires Maths, English and Science
All are to a grade 4 level (or C)
| Level | Maths | English | Science
|--|--|--|--|
| Secondary | 1-3 | 1-3 | Not set, or not required |
| Primary | 1-3 | 1-3 | 1-3 |
| Further education | Not required | Not required | Not required |
Codify this logic and expose for frontend.
Follow-up to https://github.com/DFE-Digital/manage-courses-frontend/pull/473

[1691]  Codify required GCSE subjects

---

lib/mcb/commands/courses/audit.rb
lib/mcb/commands/courses/edit.rb
lib/mcb/commands/courses/show.rb
lib/mcb/commands/courses/touch.rb
spec/lib/mcb/commands/courses/audit_spec.rb
spec/lib/mcb/commands/courses/edit_spec.rb
spec/lib/mcb/commands/courses/list_spec.rb
spec/lib/mcb/commands/courses/show_spec.rb
spec/lib/mcb/commands/courses/touch_spec.rb
spec/lib/mcb/commands/providers/audit_spec.rb
spec/lib/mcb/commands/providers/edit_spec.rb
spec/lib/mcb/commands/providers/list_spec.rb
spec/lib/mcb/commands/providers/show_spec.rb
spec/lib/mcb/commands/providers/touch_spec.rb
spec/support/mcb_command.rb

A number of MCB commands are not recruitment cycle aware.  
Make all `mcb course` commands recruitment cycle aware and write any missing tests.  
`sync_to_find` has been ignored for the time being because this is still in C# land.

[1731] Recruitment cycles for other course commands

---

db/migrate/20190723092536_fix_fe_course_requirements.rb
db/schema.rb

There are no minimum GCSE requirements for further education courses. UCAS advises providers to set these to code 9 (not_required).
We're going to remove the ability to edit these codes for FE, but need to make the data consistent first.
```
== 20190723092536 FixFeCourseRequirements: migrating ==========================
-- setting further education course requirements to not_required
-> 9.5594s
== 20190723092536 FixFeCourseRequirements: migrated (9.5596s) =================
```
Before:
```
["equivalence_test", "equivalence_test", nil, 22],
["expect_to_achieve_before_training_begins", "expect_to_achieve_before_training_begins", nil, 20],
["not_required", "expect_to_achieve_before_training_begins", nil, 20],
["not_required", "not_required", nil, 16], …
```

[1804] Set further education requirements to not_required

---

bin/mcb

Had accidentally clipped first items in list for help of subcommands.
It was quick to fix and annoying me.
It's a bit of a hack doing the string compare but it's the first thing I could think of and this isn't user value so didn't want to spend more time on this. Suggestions welcome :pray: 
E.g. `bin/mcb az -h` only showed help for subcommands rather than the
direct descendants
before:
```
bin/mcb -h
...
SUBCOMMANDS
apps pg_dump                      backup the psql server for an app
apps config                       read webapp config from azure,...
```
after:
```
bin/mcb -h
...
INDEX
bin/mcb                         wrapper for management of manage-curses-backend app
---
bin/mcb apiv1                   Commands that target the V1 providers endpoint
bin/mcb apiv1 courses           Operate …
```

Fix showing subcommands of subcommands in help

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
config/locales/en.yml
db/migrate/20190724112016_fix_nil_entry_requirements.rb
db/schema.rb
lib/mcb/courses_editor_cli.rb
spec/factories/courses.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v2/providers/courses/update_gsce_requirements_spec.rb

A follow up to #631.
- Add validations to maths, english and science
- Maths and english must always be set, science only on Primary courses
- New validations make some existing courses invalid, include a data migration to correct those courses (22 per cycle)
- Don't include "not_set" option for Maths and English when creating courses in MCB (this can't use the gcse_subjects_required method as the course level is determined by subjects which are only added after creation)
- DRY up the existing spec
There's a few gotchas found while working on this, which led to some frustrating rabbit holes:
- When a enum is assigned to nil, (not_set: nil), a `presence` validation won't work as expected – 'not_set' gets passed through and becomes nil after validations run
- When creating a course in MCB …

[1804] Add validations for GCSE entry requirements

---

app/models/provider_enrichment.rb
db/migrate/20190719100923_change_provider_id_to_not_null.rb
db/schema.rb
spec/factories/provider_enrichments.rb
spec/models/provider_enrichment_spec.rb

This was previously rolled back due to the data model changes not having been implemented in the c# code. This caused provider_enrichments to have nil in the provider_id column. The C# work has now been merged and i've cleared up the data on prod and qa. 
- Add a not null constraint to the provider_id column on the provider enrichment table

[1752] Add not null constraint to provider_id

---

app/controllers/api/v1/courses_controller.rb
app/models/course.rb
lib/tasks/govuk_lint.rake
spec/factories/site_statuses.rb
spec/models/course_spec.rb
spec/requests/api/v1/course_spec.rb

When UCAS requests course data we should not provide courses that have been marked 'new' as these haven't yet been published (and also have the potential to be discarded instead).
This PR ensures that courses with a status of 'new' are not emitted by the v1 courses endpoint.  
This has the side effect of causing empty courses not to be sent, but this is correct behaviour. I had to correct tests that were dependent on the previous behaviour.

[1822] Don't send courses marked 'new' to UCAS

---

app/models/course.rb
app/models/edit_course_options.rb
app/serializers/api/v2/serializable_course.rb
spec/models/edit_course_options_spec.rb
spec/requests/api/v2/providers/courses_spec.rb

Backend should be responsible for the business logic which determines which options are available for each course. Eg which course outcomes should be listed when editing the outcome.
We need a place for these and we need to share them with the frontend.
Add an EditOptions class and use it pass through the options for editing entry requirements.
Goes alongside https://github.com/DFE-Digital/manage-courses-frontend/pull/481

Expose edit options for entry requirements

---

Dockerfile
lib/mcb.rb
spec/bin/mcb_spec.rb

For the convenience of users, especially those new to MCB, we should provide a way for commands to be completed.  
Add tab autocomplete for main commands.  
Currently stderr spills into the terminal during tests, I'm not sure how to disable it in `with_stubbed_stdout`. This also only performs completions for main commands as Readline is not context-aware.

[1734] Add completions for MCB

---

Gemfile
Gemfile.lock
app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/provider.rb
app/policies/course_policy.rb
app/serializers/course_serializer.rb
config/routes.rb
db/migrate/20190718142118_add_discarded_at_to_course.rb
db/schema.rb
db/seeds.rb
spec/factories/courses.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/course_serializer_spec.rb

* Allowing deletion of courses through the Ruby gem discard.
* :sweat_smile: damn hot https://www.youtube.com/watch?v=DpktBGInl60
* Scorchio :hot_pepper: https://www.youtube.com/watch?v=kZMUAd7OJc8
Pairing @timabell & @NyWeb 
- Include gem
- Used the gems callbacks for throwing error when a course can't be deleted
- Forced kept as a scope for provider
- Minor clean-up of test
- Added tests
* Simplest implementation of if `discard is allowed` was to throw an exception in `before_discard`
* Feedback on the test setup always welcomed.
* Turn off whitespace to see the change to `spec/requests/api/v2/providers/courses_spec.rb` more clearly (indented large json block because it's wrapped in a new block)

[1813] delete a course

---

spec/lib/mcb/commands/courses/list_spec.rb

MCB spec randomly fails as string checks where a bit wobbly. We're using Faker for generating strings (programming languages). D & C gives false positives, and there are only so many languages.
This got me and @timabell many times when we were trying to push forward the Delete Courses Backend work, and left us rerunning TravisCI over and over, delaying the eventual merge. 
Gave explicit names to courses to give fewer false positives, making us
I could've created more randomness in the factory too, but that seemed like the wrong way.

[1843] mcb specs fails intermittently due to pseudo-random test-data

---

app/models/course.rb
app/serializers/api/v2/serializable_course.rb
app/serializers/course_serializer.rb
db/migrate/20190726104939_add_age_range_in_years_to_course.rb
db/schema.rb
spec/factories/courses.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/serializers/course_serializer_spec.rb

Better age range for courses
Add new age range course for V2 so that we don't impact V1(UCAS)
I see us handling this in the same way we do for course length, have several hardcoded radion buttons on the frontend and just send a string value to the backend. An ENUM would have been nicer but the "other" makes this difficult.
🚢

[1844] Add new age ranges to course

---

app/controllers/api/v2/providers_controller.rb
app/models/provider.rb
app/models/provider_enrichment.rb
app/policies/provider_policy.rb
config/locales/en.yml
config/routes.rb
spec/factories/provider_enrichments.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/providers/publish_spec.rb
spec/requests/api/v2/providers/publishable_spec.rb
spec/requests/api/v2/providers/sites_spec.rb
spec/support/shared_examples/unauth.rb

These will be called by the frontend to publish the latest provider enrichment.
Adds `#publish` and `#publishable` actions to the provider controller. `#publish` is a no-op.
Does not actually implement the publish logic, that will be done as a separate PR; this is just to facilitate the frontend validations work.

[1792] Add provider publish and publishable actions

---

spec/bin/mcb_spec.rb

MCB tests were spilling out into the terminal when MCB sent output to stderr.  
Stub out `stderr` & some tweaks to the tests.

[1859] Fix spurious output of MCB tests

---

lib/tasks/prepare_postgres.rake

We've taken a couple stabs :hocho: at fixing how we create the use role when we create the db, esp on dev. :imp: 
* Create the user before the dbs are created, and then set the user's password afterwards. This sequence seems to be the right way to get things done.
* Unholy deeds :latin_cross:

🗡 fix dev role creation for db:create (and dropping for db:drop) 

---

db/migrate/20190730133727_update_start_date_for_rolled_over_courses.rb
db/schema.rb

Start dates for the next cycle's courses were still set to the same value as last cycle's courses.
Add a migration to update courses in the next cycle to have a start date one year after their existing date.
Example courses from before this migration is run:
```
[10] pry(main)> Course.get_by_codes('2020', '2JF', '39SS').start_date
=> Sun, 01 Sep 2019 00:00:00 UTC +00:00
[19] pry(main)> Course.get_by_codes('2020', '2BN', '2YVF').start_date
=> Thu, 01 Aug 2019 00:00:00 UTC +00:00
[11] pry(main)> Course.get_by_codes('2020', '2JF', '39SS').start_date
=> Tue, 01 Sep 2020 00:00:00 UTC +00:00
[20] pry(main)> Course.get_by_codes('2020', '2BN', '2YVF').start_date
=> Sat, 01 Aug 2020 00:00:00 UTC +00:00
```

Add a year to the start-dates of rolled-over courses.

---

app/controllers/api/v2/providers_controller.rb
app/models/provider.rb
app/policies/provider_policy.rb
config/routes.rb
spec/models/provider_spec.rb
spec/policies/provider_policy_spec.rb
spec/requests/api/v2/providers/sync_courses_with_search_and_compare_spec.rb

**Part 2 do not merge until #569 has been merged **
We want to do all the course publishing in Rails instead of C#. 
This PR adds an endpoint to sync all the providers courses which are `syncable?` to search and compare.

[1489] Add endpoint for provider to sync courses to S&C

---

app/controllers/api/v2/courses_controller.rb
app/controllers/api/v2/providers_controller.rb
app/models/provider.rb
app/models/provider_enrichment.rb
spec/models/provider_enrichment_spec.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers/publish_spec.rb
spec/requests/api/v2/providers/sync_courses_with_search_and_compare_spec.rb

As it stands the provider publish endpoints are just stubs.  
- Publish the enrichments for a provider    
- Sync SearchAndCompare

[1852] Add provider publish logic

---

spec/factories/sites.rb
spec/models/site_spec.rb

Every now and then some tests fail because duplicate site codes can be generated when building multiple sites that aren't persisted.
Use a sequence when generating a site's code instead of relying on randomness. Also, use randomness to try to ensure we don't accidentally start to rely on deterministic site codes (always expecting the site code to be 'A') unless explicitly set.

make a better effort to not create duplicate site codes in factories

---

spec/controllers/api/v2/application_controller_spec.rb

Manage course api calling manage courses backend
Pass thro user info in order to allow for authenticated calls to backend.
Api will be proxying an authenticated user to backend similar aspect as to the frontend.
Api user is already authenticated the test is to illustrate the expected behaviour of api generating a token that can be consumed by backend. 
Related to 
https://github.com/DFE-Digital/manage-courses-api/pull/325

[1641] Added additional tests to illustrate manage-courses-api integration

---

app/controllers/api/v2/providers_controller.rb
app/deserializers/api/v2/deserializable_provider.rb
app/models/provider.rb
app/models/provider_enrichment.rb
app/serializers/api/v2/serializable_provider.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers/update_accrediting_providers_spec.rb
spec/requests/api/v2/providers_spec.rb
spec/serializers/api/v2/serializable_provider_spec.rb

Full read/create/update for accrediting provider enrichments.
Because of all the questions about feasibility & shape of update when working on just the list of names/codes we gave up on splitting the card in three and this PR is for the whole feature.
This is api work is to support re-implement https://bat-qa-mcui-as.azurewebsites.net/organisation/1dq/about in rails
* `providers#show`: Include code/name, & enrichment if available, of accrediting bodies for a provider.
* `providers#update`: Update enrichments in database when accredited body info is posted as part of provider#update

[1808] accrediting provider enrichments

---

app/models/provider.rb
app/models/recruitment_cycle.rb
app/models/user.rb
app/policies/provider_policy.rb
lib/mcb/commands/providers/create.rb
lib/mcb/provider_cli.rb
lib/mcb/provider_editor.rb
spec/lib/mcb/commands/providers/create_spec.rb
spec/lib/mcb/provider_editor_spec.rb
spec/models/provider_spec.rb
spec/models/recruitment_cycle_spec.rb
spec/models/user_spec.rb
spec/policies/provider_policy_spec.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/provider_spec.rb

Need to provide a command via `mcb` to create a Provider (and organisation).
- Add create command for Providers 
- Automatically set `accrediting_provider` and `scitt` based on Provider Type
- `User.admins` scope
- ~~Should this belong here: https://github.com/DFE-Digital/manage-courses-backend/pull/683/files#diff-5c08de53fa6bea147e31fe1d5930422aR30-R32~~

[1798] mcb providers create

---

app/models/course.rb
app/serializers/api/v2/serializable_course.rb
app/serializers/course_serializer.rb
db/migrate/20190806102256_add_applications_open_from_to_courses.rb
db/schema.rb
db/seeds.rb
spec/factories/courses.rb
spec/lib/mcb/courses_editor_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/serializers/course_serializer_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb

Courses have a date that applications are accepted from. This date is currently modelled onto the `SiteStatus` instead of the course, so it's duplicated a lot.
- Add new attribute `applications_open_from`, replacing the current method which pulls from the site statuses
- Default to next recruitment cycle
- Update current references to `applications_open_from`
Am open to suggestions on any changes/incorrect assumptions I have made given I'm still getting my head around the data model :tada:

[1905] expose applications accepted from

---

db/migrate/20190806102256_add_applications_open_from_to_courses.rb

Following the migrations added in #684 it was discovered that they ran poorly on production data (300-400 seconds on my laptop). Indicating that it would be good to improve performance.
- Update the migration to use `includes` to pre-load several of the relations
- Sort `site_statuses` in memory
- Skip validations when updating
- Update all courses for the next recruitment cycle in one batch

[1905] Improve performance of applications accepted from migration

---

app/models/user.rb
spec/models/user_spec.rb

Noticed Regex did not escape any character `.`
Escape any character regex 
Edge case spec added

[1928] Escape peroid in User email regex

---

Gemfile
Gemfile.lock
app/models/organisation.rb
lib/mcb/commands/courses/list.rb
lib/mcb/provider_cli.rb
lib/mcb/provider_editor.rb
spec/factories/courses.rb
spec/lib/mcb/provider_editor_spec.rb
spec/models/organisation_spec.rb

Providers were created with an Organisation without a name.
Before: Was able to create/assign Providers to organisation with an empty name
After: Must provide an Organisation name to create a new Provider

[1798] Make sure an Org Name has been entered via MCB providers create

---

config/settings/qa.yml

Update qa environment to use non-Azure domains
Change base_url value in qa.yml file from default azure web app .azurewebsites.net urls to service domains
base_url updated in qa.yml file only. New staging service domain urls are as follows:
mcapi: https://api.qa.publish-teacher-training-courses.service.gov.uk
mcbe: https://api2.qa.publish-teacher-training-courses.service.gov.uk
mcfe: https://www2.qa.publish-teacher-training-courses.service.gov.uk
mcspt: https://support.qa.publish-teacher-training-courses.service.gov.uk
mcui: https://www.qa.publish-teacher-training-courses.service.gov.uk
sacapi: https://api.qa.find-postgraduate-teacher-training.service.gov.uk
sacui: https://www.qa.find-postgraduate-teacher-training.service.gov.uk

updated base_url in config/settings/qa.yml

---

app/controllers/api/v2/courses_controller.rb
app/jobs/application_job.rb
app/jobs/sync_courses_to_find_job.rb
config/environment.rb
config/environments/development.rb
config/environments/test.rb
spec/jobs/sync_courses_to_find_job_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb
spec/spec_helper.rb

We need to background this task.
Use ActiveJob to sync a course to find. This will allow us to plugin a background job processor when ready.
This doesn't include a proper background job processor, but it's a step above what we have (it'll background the task to sync the course), even if it suffers from the flaw that it could lose jobs when the app is restarted. The next PR should add a background job processor, so we may want to couple the two PRs together for release.

[1835] sync courses to find active job

---

app/models/provider.rb
spec/models/provider_spec.rb

Updating provider enrichments doesn't work for some providers.
The previously provided block was a no-op.

[1933] Fix latest_enrichment scope on provider model 

---

app/models/provider_enrichment.rb
spec/models/provider_enrichment_spec.rb

Need to add Auditing to the `ProviderEnrichment` model
Add auditing and ensure association to Provider works
Haven't tested what happens when I create/update an Enrichment as I can't get the Front End app to log me in.

[1916] Add Audits to Provider Enrichments

---

app/models/accrediting_provider_enrichment.rb
app/models/course.rb
app/models/provider.rb
app/models/provider_enrichment.rb
spec/models/provider_enrichment_spec.rb
spec/requests/api/v2/providers/update_accrediting_providers_spec.rb

Main different between this PR and the #695 
word count validation is done per accrediting provider enrichments' description
via the introduction of said class
Added word count validation for the description of an accrediting provider enrichment

[1919] Advance validation for accrediting provider description word

---

app/models/provider_enrichment.rb

Two tweaks to error messages:
> Reduce the word count for train with us
"Reduce the word count for training with you"
> Reduce the word count for train with disability
"Reduce the word count for training with disabilities and other needs"
Adds a message to the word count validation to display the correct error messages

[1945] Update error message for provider enrichments

---

app/controllers/api/v2/providers_controller.rb
spec/requests/api/v2/providers/publish_spec.rb
spec/requests/api/v2/providers/sync_courses_with_search_and_compare_spec.rb

Add job to publish a single provider's courses to find.
Use ActiveJob to sync
I do not have the whole stack running to test this but it is based heavily from https://github.com/DFE-Digital/manage-courses-backend/pull/643

[1836] Use background process to sync

---

azure/backgroundJobTemplate.json

Automate deployment of background jobs docker images onto an Azure Container Instance (ACI). ARM template has been created to deploy the ACI infrastructure using Azure Devops Release pipeline. 
New additional ARM template for for background job creation. This ARM template has no dependency and does not replace existing template for Backend app services (template.json). 
New file created under Azure folder

1837 add background job arm template

---

app/models/provider_enrichment.rb
app/validators/email_validator.rb
app/validators/phone_validator.rb
config/locales/en.yml
spec/factories/provider_enrichments.rb
spec/models/provider_enrichment_spec.rb
spec/requests/api/v2/providers/publish_spec.rb
spec/requests/api/v2/providers/publishable_spec.rb
spec/requests/api/v2/providers/update_spec.rb
spec/validators/email_validator_spec.rb
spec/validators/phone_validator_spec.rb

C# has validations for the email and telephone numbers for provider enrichments - we need to add these to the ruby application.
- Validate email address and telephone formats when they are updated by the user
- These are not updated on create/all updates as they'd be triggered by updating values that are not on the details page, e.g. About your organisation
- The error messages have been taken from [The GOV.UK Design System](https://design-system.service.gov.uk/patterns/email-addresses/)

[1944] Add provider enrichment details validations

---

app/controllers/api/v2/users_controller.rb
spec/requests/api/v2/users/accept_rollover_screen_spec.rb
spec/requests/api/v2/users/accept_transition_screen_spec.rb

If a user tries to accept the transition screen while already rolled over, it currently throws a sentry error. This is undesirable behaviour.
- Make the accept transition screen idempotent

[1438] Make the accept transition screen idempotent

---

app/policies/access_request_policy.rb
spec/policies/access_request_policy_spec.rb
spec/requests/api/v2/access_request_spec.rb

Currently if a non admin user tries to create an access request it throws an error.
- Tweak the policy to allow any user to create an access request.

[1972] Allow non-admin users to create access requests

---

app/controllers/api/v2/courses_controller.rb
app/controllers/concerns/study_mode_vacancy_mapper.rb
app/deserializers/api/v2/deserializable_course.rb
spec/requests/api/v2/providers/courses/update_study_mode_spec.rb

Users need to be able to update their course to full time or part time
- Allow study mode to be updated
- Update site statuses to the correct vac_status.
If updated to full time all site statuses except those with no vacancies should have full time vacancies.
Same with part time except part time vacancies.
There is currently no logic to deal with full time and part time courses. This will be dealt with through support until users have the functionality to select both full time and part time vacancies on each site attached to a course.

[1900] update study mode

---

app/models/course.rb
app/serializers/course_serializer.rb
db/migrate/20190812153252_add_is_send_to_course.rb
db/schema.rb
spec/factories/courses.rb
spec/factory_specs/subject_spec.rb
spec/models/course_spec.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/serializers/course_serializer_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb

In able to easily edit a Course's SEND state. We need to remove the legacy implementation of SEND as a subject.
What we use for SEND for the C# App: https://github.com/DFE-Digital/manage-courses-backend/blob/c976d4ab6da8224db2a35b0e5499410c86627661/app/serializers/search_and_compare/course_serializer.rb#L52 
And the Subjects we pass for the C# App: https://github.com/DFE-Digital/manage-courses-backend/blob/c976d4ab6da8224db2a35b0e5499410c86627661/app/serializers/search_and_compare/course_serializer.rb#L226-L238
~~So I don't think there would be any impact to the C# App.~~
- Add test to API V1 to ensure no regressions
- Add DB Column `is_send` as boolean to Course
- Update tests to reflect this new behaviour 
Are microservices effected by this change?

[1932] move send from subject to course

---

db/migrate/20190815091422_set_application_end_dates_on_recruitment_cycles.rb
db/schema.rb

Currently recruitment cycles application_end_date is set to nil. Some code is reliant on this being set for validations.
- Creates a migration that sets the application_end_date

[1856] Migration to set application end date

---

app/models/provider_enrichment.rb
spec/requests/api/v2/providers/update_spec.rb

Telephone number was not triggering validation on creation of an enrichment from the `enrichment` (`enrichment.save`)
Leading to the enrichment being saved then triggering validation from the provider (`@provider.valid?`) 
On the controller
Making phone calls again 
First commit to flush it out
Second commit to clean it up

1982 bad phone

---

lib/mcb/courses_editor.rb
lib/mcb/courses_editor_cli.rb
spec/lib/mcb/courses_editor_spec.rb

Based on https://trello.com/c/1HMd3Qmk/1932-remove-send-u3-subject-and-add-it-as-attribute-to-course and #704. 
~Cannot merge until #704 has been merged in.~
- Add ability to Edit a Course to be SEND
- Add ability to Create a Course as SEND
- ~Uses #704 as base branch so only look at `lib/mcb` changes~

[1952] edit course send via mcb cli

---

app/controllers/api/v2/courses_controller.rb
app/deserializers/api/v2/deserializable_course.rb
app/models/course.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/update_send_spec.rb

Uses #704 as a base. Need to allow the Front End to set the `is_send` attribute on a Course.
- Add Validation to `Course#is_send` attribute to only allow explicit variables
- Add V2 Course Controller to accept `is_send` param
Do we trust the the information sent to the API will always be valid? If so, do we need to be so restrictive about settings `is_send`? 
For example, without the `#is_send=(value)` override then:
```ruby
$ course.is_send? 
=> true
$ course.is_send = 'something'
$ course.is_send?
=> false 
```

[1880] Edit SEND on course via API

---

app/models/provider_enrichment.rb
spec/models/provider_enrichment_spec.rb

`jsonb_accessor` and `ActiveRecord#enums` does not play nice. Rails can use Int/String and be fine. However, we want to store the data as Integers so the C# App can read them.
`jsonb_accessor` stores the enum as a string.
This comment is explaining the order of events. https://trello.com/c/YyfUArP7/1914-investigation-regioncode-being-saved-to-provider-enrichments-as-a-string-causing-manage-api-c-to-fail#comment-5d5669a350c3475785ca1be6
- Include a before save that will always set the `RegionCode` to be an integer

[1914] Ensure that JSON Data stores/retrieves RegionCode as Integer

---

lib/mcb/provider_editor.rb
spec/lib/mcb/provider_editor_spec.rb

When using `bin/mcb provider edit ABC -r 2020` argument to specify a Recruitment Cycle year and then editing a course from within that Provider. The Courses loaded are for the Current Recruitment Cycle.
- Always specify the Recruitment Cycle
Is there a better way to test this?

[1987] Ensure that Sub Commands contain Provider Recruitment Cycle year

---

lib/mcb/commands/users/grant.rb
lib/mcb/grant_access_wizard.rb
spec/lib/mcb/commands/users/grant_admin_spec.rb
spec/lib/mcb/commands/users/grant_spec.rb

Interim measure - give DfE people access to all orgs for support / research etc.
* Add `--admin` flag - `bin/mcb users grant --admin someone@digital.education.gov.uk`
* Move provider into `-p` flag (because of the way the cli lib works) - `bin/mcb users grant  someone@example.org -P AA1`
:ship: ?

1865 mcb god users

---

app/controllers/api/v2/courses_controller.rb
app/models/concerns/courses/edit_options.rb
app/models/concerns/courses/edit_options/age_range_concern.rb
app/models/concerns/courses/edit_options/entry_requirements_concern.rb
app/models/concerns/courses/edit_options/qualification_concern.rb
app/models/concerns/courses/edit_options/start_date_concern.rb
app/models/concerns/courses/edit_options/study_mode_concern.rb
app/models/concerns/with_qualifications.rb
app/policies/course_policy.rb
app/serializers/api/v2/serializable_course.rb
app/services/subject_mapper_service.rb
config/routes.rb
spec/models/concerns/with_qualifications_spec.rb
spec/policies/course_policy_spec.rb
spec/requests/api/v2/providers/courses/new_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/services/subject_mapper_service_spec.rb

From the ticket:
> ## What
>
> Add "new" endpoint for courses to mcbe that returns default `edit_options` to be
> used when generating the "new" pages on the frontend.
From the ticket:
> ## Why
> 
> We are keeping the logic behind course states constrained to the backend, so we
> need to be able to query it to find out what outcomes are available, for courses
> as we step the user through the wizard steps.
This is required by [1938 Add "new" page for course outcomes](https://trello.com/c/4HGV6r3S/1938-m-add-new-page-for-course-outcomes).

[1997] add endoint for new course

---

Gemfile
Gemfile.lock
app/controllers/api/v2/sessions_controller.rb
app/mailers/welcome_email_mailer.rb
app/services/send_welcome_email_service.rb
config/application.rb
config/environments/test.rb
config/initializers/mailers.rb
config/settings/development.yml
config/settings/test.yml
spec/factories/users.rb
spec/mailers/welcome_email_mailer_spec.rb
spec/requests/api/v2/session_spec.rb
spec/services/send_welcome_email_service_spec.rb

Sending the welcome email is currently handled by the C# application and needs to be rewritten.
- Add a new service object for sending welcome emails
-  Add [`govuk_notify_rails`](https://github.com/ministryofjustice/govuk_notify_rails) gem
- Send emails via GOV.UK Notify when logging in for the first time
- Add relevant test fixtures for testing GOV.UK Notify emails
**To test locally**
- Create `config/settings/development.local.yml`
- Set the values for `govuk_notify.welcome_email_template_id` and `govuk_notify.api_key` to the correct values
- Set your users `first_login_date_utc` to `nil`
- Login

[1947] Reimplement "Welcome to find" email

---

lib/mcb/commands/users/revoke.rb

The `mcb users rekove` usage text doesn't work as is.
Align the usage text with the command params.

[XXX] Fix `mcb users revoke` command usage

---

README.md
app/services/send_welcome_email_service.rb
config/settings.yml
config/settings/development.yml
spec/factories/users.rb
spec/requests/api/v2/session_spec.rb
spec/services/send_welcome_email_service_spec.rb

When logging in locally - it was found that if it was the first login it would throw a 500 but still update the email received.
- Update the README to expose the environment variables that will need to be set in order to login for the first time locally
- Don't update the welcome email sent time until after it's sent

[1947] Ensure welcome emails are retried

---

app/models/provider.rb
app/serializers/course_provider_serializer.rb
app/serializers/provider_serializer.rb
spec/lib/mcb/provider_editor_spec.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers/update_spec.rb

The `Provider#scheme_member` field stores whether the given provider is a member of UCAS's ITT scheme (and is consequently able to accept applications to its courses).
Introduce an enum for the attribute, which defines default scopes that can be used for filtering.

[XXX] Add enum for Provider#scheme_member

---

lib/mcb.rb

We're moving to the new env, which has different `webapp` and `rgroup`.

Add new production environment to mcb

---

app/models/provider.rb
spec/lib/mcb/commands/users/revoke_spec.rb
spec/models/provider_spec.rb

As it stands providers that have been rolled over cannot be distinguished from their initial versions.
Change `Provider.to_s()` to print the code, name and recruitment cycle e.g: `[A01] Kings College London (2019/20)`

[1876] Add recruitment cycle to Provider.to_s

---

app/models/nctl_organisation.rb
config/initializers/inflections.rb
spec/models/nctl_organisation_spec.rb

The `nctl_organisation` table contains NCTL ids associated with particular organisations. 
These are useful for linking Find organisations to other DfE services because. The Support app already displays this information.
Add the model and spec for it.

[XXX] Add NCTLOrganisation model

---

app/controllers/api/v2/providers_controller.rb
app/models/provider_enrichment.rb
app/services/provider_enrichments/rollover_enrichment_to_provider_service.rb
db/migrate/20190820095253_copy_enrichments_to_next_cycle.rb
db/schema.rb
spec/factories/provider_enrichments.rb
spec/models/provider_enrichment_spec.rb
spec/requests/api/v2/providers/update_spec.rb
spec/services/provider_enrichments/rollover_enrichment_to_provider_service_spec.rb

In order to make providers cycle aware (https://trello.com/c/wXf4ncic/1854-s-make-provider-cycle-aware) we would like to ensure that when they go to the "About your org" pages for the next cycle they are met with data, rather than it being blank. 
- Adds migration which goes over current providers and copies the last enrichment to the current cycle
- Copying only the last mirrors how courses were rolled over
- Check out the branch to your local machine
- Ensure you have production-like data (in terms of quantity)
- Run the migrations

[2003] Add migration to copy provider enrichments

---

app/controllers/api/v2/courses_controller.rb
app/models/accrediting_provider_enrichment.rb
app/serializers/api/v2/serializable_course.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_provider_spec.rb

We'd like the ability to modify a course's accredited provider, in order to do this the frontend requires a list of all the accredited providers for a given provider's courses and the ability to update the accredited provider's course.
Permit the modification of a course's `:accredited_provider_code`, also add testing to afford some confidence when editing providers serialisation for accrediting bodies & course updating in future.

[2009] Edit course accredited body

---

app/models/provider.rb
spec/models/provider_spec.rb

Feedback from previous PR for this ticket  
https://github.com/DFE-Digital/manage-courses-backend/pull/748#discussion_r318905976  
Show providers in the format `Kings College London (A01) [2019/20]` rather than `[A01] Kings College London (2019/20)`

[1876] Make Provider.to_s consistent with UI

---

app/models/course.rb
app/models/nctl_organisation.rb
spec/lib/mcb/editor/provider_editor_spec.rb
spec/models/course_spec.rb
spec/models/nctl_organisation_spec.rb

As it stands courses that have been rolled over cannot be distinguished from their initial versions.
Change `Provider.to_s()` to print the provider code, course code, name and recruitment cycle e.g: `[A1/QM1] Introductory Quantum Mechanics (2019/20)`

[1877] Add recruitment cycle to Course.to_s

---

docs/api.md
spec/lib/mcb/commands/courses/list_spec.rb

Add the "created-at" timestamp to the serialised course information documentation for API V1.
This will help UCAS detect when a course is new.
This is just the documentation bit, for UCAS's benefit.

[2045] add created_at and changed_at to apiv1 docs for courses

---

app/serializers/provider_serializer.rb
docs/api.md
spec/requests/api/v1/provider_spec.rb
spec/serializers/provider_serializer_spec.rb

v1 api providers endpoint
created at and changed at timestamp for providers
Added created at and changed at timestamp for providers to api v1
Amended docs to reflect changes
`/api/v1/2019/providers`

[2044] add created at and changed at timestamp for providers to api v1

---

spec/requests/api/v2/providers/courses/update_spec.rb

A time bound test will fail on the 01/09 every year.
Give it set date that will never coincide with the courses start_date

[2058] Fix failing time bound test

---

app/serializers/course_serializer.rb
docs/api.md
spec/requests/api/v1/course_spec.rb
spec/serializers/course_serializer_spec.rb

v1 api courses endpoint
created at and changed at timestamp for courses
Added created at and changed at timestamp for courses to api v1
Amended docs to reflect changes
`/api/v1/2019/courses`

[2045] add created at and changed at timestamp for courses to api v1

---

app/controllers/api/system/application_controller.rb
app/controllers/api/system/force_sync_controller.rb
config/environments/test.rb
config/routes.rb
spec/controllers/api/system/application_controller_spec.rb
spec/requests/api/system/force_sync_spec.rb

We had this functionality in the C# version via WebJobs as Azure allowed us to manually trigger it. We would like to replicate this functionality by creating an endpoint that when sent a message will trigger the jobs.  
Add the /api/v2/sync endpoint that when pinged will queue another sync

[2085] Create endpoint for triggering bulk sync

---

app/models/concerns/courses/edit_options.rb
app/models/concerns/courses/edit_options/applications_open_concern.rb
app/models/concerns/courses/edit_options/is_send_concern.rb
app/models/concerns/courses/edit_options/start_date_concern.rb
app/models/course.rb
spec/models/concerns/courses/edit_options_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb

The fields 'SEND', 'applications open' and 'start date' shouldn't be changed after they've been published.  
Wrap `course_params_assignable()` in tests and prevent the changing of `is_send`, `applications_open_from` and `application_start_date` when published.  
At the moment this only checks whether `content_status` is published to decide whether to permit the change, it may be the case that we should disable it with other statuses. Also it seems that the error message `enrichments: []` persists regardless of whether the data has any errors, this is a side issue that perhaps warrants further discussion.

[2040] Change fields to not editable when published

---

spec/requests/api/v2/providers/courses/publish_spec.rb

Providers need to be able to select publish on courses in their next cycle. 
There are no validations on the backend to stop  next cycles courses being set to published. There is simply no button for users to click on the frontend.
- Add tests to check that publish works for next cycles courses

[2068] Add tests to ensure next cycles courses can be published

---

db/migrate/20190904131906_change_contact_types_to_be_unique_to_provider.rb
db/schema.rb

There should only be able to be one contact for each UCAS contact type for each provider
- Migration to make the contact type unique to each provider_id

[2086] Make each UCAS contact type unique for a provider

---

app/models/provider.rb
app/serializers/api/v2/serializable_provider.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers_spec.rb
spec/serializers/api/v2/serializable_provider_spec.rb

UCAS have asked for providers to be able to edit their contacts on publish (admin, utt etc.)
This is the first of several cards and exposes the providers ucas contacts on the v2 api.
- Expose the providers ucas contacts on the v2 api

[2086] Expose the providers ucas contacts on api v2

---

app/controllers/api/v2/providers_controller.rb
app/models/provider.rb
app/models/provider_enrichment.rb
db/migrate/20190909105439_provider_enrichment_user_not_null.rb
db/schema.rb
spec/factories/provider_enrichments.rb
spec/models/provider_enrichment_spec.rb
spec/models/provider_spec.rb

CourseExporter in c# fell over on null user, make this impossible, move
failure to earlier.
breaking because created by user id is nil
https://github.com/DFE-Digital/manage-courses-api/blob/ffa3ea9bb5536c9365f4c0fa8de71bcc03044b64/src/ManageCourses.Api/Mapping/EnrichmentConverter.cs#L69
Data in prod already manually cleaned, but need the cleanup code in case
new records appear in prod, and also for qa/staging that  haven't been
cleaned.
:ship:

[2116] Add not null constraints to provider_enrichment user fields

---

app/controllers/api/v2/courses_controller.rb
app/policies/provider_policy.rb
config/routes.rb
spec/requests/api/v2/build_new_course_spec.rb

Add an endpoint that the course creation steps can use to build a new course to validate it and retrieve relevant metadata (like the edit options) without persisting it.
Adds the endpoint.
Nothing particular!

[2055] Add build new course endpoint

---

app/models/concerns/courses/edit_options/age_range_concern.rb
app/models/concerns/courses/edit_options/qualification_concern.rb
app/models/course.rb
app/models/subjects/course_level.rb
app/serializers/api/v2/serializable_course.rb
app/services/subject_mapper_service.rb
db/migrate/20190723092536_fix_fe_course_requirements.rb
lib/mcb/course_show.rb
spec/models/concerns/courses/edit_options/age_range_concern_spec.rb
spec/models/concerns/courses/edit_options/qualifications_concern_spec.rb
spec/models/course_spec.rb
spec/models/subjects/course_level_spec.rb
spec/services/subject_mapper_service_spec.rb

Subjects refactor
Rename `level` to `ucas_level` ready for new `level` attribute 
🚢

[2128] Rename course level to ucas_level

---

app/controllers/api/v2/providers_controller.rb
spec/requests/api/v2/providers/suggest_provider_spec.rb

We don't need more for either the autocomplete or the no-JS fallback.
`s/30/5/`
:ship:

[2053] Reduce provider search to 5 items

---

app/services/providers/copy_to_recruitment_cycle_service.rb
spec/lib/mcb/commands/providers/rollover_spec.rb
spec/services/providers/copy_to_recruitment_cycle_service_spec.rb

Previous output:
> /home/tim/repo/dfe/manage/backend/app/services/sites/copy_to_provider_service.rb:4:
> in `execute': undefined method `sites' for nil:NilClass (NoMethodError)
This was because `new_provider` was `nil` if the rollover copy of the
provider already existed.
I moved [the commented out test](https://github.com/DFE-Digital/manage-courses-backend/blob/531324991aeefe4e13555edec3430d6e975c2c60/spec/lib/mcb/commands/providers/rollover_spec.rb#L49) into an `xit`. Needs investigating but isn't a regression.
* Fix it.
* Add coverage at unit and integration level.
:ship:

[2126] mcb - fix rolling over already-rolled over providers

---

db/migrate/20190916155318_clean_up_course_subject_data_post_migration.rb
db/schema.rb

Post the subject migration taking place there are quite a few bits of erroneous data due to how the subject mapper works. 
The following needs to take place: 
2019 Course with `Primary` + one `other primary` subjects
2020 Course with be just assigned  `other primary` subject
(If a course includes primary and another subject remove the primary subject from the courses subjects)
2019 Course with `Physics`, `Biology`, `Chemistry`, `Balanced science`
2020 Course with be assigned with one `Science` subject
2019 Course with `Balanced science`
2020 Course with be assigned with `Science` subject
2019 Course with `Humanities`
2020 Course with be assigned with both `Geography`, `History` subjects
2019 Courses with any of the following
`French`
`English as a Second Language`
`German`
`Italian` …

[2130] Data cleanup post UCAS to DfE subjects migration

---

app/models/course.rb
app/models/course_subject.rb
db/migrate/20190913115905_subject_and_ucas_subject_subject_name_indexing.rb
db/migrate/20190913125905_migrate_subjects.rb
db/schema.rb

Loop thro all courses and using the existing subject mapper in order to set 
course's
`level` using `UCASSubjects::CourseLevel.new(ucas_subjects.map(&:subject_name)).ucas_level`
`course_subject` using `UCASSubjectMapperService.get_subject_list(name, ucas_subjects.map(&:subject_name))`
Migrate the old subjects structure using the new dfe subjects
Test with latest database
Apart from rewriting the `UCASSubjectMapperService` to actual `sql` this is about as fast as rails would allow.
using indexes
```
== 20190913115905 SubjectAndUCASSubjectSubjectNameIndexing: migrating =========
-- index subject name for subject and ucas subject
-- add_index(:subject, :subject_name)
-> 0.0060s
-- add_index(:ucas_subject, :subject_name)
-> 0.0050s
-> 0.0112s
== 20190913115905 …
```

2123 migration current ucas subjects dfe subjects to new dfe subjects

---

app/controllers/api/v2/application_controller.rb
spec/support/shared_examples/unauth.rb

We use the `403` status code to also highlight if a user has not accepted the T&C - to better differentiate between the cause of the `403` we need to provide more information.
- Adds in meta information to the user not accepted terms failure

[2137] Add meta information to accept terms forbidden response

---

app/controllers/api/v2/providers_controller.rb
app/deserializers/api/v2/deserializable_provider.rb
app/models/course.rb
app/models/provider_ucas_preference.rb
app/models/subject.rb
app/serializers/api/v2/serializable_provider.rb
app/serializers/course_serializer.rb
app/serializers/subject_serializer.rb
spec/factories/courses.rb
spec/factories/provider_ucas_preferences.rb
spec/factories/subjects.rb
spec/models/course_spec.rb
spec/models/provider_ucas_preference_spec.rb
spec/models/subject_spec.rb
spec/requests/api/v2/providers/update_provider_ucas_preferences.rb
spec/requests/api/v2/providers_spec.rb
spec/serializers/api/v2/serializable_provider_spec.rb
spec/serializers/course_serializer_spec.rb
spec/serializers/subject_serializer_spec.rb

A providers UCAS gt12 preferences need to be exposed and updatable via the V2 API as per our agreement with UCAS.
- Expose providers type_of_gt12
-  type_of_gt12 and gt12_response_destination can be updated
- correct incorrect annotations that have accidentally been merged into master

[2190] Expose and update ucas gt12 preferences

---

db/migrate/20190912162820_create_subject_table.rb

It was missing subject code for subjects 
Added subject codes to the subjects
```
{ subject_name: 'Modern languages (other)', subject_code: nil }
This will be another PR.
```

[2122] Amended subjects with subject code

---

app/jobs/bulk_sync_courses_to_find_job.rb
spec/jobs/bulk_sync_courses_to_find_job_spec.rb

We get an error from sacui fairly regularly with this process, and as the bulk sync is a pretty heavy job we don't want a bunch of these retrying in the background. And the job just reruns every 2 hours anyway. Until we sort how not to get errors every time it kicks off we should drop failed job runs.
Disable Sidekiq retries for the bulk sync job.
:shipit: . o ( This is blocking implementing bulk sync in prod. )

[2207] don't retry when we get 502 from sac api for bulk sync

---

app/controllers/api/v1/subjects_controller.rb
app/models/course.rb
app/models/dfe_subject.rb
app/models/ucas_subject.rb
app/serializers/api/v2/serializable_course.rb
app/serializers/course_serializer.rb
app/serializers/search_and_compare/course_serializer.rb
app/serializers/subject_serializer.rb
app/services/ucas_subject_mapper_service.rb
db/seeds.rb
spec/factories/subjects.rb
spec/factories/ucas_subjects.rb
spec/lib/mcb/commands/apiv1/courses/find_spec.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/models/recruitment_cycle_spec.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v1/subject_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/providers/publish_spec.rb
spec/requests/api/v2/providers/sync_courses_with_search_and_compare_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/subject_serializer_spec.rb
spec/services/ucas_subject_mapper_service_spec.rb

State of flux 
In relation to #800 with regards to subjects matters only.
The previous PR takes the existing knowledge by re-modeling it to remove the need to calculate a given course's `level` and the perceived old `dfe subjects` via the `ucas subjects` assigned to it.
The previously workflow evolves around correctly assigning the required `ucas subjects` in order to create a given course with the desired `level` and desired  old`dfe subjects` via the subject mapper.
The new modeling should now be in the position to address the imbalance.
The course may now be able to set its level in order to set the subjects of that level and apply the appropriative business rules.
This PR only deals with returning subjects outwardly in the correct manner, to facilitate the bear minimum, for the next …

2132 refactor v1 v2 endpoints to use new dfe subjects instead

---

app/models/course.rb
app/models/subject.rb
app/models/subjects/secondary_subject.rb
app/services/course_assignable_subject_service.rb
lib/mcb/cli/course_cli.rb
lib/mcb/editor/courses_editor.rb
spec/factories/subjects.rb
spec/lib/mcb/editor/courses_editor_spec.rb
spec/models/course_spec.rb
spec/models/secondary_subject_spec.rb
spec/models/subject_spec.rb
spec/services/course_assignable_subject_service_spec.rb

MCB should be able to use the new subjects rather than the UCAS subjects.  
Use the DfE subjects instead of the UCAS subjects.  
I've added `CoursePotentialSubjectService` because this is logic that will likely be used elsewhere but that I don't think belongs in the model since it doesn't pertain directly to courses themselves but rather is an implication of its properties. I am open to feedback, I've tried to maintain a reasonable degree of coupling between it and Rails.

[2186] Update mcb to use new subjects

---

app/serializers/api/v2/serializable_course.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

All courses created via mcb after are defaulting to `Secondary` even when created as Primary
Serialize `level` in courses

[2249] Serialize level not ucas level for v2 courses

---

app/models/provider_enrichment.rb
spec/models/provider_enrichment_spec.rb
spec/requests/api/v2/providers/publish_spec.rb
spec/requests/api/v2/providers/publishable_spec.rb

Provider contact details enrichments
Remove all validation on enrichment contact details for "publishing"
🚢

[2251] Remove provider contact enrichment validation for publish

---

app/models/course.rb
config/locales/en.yml
spec/models/course/publishable_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb

There've been some issues with subjects and levels being missing from courses since moving away from UCAS subjects, this should help us better diagnose these issues.
Give a validation message when either subject or level are not present.
[This test](https://github.com/DFE-Digital/manage-courses-backend/pull/853/files#diff-2370f7c60a21a83d5258e3f9f253bbb7L119) was deleted because this validation prevents it ever reaching a state where a course cannot be bulk published because it has no subjects.  
I've also refactored the request validation tests a bit while correcting them so that they aren't as fragile.

[2250] Add validation for subject and level presence

---

app/services/subject_creator_service.rb
db/migrate/20190912162820_create_subject_table.rb
db/seeds.rb
spec/requests/api/v1/subject_spec.rb
spec/services/subject_creator_service_spec.rb

As it stands seeded courses are not created with data that reflects the new subject changes.  
Removal of old style courses from seeds and instead create new style courses. Also creates subjects in the seeds as well as refactoring the migration that creates them to avoid duplication of code.

[2205] Update db seeds for subjects

---

app/models/course.rb
spec/models/course/publishable_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb

Errors were coming through as a result of site statuses not being findable on published courses
Prevent courses being published without findable site statuses by adding validation.

[1957] Add site status publishing validation

---

app/models/course.rb
app/models/financial_incentive.rb
app/models/subject.rb
db/migrate/20190930110525_create_financial_incentive.rb
db/schema.rb
spec/factories/financial_incentives.rb
spec/models/course_spec.rb
spec/models/financial_incentive_spec.rb
spec/models/subject_spec.rb

We currently have a bunch of logic to do with financial incentives hardcoded in DFESubject, DFESubject will be going away and hardcoding makes things harder for rollover.
Move this logic to the new FinancialIncentive model and remove course's dependency on DFESubject.

[2245] Add financial incentive model

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/update_sites_spec.rb

When editing these locations for a provider:
https://www.publish-teacher-training-courses.service.gov.uk/organisations/1ZC/2020/courses/38BW/details
After removing a location (Inspiration Trust) on an draft course, it attempted to sync which then errored: https://sentry.io/organizations/dfe-bat/issues/1250607692/
The change was made successfully but the user sees a 500 page.
If a course hasn't been published yet, it's not on Find, and we don't need to sync it.
This wasn't true last cycle, in 2019 a course was on Find if it had been set to running on UCAS – a course's published content was published separately.
From 2020 the only way a course gets set to running is by publishing it. So we can now include this check.
This will prevent errors when trying to sync something in a non-syncable …

[2258] Only sync published course on course update

---

app/models/course.rb
spec/models/course/publishable_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb

This reverts commit c782409930c322c8a52f643bc7ceb7e1fddee59a.
Calling this validation on Publish:
```ruby
def validate_site_status_findable
unless findable?
errors.add(:site_statuses, "must be findable")
end
end
```
Ultimately means checking a course's site statuses for:
```scope :findable, -> { status_running.published_on_ucas }```
The job of publish however is to take new sites and put them into the running and published on UCAS state.
#857 PR made it so that only already published courses could be published. New or draft courses could not be published by users.
The tests illustrate this, by making a "new" site not publishable:
https://github.com/DFE-Digital/manage-courses-backend/pull/857/files#diff-2370f7c60a21a83d5258e3f9f253bbb7L62-R62
The 500s this was trying to fix should be …

Revert "[1957] Add site status publishing validation"

---

app/models/course.rb
spec/models/course_spec.rb

Expand the scope of "is_published" to all published courses.
Before this change courses that were published_with_unpublished_changes:
- wouldn't be sync'd to Find when editing details
- would allow editing of properties that shouldn't be edited after publish
Added a test, which was initially failing.

`is_published` should be true when `:published_with_unpublished_changes`

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/policies/course_policy.rb
config/routes.rb
spec/models/course/withdraw_spec.rb
spec/policies/course_policy_spec.rb
spec/requests/api/v2/providers/courses_spec.rb

Users need to be able to withdraw a published course. Once published a course should not be able to be deleted/discarded
- Add an endpoint for withdrawing a course
- A second PR to add a command to mcb to do this will follow.

[1809] Add withdraw course functionality

---

app/services/authentication_service.rb
spec/services/authentication_service_spec.rb

Rails has never saved the users SignIn ID
Save the users SignIn user ID

[2135] Update users sign in id when logging in

---

app/services/authentication_service.rb
spec/services/authentication_service_spec.rb

We don't set the users first/last name from DfE SignIn
Set the first/last name based on the token sent from the frontend

[2276] Set first and last name from DfE signin

---

app/models/recruitment_cycle.rb

We originally believed we wouldn't be syncing courses for providers who hadn't added enrichments. We now are.
Don't filter out providers that aren't "publishable" when generating list for bulk sync.
This is customer-affecting bug, about 270 courses are currently affected by this issue.

[2274] sync courses from un-enriched providers

---

app/controllers/api/v3/application_controller.rb
app/controllers/api/v3/courses_controller.rb
config/routes.rb
config/settings.yml
config/settings/production.yml
spec/requests/api/v3/providers/courses/show_spec.rb

Apply (and search-ui soon) will need to query for public course information. One proposal is to have public endpoints living under the `v3` namespace.
Add v3 courses controller and route.
Allows us to run:
```bash
# Look ma, no auth!
curl "http://localhost:3001/api/v3/recruitment_cycles/2020/providers/2CG/courses/2Z3H" | ppjson
{
"data": {
"attributes": {
"about_accrediting_body": null,
"about_course": null,
"accrediting_provider": {
"accrediting_provider": "accredited_body",
...
```
And again, with sparse fields (`?fields[courses]=provider_code,course_code,name`):
```bash
curl -v "http://localhost:3001/api/v3/recruitment_cycles/2019/providers/2KN/courses/39VZ?fields\[courses\]=provider_code,course_code,name" | ppjson
{
"data": {
"attributes": {
"course_code": "39VZ",
"name": …
```

Implement public V3 courses API

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/course_enrichment.rb
spec/factories/course_enrichments.rb
spec/models/course/withdraw_spec.rb
spec/models/course_enrichment_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb

The withdraw course check had it's if condition backwards, this needed to be flipped.
Additionally, we needed to update the `content_status` to `withdrawn` so the frontend could respond appropriately
- Flip the check
- Edit the content status

[1809] Withdraw course updates

---

app/serializers/search_and_compare/course_serializer.rb
spec/serializers/search_and_compare/course_serializer_spec.rb

Provider enrichments was getting non deterministic draft vs published content becoming bulk pub
Changed to use updated_at
:ship: 
paired with @misaka

[2290] Fixed provider enrichments to use updated_at

---

app/models/subject.rb
spec/models/subject_spec.rb

Avoid confusion when choosing subjects during course editing and creation in MCB.
Consider:
`9. [ ] Computing (11)`
If a user types 11, the course has the wrong subject assigned.
```
1. continue
2. [ ] Art and design (W1)
3. [ ] Biology (C1)
4. [ ] Business studies (08)
5. [ ] Chemistry (F1)
6. [ ] Citizenship (09)
7. [ ] Classics (Q8)
8. [ ] Communication and media studies (P3)
9. [ ] Computing (11)
10. [ ] Dance (12)
11. [ ] Design and technology (DT)
12. [ ] Drama (13)
13. [ ] Economics (L1)
14. [ ] English (Q3)
15. [ ] English as a second or other language (16)
16. [ ] French (15)
17. [ ] Geography (F8)
18. [ ] German (17)
19. [ ] Health and social care (L5)
20. [ ] History (V1)
21. [ ] Italian (18)
22. [ ] Japanese (19)
23. [ ] Mandarin (20)
24. [x] Mathematics (G1)
25. [ ] Modern …
```

Remove subject code from subject `to_s`

---

app/controllers/api/v1/application_controller.rb
config/routes.rb
spec/requests/api/v1/course_spec.rb

We want to ensure that UCAS can't access stale date, so it makes sense to make the old data 404.
Adds a `constraints` option to the route that I've stolen from Frontend, plus checks the query string param.
UCAS can request by either specifying the param in the URL or as a query string parameter.
Have tested this locally and it seems to work fine, plus we have good test coverage.

[2295] Disable v1 API for 2019 courses

---

db/migrate/20191007103707_fix_secondary_science_course_requirements.rb
db/schema.rb

Similar to https://github.com/DFE-Digital/manage-courses-backend/pull/640
There are no minimum GCSE requirements for science in secondary courses. Most are set to nil, set everything else to nil too (ie not set).
We've already removed the ability to edit these codes in frontend.
Set any non nil secondary course science requirement to nil (eg :not_set – but nil enums behave weirdly, so using nil explicitly)

[2299] Set secondary science requirements to not_set

---

lib/mcb/commands/providers/withdraw_courses.rb
spec/lib/mcb/commands/providers/withdraw_courses.rb
spec/lib/mcb/commands/providers/withdraw_courses_spec.rb

We need to be able to withdraw a provider's courses from find if they are no longer eligible to run teacher training.
- Add an mcb command to remove a (or multiple) providers courses.

[2229] Withdraw courses mcb command

---

app/models/course.rb
spec/models/course/funding_type_spec.rb

When creating courses - the `funding_type` attribute gets set. This can cause 500s due to an override on `funding_type=` calling update, triggering validations which attempt to validate nil data
Set the value rather than calling update when setting funding type

[2305] Dont call update when updating funding type

---

app/models/provider.rb
app/models/recruitment_cycle.rb
db/migrate/20191007163334_add_discarded_at_to_provider.rb
db/schema.rb
lib/mcb/commands/providers/discard.rb
spec/factories/providers.rb
spec/lib/mcb/commands/providers/discard_spec.rb
spec/models/provider_spec.rb
spec/models/recruitment_cycle_spec.rb

Providers need to be able to be soft deleted.
- Add discard to the provider model
- Add mcb command to discard providers

[2240] Add discard to provider and add mcb command

---

app/controllers/api/v2/site_statuses_controller.rb
app/models/course.rb
app/models/site_status.rb
app/serializers/api/v2/serializable_site_status.rb
app/serializers/site_status_serializer.rb
app/services/sites/copy_to_course_service.rb
db/migrate/20190806102256_add_applications_open_from_to_courses.rb
db/migrate/20191008113447_remove_applications_accepted_from_from_course_site.rb
db/schema.rb
db/seeds.rb
lib/mcb/render.rb
spec/factories/courses.rb
spec/factories/site_statuses.rb
spec/lib/mcb/commands/apiv1/courses/find_spec.rb
spec/lib/mcb/commands/courses/show_spec.rb
spec/lib/mcb/editor/courses_editor_spec.rb
spec/models/course_spec.rb
spec/models/site_status_spec.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v2/site_statuses_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/services/sites/copy_to_course_service_spec.rb

Leftovers from when `course` table introduced `applications_open_from`
Remove `applications_accepted_from` from `course_site` as is superseded by `applications_open_from` from `course` table
Realign/unify logic used to calculate `open_for_applications?` on the `course` model
:rabbit: :hole: :ship:

1906 remove applications accepted from field from course site

---

app/controllers/api/v2/providers_controller.rb
spec/factories/providers.rb
spec/requests/api/v2/providers/update_spec.rb
spec/requests/api/v2/providers/update_with_sync_spec.rb

Sync courses when saving a provider
A provider's courses can only be sync
1. the provider is valid
2. it is the current recruitment cycle
3. there is syncable courses
spec/requests/api/v2/providers/update_spec.rb
- deals with 1
spec/requests/api/v2/providers/update_with_sync_spec.rb
- deals with 2 and 3

2289 sync courses when saving provider

---

db/migrate/20191007125535_mark_withdrawn_courses_as_withdrawn.rb

Before the "withdrawn" content status existed, we withdraw courses manually. This updates those withdrawn in that way to fix the content status

[2303] Add migration to mark manually withdrawn courses as withdrawn

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
lib/mcb/editor/courses_editor.rb
spec/lib/mcb/editor/courses_editor_spec.rb

Site statuses have a vacancy status that's dependent on the course's study mode. eg A full time course has full time vacancies.
When updating the course through the UI we were ensuring this was updated. But no such checks were made in MCB.
- Move the method into the course
- Reuse the ensure method in MCB to keep changes consistent and correct
This is how site statuses got out of sync on https://trello.com/c/h4yNl5DH/

[2330] Update a site_status’s vacancy status when editing a course study mode in MCB

---

lib/mcb.rb

`qa` and `staging` have moved to CIP. These are the connection details we need to connect with them.
Use the CIP resources for `qa` and `staging`.
😞

[2323] configure mcb to use cip qa and staging envs

---

app/models/course.rb
app/models/subjects/secondary_subject.rb
app/serializers/course_serializer.rb
app/serializers/search_and_compare/course_serializer.rb
spec/factories/subjects.rb
spec/lib/mcb/editor/courses_editor_spec.rb
spec/models/course_spec.rb
spec/models/secondary_subject_spec.rb
spec/requests/api/v1/subject_spec.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb
spec/services/course_assignable_subject_service_spec.rb
spec/services/courses/generate_course_title_service_spec.rb
spec/support/reference_data.rb

With the recent work on subjects they weren't being preloaded causing the bulk sync job to become an N+1 query. 
Add a method to use the already-loaded course subjects, if present, instead of always refering to the DB.
Also add memoisation of the "Modern Languages" subject to prevent DB hits.
Add creation of subjects in the specs outside of the spec transaction so that the memoised "Modern Languages" object is always the right one. This approach was taken since the subjects are singleton objects and this may present a useful optimisation approach in general to such data.
Sorry this turned into something a bit bigger than just the `syncable_subjects`, but it's all part of the boyscout approach.

[2313] optimise sync course

---

app/models/concerns/courses/edit_options.rb
app/models/concerns/courses/edit_options/subjects_concern.rb
app/services/course_assignable_master_subject_service.rb
spec/models/concerns/courses/edit_options_spec.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/services/course_assignable_master_subjects_service_spec.rb

As it stands the frontend has no subjects to choose from for subject editing.  
Send potential master subjects via edit options.

[2352] Add potential subjects to edit options

---

config/environments/development.rb

To remove redis from the development dependencies.
You can flip it back if you need to test sidekiq.
Turn it off, but not on again.
sidekiq -> async
:ship:

[2373] Turn off sidekiq in development mode

---

db/migrate/20191016095315_remove_ucas_subject_and_course_ucas_subject.rb
db/schema.rb

The tables for ucas_subject and course_ucas_subject are now redundant and need to be removed.
- Migration to drop the tables

[2237] migration to remove ucas subjects

---

app/models/course.rb
spec/models/course_spec.rb

During course creation, the `build_new` endpoint does not return sites when assigned, this is because the `sites=` method is overridden to change sites based on persisted values.
This is a workaround for that behaviour
- Add tests to existing behaviour
- Add tests for new course
- Change the logic on `sites=` where appropriate

[2362] Ensure sites get assigned to non-persisted courses

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/create_spec.rb
spec/serializers/api/v2/serializable_course_spec.rb

We would like to be able to edit subjects during course creation, but as it stands the backend does not do the work of assigning subjects.
Run `update_subjects` during course creation so that subjects can be set.

[2365] Allow subjects to be set in course creation

---

app/serializers/course_serializer.rb
spec/requests/api/v1/course_spec.rb
spec/serializers/course_serializer_spec.rb

The CourseSerializer incorrectly determines the `age_range` value in some cases (defaulting to "O").
_Please note_
The success criteria on this ticket has changed since the original PR was raised. The age_range calculation is a lot simpler than was previously proposed. See Trello ticket - https://trello.com/c/5FZxbtXi/2388-fix-ucas-agerange
- Implement correct logic.

[2388] - Fix UCAS Age Range

---

app/models/contact.rb
config/locales/en.yml
db/migrate/20191023195941_assign_provider_name_to_contacts.rb
db/schema.rb
spec/models/contact_spec.rb

UCAS Contacts
- Ensure all UCAS contacts have a name, telephone number and email
🚢

2396 assign contacts with name

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
spec/models/course_spec.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/requests/api/v2/providers/courses/create_spec.rb

We need to assign sites to courses in the create/build_new endpoints in order for the frontend to display them, and courses to be created with them
- Assign sites in the course controller
- `distinct` the sites relationship in the course model
- Due to the way we solved the issue with sites= courses will be created with duplicated site statuses
To work around that issue for now a distinct was added to the sites has_many to ensure the frontend only receives the sites added, not duplicates
https://trello.com/c/bFxJArKI/2364-assign-sites-to-course-during-creation

[2364] Assign sites to courses for course creation

---

app/controllers/api/v2/providers_controller.rb

Noticed while doing testing that there was an N+1 query triggered when we list providers in API v2. This wouldn't have a massive affect on users since they usually only have a few providers linked to their accounts, but whenever an admin user hits the system this would cause a costly query to run.
include `recruitment_cycle` when listing providers for `/api/v2/providers`
No Trello card as it's a one-liner. I did a quick check and I don't think we even test for `includes` on queries.

include recruitment cycle in query for provider index

---

spec/models/financial_incentive_spec.rb

`pending`!
* Add missing spec for FinancialIncentive
:ship:

[2417] Add missing spec for FinancialIncentive

---

app/controllers/api/v2/providers_controller.rb
spec/requests/api/v2/providers/update_provider_ucas_preferences.rb

https://sentry.io/organizations/dfe-bat/issues/1295662651/
```
NoMethodError: undefined method `assign_attributes' for nil:NilClass
app/controllers/api/v2/providers_controller.rb:158:in `update_ucas_preferences'
@provider.ucas_preferences.assign_attributes(ucas_preferences_params)
app/controllers/api/v2/providers_controller.rb:36:in `update'
update_ucas_preferences
(58 additional frame(s) were not displayed)
```
~ 230 provider records out of 1900 are in this state
* Failing test (commit 1)
* Fix ucas_preferences where there is no existing record (commit 2)
Before: 500 error saving contacts on new provider
After: 200 success
:eyes: :ship:
Is this idiomatic rails? https://github.com/DFE-Digital/manage-courses-backend/pull/940/files#diff-39dc04fe15459326f96c330daef49bb7R158
``` …
```

[2412] Fix ucas_preferences where there is no existing record

---

app/controllers/api/v2/courses_controller.rb
spec/factories/courses.rb
spec/requests/api/v1/course_spec.rb
spec/requests/api/v2/providers/courses/update_subject_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb
spec/serializers/search_and_compare/test_data.json

The title courses title(name attribute) is not currently being updated when it's subjects are being updated.
- update the course's name when it's subjects are updated
- refactor the course factory to use the correct name if is has subjects

[2437] Update courses title when subjects are updated

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/create_spec.rb

The course doesn't have the provider set when creating the course with all params at the same time. This calls the `funding_type=` method to be called before the provider is set
Assign the provider to the course first before assigning other attributes

[2470] Assign provider to course before other params in creation

---

spec/models/course_spec.rb

In the course spec file. The tests related to sites and site_statuses often instantiate multiple providers unnecessarily. As if a site_status is not assigned site it creates one. This in turns creates a provider. 
- Assign site_statsues to a site and provider
- General refactor to DRY the code out

[1788] Refactor site_statuses in course_spec to use the same provider

---

app/models/course.rb
spec/requests/api/v2/providers/courses/publish_spec.rb

Avoid publishing bad site statuses/courses in the event that the relationship between a course and it's site statuses has been corrupted somehow.
This happened before and the cause was fixed in #905
This will flag bad data and let us fix the data/causes before Publish/Find get into a broken state.
An error message would swallow the error show the user a message they couldn't recover from.

Raise an error if trying to publish with invalid site statuses

---

app/models/user.rb
spec/factories/users.rb
spec/lib/mcb/commands/courses/audit_spec.rb
spec/lib/mcb/commands/users/audit_spec.rb
spec/models/user_spec.rb

* Fear, uncertainty & doubt.
* This is a follow-up to #954 
* Restrict email for admin users to education domains
* The mighty power of test-driven development
:eyes: :ship:

[2480] Restrict email for admin users to education domains

---

app/models/course.rb
app/models/organisation.rb
db/migrate/20191101095530_remove_course_enrichment_legacy.rb
spec/lib/mcb/commands/courses/list_spec.rb
spec/models/course_spec.rb
spec/models/organisation_spec.rb
spec/models/user_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/update_send_spec.rb
spec/support/parse_text_table.rb

There are a number of pieces of code that are no longer necessary increasing cognitive load.
Remove any obsoleted functionality and anything dependent on it.
This eliminates the dependent destroy on organisations [seems to have now been fixed](https://github.com/rails/rails/issues/7618) (and additionally adds a test to ensure it functions correctly), the use of obsoleted columns in course_enrichments and the obsoleted is_send= setter.

[2454] Remove obsoleted functionality (part 1)

---

azure/template.json

As it stands we connect to Redis in an insecure manner, this may be a minor security risk.
Make Sidekiq connect to Redis on port 6379 over `rediss`

[2449] Secure Redis connection

---

app/controllers/api/v2/application_controller.rb
app/services/authentication_service.rb
spec/services/authentication_service_spec.rb

When we added logging, we opted to avoid testing it as we wanted to fix an urgent issue. This refactors the service to allow for the testing of logging and also tests the logging
- Refactor authentication service to invert dependencies
- Test the logging
- Fix a bug caught by the tests

[2235] Test personal information isnt being leaked in logging

---

app/models/course.rb
app/models/recruitment_cycle.rb
app/services/courses/content_status_service.rb
spec/models/course_spec.rb
spec/models/recruitment_cycle_spec.rb
spec/services/courses/content_status_service_spec.rb

The course model is currently over 600 lines and has become a bit of a god class
- refactor content status into a service object

[2476] Refactor content status to service 

---

app/controllers/api/v2/sessions_controller.rb
app/services/authentication_service.rb
app/services/record_first_login_service.rb
app/services/send_welcome_email_service.rb
app/validators/words_count_validator.rb
spec/services/authentication_service_spec.rb
spec/services/record_first_login_service_spec.rb
spec/services/send_welcome_email_service_spec.rb

In order to be able to deliver value it must be easy to understand and work with the code.
https://github.com/DFE-Digital/manage-courses-backend/pull/942
This refactors any unclear or non-idiomatic lines.
Remove unused functionality from authentication service and clarify the use of MD5 as obfuscation. Moves some of SendWelcomeEmailService's functionality to RecordFirstLoginService to avoid having a service do too many things. Also includes some additional restructuring.

[2473] Cleanup (part 2)

---

app/controllers/api/v2/users_controller.rb
app/serializers/api/v2/serializable_user.rb
spec/requests/api/v2/access_request_spec.rb
spec/serializers/api/v2/serializable_user_spec.rb

As we are porting access requests to the frontend we need a mechanism to only give access to the support section of publish to admin users.
- Expose the admin attribute on the user serialiser

[2484] Expose admin attribute to the frontend

---

.bundle/config
.gitignore
Gemfile
Gemfile.lock
README.md
Rakefile
config/database.yml
spec/rails_helper.rb
spec/spec_helper.rb

The work required to make these specs run in parallel is very similar to https://github.com/DFE-Digital/manage-courses-frontend/pull/742 however we now have a database to contend with.
_Rationale for changes?_
- Slow running specs eat up valuable dev-time.
- It's a pain to have to manually open up SimpleCov results right?
Adds:
-  the `parallel_tests` gem to speed up tests
- the `simplecov-console` gem to print SimpleCov test output to the console
The default rake task has been amended so that parallel specs run by default (using 12 cores) 
- to change the number of cores used when running the default Rake task `bundle exec rake` set a `'PARALLEL_CORES'` env var to what ever your machine can handle.
- to just run the tests in parallel run `bundle exec rake parallel:spec`
- _NOTE_ - a …

[2488] - Run specs locally in parallel

---

Rakefile
azure-pipelines.yml

Part of a bigger section of work to run specs in parallel.
A simple change to the azure configuration so that specs are run in parallel on CI via the `parallel_tests` gem. Azure has _two_ available cores that can be utilised.
_Before_
~ 4 min 40 sec 
_After_
2 min 55 sec 🎉

[2500] - Run specs in parallel on CI

---

config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml

MCAPI is being decommissioned and config/settings files still reference it.
- Remove references to MCAPI

[2496] Remove manage_api from the config settings

---

Gemfile
Gemfile.lock
app/controllers/api/v2/application_controller.rb
app/services/authentication_service.rb
config/environments/development.rb
config/initializers/logstash.rb
config/initializers/semantic_logger.rb
spec/services/authentication_service_spec.rb

Default Rails logging to logstash is messy and painful to use.
Introduce `semantic_logger` which makes request logging to Logstash sane, and also pretties up file logging.
12 events are logged for a single API request for a Provider's page. 2 of the events are custom events for authentication (won't show in Prod), and the rest is basically an event per line logged for Rails. And also none of the attributes are broken out to individual fields for searchability:
4 events are logged for a single API request for the provider's endpoint. Same as above, 2 of the events are custom events for authentication (and won't show in Prod), one is for the actual request and another is an extra one that the JSONAPI has spat out to tell us how long it took to generate the JSON. That one should be …

[2509] add semantic logger

---

app/models/course.rb
app/services/courses/assign_program_type_service.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/services/courses/assign_program_type_service_spec.rb

The course model is currently over 600 lines and has become a bit of a god class
- refactor funding_type=(funding_type) into a service

[2476] Refactor funding_type= to service

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/providers/courses/publish_spec.rb

Publishing a course for the first time threw an error because we were checking whether the course prior to publishing changing the relations was syncable and we needed to reload
- Reload the course before checking if it is syncable
- Find a valid course that has never been published
- Publish it

[2518] Reload course before checking if it's syncable on publish

---

azure/template.json

Related to previous merge. Due to a bug in ARM template. ARM template for PSQL firewall rules in split into two templates. see details here `https://github.com/DFE-Digital/bat-platform-building-blocks/pull/30`

2356- Update psql fw template uri

---

bin/mcb

Spotted this during show & tell. 
We should definitely have a manage-curses-backend though #$@&%*!.

Fix typo in mcb help command

---

Gemfile
Gemfile.lock
Rakefile
app/models/user.rb
azure-pipelines.yml
config/brakeman.ignore
lib/tasks/brakeman.rake

Static analysis is way to identifies security flaws in an application. _Brakeman_ is a gem that provides this functionality.
- Add Brakeman gem
- Create rake task to run static analysis locally
- Add Brakeman rake task to default rake task
- Add static analysis as a build step on CI. Build will fail if static analysis does not pass.
```
bundle exec brakeman
```

[2522] - feat(security): add Brakeman static analysis

---

Gemfile
Gemfile.lock
Rakefile
spec/spec_helper.rb

The `simplecov-console` gem was added recently in order to print results to the console rather than publish results to the 'coverage' folder. However following discussion with team have concluded this is too noisy so am reverting back to the previous method.
- remove `simplecov-console` gem and associated config.
- threshold added for passing Simplecov (75%). Currently the coverage is just over 75% and this is largely influenced by low code coverage in the mcb library.
- reduced noise in console when running specs in parallel

[2534] - Don't use simplecov-console gem

---

lib/mcb/commands/courses/sync_to_find.rb
lib/mcb/editor/courses_editor.rb
spec/lib/mcb/commands/courses/sync_to_find_spec.rb
spec/lib/mcb/editor/courses_editor_spec.rb

be bin/mcb courses edit (sync to find) & be bin/mcb courses sync_to_find currently do not work as they still point to a MCAPI service. 
- Refactor the above mcb commands to use the S&C API service

[2517] Fix sync course to find mcb commands

---

app/controllers/api/v2/application_controller.rb
spec/controllers/api/v2/application_controller_spec.rb

When a request comes in, add the value of the X-Request-ID to the logs, and ensure this value gets sent to the MCBE. This so we can track a requests journey through the system.
See frontend PR - https://github.com/DFE-Digital/manage-courses-frontend/pull/765
- Send request ID to Kibana and Sentry

[2510] - Add Request ID support to MCBE

---

Rakefile

- removing 'clearing' the default Rake task.
- Fixes application tripping over when running migration in Production

FIX - Default Rake Task

---

app/controllers/api/v2/access_requests_controller.rb
app/controllers/api/v2/users_controller.rb
app/serializers/api/v2/serializable_organisation.rb
app/serializers/api/v2/serializable_user.rb
spec/requests/api/v2/access_request_spec.rb
spec/serializers/api/v2/serializable_organisation_spec.rb

As it stands the access requests default to always include only the requester, this is inconsistent with dominant convention and prevents us extracting organisation data.
Have the AccessRequest `show` endpoint respond to the `?include` parameter.
This is necessary as part of https://github.com/DFE-Digital/manage-courses-frontend/pull/766

[2484] Make AccessRequest respond to include url parameters

---

Gemfile

Move RequestStore gem out of the test/development group so that it is accessible in production

Move RequestStore Gem

---

spec/lib/mcb/commands/courses/list_spec.rb

I want this off my mental stack, hence separate PR for trivial thing.
See trivial diff
:ship:

Fix typo in existing spec name

---

Rakefile

When running the default rake task specs are no longer running in parallel. This was a result of [this change](https://github.com/DFE-Digital/manage-courses-backend/pull/1001).
Revert back to clearing the default rake task (so that specs are not run in series) and create a default rake task so that rake tasks (such as db migrations) do not trip over when run in the production environment.
- Please run 'be rake` locally and check specs run in parallel
- The run `RAILS_ENV=production bundle exec rails db:migrate` and make sure you do **not** get the error _Don't know how to build task 'default'_.

Fix default rake task

---

.gitignore
README.md
config/settings/development.yml
lib/mcb.rb
spec/lib/mcb/commands/db_spec.rb

Sync to find was not working correctly due to the above method in mcb.rb`
- refactors the above to use opts[:env] to ensure the correct settings are being used for the selected environment.
- adds an azure section to the settings/qa.local.yml, settings/staging.local.yml, settings/production.local.yml files
- updates the README on how to connect to MCB (add .local files for qa, staging and prod.
The updated confluence is here.
https://dfedigital.atlassian.net/wiki/spaces/BaT/pages/1182761062/MCB+Configuration

[2517] Refactor mcb.rb to use opts[:env] when loading the settings file

---

db/migrate/20191121134050_add_latitude_and_longitude_to_provider.rb
db/migrate/20191121134242_add_latitude_and_longitude_to_site.rb
db/schema.rb

Part of the epic to add to geolocation info to courses.
- Add latitude and longitude columns to the Provider and Site tables
- Add indexes for latitude and longitude

Add latitude and longitude columns to the Provider and Site tables

---

lib/mcb.rb
spec/bin/mcb_spec.rb

If a user specifies an environment that is not listed in the config file they will receive a cryptic `KeyError`, this is an error that is likely to appear often and as such should be clear in order to avoid wasting time during setup.
Adds a message that clarifies the error to the user.
This PR has been written in such a way that it anticipates @davidgisbey's fix for the wrong environment being used, it will direct the user to modify the correct config depending on `RAILS_ENV`.

[2542] Add descriptive error for missing MCB environment

---

app/models/provider.rb
spec/lib/mcb/commands/providers/discard_spec.rb
spec/models/provider_spec.rb

When a provider is discarded it should also discard their courses.
- Add before block that discards a providers courses before provider.discard
- Add this functionality to MCB provider discard command

[2602] Discarding a provider should discard its courses

---

azure-pipelines.yml

Fix variable error `The CC_TEST_REPORTER_ID variable is not set. Defaulting to a blank string.`

2613-fix CodeClimate variable error

---

app/models/concerns/courses/edit_options/subjects_concern.rb
spec/models/concerns/courses/edit_options_spec.rb

Secondary subjects are currently not in alphabetical order.
- Sort secondary subjects before serialising them into the edit options serialiser

[2579] Sort potential subjects by name

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/build_new_course_spec.rb

In order to be able to determine information about courses in relation to their providers for https://github.com/DFE-Digital/manage-courses-frontend/pull/773.
Include the provider in the response for `build_new`.

[2412] Include provider in build_new

---

app/models/course.rb
spec/models/course/funding_type_spec.rb

`Course#build_new` on the API was returning a default `funding_type` of `"fee"` when called without a funding type given - it should instead return a `funding_type` of `nil`
- Default funding type to nil when no program type is set

[2585] Default to nil funding type

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/build_new_course_spec.rb

So that the frontend remembers the current accredited body selection
* Include accredited body in new course
* run it
* build a new course - https://localhost:3000/organisations/2HO/2020/courses/new
* go one step past choosing an accredited body
* click the back link (not the browser back)
* check the accredited body you chose is still selected
* ship it

[2571] Include accredited body in new course

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/build_new_course_spec.rb

The frontend needs the provider to be passed back from the API in build new, this used to exist but seems to have gone AWOL
- Re-include provider

[2639] Re-include provider on build new endpoint

---

config/initializers/geocoder.rb

Geocoder has the ability to cache requests. This PR configures it to use the existing Redis instance

[2565] - Configure Geocoder gem to use existing Redis instance

---

app/models/organisation.rb
app/serializers/api/v2/serializable_organisation.rb
spec/factories/nctl_organisation.rb
spec/serializers/api/v2/serializable_organisation_spec.rb

NCTL ids are exposed on the org index support page, but it is not currently exposed on the V2 API.
- Expose nctl_ids as an attribute on organisation

[2576] Expose nctl_ids on the V2 API via organisation

---

app/serializers/api/v2/serializable_organisation.rb
app/serializers/api/v2/serializable_user.rb
spec/requests/api/v2/access_request_spec.rb
spec/serializers/api/v2/serializable_organisation_spec.rb
spec/serializers/api/v2/serializable_user_spec.rb

The org support page needs this to deeplink to users
- Expose user sign in id on the v2 api

[2576]  2576 expose user sign in to frontend

---

app/controllers/api/v2/courses_controller.rb
spec/bin/mcb_spec.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/spec_helper.rb

In order for https://github.com/DFE-Digital/manage-courses-frontend/pull/798 to function correctly the course needs to have site information.  
Provide the provider sites when requesting a course object from `build_new()`.
We'll want to have an include parameter at some point, but I think this works for now.  
This also includes a fix for a test which was breaking if `config/azure_environments.yml` was present on your real filesystem.

[2631] Add sites to course creation

---

app/models/concerns/geolocation.rb
spec/models/concerns/geolocation_spec.rb

When a Site or Provider address was updated the lat and long was not being updated.
This was because:
- Geolocation was not running under these conditions (we should be looking at what changes _were_ saved to the db)
- Bad test setup that gave a false positive 😿

[2667] - BUGFIX: Update lat and long when Site and Provider address is updated

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/subjects/further_education_subject.rb
spec/models/course_spec.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/requests/api/v2/providers/courses/create_spec.rb

FE courses could not currently be created as they would fail validation based on fields they don't require. To solve this - we need to change validation
- No longer require maths, english, or age range on a FE course
- Set the funding type to "Fee" in build new course/create
- Set the FE Subject on the course in build new course/create

[2655] Allow Further Education courses to be created in new course flow

---

app/controllers/api/v2/organisations_controller.rb
spec/requests/api/v2/organisations_spec.rb

When gathering the list of organisations for the organisation support page a large number of queries are being made leading to the page being unable to load before the connection times out.
Restrict the amount of data serialized, as during serialization additional queries are made, and additional data has to be sent over the wire.
This should be tested with prod data to see if it loads reasonably quickly.

[2697] Remove all unneccessary data when requesting organisations

---

app/models/provider.rb
app/serializers/api/v2/serializable_provider.rb
app/serializers/provider_serializer.rb
db/migrate/20191216113352_remove_provider_last_published_at.rb
db/schema.rb
spec/factories/providers.rb
spec/models/provider_spec.rb
spec/requests/api/v1/provider_spec.rb
spec/requests/api/v2/providers/update_spec.rb
spec/requests/api/v2/providers_spec.rb
spec/serializers/provider_serializer_spec.rb
spec/serializers/search_and_compare/course_serializer_spec.rb

Provider enrichments are no longer in use, these fields are leftover from them.
Remove any references to providers' `content_status` or `last_published_date` and correct any tests broken by this.
Needs to be checked by @fofr but things seem to still work.

[2403] Remove content_status and last_published_date from provider

---

app/jobs/geocode_job.rb
spec/jobs/geocode_job_spec.rb

Restrict geocode searches to Great Britain (gb)

[2702] - Restrict geocode searches to Great Britain (gb)

---

config/initializers/geocoder.rb

Redis caching for geocoding was turned off recently when we were debugging Postgres connection issues on QA. Just need to enable again

[2709] - Re-enable Redis caching for storing geocoder api responses

---

db/migrate/20191220161244_remove_admin_users_from_organisations.rb
db/schema.rb

We have an admin flag on users
Remove all associated organisations from users flagged as admin 
- Ensure all users with the admin flag do not have any organisations
- Ensure all other users still have their associated organisations

[2714] Remove admin users from organisations

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
config/locales/en.yml
lib/mcb/editor/courses_editor.rb
spec/factories/courses.rb
spec/lib/mcb/commands/courses/edit_spec.rb
spec/lib/mcb/editor/courses_editor_spec.rb
spec/models/concerns/courses/edit_options_spec.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/requests/api/v2/providers/courses/create_spec.rb
spec/requests/api/v2/providers/courses/publish_spec.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb
spec/requests/api/v2/providers/courses/update_application_open_from_spec.rb
spec/requests/api/v2/providers/sync_courses_with_search_and_compare_spec.rb
spec/services/courses/assignable_subject_service_spec.rb

The `build_new` endpoint for course creation needs additional validations - this is to enable us to ensure we have correct data being created.
- Add a new validation scope for `:new`
- The reason for the additional scope was that currently a lot of tests fail when adding some of them to `on: :create` - this could be mitigated in the future but I wanted to minimise the changes in this PR
- Add new validations to courses 
- Check out `2640-create-a-course-validation-changes` on MCFE (or master if it is merged)
- Run through the course creation for an accredited body and attempt to submit without any data
- **Note** the Frontend for age ranges with a custom age range is not handled yet as this needs additional work to remove the validation from the frontend

[2640] Add validations for course creation

---

app/models/course_subject.rb
app/models/subject.rb
app/models/subjects/discontinued_subject.rb
app/models/subjects/further_education_subject.rb
app/models/subjects/modern_languages_subject.rb
app/models/subjects/primary_subject.rb
app/models/subjects/secondary_subject.rb
app/serializers/subject_serializer.rb
db/migrate/20191223134441_add_timestamps_to_subjects.rb
db/migrate/20191223135644_add_timestamps_to_course_subjects.rb
db/schema.rb
spec/models/course_subject_spec.rb
spec/models/secondary_subject_spec.rb
spec/models/subject_spec.rb
spec/serializers/subject_serializer_spec.rb

A number of tables with being flagged by rubocop as missing timestamps, this adds timestamps to those tables.
Add timestamps to the tables `course_subject` and `subject`
These timestamps are nullable in because no data for them currently exists, an alternate solution would be to set the date to the epoch.

[2678] Add timestamps to tables without them

---

.azure_parallel
azure-pipelines.yml

Inspired by @timabell 's trip down the rabbit hole - https://github.com/DFE-Digital/manage-courses-frontend/pull/823
When switching over parallel tests, it ended up breaking publishing of test results in Azure. This was because:
* The xml file wasn't copied out of the container so azure DevOps couldn't find it.
* Multiple processes wrote to the same xml file, sometimes making it invalid xml.
* Show test results sooner
* Fix display of test results in azure portal

[2664] - Fix display of test results in azure portal

---

app/controllers/api/v2/courses_controller.rb
spec/requests/api/v2/build_new_course_spec.rb

PE courses should not be able to be created by non-admin users via the UI.
- Remove PE from the list of potential subjects from the build new course endpoint.

[2677] Remove PE from potential subjects if user is not an admin

---

app/models/course.rb
app/services/courses/validate_custom_age_range_service.rb
spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb
spec/services/courses/validate_custom_age_range_service_spec.rb

We need a validation on the course that checks that custom age ranges are valid for the new and create actions.
It must do three things:
1. Check if the age ranges are 4 or more years apart
2. Check that the from value is valid (so in 3_to_7 that 3 is an integer)
3. Check that the to value is valid (so in 3_to_7 that 7 is an integer)
- Add a validation that is triggered on the new and create course endpoints that does the above.

[2704] Add validation for custom age ranges

---

lib/mcb.rb
lib/mcb/azure.rb
lib/mcb/commands/api.rb
lib/mcb/commands/api/bulk_sync_to_find.rb
lib/mcb/commands/apiv1/courses/find.rb
lib/mcb/commands/apiv1/courses/list.rb
lib/mcb/commands/apiv1/providers/find.rb
lib/mcb/commands/apiv1/providers/list.rb
spec/lib/mcb/azure_spec.rb
spec/lib/mcb/commands/api/bulk_sync_to_find_spec.rb
spec/lib/mcb_spec.rb
spec/support/with_stubbed_stdout.rb

The `mcb apiv2 bulk_sync_to_find` was using the wrong token, because it was added as an `apiv2` command when it's actually in the "system" api.
Move `bulk_sync_to_find` to the right namespace (just `api` instead of `apiv2`) and add support for getting configuration for the system API.
The method `system_api_opts` is just a copy of `apiv1_opts`, but it should be refactored to pull out logic that is shared between those methods, and `apiv2_opts`. I'll do that as a separate PR to keep this one smaller.

[2663] fix mcb bulk sync to find

---

azure-pipelines.yml

The Azure DevOps pipelines don't display what commands are running so it can be hard to understand what's happening just from the output.
Add `set -x` to all the steps' jobs in the build pipeline to enable built-in shell tracing.
:shipit:

[2700] add "set -x" to the azure pipeline jobs

---

config/database.yml
lib/mcb/commands/users/grant.rb

A couple of issues I had getting the app running locally during on boarding.
* Default the DB_HOSTNAME to `localhost`. This avoids having to set the env var to run things locally in dev and test.
* Remove the `--admin` option from the usage guidance in MCB as it was removed in 021ec535

Add default DB_HOSTNAME

---

app/models/course.rb
spec/factories/courses.rb
spec/models/course/assign_program_type_spec.rb
spec/models/course/funding_type_spec.rb
spec/models/course_spec.rb
spec/requests/api/v2/providers/courses/create_spec.rb
spec/services/courses/assign_program_type_service_spec.rb

Salaried courses could not be created by non-accredited providers. This was due to the `self_accredited?` method depending on the `accreditng_provider` association which was not set yet.
- Change `self_accredited?` to look at the provider type of the course's provider

[2750] Check self_accredited course by looking at provider

---

app/controllers/api/v1/courses_controller.rb
config/routes.rb

The V1 API controllers only expose an `index` endpoint but the routes were registered for all of the restful routes.
* Add `only: :index` to the three V1 controller routes
* Make `build_recruitment_cycle` private in `CoursesController` to make it clear it isn't an action
The Trello ticket mentions the `index` and `show` but I can't see `show`. Am I missing something?

[2742] Remove unused API V1 routes

---

app/controllers/api/v2/accredited_provider_training_providers_controller.rb
app/models/provider.rb
app/policies/provider_policy.rb
config/routes.rb
spec/models/provider_spec.rb
spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb

We are adding a page that lists all of the providers that deliver courses for a particular accredited provider.
* Add `/api/v2/recruitment_cycles/<year>/providers/<provider_code/training_providers` route
* Add `AccreditedProviderTrainingProvidersController` to serve that URL ^
* Add `Provider#training_providers` method
The language is a bit tricky here. We've gone with 'training provider' being a provider that doesn't have it's own accreditation but delivers courses on behalf of an 'accredited provider' (a provider that does. Both of these are represented as a `Provider` object.

1591 return providers accredited by accrediting provider

---

config/database.yml

Turns out this breaks things for other devs so reverting.
This was added to address an issue I had during on-boarding but is now broken for Linux users. The issue I had seems to have resolved so it may have been unrelated. Possibly moving from Postgres 12 to 9.6 caused an issue for me 🤷‍♂ 
Remove the localhost default value for `DB_HOSTNAME`

Remove localhost DB_HOSTNAME config

---

lib/mcb.rb
lib/mcb/commands/sites/geocode.rb
spec/lib/mcb/commands/sites/geocode_spec.rb

There are around 800 (out of 16000) Sites that are not currently geocoded. This because these Sites cannot be updated due to validation issues (e.g. they were imported from legacy with invalid attributes e.g. partial postcode or duplicate Site name). 
- Update the mcb geocode tasks (Sites and Providers) to skip validation then re-geocode all Sites (and Providers) with nil lat and long on each environment. 
* We update the lat and log for invalid sites as a one-off process.
* Command is repeatable in case we need.
* This is changing prod data so let's make sure it's covered with tests.
* mcb - add flag to allow geocode of invalid sites
Geocode a single site
bin/mcb sites geocode 11216495 -v -f
Geocode all the sites without lat long
bin/mcb sites geocode -v -f
See the update help with new …

[2767] mcb - add flag to allow geocode of invalid sites

---

app/controllers/api/v3/courses_controller.rb
app/services/courses/assignable_master_subject_service.rb
config/initializers/api_pagination.rb
config/initializers/jsonapi.rb
config/initializers/kaminari_config.rb
config/routes.rb
spec/requests/api/v3/providers/courses/index_spec.rb

In order to create the results page for find there must be a way to list all courses regardless of course.
Create the path /providers/courses, and allow it to be paginated.
https://jsonapi.org/format/#fetching-pagination

[2743] Add v3 /providers/courses endpoint

---

app/controllers/api/v3/courses_controller.rb
app/serializers/api/v3/serializable_course.rb
app/services/course_serializers_service_v3.rb
spec/requests/api/v3/providers/courses/show_spec.rb
spec/serializers/api/v3/serializable_course_spec.rb

Courses V2 serializer exposing the last enrichment for the frontend
- Create a new serializer for V3 that exposes the last "published" enrichment
- Remove metadata as they aren't needed in V3.
🚢

[2766] Add new course serializer for v3

---

app/jobs/geocode_job.rb
app/models/site.rb
app/services/geocoder_service.rb
lib/mcb.rb
lib/mcb/commands/providers/geocode.rb
lib/mcb/commands/sites/geocode.rb
spec/jobs/geocode_job_spec.rb
spec/services/geocoder_service_spec.rb

MCB's geocoding logic did not restrict searches to the UK region. This meant that geocoding of any invalid Sites (specifically those without an address) would result in coordinates set to somewhere in the U.S (this is the default behaviour).
- Extract geocoding logic to a new service. Geocoding is restricted to the UK (gb).
- Update mcb console and background job to use this new service
Centralising this logic will (hopefully) reduce the chances of bugs resulting from diverging paths in future

[2804] - Centralise geocoding logic

---

app/models/financial_incentive.rb
app/services/subject_financial_incentive_set_subject_knowledge_enhancement_course_available_service.rb
db/migrate/20200115141035_add_subject_knowledge_enhancement_available_to_financial_incentive.rb
db/schema.rb
db/seeds.rb
spec/factories/financial_incentives.rb
spec/models/financial_incentive_spec.rb
spec/services/subject_financial_incentive_set_subject_knowledge_enhancement_course_available_service_spec.rb
spec/support/reference_data.rb

Missing data for subject knowledge enhancement course available data for financial incentives for a given subject
Added missing subject knowledge enhancement
These are the subject/financial incentive concerned with
"Primary with mathematics", "Biology", "Computing", "English", "Design and technology", "Geography", "Chemistry", "Mathematics", "Physics", "French", "German", "Spanish", "Italian", "Japanese", "Mandarin", "Russian", "Modern languages (other)", "Religious education"

[2803] Added missing subject knowledge enhancement

---

app/controllers/api/v3/providers_controller.rb
app/serializers/api/v3/serializable_provider.rb
spec/requests/api/v3/providers/index_spec.rb
spec/serializers/api/v3/serializable_provider_spec.rb

Providers#index =   🐌 
Remove unused attributes from serializer
```
Completed #index -- { :controller => "API::V3::ProvidersController", :action => "index", :params => { "recruitment_cycle_year" => "2020" }, :format => "HTML", :method => "GET", :path => "/api/v3/recruitment_cycles/2020/providers", :status => 200, :view_runtime => 31667.63, :db_runtime => 47849.95, :status_message => "OK" }
```
```
Completed #index -- { :controller => "API::V3::ProvidersController", :action => "index", :params => { "recruitment_cycle_year" => "2020" }, :format => "HTML", :method => "GET", :path => "/api/v3/recruitment_cycles/2020/providers", :status => 200, :view_runtime => 784.47, :db_runtime => 92.54, :status_message => "OK" }
```

Add V3 serializer for providers endpoint

---

lib/mcb/azure.rb

This has two benefits:
* Easier workflow for throw-away qa/staging data
* Makes it stand out much more when you do actually want production
Doing a lot of qa/staging stuff while building a new query before
running on prod.
* Don't prompt for environment confirmation on qa/staging
Ignore whitespace to see a more meaningful diff
:ship:

mcb - Don't prompt for environment confirmation on qa/staging

---

.rubocop.yml
spec/factories/courses.rb
spec/factories/organisations.rb
spec/factories/providers.rb
spec/factory_specs/course_spec.rb
spec/factory_specs/providers_spec.rb
spec/models/provider_spec.rb
spec/models/recruitment_cycle_spec.rb
spec/requests/api/v2/providers/courses/publishable_spec.rb
spec/services/providers/copy_to_recruitment_cycle_service_spec.rb
spec/support/reference_data.rb
spec/support/test_setup.rb

We recently undertook a spike on our test suite to identify opportunities for improve, particularly around decreasing the time it takes to run the tests.
This PR acts on one the recommendations and aims to create a standard test setup process. What this means is that each test will have access to standardised set of test data (with the ability to customise where required). This will remove a lot of the duplicated factories that are instantiated across all the tests and increase overall speed. 
This work is based on similar work undertaken for [Ministry Of Justice Correspondance Tool](https://github.com/ministryofjustice/correspondence_tool_staff/blob/master/spec/support/standard_setup.rb)
NB: This PR should be considered a 'first iteration'. Functionality has been added to create a …

[2731] Test setup

---

etc/ttapi-slow-response-times.yaml

After the recent outage we had, I've taken a look into how to get alerts out of logit.i to let us know that we're getting slow requests. I've created an ElastAlert there that will trigger if the average request time is over 2.5s over a period of 60 seconds.
Add the ElastAlert YAML definition to the repo so we have it. Note that sensitive information has been stripped out of the definition and have to be re-added.
A sample of the alert is here: https://ukgovernmentdfe.slack.com/archives/CGVNJ2Q2F/p1579091158144800
This alert is already deployed.

[2809] add ElastAlert definition for slow requests

---

app/controllers/api/v3/providers_controller.rb
spec/requests/api/v3/providers/index_spec.rb

In order to support searching by providers on Rails Find - we need the endpoint in order to search for a specific provider by name or code
Additionally, as this endpoint will be getting hit frequently (potentially once ever key press) it needs to avoid slow performance by accidentally loading more than required, as such sparse field support has been added (https://jsonapi.org/format/#fetching-sparse-fieldsets)
- Add the ability to support a search param at  `v3/.../providers?search=Meow`
- Add the ability to define the fields you wish to return 
- E.g. `v3/.../providers?fields[providers]=provider_name` for returning only the `provider_name`
- **Note** This currently defaults to `provider_name`, `provider_code` and `recruitment_cycle_year` to avoid breaking anything that currently depends …

[2861] Add search to V3 Provider Index

---

spec/services/courses/generate_course_name_service_spec.rb

This is being cached on the class and so bleeds between specs. Card
added to fix but this will unflakiness the specs in the meantime.
The spec/services/courses/generate_course_name_service_spec.rb are failing intermittently on various builds [(example)](https://dfe-ssp.visualstudio.com/Become-A-Teacher/_build/results?buildId=43165&view=ms.vss-test-web.build-test-results-tab&runId=1148374&resultId=101092&paneView=debug) 
There is caching on the Secondary subject but the value is cached on the class so it is bleeding across specs.
This change is temporary to get PRs through CI for now. I've added another card to fix the cacheing to work properly.
* Clear the modern languages cache before each course name spec
The failures are intermittent and only happen when the full suite is run so this …

[2827] Clear modern language cache

---

app/models/user.rb
spec/models/user_spec.rb

We get late failures when trying to send the welcome email.
Adding the valuation will flush out whatever is incorrectly setting
these to nil.
I believe this has affected our provider users too.
[2907] Require first/last name in user model
```
tim@fox:~/repo/dfe/teacher-training-api(master)
$ bin/mcb users grant wibble@timwise.co.uk
Audit user: Tim Abell <tim.abell@digital.education.gov.uk>
wibble@timwise.co.uk appears to be a new user
First name?  
Last name?  
User:
+------------------------+----------------------+
| id                     |                      |
| email                  | wibble@timwise.co.uk |
| first_name             |                      |
| last_name              |                      |
| first_login_date_utc   |                      |
| last_login_date_utc    | …
```

[2907] Require first/last name in user model

---

azure/template.json

When a server reaches the allocated storage limit, the server is marked as read-only. However, if we enable storage auto grow, the server storage increases to accommodate the growing data
Allow enable/disable of PSQL DB storage auto growth through a parameter/pipeline variable 
https://trello.com/c/sgCZ91FB/208-auto-growth-for-postgresql-databases

208-Parameterised PSQL DB autogrowth

---

app/controllers/api/v3/course_searches_controller.rb
app/models/course.rb
app/models/site_status.rb
app/serializers/site_status_serializer.rb
app/services/course_search_service.rb
config/routes.rb
db/migrate/20200131104849_add_site_status_indexes.rb
db/schema.rb
spec/factories/site_statuses.rb
spec/models/course_spec.rb
spec/models/site_status_spec.rb
spec/requests/api/v3/courses/index_spec.rb
spec/serializers/site_status_serializer_spec.rb
spec/services/course_search_service_spec.rb
spec/support/test_data_cache.rb

Find needs to be able to display a list of currently available courses and filter them by various filters.
* Add scopes to `Course` to enable filtering
* Add a `CourseSearch` service that builds a `Course` scope based on the provided filter parameters.
* Add `/api/v3/recruitment_cycle/<year>/courses` endpoint
* Add indexes to `course_site` table for the enums on `SiteStatus`
Filter params are passed in the following format:
`/api/v3/recruitment_cycle/<year>/courses?filter[salary]=true&filter[qualifications]=pgce,pgde`
Out of scope in this PR
* Only returning 'published' courses
* Location filtering

2827 add filtering for courses to api

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
config/locales/en.yml
spec/models/course_spec.rb
spec/serializers/site_status_serializer_spec.rb

The subjects page is unable to select modern languages because the validation for modern languages is triggered
Separate the error for modern languages being missing from other subject errors and create a method for retrieving modern language subjects only.

[2859] Basic seperation of modern language subjects and subjects

---

app/services/subjects/subject_area_creator_service.rb
db/migrate/20200207094915_fix_subject_area_name_cases.rb
db/schema.rb
spec/requests/api/v3/subject_areas/index_spec.rb
spec/services/subjects/populate_subject_areas_service_spec.rb

The names of two subjects areas have incorrect casing.
Change the names of those subject areas so they appear correctly in Find:
* Secondary: Modern `L`anguages => Secondary: Modern `l`anguages
* Further `E`ducation => Further `e`ducation
**Before:**
**After:**
* run migration in teacher-training-api: `bundle exec rails db:migrate RAILS_ENV=development`
* visit http://localhost:3002/results/filter/subject

[2906] Add a migration to fix subject areas naming

---

azure/template.json

Microsoft is disabling TLS 1.0 and 1.1 from Azure Redis Cache on 31st March.
Update ARM template and enable TLS1.2 for Azure Redis Cache
Apply the changes on QA and Staging initially to ensure Rails code is compatible with TLS1.2.
https://docs.microsoft.com/en-gb/azure/azure-cache-for-redis/cache-remove-tls-10-11
https://trello.com/c/pOTczm7C/2925-test-azure-redis-cache-with-tls12

2925 test azure redis cache with tls12

---

app/services/courses/validate_custom_age_range_service.rb
spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb
spec/services/courses/validate_custom_age_range_service_spec.rb

An option for age ranges on the frontend did not pass validation
Increase the validation range to support the option the user can select
- Create a secondary course on course creation flow
- Select "14 to 19" 
- Press continue

[2918] Increase valid age range possibilities

---

app/models/course.rb
app/services/course_search.rb
spec/models/course_enrichment_spec.rb
spec/models/course_spec.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_spec.rb

The courses endpoint should only return published courses. In this context a 'published' course is one that has its most recent associated `CourseEnrichment` in `published` state.
* Add `Course.published` scope. This delegates the 'what is published' stuff to `CourseEnrichment`. I think that's the right place for it but it's tricky to get a chainable scope back from `CourseEnrichment.current_published`. I tried variations on SQL and Arel but it either didn't work or was super slow. This seems to work ok but the `group` calls need to be 'creatively' namespaced.
* Add the `published` scope into `CourseSearch`
This is on top of #1142 which is still in review and likely to change. The CI failures aren't directly related to this work. I'm looking at those separately.

2855 add filtering for courses to api part 2

---

app/serializers/api/v2/serializable_subject.rb
spec/requests/api/v2/providers/courses_spec.rb
spec/requests/api/v3/providers/courses/index_spec.rb
spec/serializers/api/v2/serializable_subject_spec.rb

We need to display information on Subject Knowledge Enhancement (SKE) course availability on subject filter page in Find. 
Add `subject_knowledge_enhancement_course_available` to Serializable Subject attributes

[2905] Add subject_knowledge_enhancement_course_available attribute

---

app/controllers/api/v3/courses_controller.rb
app/models/course.rb
app/services/course_search_service.rb
spec/models/course_spec.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_service_spec.rb

Users on Search and Compare can currently sort alphabetically by provider name, in order to provide this functionality for Find we must create an endpoint that supports this behaviour in accordance with JSON API's standards
Add an endpoint that supports sorting
https://jsonapi.org/format/#fetching-sorting

[2958] Add ability to sort by provider name on v3 course endpoint

---

app/serializers/api/v3/serializable_course.rb
spec/requests/api/v3/providers/courses/show_spec.rb

The latest published enrichment isn't always correct because of the order 
Use `max_by` instead of `last` as per - https://github.com/DFE-Digital/teacher-training-api/blob/master/app/serializers/search_and_compare/course_serializer.rb#L152:L156
🚢

[2949] Fix api v3 latest published enrichment

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
app/models/course_subject.rb
app/models/subject.rb
db/migrate/20200212161248_add_position_to_course_subject.rb
db/schema.rb
spec/models/course_spec.rb
spec/models/course_subject_spec.rb
spec/requests/api/v2/build_new_course_spec.rb
spec/requests/api/v2/providers/courses/update_subject_spec.rb
spec/services/courses/generate_course_name_service_spec.rb

Secondary courses can have multiple subjects that have to be stored in the correct order to ensure that bursaries are calculated correctly.
To solve this, we are adding a `position` value on the `course_subject` in order to keep the original order they are given.
- Add an integer field `:position`  to `CourseSubject`
- Assign `position` when course subjects are added to a secondary course
- Assign `position` based on the order of the params given when updating/building a new course

[2909] Change course to support ordering of subjects

---

app/models/course.rb
app/models/subject.rb
app/services/course_search_service.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_service_spec.rb

Allow courses to be filtered by subject(s) (V3 API)

[2980] - Add subject filtering to the V3 API

---

app/controllers/api/v2/providers_controller.rb
app/controllers/api/v3/providers_controller.rb
app/models/course.rb
app/models/provider.rb
app/services/course_search_service.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_service_spec.rb

https://github.com/DFE-Digital/find-teacher-training/pull/106 highlighted that we need the ability to sort by both course name and provider name, as this is what C# does.  
Add canonical sorting.
https://github.com/DFE-Digital/search-and-compare-api/blob/3aa6be82dcf5548892580e900ea1e37decf63a0f/src/api/Controllers/CoursesController.cs#L226

[2993] Add support for sorting by course name as well as provider name

---

app/models/course.rb
app/services/course_search_service.rb
spec/models/course_spec.rb
spec/requests/api/v3/courses/index_spec.rb

[Check this trello card](https://trello.com/c/RBaGAf8C/2932-m-add-provider-filtering-to-the-api) for details - we're adding the ability to filter courses by provider name. 
Add scoping to providers to filter by exact provider name matches
Add scoping to courses to filter by provider names
Add method to CourseSearchService to filter by provider names

2932 m add provider filtering to the api

---

app/controllers/api/v2/courses_controller.rb
app/models/course_subject.rb
config/locales/en.yml
spec/requests/api/v2/providers/courses/update_subject_spec.rb

To prevent people selecting two of the same subject in Publish, we prevent duplicate subject IDs being passed in in the controller
- Validate uniqueness of `course_subjects`
- Check `subject_ids` in the controller before assignment
- Go to publish
- Create a new course -> Add duplicate secondary subjects
- Edit an existing course -> Add duplicate secondary subjects

[2988] Validate courses dont have duplicate subjects

---

app/models/course.rb
app/services/course_search_service.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_service_spec.rb

We need to allow to filter `send_courses` as it is [used by Find](https://github.com/DFE-Digital/find-teacher-training/blob/master/app/view_objects/results_view.rb#L108)

[3016] Add send_courses filtering to the V3 

---

app/models/site_status.rb
spec/requests/api/v2/providers/courses_spec.rb

New Find was displaying `Yes` for all sites with vacancies. This was due to
incorrectly calculating the value on the model when serialising.
- Change `has_vacancies?` to correctly return true/false
- Set a course to have a site with no vacancies
- Look at the course on find
- The site should show `No` for vacancies

[3047] Correctly show if site_status has vacancies

---

db/migrate/20200221150255_add_subject_indexes.rb
db/migrate/20200221150821_add_subject_area_indexes.rb
db/migrate/20200221151215_remove_unused_subject_columns.rb
db/schema.rb

###Context
There were some production issues on 20/2/2020 after we deployed some subject updates. The updates don't look to have caused the issues but while investigating I spotted a couple of minor things in the DB.
* Remove unused subject area columns
* Add index to subject type as it is the foreign key for subject area
* Add index to subject subject_code as we use it in the API query
* Add index to subject area typename as it is the primary key
`SubjectArea` uses `typename` as the primary key. The fields on subject that have been removed are all `nil` on production.

[3018] Update subject db schema

---

app/mailers/course_update_email_mailer.rb
azure/template.json
config/settings.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml
spec/mailers/course_update_email_mailer_spec.rb

Co-authored-by: defong <de_fong2k@yahoo.com>
[See this card for more details](https://trello.com/c/Xnoghg3q/3003-s-notify-accredited-body-users-that-something-has-changed-on-a-course)
There is also a Notify template that needs to be finalised, which this will directly link to. There's a template ID that will need to be included in the live environments as a result. 
Adds a mailer to mailer set that can be used to invoke an API call to notify.

[3003] Add mailer for course updates

---

azure/template.json

[See this Trello card for more detail](https://trello.com/c/4PlX8ZQF/3056-azure-config-not-set-correctly-for-course-update-email-template-id#)
Fix the Azure config for the CourseUpdateEmailTemplateId

[3056] Fix course update email template ID parameter

---

README.md

The 2019 endpoint no longer responds.
Readme - update year in example curl for v1
:ship:

Readme - update year in example curl for v1

---

app/controllers/api/v3/courses_controller.rb
spec/requests/api/v3/courses/index_spec.rb
spec/requests/api/v3/providers/courses/index_spec.rb

- The inclusion of non-standard meta-information should be returned in a 'meta object'. See https://jsonapi.org/format/#document-meta
- This change is required to fix the inaccurate results page count on Find Teacher Training (a separate PR for Find Teacher Training required, to follow)
- Return course count in global metal object
- Do not rely on the header 'Total' for accessing course count. This appears to go against the JSON API spec.

[3057] - Return course count in meta object

---

app/models/provider.rb
app/models/user.rb
app/models/user_notification.rb
db/migrate/20200227105316_add_user_notifications_table.rb
db/schema.rb
spec/models/provider_spec.rb
spec/models/user_notification_spec.rb
spec/models/user_spec.rb

In order to control which users have notifications on for which provider - we need to add a join
table between the `User` and `Provider`.
- Add a join table between user and provider

[3025] Add User notifications table

---

Gemfile
app/models/course.rb
app/services/course_search_service.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_service_spec.rb

- https://trello.com/c/8wGCf2P3/3069-m-sort-courses-by-distance-to-sites
- Backend can now sort results by distance from origin
- Able to sort results by distance from origin
- Does not implement parameter checking
- Given you have a dataset with geocoded sites
- via rails console `Course.limit(100).by_distance(origin: [54.9713392, -1.6112336])`
- or other origin. this should return results sorted by distance from origin with closest first
- the should be using the geocoded data from `Site`

[3069] Sort courses by distance

---

app/models/course.rb
config/locales/en.yml
spec/models/course_spec.rb

When a user updates a course, we want to notify users of the accreiditng body 
who have opted in to notifications.
The work for the notifications table and the mailer has been done prior to this.
This does **not** cover notifications for the following:
- Subjects
- Locations
- Add in an `after_update` callback to send a notification
- Add a `UserNotifciation` for yourself for an accreiditng body
- Edit the `age_range_in_years` of the course
- See the notification get sent

[3034] Send notifications when a courses basic details has changed

---

app/controllers/api/v3/application_controller.rb
config/initializers/api_pagination.rb
config/initializers/kaminari_config.rb
spec/controllers/api/v3/application_controller_spec.rb

- https://trello.com/c/zOB0CYyM/3061-fix-sitemap-backend
- We firstly need to solve the problem of being able to disable pagination before we even begin to fix the sitemap
- This PR allows v3 endpoints to disable pagination if desired
- There will be a subsequent PR to fix the sitemap
- If requested pagination is over the default number we check if this is allowed
- This check is done by implementing `allowed_to_disable_pagination?`
- If not implemented or returns false then we fallback to the default
- Existing endpoints should still be paginated to 100
- Implement `allowed_to_disable_pagination?` on a controller to return true
- if `params[:page][:per_page]` provided pagination should be respected
- There will be a subsequent PR to fix the sitemap

[3061] Able to disable pagination for v3

---

app/controllers/api/v3/courses_controller.rb
app/serializers/api/v3/serializable_course.rb
spec/requests/api/v3/courses/index_spec.rb
spec/requests/api/v3/providers/courses/index_spec.rb
spec/requests/api/v3/providers/courses/show_spec.rb

- https://trello.com/c/zOB0CYyM/3061-fix-sitemap
- Sitemap currently only able to generate 10 courses due to pagination
- This is the backend fix to remove pagination from courses if correct parameters are sent
- Switch v3 courses controller to use v3 courses serialiser
- Courses controller can disable pagination if correct params sent
- Courses controller now always includes provider association
- This is to prevent n+1 queries
- jsonapi :include is not used as causes many additional SQL queries
- Test slices out updated_at as cannot use Timecop as multiple providers cannot be created at the same time due to uniqueness index
- Visit http://localhost:3001/api/v3/recruitment_cycles/2020/courses?fields%5Bcourses%5D=course_code,provider_code,changed_at&page[per_page]=20000
- Should return …

[3061] Can return all courses for sitemap

---

app/controllers/api/v3/provider_suggestions_controller.rb
app/models/provider.rb
spec/models/provider_spec.rb
spec/requests/api/v3/providers/suggest_provider_spec.rb

prevention for suggesting providers with no courses
Added prevention for suggesting providers with no courses
Provider that are either the accredited body or the provider of a findable course will only be shown

[3094] Added prevention for suggesting providers with no courses

---

app/controllers/api/v3/courses_controller.rb
app/services/course_search_service.rb
spec/requests/api/v3/courses/index_spec.rb
spec/services/course_search_service_spec.rb

- https://trello.com/c/c8h5V8zx/3086-qa-order-by-distance-not-always-correct
- This removes duplicates from search results
- Duplicates mainly due to courses having multiple sites
- when sorting by distance from origin deal with courses with multiple
sites
- only return a course once even if it has multiple sites
- use the closest site when sorting by distance
- only use site that are new or running
- now select `distinct` courses for search results
- meta count scopes to `course.id`
- add tests to cover duplicate results bug
- http://localhost:3002/results?fulltime=False&hasvacancies=True&l=1&lat=50.82253000000001&lng=-0.137163&loc=Brighton%2C+UK&lq=Brighton%2C+UK&parttime=False&qualifications=QtsOnly%2CPgdePgceWithQts%2COther&rad=20&senCourses=false&sortby=2&subjects=31
- There should …

[3086] De-duplicate search results

---

.rspec_parallel
spec/rails_helper.rb
spec/spec_helper.rb

- https://trello.com/c/VKUaOutH/3108-improve-parallel-tests-speed
- Improve test suite running time
- This uses a feature in parallel_tests to even tests across cores
- This is done by logging test run times
- For me this has shaved 2 minutes off the test suite
- Run the test suite via `bundle exec rake` twice
- The second run through should be quicker

[3108] Improve parallel specs

---

app/services/course_search_service.rb
spec/requests/api/v3/courses/index_spec.rb

When we calculate the nearest site for a course we want to exclude sites
that have insufficient address data as they cannot be accurately
geocoded.
Add a where clause that only includes sites if they have an `address1` or
`postcode` value when building the sites with distance Arel table.
To test run a location search. Select one of the lower ranking results. In the console create a `Site` with only lat, lng, code and provider ID and `save(validate: false)`. Use the lat and lng of the search and the provider ID of the chosen course. Add the site to the course `Course.sites << site`. This course should now appear first before this change but remain in its original position after the change.
Before: The course Chemistry(test) has had a site with no address added that has a lat/lng that …

[3097] Exclude non-locatable sites from ordering

---

app/mailers/course_update_email_mailer.rb
spec/mailers/course_update_email_mailer_spec.rb

Update time format from 14:54 to 2:54pm in the course changes notifications emails.

[3080] Format date time to our standard format

---

app/controllers/concerns/next_link_header.rb
app/lib/time_format.rb
app/models/course.rb
app/serializers/api/v2/serializable_course.rb
app/serializers/api/v3/serializable_course.rb
spec/lib/time_format.rb

There are a number of date formats used across TTAPI and it's possible that these could begin diverging in implementation as we proceed with adding notifications.
DRY up all time date formatting using a module.
This provides a place for the date format needed by notifications to live.

[3111] Cleanup time formats

---

app/services/course_search_service.rb
spec/requests/api/v3/courses/index_spec.rb

- https://trello.com/c/fYgK7vnQ/3118-sort-by-distance-only-uses-sites-that-have-been-geocoded
- We are not excluding un-geocoded sites from distance sorting
- These sites are then deemed be at the origin of the search query as a result
- When sorting by distance we exclude any site that has not been geocoded
- These are sites that do not have latitude and longitude present
- visit http://localhost:3002/results?fulltime=False&hasvacancies=True&l=1&lat=53.9588365&lng=-1.0794777&loc=York+YO1%2C+UK&lq=York+YO1%2C+UK&parttime=False&qualifications=QtsOnly%2CPgdePgceWithQts%2COther&rad=20&senCourses=False&sortby=2&subjects=31%2C32
- Results should be ordered correctly

[3118] Ignore ungeocoded sites in distance search

---

app/controllers/api/v3/provider_suggestions_controller.rb
spec/requests/api/v3/providers/suggest_provider_spec.rb

Please see https://github.com/DFE-Digital/find-teacher-training/pull/197 for further context. This PR should be merged first. 
The ProviderSuggestions controller should process encoded queries and not return a Bad request status (400) by default. If a provider search still returns no results then the API will return an empty array and 200 status.

[3120] - Accept non-alphanumeric provider suggestion queries

---

azure/template.json

On 11 March 2020 at 9:20pm we had an outage on Azure Redis Cache. This was caused by Microsoft patching the underlying resources.
Since we are using Basic tier, when that once VM goes down for patching (either OS or Redis Runtime), then the Redis instance will be inaccessible for the duration of the pating. For this reason we do not offer an SLA for the Basic cache SKU. Basic caches are good for test/development environments but if your cache is not able to tolerate this kind of downtime, we suggest you to go with a Standard cache which does offer an SLA.
Parameterise the redis template ARM so we can specify a different instance type with high availability.
Review the redis ARM template and the building block.

[3130] Add redisCacheSKU to ARM template

---

app/mailers/course_update_email_mailer.rb
config/settings.yml
config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml
spec/mailers/course_update_email_mailer_spec.rb

The "view course" link in the course updated email is linking to course details on Publish instead of Find.
Course update notification email now links to Find Teacher Training
Anyone know how I can test this on QA? 
@danielburnley

[3117] - Course updated notification: update "view course" link

---

app/controllers/api/v3/providers_controller.rb
spec/requests/api/v3/providers/show_spec.rb

- https://trello.com/c/u4DDrH4M/3132-bug-triage-activemodelunknownattributeerror-apiv3providerscontrollershow-error-unknown-attribute-urlhelpers-for-secondarysubject
- showing a provider and including `courses.subjects` would throw an error
- Including `courses.subjects` on a provider would throw an error
- This is due to it not able to find correct serializer for subjects
- Now use serializer service to find serializer
- visit http://localhost:3001/api/v3/recruitment_cycles/2020/providers/1N1?include=courses.subjects
- should not throw an error
- should see json

[3132] Fix provider including `course.subjects`

---

app/mailers/course_update_email_mailer.rb
spec/mailers/course_update_email_mailer_spec.rb

Email notification points users to t https://www2.qa.find-postgraduate-teacher-training.education.gov.uk/organisations/1DD/2020/courses/28TR which does not exist.
Instead, it should point them to t https://www2.qa.find-postgraduate-teacher-training.education.gov.uk/course/1DD/28TR

[3139] Fix course link in the notification email

---

app/mailers/course_update_email_mailer.rb
app/models/course.rb
app/services/course_attribute_formatter_service.rb
config/locales/en.yml
spec/mailers/course_update_email_mailer_spec.rb
spec/models/course_spec.rb
spec/services/course_attribute_formatter_service_spec.rb

We want to send an email notification when a course is updated. The email will contain the name of the attribute that has been updated, the original value and the updated value. This PR adds the original and updated value.
Note: The API currently only supports one attribute being updated per update. This has been implemented because the Publish app only supports updating one attribute at a time (I think). The API does support updating more than one attribute at a time so we shouldn't assume that a caller won't do that. I've not addressed that here. I've added a card to refactor this code too to move the notification and email concerns out of the Course model. [Trello](https://trello.com/c/vItr7tVZ/340-move-notification-sending-out-of-course-callbacks)
* Update the mailer to receive …

[3116] Add previous value and current value to change email notification

---

config/initializers/request_output.rb
lib/rack/request_output.rb

- Developers find it hard to see what API endpoint is being hit
- And also what response is being sent back
- In development this adds a piece of rack middleware
- This outputs the URL that hit the API
- This allows devs to repeat the same API calls in their tool of their choice to see the response
- fire up locally in dev mode
- hit the api directly or via find
- should see api endpoint being hit
- should able to curl the url to see response given

[3142] Add request output middleware

---

app/models/course.rb
spec/models/course_spec.rb

The accredited body does not see all the courses they expected to see on Find when they search for a specific provider.
The Find search should have displayed all the courses that U80 accredits including their own courses.
When you search for a provider on Find, you should see all courses offered by the provider, including the courses they accredit.
:ship:

[3141] Fixed query for provider_name

---

config/settings/production.yml
config/settings/qa.yml
config/settings/staging.yml
config/settings/test.yml

We are using this URL in links within the course update/create email. Turns out it doesn't work.
Change `service` to `education`.

Fix find URL

---

app/controllers/api/v2/sessions_controller.rb
app/models/course.rb
app/services/courses/publish_service.rb
app/services/send_welcome_email_service.rb
azure-pipelines.yml
bg-mailer/Dockerfile
config/application.rb
docker-compose.yml
spec/models/course_spec.rb
spec/requests/api/v2/session_spec.rb
spec/services/courses/publish_service_spec.rb
spec/services/send_welcome_email_service_spec.rb

* We have a new Sidekiq background container running, similar to geocoding.
* Mail is sent out via a background task.
* When you call `.deliver_later` on the mailers it will [automatically use an ActionMailer::DeliveryJob.](https://edgeapi.rubyonrails.org/classes/ActionMailer/MessageDelivery.html#method-i-deliver_later)

[3102] - Background mail notifications

---

azure/template.json

We're adding API docs which benefit from some static assets like CSS and JS files. This API app doesn't have an asset pipeline, so we've chosen to serve out static files to manage this.
Enable serving out static files in deployed environments.
Normally this isn't recommended. Some thoughts I added to the Trello card:
> Normally this is discouraged as the upstream webserver, e.g. Apache or NGinx, is better placed to serve out this content. However, we don't have the luxury of one of those webservers fronting our app, and I don't believe that whatever it is can be configured to serve this file out.
>
> We could also enable the asset pipeline, but it's kind of nice that this app is API-only, and we are unlikely to get enough legitimate requests for these assets for it to be an issue. …

[3112] enable Rails to serve static files in deployed environments

---

azure/template.json

The mailer container instance cannot send mail as it does not have access to Notify credentials.
Add GOV.UK Notify env vars to container instance

[3102] - Update Azure Template

---

Gemfile
Gemfile.lock
README.md
app/models/api_spec.rb
app/models/api_spec/public.rb
config/initializers/rswag-ui.rb
config/initializers/rswag_api.rb
config/routes.rb
spec/api/courses_spec.rb
spec/swagger_helper.rb
swagger/v1/swagger.json
swagger/v1/template.yml

- This implements rswag which allows for API endpoints to be documented more easily
- It also allows responses to be tested against the generated OpenAPI specification that we now generate 
- Added rswag related gems
- Documentation via swagger available at /api-docs
- Updates api spec, CourseSingleResponse.data is now an array
- Update readme on how to generate OpenAPI spec
- Add test on api courses response matches JSON schema
- swagger docs available at http://localhost:3001/api-docs
- generated OpenAPI specification should be similar to previous hand crafted one

[3168] Near parity of api docs via rswag

---

app/models/provider.rb
app/models/site.rb
app/services/geocoder_service.rb
spec/models/provider_spec.rb
spec/models/site_spec.rb
spec/services/geocoder_service_spec.rb
spec/spec_helper.rb
spec/support/geocoder_helper.rb

Some legacy sites and providers have missing address details, which are considered 'invalid'. When we batch geocode we override the validation checks and attempt to geocode their address with what little information we have. 
A problem arises when we attempt to geocode Sites and Providers with no address details whatsoever (i.e. `address1`, `address2`, `address3`, `address4`, `postcode` are all blank).
Batch geocoding is done in a single process. On Publish, when a site or provider is updated, this is done in a separate process via a back ground job. 
_Currently_, where a Site or Provider **has no address** whatsoever:
1. The mcb geocode command geocodes the object via the GeocoderService.
2. The Geocoder API returns an unsuccessful response. The GeocoderService still attempts to update …

[3072] - GeocodingService bug fix

---

app/models/course.rb
app/models/financial_incentive.rb
app/models/site.rb
app/models/user.rb
app/models/user_notification.rb
app/serializers/course_serializer.rb
app/serializers/site_serializer.rb
spec/factories/courses.rb
spec/factories/financial_incentives.rb
spec/factories/sites.rb
spec/factories/user_notifications.rb
spec/factories/users.rb
spec/models/course_spec.rb
spec/models/financial_incentive_spec.rb
spec/models/site_spec.rb
spec/models/user_notification_spec.rb
spec/models/user_spec.rb
spec/serializers/course_serializer_spec.rb
spec/serializers/site_serializer_spec.rb

https://github.com/DFE-Digital/teacher-training-api/pull/1270
Merged in daf1e293c46b978e9fd89db681e3ee10aa25fb92
> Bumps annotate from 3.1.0 to 3.1.1.
Update annotations after gem update
:eyes:

Update annotations after gem update

---

azure-pipelines.yml

In order to send the commit sha of the release to Sentry/Logit - we need to store it in the build artifact to be accessible.
- Store the commit sha in a file to be later accessed.

[3194] Add commit sha to deploy artifact

---

app/controllers/api/v2/courses_controller.rb
app/models/course.rb
config/routes.rb
spec/models/course_spec.rb
spec/requests/api/v2/courses_spec.rb

Changes are required for the Accredited body feature in Publish.
Allow retrieving courses across multiple training providers in one
hit. Specifically for accredited bodies to be able to see the courses of
their training providers.
Having this as a new resource-style endpoint with the ability to apply
filters will allow us to consolidate all the other course endpoints.
- Generate a token: TOKEN=`bin/mcb apiv2 token generate -S secret user@example.com`
- `curl -H 'Accept: application/json' -H "Authorization: Bearer ${TOKEN}" 'http://localhost:3001/api/v2/recruitment_cycles/2020/courses?filter%5Baccrediting_provider_code%5D%3DE69%27’`

[3190] Add course resource to v2

---

config/initializers/logstash.rb
config/initializers/raven.rb

We want to see the version of the code that is deployed in both logging and when we get errors reported
- Add the `COMMIT_SHA` to both Sentry and Logstash

[3195] Add the commit sha to logging and sentry

---

app/controllers/api/v3/application_controller.rb
app/controllers/api/v3/subjects_controller.rb
app/models/subject.rb
config/routes.rb
spec/models/subject_spec.rb
spec/requests/api/v3/subject_areas/index_spec.rb
spec/requests/api/v3/subjects/index_spec.rb

Find currently contains this hack to get all subjects.
https://github.com/DFE-Digital/find-teacher-training/blob/master/app/view_objects/results_view.rb#L364
Have v3 provide a proper way to provide all subjects

[3210] Add v3 subjects endpoint

---

app/controllers/api/public/v1/application_controller.rb
app/controllers/api/public/v1/locations_controller.rb
config/routes.rb
spec/api/locations_spec.rb
swagger/public_v1/api_spec.json
swagger/public_v1/template.yml

- https://trello.com/c/fdFc3kNR/2893-create-openapi-spec-for-locations
- Add Location to API documentation as it is does not exists
- Add documentation
- run docs, see https://github.com/DFE-Digital/teacher-training-api#documentation
- visit http://localhost:3001
- see added Location documentation, compared to https://api2.qa.publish-teacher-training-courses.service.gov.uk/#about

[2893] Add Location to API docs

---

app/controllers/api/public/v1/courses_controller.rb
config/routes.rb
spec/api/courses_spec.rb
spec/api/locations_spec.rb
spec/swagger_helper.rb
swagger/public_v1/api_spec.json
swagger/public_v1/template.yml

- https://trello.com/c/AEcOqa1a/3218-fix-api-docs-endpoint-paths
- api docs shows very long endpoint names with base url
- this change moves the endpoint prefix to the base suffix
- api docs now use shortened endpoint urls
- the prefix is now server url
- add place holder endpoint for un-implemented courses endpoint
- setup api docs, see http://localhost:4567/api-reference.html#teacher-training-courses-api
- visit api docs: http://localhost:4567/api-reference.html#teacher-training-courses-api
- compare to https://api2.qa.publish-teacher-training-courses.service.gov.uk/api-reference.html#teacher-training-courses-api
- should no longer see long endpoint names on LHS

[3218] Fix base url for api docs

---

Gemfile
Gemfile.lock
docs/performance-testing.md
spec/performance/pre_deploy_spec.rb
spec/rails_helper.rb

We have performance issues on some endpoints. As part of the work to address this we want to run performance regression tests as part of the staging deploy pipeline. The thresholds in theses tests will be reduced as we improve performance.
The tests are intended to warn (but not block) during deployment. They haven't been added to the pipeline yet as this will need to be merged before they can be added.
Add spec/performance/pre_deploy_spec.rb that runs multiple requests against specified endpoints and compares their average response against a predefined threshold.
The tests can be run locally as per the docs.

3033 setup benchmarking performance test

---

spec/api/courses_spec.rb
swagger/public_v1/api_spec.json
swagger/public_v1/template.yml

- https://trello.com/c/xKXyUcCk/3163-review-course-api-spec-descriptions-and-examples
- Courses endpoint api docs are not complete and this adds more info
- Adds Filter and Sort Schema for courses endpoint
- Updates descriptions and examples for courses endpoint
-  Fix newlines appearing within docs due to wrong yaml syntax
- run docs, see https://github.com/DFE-Digital/teacher-training-api#documentation
- visit visit http://localhost:3001
- see updated course documentation, compared to https://api2.qa.publish-teacher-training-courses.service.gov.uk/#about
- copy can be found at https://docs.google.com/document/d/1seXGkS3W5zr1matZPuuRNxuOCAOyoIJeXfk-iJQlsyQ/edit

[3163] Update API docs for courses endpoint

---

.rspec
spec/performance/pre_deploy_spec.rb

We are running specs against live staging from a docker container which currently won't work without a DB available.
Remove the .rspec file
This file was requiring spec_helper for all specs. This isn't necessary because:
a) spec_helper is required explicitly in all of the specs anyway
b) rails_helper is being required in some of the files that spec_helper requires so this ends up also requiring rails_helper which loads the app and this isn't what we want (we should fix that too)
c) this stops the pre_deploy_spec being run on a docker container without db access which we want to do.

[3033] Remove .rspec file
