app/controllers/api/v2/courses_controller.rb, spec/requests/api/v2/courses_spec.rb
The new courses endpoint was returning courses for all recruitment cycles as well as discarded courses. 
Stop the endpoint doing this, so it behaves like the `provider/:id/courses` endpoint
- Checkout this branch and run the server
- Open console in Publish  run `Course.where(recruitment_cycle_year: "2020", accrediting_provider_code: "B20").count` 
- It should return 36 (not 84)
=> [3224] Make v2 course endpoint return courses correctly

swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/LocationStatusAttributes.yml, swagger/public_v1/component_schemas/LocationStatusRelationships.yml, swagger/public_v1/template.yml
- https://trello.com/c/9fqUlf8O/2892-s-create-openapi-spec-for-courselocations
- Add LocationStatus to API docs as it does not exists
- Add documentation for LocationStatus
- fire up docs, see https://github.com/DFE-Digital/teacher-training-api#documentation
- Should see new documentation
- this depends on https://github.com/DFE-Digital/teacher-training-api/pull/1287/files which should be merged first
=> [2892] location status api docs

README.md
The rails-erd gem that we are now using to generate the entity
relationship diagram for the app requires GraphViz to be installed.
Note this in the README
=> Add GraphViz requirement to README

app/controllers/api/v2/accredited_provider_training_providers_controller.rb, app/models/course.rb, app/services/course_search_service.rb, spec/models/course_spec.rb, spec/requests/api/v2/providers/accredited_body_filter_providers_spec.rb, spec/services/course_search_service_spec.rb
We want to filter training providers by what kind of courses they provide, for example, list providers that have fee-funded, physical education courses
Adds `funding_type` and `subject` filters to the accredited body training providers endpoint 
Example request path:
```
"/api/v2/recruitment_cycles/#{recruitment_cycle.year}/providers/#{accredited_provider.provider_code}/training_providers?filter[funding_type]=fee,salary&[subjects]=C6,A2"
```
I suggest that _negative filters_ are tackled in another PR. Possibly we may end up handling client side.
=> [3253] - Filter training providers by subject and funding type

app/controllers/api/v2/providers_controller.rb, spec/requests/api/v2/providers/providers_spec.rb
- https://trello.com/c/xM3j6Ohd/3246-paginate-providers-in-publish-and-api
- Server side pagination has not been implemented of v2 providers endpoint
- This is consumed by publish and is slow
- We implement server side pagination to improve performance
- add pagination to v2 providers endpoint
- hard coded to 10 providers per page
- adds meta count to response
```
curl -H "Authorization: Bearer bats" "http://localhost:3001/api/v2/recruitment_cycles/2020/providers" | ruby -e "require 'json'; puts JSON.parse(gets)['data'].size"
```
- the above should return 10
```
curl -H "Authorization: Bearer bats" "http://localhost:3001/api/v2/recruitment_cycles/2020/providers?page[page]=1" |  ruby -e "require 'json'; puts JSON.parse(gets)['data']"
```
- should return page 1
```
curl -H "Authorization: …
```
=> [3246] paginate v2 providers endpoint

docs/Gemfile, docs/Gemfile.lock
`govuk_tech_docs` gem is pointing to a repository branch, however install of the docs fails. 
Source `govuk_tech_docs` gem via RubyGems
Reinstall as per the docs guidance
=> Source 'govuk_tech_docs' gem via RubyGems

app/models/course.rb, spec/models/course_spec.rb, spec/requests/api/v2/providers/courses/update_sites_spec.rb
- https://trello.com/c/vElWfWcT/3172-prevent-duplicate-site-statuses-being-created-on-course-creation
- duplicate site_statuses were being generated on course creation
- this would occur for unpersisted records
- as hand creating site_statuses
- then calling super which is default activerecord
- default activerecord creates the join on has_many through
- hence dupe joins
- now the handcrafting only happens for persisted records
- non persisted uses default rails behaviour
- checkout branch
- take a note of `SiteStatus.count`
- in publisher create a course
- after creation of course `SiteStatus.count` should increase by the number of sites you selected and not double as it was previously
=> [3172] Fix dupe site_statuses on course create

app/models/course.rb, spec/models/course_spec.rb
- https://trello.com/c/5CqPh7eV/3290-bug-course-still-showing-on-find-even-though-no-vacancies
- Search would return courses that had no vacancies despite user searching for courses with vacancies
- When combining scopes #findable and #with_vacancies
- These would be combined with OR instead of AND
- This would introduce bugs where a course could be return that should
not be because it was unfindable with vacancies AND findable with no
vacancies
- This fixes scopes so activerecord can combine these scopes correctly
=> [3290] Vacancies only consider findable courses

app/controllers/api/v2/allocations_controller.rb, app/policies/allocation_policy.rb, config/routes.rb, spec/policies/allocation_policy_spec.rb, spec/requests/api/v2/allocations_spec.rb
Add an endpoint to the allocations API to allow allocations for an accredited body to be retreived.
Add `GET /api/v2/providers/:accredited_body_code/allocations`
Update the `AllocationPolicy` with a scope and allow admins
This is on top of #1321. There is discussion in the description there about the relationship of allocations with the recruitment cycle. This PR carries on relating through the provider ids (which are recruitment cycle specific). I wonder if it would be useful to associate `Allocation` with recruitment cycle directly?
=> 3277 m add listing to allocations endpoint

app/controllers/api/v2/allocations_controller.rb, app/deserializers/api/v2/deserializable_allocation.rb, app/policies/allocation_policy.rb, spec/policies/allocation_policy_spec.rb, spec/requests/api/v2/allocations_spec.rb
- https://trello.com/c/xZDgo5YV/3298-m-4d-create-allocation-request-action
- Selecting yes/no will now talk to the API and create an allocation
- Allocation will be 42 `number_of_places` if yes
- Allocation will be with 0 `number_of_places` if no
- admins can create allocations otherwise review apps and QA will not work
- add placeholder backfilling mechanism so flows journey from publish will work by hard coding to 42 `number_of_places`
- add deserialiser to handle json api client requests
- I foresee bugs occurring as the create endpoint is not idempotent. It is possible for multiple allocations to exist because of this
- wire up with publish from this PR https://github.com/DFE-Digital/publish-teacher-training/pull/1037
- go thru yes journey
- should end up with allocation with 42 …
=> [3298] Create allocations

app/services/api_service.rb, app/services/query_normalizer_service.rb, spec/services/query_normalizer_service_spec.rb
#1310 will be split into three smaller PR and deployed individually. This is the first of three.
Service to handle normalization of query terms for comparison against
normalised data columns. Currently, this is used for the provider
suggestions on the `Provider` model.
=> [3284] Add QueryNormalizerService 

app/controllers/api/v2/allocations_controller.rb, spec/requests/api/v2/allocations_spec.rb
Currently the AllocationsController index action does not return information about an allocation's relationships (provider and training provider).
- process 'includes' params in order to return provider and accrediting provider relationship info.
=> [3256] - Update AllocationsController#index

Gemfile, Gemfile.lock, app/models/provider.rb, spec/models/provider_spec.rb
The provider suggestions and search are being confounded by the inclusion of unicode characters, incorrect numbers of spaces etc. This introduces a more effective search that can handle that.
^ note sexy apostrophe and extra spaces in the search term being correctly matched 🕺 
* Bundle pg_search gem
* Switch search_by_code_or_name to use a combined scope on
`provider_code` and `provider_name`
Run find locally against this version of the API. Update a provider that has findable courses to 
have a name including a standard apostrophe. Enter the name but substitute a unicode apostrophe. The provider suggestion should now work.
This will need thorough product review on QA when it is merged as we may alter the expected search results. This introduces some fuzziness and partial-ness (😬) to the …
=> Add pg_search to Provider

azure/template.json
When we deploy, the route table added by CIP is removed. It is required to use the Internet Access Service (IAS). This is because our Azure template also configures vnet and subnet, but without route table.
Use a simpler network template which does not try to recreate the network config, but only references the existing.
It was deployed here: https://dev.azure.com/dfe-ssp/Become-A-Teacher/_releaseProgress?_a=release-environment-logs&releaseId=5843&environmentId=23304
And the route table has not been removed: https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/f013afaf-9685-4a48-91ae-155e77aa42fc/resourceGroups/s121d01-core/providers/Microsoft.Network/virtualNetworks/s121d01-core-vn-01/subnets
=> [3216] Remove vnet config from template

spec/requests/api/v2/organisations_spec.rb, spec/serializers/api/v2/serializable_organisation_spec.rb
This spec fails quite regularly as the ordering is flakey within the
JSON. We have moved to not testing the entire JSON response in request
specs as this should be well covered in the serializer specs so removing
that here should make the tests more reliable.
Don't test the whole JSON response in the v2 organisation request spec.
=> Fix flakey organisation spec

app/controllers/api/v2/accredited_provider_training_providers_controller.rb, spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb
- https://trello.com/c/XSJooptJ/3308-m-6a-api-add-negated-subject-filtering-support-to-providers-endpoint
- Original PR name `3308 negate subject provider search`
- ~~Enables searching of training providers that do not offer specified subjects~~
- The original task is no longer required and this PR only contains a refactor
- Refactor `AccreditedProviderTrainingProvidersController` with internal service class
- Results now ordered by `provider_name`
- only change is now results are always sorted `provider_name`
=> 3308 Refactor training provider search

app/controllers/api/v2/notifications_controller.rb, app/policies/user_notification_policy.rb, config/routes.rb, spec/policies/user_notification_policy_spec.rb, spec/requests/api/v2/users/notifications_spec.rb
In order to allow users to opt in and opt out of receiving course update notifications we need to add some new end points to V2.
- Adds index endpoint for user notifications
=> [3318] - V2 API User Notifications index endpoint

azure-pipelines.yml, terraform/backend.tf, terraform/provider.tf, terraform/resources.tf, terraform/terraform_prod.tfvars, terraform/terraform_qa.tfvars, terraform/terraform_staging.tfvars, terraform/variables.tf
Emit an alert from health-check endpoints on any of the services going down.
Add terraform StatusCake alerts directory to the repo.
Example: https://dfe-ssp.visualstudio.com/Become-A-Teacher/_releaseProgress?_a=release-environment-logs&releaseId=6121&environmentId=25474
=> [3243] Add terraform StatusCake alert directory 

app/controllers/api/v2/courses_controller.rb, app/controllers/api/v2/sites_controller.rb, app/policies/provider_policy.rb, spec/requests/api/v2/providers/courses_spec.rb
When an accredited body user tries to list courses for a provider that they are not directly associated with but that does deliver courses on behalf of the accredited body they are getting a 403 response in publish.
Publish currently calls the `ProvidersController#show` endpoint and includes the courses and the `ProviderPolicy#show?` policy does not allow this. Updating that policy will have undesirable side effects and will require complex coupling of with `Course`. So, we're going to switch `Publish` to use the `CourseController#index` endpoint to retrieve these courses. Unfortunately that also uses the `ProviderPolicy#show?` (via an alias) when the courses are scoped by provider. It also disregards any other filter params in that case.
* Don't use `ProviderPolicy` in the …
=> [3364] User getting 403 errors when viewing their training providers on the courses as an accredited body page

app/controllers/reporting_controller.rb, app/services/course_reporting_service.rb, config/routes.rb, spec/requests/reporting_spec.rb, spec/services/course_reporting_service_spec.rb
Vital statistics
Add basic course stats
Subject stats will have dupes as a course can be associated to one or more subjects
http://localhost:3001/reporting
```json
{
"total": {
"all": 17575,
"non_findable": 4626,
"all_findable": 12949
},
"findable_total": {
"open": 9886,
"closed": 3063
},
"provider_type": {
"open": {
"scitt": 1641,
"lead_school": 7257,
"university": 987,
"unknown": 0,
"invalid_value": 0
},
"closed": {
"scitt": 332,
"lead_school": 2637,
"university": 94,
"unknown": 0,
"invalid_value": 0
}
},
"program_type": {
"open": {
"higher_education_programme": 1035,
"school_direct_training_programme": 6213,
"school_direct_salaried_training_programme": 1068,
"scitt_programme": 1493,
"pg_teaching_apprenticeship": 77
},
"closed": {
"higher_education_programme": 101, …
```
=> [3338] Added basic top level course stats

app/controllers/reporting_controller.rb, app/services/provider_reporting_service.rb, spec/requests/reporting_spec.rb, spec/services/provider_reporting_service_spec.rb
vital statistics
Added providers stats
http://localhost:3001/reporting
```json
{
"providers": {
"total": {
"all": 1939,
"non_findable": 850,
"all_findable": 1089
},
"findable_total": {
"open": 1022,
"closed": 67
},
"accredited_body": {
"open": {
"accredited_body": 227,
"not_an_accredited_body": 795
},
"closed": {
"accredited_body": 27,
"not_an_accredited_body": 40
}
},
"provider_type": {
"open": {
"scitt": 138,
"lead_school": 811,
"university": 72,
"unknown": 0,
"invalid_value": 0
},
"closed": {
"scitt": 3,
"lead_school": 64,
"university": 0,
"unknown": 0,
"invalid_value": 0
}
},
"region_code": {
"open": {
"no_region": 0,
"london": 162,
"south_east": 150,
"south_west": 80,
"wales": 0,
"west_midlands": 119,
"east_midlands": 72,
"eastern": 125,
"north_west": 123,
"yorkshire_and_the_humber": …
```
=> [3329] top level stats endpoint providers

app/serializers/api/v2/serializable_provider.rb, spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb, spec/requests/api/v2/providers/providers_show_spec.rb, spec/serializers/api/v2/serializable_provider_spec.rb
- Publish will be displaying users that can access a particular provider. See related PR - https://github.com/DFE-Digital/publish-teacher-training/pull/1094
- We need to return the user association to that we can display the
user's information
- adds user association to Provider serializer
- adds missing test coverage for requesting a provider and including `sites`
=> [3305] - Return user association on provider resource

app/controllers/heartbeat_controller.rb, spec/requests/heartbeat_spec.rb
Meant to fix the Sidekiq healthcheck, but can't currently find evidence of it being broken.
Change `502 bad gateway` to `503 service unavailable`.
Another PR will be made if we can find anything to fix in the Sidekiq healthcheck.
=> [3416] change healthcheck to return service unavailable

app/controllers/api/v2/accredited_provider_training_providers_controller.rb, spec/requests/api/v2/providers/accredited_body_filter_providers_spec.rb, spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb
- https://trello.com/c/Hwg5ZBqT/3422-accredited-bodies-should-be-able-to-request-pe-allocations
- For allocations we need to return accrediting providers if they also have a PR fee funded course
- on accredited provider search if the accredited provider has a course
themselves that meets the criteria the accredited provider is returned
in the results
- previously only training providers would be considered
- Navigate to a provider with their own fee funded PE course eg `2AT`
- go to the index allocations page
- should see yet to request repeat allocation
=> [3422] Provider search can now include self

Rakefile
Annotate gem was removed in a previous PR #1371
=> Don't run annotate in the default rake task

app/models/course.rb, app/models/provider.rb, app/services/course_search_service.rb, spec/models/course_spec.rb, spec/models/provider_spec.rb, spec/requests/api/v3/courses/index_spec.rb, spec/services/course_search_service_spec.rb
- When users search for an accredited body who delivers its own courses _and_ has partners who delivers courses on it's behalf, then the accredited body's courses should be prioritised in the results .
- Scope added to prioritise university courses in results where appropriate.
- There appears to be a modest 30ms decrease in `db_runtime` (avg) as a result of the changes
- Do a provider search for 'University of Warwick' - you can see that its courses are now returned at the beginning of the results, other courses are returned thereafter alphabetically by provider name.
=> [3360] - Prioritise accredited body's own courses in search results

app/services/allocation_importer_service.rb, config/data/itt_allocations_2020_to_2021/missed_physical_education.csv, db/migrate/20200522114747_add_uniq_index_on_allocations.rb, db/schema.rb, spec/services/allocation_importer_service_spec.rb
- https://trello.com/c/x2El42cz/3429-import-additional-allocations
- There were missed allocations that were submitted after the deadline and were not in the published spreadsheet
- Reintroduce allocation import script
- Add missed allocation data for import
- Introduce uniqueness index to prevent duplicate allocations from being created
- Test against most recent db dump
- Run the following in a rails console
- `service = AllocationImporterService.new(path_to_csv: Rails.root.join('config/data/itt_allocations_2020_to_2021/missed_physical_education.csv')); service.execute`
- New or updated allocations should be present
=> [3429] Import missed allocations

README.md, app/controllers/heartbeat_controller.rb, docs/healthcheck_and_ping_endpoints.md, spec/requests/heartbeat_spec.rb
Made a mistake in how queues were processed. 😢 Goes to show that this test is a bit tricky and brittle ... my issue locally was being masked by the fact that I have jobs in the queue that we're no longer processing.
Fix this. Hopefully. Also, add some docs.
=> [3416] fix queues checking

app/controllers/api/v2/providers_controller.rb, app/controllers/api/v3/providers_controller.rb, spec/requests/api/v2/providers/suggest_provider_spec.rb, spec/requests/api/v3/providers/index_spec.rb
On Publish and Find we now want to allow users to run provider searches containing 2 characters. 
NB: Hold fire on merging until front ends are updated
- Changes the provider search query minimum character limit to  1
- Adds missing test coverage
=> [3399] - Allow provider searches with queries containing 2 characters

app/controllers/heartbeat_controller.rb, config/routes.rb, config/settings.yml, spec/requests/heartbeat_spec.rb
Sometimes it's important to be able to see what version of the code is actually running for debugging issues.
Add an endpoint that exposes the git commit SHA at `/sha`.
=> [3462] add /sha endpoint to see the commit SHA in deployed env

app/models/user.rb, app/services/courses/update_notification_service.rb, spec/models/user_spec.rb, spec/requests/api/v2/providers/courses/update_spec.rb, spec/services/courses/update_notification_service_spec.rb
Course updated emails don't appear to be being sent when a course is updated. Turns out we were checking notifiable users using the provider code rather than the accredited body code on the course so what was actually happening is that there would have been emails sent in some cases, just not to the correct users. This wasn't clear as we don't have many subscriptions and may explain why we didn't see this in user research when the same code was used.
* Update the `UserNotificationService` to use the correct provider code when querying the users to be notified
* Remove the `User.notifiable_users` as the `User` model has enough to worry about. Move that logic into the service as it seems like the service that should be concerned with this relationship. This also makes it consistent with the …
=> 3459 Course updated emails not being sent

app/controllers/api/v2/allocations_controller.rb, spec/factories/allocations.rb, spec/requests/api/v2/providers/allocations_spec.rb
- https://trello.com/c/dtbw2raY/3440-stop-filtering-out-providers-from-provider-search-initial-allocation-request
- The frontend needs to to determine what to show the user depending on whether or not an allocation exists
- This change modifies the allocation endpoints so the results can be filtered
- Can now pass training_provider_code to find allocations only
associated with the specified training provider
- allocations#show handles `include` to return associations
```ruby
Allocation.where(recruitment_cycle_year: recruitment_cycle.year)
.where(provider_code: provider.provider_code, training_provider_code: training_provider[:provider_code])
.first
```
- Using the above code in publish given an allocation exists for the training provider it should be returned otherwise should return nil …
=> [3440] Allocations can now be filtered

app/controllers/api/v2/application_controller.rb, app/controllers/api/v2/providers_controller.rb, app/policies/provider_policy.rb, config/routes.rb, spec/controllers/api/v2/providers_controller_spec.rb
- https://trello.com/c/QpRrdwxL/3466-pre-launch-task-make-accredited-bodies-able-to-see-allocation-pages
- We don't want accredited bodies to see training providers under normal circumstances but sometimes we do. This adds another endpoint to allow for this
- This is needed for the allocation work so accredited bodies can access any training provider
- There is also another endpoint for suggestions so allocations autocomplete can search for any provider
- Additional endpoint for provider lookup
- This additional endpoint is identical to the show endpoint
- It uses a different policy
- The policy allows anyone to see any provider
- The additional endpoint was added instead of the policy of the #show
endpoint modified so on the client side a accredited body could not see
a training …
=> [3466] Add extra endpoint to show a provider

app/models/recruitment_cycle.rb, app/services/allocation_reporting_service.rb, app/services/statistic_service.rb, spec/requests/reporting_spec.rb, spec/services/allocation_reporting_service_spec.rb, spec/services/statistic_service_spec.rb
Allocations informations
Added allocations informations to reporting endpoint
http://localhost:3001/reporting
```json
{
"providers": {...},
"courses": {...},
"publish": {...},
"allocation": {
"previous": {
"total": {
"allocations": 433,
"distinct_accredited_bodies": 153,
"distinct_providers": 397,
"number_of_places": 1461
}
},
"current": {
"total": {
"allocations": 0,
"distinct_accredited_bodies": 0,
"distinct_providers": 0,
"number_of_places": 0
}
}
}
}
```
These stats are only as accurate, if it remains the source of truth, as when an `allocation request` is made it will later be confirmed which results in the `number of places` subjected to amendments beyond current boundaries.
=> 3457 s add allocations information to reporting endpoint

app/services/courses/copy_to_provider_service.rb, app/services/providers/copy_to_recruitment_cycle_service.rb, lib/mcb/commands/providers/rollover.rb, spec/mcb_helper.rb, spec/services/courses/copy_to_provider_service_spec.rb, spec/services/providers/copy_to_recruitment_cycle_service_spec.rb
This may seem counter-intuitive, but it seems that our courses aren't all valid
at the current time, for example the "age_range_in_years" is nil on a bunch of
courses, but is validated as being present on new/create. We should fix this,
but for the time being we just need to duplicate the broken-ness.
This change also adds a little extra info when an error is raised to know which
course code was being processed at the time of the error.
When testing rollover locally, we got the error that a course was invalid pretty early on in the process.
Be messy and don't validate a course before saving. It seems that last year's rollover also didn't validate courses, and that the `save!` was added as part of the refactoring later in PR #726.
=> [3417] don't validate courses when rolling over

app/services/user_associations_service/create.rb, app/services/user_associations_service/delete.rb, lib/mcb/editor/grant_access_wizard.rb, lib/mcb/editor/revoke_access_wizard.rb, spec/services/user_associations_service/create_spec.rb, spec/services/user_associations_service/delete_spec.rb
A user's notification preferences are stored with one record (`UserNotification`) per accredited body. If the user is associated with a new accredited body and they have existing preferences stored we need to add a record for the new accredited body with the same preferences.
The opposite process also needs to take place if they are removed from an accredited body.
Update user notifications when user is added or removed to an accredited body.
When user is granted access to a new organisation, they will receive notifications for the new organisation, if they opted in.   
When user's access to an organisation is revoked, they will no longer receive notifications for the organisation that was removed, if they opted in. 
Adding/removing access is done via MCB.
_Note:_
It is also possible to …
=> [3456] Update user notifications when accredited body changes

Dockerfile, azure-pipelines.yml, docker-compose.yml
Teacher training API builds are slow.
Make builds faster by building branch-specific images and ensuring we use them in the docker cache.
A few more details about what's changed:
- We build an image for the `middleman` stage separately and push it up to docker-hub.
- We pull down the `middleman` image before each build and try to cache from it it.
- Don't tag either images, `api` or `middleman`, as `latest` anymore, but instead:
- Tag `api` and `middleman` images with the branch name and push/pull them to dockerhub so we're more likely to be able to reuse them next build.
Makes builds faster.
Oh, and ya, I'll squash this mess back together.
=> XXXX cache api docs for builds

app/models/allocation.rb, spec/models/allocation_spec.rb, spec/policies/allocation_policy_spec.rb
We shouldn't accept `0` allocation requests for initial requests.  "Repeat"
request should still allow "0" places because this is where we don't have date
for the training provider.
Validate number_of_places is not zero if the request type is "initial" 
- try to create new allocations with the following params
provider_code: "B20", provider_id: 15052, **request_type: "initial", number_of_places: 0**
Note: when I tried adding `presence: true` Publish blows up
=> [3287] Add 0 allocation request validations

docs/lib/govuk_tech_docs/open_api/renderer.rb, docs/lib/govuk_tech_docs/open_api/templates/any_of.html.erb
- https://trello.com/c/NnG2a0CU/3408-m-fix-rendering-of-arrays-in-api-docs
- API renderer for tech docs does not handle arrays and `anyOf` schema
- Refactor some of the api renderer code, should now be slightly quicker and memory efficient (not benchmarked)
- Add a new view for `anyOf` schemas to link user to the schema
- Handle arrays by using the first in `items` as a property
- Load up the docs
- `AnyOf` schemas eg `Resource` should link off to relevant schemas
- arrays eg `Sort` should show some documentation for the element
=> 3408 api docs arrays

Gemfile, Gemfile.lock
Code Climate was not reporting our test coverage.
In our Azure jobs we were seeing the following errors:
```
Error: json: cannot unmarshal object into Go struct field input.coverage of type []formatters.NullInt
```
which meant that code climate was no longer receiving our test coverage
score. This is a known issue with code climates test-report and simplecov 0.18.x see codeclimate/test-reporter#418 
- Rollback simplecov until code climate issue is resolved
- coverage is reported in the PR checks
- Copy of recent test coverage submissions to code climate done during this work
=> [3502] Fix Code Climate test coverage

app/controllers/api/v2/accredited_provider_training_providers_controller.rb, app/models/provider.rb, spec/models/provider_spec.rb, spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb
“Courses as accredited body” page is extremely slow, 20-40sec Time to First Byte. This is because the API endpoint returning the list of training providers or course counts are extremely slow.
This is a spike to see what improvements could be made. This is one option for feedback purposes.
- Return the courses as an accredited body count as meta
- NB: this code has not been refactored. No tests yet
- Publish `ProvidersController` would just then need a minor tweak to access the count via the meta object
```
def index
page = (params[:page] || 1).to_i
per_page = 10
@providers = providers.page(page)
@pagy = Pagy.new(count: @providers.meta.count, page: page, items: per_page)
@providers_view = ProvidersView.new(providers: providers)
render "providers/no_providers", status: :forbidden if …
```
=> [3341] - Optimise courses as an accredited body query

app/controllers/api/public/v1/providers_controller.rb, config/routes.rb, spec/api/courses_spec.rb, spec/api/locations_spec.rb, spec/api/providers_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/template.yml
- https://trello.com/c/Wu4CewI6/3356-add-missing-endpoints-to-api-docs
- There were some missing proposed endpoint in the api docs
- Namespace proposed api docs to recruitment cycle
- Add provider endpoints
- Add course show endpoint
- Nest course endpoints within provider
- Add missing api schema specs
- Add CourseListResponse schema
- Add missing url parameter docs
- Fire up the tech docs see the README
- Should see the new endpoints in the docs
=> [3356] Improve api docs

azure-pipelines.yml, docker-compose.yml
I've checked the request made to code climate and as you can see the branch name is no longer `HEAD` and you can see the git commit assigned too.
=> [3502] Fix branch name so its sent to code climate

azure-pipelines.yml
- Run rubocop in CI with multithreading to improve running times by a small amount
- See this build in CI
- Step for rubocop should be slightly faster compared to previous runs
=> run rubocop with mutlithreading

azure-pipelines.yml, bg-jobs/Dockerfile, docker-compose.yml
We need to run background jobs. We also need a generic job runner as it's turning into too much overhead having one container per task (mailer, geosync, etc).
Add a generic background job runner image that's a copy of the existing ones, but with a generic name. A future PR will scrap the existing ones and configure this one to run all the queues.
=> [3517] add bg jobs dockerfile

Gemfile, app/models/provider.rb, spec/factories/users.rb, spec/models/provider_spec.rb
https://trello.com/c/Z9uH4OZB/3532-only-show-kept-users-on-orgusers-list
Add default scope to users to prevent showing discarded
=> [3532] Add default kept scope to user mode

spec/performance/pre_deploy_spec.rb, spec/rails_helper.rb
The performance tests were only intended to run when called explicitly in CI. They shouldn't run with the default test suite as they require an API to be running and are very slow.
Tag the tests `:performance` as intended so as the exclusion in `rails_helper` works.
=> Performance tests don't run by default

app/controllers/api/v2/users_controller.rb, app/models/user.rb, app/serializers/api/v2/serializable_user.rb, spec/models/user_spec.rb, spec/requests/api/v2/access_request_spec.rb, spec/requests/api/v2/users_spec.rb, spec/serializers/api/v2/serializable_user_spec.rb
On Publish a new interruption screen will be shown to users who are associated with an accredited body. 
In order to determine whether the screen should be shown the V2 users#show endpoint now contains a meta object confirming whether the user is associated with an accredited body.
- Another PR will be raised to remove the AASM library and state machine. 
- Custom user endpoints for triggering state will also be removed in a subsequent PR (as all state updated now happen through the update action)
This PR relies on this Publish PR-  https://github.com/DFE-Digital/publish-teacher-training/pull/1178 - please see this for instructions on on how to test changes
=> [3336] - Accredited Body New Feature Interruption Screen

app/controllers/api/v2/providers_controller.rb, spec/controllers/api/v2/providers_controller_spec.rb
- https://trello.com/c/OO8AqZZe/3500-course-creation-accredited-body-search
- Provider suggestions can not be filtered to only show accredited bodies which is needed by publish for autocomplete purposes (or non-js equivalent)
- Provider suggestions can now be filtered to only suggest providers that are accredited bodies
- with valid api key `curl http://localhost:3001/api/v2/providers/suggest_any?filter%5Baccredited_body%5D=true&query=london`
- should only return accredited bodies
=> [3500] Add provider suggestions filtering

app/controllers/api/v2/accredited_provider_training_providers_controller.rb, app/policies/provider_policy.rb, config/routes.rb, spec/controllers/api/v2/accredited_provider_training_providers_controller_spec.rb, spec/policies/provider_policy_spec.rb
- https://trello.com/c/6S5IQpl1/3563-accredited-bodies-cant-see-the-courses-they-accredit
- The Providers#show endpoint is only accessible to users that are associated to the provider via an organisation
- Therefore it is not suitable for displaying of training provider which should be accessible to accredited bodies 
- Add new endpoint
- This endpoint allows accredited body users to see a specific training
provider
- This endpoint is also accessible to admins
- This prevents ProvidersController#show from being overloaded
- ProvidersController#show is used for only showing direct providers the
user has access to
- paired with https://github.com/DFE-Digital/publish-teacher-training/pull/1195
- follow review guidance at https://github.com/DFE-Digital/publish-teacher-training/pull/1195
=> [3563] Add endpoint to show training provider

app/controllers/api/v2/courses_controller.rb, app/mailers/course_withdraw_email_mailer.rb, app/services/notification_service/course_withdrawn.rb, azure/template.json, config/settings.yml, config/settings/test.yml, spec/mailers/course_withdraw_email_mailer_spec.rb, spec/services/notification_service/course_withdrawn_spec.rb
https://trello.com/c/uuwGgy2X/3557-turn-on-accredited-body-notifications-for-when-course-is-withdrawn
Still need to sort out the Notify templates, setting up appropriate environment variables. 
* Add withdraw notification mailer
* Add course withdrawn service
* Add hook for notification when course is withdrawn
=> [3557] Add course withdraw notification

app/models/user.rb, app/serializers/api/v2/serializable_user.rb, spec/models/user_spec.rb, spec/requests/api/v2/access_request_spec.rb, spec/requests/api/v2/users_spec.rb
- Publish needs to know if the user is subscribed to notifications in order to determine whether the 'accredited body new features' interruption screen is shown. See related PR - https://github.com/DFE-Digital/publish-teacher-training/pull/1178
- An attribute is now returned on the user resource indicating whether the user is subscribed to notifications or not.
- State machine has been updated to prevent breakages. Note this is a temporary edit as the user state machine is to be removed in https://github.com/DFE-Digital/teacher-training-api/pull/1427
=> [3336] - Add 'notifications_configured' attribute to UserSerializer

azure/template.json
https://trello.com/c/uuwGgy2X/3557-turn-on-accredited-body-notifications-for-when-course-is-withdrawn
https://github.com/DFE-Digital/teacher-training-api/pull/1430
I've had to do this second PR as the first was merged
Add notify template ID env variable to azure, was not done correctly in previous PR
=> [3557] Add withdraw email template ID to azure

app/controllers/api/v2/allocations_controller.rb, app/models/allocation.rb, app/services/allocations/create.rb, config/settings.yml, spec/models/allocation_spec.rb
- https://trello.com/c/KHA3DiHM/3574-hardcode-allocation-year-for-rollover
- Allocations will be present over different cycles and rollover
- However we want allocations to be created in correct cycle
- Hardcode year to `2020`
- This should be controlled by us and not the client
- This will have to be changed once a year, every year
- Change the current recruitment cycle
- Create a new allocation
- Allocation should be created for the year `2020`
=> [3574] Hardcode allocation year to 2020

app/mailers/course_withdraw_email_mailer.rb, spec/mailers/course_withdraw_email_mailer_spec.rb
https://trello.com/c/uuwGgy2X/3557-turn-on-accredited-body-notifications-for-when-course-is-withdrawn
Turned up in product review, the course url doesn't work for the accredited body seeing as the course is withdraw, so removing it from the notification
Remove the course url stuff from withdrawl notification
=> [3557] Remove course url from withdrawn notification

config/database.yml, config/environments/qa_paas.rb, config/settings/qa_paas.yml
We are evaluating running this app on PAAS.
Eventually we will switch the existing QA, Staging and Production environments but while we are evaluating the PAAS this PAAS only environment will allow us to make configuration changes without disrupting the existing environments.
Add qa_paas environment to allow deployment to the PAAS.
=> [3477] Add qa_paas environment

app/controllers/api/v2/site_statuses_controller.rb, app/mailers/course_vacancies_filled_email_mailer.rb, app/models/site_status.rb, app/services/notification_service/course_vacancies_filled.rb, azure/template.json, config/settings.yml, config/settings/test.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/controllers/api/v2/site_statuses_controller_spec.rb, spec/mailers/course_vacancies_filled_email_mailer_spec.rb, spec/models/site_status_spec.rb, spec/services/notification_service/course_vacancies_filled_spec.rb
When a user indicates that a course is full (has no vacancies) a notification will now be sent to notification subscribers.
- Adds 'course vacancies full' emailer
-  Adds test coverage for 'course withdrawal' notification
=> [3558] - add 'course vacancies full' notification

config/settings.yml
Fix for notify template config setting (spelling error)
Have tested locally and vacancies filled email is sending ok
=> Fix notify template config setting (spelling error)

app/models/course.rb, app/services/notification_service/course_published.rb, app/services/notification_service/course_updated.rb, app/services/notification_service/course_vacancies_filled.rb, app/services/notification_service/course_withdrawn.rb, spec/services/notification_service/course_published_spec.rb, spec/services/notification_service/course_updated_spec.rb, spec/services/notification_service/course_vacancies_filled_spec.rb, spec/services/notification_service/course_withdrawn_spec.rb
- https://trello.com/c/DvAQtnEy/3580-disable-notifications-at-roll-over
- We only want to send notifications for courses in the current cycle. So that during rollover notifications around the next cycle are not sent
- For course notifications add guard to ensure only courses in the current cycle send out notifications 
- With rollover enabled
- Find.a course in the next cycle that has user notifications
- Update the course eg fill the vacancies
- A notification should not be sent
- The same course in the current cycle if updated should send a notification
=> [3580] Notifications only for current cycle

app/models/course.rb, spec/factories/courses.rb, spec/models/course_spec.rb
- https://trello.com/c/4OdjeI1q/3615-make-age-range-a-required-field-for-courses-in-2020-cycle
- We want to collect `age_range_in_years` data which is missing from approximately 14,000 / 15,000 courses
- During rollover this gives us the opportunity to collect this data
- Course publication requires `age_range_in_years`
- Otherwise the course cannot be published
- This is to improve data collection
- Wire up publish to this PR
- login as admin
- Find a course with `age_range_in_years` data missing  e.g.`Course.joins(:provider).where(provider: { recruitment_cycle_id: 2 }, age_range_in_years: nil).first.provider`
- Find the course via the publish web interface
- Attempt to publish the course
- Should be shown a validation message
- Course should not be published
- Set the …
=> [3615] Course publication now requires age range

app/controllers/api/v2/providers_controller.rb, app/deserializers/api/v2/deserializable_provider.rb, app/policies/provider_policy.rb, spec/controllers/api/v2/providers_controller_spec.rb, spec/policies/provider_policy_spec.rb
- https://trello.com/c/KXiJdzYT/3573-m-make-provider-name-editable
- Admin users of publish want to be able to update provider names for convenience
- Thru strong params allow `provider_name` for admins
- This is done thru a convention available via pundit
- Use publish with https://github.com/DFE-Digital/publish-teacher-training/pull/1237
- Login a non-admin
- Navigate to provider contact page to update their details
- Modify the DOM so it sends a new value for `provider[provider_name]`
- Submit
- Provider name should not be update
- Use publish with https://github.com/DFE-Digital/publish-teacher-training/pull/1237
- Login an admin
- Navigate to provider contact page to update their details
- Submit
- Provider name should name should now be updated
- I don't see these low level changes …
=> [3573] Admins can update provider_name

app/models/provider.rb, app/models/site.rb, app/services/providers/copy_to_recruitment_cycle_service.rb, app/services/sites/copy_to_provider_service.rb, spec/models/provider_spec.rb, spec/models/site_spec.rb
Running the rollover `mcb` command has triggered geocoding requests when duplicating sites and providers. This is because the `:needs_geolocation?`  guard is resolving to true. See https://github.com/DFE-Digital/teacher-training-api/blob/master/app/models/site.rb#L34
- Introduce a new virtual boolean attribute on the Site and Provider models so that geocoding can be skipped where required
The `after_commit` geocoding callback is no longer triggered when running the mcb rollover command. 
I think there could be a case for extracting the geocoding logic out of the Site and Provider models which is largely similiar.
=> [3636] - Ensure sites and providers are not geocoded on rollover

config/locales/en.yml, spec/mailers/course_update_email_mailer_spec.rb
```
As an Accredited Body
I need to be able to understand the notification I receive
So that I can act accordingly.
```
When a user updates its study mode attribute then this will now be displayed in the Course Update email as 'study mode'.
=> [3590] - Rename 'attribute_changed' for 'full time or part time' to 'study mode'

azure/template.json
Set the environment variable for the magic link template id.
We have a magic link alternative to signin. The template ID environment variable is not present on Azure.
Set it.
=> [3595] Set magic link template id env var

azure/template.json
This has already been added to the environmentVariables section but
isn't visible on Azure. Trying this...
Also set `SETTINGS__GOVUK_NOTIFY__MAGIC_LINK_EMAIL_TEMPLATE_ID` in the app service app settings section.
=> [3595] Add magic link template id to app settings

app/controllers/api/v2/courses_controller.rb, app/policies/course_policy.rb, app/serializers/api/v2/serializable_course_without_name.rb, config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/policies/course_policy_spec.rb, spec/requests/api/v2/build_new_course_spec.rb, spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb, spec/requests/api/v2/providers/courses/create_spec.rb, spec/requests/api/v2/providers/courses/update_subject_spec.rb
- https://trello.com/c/bKhHARtf/3572-m-make-course-title-editable
- This is the api side on allowing admins to modify course title
- Permitted course parameters moved to policy and depending on whether admin/non-admin returns different fields for mass assignment
- Updating of course now name available in the API and only available to admins
- Added `SerializableCourseWithoutName` to handle existing test cases which simply serialised an entire course and threw it at the api. This can no longer be done for non-admins hence the serialiser was added to remove the `name` field
- Using publish https://github.com/DFE-Digital/publish-teacher-training/pull/1241
- Login as admin
- Find a course
- Change the title of the course
- Course title should now be changed
- Attempting the same API request …
=> [3572] Course titles can be modified by admins

app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
based upon #1356 
Added a `boosted_distance` column where by it can be used as for the ordering
This is to improve university course ranking via distance searches
Added an `expand_university` filter flag when it is not set or set as `false` then it will retain current/old behaviour order via `distance`, when set to true then it will use the new `boosted_distance` for ordering.
~~Added provider type to serialiser~~ move to here https://github.com/DFE-Digital/teacher-training-api/pull/1440
Best to review commit by commit
Best to compare before and after https://github.com/DFE-Digital/find-teacher-training/pull/353
command
```sh
time curl "http://localhost:3002/results?fulltime=false&hasvacancies=true&l=1&lat=54.9827086&lng=-1.6572078&loc=Newcastle+upon+Tyne+NE4+9YH%2C+UK&lq=Newcastle+upon+Ty …
```
=> 3538 l treat university locations as an area rather than a single point in api

app/controllers/api/v2/users_controller.rb, spec/controllers/api/v2/users_controller_spec.rb
- https://trello.com/c/sDVFcGD0/3660-update-session-when-user-accepts-terms
- After the user accepts the terms the client is not able to keep in sync with the API
- Accepting terms return json of the updated use
- This is so publish can keep in sync with the API
- Hit the accept terms endpoint for a user
- Should now return json of the user
=> [3660] Accepting terms returns user json

app/controllers/api/v2/users_controller.rb, app/mailers/email_unrecognised_mailer.rb, app/services/notification_service/unrecognised_email.rb, config/settings.yml, config/settings/test.yml, spec/mailers/email_unrecognised_mailer_spec.rb, spec/requests/api/v2/users/generate_and_send_magic_link_spec.rb, spec/services/notification_service/unrecognised_email_spec.rb
If a user attempts to sign in via magic link but their email address is unknown, then a notification is sent to that email address saying that the are an unknown user.
- Turn magic link on locally on Publish via `development.local.yml'
```
features:
signin_intercept: true
signin_by_email: true
dfe_signin: false
```
- Go to `/signin`
- Sign in via magic link using a made up address (e.g. foo@bar.com)
- API logs should show that an UnrecognisedEmail notification was sent
=> [3359] - Send 'unrecognised email' notification

app/models/course.rb, spec/models/course_spec.rb, spec/requests/api/v2/providers/courses/publish_spec.rb, spec/requests/api/v2/providers/courses/publishable_spec.rb
- https://trello.com/c/97e3BxBu/3653-missing-broken-error-summaries-when-trying-to-publish-a-course-in-rollover
- When publish a course that does not have an enrichment the error message are not very user friendly
- If a course does not have an enrichment we now present back errors as
if the course did have an enrichment
- This gives more meaningful errors to the user
- Rather than the enrichment is missing
- Find or create a course without an enrichment
- Attempt to publish it
- Should see errors as seen in attached screenshot
- All errors should link to relevant error or page at least with the exception for age range which will be fixed in another change
=> [3653] Publish course enrichments validations

spec/api/courses_spec.rb, spec/api/locations_spec.rb, spec/api/providers_spec.rb, swagger/public_v1/api_spec.json
- https://trello.com/c/471nIyfp/3672-s-fix-documentation-of-api-query-parametersfilters-and-page
- When using the open api specification in swagger, requests would not be generated correctly for pagination and filtering
- Change styling of page and filter open api docs
- This fixes the ability to use the the specification in swagger editor
- Remove filtering from providers endpoint as the current filtering is designed to be used on the courses endpoint
- Take the generated open api specification and use the swagger editor at https://editor.swagger.io
- Alternatively use the local rswag ui at http://localhost:3001/api-docs/index.html
- Generate a courses request with filtering and pagination
- Run against local api
- Should get some test results
=> [3672] Tweak page and filter open api docs

docs/lib/govuk_tech_docs/open_api/renderer.rb, docs/lib/govuk_tech_docs/open_api/templates/schema.html.erb
- https://trello.com/c/7VV8EZki/3670-s-display-empty-values-in-examples-in-api-docs
- Empty strings in enumeration in open api docs are not immediately obvious  
- Replace empty bullet points with `<em>empty string</em>`
- Load open api docs
- Find a schema with an enumeration which can include empty strings eg `required_qualifications_english`
- Should not see an empty bullet point
- Should see `empty string` with text italicised
=> 3670 empty string docs

app/controllers/api/v3/application_controller.rb, spec/requests/api/v3/courses/index_spec.rb
- https://trello.com/c/2jQCohxd/3684-add-requestid-to-logging-for-find
- V3 api was not taking the `X-Request-Id` header from the request. Therefore a new `request_id` was being generated and this would not correlate with request ids from Find
- V3 requests store request_id from header
- Checkout this PR
- `curl -H "X-Request-Id: foo" "http://localhost:3001/api/v3/subjects?fields%5Bsubjects%5D=subject_name%2Csubject_code&sort=subject_name"`
- add `binding.pry` after app/controllers/api/v3/application_controller.rb:44
- `request.uuid` should be `foo`
- alternatively if you want to check the logs you will have to enable the tagged logger for the dev environment
=> [3684] Store request id from header for V3 api

app/mailers/course_update_email_mailer.rb, app/models/course.rb, config/locales/en.yml, spec/mailers/course_update_email_mailer_spec.rb
https://trello.com/c/6mxlYteo/3680-m-basic-detail-notification-course-title
- Added `name` (Course name) to the list of update notification attribute
- Toggle course name based on whether the user changed the course name or not.
=> [3680] - Sends notification when course title changes

app/controllers/api/v2/courses_controller.rb, app/mailers/course_sites_update_email_mailer.rb, app/services/notification_service/course_sites_updated.rb, config/settings.yml, config/settings/test.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/mailers/course_sites_update_email_mailer_spec.rb, spec/services/notification_service/course_sites_updated_spec.rb
We want to let subscribed users know when a course's locations have changed.
When a user updates the sites (locations) for a course this will trigger a new notification indicating which sites have changed.
- You will need to have a Notify api key configured locally.
- Run locally against publish, and update the sites for a course. The `sites updated` notification should be sent. 
- View an example notification here - https://www.notifications.service.gov.uk/services/022acc23-c40a-4077-bbd6-fc98b2155534/notification/abf23bd6-4732-4121-bcd4-193f5e0b8ace
=> [3681] - Create sites update notification

app/controllers/api/v2/courses_controller.rb, app/mailers/course_subjects_updated_email_mailer.rb, app/models/user.rb, app/services/notification_service/course_published.rb, app/services/notification_service/course_subjects_updated.rb, app/services/notification_service/course_updated.rb, app/services/notification_service/course_vacancies_filled.rb, app/services/notification_service/course_withdrawn.rb, config/settings.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/mailers/course_subjects_updated_email_mailer_spec.rb, spec/models/user_spec.rb, spec/services/notification_service/course_subjects_updated_spec.rb
When a user updates a courses subjects we want to trigger a new 'Subjects updated' notification
- 'Subjects updated' notification is triggered when the V2 API receives a request to update a course's subjects
- Any number of subjects can be updated
- To test locally you will need to be subscribed to notifications and have a Notify key
- Go to a course that you are subscribed to get course updates for. Edit the courses subjects via 'basic details` tab. Once the update is submitted a subjects updated notification should fire.
- See a real example of the notification on Notify - https://www.notifications.service.gov.uk/services/022acc23-c40a-4077-bbd6-fc98b2155534/notification/1b579e0d-fd6b-4cf9-9806-321cd716c8f1
=> [3679] - Subject change notification

docs/lib/govuk_tech_docs/open_api/templates/responses.html.erb
We were using malformed HTML where the "Responses" section had the same
id as "Responses Example". This meant that the left side nav was highlighting
both entries because their URL was the same.
=> [3753] Responses & Responses eg's produces same id

app/services/course_attribute_formatter_service.rb, app/services/notification_service/course_updated.rb, config/locales/en.yml, spec/services/course_attribute_formatter_service_spec.rb, spec/services/notification_service/course_updated_spec.rb
https://trello.com/c/vDDbpmtB/3682-m-basic-detail-notification-ucas-apply
Multiple emails are now sent. One per attribute being changed. 
- Added a loop to course update attribute changes
- Added locale entry requirement value changes
=> 3682 basic detail notification ucas apply

app/services/course_attribute_formatter_service.rb, spec/services/course_attribute_formatter_service_spec.rb
- A course may have certain attributes (e.g.like 'age_range_in_years) that are nil. In this scenario the `CourseAttributeFormatterService` breaks and the course update notification fails to send
- Populate the notify template with a value regardless ('unknown') so that it does not break.
=> [3716] - CourseAttributeFormatterService - return 'unknown' when value is nil

docs/lib/govuk_tech_docs/open_api/renderer.rb, docs/lib/govuk_tech_docs/open_api/templates/operation.html.erb, docs/lib/govuk_tech_docs/open_api/templates/parameters.html.erb, docs/lib/govuk_tech_docs/open_api/templates/path.html.erb, docs/lib/govuk_tech_docs/open_api/templates/responses.html.erb
I made the HTTP method uppercase and styled as a caption because unlike
Apply's API our URL are longer and so they would automatically wrap to a
new line.
=> [3738] Prettify HTTP method and path headings

app/controllers/api/public/v1/providers_controller.rb, spec/api/providers_spec.rb, spec/requests/api/public/v1/providers/index_spec.rb, swagger/public_v1/api_spec.json
public v1 providers endpoint
Returns collection of providers based on recruitment cycle
Defaults to be sorted alphabetically by provider name (asc)
Added support for sparse fields
Added ability to sort providers via its name from `a-z` or `z-a`
No pagination
=> [3735] Added implementation of providers endpoint

app/controllers/api/public/v1/provider_suggestions_controller.rb, config/routes.rb, spec/api/provider_suggestions_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/template.yml
- https://trello.com/c/6u0XPujL/3750-document-api-endpoint-api-public-v1-provider-suggestions
- Document `/api/public/v1/provider_suggestions`
- Document the provider suggestions endpoint in the new public api docs
- Run the middleman docs, see the new endpoint documentation for provider suggestions
- Discuss whether it's worth making the endpoint snake_case rather than kebab-case to be consistent with other endpoints
=> [3750] Document Provider Suggestions Endpoint

app/controllers/api/public/v1/subject_areas_controller.rb, config/routes.rb, spec/api/subject_areas_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/SubjectAreaAttributes.yml, swagger/public_v1/component_schemas/SubjectAreaRelationships.yml, swagger/public_v1/template.yml
- https://trello.com/c/QJAGE2SD/3748-document-api-endpoint-api-public-v1-subjectareas
- Document `/api/public/v1/subject_areas`
- Document the subject areas endpoint in the new public api docs
- Run the middleman docs, see the new endpoint documentation for subject areas
=> [3748] - Document subject areas

.rubocop.yml, app/models/course.rb, app/serializers/api/public/v1/serializable_course.rb, config/locales/en.yml, spec/factories/course_enrichments.rb, spec/factories/subjects/secondary_subjects.rb, spec/models/course_spec.rb, spec/serializers/api/public/v1/serializable_course_spec.rb
- https://trello.com/c/Igxd218k/3737-mimplement-api-endpoint-api-v3-recruitmentcycles-year-providers-providercode-courses
- First step to implement public/v1 api for courses
- Add `Course` serializer for public/v1 api
- Some additional code to support extra data compared to previous serializers
- Should map with the API docs
=> [3737] Add course serializer for public/v1 api

docs/adr/0004-before-action-variables.md, docs/adr/index.md
- https://trello.com/c/xKBtll4v/3781-adr-for-removal-of-beforeaction-instance-variable-loading
- Raise ADR to swap `before_action` loading of instance variables with lazy loaded memoised private methods
- Read ADR
=> [3781] Add ADR to remove before_action variables

lib/tasks/swaggerize.rake
- Fix the rake task `rswag:specs:swaggerize`
- This fixes the rake task rswag:specs:swaggerize
- We have now move our rswag tests to a non-supported location of
api/docs
- To acheive this we have to override the original rake task
- Run the rake task `rswag:specs:swaggerize`
- Open api spec should be generated correctly without the endpoints missing
=> Override original swaggerize rake task

app/controllers/api/public/v1/courses_controller.rb, app/controllers/api/public/v1/providers/courses_controller.rb, app/serializers/api/public/v1/serializer_service.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb, spec/docs/providers/courses_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml, swagger/public_v1/template.yml
- https://trello.com/b/fXA6ioZN/find-publish-sprint-board
- This starts the implementation of public/v1 api endpoint for provider courses#index
- This PR has missing features such as sorting and filtering and will be added in future PRs
- Implement basic controller endpoint for provider courses
- Sorting is out of scope of this PR
- Filtering is out of scope of this PR
- Included associations is out of scope of this PR
- Fields returned is out of scope of this PR
- Hit the API endpoint, should returns the providers courses
=> [3737] Start public/v1 provider courses endpoint

app/controllers/api/v2/accredited_provider_training_providers_controller.rb, app/controllers/api/v3/courses_controller.rb, app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
- https://trello.com/c/Igxd218k/3737-m-implement-api-endpoint-api-v3-recruitmentcycles-year-providers-providercode-courses
- The CourseSearchService is currently constrained to `findable` courses only
- We want to open up this constraint so the class can also be used to search for non-findable courses too
- This will be required for the public api
- This allows for greater flexbility and does not limit the class to
only return findable courses
- The onus is on the caller to pass correct base scope
- This means this class can now be used to search non-findable courses
too
- v3 api should remain the same. therefore find search functionality should remain the same
- should be able to call CourseSearchService class with a base scope and should return non findable courses too
=> [3737] Change CourseSearchService base scope

README.md, azure/template.json, config/settings.yml
-https://trello.com/c/sZ4woLkJ/3788-remove-govuk-notify-template-ids-into-repository-settings 
There is no reason for us to hide our template ID and use Azure to set
them. We can leave them in our source code so long as we still key the
api key secure then a potential attacker will not be able to use that
template.
=> [3788] Move GOV.UK Notify template id out of azure

lib/tasks/swaggerize.rake
- Fixes build
- Only patch swaggerize rake task if RSpec is loaded
- locally run `RAILS_ENV=staging be rake -T` without this patch should throw error
- locally run `RAILS_ENV=staging be rake -T` with this patch should no longer throw error
=> Only patch swaggerize rake task if RSpec loaded

app/controllers/api/public/v1/providers/courses_controller.rb, app/serializers/api/public/v1/serializable_course.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb
https://trello.com/c/iIyuBytF/3790-add-inclusion-to-public-api-courses-endpoints
* Add belongs_to relationships for course endpoint for accredited bodies, providers, and recruitment cycles
=> [3790] api courses endpoint include

azure/template.json, config/settings.yml, config/settings/test.yml
As we are no longer storing template ids in Azure we should update the app config accordingly
- template id entries removed from `config/settings/test.yml`
- template id entries removed from `template.json` (Azure config)
- `course_vacancies_filled_template_id` removed
=> [3801] - Tidy up Notify template config

app/controllers/api/public/v1/providers/locations_controller.rb, app/serializers/api/public/v1/serializable_location.rb, app/serializers/api/public/v1/serializable_recruitment_cycle.rb, app/serializers/api/public/v1/serializer_service.rb, spec/controllers/api/public/v1/providers/locations_controller_spec.rb, spec/docs/locations_spec.rb, spec/rails_helper.rb, spec/serializers/api/public/v1/serializable_location_spec.rb, spec/support/request_helper.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/LocationRelationships.yml, swagger/public_v1/template.yml
- https://trello.com/c/AZ9Z9cqs/3778-m-implement-includes-to-locations-api-endpoint-api-v3-recruitmentcycles-year-providers-providercode-courses-coursecode-locations
- Add inclusion options to the locations endpoint
- Dependant on this PR: https://github.com/DFE-Digital/teacher-training-api/pull/1513
- Update v1/public documentation for this endpoint to show inclusion options [WIP]
- Introduce a new test helper module https://github.com/DFE-Digital/teacher-training-api/pull/1523/files#diff-d5206992d9c7232aca19cf9ac241420eR3 which allows us to call `json_response` to interrogate the json response instead of multiple `JSON.parse(response.body)` calls in tests.
- Fire off a request for a given provider & course to get a list of that course's locations, passing along some include options. …
=> [3778] Implement inclusion options in locations endpoint

.rubocop.yml, spec/rails_helper.rb, spec/support/request_helpers.rb
- I noticed a lot of duplicated calls to `JSON.parse` for parsing the response body in test files
- Standardise helper method for parsing JSON responses in test files to avoid duplicating calls. 
- Instead of `JSON.parse` you would just do `json_response` which would also memoize the results.
- See the new helper method
=> Clean up duplicate JSON.parse calls into re-usable helper

azure/template.json
The change is to accommodate both api and ap2 custom domain requires for all environment.
Ammending arm template to support multiple custom domains
- [x ] Attach to Trello card
=> modified azure/template.json accommodate multiple custom-domain (api\api2)

lib/tasks/code_climate.rake
During a recent dependabot bump of simplecov(https://github.com/DFE-Digital/teacher-training-api/pull/1529), all the azure tasks passed and it was only when we inspected the codeclimate task when we noticed the task had failed.
This PR is to ensure that if the task fails then an exception should be raised.
I've cherry picked a commit from the dependabot failing PR to show that the task now fails.
Once this PR has been approved we can removed the cherry picked commit 
and push up the changes. The task should pass once the commit is removed.
=> Raise exception when Code Climate azure task fails

docs/api.md, docs/config/tech-docs.yml, docs/performance-testing.md, docs/source/specifications.html.md.erb, swagger/public_v1/api_spec.json, swagger/public_v1/template.yml
In the api docs, we referred to the endpoint as `api2` instead we should
be referring to `api`.
=> [3752] Use `api` instead `api2`

app/controllers/api/public/v1/providers/courses_controller.rb, app/serializers/api/public/v1/serializable_recruitment_cycle.rb, app/serializers/api/public/v1/serializer_service.rb, config/routes.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb, spec/docs/providers/courses_spec.rb, spec/serializers/api/public/v1/serializable_recruitment_cycle_spec.rb
- https://trello.com/c/ekPzeeJr/3742-s-implement-api-endpoint-api-v3-recruitmentcycles-year-providers-providercode-courses-coursecode
- Adds public/v1 api endpoint for providers courses#show
- Add `RecruitmentCycle` serialiser
- Add endpoint for courses on providers for public API
- Should be able to fetch a course via endpoint
- Should be able to specify includes for endpoint and they should be returned in the response
=> [3742] Implement api endpoint for provider courses#show

app/models/course.rb, app/models/site_status.rb, app/services/provider_reporting_service.rb, spec/models/course_spec.rb, spec/models/site_status_spec.rb, spec/requests/api/v2/providers/courses/update_study_mode_spec.rb
https://trello.com/c/ejcChJPq/3811-change-with-has-vacancies-to-only-include-findable-courses
* Add findable scoping to the with_vacancies scope for courses
=> [3811] Add findable to with_vacancies scope for courses

app/controllers/api/public/v1/courses_controller.rb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/docs/courses_spec.rb, swagger/public_v1/api_spec.json
- https://trello.com/c/VD20nCHv/3789-implement-api-endpoint-api-public-v1-recruitmentcycles-year-courses
- Add `recruitment_cycle/:recruitment_cycle_year/courses` endpoint
- Update v1/public documentation for this endpoint
- Fire off a request for a given recruitment_cycle year to get a list of that cycle's courses. Here is an example request you can use (providing you have the sanitised data available):
`curl --location --request GET 'localhost:3001/api/public/v1/recruitment_cycles/2020/courses?include=provider,recruitment_cycle&page[page]=1&page[per_page]=10' \
--header 'Content-Type: application/json'`
- Assert the list of courses are returned correctly for that year. You can compare with the results from a rails console
- Assert you can pass paginate the results
=> [3789] - Create endpoint for courses based on recruitment cycle

app/controllers/api/public/v1/courses_controller.rb, spec/controllers/api/public/v1/courses_controller_spec.rb
- https://trello.com/c/u8s9har0/3805-s-linked-to-3789-add-sorting-to-api-public-v1-recruitmentcycles-year-courses
https://trello.com/c/t0UwzFDt/3806-s-linked-to-3789-add-filtering-to-api-public-v1-recruitmentcycles-year-courses
- Dependent on this PR https://github.com/DFE-Digital/teacher-training-api/pull/1534
- Implements sorting/filtering via the CourseSearchService in `/api/public/v1/:recruitment_cycle_year/courses`
-  Fire off the example request below and add your sorting and filtering options in the request.
- Assert the courses returned match provided sorting/filtering params
CURL:
```
curl --location --request GET 'localhost:3001/api/public/v1/recruitment_cycles/2020/courses?sort=name,provider.provider_name&filter[funding_type]=salary' \
--header 'Content-Type: application/json' …
```
=> [3805] - Implement sorting and filtering for public courses endpoint

docs/lib/govuk_tech_docs/open_api/renderer.rb, docs/lib/govuk_tech_docs/open_api/templates/curl_examples.html.erb, docs/lib/govuk_tech_docs/open_api/templates/operation.html.erb, spec/docs/courses_spec.rb, spec/docs/provider_suggestions_spec.rb, spec/docs/providers/courses/locations_spec.rb, spec/docs/providers/courses_spec.rb, spec/docs/providers_spec.rb, spec/docs/subject_areas_spec.rb, spec/docs/subjects_spec.rb, spec/swagger_helper.rb, swagger/public_v1/api_spec.json
- https://trello.com/c/7jVzT0Uk/3739-add-curl-examples-for-api-requests
- Add curl request examples to api docs so docs can better understand how to use endpoints
- Monkey patch `open_api-rswag-specs` gem to extend the DSL allowing `curl_example` to be used
- `curl_example` can now be used in rspec DSL with a given `description` and curl `command`
- `curl_example` adds to the generated open api spec under the key of `x-curl-examples` which seems to be permitted by https://swagger.io/docs/specification/openapi-extensions/
- Updated api docs so it pulls in the curl examples from the generated open api spec
- Added template to deal with these examples, see screenshots below
- Pull down this branch
- Fire up the tech docs
- Ensure docs show example curl commands
=> [3739] curl examples in tech docs

azure/template.json
SETTINGS__SKYLIGHT__AUTHENTICATION env variable added to arm template (./azure/template.json)
In order to allow the Skylight integration, SETTINGS__SKYLIGHT__AUTHENTICATION has been added as parameter to the arm template.
We just need to add set the API key to the env var SETTINGS__SKYLIGHT__AUTHENTICATION
=> SKYLIGHT variable to arm template

app/serializers/api/public/v1/serializable_course.rb, spec/docs/providers_spec.rb, spec/serializers/api/public/v1/serializable_course_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml
Including this data forces the endpoint to include `recruitment_cycles` and `provider` into the SQL query. Instead of doing this we should allow the client to include the `recruitment_cycle` and `provider` if they need to get this data.
- https://trello.com/c/c1VBUUXP/3810-s-remove-providercode-from-the-public-apis-courses-endpoint
- https://trello.com/c/JaOlx4mc/3807-s-remove-recruitmentcycleyear-from-the-public-apis-courses-endpoint
- Remove from API v1 courses endpoint documentation.
- Remove from API v1 courses serialiser.
- Remove from API v1 courses endpoint tests.
- Fire up the public api docs locally and assert the the `recruitment_cycle_year` and `provider_code` has been removed from the Courses OpenAPI schema
- Use the curl request below to assert the `recruitment_cycle_year` …
=> [3810] and [3807] Remove recruitment_cycle_year and provider_code

app/controllers/api/v2/courses_controller.rb, spec/requests/api/v2/build_new_course_spec.rb, spec/requests/api/v2/providers/courses_spec.rb
Removes the PE subject from subject list for non admins as providers require permission to recruit for this course. It is not visible as a subject on the add new course flow.
Remove the PE subject from subject list for non admins.
=> [3820] remove PE from edit subjects list for non admins

app/controllers/api/public/v1/courses_controller.rb, config/routes.rb, spec/controllers/api/public/v1/courses_controller_spec.rb
- https://trello.com/c/bqY8jqRL/54-add-api-endpoint-api-public-v1-courses
- This is the actual courses endpoint that is used by Find and Apply, it defaults to the current recruitment cycle when retrieving courses, and is nearly identical to `/api/public/v1/recruitment_cycles/:year/courses`
- Implement `api/public/v1/courses`
- Use curl command below to assert courses for current cycle are returned when no cycle is provided in the request
Curl:
```
curl --location --request GET 'localhost:3001/api/public/v1/courses?include=provider,recruitment_cycle&page[page]=1&page[per_page]=3' \
--header 'Content-Type: application/json'
```
=> [54] - Implement api/public/v1/courses

terraform/resources.tf, terraform/terraform_prod.tfvars, terraform/terraform_qa.tfvars, terraform/terraform_staging.tfvars, terraform/variables.tf
Add terraform code and configuration to create a
StatusCake check to monitor the /ping every minute
and let us know immediately if the site is down
Figure out what is causing it to return false, fix it.
configure statuscake via terraform to /ping instead of healthCheck.
- [x ] Make sure all information from the Trello card is in here
- [x ] Attach to Trello card
- [ x] Rebased master
- [ x] Cleaned commit history
- [ x] Tested by running locally
=> Monitor /ping via statusCake

app/services/courses/validate_custom_age_range_service.rb, spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb, spec/services/courses/validate_custom_age_range_service_spec.rb
The age range validation error message was incorrectly displaying underscores. 
The underscores no longer appear.
- Login to Publish 
- Create a new course 
- On the age range page select 'another age range'
- Enter an invalid range such as 0 to 50
- Click submit
=> [88] Age range validation error message no longer display underscores

app/services/rollover_reporting_service.rb, app/services/statistic_service.rb, spec/requests/api/v2/recruitment_cycle_spec.rb, spec/requests/reporting_spec.rb, spec/services/rollover_reporting_service_spec.rb, spec/services/statistic_service_spec.rb
* https://trello.com/c/3C81CAYu/130-service-status-dashboard-rollover-data
Rollover data is needed for the new rollover tab on the performance dashboard as per the prototype. As a result, data needs to be added to the reporting endpoint on the API.
At the /reporting endpoint
* https://publish-dashboard-prototype.herokuapp.com/with-tables#rollover  
N.B There's been a copy change to new courses 'published' instead of created.
=> [130] service status dashboard rollover data

spec/requests/api/v2/providers/courses_spec.rb
We are currently in a weird state between closing the current_recruitment_cycle
and opening up the next_recruitment cycle. This caused a problem with
one test failing when it tried to save a findable open course. It
was failing because the tests were setting the start date and the
application_from_date as today (using a date outside the
current current_recruitment_cycle) instead of using the date set
by the factories.
=> Fix failing spec relating to rollover

config/settings/production.yml, config/settings/qa.yml
To test it's functioning before we ask skylight.io to enable our OSS account.
We're trying to sort out Skylight and would like to ask them to enable our OSS account. However, we'd like to demonstrate that we have it working in qa first.
Enable skylight in qa and disable it in production (since our prod receives too many requests for the current free tier anyway).
=> [177] enable skylight in qa and disable in prod

config/routes.rb, config/settings.yml, spec/config/settings_spec.rb, spec/controllers/api/public/v1/providers/courses/locations_controller_spec.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb, spec/controllers/api/public/v1/providers/locations_controller_spec.rb, spec/docs/providers/courses/locations_spec.rb, spec/docs/providers/locations_spec.rb, spec/models/recruitment_cycle_spec.rb, spec/requests/api/v2/allocations_spec.rb, spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb, spec/requests/api/v2/providers/allocations_spec.rb, spec/requests/api/v2/providers/courses_spec.rb, spec/requests/api/v3/providers/suggest_provider_spec.rb, spec/serializers/api/public/v1/serializable_course_spec.rb, spec/services/allocations/create_spec.rb
Rollover
Rollovered
Best to view by commits
Config change cause some broken tests due to hardcoring.
As well as the ethereal nature of recruitment cycle vs allocation year over allocation
=> 0209 update settings to complete rollover

app/services/rollover_reporting_service.rb, spec/services/rollover_reporting_service_spec.rb
There was an error in Publish performance dashboard where the page failed
to load because the next recruitment cycle is not created until we do
rollover again.
We decided that this should really be handled the api and instead of
attempting to count data that doesn't exist we decided that the guard
would instead return a default data structure with zero out figures.
We tested this locally and this worked with publish because the rollover
tab is hidden from the user until the next cycle is created and we
are in rollover state.
Co-authored-by: SamJamCul <samuel.culley@digital.education.gov.uk>
Co-authored-by: Jonathan Filar <58793682+JonF1@users.noreply.github.com>
=> [239] Fix rollover reporting information

azure/template.json
Change dbServerCpuCores from type string to int
Change dbServerCpuCores from type string to int
=> Change dbServerCpuCores from string to int

app/services/subjects/financial_incentive_creator_service.rb, app/services/subjects/financial_incentive_set_subject_knowledge_enhancement_course_available_service.rb, db/migrate/20191024143538_add_financial_incentive_to_subjects.rb, db/migrate/20200115141035_add_subject_knowledge_enhancement_available_to_financial_incentive.rb, db/migrate/20201005132433_remove_all_financial_incentive_records.rb, db/seeds.rb, spec/services/subjects/financial_incentive_creator_service_spec.rb, spec/services/subjects/financial_incentive_set_subject_knowledge_enhancement_course_available_service_spec.rb, spec/support/reference_data.rb
2020 financial incentives
Amended 2020 financial incentives
Retained and move it to its own chain
Nothing breaks, prep work before introducing 2021 financial incentives
```ruby
Subjects::FinancialIncentiveCreatorService.new().execute
Subjects::FinancialIncentiveSetSubjectKnowledgeEnhancementCourseAvailableService.new().execute
```
```ruby
whatever = year
Subjects::FinancialIncentiveCreatorService.new(year: whatever).execute
Subjects::FinancialIncentiveSetSubjectKnowledgeEnhancementCourseAvailableService.new(year: whatever).execute
```
```ruby
FinancialIncentiveCreatorService
FinancialIncentiveSetSubjectKnowledgeEnhancementCourseAvailableService
```
Retained the above two services with the ability to select any other year based financial incentives
=> [0254] Amended 2020 financial incentives

.gitignore, app/models/course.rb, spec/factories/courses.rb, spec/models/course_spec.rb, spec/requests/api/v3/courses/index_spec.rb
_Apply_ trello card: https://trello.com/c/LvY0EtlQ/2332-bug-salaried-courses-filter 
Slack thread: https://ukgovernmentdfe.slack.com/archives/CQA64BETU/p1602522466230000
London Metropolitan University is an accredited body for some courses. When a user searches by provider ('London Metropolitan University') and then filters the results by 'courses with salary' then any courses that are apprenticeships are not being returned.
Find considers salaried courses to include apprenticeships.
https://github.com/DFE-Digital/find-teacher-training/blob/master/app/decorators/course_decorator.rb#L78
Return apprenticeship courses when calling the `with_salary` scope on the Course model
=> Update 'with_salary' scope

app/models/provider.rb, app/serializers/api/v2/serializable_provider.rb, spec/models/provider_spec.rb
This method used to branch between the contact info on the `Provider` 
itself and contact info from an enrichment if one existed.
It no longer does that so is uneeded now as the fields exist on the 
Provider.
* Remove `Provider#external_contact_info`
* Serialize the fields directly in `V2:SerializableProvider`
=> Remove unused external contact info

Dockerfile, lib/tasks/migrate_swallowing_concurrent_migration_exceptions.rake
We often get concurrent migration errors when the multiple instances we
deploy to all try to migrate the DB.
Ignore these errors.
[The Apply team have successfully used this approach.](https://github.com/DFE-Digital/apply-for-teacher-training/pull/1058)
=> Ignore ConcurrentMigration errors

azure/template.json
Add nested arm template for App Service Plan metric alert. This allows alert to be sent, when certain threshold is reached e.g. CPU utilisation reaches over 80%
Add nested arm template for App Service Plan metric alert
=> Add nested Arm template for App service plan metric

app/controllers/api/v3/providers_controller.rb
https://trello.com/c/wlaJ1u1D/284-add-query-includes-on-the-v3-providersindex-endpoint
* Include recruitment cycle when using v3 providers_index, helps with searching through large numbers of results.
=> 284 add query includes on the v3 providersindex endpoint

app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
Part of work to improve performance of the V3 endpoints.
Include relationships in the course query in `v3::CoursesController#index`
The CourseSearchService handles this query. This commit adds includes to the outer query scope within the service. This reduces the N+1 issues but doesn't relate to the includes parameters accepted at the controller. This endpoint is used by Find so we probably don't need that kind of flexibility.
The performance improvement we'll get in production is difficult to gauge as we don't have parity on the QA environment but locally there is a significant improvement and query definitely looks better in Skylight. I'll get some better figures from Kibana once it's deployed.
Before:
Local: 2020-10-19 16:44:33.995788 I [27181:puma threadpool 002] (1.447s) …
=> [252] Add includes for course index

config/initializers/semantic_logger.rb
Turns out this approach was not compatible with the standard way of logging and
can result in breaking the indexing for the 'duration' field, breaking
aggregation and other operations reliant on the 'duration' field. The correct
approach is to leave 'duration_ms', fix any discrepencies in the logit filters
to ensure that it's indexed as a number, and then use 'duration_ms' for
aggregation.
=> [342] revert duration/duration_ms formatting for logstash

app/services/generate_and_send_magic_link_service.rb, app/services/notification_service/course_published.rb, app/services/notification_service/course_sites_updated.rb, app/services/notification_service/course_subjects_updated.rb, app/services/notification_service/course_updated.rb, app/services/notification_service/course_vacancies_updated.rb, app/services/notification_service/course_withdrawn.rb, app/services/send_welcome_email_service.rb, config/sidekiq.yml, spec/requests/api/v2/sessions/create_by_magic_spec.rb, spec/services/generate_and_send_magic_link_service_spec.rb, spec/services/notification_service/course_published_spec.rb, spec/services/notification_service/course_sites_updated_spec.rb, spec/services/notification_service/course_subjects_updated_spec.rb, spec/services/notification_service/course_updated_spec.rb, spec/services/notification_service/course_vacancies_updated_spec.rb, spec/services/notification_service/course_withdrawn_spec.rb, spec/services/send_welcome_email_service_spec.rb
The default mailer queue for Rails is ['mailers' not 'mailer'](https://github.com/rails/rails/blob/ced687fe710b2f3d6cf0d0e978bdb531357299e4/actionmailer/lib/action_mailer/delivery_job.rb#L7). We should use that instead of customising the queue every time we send a mail.
* Remove all of the `queue: mailer` arguments
* Set the queue name to `mailers` in sidekiq.yml
* Leave the old `mailer` queue in sidekiq.yml for now to let that queue drain. I'll remove that in a subsequent PR.
Run sidekiq locally and then `WelcomeEmailMailer.send_welcome_email(first_name: "Dave", email: <your email>).deliver_async`. `Sidekiq::Queue.all.map(&:size)` should all be 0. I'll check this again on QA, staging, production when it's deployed.
=> [203] Mailer queue is 'mailers'

azure/template.json
see https://azure.github.io/AppService/2020/10/15/Docker-Hub-authenticated-pulls-on-App-Service.html
Configure App Service and background container to authenticate with DockerHub to over come rate limits.
Set in Azure Release pipelines. (done for QA)
```
-dockerRegistryUsername $(dockerRegistryUsername) -dockerRegistryPassword $(dockerRegistryPassword)
```
https://trello.com/c/qG7Lio3h/365-pipeline-and-arm-template-changes-to-include-dockerhub-credentials-to-overcome-rate-limit
Tested in Find, Apply
=> Authenticate with DockerHub registry

app/controllers/api/public/v1/application_controller.rb, swagger/public_v1/component_schemas/Pagination.yml
https://trello.com/c/JrRxAcy7/389-perpage-query-param-doesnt-do-anything-on-providersindex
Increase max_per_page to 500 as suggested by @dankmitchell
=> [389] Bump max_per_page value to 500

app/models/course.rb, app/models/course_enrichment.rb, app/serializers/api/v2/serializable_course.rb, app/services/courses/copy_to_provider_service.rb, db/migrate/20191007125535_mark_withdrawn_courses_as_withdrawn.rb, spec/models/course_enrichment_spec.rb, spec/requests/api/v2/providers/courses/update_spec.rb, spec/serializers/api/v2/serializable_course_spec.rb
When users update a course, the changes would sometimes not show up in preview mode. This was because `API::V2::SerializableCourse.enrichment_attribute` didn't explicitly request for the latest course enrichment record (ordered by created_at). Using `last()` on its own doesn't guarantee the order we want.
With regards to performance, since the same query is executed multiple times within the same action, ActiveRecord will cache the query `@object.enrichments.most_recent&.first&.public_send(enrichment_name)`, helping us to avoid the N + 1 problem.
Use an ordered scope instead of calling `last()` to fetch the latest course enrichment record.
Introducing this fix also caused other tests to fail as they depended on `API::V2::SerializableCourse.enrichment_attribute` using the `last()` …
=> [372] Fix course enrichment bug

app/models/course.rb, spec/models/course_spec.rb
This makes ordering of identically named courses deterministic. Without including the course code we get bugs in paging for identically named courses. This is quite common as the course is often named with the subject.
When ordering canonically (ie provider name and course name) also include the `course_code`.
Visit:
https://www.find-postgraduate-teacher-training.service.gov.uk/results?fulltime=false&hasvacancies=false&l=3&parttime=false&qualifications%5B%5D=QtsOnly&qualifications%5B%5D=PgdePgceWithQts&qualifications%5B%5D=Other&query=CTSN+-+Cambridge+Teaching+Schools+Network&senCourses=false
There are three computing courses towards the bottom of page one. Click into page two and one of the courses "Computing (28B8)" re-appears at the top of page two. There is another computing course …
=> [320] Include course_code in canonical order

config/sidekiq.yml
We were using this queue for mailer jobs but it isn't default so we changed it in a83a0a8.
This removes the old queue which should now be empty.
=> [203] Remove 'mailer' sidekiq queue

.github/workflows/build.yml, .github/workflows/deploy.yml
Split workflows to make it easy to reuse the deploy workflow.
next steps: update `tf 0.13.x` 
Split build and deploy workflows.
Use latest docker/actions.
=> Split Build & Deploy GitHub Actions workflows

.github/workflows/deploy.yml, .gitignore, terraform/variables.tf, terraform/workspace_variables/production.tfvars, terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/staging.tfvars
Make application secrets easier to manage in GitHub actions / terraform,
Read application secrets from a yml file.
base64 encoded yaml file is stored as secret in GitHub Secrets.
=> Read application secrets from yaml file in terraform

terraform/modules/paas/data.tf, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/production.tfvars, terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/staging.tfvars
Adds support for `{env}.api.publish-teacher-training-courses.service.gov.uk` as custom route for PaaS web app.
=> Configure api.publish-teacher-training-courses.service.gov.uk custom domain for PaaS app

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/smoke-test.yml
Trigger smoke tests
Wait for smoke tests to complete and then trigger deployment to next environment.
=> Trigger smoke tests after deployment

.github/workflows/build.yml, Dockerfile, app/controllers/heartbeat_controller.rb, azure-pipelines.yml, config/initializers/logstash.rb, config/initializers/raven.rb, config/settings.yml, spec/requests/heartbeat_spec.rb
Set COMMIT_SHA as docker build argument
Stop writing to and reading COMMIT_SHA to a file.
Set COMMIT_SHA as build arg to docker build
COMMIT_SHA is prefixed with `paas-` in the app hosted in PaaS for identification while we are running on two platforms.
=> Read COMMIT_SHA from ENV hash

app/controllers/api/public/v1/application_controller.rb, spec/controllers/api/public/v1/courses_controller_spec.rb
[Our documentation](https://api.qa.publish-teacher-training-courses.service.gov.uk/api-reference.html#recruitment_cycles-year-courses-get-parameters) defines pagination params as:
`page: { page: <whatevs>, per_page: <whatevs> }`
In `ApplicationController` we don't handle this and expect the `page` and `per_page` to be in the root of the params.
Handle both cases to behave as documented but not break any clients that have already worked around.
=> [506] Pagination params are nested

app/serializers/api/v3/serializable_course.rb, app/serializers/api/v3/serializable_provider.rb, spec/requests/api/v3/providers/courses/index_spec.rb, spec/requests/api/v3/providers/courses/show_spec.rb, spec/requests/api/v3/providers/suggest_provider_spec.rb, spec/serializers/api/v3/serializable_course_spec.rb, spec/serializers/api/v3/serializable_provider_spec.rb
Apply needs some additional attributes exposed on the V3 API for research/analysis purposes. 
- Expose a providers lat/long
- Expose the courses program_type (so we know if it's a `scitt_programme`)
https://trello.com/c/YgubEbfX/2577-dev-use-the-v3-api-to-populate-the-latitude-and-longitude-for-providers
https://trello.com/c/yeZRKLYE/2530-dev-locations-persona-data
=> Expose additional attributes on the V3 API

app/serializers/api/public/v1/serializable_provider.rb, spec/controllers/api/public/v1/providers_controller_spec.rb, spec/serializers/api/public/v1/serializable_provider_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/ProviderAttributes.yml
We're now using the public API so I've close the other PR, added lat/long here and updated the docs accordingly.
- Add lat & long to the provider serialiser
- Update tests
Are there some docs that need updating somewhere @dankmitchell?
=> Add lat long for provider to the public api

app/controllers/api/public/v1/subject_areas_controller.rb, app/serializers/api/public/v1/serializable_subject_area.rb, app/serializers/api/public/v1/serializer_service.rb, spec/controllers/api/public/v1/subject_areas_controller_spec.rb, spec/docs/subject_areas_spec.rb, spec/serializers/api/public/v1/serializable_subject_area_spec.rb, swagger/public_v1/api_spec.json
- https://trello.com/c/6Kr40mh9/633-s-implement-public-v1-subject-areas
- Replace hard coded response with real code!
Fire the following curl command in your shell locally (after running the server):
```sh
curl --location --request GET 'localhost:3001/api/public/v1/subject_areas?include=subjects' \
--header 'Content-Type: application/json'
```
=> [633] Implement api/public/v1/subject_areas

app/serializers/api/public/v1/serializable_provider.rb, spec/controllers/api/public/v1/providers_controller_spec.rb, spec/serializers/api/public/v1/serializable_provider_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/ProviderAttributes.yml
In order to move Find over to the Public API, we need to expose additional attributes on the Public API.
- Expose a providers phone number and email address on the public API 
- Results count in the meta options
Does the course count need to be added to the swagger documentation
=> Expose the required attributes on the v1 public api, in order to move find over

app/controllers/api/public/v1/courses_controller.rb, app/serializers/api/public/v1/serializable_provider.rb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/controllers/api/public/v1/providers_controller_spec.rb
- We accidentally added the Provider courses count from the v2 API in https://github.com/DFE-Digital/teacher-training-api/pull/1713 (soz)
- What we actually want to do is add the _courses_ count to the meta object when the Public API receives course search queries (which is currently the behaviour in v3)
- Remove Provider courses count from the Public API
- Return the (search) courses count in the meta object from the Courses Controller. This matches the behaviour in the v3 API.
https://trello.com/c/e5NdFola/2829-dev-expose-required-attributes-on-the-v1-public-api
=> [2829] - Add courses count to Public API

app/services/course_search_service.rb, spec/services/course_search_service_spec.rb, swagger/public_v1/component_schemas/Filter.yml
The Public API currently returns 'findable' and 'non-findable' courses.
In the V3 API only 'findable' courses are returned.
It has been agreed that Public API clients now need to add a 'findable' filter param to their requests in order to fetch 'findable' courses.
- Add findable scope to CourseSearchService
- Update v3 CoursesController to merge a 'findable' filter param into filter params before passing courses to the CourseSearchService
- Update 'findable' description in docs
https://trello.com/c/S2m1uZtm/2849-add-findable-filter-to-teacher-training-public-api
=> [2849] - Add findable filter to Public API

swagger/public_v1/api_spec.json
Some changes to the Public API were made but we did not regenerate the Swagger docs
- Regenerate Swagger docs (`bundle exec rake rswag:specs:swaggerize`)
https://trello.com/c/S2m1uZtm/2849-add-findable-filter-to-teacher-training-public-api
=> Regenerate Swagger dogs to make latest changes available

docs/healthcheck_and_ping_endpoints.md, spec/smoke/api/v1/courses_spec.rb, spec/smoke/api/v1/healthcheck_spec.rb
https://trello.com/c/tcSBRSoL/711-m-healthcheck-smoke-test
https://trello.com/c/2EUGHq7k/713-m-courses-endpoint-smoke-tests
- Smoke test to check V1 /healthcheck endpoint returns HTTP status of 200, json and expected shape
- Smoke test to check V1 /courses endpoint returns HTTP status of 200
As per the instructions in https://github.com/DFE-Digital/teacher-training-api/pull/1725
=> [711] Smoke test for healthcheck and courses index routes

.github/workflows/smoke-test.yml, spec/smoke/api/v1/providers_spec.rb, spec/spec_helper.rb, spec/spec_helper_smoke.rb
https://trello.com/c/uqDY2T7t/712-m-providers-endpoint-smoke-tests
- Modify smoke test Github action to dynamically update `Gemfile` so it can use `rspec` and `httparty` in any environment
- New `spec_helper_smoke.rb`
- Smoke test to check V1 providers endpoint returns HTTP status of 200
- Copy and paste the following into the existing `Gemfile` and run `bundle`:
```
gem "httparty"
gem "rspec"
```
- run `bundle exec rspec spec/spoke` - the test should pass
- run `RAILS_ENV=qa bundle exec rspec spec/spoke` - the test should pass
- run `RAILS_ENV=staging bundle exec rspec spec/spoke` - the test should pass
- run `RAILS_ENV=production bundle exec rspec spec/spoke` - the test should pass
=> [712] V1 public API smoke tests

spec/docs/provider_suggestions_spec.rb, spec/docs/providers/courses/locations_spec.rb, spec/docs/providers/courses_spec.rb, spec/docs/providers/locations_spec.rb, spec/docs/providers_spec.rb, spec/docs/subject_areas_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseRelationships.yml, swagger/public_v1/component_schemas/LocationRelationships.yml, swagger/public_v1/component_schemas/ProviderRelationships.yml, swagger/public_v1/component_schemas/RecruitmentCycleAttributes.yml, swagger/public_v1/component_schemas/SubjectAttributes.yml, swagger/public_v1/template.yml
- https://trello.com/c/Hpj3nXtX/755-m-refactor-include-schema-definition-setup
- Refactors some of the documented public endpoint examples to correctly show their relationships/include options
- Previously, any endpoint with an optional include query parameter would return a random `Resource` defined in the swagger template, this change makes it more explicit what to render in that file.
- Fire up the API docs locally
- Assert any endpoint with optional includes shows the correct structure in the response example
=> [755] Clean up include examples for public api end points

Dockerfile
alpine has released version 3.13 with
an updated version of node which might cause version conflicts.
use `ruby:2.7.2-alpine3.12`
=> Pin docker image to alpine3.12

app/services/course_search_service.rb, spec/docs/courses_spec.rb, spec/docs/providers/courses_spec.rb, spec/services/course_search_service_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseFilter.yml
https://trello.com/c/eQnKyAgV/851-s-filter-by-updatedsince-on-api-public-v1-courses-endpoint-update-tech-notes-from-provider
- Add `updated_since` filter scope to `CourseSearchService`
- Updated swagger doc spec
- http://localhost:3001/api/public/v1/recruitment_cycles/2021/courses?filter[updated_since]=2020-11-13T11:21:55Z
=> [851] Add `updated_since` filter option for /api/public/v1/courses

config/settings/production.yml, config/settings/qa.yml, config/settings/sandbox.yml, config/settings/staging.yml, spec/smoke/api/v1/courses_spec.rb, spec/smoke/api/v1/healthcheck_spec.rb, spec/smoke/api/v1/providers_spec.rb
Api URL is inferred by replacing `www.` with `api.` in `publish_url` setting.
This will not apply to all environments in PaaS as, qa,staging and sandbox don't have a `www` prefix in PaaS.
This is also causing smoke-tests to fail in sandbox env.
Use a separate variable with correct value for `publish_api_url`
=> Use separate publish_api_url setting

.github/workflows/deploy.yml, .gitignore, terraform/data.tf, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/app_config.yml, terraform/workspace_variables/production.tfvars, terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/sandbox.tfvars, terraform/workspace_variables/staging.tfvars
Move secrets from GitHub to Azure KeyVault
BAT-INFRA-SECRETS-{ENV} & TTAPI-APP-SECRETS-{ENV}
stored in Azure KeyVault
Use `app_config.yml` for storing non-secret environment variables.
Context
Managing secrets in GitHub Secrets makes it difficult to view/edit secrets.
Storing Application Secrets and Infrastructure as separate yaml files in KeyVault
and accessing them directly using terraform during deployment.
=> Manage secrets in KeyVault

.rubocop.yml, config/database.yml, config/settings/sandbox.yml, lib/tasks/sandbox.rake
We now have Publish in the sandbox environment and need to grant users access in bulk to match the current Apply sandbox users.
Add a rake task to allow the creation of users from a CSV in the sandbox environment. The csv can be piped into STDIN from a local machine and into this rake task on a running instance of the API in sandbox.
This task doesn't currently create providers as we need to have a think of the best way to handle the provider type etc and the implications of that for sandbox users. This will get us started with the publish sandbox for now.
This can be run locally on an anonymised DB dump with:
`rake sandbox:import_users\['./sandbox_users.csv'\]` (escaped [] needed for zsh)
Sandbox users needs to be in the format:
```
name, email,provider
Dave …
```
=> [993] Add sandbox user rake task

terraform/modules/paas/providers.tf, terraform/terraform.tf
Currently deployments could fail(worker app) when environment variables are changed.
Fixes an app restart issue with docker apps
https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/releases/tag/v0.13.0
Use cf provider 0.13
=> Update terraform provider

app/serializers/api/v2/serializable_provider.rb, spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb, spec/requests/api/v2/providers/providers_show_spec.rb
https://trello.com/c/xNFb9yGQ/2989-course-guidance-to-providers-on-publish
This PR exposes the value and tweaks the stubbed responses on the associated test files.
As part of a tweak to content on the publish-teacher-training app we need to expose this
attribute in order to show different content to university and SCITT/School Direct users.
=> Expose provider_type Attribute on Provider Serializer v2

config/initializers/semantic_logger.rb, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf
Send application logs to logit using user-provided-service instead of logstash gem.
Add logging user_provided_service and bind to app.
=> Configure logging as user provided service in PaaS

.github/workflows/deploy.yml, .gitignore, Makefile, terraform/workspace_variables/production.sh, terraform/workspace_variables/production.tfvars, terraform/workspace_variables/qa.sh, terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/sandbox.sh, terraform/workspace_variables/sandbox.tfvars, terraform/workspace_variables/staging.sh, terraform/workspace_variables/staging.tfvars
Secrets not in correct YAML format might lead to terraform erroring and outputting the values when running the deploy worklow.
To prevent such leaks we validate the secrets for correct YAML before running terraform.
Run secrets validation step before running terraform.
Set key_vault variables as env variables to reuse in make commands.
=> Validate secrets in deploy workflow before running terraform

app/services/csv_imports/fake_providers_import.rb, app/services/providers/create_fake_provider_service.rb, config/initializers/inflections.rb, lib/tasks/sandbox.rake, spec/services/csv_imports/fake_providers_import_spec.rb, spec/services/providers/create_fake_provider_service_spec.rb
We need to onboard users and providers to the Publish/TTAPI sandbox environment.
Add task that:
* Accepts a CSV
* Creates an organisation
* Creates a provider
* Adds a location to the provider
This task is procedural stylee for now. We are currently discussing building some UI on the API for this sort of support work. This will serve as 'documentation' for creating a better structured service class in the future.
The data set on the provider and associated entities is minimal placeholder data. Sandbox users should probably be directed to update things like the address and location etc otherwise there will be a lot of courses at the same location in Find.
The tasks will run locally. Create appropriate CSV files as per the task description.
`bundle exec rake …
=> [99] Add provider creation task

config/sidekiq.yml
We recently added a new background job to backfill `travel_to_work` and `london_borough` info to Sites
https://github.com/DFE-Digital/teacher-training-api/blob/6cdd9757e849a02e98a3c2da15762b92091a5c2a/app/jobs/travel_to_work_area_and_london_borough_job.rb#L2
- Add `add_travel_to_work_area_and_london_borough` queue to to `sidekiq.yml`
https://trello.com/c/Q3Di0OfY/3076-failing-sidekiq-healthcheck
=> Add missing queue to Sidekiq config

.github/workflows/deploy.yml
Pin update deployment status action to v0.4.3 as @5 (master) is erroring
Alert slack channel on deployment job failures.
=> Alert slack channel on deploy workflow failures

config/initializers/semantic_logger.rb
Running specs was spamming the console with a line or two of JSON output
for every single test. Way way too much.
Don't add SemanticLogger when in `test` env.
Before:
```
% be rspec spec/controllers/api/v2/courses_controller_spec.rb
Run options:
include {:focus=>true}
exclude {:smoke=>true}
All examples were filtered out; ignoring {:focus=>true}
{"host":"stutter.local","application":"Semantic Logger","environment":"test","timestamp":"2021-02-24T14:09:57.678556Z","level":"warn","level_index":3,"pid":73616,"thread":"10680","name":"CourseEnrichment","message":"Creating scope :draft. Overwriting existing method CourseEnrichment.draft."}
{"host":"stutter.local","application":"Semantic Logger","environment":"test","timestamp":"2021-02-24T14:09:57.859813Z","level":"info","level_index":2,"pid":736 …
```
=> don't spam-a-lot in test env

terraform/workspace_variables/production.tfvars
StatusCake check for https://teacher-training-api-prod.london.cloudapps.digital/ping
=> Add StatusCake check for cloudapps URL

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/smoke-test.yml
<!channel> is parsed as `@channel` only inside SLACK_MESSAGE
move <!channel> inside SLACK_MESSAGE to notify the channel.
=> Update @channel alert in SLACK_MESSAGE

azure/template.json
`SETTINGS__MAPIT_API_KEY ` is missing from the bg container.
Set `SETTINGS__MAPIT_API_KEY ` for the background container.
=> Add SETTINGS__MAPIT_API_KEY variable for bg container

app/serializers/api/public/v1/serializable_course.rb, docs/source/release-notes.html.md.erb, spec/serializers/api/public/v1/serializable_course_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml
The Apply sync job still uses the V3 API to fetch subject codes. With these on the `public/v1` API we can turn off the v3 API altogether and start to benefit from features of the V1 API like the `updated_since` filter for courses.
Add the field, a spec and documentation.
Introduce a pattern for release notes as discussed on Slack https://ukgovernmentdfe.slack.com/archives/CGVNJ2Q2F/p1614852108081800
Please be nice @defong 🙏
=> Add subject_codes to public/v1 API

swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml
https://trello.com/c/SHa65Stm/472-s-update-uk-eu-fees-info-in-api-documentation
- Update description in api docs and api spec for `fee_domestic` from 'Fee in GBP for UK and EU students.' to' Fee in GBP for UK students.'
- Visit the docs at `/api-reference.html#schema-courseattributes` and check the description for `fee_domestic`
=> [471] Update fee_domestic description in api docs

app/services/feature_service.rb, spec/services/feature_service_spec.rb
Add service to help use of features, patterns copied from Register and
Publish.
This has been pulled out of the other 452 PR as it's already a bit too large.
The change for the the GIAS spike needs to be put behind a feature flag, and in general we will likely want to support features in the API going forward.
Add a `FeatureService` which reuses patterns from Publish and Register.
=> [452] add feature service

app/controllers/support/providers_controller.rb, app/controllers/support/users_controller.rb, app/helpers/layout_helper.rb, app/views/layouts/provider_record.html.erb, app/views/support/providers/show.html.erb, app/views/support/users/index.html.erb, config/routes.rb, spec/features/support/providers/provider_users_list_spec.rb, spec/support/feature_helpers/pages.rb, spec/support/page_objects/support/provider_show.rb, spec/support/page_objects/support/provider_users_index_page.rb
https://trello.com/c/hpDqCfE2/1315-m-provider-show
- Add tab navigation to provider show page
- Add users index resource
Taking inspiration from Apply, when the user clicks on a provider, the show page lands on the "Details" tab (to be filled in later).
- Visit `/support/providers`
- Click on a provider
- Click on the "Users" tab
- Confirm table of users is displayed
=> [1315] Provider show page with users tab

terraform/modules/paas/main.tf
It's filling up in production
Increase disk quota to 1.5GB
The root cause should be examined separately
Successfully deployed to QA: https://github.com/DFE-Digital/teacher-training-api/actions/runs/722017731
=> Increase webapp disk quota

config/environments/production.rb
Rails is logging requests to /log/{env}.log
This is leading to an increased disk utilisation
Remove logs from being written to disk.
=> Stop Rails logging to file

app/components/paginated_filter/view.html.erb, app/components/paginated_filter/view.rb, app/components/providers/filters/script.js, app/components/providers/filters/style.scss, app/components/providers/filters/view.html.erb, app/components/providers/filters/view.rb, app/controllers/application_controller.rb, app/controllers/support/providers_controller.rb, app/helpers/application_helper.rb, app/models/provider_filter.rb, app/services/support/providers/filter.rb, app/views/support/providers/index.html.erb, config/locales/en.yml, spec/models/provider_filter_spec.rb
https://trello.com/c/8urvajGN/1314-m-provider-lookup
- Add provider filter section allowing text search using name or code
- Visit `/support/providers`
- Input a name or code
- Results should match input
=> [1314] Provider lookup supporting name or code

app/controllers/support/courses_controller.rb, app/views/layouts/provider_record.html.erb, app/views/support/courses/index.html.erb, config/environments/test.rb, config/initializers/semantic_logger.rb, config/locales/en.yml, config/routes.rb, spec/features/support/providers/provider_courses_list_spec.rb, spec/support/feature_helpers/pages.rb, spec/support/page_objects/support/provider_courses_index_page.rb, spec/support/page_objects/support/provider_show.rb, spec/support/page_objects/support/provider_users_index_page.rb
- https://trello.com/c/0Yz9ZE0n/1320-s-add-course-list-to-provider-pages-on-api-ui
- Add the provider's courses under a courses view
=> [1320] Add courses view to providers sub menu

app/components/paginated_filter/view.rb
- https://trello.com/c/yF9UWNHC/1324-s-fix-deprecation-warnings-re-errors-in-rails-62
`ActiveModel::Errors#keys is deprecated and will be removed in Rails 6.2.`:
These warnings are caused by a method in the jsonapi-rails gem calling `.keys` on a given errors object:
https://github.com/jsonapi-rb/jsonapi-rails/blob/6d49925aedb08c34d9891916fd5936e6697ba9d6/lib/jsonapi/rails/serializable_active_model_errors.rb#L28
You can confirm this by opening that class up locally, adding a breakpoint before that line and triggering the method manually. You'll see the deprecation warning raised in your console.
The change for those deprecations needs to be made there. I was going to create a patch to the gem but it looks like a couple already exist:
https://github.com/jsonapi-rb/jsonapi-rails/pull/130 …
=> [1324] Handle view component method deprecation warning

app/models/provider.rb
Hot fix to ensure that providers can make changes and a rollback from [this](https://trello.com/c/cwKSUfTf/1317-s-add-edit-provider-name-feature-to-providers-pages) ticket
Removed the uniqueness validation for the Provider name
=> [1317] Rollback of uniqueness of the provider name

config/initializers/sentry.rb
- Set sampling rate for API V1 course locations endpoint to 0.01
- Don't send any /ping transactions
- Default sampling rate to 0.5
Performance tracking was recently switched to Sentry because the Skylight gem was causing errors and disk over-usage. However Sentry has transaction quotas that we're going to start bumping against.
Send fewer course location lookup transactions to Sentry, they're taking up 85% of our quota. Also don't bother sending ping transactions.
Tested locally by setting the `SENTRY_DSN` env var and watching what shows up in Sentry.
=> Reduce events sent to Sentry.

config/initializers/sentry.rb
Previous attempt would still put us way over our 100k/mo transaction
limit, now we have:
- API v1 course locations endpoints, which accounts for 85% of our ~400/day requests, gives us ~20k/month transactions.
- All other endpoints, which account for 15% of our ~400/day requests, gives us ~36k/month transactions
See #1868.
Reduce logging rate even further, using actual m47h5!!! this time.
Probably just worth checking that the numbers actually make sense this time.
=> Reduce sentry logging rate even moar.

app/controllers/support/users_controller.rb, app/helpers/user_helper.rb, app/views/support/providers/_list.html.erb, app/views/support/providers/index.html.erb, app/views/support/users/_users.html.erb, app/views/support/users/show.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/providers.rb, spec/features/support/providers/viewing_a_user_spec.rb, spec/support/feature_helpers/pages.rb, spec/support/page_objects/sections/provider.rb, spec/support/page_objects/sections/user.rb, spec/support/page_objects/support/provider_users_index_page.rb, spec/support/page_objects/support/user_show_page.rb
https://trello.com/c/HtLxI0c5/1427-s-display-a-list-of-providers-that-a-user-has-access-to
- Adds links to the users table on `support/providers/:id/users`, which redirect to:
- A new user show page on `support/users/:id`, which shows:
- A paginated list of the providers that user has access to in the current recruitment cycle, which looks something like:
(page limit for pagination set artificially to four for the example screenshot, in reality it is 25 like elsewhere)
- Head to `support/providers/:id/users` for a provider
- Click on a user
- See that that user's providers are listed
=> [1427] Show a list of the providers a user has access to

Gemfile, Gemfile.lock, README.md, config/application.rb, config/initializers/sentry.rb, config/settings.yml, config/settings/production.yml, config/settings/qa.yml, config/skylight.yml, docs/alerting_and_monitoring.md
Switch back to skylight monitoring, and turn off sentry monitoring
- Add sentry back in.
- Turn off sentry performance monitoring
=> [1578] switch back to skylight

app/models/provider.rb, spec/requests/api/v2/providers/update_spec.rb
We are going to start collecting UKPRN numbers from providers. This PR sets out the validations. 
The front end work for this is in [this PR](https://github.com/DFE-Digital/publish-teacher-training/pull/1609).
- Add validation to ensure the string is 8 characters
- Allow blank values
- Custom validation error message
- Pull down the code and ensure you have the latest migrations
- Boot up the rails console and navigate to a provider
- Ensure the UKPRN will only be saved if it is `nil` or `8 characters`
=> [1494] Add validation to UKPRN on provider table

Gemfile, app/models/provider.rb, app/services/providers/create_fake_provider_service.rb, spec/factories/providers.rb, spec/models/provider_spec.rb
- [This trello ticket](https://trello.com/c/ymwbAv9m/1497-s-add-validation-to-urn-only-applicable-to-lead-school-providers)
- Added validation for presence of urn in lead schools, and a length range of between 5 and 6 characters for the urn if it is present
- Open your rails console `rails c`
- Create an invalid provider like so (a lead school provider without a URN, that is) 
- `Provider.create!(provider_type: "Y", recruitment_cycle: RecruitmentCycle.first)`
- You should see an error
- You can validate it by adding a urn, which will need to be 5-6 characters long. 
- No URN needed if the provider_type is anything but lead school
=> [1497] Validations added to urn

app/controllers/sessions_controller.rb, docs/config/tech-docs.yml, spec/controllers/sessions_controller_spec.rb
- https://trello.com/c/vfsBfD42/1544-m-logging-in-to-api-support
Originally barked up the wrong tree around the thinking but this PR just sets a relative url to the support console. There's another ticket to handle returning to the correct url once you pass DFE sign in.
We have to explicitly set it to a route within `support` or else it will direct you to the `support.html` page in the docs
At this time of writing, this change is deployed to the qa branch for testing.
=> [1544] Set relative url to system support

app/models/provider.rb, config/locales/en.yml
https://trello.com/c/gT1UaJom/1581-remove-uniqueness-validation-error-message-and-conditional
Finishing production bug fix
* Remove unique validation error message as no longer being used
* Remove if conditional as was always evaluating to true. As providers won't be editing their names from previous cycles then in practice it will always be the current recruitment cycle
Visit `/support/providers` and click on a provider
Edit provider name and verify max length validation and then edit name to see if it persists to database
=> [1581] Remove error message and if conditional

config/application.rb
Skylight is writing the below in to a log file inside the app container with each request and this is increasing the disk utilisation and could lead to degraded performance if app isn't recycled in time before all disk space is usedup.
[Log to SDTOUT](https://www.skylight.io/support/advanced-setup#logger)
The file should be not initialised/created in the app container since we are now writing to stdout.
=> [1579] Log skylight to STDOUT

.gitignore, app/models/provider.rb, app/models/site.rb, app/validators/reference_number_format_validator.rb, spec/factories/sites.rb, spec/models/provider_spec.rb, spec/models/site_spec.rb, spec/requests/api/v2/providers/update_spec.rb, spec/validators/reference_number_format_validator_spec.rb
This PR prevents users from entering a URN or UKPRN in an incorrect format.
- Validate that the string is 5-6 numbers on URN (Site table)
- Validate that the string is 8 numbers on UKPRN (Provider table)
- Allow blank values
- Custom validators
- Add staging data dump file to .gitignore
- Pull down the code and ensure you have the latest migrations
- Boot up the rails console and navigate to a Site
- Ensure the URN will only be saved if it is nil, 5 or 6 numbers
- Repeat for UKPRN on the provider table. 
- Ensure the UKPRN will only be saved if it is nil, or 8 numbers
=> [1503] Add validations to URN and UKPRN

app/models/course.rb, spec/lib/mcb/commands/courses/touch_spec.rb, spec/models/course_spec.rb, spec/requests/api/v1/course_spec.rb
- [This trello ticket](https://trello.com/c/Dbm8Ct4t/1678-s-touch-provider-when-course-is-updated)
- Added TouchProvider module to the course model to ensure that the provider model records updates to the course, through `changed_at`. 
- Open your rails console `$ rails c`
- `$ course = Course.all.sample`
- `$ course.changed_at` => outputs sometime in the past
- `$ course.provider.changed_at` => outputs sometime in the past
- `$ course.name = "A new name!"`
- `$ course.save`
- `$ course.changed_at` => outputs today's date
- `$ course.provider.changed_at` => outputs today's date # this is the important part
=> [1678] Touch provider when course is updated

.github/workflows/build.yml
Dependabot PRs can't access pipeline secrets
Don't push images to DockerHub from dependabot PR build
=> Don't access secrets for dependabot PRs

app/services/recruitment_cycle_creation_service.rb, app/services/rollover_service.rb, lib/mcb/commands/providers/rollover.rb, lib/tasks/rollover.rake, spec/services/recruitment_cycle_creation_service_spec.rb, spec/services/rollover_service_spec.rb
We are creating a service which encompasses the rollover code. It will be removed from MCB in a separate ticket. 
- Add `RecruitmentCycleCreationService`, which takes the required fields as arguments. 
- Create `RolloverService` encompassing the logic previously in `rollover.rb`. You can rollover all providers or specific ones using a rake task.
- Refactor MCB rollover task, encapsulating logic in `RolloverService`
- Build rollover rake tasks
- Run ` bundle exec rake rollover:create_recruitment_cycle"[YYYY, "YYYY-MM-DD", "YYYY-MM-DD"]`. This is `year`, `application_start_date` and `application_end_date` respectively. 
- Open up the rails console and execute `RecruitmentCycle.find_by(year: YYYY)` to check the recruitment cycle has been successfully created. 
- Ensure you have created a new …
=> [1725] Build rake task for rollover and RecruitmentCycle creation

app/services/allocation_copy_data_service.rb, lib/tasks/allocations.rake, lib/tasks/backfill_urns_and_ukprns.rake, spec/services/allocation_copy_data_service_spec.rb
https://trello.com/c/sJvRcyC6/1785-copy-allocations-data-into-recruitment-cycle-3
* Rake task `allocations:copy_allocations_data_to_cycle_year` to copy allocations from previous allocation year to current allocation year
=> [1785] Copy Allocations data into recruitment cycle 3

app/services/recruitment_cycle_creation_service.rb, lib/tasks/rollover.rake
Prevent rake task printing out puts statement when running the specs.
- Run `recruitment_cycle_creation_service_spec.rb` and ensure the puts statement is not displayed
- Ensure the rake task still works as expected
=> Prevent rake task printing out puts statement during tests

config/settings.yml, spec/config/settings_spec.rb
Allocations opened on 1 June 2021.
https://trello.com/c/yNzAoH7Q/1823-open-allocations-2021
Update the setting to open the new allocations year.
=> Update setting to open allocations 2021

.github/workflows/delete-review-app.yml
Terraform destroy fails if review app isn't created in the first place.
Check for existence of a state file before executing `tf destroy`
=> Check if terraform state exists before trying to delete app

app/controllers/api/v2/allocations_controller.rb, config/routes.rb
https://trello.com/c/BQ6F49Q6/1905-providers-unable-to-confirm-last-years-allocations
To be deployed before: https://github.com/DFE-Digital/publish-teacher-training/pull/1711
This PR allows publish to request allocations made by an accredited body in the previous recruitment cycle.
=> [1905] Allow requests for last year allocations on v2 API

app/controllers/api/v2/providers_controller.rb, app/deserializers/api/v2/deserializable_provider.rb, app/policies/provider_policy.rb, spec/controllers/api/v2/providers_controller_spec.rb, spec/requests/api/v2/providers/update_spec.rb
This is needed for Publish to be able to manage these new attributes. `Provider` attributes `can_sponsor_student_visa` and `can_sponsor_skilled_worker_visa` were added recently so that providers could declare information about the kind of visas they sponsor. This PR just attempts to make those attributes accessible via the `/api/v2/recruitment_cycles/:recruitment_cycle_year/providers/:provider_code` endpoint.
https://trello.com/c/I2K4fchq/3441-add-visa-flow-to-publish
- I had to add the new attributes to the `except` lists for a few other `update_*` methods because they are all called from the same action and leaving as is causes an unsupported param exception.
- I couldn't see an obvious place to put a high-level spec that tests this particular feature other than …
=> Permit visa attributes in V2 provider updates

app/views/layouts/application.html.erb, app/views/layouts/provider_record.html.erb
- [This trello ticket](https://trello.com/c/0vlooAj5/1916-s-back-link-on-provider-show)
- Added a backlink to take users back to the provider list page
- Start up rails server `SETTINGS__USE_SSL=1 rails s`
- Direct yourself to support console `https://localhost:3001/support/providers`
- Click on any provider
- At the top of the page above the provider name you should be able to see a backlink
=> [1916] Added backlink to the provider show page

app/controllers/concerns/error_handlers/base.rb, config/settings.yml, config/settings/production.yml, spec/controllers/concerns/error_handlers_base_spec.rb
https://trello.com/c/4cI5XPmN/1949-ttapi-is-not-reporting-errors-to-sentry-in-production
Previously we were swallowing exceptions in production using
rescue_from and not capturing them in sentry. Make this configurable
and make sure that sentry is notified
If you don't believe this works, I can screen share with some prys stuck inside the sentry-ruby gem to show the behaviour before and after this PR
=> [1949] Fix sentry reporting in controllers

Gemfile, Gemfile.lock
Reverts DFE-Digital/teacher-training-api#1966
Mystery as to why the CI passed on this PR, it broke when merged into master
=> Revert "Bump pagy from 3.13.0 to 4.8.0"

app/services/authentication_service.rb, spec/services/authentication_service_spec.rb
https://trello.com/c/6PXmSDyj/1911-bug-missing-personlisation-firstname
This is an attempt to fix a frequent Sentry exception caused by a welcome email job whereby the first name is missing which is required to personalise it.
- Reorder the methods under `AuthenticationService#update_user_information` to ensure first name gets a chance to be updated. Up until now, if the update email method blows up because of `AuthenticationService::DuplicateUserError`, none of the other methods get executed which might be the reason we're getting `BadRequestError: Missing personalisation: first_name` within `WelcomeEmailMailer`.
=> [1911] Reorder methods to ensure first name gets a chance to be update

app/controllers/api/v2/courses_controller.rb, app/deserializers/api/v2/deserializable_course.rb, app/policies/course_policy.rb, app/serializers/api/v2/serializable_course.rb, spec/factories/courses.rb, spec/requests/api/v2/providers/courses/update_additional_degree_subject_requirements_spec.rb, spec/requests/api/v2/providers/courses/update_age_range_spec.rb, spec/requests/api/v2/providers/courses/update_degree_grade_spec.rb, spec/requests/api/v2/providers/courses/update_degree_subject_requirements_spec.rb, spec/requests/api/v2/providers/courses_spec.rb, spec/serializers/api/v2/serializable_course_spec.rb
This PR follows on from #1967 which adds the `degree_grade` and `subject_requirements`  columns to the course table.
It does the work to expose the new attrs on the V2 API via the CourseSerailiser
This PR does the following:
1. Adds the new fields to the course factory
2. Updates the serialiser to expose them
3. Adds them to the deserialiser
4. Updates the controllers course_params and enrichment_params methods
5. Updates the course policy
6. Updates the course show request spec
https://trello.com/c/KAPUFr0o/3494-add-structured-degree-requirements-fields-to-the-v2-ttapi
=> Expose the structured degree fields on the V2 API

app/controllers/api/v2/allocations_controller.rb, config/routes.rb, spec/requests/api/v2/providers/allocations_spec.rb
Retrieval of allocations
Allow the retrieval of allocations using recruitment year as a filter.
Removed previous attempt as it was erroneous assuming that there will be a provider for previous recruitment cycle (ie. new providers). 
Should have no impact going forward, as it defaults to current allocation year.
=> [1918] Fixed by allowing allocation to return current and previous allocation year

app/services/authentication_service/duplicate_user_error.rb, spec/services/authentication_service/duplicate_user_error_spec.rb
https://trello.com/c/KMR5Tpjc/2031-add-debug-info-to-error-message-for-error-duplicateusererror
It is impossible to debug this without more information.
Sentry just prints out the error message for the exception, (we could
also use something called raven_context to add some json to the 
exception, but that feature is undocumented so this feels safer). It
would be nice to have the email address as well, but this would be 
filtered out by our sentry config for PII reasons.
Adds all the attributes on DuplicateUserError to the message
Not easy to test this with sentry as we disable it on the review apps. If you want to see the error message in action, just raise one manually in the console. Or if you really want to have a fun Friday afternoon, set up your own trial sentry account, set the dsn …
=> [2031] Add debug info to DuplicateUserError

lib/rack/request_output.rb
All the builds are failing due to the debug method not being passed a block 
- pass a block into the debug method
=> Appease Rubocop so the builds stop failing

app/controllers/api/v2/courses_controller.rb, spec/requests/api/v2/providers/courses/update_degree_subject_requirements_spec.rb
At the moment, on Publish if you provide a value for the degree_subject_requirements and the go and edit your answer to there not being any additional subject requirements, your original response is not set to nil.
https://trello.com/c/KAPUFr0o/3494-add-structured-degree-requirements-fields-to-the-v2-ttapi
- Allow the degree_subject_requirements field to be updated to nil
=> Fix degree_subject_requirements bug

app/models/course.rb, app/models/provider.rb, config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/models/provider_spec.rb
Starting in the 2022 recruitment cycle we will require providers declare whether or not they can sponsor visas (student and skilled worker) before publishing any courses in that cycle. 
https://trello.com/c/I2K4fchq/3441-add-visa-flow-to-publish
Validation as it appears in publish:
- Is there a better way to implement the specs for this?
- Are there any potential knock-on effects that might cause issues in the 2022 cycle?
=> Add validation for visa sponsorship

app/models/course.rb, app/models/provider.rb, app/services/courses/copy_to_provider_service.rb, app/services/providers/copy_to_recruitment_cycle_service.rb, spec/lib/mcb/editor/provider_editor_spec.rb, spec/services/courses/copy_to_provider_service_spec.rb, spec/services/providers/copy_to_recruitment_cycle_service_spec.rb, spec/services/rollover_service_spec.rb
Changing the rollover script so that it no longer rolls over courses which weren't published last cycle. Only courses which have the status `withdrawn` or `published` will be rolled over. Accredited bodies, which accredit valid courses will always be rolled over even if they have no courses.
- Add two `rollable?` methods, one on `Course` and one on `Provider` which encompass `content_status` logic.
- We don't rollover courses unless they are `rollable?`.
- We don't rollover providers unless they are `rollable?`.
- Remove failing MCB test as this is now redundant (all of MCB can now be removed).
- Run ` bundle exec rake rollover:create_recruitment_cycle"[YYYY, "YYYY-MM-DD", "YYYY-MM-DD"]`. This is `year`, `application_start_date` and `application_end_date` respectively. 
- Ensure you have …
=> [1908] Only rollover active courses and providers

app/models/course.rb, config/locales/en.yml, spec/models/course_spec.rb
https://trello.com/c/waUHPqGC/3496-add-the-structured-degree-requirements-section-to-publish
This adds in a validation to ensure that degree grade is present for courses in the 2022 or later cycles.
- Add an error message to the course if it's in the 2022 cycle and degree grade is not present 
Is the test coverage good enough?
=> Add degree requirements validation for publishing

.github/workflows/database-restore.yml
The job https://github.com/DFE-Digital/teacher-training-api/actions/workflows/database-restore.yml is failing
Bump the dependency azure-blob-storage-upload as the build is failing
Run the job
=> [2086] Bump azure-blob-storage-upload

.github/workflows/delete-review-app.yml
Delte review app fails if concurrent deployment takes more than 2 min
Increase to 30 min and fail the workflow immediately if the timeout is reached
See https://github.com/DFE-Digital/teacher-training-api/actions/runs/982270020
=> [2089] Fix delete review app timeout

app/controllers/api/v2/courses_controller.rb, spec/requests/api/v2/providers/courses/update_additional_gcse_equivalencies_spec.rb
As part of the work being carried out on the structured GCSE's on publish certain params
are not saving correctly to the database. On inspection this is due to the guard clause
on the update action of the controller. 
This PR updates the method to include these params.
=> Add qualification params to courses controller

.github/workflows/build.yml
Currently the review app deployment is asynchronous from the build workflow,
so it is not visible in the PR checks if the app deployment has failed.
Add an action to wait for the deployment workflow
Fail the PR build check, if the review app deployment fails
=> Wait for review app deployment to finish

app/models/provider.rb, app/models/site.rb, app/serializers/course_provider_serializer.rb, app/serializers/provider_serializer.rb, app/services/sites/code_generator.rb, spec/factories/sites.rb, spec/lib/mcb/commands/apiv1/providers/find_spec.rb, spec/models/provider_spec.rb, spec/models/site_spec.rb, spec/requests/api/v1/provider_spec.rb, spec/requests/api/v2/providers/providers_show_spec.rb, spec/serializers/course_provider_serializer_spec.rb, spec/serializers/provider_serializer_spec.rb, spec/services/sites/code_generator_spec.rb
Providers will be allowed to add more than 37 locations (sites) next cycle. We should remove the validations enforcing this allowing them to do so.
1. The first 37 sites will continue to have a UCAS style code, i.e(one of A-Z, 0-9 or -), after which the next set of locations will have a sequential code from "AA", "AB" and so on.
2. v1 of the API will only fetch 37 sites, which have the UCAS code.
3. v2, v3 and public v1 will show all available sites.
=> [2091] Publish locations allow providers to create more than 37 locations

app/models/course.rb, config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb
- [This trello ticket](https://trello.com/c/WR5JVk06/2093-m-users-get-an-error-message-when-they-try-to-publish-a-course-if-there-are-sites-on-the-course-without-urn)
- Added validation to the Course Model, that checks that all sites have URNs
- Create a new course in the 2022 cycle, and make sure that at least one connected site does not have a URN
=> [2093] Added validation to the course model for site urn

app/models/course_enrichment.rb, spec/models/course_enrichment_spec.rb
This validation for the presence of `CourseEnrichment#required_qualifications` should not be active after the 2021 recruitment cycle. It has been replaced by new attributes.
https://trello.com/c/bCnjk5oa/3561-remove-the-qualifications-needed-section-from-the-course-page-on-publish-for-2022-courses
- Make the `presence` validation conditional on recruitment cycle and update specs.
- Does this validation make sense?
- Can be manually tested by finding a draft 2022 course, setting it's _Qualifications needed_ to blank and attempting to publish.
=> Remove validation for CourseEnrichment#required_qualifications from 2022

app/models/course.rb, app/models/required_qualifications_summary.rb, app/serializers/api/public/v1/serializable_course.rb, spec/factories/courses.rb, spec/models/required_qualifications_summary_spec.rb
We've updated course creation in Publish to take structured data for
required degree and GCSE information. This will eventually replace the
free text `required_qualifications` attribute.
To maintain the existing interface of the V1 public API, we need to
transform the structured data into a value that can be returned in the
`required_qualifications` field in scenarios where a Course has no value
for that attribute.
https://trello.com/c/LR2VwtVq
Do this by adding a RequiredQualificationsSummary object that's invoked
via the Course model. This object:
- Takes an instance of Course as an argument
- Looks for the `required_qualifications` enrichment attribute, and uses
it if it has a value
- Otherwise generates summary text from the qualifications-specific
attributes on Course
- Can be …
=> Add legacy support for 'required_qualifications' attribute in public API

app/models/course.rb, app/models/course_enrichment.rb, config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/models/course_spec.rb, spec/requests/api/v2/providers/courses/publish_spec.rb
https://trello.com/c/oLvRx47b/3497-add-the-structured-gcse-requirements-section-to-publish
We're not stopping providers from publishing their courses without completing the new structured GCSE section.
We should be from courses in the 2022 cycle
- Add validation to the publish action which checks that `accept_pending_gcse` and `accept_gcse_equivalency` are not nil for providers in the 2022 cycle
This follows the established pattern from the degree and visa work
=> Add validations to the backend for publishing structured GCSE requirements

app/models/course.rb, spec/controllers/api/v2/courses_controller_spec.rb
We want a course to be invalid when the UKPRN or URN are missing on the provider. Currently we're only failing if both are nil.
Fail when URN OR UKPRN is nil.
This was only failing when both were nil.
=> [xxx] Fix URN validation for lead schools

config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb
We've had some conversations about this and settled here for now. This change affects behaviour in publish so this PR -> https://github.com/DFE-Digital/publish-teacher-training/pull/1799 supports the old and new formats and needs to be merged before this is deployed.
Capitalise for consistency.
Run publish (from the PR above if it isn't merged) against this PR. Ensure that the course validation links for UKPRN still link to the UKPRN form.
=> [2170] Update UKPRN validation message

app/models/course.rb, spec/models/course_spec.rb
We shouldn't be validating that maths, english and science UCAS equivalency sections have been completed for rolled over courses and it's being deprecated from the next cycle onwards.
- Ensure that we are not validating the maths, english and science fields for courses in the 2022 cycle
There were some issues with tests failing due to race conditions. John very kindly added the 2nd commit that fixed them.
=> Remove validation for UCAS entry requirements for 2022 cycles courses

app/controllers/api/v2/courses_controller.rb, app/services/courses/validate_custom_age_range_service.rb, config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/models/course_spec.rb, spec/requests/api/v2/build_new_course_spec.rb, spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb, spec/requests/api/v2/providers/courses/create_spec.rb, spec/requests/api/v2/providers/courses/publish_spec.rb, spec/requests/api/v2/providers/courses/publishable_spec.rb, spec/requests/api/v2/providers/courses/update_additional_gcse_equivalencies_spec.rb, spec/requests/api/v2/providers/courses/update_degree_subject_requirements_spec.rb, spec/requests/api/v2/providers/courses/update_gcse_requirements_spec.rb, spec/requests/api/v2/providers/courses/update_sites_spec.rb, spec/requests/api/v2/providers/courses/update_subject_spec.rb, spec/services/courses/validate_custom_age_range_service_spec.rb
The teacher training API currently generates error messages that don’t follow GDS recommendations. Let’s fix that!
* Capitalise reference number abbreviations (**Unique Reference Number** and **UK Provider Reference Number**)
* Don’t capitalise maths and science in error messages
* Don’t say ‘You must’
* Use ‘Select‘ not ‘Pick’
Not so much guidance, but some questions:
* Do tests on Publish need to be updated to expect these revised error messages?
* Do these changes follow the GDS recommendations? – @B-Bonner
=> Update error messages

app/services/providers/copy_to_recruitment_cycle_service.rb, app/services/rollover_service.rb, spec/services/rollover_service_spec.rb
Some providers are `rollable? == false` but want to be rolled over. E.g.a provider has no published courses last year but wants to start publishing courses in this cycle.
This change allows them to be rolled over.
* Add `force: ` argument to `CopyToRecruitmentCycleService`
=> [2187] Add force rollover option

app/models/course.rb, app/services/courses/copy_to_provider_service.rb, app/services/providers/copy_to_recruitment_cycle_service.rb, app/services/rollover_service.rb, spec/models/course_spec.rb, spec/services/courses/copy_to_provider_service_spec.rb, spec/services/providers/copy_to_recruitment_cycle_service_spec.rb, spec/services/rollover_service_spec.rb
Courses that have been published but have unpublished changes should be included in rollover.
* Make those courses rollable
* Add a `force:` argument to allow us to manually rollover any courses
* Refactor the `RolloverService` spec to stop it failing when unrelated code is changed
=> [2187] Make previously published courses rollable

Makefile, config/environments/loadtest.rb, config/settings/loadtest.yml, terraform/workspace_variables/app_config.yml, terraform/workspace_variables/loadtest.sh, terraform/workspace_variables/loadtest.tfvars, terraform/workspace_variables/loadtest_backend.tfvars
Apply requires a TTAPI env to use for its load testing.
Config for deploying a load test environment.
It is deployed manually using `make loadtest` commands.
Deployed and available at https://teacher-training-api-loadtest.london.cloudapps.digital
=> Configure load test environment

app/models/provider.rb, app/models/site.rb, app/services/providers/create_fake_provider_service.rb, app/validators/reference_number_format_validator.rb, db/seeds.rb, spec/models/provider_spec.rb, spec/models/site_spec.rb
- [This trello ticket](https://trello.com/c/M4m91TCf/2094-s-lead-schools-are-required-to-have-a-urn-and-a-ukprn)
- Added custom validations to not allow blank values for URN and UKPRN on sites and providers respectively, scoped to lead schools
- On a provider that is a lead school, try and make a site without a URN. You will be met with an error message on submission of the form. 
- On a provider that is a lead school, try and submit your contact details without a UKPRN. You will be met with an error message on submission of the form. 
- 🧵  These validations are only run `on: :update` to allow for creation of providers without a urn.
=> [2094] Lead schools are required to have a URN and UKPRN

app/serializers/api/v2/serializable_course.rb, spec/requests/api/v2/providers/courses_spec.rb, spec/serializers/api/v2/serializable_course_spec.rb
We need program type for some conditional content on the preview page 
- expose program type on the v2 course serialiser
=> Add program type to the v2 serialiser

app/serializers/api/v3/serializable_course.rb, spec/requests/api/v3/providers/courses/index_spec.rb, spec/requests/api/v3/providers/courses/show_spec.rb
These have already been added to the DB schema and the V2 API, see https://github.com/DFE-Digital/teacher-training-api/pull/1986/files
This PR just brings the V3 API up to date with these new columns.
https://trello.com/c/ZWSEnlXK/3535-📐-add-structured-gcse-requirements-fields-to-the-v3-api
- Are the tests adequate?
- Is there any documentation that needs to be updated?
- Are there any potential knock on effects of this change?
=> Add structured GCSE requirements fields to V3 API

app/serializers/api/v3/serializable_course.rb, spec/requests/api/v3/providers/courses/index_spec.rb, spec/requests/api/v3/providers/courses/show_spec.rb
The structured degree fields have already been added to the DB schema and the V2 API, see https://github.com/DFE-Digital/teacher-training-api/pull/1968
This PR just brings the V3 API up to date with these new columns.
- Are the tests adequate?
- Is there any documentation that needs to be updated?
- Are there any potential knock on effects of this change?
=> Add structured degree fields to V3 API

app/components/persona/view.html.erb, app/components/persona/view.rb, app/controllers/application_controller.rb, app/controllers/concerns/basic_authenticable.rb, app/controllers/personas_controller.rb, app/controllers/sessions_controller.rb, app/models/user_session.rb, app/services/authentication_service.rb, app/views/personas/index.html.erb, app/views/sign_in/index.html.erb, config/initializers/omniauth.rb, config/locales/en.yml, config/routes.rb, config/settings.yml, config/settings/qa.yml, spec/components/persona/view_preview.rb, spec/components/persona/view_spec.rb, spec/features/auth/dfe_sign_in_spec.rb, spec/features/auth/persona_spec.rb
We are adding personas to the TTAPI to enable us to use review apps. DfE sign in makes it difficult to whitelist the URLs created for the review apps. 
- Add dfe_signin and persona mode logic to the authentication_service
- Add persona view
- Add admin persona component button
- Add logic to the view which displays sign in if mode == dfe_signin
- Add logic to the view which displays persona if mode == persona
- Add logic to omniauth for new auth if AuthenticationService.persona?
- Add Persona controller with conditional if mode == persona
- Add persona routes and logic to use persona route if mode == persona
- Add sign_out logic to make signout button work
- Add admin persona details to Settings
`Product review edit`: This can now be reviewed on QA and Staging as I have manually deployed …
=> [2299] Add persona login

app/services/course_search_service.rb, spec/requests/api/v3/courses/index_spec.rb
Previously the `has_vacancies` filter was not taken into account when ordering by distance. This meant that some searches on Find would results in courses appearing higher up in search results even though they had sites with no vacancies
Squash that bug!
Make sense? [You can see a live example of the bug on prod](https://www.find-postgraduate-teacher-training.service.gov.uk/results?c=England&l=1&lat=51.4612794&lng=-0.1156148&loc=Brixton%2C+London%2C+UK&lq=Brixton%2C+London&rad=50&sortby=2&subjects%5B%5D=24)
|Find with bug|Find without the bug|
--- | --- |
|<img width="587" alt="before_find_no_vacancies" src="https://user-images.githubusercontent.com/5256922/127507468-b9f9a916-c4d2-4094-bf92-8174691fe8de.png">|<img width="608" alt="find_after" …
=> Bug fix - order courses correctly when ordering by distance and filtering by  'has_vacancies'

app/models/site.rb, spec/models/site_spec.rb
Locations aren't always a specifc school so they won't all have a URN
Remove `presence` validation from URN on sites aka locations
🚢
=> [2422] Remove presence validation for URN on locations

app/models/course.rb, config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb
Some sites don't have a URN and this is a problem for providers.
Follows on from https://github.com/DFE-Digital/teacher-training-api/pull/2088
Remove the validation that checked that all sites had a URN before
allowing a course to be published.
=> [2422] Course can be published without site URN

app/models/course.rb, spec/models/course_spec.rb
UCL require 5+ for GCSEs for the courses they accredit.
Currently, we only check whether they are the provider. This has caused issues as a provider has noted that it says 4+ for their courses accredited by UCL.
https://trello.com/c/jYTgdnjE/3778-fix-issue-with-courses-ucl-accredit-not-showing-5-for-gcses
- Check if UCL is the accredited provider in the `gcse_grade_required` method. If so also return 5.
=> Ensure courses UCL accredit require 5+ for GCSE requirements

app/models/required_qualifications_summary.rb, spec/models/required_qualifications_summary_spec.rb
This PR updates the content in the required qualifications summary model to be in line with Find. See the 3rd success criteria in this PR https://github.com/DFE-Digital/find-teacher-training/pull/873
https://trello.com/c/eHkPZRRx/3787-update-content-on-find-publish-for-structured-quals
- Update copy for equivalencies and pending GCSEs
=> Update the content in the required quals summary model

config/initializers/bigquery.rb, spec/services/token/decode_service_spec.rb
We integrate with BigQuery and store the key In secrets as JSON. Using `to_json` is breaking things.
Don't convert the JSON `to_json`
=> [xxx] BigQuery key is JSON

app/controllers/api/public/v1/application_controller.rb, app/controllers/api/v3/application_controller.rb, app/controllers/concerns/emits_request_events.rb, app/controllers/public_api_controller.rb, spec/requests/send_data_to_big_query_spec.rb
We are sending request events to BigQuery. The existing concern `EmitsRequestEvents` expects the controller to implement `current_user` and the v1, v3 and public/v1 controller don't. So v1 is erroring currently. v3 and public/v1 were missed from the original PR to add this functionality.
* Check for current_user before calling
* Refactor the public API controllers to use a common base class that includes the concern
Check that all API versions are responding without error when the send_data_to_bigquery feature is enabled.
The app will need to be deployed to check that BigQuery is receiving the events in all envs.
=> [xxx] Fix BigQuery current user bug

app/models/course.rb, spec/models/course_spec.rb
When a course has its vacancy status changed we expect the provider to be returned in a /providers API call with an updated_since filter. They currently are not as the `Provider#changed_at` is not updated when the `Course#site_statuses` are updated.
`touch_provider` when the `Course#update_changed_at` is called. `update_columns` skips callbacks so we need to call `touch_provider` explicitly.
Retrieve a course with vacancies in the console: `course = Course.with_vacancies.last`
Update the vacancy status: `course.site_statuses.each(&:no_vacancies!)`
Check the changed at on Course: `course.changed_at`
Check the changed at on Provider: `course.provider.changed_at`
They should match (pretty much). This provider should now appear on `/api/public/v1/recruitment_cycles/2021/providers?updated_since …
=> [2540] Course#updated_changed_at touches Provider

app/controllers/api/v2/courses_controller.rb, spec/requests/api/v2/providers/courses/create_spec.rb
UCAS Apply is breaking for some FE courses as the UCAS GCSE requirements is set to nil.
I've backfilled the current cycles data to not_required where necessary. This PR ensures that the correct value is set on course creation.
- Set english, maths and science to not required on course creation for FE courses
=> Ensure UCAS GCSE requirements are set to not_required for fe courses on creation

app/serializers/api/public/v1/serializable_course.rb, app/serializers/api/public/v1/serializable_provider.rb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/controllers/api/public/v1/providers_controller_spec.rb, spec/serializers/api/public/v1/serializable_course_spec.rb, spec/serializers/api/public/v1/serializable_provider_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml, swagger/public_v1/component_schemas/ProviderAttributes.yml
The new values for degree grade requirements need to be exposed on the public API so that they can be synced with Apply.
https://trello.com/c/BNDjZri5/3872-expose-the-new-visa-gcse-degree-values-on-the-public-ttapi
We need to expose the following on the public TTAPI:
For Providers:
- `can_sponsor_student_visa`
- `can_sponsor_skilled_worker_visa`
For Courses:
- `degree_grade`
- `degree_subject_requirements`
- `accept_pending_gcse`
- `accept_gcse_equivalency`
- `accept_english_gcse_equivalency`
- `accept_maths_gcse_equivalency`
- `accept_science_gcse_equivalency`
- `additional_gcse_equivalencies`
- Have I missed anything here?
=> Expose the new visa/GCSE/Degree attributes on the public API

app/models/course.rb, app/services/course_search_service.rb, spec/docs/courses_spec.rb, spec/docs/providers/courses_spec.rb, spec/models/course_spec.rb, spec/requests/api/v3/courses/index_spec.rb, spec/services/course_search_service_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseFilter.yml
```
As an... international user of Find 
I need to... find courses that accept my degree grade
So that... I don’t end up making an unsuccessful application
```
- Add a degree grade filter
- Update API docs
https://trello.com/c/UO2ZC9E0/3843-%F0%9F%93%90-dev-ttapi-add-minimum-degree-grade-filter
=> Add 'degree grade' filter

app/models/course.rb, app/services/course_search_service.rb, spec/docs/courses_spec.rb, spec/docs/providers/courses_spec.rb, spec/models/course_spec.rb, spec/requests/api/v3/courses/index_spec.rb, spec/services/course_search_service_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseFilter.yml
One of the new features that we're adding to Find is the ability to filter courses based on whether the provider can offer either a skilled worker or student visa 
This PR adds in the functionality required to allow this.
- Add a scope to the course model which returns providers who can sponsor a visa
- Add the scope to the course search service
- Tests
=> Add filter for courses whose provider can sponsor visas

config/locales/en.yml, spec/controllers/api/v2/courses_controller_spec.rb
This updates the error message if you try to publish a course without answering the visa sponsorship questions.
See https://github.com/DFE-Digital/publish-teacher-training/pull/1890 for full context
=> Update error message to match question wording

.rubocop_todo.yml, app/jobs/send_event_to_big_query_job.rb, app/lib/big_query/entity_event.rb, app/models/concerns/emits_entity_events.rb, config/analytics.yml, config/sidekiq.yml, lib/tasks/big_query.rake, spec/models/concerns/emits_entity_events_spec.rb
We are sending create and update events to BigQuery.
* Add a `EmitsEntityEvents#send_import_event` - method to send an import event for a model
* Add config/analytics.yml which specifies the entities (db table names) and the fields that should be included in the entity event (generally, excluding PII)
* Add a rake task that will loop through the entities in the config file and queue up a job to send the entity.
=> [2392] Import existing db entities into BigQuery

Gemfile, Gemfile.lock, config/initializers/oj.rb
https://trello.com/c/y5aY2dH0
Oj performs better than the default Rails JSON serializer, and can be used as a drop-in replacement.
The following are Apache Bench results for 500 requests made to`/api/v3/courses`:
Time taken for tests:   283.719 seconds
Time per request:       567.437 [ms] (mean)
Time taken for tests:   251.801 seconds
Time per request:       503.602 [ms] (mean)
- Add oj gem
- Add initializer to configure for Rails
=> Add oj for faster JSON parsing

terraform/modules/paas/main.tf
App startup timeout to 300 seconds
database create/update timeout to 1 hour
Deployment are failing occasionally because the app is taking more than 3 mins to startup.
Increase startup timeout to 5 mins
=> Increase app startup timeout

app/controllers/api/public/v1/courses_controller.rb, spec/controllers/api/public/v1/courses_controller_spec.rb
- [This trello ticket](https://trello.com/c/LtIVZbq7/16-public-v1-course-endpoints-date-validation)
- Added an error rescue notifying the user of the correct date time format if they enter an invalid `changed_since` value
- Go to `api/public/v1/recruitment_cycles/2022/courses?filter%5Bupdated_since%5D="something_invalid"` to see the error catching with a 400, and custom error message
=> [16] Added rescue if changed_since value is invalid

config/analytics.yml
Upon review we decided we want to import the values from the nctl_organisation table into BigQuery.
https://trello.com/c/krlbZnL4/18-import-existing-db-entities-into-bigquery
Add nctl_organisation and fields to `analytics.yml` file.
I don't think there any tests for this ...
=> [18] add nctl_organisation table to BigQuery

spec/spec_helper.rb
So that we can use the --only-failures and --next-failure flags when
running specs.
=> Add rspec failures file

app/services/support/data_exports/users_export.rb, spec/services/support/data_exports/users_export_spec.rb
We have a CSV export of users in the support console that we use for mailing lists etc. We also have SQL pad but only on the anonymised data. 
Add user ID, first and last login dates.
If we add user ID BAs can link this list with the anonymised data in staging for analysis without having to do said analysis on production.
First and last login dates are useful for UR to determine active users.
Run the API, open the support bit and click download users CSV in the user tab.
=> [xxx] Add extra fields to users export

lib/tasks/big_query.rake
The redis client will raise a `Redis::CommandError` when an operation is attempted that will cause it to breach its configured memory limit. When we ran this task on staging we almost reached that limit so as an extra bit of safety this commit will cause a sleep to allow Sidekiq to reduce the queue size back below the threshold. The staging data is effectively identical to production so it is unlikely that we'll hit this limit with more workers running in production. This should be sufficient to deal with an unexpected peak.
* Retry 5 times on Redis::CommandError
* Sleep for 10 seconds to give Sidekiq time to clear some jobs
=> [2392] Throttle on Redis out of memory

config/environments/production.rb, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf
Use separate redis instance for caching
Create a redis instance for caching
Set memory policy for redis instances
Set rails cache store to redis_cache_store
=> Separate redis instance for cache

Gemfile, Gemfile.lock, app/controllers/api/v3/courses_controller.rb, app/serializers/api/v3/serializable_course.rb, config/environments/test.rb, spec/requests/api/v3/courses/index_spec.rb, spec/spec_helper.rb
We forked jsonapi-rails because:
- its caching mechanism is broken
- the project appears to be abandoned, with the current maintainer unresponsive to open issues and PRs
Commit 359d794 of the fork provides a fix for the cache.
With the code change in place, we're able to add caching to V3 courses.
- Use the DfE fork of jsonapi/rails
- Do sub-object caching of courses in the index action of the V3 courses controller, keeping serialised JSON
course payloads in the cache and using them when rendering responses at
this endpoint.
- Is the spec sufficient?
=> Use jsonapi-rails fork and add caching to V3 courses endpoint

spec/requests/api/v3/courses/index_spec.rb
Initial version of these specs were dependent on order of courses in the returned response.
Use `match_array` to remove order dependency.
=> Fix ordering bugs in v3 cache specs

app/lib/big_query/entity_event.rb, config/analytics.yml, spec/lib/big_query/entity_event_spec.rb
`Provider.accrediting_provider_enrichments` is an array in a jsonb field. Sending this to BigQuery is currently failing.
Update `BigQuery::EntityEvent` to handle array attributes and send as JSON.
=> [xxx] Send arrays to BigQuery as json

app/lib/big_query/entity_event.rb
We need more precision to differentiate between events happening in the same second.
We timestamp events sent to Big Query. Those events often happen almost simultaneously so we need to be more precise to determine the order in Big Query.
Two brackets and the number 6.
I copied this so it must be fine -> https://github.com/DFE-Digital/apply-for-teacher-training/pull/5678
=> [xxx] Increase BigQuery timestamp precision

app/models/course.rb, app/services/course_search_service.rb
The endpoint that Find uses for course searches is high traffic and can be slow for certain queries. Therefore we have attempted to analyse the database queries to get a handle on what they are doing, how slow or fast they are and come up with any optimisations that are possible.
This is an optimisation extracted from https://github.com/DFE-Digital/teacher-training-api/pull/2188. It simply eliminates a double join from the `course` table to the `course_site` table resulting in a measurable performance gain and an (accidental) bug fix (I think).
https://github.com/DFE-Digital/teacher-training-api/pull/2188 contains a fair amount of context for this change and some analysis of the underlying queries.
The code change is very small here and just attempts to ensure that there is a single join …
=> Optimisation for /v3/courses SQL - remove double join to `course_site`

app/jobs/send_event_to_big_query_job.rb, config/initializers/sidekiq.rb
Filling up Logit with bigquery job log
Stop filling up Logit with bigquery job log by setting sidekig log level to WARN and bigquery job activejob log to null logger
Same implementation as find
=> [2261] Stop logging bigquery

terraform/workspace_variables/app_config.yml, terraform/workspace_variables/production.tfvars
In preparation for the cycle opening, we tested this combination with Find.
A combined capacity of 500 request threads gives us an optimal setup against the DB plan.
This combination has been tested against find and with caching enabled gives us an ideal setup.
Run 10 web app instances and 4 worker app instances in prod.
Set RAILS_MAX_THREADS to 50
=> Run 10 web app instances and 50 RAILS_MAX_THREADS

app/models/course.rb, app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
This endpoint was flagged as problematic by Skylight:
https://www.skylight.io/app/applications/NXAwzyZjkp2m/recent/6h/endpoints/API::Public::V1::Providers::CoursesController%23index?responseType=jsonapi
The logs show that there are a lot of 1+n type queries happening when we hit this endpoint. The tables being queried repeatedly include `provider`, `financial_incentive`, `subject`, `course_enrichment`.
Two very subtle changes result in measurable performance improvements by reducing these queries.
1. I've adjusted the `includes` in the query used by this endpoint to avoid the 1+n's on `financial_incentive` and `course_enrichment`
2. It turns out that there is a repeated lookup in the `Course#bursary_requirements` method. This eliminates a bunch of 1+n's on the `subject` table.
As a rough …
=> Query tuning for the public V1 provider/courses index endpoint

config/settings/production.yml
Make 2022 the current cycle in production.
Remove the settings override in /settings/production.yml
=> [164] Switch cycle to 2022

app/serializers/api/v3/serializable_course.rb
So that updates to the provider bust the cache entry for serializable
courses.
=> Add provider to V3 serializable course cache key

app/controllers/api/v3/courses_controller.rb
- To reduce latency on the v3 `/courses` endpoint
- use `course_search.size` instead of `course_search.count("course.id")`
- run `ab -n 10 http://localhost:3001/api/v3/courses` from your command line with and without the changes above to see the latency difference
=> [203] Use size instead of count

app/models/course.rb, config/settings/review.yml, spec/controllers/api/v2/courses_controller_spec.rb, spec/models/course/publishable_spec.rb, spec/requests/api/v2/providers/courses/publish_spec.rb, spec/requests/api/v2/providers/courses/publishable_spec.rb
- We are getting situations where an accredited body is discarded, but courses that are accredited by them are still able to be published. 
- Add a validation that prevents courses from being published, if their AB does not exist in the current cycle
=> [xxx] Validate accredited body if course not self accredited

app/controllers/support/allocation_uplifts_controller.rb, app/controllers/support/allocations_controller.rb, app/models/allocation.rb, app/models/allocation_uplift.rb, app/models/provider.rb, app/models/recruitment_cycle.rb, app/views/support/_menu.html.erb, app/views/support/allocation_uplifts/edit.html.erb, app/views/support/allocation_uplifts/new.html.erb, app/views/support/allocations/_list.html.erb, app/views/support/allocations/index.html.erb, app/views/support/allocations/show.html.erb, config/locales/en.yml, config/routes.rb, config/settings/review.yml, spec/factories/allocations.rb, spec/factories/recruitment_cycles.rb, spec/features/support/allocations/allocation_uplift_edit_spec.rb, spec/features/support/allocations/allocation_uplift_new_spec.rb, spec/features/support/allocations/allocations_list_spec.rb, spec/features/support/allocations/allocations_show_spec.rb, spec/services/allocations/update_spec.rb, spec/support/feature_helpers/pages.rb, spec/support/page_objects/support/allocation_uplift_edit.rb, spec/support/page_objects/support/allocation_uplift_new.rb, spec/support/page_objects/support/allocations_index.rb, spec/support/page_objects/support/allocations_show.rb
- [This trello ticket](https://trello.com/c/VRq3HZqn/320-add-support-interface-screen-to-edit-uplifts)
- Add `Allocations` tab on the support console
- Lists providers with allocations
- Allows CRU actions on AllocationUplift relation to Allocation
- Log into support console
- Go to allocations tab
- CRU allocation uplifts on each allocation for each provider listed
=> [320] Add support interface screen to edit uplifts

config/settings/sandbox.yml
The sandbox config was misaligned 
Sandbox are aligned with DSI `prod` settings
They are aligned with DSI `prod` settings
https://github.com/DFE-Digital/publish-teacher-training/blob/master/config/settings/sandbox.yml
> Cannot really test locally as it's DSI is 3rd party
=> [0377] Added DSI prod for sandbox configs

app/views/support/allocations/_list.html.erb, app/views/support/allocations/show.html.erb
- Adding Accredited Body Name and Code to the allocation support soncole
- Adding Accredited Body Name and Code to the allocation support soncole
- Go to support console
- Click on the PE Allocations tab
- View the changes on the table
=> [xxx] AB name and code added to allocation support console

app/controllers/support/users_controller.rb, app/views/support/users/show.html.erb, config/routes.rb, spec/features/support/users/deleting_a_user_spec.rb, spec/support/page_objects/support/user_show_page.rb
- [This trello ticket](https://trello.com/c/x5QrpcuK/368-allow-users-to-be-deleted-in-the-support-ui)
- Add delete user functionality to support console
- Go to support console
- select user tab
- select a user by clicking their email address
- scroll to bottom of page and click delete this user
=> [368] Add delete user to support

app/controllers/api/v2/courses_controller.rb, app/models/course.rb, spec/models/course_spec.rb
Admin can set `send value` after course is published
Amended so that admin can set `send value` after course is published
This PR is standalone but lays the ground works for
https://github.com/DFE-Digital/publish-teacher-training/pull/1999
=> [0365]  Amended so that admin can set `send value` after course is published

app/serializers/api/v3/serializable_course.rb, app/serializers/jsonapi_course_cache_key_helper.rb, spec/requests/api/v3/courses/index_spec.rb
We currently have caching on the [V3 Courses Controller](https://github.com/DFE-Digital/teacher-training-api/blob/master/app/controllers/api/v3/courses_controller.rb#L16).
However, when a provider updates a course’s locations in Publish (eg adds a site) the cache does not expire and the updated sites are not showing on the results page in Find (_Nearest of X locations to choose from_  has the wrong total)
This is because when a course is touched `#updated_changed_at` only updates the `changed_at` column in the course table and the ~`jsonapi_rails` gem~ custom cache key we specify for jsonapi_rails expects the `updated_at` column to be updated.
- Create `JsonapiCourseCacheKeyHelper` and include this helper in the SerializableCourse class. This adds the 'changed_at' value to the cache key …
=> Add 'changed_at' to SerializableCourse 'jsonapi_cache_key'

app/services/statistic_service.rb, spec/factories/recruitment_cycles.rb, spec/requests/reporting_spec.rb, spec/services/statistic_service_spec.rb
The statistics for allocations on the performance Dashboard are coming 
through incorrectly. After looking into this the service is workingas it 
should be. It's just that because Allocations take place in June/July 
i.e. before cycle starts they are associated with previous year's 
recruitment cycle. 
The quick fix here is to pass in the previous year.  I've done this and run the numbers past Adam who says they all look as 
expect for the previous and current cycles.
Would this need a feature/system spec?
or should we backfill all of the allocations to match the revruitment cycle they are for?
=> [397] Fix Stats service to pass in correct cycle

app/models/course.rb, spec/models/course/assign_program_type_spec.rb, spec/models/course/funding_type_spec.rb, spec/services/courses/assign_program_type_service_spec.rb
https://trello.com/c/Ihd5u7WM/289-bug-invalid-course-2vvz-cannot-be-edited
Sentry error triggered by validation of course with accredited body and salary.
After discussion with Matilde and Gaby it turns out that this is not 
required for editing a course. The ability for providers to create 
salaried courses does not exist so this should only affect those merged 
in recently.
Removal of validation and assocaited tests
=> [0289] Remove accredited body salary validation

app/components/persona/view.html.erb, app/views/personas/index.html.erb, spec/features/auth/persona_spec.rb
A persona-based authentication mode exists for use in development and
QA. Currently this supports sign in of a support user only.
https://trello.com/c/Ghmij2De
Enhance this with additional users ported across from the Publish
app. Each of these users maps to an anonymised account in the TTAPI
database dump available on Github.
- Can be accessed via `/sign-in` when running locally with persona auth mode enabled.
- Doesn't do much right now — you'll go to support if you sign in as Colin, everyone else will go to the blank Publish holding page.
- Have retained (but re-written) the lightweight feature spec that was already there. This is probably sufficient given this is an internally-facing bit of functionality. Also, our route definitions don't define the developer-mode endpoints unless the …
=> Add additional Persona users

Gemfile, Gemfile.lock, app/controllers/concerns/pagy_pagination.rb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb, spec/controllers/api/public/v1/providers_controller_spec.rb
Dependabot failed to update the Pagy gem as it introduced breaking changes
After updating the gem locally it looks as if certain syntax around Pagy has been updated. There's no longer a need to specify `urls: true` in concerns.  Also, there is no longer a need to include a fake protocol and domain of `http://test.host` for url prefixes in tests that use the gem.
Have I overlooked anything?
=> [319] Update pagy gem

app/controllers/concerns/pagy_pagination.rb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb, spec/controllers/api/public/v1/providers_controller_spec.rb
We updated the Pagy gem recently and the the update removed the hostname
prefix from the metadata pagination links which is a breaking change to
the API and not what we wanted. This change puts the full absolute links
back.
* Add `absolute: true` argument for pagy metadata
Run the API -> http://localhost:3001/api/public/v1/courses should have absolute pagination links.
=> [xxx] Make metadata links absolute

lib/tasks/correct_subject_positions.rake
- [This trello ticket](https://trello.com/c/VoUTfJmm/411-ensure-the-financial-incentive-is-only-applied-to-the-first-major-subject-on-a-course)
- Some courses have subjects that are in an incorrect position/order. This trickles down into an incorrect Financial Incentive being applied to them, as we always take the financial incentive from the *first* subject.
- Create a rake task to fix the incorrect subject positions
- You will need to run the rake task with arguments. It takes arguments of course_ids, seperated by spaces. For example...
- `bundle exec rake correct_subject_positions:flip_subjects'[id1 id2 id3]'`
- Run the rake task to see the courses get fixed
=> [411] Rake task to fix incorrect subject position

app/models/course.rb, spec/models/course_spec.rb
- [This trello ticket](https://trello.com/c/VoUTfJmm/411-ensure-the-financial-incentive-is-only-applied-to-the-first-major-subject-on-a-course)
- Courses have `financial_incentives`. While the relationship is correct, we only need to worry about the incentive of the *main*, or first subject
- This PR changes so it only worries about the first `financial_incentive` (note the lack of pluralisation) on the first, or *main* subject, rather than checking through each subject for an incentive.
=> [411] Course financial incentives scoped to first subject

app/models/course.rb, spec/models/course_spec.rb
- Sentry errors for nil class when calling `financial_incentive` method
- Add a safe navigation operator to ensure nil values dont have methods called on them
- Run the specs
=> [xxx] Add safe navigation to Modern Languages FI

app/components/providers/filters/view.html.erb, app/components/providers/filters/view.rb, app/controllers/api/public/v1/provider_suggestions_controller.rb, app/controllers/api/v2/providers_controller.rb, app/controllers/api/v3/provider_suggestions_controller.rb, app/controllers/api/v3/providers_controller.rb, app/controllers/support/providers_controller.rb, app/models/course.rb, app/models/provider.rb, app/models/provider_filter.rb, app/services/support/filter.rb, app/views/support/providers/index.html.erb, config/locales/en.yml, spec/features/support/providers/providers_filter_spec.rb, spec/models/course_spec.rb, spec/models/provider_filter_spec.rb, spec/models/provider_spec.rb, spec/services/support/filters/filter_spec.rb
As part of ongoing improvements to the ttapi support console, it has been asked that the filter on the provider page has the capacity to filter by course code as well as provider name/code.
This PR adds in the functionality to the current view filter and associated services.
Search by course code:
search by provider code and course code:
Will this be okay for now? We may want to consider refactoring into it's own filter if filters in general across the service become more complex.
=> [376] Add to search via course code to Providers list on support

app/controllers/api/public/v1/provider_suggestions_controller.rb, app/controllers/api/v2/providers_controller.rb, app/controllers/api/v3/provider_suggestions_controller.rb, app/controllers/api/v3/providers_controller.rb, app/models/provider.rb, app/services/support/filter.rb, spec/models/provider_spec.rb, spec/services/support/filters/filter_spec.rb
- [This trello ticket](https://trello.com/c/vr0pImZO/485-bug-search-by-provider-code-on-pe-allocations-tab-support-console-doesnt-work)
=> [485] Change pg search method

app/controllers/support/courses_controller.rb, app/views/support/courses/edit.html.erb, app/views/support/courses/index.html.erb, config/locales/en.yml, spec/features/support/providers/courses/editing_a_course_spec.rb, spec/features/support/providers/provider_courses_list_spec.rb, spec/requests/api/v2/build_new_course_spec.rb, spec/support/page_objects/sections/course.rb, spec/support/page_objects/support/provider/course_edit_page.rb
As part of ongoing improvemtns to the support console, support users need the ability to update more course details than just the course code.
This PR adds additional field to the course edit page to allow both course title and start date to be updated as well as course code.
Test in review app, plz let me know RE: any refactor.
=> [433] Allow support users to edit the details of a course

app/controllers/api_error_controller.rb, app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/controllers/publish_interface/providers_controller.rb, app/helpers/provider_helper.rb, app/views/errors/forbidden.html.erb, app/views/errors/internal_server_error.html.erb, app/views/layouts/publish_interface.html.erb, app/views/layouts/support.html.erb, config/application.rb, config/locales/en.yml, config/routes.rb, spec/controllers/api_error_controller_spec.rb
We don't have GOVUK style error pages for these HTTP response codes in TTAPI.
https://trello.com/c/4PUK3wCt
- Copy the ones from Publish, along with the routing and controller code.
- Tweak the service name in the header so it makes sense across Support, New Publish, and these error pages.
- Should be fairly easy to trigger a 404 and 403 in the review app, a 500 probably easier to do locally
- If testing locally, you'll need to set `config.consider_all_requests_local` to `false` in `development.rb`
=> Add custom error pages

app/controllers/support/courses_controller.rb, spec/features/support/providers/courses/viewing_providers_courses_spec.rb
https://sentry.io/organizations/dfe-bat/issues/2827983994/?project=1377944&referrer=slack
https://trello.com/c/oX1yp6n4/448-server-error-when-accessing-deleted-provider
This error was triggered by trying to access a provider which was discarded from the support console. This may have been a red herring and somebody accessing the provider's courses via the url directly as the providers list in the support console already filters out discarded providers.
The API already returns a 404 so I think this may have just been an edge case with the scenario described above. I've added a fallback for now.
- Try to access the same url the sentry error got triggered by `https://localhost:3001/support/providers/17139/courses` and it should redirect to the support providers list
=> [448] Rescue from discarded provider in support providers controller

app/controllers/application_controller.rb, app/controllers/publish_interface/providers_controller.rb, app/controllers/sessions_controller.rb, app/forms/publish_interface/about_your_organisation_form.rb, app/helpers/view_helper.rb, app/models/provider.rb, app/views/layouts/application.html.erb, app/views/publish_interface/providers/about.html.erb, app/views/publish_interface/providers/contact.html.erb, app/views/publish_interface/providers/details.html.erb, config/locales/en.yml, config/routes.rb, spec/features/publish_interface/edit_provider_details_spec.rb, spec/support/feature_helpers/govuk_components.rb, spec/support/feature_helpers/publish_interface_pages.rb, spec/support/feature_helpers/support_pages.rb, spec/support/features.rb, spec/support/page_objects/publish_interface/provider_contact_details_edit.rb, spec/support/page_objects/publish_interface/provider_details_edit.rb, spec/support/page_objects/publish_interface/provider_details_show.rb
We're gradually moving Publish into the TTAPI codebase. This is the next set of code to be migrated across.
https://trello.com/c/wlq5VfsQ
- Move over most of the About Your Organisation section (everything except Visa sponsorship, which will follow in a later PR)
- Small improvements to application layout and sign in flow
- See commits for more detail
- In a review app or locally, navigate straight to the About Your Organisation section, eg— http://localhost:3001/publish/organisations/1O8/2022/details
- All edits and validation errors should match what's currently in Old Publish (except Visas, tbc)
- The behaviour in the controller actions is essentially a combination of the behaviour in Old Publish and in the V2 API endpoint that Old Publish calls. I've used a form object to combine …
=> Migrate Provider and Contact details from Old Publish

app/controllers/publish_interface/providers/visas_controller.rb, app/forms/publish_interface/base_provider_form.rb, app/forms/publish_interface/provider_visa_form.rb, app/views/publish_interface/providers/details.html.erb, app/views/publish_interface/providers/visas/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/publish_interface/editing_visa_sponsorships_spec.rb, spec/forms/publish_interface/provider_visa_form_spec.rb, spec/support/feature_helpers/publish_interface_pages.rb, spec/support/page_objects/publish_interface/provider_visa_sponsorships.rb
- https://trello.com/c/v9bhJE9a/481-publish-ttapi-merge-migrate-visa-sponsorship
- Migrate over visa sponsorships from publish
=> [481] Migrate visa sponsorships

lib/tasks/migrate_user_organisation_to_user_permission.rake, lib/tasks/validate_organisation_user_permission_migration.rake
- [This trello ticket](https://trello.com/c/hlEKCLCm/457-rake-task-to-migrate-userpremission-from-organisations)
- A rake task to migrate the OrganisationUser records to UserPermission
- `bundle exec rake organisation_user_migrate:migrate_organisation_user_to_user_permission`
=> [457] (Part 3) Rake task to migrate userpremission from organisations

app/controllers/support/locations_controller.rb, app/views/layouts/provider_record.html.erb, app/views/support/locations/index.html.erb, config/locales/en.yml, config/routes.rb, spec/features/support/providers/courses/viewing_providers_courses_spec.rb, spec/features/support/providers/locations/locations_list_spec.rb, spec/support/feature_helpers/support_pages.rb, spec/support/page_objects/sections/location.rb, spec/support/page_objects/support/provider/locations_index_page.rb
- https://trello.com/c/qHQhzncn/499-add-locations-tab-in-support-console
- Add the locations list to the providers tab in the support console
`support/providers/18035/locations`
=> [499] Add locations list to providers tab in support console

.rubocop_todo.yml, lib/tasks/big_query.rake, spec/validators/phone_validator_spec.rb, spec/validators/reference_number_format_validator_spec.rb
Clearing rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
For the validator spec files i have moved the classes outside of the test describe blocks.
For the rake task I have done the same, but I had to additionally redefine ActiveRecord as classes are now outside of the namespace. Additionally, constants triggered a further linting error and so have moved themout too.
=> [489] Rubocop To Do: Extract embedded classes from code blocks

spec/serializers/api/v2/serializable_access_request_spec.rb
- A flakey spec
- Use `be_between`
=> [xxx] Use be_between for flakey spec date

config/application.rb
- https://trello.com/c/CaFE7I3v/398-increase-user-session-expiry
Increase session expiry to 3 days to coincide with https://github.com/DFE-Digital/publish-teacher-training/pull/2048
=> [398] Set session expiry to 3 days

terraform/modules/paas/data.tf, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/qa.tfvars
Adding qa2 routes for publish-ttapi redirection
https://trello.com/c/uwBX42F6/392-publish-ttapi-merge-set-up-dns-record-for-www2
-Following the same format as applied to apply-for-teacher-training
-Changing host names to a list
-Extra variable for redirect hostname
-Added redirect domain
=> Adding qa2 routes for publish-ttapi redirection

.rubocop_todo.yml, app/components/flash_banner/view.rb, app/components/header/view.rb, app/components/navigation_bar/view.rb, app/components/page_title/view.rb, app/components/paginated_filter/view.rb, app/components/paginator/view.rb, app/components/tab_navigation/view.rb
Clear up of Rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
Lint/Missing Super errors
I've added `super` to all components inheriting from ViewComponent::Base
I've added `super(classes: classes, html_attributes: html_attributes)` to all components inheriting from GovukComponent::Base
=> [489] Rubocop Todo: Add super to View components

.rubocop_todo.yml, app/controllers/api/v2/providers_controller.rb, app/models/course.rb
Clear up of Rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
Renaming methods to comply with linter
=> [489] Rubocop ToDo: Rename Accessor Methods

app/services/access_request_approval_service.rb, spec/factories/access_requests.rb, spec/requests/api/v2/access_request_spec.rb, spec/services/access_request_approval_service_spec.rb
- [https://trello.com/c/lj1OmlYF/467-part-5-stop-writing-user-permissions-to-organisationusers](This trello ticket)
- Change AccessRequest to only write to UserPermission
=> [467] Change AccessRequest to only write UserPermission

app/controllers/support/courses_controller.rb, app/forms/support/edit_course_form.rb, app/models/course.rb, app/views/support/courses/edit.html.erb, spec/features/support/providers/courses/editing_a_course_spec.rb, spec/forms/edit_course_form_spec.rb, spec/support/page_objects/support/provider/course_edit_page.rb
- [This trello ticket](https://trello.com/c/3QK8OQMI/500-allow-application-open-date-to-be-editable-in-the-support-console)
- Allow support users to input a application form start date input in the SC
- Edit course details form to take dynamic date values to cut down code overhead
=> [500] Add application_open_from in the edit course form

.rubocop.yml, app/helpers/signin_helper.rb, app/views/sign_in/_default_signin_content.html.erb, app/views/sign_in/_migration_signin_content.html.erb, app/views/sign_in/index.html.erb, config/settings.yml, config/settings/qa.yml, spec/features/auth/provider_user_signs_in_spec.rb, spec/support/feature_flags.rb
- https://trello.com/c/i4t2NzH7/395-update-sign-in-page-copy-on-ttapi
- Add some new content for users coming in from old publish who need to re-authenticate
- Put the above behind a flag which is only enabled during the migration
This depends on the PRs in this ticket getting merged in to properly test https://trello.com/c/6Ay3bdEp/515-add-breadcrumbs-helper-for-migrated-publish-code.
=> [395] Add new sign in content for old publish sign in flow

app/helpers/publish_helper.rb, app/views/publish_interface/providers/about.html.erb, app/views/publish_interface/providers/contacts/edit.html.erb, app/views/publish_interface/providers/visas/edit.html.erb, spec/helpers/publish_helper_spec.rb
https://trello.com/c/6Ay3bdEp/515-add-breadcrumbs-helper-for-migrated-publish-code
Create a helper for generating return links to old publish for migrated sections
Head to https://teacher-training-api-pr-2394.london.cloudapps.digital/publish/organisations/2AT/2022/details (sign in as colin) and click on any of change links, the back link at the top should return you to old publish
=> [515] Create helper to generate old publish link for migration

app/lib/publish_constraint.rb, config/routes.rb, config/settings/production.yml, config/settings/qa.yml, config/settings/sandbox.yml, config/settings/staging.yml
- https://trello.com/c/JuEEOo28/544-root-path-needs-to-serve-new-publish-app-instance-and-not-api-docs
- Add a routing constraint to redirect root path to new publish and not api docs if the request url matches a new publish domain
=> [544] Set root path to redirect to new publish

app/views/publish_interface/providers/details.html.erb, config/routes.rb, spec/support/page_objects/publish_interface/provider_visa_sponsorships.rb
https://trello.com/c/GLxf53cm/566-fix-visa-routes-in-new-publish
The visa routes were setup to follow the restful resource style but they need to be changed to more manual get/post routes to be backwards compatible with old publish
=> [566] Fix visa paths

app/controllers/support/courses_controller.rb, app/forms/support/edit_course_form.rb, app/views/support/courses/edit.html.erb, spec/factories/courses.rb, spec/features/support/providers/courses/editing_a_course_spec.rb, spec/forms/edit_course_form_spec.rb, spec/support/page_objects/support/provider/course_edit_page.rb
- [This trello ticket](https://trello.com/c/6mK3z3TA/535-include-send-option-in-course-info-on-the-support-console)
- Add is_send? option on the support console on the course edit form
- Log in as Colin on the SC
- Navigate to providers
- Navigate to courses
- Select a course and edit it
- See the changes on the course form
=> [535] Add is_send to the course edit form on Support Console

app/controllers/publish_interface/providers_controller.rb, app/forms/publish_interface/about_your_organisation_form.rb, app/views/publish_interface/providers/about.html.erb
`BaseProviderForm` should be used instead
Refactor about your organisation to use BaseProviderForm
Removed unneeded `page` params
Just a refactor, have a play around.
=> [0509] Refactor about your organisation to use BaseProviderForm

app/controllers/publish_interface/providers_controller.rb, app/controllers/publish_interface/publish_interface_controller.rb, spec/features/publish_interface/edit_provider_details_spec.rb
The original Trello card called for better authorization specs. I looked at a few different ways of doing this and settled on a different approach to help ensure we're authorizing access correctly.
https://trello.com/c/nb8N8Hk3
Writing specs for each authorization case is time consuming and easily missed. Instead, use Pundit's built-in `verify_authorized` method in the PublishInterfaceController as an `after_action`. This raises an error if we forget to call authorize in any action. If we don't need authorization (eg—static content linked from the footer, cc: @defong ), we can call `skip_authorization`.
Paired with a very light feature spec, this should give us enough certainty that we're authorizing correctly, without the ongoing need to keep our specs up to date.
- Suitable approach?
=> Verify authorization in PublishInterface

app/controllers/publish_interface/providers/locations_controller.rb, app/helpers/location_helper.rb, app/helpers/provider_helper.rb, app/models/site.rb, app/views/publish_interface/providers/locations/_location.html.erb, app/views/publish_interface/providers/locations/index.html.erb, app/views/publish_interface/providers/visas/edit.html.erb, config/routes.rb, spec/features/publish_interface/managing_locations_spec.rb, spec/support/feature_helpers/publish_interface_pages.rb, spec/support/page_objects/publish_interface/provider_locations_index.rb
- https://trello.com/c/giOu9OOk/576-migrate-locations-locations-list
- Migrate over locations index page from the locations section here https://qa.publish-teacher-training-courses.service.gov.uk/organisations/2GU/2022
- Editing/Adding a location in a follow up ticket
- Clean up redundant visa routes
`publish/organisations/2AT/2022/locations`
=> [576] Migrate the publish locations index

terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/staging.tfvars
QA and Staging alerts are currently routed to StatusCake Contact group BAT-DevOps-Slack-All which only forwards to email.
The contact group will be changed to BAT-DevOps-Slack-Prod which will be routed to Slack, email and mobile alerts instead of just email. Email and mobile alerts are a limited subset of users. Updated contact groups in workspace variable files for qa and staging to match production and sandbox.
https://trello.com/c/q3F2WvuS
Do the channels match the expected channels.
=> Update StatusCake contact groups

app/components/header/style.scss
- [This trello ticket](https://trello.com/c/4hQyThZV/623-bug-spacing-issue-on-the-header-of-ttapi-publish)
- Spacing issue fix
=> [623] Set padding left to 0

terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf
Service binding is causing interruption in database connection after deployment as new service binding replaces old. 
Replacing with service key that defines a persistent set of credentials.
https://trello.com/c/LAQXxy4y/2042-site-reliability-engineering-issue
Ensure database connection still works in review app
=> Replaced service binding with service key

Gemfile.lock
1.9.0 seems to have disappeared from RubyGems. Not currently clear why.
=> Update i18n gem, 1.9.0 -> 1.9.1

app/controllers/publish_interface/providers/access_requests_controller.rb, app/forms/publish_interface/access_request_form.rb, app/policies/access_request_policy.rb, app/views/publish_interface/providers/access_requests/new.html.erb, config/locales/en.yml, config/routes.rb, spec/features/publish_interface/creating_request_access.rb, spec/features/publish_interface/viewing_provider_users.rb, spec/policies/access_request_policy_spec.rb, spec/support/feature_helpers/publish_interface_pages.rb, spec/support/page_objects/publish_interface/provider_users.rb, spec/support/page_objects/publish_interface/request_access_new.rb, spec/support/page_objects/sections/errorlink.rb
Users section request access form
Migrate users section request access form
There's one change in behaviour needed here — rather than redirect to the provider show page after form submission (which is what Old Publish does currently), let's redirect to the users index page.
Start from
`https://teacher-training-api-pr-2477.london.cloudapps.digital/publish/organisations/{provider_code}/users`
=> [0580] Migrate users section request access form

.rubocop.yml, app/controllers/publish_interface/providers/courses/vacancies_controller.rb, app/controllers/publish_interface/providers/courses_controller.rb, app/decorators/application_decorator.rb, app/decorators/course_decorator.rb, app/helpers/view_helper.rb, app/models/course.rb, app/models/provider.rb, app/services/courses/fetch.rb, app/views/publish_interface/providers/courses/_course_abilities_blurb.html.erb, app/views/publish_interface/providers/courses/_course_table.html.erb, app/views/publish_interface/providers/courses/_course_table_row.html.erb, app/views/publish_interface/providers/courses/index.html.erb, app/webpacker/styles/_table.scss, app/webpacker/styles/application.scss, config/routes.rb, config/settings.yml, config/settings/production.yml, config/settings/qa.yml, config/settings/review.yml, config/settings/sandbox.yml, config/settings/staging.yml, spec/decorators/course_decorator_spec.rb, spec/features/publish_interface/viewing_courses_spec.rb, spec/support/feature_helpers/publish_interface_pages.rb, spec/support/page_objects/publish_interface/provider_courses_index.rb
- https://trello.com/c/T5fMViQB/591-migrate-courses-courses-index-page
- Migrate the courses index page to new publish
- Bring over supporting code and fix where things are broken
https://teacher-training-api-pr-2460.london.cloudapps.digital/publish/organisations/2AT/2022/courses
Assert the current list of courses (and information) matches the same view in old publish.
Note: Course adding/editing (and vacancies editing) will be handled in upcoming tickets
I've also temporarily disabled a couple of Rubocop rules in two methods as they'll probably require refactoring which is outside the scope of this ticket/work. We'll remove these and sort out post migration.
=> [591] Implement the courses index page

config/analytics.yml, lib/tasks/big_query.rake
- https://trello.com/c/YO6vJnOA/638-get-courseenrichment-attributes-into-big-query-for-publish
- Add course_enrichment model to the analytics list
- Update rake task to allow importing individual tables, eg:
```ruby
bundle exec rails big_query:send_import_events["course_enrichment, course"]
```
=> Send course enrichment data to big query

docs/support_playbook.md
Update support playbook with info on how to un-publish a course that's been "accidentally" published
=> Update support playbook with un-publishing a course

app/controllers/publish_interface/providers/courses/vacancies_controller.rb, app/forms/publish_interface/course_vacancies_form.rb, app/helpers/vacancy_helper.rb, app/models/course.rb, app/services/vacancy_status_determination_service.rb, app/views/publish_interface/providers/courses/vacancies/_multiple_sites.html.erb, app/views/publish_interface/providers/courses/vacancies/_single_site.html.erb, app/views/publish_interface/providers/courses/vacancies/_site_status_checkbox.html.erb, app/views/publish_interface/providers/courses/vacancies/edit.html.erb, config/rubocop/naming.yml, spec/factories/courses.rb, spec/features/publish_interface/editing_vacancies_spec.rb, spec/helpers/vacancy_helper_spec.rb, spec/services/vacancy_status_determination_service_spec.rb, spec/support/feature_helpers/course_steps.rb, spec/support/feature_helpers/publish_interface_pages.rb, spec/support/features.rb, spec/support/page_objects/publish_interface/course_vacancies_edit.rb, spec/support/page_objects/sections/errorlink.rb, spec/support/page_objects/sections/vacancy.rb
- https://trello.com/c/OC8lv6IK/593-migrate-courses-edit-vacancies
- Refactor and simplify entire editing vacancies flow
- Use govuk formbuilder for views over manual markup
- Move logic over to form object pattern
- Increase test coverage with feature spec
Edit vacancies for a course with one site https://teacher-training-api-pr-2490.london.cloudapps.digital/publish/organisations/2AT/2022/courses
Edit vacancies for a course with a site and multiple study modes https://teacher-training-api-pr-2490.london.cloudapps.digital/publish/organisations/2EZ/2022/courses (33PY)
Edit vacancies for a course with multiple sites https://teacher-training-api-pr-2490.london.cloudapps.digital/publish/organisations/2CJ/2022/courses (M444)
=> [593] Migrate and rework the entire vacancies editing functionality

config/routes.rb
API constraint should take precedence. Tested on QA and works.
=> Update ordering of routes so constraint takes effect

app/components/flash_banner/view.html.erb, app/components/flash_banner/view.rb, app/controllers/publish/providers_controller.rb, app/controllers/publish/publish_controller.rb, spec/components/flash_banner/view_preview.rb
Cross cutting flash
There are cross cutting messages that is displayed when the intended user action can not be commerced as prior data input is required.
Go to 
https://teacher-training-api-pr-2520.london.cloudapps.digital/publish/organisations/B1T/2022/details
then you will be redirected to 
https://teacher-training-api-pr-2520.london.cloudapps.digital/publish/organisations/B1T/2022/contacts
=> [0698] Added missing cross cutting flash

.github/workflows/build-nocache.yml, .github/workflows/build.yml, Makefile, docker-compose.yml, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf
Containers for this repo are currently published to Dockerhub. Publishing images to GitHub container registry is simpler and more secure.
This commit migrates workflows from Dockerhub to the GitHub Container Packages registry.
- Confirm that image is being published as a GitHub Container Package
- Confirm that deployment is using the correct GitHub Container Package
https://trello.com/c/wVT0QcJ4
=> Migrate to GitHub container registry

app/components/notification_banner/view.rb, app/controllers/publish/courses/sites_controller.rb, app/forms/publish/course_location_form.rb, app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/show.html.erb, app/views/publish/courses/sites/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/publish/courses/editing_course_locations_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/course_location_edit.rb
- https://trello.com/c/ZNQzq1dZ/621-migrate-courses-course-show-page-updating-locations
- Port over and simplify locations selection logic for the course
- Refactor markup to use govuk form builder
- Add test coverage with feature spec
Original implementation here: https://qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2022/courses/AK12/locations
Ported version: https://teacher-training-api-pr-2526.london.cloudapps.digital/publish/organisations/2AT/2022/courses/AK12/locations
Check:
- You can update locations
- Error message is triggered if you try to remove all locations
FYI the full address is shown in the hint for the location in new publish which includes the location name but is excluded in old publish. Not sure which is right, @mbocc or Adam to confirm?
=> [621] Port over locations editing from course page

.github/workflows/smoke-test.yml, .tool-versions, Dockerfile, Gemfile, Gemfile.lock, docs/.tool-versions, docs/Gemfile, docs/Gemfile.lock, package.json
https://trello.com/c/RjLvJulr/744-update-docker-base-image
This is to resolve security vulnerabilities in the base image
alpine, ruby and nodejs will be updated in this change
ruby:2.7.4-alpine3.12 to ruby:2.7.5-alpine3.15
nodejs 12.18.3 to 16.14.0
ruby 2.7.4p191 to ruby 2.7.5p203
check locally
check review app
=> Update docker base image to ruby:2.7.5-alpine3.15

.github/workflows/build-nocache.yml
Fix Github Container Registry login for the build-no-cache workflow.
Alter workflow to use GHCR secrets instead of Dockerhub
Workflow has been run against branch
=> Fix GHCR login for build-no-cache workflow

app/models/course.rb
- https://trello.com/c/fHcLxzsC/754-remove-organisation
We've got a couple of orgs which need to be deleted in prod but fail to be discarded as the logic is only checking `ucas_status` is new. 
Updating logic to also check for `ucas_status == :not_running` so orgs who wish to be deleted and have no running courses can.
Tested with the latest prod dump locally on the orgs who couldn't be removed in prod.
=> [754] Check for new and not running ucas_status when discarding

app/components/degree_row_content_component/view.html.erb, app/controllers/publish/courses/degrees/grade_controller.rb, app/controllers/publish/courses/degrees/start_controller.rb, app/controllers/publish/courses/degrees/subject_requirements_controller.rb, app/forms/publish/degree_grade_form.rb, app/forms/publish/degree_start_form.rb, app/forms/publish/subject_requirement_form.rb, app/models/course.rb, app/views/publish/courses/_description_content.html.erb, app/views/publish/courses/degrees/grade/edit.html.erb, app/views/publish/courses/degrees/start/edit.html.erb, app/views/publish/courses/degrees/subject_requirements/edit.html.erb, config/routes.rb, spec/components/degree_row_content_component/view_preview.rb, spec/components/degree_row_content_component/view_spec.rb, spec/features/publish/courses/editing_degree_requirements_spec.rb, spec/models/course_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/degree_grade.rb, spec/support/page_objects/publish/degree_start.rb, spec/support/page_objects/publish/degree_subject_requirement.rb
- https://trello.com/c/cEGtwmt0/596-migrate-courses-course-show-page-edit-requirements-eligibility-degree
- Port over the degree editing logic within the course show page
- Increase test coverage for this flow
The form objects need to be refactored to follow our pattern. Some of the controller redirect logic can be simplified after cleaning up the forms. As this is mostly a lift and shift from old publish have marked these as TODOs.
Original implementation here: https://qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2022/courses/AK12/degrees/start
migrated version: https://teacher-training-api-pr-2553.london.cloudapps.digital/publish/organisations/2AT/2022/courses/AK12 (click change)
Check:
You can update the degree requirements with:
- classification required
- …
=> [596] Port over degree requirements flow

app/components/gcse_preview_component/view.html.erb, app/components/gcse_row_content_component/view.html.erb, app/controllers/publish/courses/gcse_requirements_controller.rb, app/forms/publish/gcse_requirements_form.rb, app/views/publish/courses/_description_content.html.erb, app/views/publish/courses/gcse_requirements/edit.html.erb, config/routes.rb, spec/components/gcse_row_content_component/view_preview.rb, spec/components/gcse_row_content_component/view_spec.rb, spec/features/publish/courses/gcse_equivalency_spec.rb, spec/forms/publish/gcse_requirements_form_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/courses/gcse_requirements_page.rb
GCSE
Migrated GCSE 
It works
ie
Original implementations
https://qa.publish-teacher-training-courses.service.gov.uk/organisations/D87/2022/courses/2F24/gcses-pending-or-equivalency-tests
vs
Migrated implementations
https://teacher-training-api-pr-2564.london.cloudapps.digital/publish/organisations/D87/2022/courses/2F24/gcses-pending-or-equivalency-tests
The changes is reflected on the course details page as well as the course preview page
Out of scope 
`Copy content from another course`
=> [0597] Migrate  GCSEs and equivalency tests 

app/models/concerns/publish/course_basic_detail_concern.rb, app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/outcome/_form_fields.html.erb, app/views/publish/courses/outcome/edit.html.erb, config/routes.rb, spec/features/publish/courses/editing_course_outcome_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/courses/outcome_edit_page.rb, spec/support/page_objects/sections/qualification.rb
- https://trello.com/c/smfqS9tO/619-migrate-courses-course-show-page-updating-outcome
- Port over the course outcome editing flow from the course page
- Improve test coverage
Original implementation here: https://qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2022/courses/AK12/details (click update Outcome)
migrated version: https://teacher-training-api-pr-2566.london.cloudapps.digital/publish/organisations/2AT/2022/courses/AK12/details (click update Outcome)
Check:
You can update the course outcome.
=> [619] Port over outcome editing for course

app/controllers/publish/courses/withdrawals_controller.rb, app/controllers/publish/publish_controller.rb, app/controllers/publish/users_controller.rb, app/forms/publish/course_withdrawal_form.rb, app/views/publish/courses/_description_status_panel.html.erb, app/views/publish/courses/withdrawals/edit.html.erb, app/views/publish/providers/access_requests/new.html.erb, app/webpacker/styles/_link.scss, app/webpacker/styles/application.scss, config/locales/en.yml, config/routes.rb, spec/features/publish/courses/withdrawing_a_course_spec.rb, spec/features/publish/editing_vacancies_spec.rb, spec/support/feature_helpers/course_steps.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/courses/withdrawal_page.rb
- https://trello.com/c/QXTXwmQX/616-migrate-courses-course-show-page-status-sidebar-withdrawing
- Port the course withdrawal flow
- Refactor markup to use govuk formbuilder
- Refactor original code to use form object pattern
- Increase test coverage
Original implementation here: https://qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2022/courses/3CXB (click withdraw this course)
migrated version:  https://teacher-training-api-pr-2574.london.cloudapps.digital/publish/organisations/2AT/2022/courses/3CXB (click the same link above)
Check:
You can withdraw the course.
=> [616] Port the withdrawing courses flow

.github/actions/deploy/action.yml, .github/workflows/build-and-deploy.yml, .github/workflows/delete-review-app.yml, .github/workflows/deploy.yml
The bobheadxi/deployments GitHub Action is used to update deployment statuses, this is ineffective when deploying to persistent environments such as qa or prod.
This change removes that action from non-review app deployment workflows and uses the built in functionality instead.
Review apps continue to use the bobheadxi/deployments action.
- Check that the [environments page](https://github.com/DFE-Digital/teacher-training-api/deployments) is updated as expected including correct View Deployment link
- Check that delete-review-app workflow functions as expected
=> Use job environment to update deployment status

app/controllers/publish/courses/deletions_controller.rb, app/forms/publish/course_deletion_form.rb, app/policies/provider_policy.rb, app/views/publish/courses/_description_status_panel.html.erb, app/views/publish/courses/deletions/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/publish/courses/deleting_a_course_spec.rb, spec/features/publish/courses/withdrawing_a_course_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/courses/delete_page.rb, spec/support/page_objects/publish/courses/withdrawal_page.rb, spec/support/page_objects/sections/status_sidebar.rb
- https://trello.com/c/E7R3KM6v/828-migrate-courses-course-show-page-status-sidebar-deleting
- Port the course deletion flow
- Refactor markup to use govuk formbuilder
- Refactor original code to use form object pattern
- Increase test coverage
Original implementation here: https://qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2022/courses/3CXB (click delete this course)
migrated version:  
Check:
You can delete the course and it no longer appears on the course index page
=> [828] Port course deletion flow

.github/actions/deploy/action.yml, .github/actions/smoke-test/action.yml, .github/workflows/smoke-test.yml
The smoke tests are mainly ran using workflow dispatch from the build workflow. This makes the logs harder to follow and rerunning failed checks harder.
https://trello.com/c/D6tyzjoj
This change refactors the workflow as a reusable action.
The `softprops/turnstyle` step has been removed, instead we rely on concurrency at the workflow level to prevent multiple tests running against the same environment (though with the current smoke tests only hitting the healthcheck endpoint this shouldn't be a concern at present).
- Check that smoke tests run as expected when:
- running as part of the `deploy_review` job
- deploying to an environment, eg QA, using the `deploy` workflow
- running manually using the `smoke-test` workflow against an environment, eg QA, and a review app
=> Refactor smoke test workflow as a reusable action

.github/workflows/build-and-deploy.yml, .github/workflows/build-nocache.yml
Dependabot has been granted permissions to push to the GitHub Container Registry so there is no longer a requirement to skip container related steps in the build.
Run all container related steps for Dependabot triggered build workflow runs.
- Check review app is deploying
=> Removed dependabot conditions in build workflows

app/controllers/publish/courses/modern_languages_controller.rb, app/controllers/publish/courses/subjects_controller.rb, app/forms/publish/base_course_form.rb, app/forms/publish/course_location_form.rb, app/forms/publish/course_subjects_form.rb, app/forms/publish/course_vacancies_form.rb, app/forms/publish/course_withdrawal_form.rb, config/locales/en.yml, spec/features/publish/courses/editing_modern_languages_spec.rb, spec/forms/publish/base_course_form_spec.rb, spec/forms/publish/course_location_form_spec.rb, spec/forms/publish/course_subjects_form_spec.rb, spec/forms/publish/course_vacancies_form_spec.rb, spec/forms/publish/course_withdrawal_form_spec.rb
Migrate notifications logic
Migrated notifications logic for
- `NotificationService::CourseSitesUpdated`
- `NotificationService::CourseSubjectsUpdated`
- `NotificationService::CourseUpdated`
- `NotificationService::CourseVacanciesUpdated`
- `NotificationService::CourseWithdrawn`
An email for one of the above is sent whenever a change has been made to the related fields
Embedded it on the forms as well as some general tidy up.
- `NotificationService::CoursePublished` is covered elsewhere
=> [0803] Migrate notifications logic for when courses are changed

app/controllers/publish/training_providers/courses_controller.rb, app/controllers/publish/training_providers_controller.rb, app/views/publish/courses/_course_table.html.erb, app/views/publish/training_providers/courses/index.html.erb, app/views/publish/training_providers/index.html.erb, config/routes.rb, spec/features/publish/viewing_training_providers_and_their_courses_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/training_provider_index.rb, spec/support/page_objects/publish/training_providers/course_index.rb, spec/support/page_objects/sections/training_provider.rb
Also migrates their courses
- https://trello.com/c/fiQ1HxwQ/836-migrate-the-courses-as-an-accredited-body-section
- Migrate the training providers page
- Migrate the courses list for each training provider
Export to CSV is handled in a separate ticket
Original implementation - https://qa.publish-teacher-training-courses.service.gov.uk/organisations/B25/2022/training-providers
Migrated version - https://teacher-training-api-pr-2593.london.cloudapps.digital/publish/organisations/B25/2022/training-providers
Check that the training provider list for the accredited provider from old publish matches the same on new publish (and their courses)
=> [836] Migrate the training providers list

app/controllers/api_controller.rb, app/controllers/application_controller.rb
:shipit: 
Get rids of 
`DEPRECATION WARNING: 'include Pundit' is deprecated. Please use 'include Pundit::Authorization' instead.`
=> [xxxx] Fixed punit warnings

app/controllers/publish/providers/allocations_controller.rb, app/view_objects/allocations_view.rb, app/views/publish/providers/allocations/allocation_report/_confirmed_state.html.erb, app/views/publish/providers/allocations/allocation_request/_confirmed_state.html.erb, app/views/publish/providers/allocations/index.html.erb, config/routes.rb, config/settings.yml, docs/allocations.md, spec/features/publish/allocations/view_allocation_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/allocations/allocations_page.rb, spec/view_objects/allocations_view_spec.rb
PE allocations section confirmed state
Migrate the PE allocations section confirmed state
This is `confirmed state`, one of 3 states.
https://teacher-training-api-pr-2597.london.cloudapps.digital/publish/organisations/24P/2022/allocations
vs
https://qa.publish-teacher-training-courses.service.gov.uk/organisations/24P/2022/allocations
https://teacher-training-api-pr-2597.london.cloudapps.digital/publish/organisations/S17/2022/allocations
vs
https://qa.publish-teacher-training-courses.service.gov.uk/organisations/S17/2022/allocations
=> [854] Migrate the PE allocations section confirmed state

.github/workflows/build-and-deploy.yml
Currently the deploy-all matrix job has a concurrency group to prevent concurrent deployments.  Observed behaviour is that each job within the matrix is treated as a separate job rather all the jobs in the matrix being treated as a single element.  This results in prod deployments occurring after earlier environments have been skipped.
- Switch to workflow concurrency to ensure that only 1 `deploy-all` job can run at any one time but that all jobs in that matrix are executed in order
- Retain job concurrency for deploy and delete of review app to prevent the delete job running at the same time as the review app deployment
- The concurrency groups have been tested in a [sandbox repo](https://github.com/NickGraham101/actions-sandbox)
https://trello.com/c/zCmvKchC
=> Use workflow concurrency for build and deploy

.github/workflows/deploy.yml
Deploy workflow can run at the same time as the Build and Deploy workflow potentially creating conflicting deployments.
Add concurrency to prevent workflows running at the same time.
=> Add concurency to the deploy workflows

Gemfile, Gemfile.lock
Reverts DFE-Digital/teacher-training-api#2610
=> Revert "Bump omniauth from 1.9.1 to 2.1.0"

app/controllers/publish/publish_controller.rb, app/controllers/publish/rollover_controller.rb, app/helpers/recruitment_cycle_helper.rb, app/models/user.rb, app/views/publish/rollover/new.html.erb, config/routes.rb, spec/features/publish/accepting_rollover_spec.rb, spec/models/user_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/rollover.rb
- https://trello.com/c/EvjQZECF/876-migrate-the-interruption-pages-rollover
- Rework and simplify the rollover interruption screen logic
- Drives logic from the `InterruptPageAcknowledgement` rather than storing acceptance in session
- Changing the cycle year will naturally trigger the interruption for the next cycle (providing flag is also turned on)
=> [876] Port over rollover interruption screen

app/controllers/publish/publish_controller.rb, app/controllers/publish/rollover_controller.rb, app/controllers/publish/rollover_recruitment_controller.rb, app/controllers/publish/terms_controller.rb, app/models/user.rb, app/views/publish/rollover_recruitment/new.html.erb, config/routes.rb, config/settings.yml, spec/features/publish/accepting_rollover_recruitment_spec.rb, spec/features/publish/accepting_rollover_spec.rb, spec/features/publish/accepting_terms_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/rollover_recruitment.rb
https://trello.com/c/dypIiSV0/877-migrate-the-interruption-pages-rollover-recruitment
Similar to https://github.com/DFE-Digital/teacher-training-api/pull/2613 but for the rollover recruitment interruption screen.
=> [877] Port the rollover recruitment interruption screen

.github/actions/deploy/action.yml, .github/workflows/build-and-deploy.yml, .github/workflows/delete-review-app.yml, .github/workflows/deploy.yml
A GitHub environment is created for each review app that is deployed, this environment persists after the review app is deleted.
- Removed unneeded references to `API_TOKEN_FOR_GITHUB_ACTION` secret, this is now only used for the step below
- Add a step to the delete-review-app workflow to delete the environment
- Close PR to test delete process, reopen PR once tested
https://trello.com/c/ybnYhCK3
=> Delete GitHub environment

app/controllers/publish/courses/accredited_body_controller.rb, app/controllers/publish/courses/applications_open_controller.rb, app/views/publish/courses/accredited_body/search_new.html.erb
https://trello.com/c/orO2PVAV/904-fix-wrong-search-path
Fixes this Sentry error https://sentry.io/organizations/dfe-teacher-services/issues/3210660165/?environment=production&project=1377944&query=is%3Aunresolved
Create a new course under this provider https://teacher-training-api-pr-2621.london.cloudapps.digital/publish/organisations/5E4/2022/courses (should allow you to search for an accredited body successfully)
=> [904] Fix accredited body search step

app/forms/publish/course_location_form.rb
https://trello.com/c/GQZV3WRF/909-issue-with-locations-l142-1fn
When locations are selected in the course's locations edit view, the `site_ids` are assigned to the course but their corresponding `site_statuses` records are set to the defaults `{ status: :new_status, published: :unpublished }` and don't appear in the course's vacancies list as it only queries running sites. 
This change fixes by marking the site statuses attributes for the chosen site ids correctly.
If you view this course's locations https://teacher-training-api-pr-2622.london.cloudapps.digital/publish/organisations/1FN/2022/courses/L142/details, Queen Elizabeth's Grammar School will be listed but not appear in the vacancies list: https://teacher-training-api-pr-2622.london.cloudapps.digital/publish/organisations/1FN/2022/ …
=> [909] Mark site and site status relationship correctly

app/components/header/view.html.erb, app/components/header/view.rb, app/controllers/publish/notifications_controller.rb, app/forms/publish/notification_form.rb, app/view_objects/notifications_view.rb, app/views/publish/notifications/index.html.erb, config/routes.rb, spec/components/header/view_spec.rb, spec/features/publish/editing_notification_preference_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/page_objects/publish/header.rb, spec/support/page_objects/publish/notification.rb, spec/view_objects/notifications_view_spec.rb
- https://trello.com/c/g71F5Ssn/568-migrate-the-notifications-page
- Migrate and refactor the notifications preference page
- Sign in as one of the accrediting body personas
- Click notifications link
- Update notifications
Original implementation: https://qa.publish-teacher-training-courses.service.gov.uk/notifications
=> [568] Migrate the notifications page

Makefile, bin/download-nightly-backup, bin/restore-nightly-backup, docs/disaster-recovery.md, docs/maintenance-mode.md, service_unavailable_page/web/nginx.conf
A DR process is required to handle a lost of the database instance.
https://trello.com/c/eh8Tgmu9
- Add a DR process to docs and supporting make recipe and scripts to execute it
- Document the maintenance page process
- Modify the maintenance page process to return a more appropriate response for API requests
Ensure the process meets the requirements in [technical guidance](https://technical-guidance.education.gov.uk/infrastructure/disaster-recovery/#loss-of-database-instance).
=> Add disaster recovery docs

Makefile, docs/disaster-recovery.md, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf
A DR process is required to handle a data corruption.
https://trello.com/c/wx5ad9MF
- Extend the DR documentation to cover data corruption scenario
- Add make recipes to execute process and modify terraform template to support this process
- The code block in [this section](https://github.com/DFE-Digital/teacher-training-api/blob/add-data-corruption-dr-process/docs/disaster-recovery.md#restore-postgres-database-instance) has been tested against QA.  You can repeat this test after checking with #twd_publish_tech
=> Add data corruption to DR docs

docs/support_playbook.md
- https://trello.com/c/7DTRabhQ/846-notification-email-investigate-on-by-default
We've been manually adding a user to a provider but not handling the notification preferences. I've tested the `UserAssociationService::Create` and it seems to do the job. 
Update support playbook to show how to correctly link a user to provider.
=> [846] Update support playbook for attaching user to provider

app/services/providers/copy_to_recruitment_cycle_service.rb, spec/services/providers/copy_to_recruitment_cycle_service_spec.rb
At rollover we create new provider records. Now that we've updated the user permissions model, we need to ensure that permissions are correctly sustained across cycles.
Update the relevant rollover code to re-create or update user_permissions records so that they point to the new provider records.
Add users to the new rolled over providers in `copy_to_recuitment_cycle_service.rb`
=> 458  Update rollover code so that user permissions are correctly maintained across cycles

config/application.rb
Cookie name vs cookie page
Amended cookie name so it aligns with the one that is stated on the cookie page
Have a nibble of the :cookie:
=> [0942] Amended cookie name

app/helpers/breadcrumb_helper.rb, app/models/user.rb, app/views/publish/courses/details.html.erb, app/views/publish/courses/index.html.erb, app/views/publish/courses/show.html.erb, app/views/publish/providers/allocations/allocation_request/_closed_state.html.erb, app/views/publish/providers/allocations/allocation_request/_confirmed_state.html.erb, app/views/publish/providers/allocations/allocation_request/_open_state.html.erb, app/views/publish/providers/details.html.erb, app/views/publish/providers/locations/edit.html.erb, app/views/publish/providers/locations/index.html.erb, app/views/publish/providers/locations/new.html.erb, app/views/publish/providers/show.html.erb, app/views/publish/training_providers/courses/index.html.erb, app/views/publish/training_providers/index.html.erb, app/views/publish/users/index.html.erb
- https://trello.com/c/NEORiD07/954-enable-breadcrumbs-on-new-publish
- Make the breadcrumbs work for the same pages in old publish
https://teacher-training-api-pr-2652.london.cloudapps.digital/
Login as Mary and click around different sections
=> [954] Fix breadcrumbs in new publish

.github/workflows/database-restore.yml, .gitignore, .tool-versions, Makefile, bin/download-nightly-backup, bin/restore-nightly-backup, docs/disaster-recovery.md
Demoing the DR process to the publish team identified some refinements and fixes that could be made to the DR process.
https://trello.com/c/wx5ad9MF
- Remove dependency on output from one script to execute another, this maintains compatibility across Linux distributions
- Replaces `grep` with `awk` to maintain compatibility across Linux distributions
- Fixed incorrect file permissions introduced by WSL
- The solution was developed on a Windows machine running Ubuntu 20 in WSL.  It should tested on MacOS ideally or another distribution.  A minimal test would be:
- execute the `deploy-plan` command documented in [recreate-the-lost-postgres-database-instance](https://github.com/DFE-Digital/teacher-training-api/blob/dr-doc-refinements/docs/disaster-recovery.md#recreate-the-lost-postgres-databa …
=> Dr doc refinements

app/models/course_enrichment.rb
Removing this comment as there isn't an equivalent validation in the form object.
=> Remove redundant comment

terraform/workspace_variables/rollover.tfvars.json
Rollover env requires larger app memory 
Increase from 1.5G to 3G
Deployed manually
=> Increase rollover app memory to 3G

app/views/publish/courses/preview/_about_the_provider.html.erb, app/views/publish/courses/preview/_international_students.html.erb, app/views/publish/users/index.html.erb
Fixes the following issues in Sentry:
- https://sentry.io/organizations/dfe-teacher-services/issues/3288687517/?project=1377944&query=is%3Aunresolved
- https://sentry.io/organizations/dfe-teacher-services/issues/3286015081/?project=1377944&query=is%3Aunresolved
- Page title missing in provider Users page
=> [74] Fix broken links in preview page

spec/models/course_spec.rb, spec/requests/api/v2/users/generate_and_send_magic_link_spec.rb, spec/serializers/api/v2/serializable_course_spec.rb, spec/serializers/api/v2/serializable_subject_spec.rb, spec/serializers/api/v3/serializable_course_spec.rb
There are some pending specs in the codebase. These add additional noise (both in files and in test output). They mainly look redundant, so we are removing these.
=> 48 remove or fix pending specs

app/views/layouts/application.html.erb, config/settings.yml, config/settings/review.yml
As a follow up from #2668 where the new navigation bar is created and #2679 where the organisation switcher is implemented. This PR removes the breadcrumbs if the `new_publish_navigation` feature flag is activated, as those are now redundant.
- Review app is deployed with the flag on. Compare with prototype.
=> Remove breadcrumbs

.github/workflows/build-and-deploy.yml
rollover will be deployed manually from deploy workflow,
and not automatically on merge to master
remove from env list in build-and-deploy deploy-all step
Check yaml
Confirm rollover not updated on merge
=> Remove rollover deploy from merge to master

app/components/title_bar/script.js, app/components/title_bar/style.scss, app/components/title_bar/view.html.erb, app/components/title_bar/view.rb, app/models/user.rb, app/views/layouts/application.html.erb, config/locales/en.yml, config/settings.yml, spec/components/title_bar/view_preview.rb, spec/components/title_bar/view_spec.rb, spec/features/publish/providers_index_without_new_publish_navigation_spec.rb, spec/features/publish/providers_show_without_new_publish_navigation_spec.rb
Following on from #2668, this PR adds a `Change organisation` button for providers who have multiple orgs.
- Add dynamic view component 
-  Render component if: current user exists, feature flag enabled, user org count greater than 1, provider not nil, not on a support page
- Add view preview page
- Duplicate tests and mark old file as ready to delete once feature flag removed
- Login as a multi org user and ensure you can change orgs using the new link on any page
- Repeat for a non multi org user and ensure you cannot
- Repeat for any of the support pages and ensure you cannot
=> 61 new nav org switcher

.tool-versions
When setting up the repo, the `asdf` config had trouble when trying to find the `az` plugin. It looks like this exists under the name `azure-cli` instead, where `az` is just the command line term to start azure stuff. 
I've been able to install and run the whole `.tool-versions` file with `asdf` at this point
=> Update asdf config for azure-cli

app/controllers/publish/publish_controller.rb, app/views/publish/recruitment_cycles/_provider_info.html.erb
- https://trello.com/c/4FjAdm3P/81-next-cycle-about-your-organisation-page-showing-current-cycle-instead
- https://trello.com/c/xcg5ZtMx/80-publish-next-cycle-2023-to-2024-is-broken-due-to-allocations
Fixes the snags listed above.
[80] - Remove allocations link for next cycle as it's going away
[81] - RecruitmentCycle year can be set under `params[:year]` for locations view so we need to check for that too
=> [80 & 81] A couple of rollover snags

app/controllers/publish/access_requests_controller.rb, app/helpers/user_helper.rb, app/policies/access_request_policy.rb, app/views/layouts/_footer.html.erb, app/views/publish/access_requests/_access_request.html.erb, app/views/publish/access_requests/confirm.html.erb, app/views/publish/access_requests/index.html.erb, app/views/publish/access_requests/inform_publisher.html.erb, config/routes.rb, config/settings.yml, spec/features/support/access_requests/managing_requests_spec.rb, spec/serializers/api/v3/serializable_course_spec.rb, spec/support/feature_helpers/publish_pages.rb, spec/support/feature_helpers/support_pages.rb, spec/support/page_objects/publish/footer.rb, spec/support/page_objects/support/access_requests/confirm.rb, spec/support/page_objects/support/access_requests/index.rb
- https://trello.com/c/cbHZEGfy/67-migrate-access-requests-section
- Migrate the access requests index/confirm/delete functionality from the old support tool
- Sign in as a non admin persona and request access for a user
- Sign out and sign back in as an admin persona and view access requests (link in the footer should be visible)
- Assert you can view the request, assert you can approve/delete the request
=> [67] Migrate the access requests section

docs/rollover.md
The rollover period
Added a sequence diagram to depict the whole before and after rollover period. 
Amended with more details towards the whole rollover period.
Perform this locally and use time machine **wisely**
```bash
bundle exec rake 'rollover:create_recruitment_cycle[2023, "2022-10-14", "2023-09-30"]'
bundle exec rake rollover:providers
```
Have `find` setup
=> [0050] Amended the rollover documentations

app/decorators/course_decorator.rb, app/services/courses/copy_to_provider_service.rb, spec/services/courses/copy_to_provider_service_spec.rb
- https://trello.com/c/YSy4Ef3g/85-application-start-date-is-causing-issues
Some courses can have their `applications_open_from_date` less than the next cycle's applications start date. This PR handles this scenario by adjusting them to the next cycle's date.
Also (perhaps controversially) I've introduced two new settings to keep track of the next cycle's applications start/end date. These dates seem to be floated around internally across conversations but it might be a good idea to have them concretely defined in the application. The tradeoff is another a pair of properties to change each time rollover comes around but i think it's worth it to catch & handle edge cases like the above. 
Also fixed another issue when creating a course with a method missing in the course decorator.
- This …
=> [85] Application start date is causing issues

app/components/header/style.scss, app/components/header/view.html.erb, app/components/navigation_bar/view.html.erb, app/components/navigation_bar/view.rb, app/components/phase_banner/script.js, app/components/phase_banner/style.scss, app/components/phase_banner/view.html.erb, app/components/phase_banner/view.rb, app/components/title_bar/view.html.erb, app/controllers/publish/providers/access_requests_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, app/views/publish/shared/_navigation_bar_with_training_partners.html.erb, config/settings/qa.yml, spec/components/phase_banner/view_spec.rb
A few small tweaks in preparation for switching on the new navigation.
Note that when this is merged the app-header line will cover the full page width. This is not behind a feature flag. 
- Extend app-header line to cover full page width
- Grey background spans full viewport width
- Reduce spacing between change org link and primary nav bar
Only display the phase banner border:
- If there is a current user
- if the current user is not an admin
- if the current user is associated with more than one provider
- Recommend reviewing commit by commit 
- Take a look at the nav bar and change org link as a multi org user, single org user and accredited body 
- Do the same for the phase banner border
- Compare and contrast with the prototype
=> 108 css tweaks to and around the nav bar

.github/PULL_REQUEST_TEMPLATE.md, .github/actions/deploy/action.yml, .github/workflows/build-and-deploy.yml, .github/workflows/delete-review-app.yml, Makefile, README.md, docker-compose.yml, spec/README.md
We want to use `main` not `master`, this will bring us in line with the other BAT repos.
Replace all incidences of `master` in actions and `Makefile` with `main`.
Once this is in, we'll need to tell GitHub `main` is the primary branch: https://github.com/github/renaming
Removing a non existent GitHub link while we are here. 
Have I missed anything?
=> 117 replace master with main

app/helpers/provider_helper.rb, app/views/publish/courses/subjects/new.html.erb, config/settings.yml
We no longer require the google forms for PE as recruitment is now uncapped.
- Remove PE google form links from yml
- Remove PE google form links from create course flow
- Remove PE course google form url helper method
- Create a PE course and ensure there is no sign of the google forms. 
- Have I missed anything?
=> 99 pe courses for next cycle

docs/lib/govuk_tech_docs/open_api/renderer.rb
Api docs `text` is wrong
Removed unneeded assignment
=> [0028] Api docs `text` is wrong

app/forms/publish/notification_form.rb, app/models/course.rb, app/models/user_notification_preferences.rb, app/services/courses/copy_to_provider_service.rb, app/services/sites/copy_to_provider_service.rb, docs/lib/govuk_tech_docs/open_api/renderer.rb
We don't need to `return nil`, `return` implicitly returns nil.
- Remove all instances of `return nil` in the codebase and replace with just `return`
=> Remove pointless return nils

app/decorators/course_decorator.rb, spec/decorators/course_decorator_spec.rb
The vacancies ‘Edit’ link should be called ‘Change’
- Change link text from `Edit` to `Change`
- Fix tests
- Inspect the change links on the courses page. Ensure it still has the visually hidden text (course name and course code)
- 🚢
=> Change vacancy link text

app/views/publish/courses/index.html.erb, spec/support/page_objects/publish/provider_courses_index.rb
We have two `Add a new course` buttons by design if there are more than 10 courses, one at the top and one at the bottom. 
- Remove the one at the bottom 
- Rename the one at the top to: `Add course`
=> Remove duplicate add course button

app/controllers/personas_controller.rb
These are already conditionally handled in the routes, i don't think we should be wrapping the controller behind similar logic as it causes an issue with Zeitwerk
```
/usr/local/bundle/gems/zeitwerk-2.5.4/lib/zeitwerk/loader/callbacks.rb:25:in `on_file_autoloaded': expected file /app/app/controllers/personas_controller.rb to define constant PersonasController, but didn't (Zeitwerk::NameError)
```
=> [xxx] Fix zeitwerk error

Makefile, bin/backup-review-database, bin/upload-review-backup, docs/disaster-recovery.md
Add content to document backup of review database when testing against a review environment.
Improve the testing process for a review environment by aligning it more closely with non-review environments. This includes creating a database backup and uploading it to a storage account so the same scripts can be used for review as with non-review environments.
=> Add review database backup content

app/controllers/concerns/authentication.rb, app/views/sign_in/_default_signin_content.html.erb, spec/features/auth/persona_spec.rb
`/support` leads us to support login. For personas (on qa and dev environments) we have 3 personas that are not eligible to login. These personas are for publish, not support. 
- Render the button to Login as an Admin (Colin) if the user is going to `/support`
- Add support to params and dynamically render true or false, based on the path and use this as the check for which button to render.
- Keep the previous journey if the user is going to Publish
- This change will only be applied to persona login
- Login to support, and ensure that you don't see any non eligible personas to login with.
- Login to Publish and ensure that the original persona login journey remains the same.
=> Remove provider personas when going to support

.bundle/config, .github/workflows/build-and-deploy.yml, .github/workflows/build-nocache.yml, Makefile, README.md, config/initializers/sentry.rb, docker-compose.yml, docs/adr/0004-before-action-variables.md, docs/adr/0008-use-skylight-for-performance-monitoring.md, docs/config/tech-docs.yml
Rename github ttapi repo to publish-teacher-training
update code references for github repo and ghcr images
check build
=> Rename github ttapi repo to publish

config/initializers/new_framework_defaults_7_0.rb
As part of the Rails 7 upgrade, we've had to turn off this setting:
[new_framework_defaults_7_0.rb](https://github.com/DFE-Digital/teacher-training-api/blob/main/config/initializers/new_framework_defaults_7_0.rb#L13)
As it causes some tests to fail, particularly around this service:
[creator_service.rb](https://github.com/DFE-Digital/teacher-training-api/blob/main/app/services/subjects/creator_service.rb#L2)
It needs to also handle it's belongs_to relationship (subject area) as this is now validated by default by Rails.
Fix the service above to also handle setting the subject area
Maybe it can be combined with this? [subject_area_creator_service.rb](https://github.com/DFE-Digital/teacher-training-api/blob/main/app/services/subjects/subject_area_creator_service.rb) …
=> # 157 Fix belongs to in fixture creation

app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
https://sentry.io/organizations/dfe-teacher-services/issues/3356685335/?project=1377944&query=url%3A%22https%3A%2F%2Fapi.publish-teacher-training-courses.service.gov.uk%2Fapi%2Fpublic%2Fv1%2Frecruitment_cycles%2F2022%2Fcourses%22
https://sentry.io/organizations/dfe-teacher-services/issues/3356643413/?project=1377944&query=url%3A%22https%3A%2F%2Fapi.publish-teacher-training-courses.service.gov.uk%2Fapi%2Fpublic%2Fv1%2Frecruitment_cycles%2F2022%2Fcourses%22
## What was supposed to happen? 
No error on split
## Technical notes
Make a guard
sentry or @defong 
The error seems to result from invalid data being passed from FIND, possibly deliberate, not able to replicate locally yet.
As the split method requires a string, have placed a guard clause in both failing methods, will continue to look …
=> #188 undefined split bug

app/controllers/cookie_preferences_controller.rb, app/forms/publish/cookie_preferences_form.rb, app/views/cookie_preferences/show.html.erb, config/locales/en.yml, config/routes.rb, config/settings.yml, config/settings/review.yml, spec/features/publish/cookie_preferences_spec.rb, spec/requests/send_data_to_big_query_spec.rb, spec/support/page_objects/publish/cookie_preferences.rb
- https://trello.com/c/f02CRcnk/181-publish-cookie-preference-form
- Implements cookie preference form on the cookies page
- Put behind feature flag
- Head to the cookies page and update your preferences, assert cookie is set in the browser
=> [181] Cookie preference form

.github/actions/deploy/action.yml, .github/workflows/delete-review-app.yml, .tool-versions, terraform/.terraform.lock.hcl, terraform/modules/statuscake/providers.tf, terraform/terraform.tf
Part of migration path to 1.2.3 is updating to 0.14.11 to prepare the tfstate file. This upgrade is to improve compatibility and maintainability.
- Upgrade to 0.14.11 of Terraform
- If you work with Terraform locally, please ensure you are using the correct version. This PR is for 0.14.11
=> Upgrade Terraform to 0.14.11

.github/actions/deploy/action.yml, .github/workflows/delete-review-app.yml, .tool-versions, terraform/.terraform.lock.hcl, terraform/terraform.tf
Final phase in upgrading the Terraform version of publish from 0.13.5 to 1.2.3. Previously updated to 0.14.11.
- Upgrade to 1.2.3 of Terraform
- If you work with Terraform locally, please ensure you are using the correct version. This PR is for 1.2.3
=> Update Terraform to 1.2.3

.gitignore, app/services/courses/copy_to_provider_service.rb, app/services/providers/copy_to_recruitment_cycle_service.rb, app/services/rollover_provider_service.rb, app/services/rollover_service.rb, lib/tasks/rollover.rake, spec/services/courses/copy_to_provider_service_spec.rb, spec/services/providers/copy_to_recruitment_cycle_service_spec.rb, spec/services/rollover_provider_service_spec.rb, spec/services/rollover_service_spec.rb
Rollover script to handle draft and individual courses
Refactor rollover script to handle draft and individual courses
```bash
bundle exec rake 'rollover:provider[provider_code, course_code1 course_code2 course_code3, true]'
```
Go and create a recruitment cycle for next recruitment cycle
Find some providers with none published courses
And take a lucky dip with the below commands
```bash
bundle exec rake 'rollover:provider[provider_code, , ]'
bundle exec rake 'rollover:provider[provider_code, ,false]'
```
To rollover a `rollover-able provider` and all it `rollover-able courses`
```bash
bundle exec rake 'rollover:provider[provider_code, course_codes , ]'
bundle exec rake 'rollover:provider[provider_code, course_codes, false]'
```
To rollover a `rollover-able provider` and only the …
=> [0189] Refactor rollover script to handle draft and individual courses

.github/workflows/database-restore.yml, Makefile, terraform/workspace_variables/loadtest.tfvars.json, terraform/workspace_variables/loadtest_backend.tfvars, terraform/workspace_variables/production.tfvars.json, terraform/workspace_variables/production_backend.tfvars, terraform/workspace_variables/qa.tfvars.json, terraform/workspace_variables/qa_backend.tfvars, terraform/workspace_variables/review.tfvars.json, terraform/workspace_variables/review_backend.tfvars, terraform/workspace_variables/rollover.tfvars.json, terraform/workspace_variables/rollover_backend.tfvars, terraform/workspace_variables/sandbox.tfvars.json, terraform/workspace_variables/sandbox_backend.tfvars, terraform/workspace_variables/staging.tfvars.json, terraform/workspace_variables/staging_backend.tfvars
Rename Azure resources from TTAPI to PUBLISH 
This affects Key Vaults and Storage Accounts used by build, deployment and database backups.
https://trello.com/c/U6UMBm0d/622-rename-ttapi-azure-resources-to-publish
Update Makefile, workspace variables and the database restore workflow.
Key vault data has been copied from TTAPI to Publish vaults
Terraform state files have been copied from TTAPI to Publish storage accounts
DB backups have been copied from TTAPI to Publish storage accounts
Any updated terraform state files or key vaults will be copied just before merge
Github secrets that reference state files will be updated just before merge
Check config
deploy-plan all envs
=> Rename ttapi Azure resources to publish

app/views/cookie_preferences/show.html.erb, app/views/layouts/application.html.erb, config/settings.yml, config/settings/production.yml
https://trello.com/c/j9ZY7rii/180-publish-install-ga-tracking-script
- Enable the Google tag manager script if analytics have been accepted
- Only configure for prod as we don't have other envs in GA
We won't be able to verify data is coming in until this is turned on in prod. This is based on the spike integration which verified data being sent locally.
=> [180] Add Google tag manager script

Makefile, terraform/workspace_variables/production.tfvars.json, terraform/workspace_variables/qa.tfvars.json, terraform/workspace_variables/sandbox.tfvars.json, terraform/workspace_variables/staging.tfvars.json
Remove env2 routes that were used for the publish to ttapi migration,
as they are no longer required.
https://trello.com/c/DKPhYzRh/624-publish-remove-env2-routes
Remove env2 from publish_gov_uk_host_names workspace variable for each env
Update Makefile for maintenance enable/disable 
deploy-plan each env
=> Remove env2 routes

app/components/title_bar/view.html.erb, app/components/title_bar/view.rb, app/controllers/publish/providers_controller.rb, app/helpers/application_helper.rb, app/helpers/provider_helper.rb, app/helpers/title_bar_helper.rb, app/views/layouts/application.html.erb, app/views/publish/providers/_provider.html.erb, spec/components/title_bar/view_spec.rb, spec/features/publish/providers_index_spec.rb, spec/features/publish/providers_index_without_new_publish_navigation_spec.rb
The rollover switcher was shipped recently, there are a few bits to address which surfaced from a product review.
- Ensure the line below the phase banner appears when it should
- Rework the organisations page
- Increase number of items before pagination to 30
- Remove courses count
Check and confirm the changes above.
=> 218 rollover switcher feedback

Makefile
The -P command has been found to be incompatible on Mac OS. Updating to use awk.
=> Update the get-image-tag recipe

app/views/publish/courses/_basic_details_tab.html.erb
Fixing the spacing between the Academic year spacing on the course basic details page
The left is before and the right is after.
=> Fix spacing for academic year

app/controllers/sessions_controller.rb, app/controllers/support/support_controller.rb, spec/controllers/sessions_controller_spec.rb, spec/features/auth/provider_user_signs_in_spec.rb
Users should not see admin error
Present a forbidden page if user is not an admin instead of redirecting to sign in when they are signed in
Removed the flash, as it presents information without boundary
Redirect to the publish root path as that is really what the user wants to go to
You need DfE Sign in to reproduce the original isses
=> [0243] Users should not see admin error

app/assets/stylesheets/components/_title-bar.scss, app/components/title_bar/view.html.erb, app/components/title_bar/view.rb
Add separator in between the title bar items, when there are multiple items and a small refactor.
=> Refactor and add separator to title bar items

app/decorators/course_decorator.rb, app/views/publish/courses/_description_content.html.erb, config/locales/en.yml, spec/decorators/course_decorator_spec.rb, spec/factories/subjects/secondary_subjects.rb, spec/features/publish/viewing_a_course_spec.rb, spec/support/page_objects/publish/provider_courses_show.rb
https://trello.com/c/hiRC3Z1m/233-surface-financial-incentives-on-course-page
Design history - https://bat-design-history.netlify.app/publish-teacher-training-courses/showing-financial-support-from-the-government/
- Surfaces financial incentive detail for courses on the course show page
- Shows relevant details for the following scenarios:
- Financial incentive is not available for the course
- Financial incentive is available (scholarship and bursary, as well as just bursary option)
- Financial incentive isn't available yet (during rollover/transition into next cycle)
Login as Mary and view the following courses https://publish-teacher-training-pr-2828.london.cloudapps.digital/publish/organisations/1ZN/2022/courses:
No incentive available course - …
=> [233] Surface financial incentives on course page

app/views/publish/access_requests/confirm.html.erb
This uses the new scope on `user.providers` to return providers in current cycle for the access request confirm page, preventing duplicates from being shown.
=> [xxx] Render correct list of providers for access request confirm

app/models/provider.rb, app/models/user.rb, app/services/user_associations_service/create.rb, spec/models/user_spec.rb, spec/services/user_associations_service/create_spec.rb, spec/services/user_associations_service/delete_spec.rb
This is a bug that prevents users from getting the correct access when granting access using the UserAssociationService. This is because the UserAssociationService doesn't consider rollover, when there are two cycles. 
- Update the UserAssociationsService to handle adding users to two cycles when rollover is active.
- Update the UserAssociationsService to handle removing users from both cycles when rollover is active.
- Add a user using the UserAssociationService
- Ensure the user is added to both cycles
- Repeat for removing a user
=> Attach users to both cycles

app/controllers/support/providers/users_check_controller.rb, app/controllers/support/providers/users_controller.rb, app/forms/form.rb, app/forms/support/user_form.rb, app/services/user_store.rb, app/views/support/providers/users/check.html.erb, app/views/support/providers/users/delete.html.erb, app/views/support/providers/users/index.html.erb, app/views/support/providers/users/new.html.erb, app/views/support/providers/users/show.html.erb, app/views/support/providers/users_check/show.html.erb, config/initializers/redis.rb, config/locales/en.yml, config/routes.rb, spec/features/support/providers/users/adding_user_to_provider_spec.rb, spec/forms/support/user_form_spec.rb, spec/services/user_store_spec.rb, spec/support/page_objects/support/provider/user/users_check.rb, spec/support/page_objects/support/provider/user/users_new.rb
Introducing a feature for user support admins to create Publish users and associate them with specific organisations. The users will also be sent an email, with the link and inviting them to sign up to DfE Sign in, if they haven't already. The email is being implemented in #2835. 
- Create new views, routes, controllers and form.
- Store changes in redis when submitting the form and going to the check page.
- Update the database with the changes stored in redis on submission of the check page.
- Values in the form are persisted if you cancel or go back from the check page. If you have accidently gone to the wrong provider, when you go to the correct one the form will be prefilled.
- Utilise the `UserAssociationService`.
- If the user does not exist on Publish, create the user and …
=> 229 add user to org via support

app/views/publish/courses/course_button_panel/_unpublished.html.erb, app/views/publish/courses/course_button_panel/_withdrawn.html.erb, spec/features/publish/viewing_a_course_spec.rb, spec/support/page_objects/sections/course_button_panel.rb
When we moved the course actions from the sidebar to below the course title, we didn't include 'Preview course'! We need to add it to empty, draft, rolled over and withdrawn courses
Added link to unpublished and withdrawn partials
Link should appear on empty, draft, rolled over and withdrawn courses only. I note the back button on the preview pages directs to the index view
=> #325 add preview link to unpublished and withdrawn

app/controllers/support/providers/users_controller.rb, app/views/support/providers/users/edit.html.erb, app/views/support/providers/users/show.html.erb, config/locales/en.yml, config/routes.rb, spec/features/support/providers/editing_a_user_from_a_provider_spec.rb, spec/support/page_objects/support/provider_user_edit.rb, spec/support/page_objects/support/provider_user_show.rb
Adding the edit provider user journey in line with #2839, #2838 and #2844.
Create a view, controller action and feature test
Compare and contrast with the prototype.
=> Add edit provider user journey

app/controllers/concerns/copy_course_content.rb, app/services/courses/fetch.rb, spec/services/courses/fetch_spec.rb
https://trello.com/c/JKvoMiv7/316-bug-copying-course-content-only-copies-from-current-cycle
When copying content for a course, it is now scoped to a course that runs in the same recruitment cycle as the course being copied to. 
Trying copying course content across from courses from the same provider, but changing the recruitment cycle - changes to the current recruitment cycle's course content will not be copyable to the next recruitment cycle's courses. 
We don't really seem to have any tests for this, I'm not entirely sure where to start introducing them either!
=> Add recruitment cycle scope to course fetch

terraform/workspace_variables/production.tfvars.json, terraform/workspace_variables/qa.tfvars.json, terraform/workspace_variables/rollover.tfvars.json, terraform/workspace_variables/sandbox.tfvars.json, terraform/workspace_variables/staging.tfvars.json
Remove the StatusCake alerts before creating them again with the new StatusCake Terraform provider.
=> Remove StatusCake alerts

app/components/filters/view.rb, app/controllers/support/users_controller.rb, app/views/layouts/user_record.html.erb, app/views/support/_menu.html.erb, app/views/support/users/_users.html.erb, app/views/support/users/edit.html.erb, app/views/support/users/index.html.erb, app/views/support/users/new.html.erb, app/views/support/users/show.html.erb, config/routes.rb, spec/features/support/filters/user_filters_spec.rb, spec/features/support/users/creating_a_new_user_spec.rb, spec/features/support/users/deleting_a_user_spec.rb, spec/features/support/users/deleting_user_from_provider_spec.rb, spec/features/support/users/editing_a_user_spec.rb, spec/features/support/users/users_list_spec.rb, spec/support/page_objects/support/user_edit.rb, spec/support/page_objects/support/user_new.rb, spec/support/page_objects/support/user_show.rb, spec/support/page_objects/support/user_show_providers.rb, spec/support/page_objects/support/users_index.rb
Support agents require the ability to update information for both cycles, to do this we need to scope the support routes based on the recruitment cycle. 
This PR deals with `support_users`
(#2878 deals with `support_allocations` #2864 deals with `support_providers`)
Add the `recruitment_cycle` to the url for `support_users`. For example:
from: `/support/users`
to: `/support/{recruitment_cycle_year}/users`
Does everything still work as intended? Have a play around on the review app.
=> Scope routes based on recruitment cycle users list

Gemfile, Gemfile.lock
Reverts DFE-Digital/publish-teacher-training#2880
It caused this 
https://sentry.io/organizations/dfe-teacher-services/issues/3463629585/?referrer=slack
=> Revert "Bump dfe-analytics from v1.2.1 to v1.3.0"

app/components/allocation_record_card/view.html.erb, app/components/allocation_record_card/view.rb, app/components/filters/view.rb, app/controllers/support/allocation_uplifts_controller.rb, app/controllers/support/allocations_controller.rb, app/views/support/_menu.html.erb, app/views/support/allocation_uplifts/edit.html.erb, app/views/support/allocation_uplifts/new.html.erb, app/views/support/allocations/index.html.erb, app/views/support/allocations/show.html.erb, config/routes.rb, spec/components/allocation_record_card/view_preview.rb, spec/components/allocation_record_card/view_spec.rb, spec/features/support/allocations/allocation_uplift_edit_spec.rb, spec/features/support/allocations/allocation_uplift_new_spec.rb, spec/features/support/allocations/allocations_list_spec.rb, spec/features/support/allocations/allocations_show_spec.rb, spec/features/support/filters/allocation_filter_spec.rb, spec/support/page_objects/support/allocation_uplift_edit.rb, spec/support/page_objects/support/allocation_uplift_new.rb, spec/support/page_objects/support/allocations_index.rb, spec/support/page_objects/support/allocations_show.rb
Support agents require the ability to update information for both cycles, to do this we need to scope the support routes based on the recruitment cycle. 
This PR deals with `support_allocations`
(#2864 deals with `support_providers` #2867 deals with `support_users`)
Add the `recruitment_cycle` to the url for `support_allocations`. For example:
from: `support/allocations/{allocation_id}`
to: `/support/{recruitment_cycle_year}/allocations/{allocation_id}`
Does everything still work as intended? Have a play around on the review app.
=> Scope routes based on recruitment cycle allocations

app/components/support_title_bar/view.html.erb, app/components/support_title_bar/view.rb, app/controllers/support/recruitment_cycle_controller.rb, app/views/layouts/application.html.erb, app/views/support/recruitment_cycle/index.html.erb, config/routes.rb, spec/components/support_title_bar/view_preview.rb, spec/components/support_title_bar/view_spec.rb, spec/features/support/switching_between_recruitment_cycles_spec.rb, spec/support/page_objects/support/recruitment_cycle_index.rb
As we have now finished scoping the recruitment cycle year to the params in support, we need a way for support users to easily switch between cycles. 
We have a switcher in the app, we are building something similar for support users.
- Implement the cycle switcher html page for support
- Show the html page when switching between cycles
- Add the cycle switcher in the title bar in line with the prototype
=> 342 add cycle switcher to support console

app/components/header/view.html.erb, spec/features/support/switching_between_recruitment_cycles_spec.rb
A test for an unhappy path and a fix for a blue support link
- Add test sad path test for rollover inactive (which tests that we arrive at providers page and not the cycles page)
- Stop support link being blue on the support cycles page
- I've deployed the review app - have a look and ensure the support console link in the header is no longer blue on the support cycles page.
=> Add sad path test and fix blue support link in header

Gemfile
This allows us to send the correct IPs to the analytics platform.
=> load cloudfront-rails in envs that use CloudFront

app/views/support/recruitment_cycle/index.html.erb, config/locales/en.yml
Adding a title to the recruitment cycle support page in line with the prototype
=> Add support recruitment cycle page title

app/services/user_associations_service/create.rb, spec/services/user_associations_service/create_spec.rb
Now that we have added the cycle switcher to support, it feels wrong to add the user to both cycles in one go
- Remove the logic that used to handle this
=> Only add users to the cycle you are in

app/views/support/_menu.html.erb, spec/features/support/switching_between_recruitment_cycles_spec.rb
Removing the PE Allocations tab from support in the next recruitment cycle as this is no longer required.
- Login to support in the current cycle, check that the PE allocations tab is present
- Repeat for the next cycle and ensure it is not present
=> Remove PE Allocations tab from support in the next recruitment cycle

app/decorators/application_decorator.rb, app/models/course.rb, spec/features/publish/viewing_a_course_spec.rb, spec/models/course_spec.rb, spec/support/page_objects/publish/provider_courses_index.rb
This is the beginning of a piece of work to improve course labels. This PR only makes surface level UI changes. Downstream systems can continue to rely on the internal states `published`.
- Split the `Published` label into `Open` and `Closed`
- Only display `OPEN` if the course `has_vacancies?` other wise display `CLOSED` 
- In the next cycle display `SCHEDULED` for courses that will be published when Find opens 
- Colour changes to these statuses
- Apply the same logic to the `Applications` column on the course table, i.e `Open` if there are vacancies and `Closed` if there isn't.
- Log into the prototype, have a look at a course with vacancies, change to no vacancies, look at the new labels and watch the Applications column update. 
- Perhaps the status tags logic can be refactored in a …
=> Implement open closed status labels for courses

Dockerfile
https://github.com/DFE-Digital/publish-teacher-training/pull/2907 was raised to fix CVE-2022-37434 however the r2 package has been removed and replaced by r3. This caused errors when referencing r2 so we need to ensure the reference is updated to use r3.
=> Update zlib to r3

terraform/modules/paas/data.tf, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/qa.tfvars.json
https://trello.com/c/bzTV1UDE/377-create-2https-wwwfind-postgraduate-teacher-trainingservicegovuk-domains
Create qa2.find-postgraduate-teacher-training.service.gov.uk route for find migration to publish
Add terraform resources for new route
Add find_gov_uk_host_names variable to qa.tfvars.json to create new route
(DNS and CDN will be completed afterwards)
deploy-plan
=> Create qa2.find route for find migration to publish

app/decorators/course_decorator.rb, app/views/publish/courses/_course_table.html.erb, config/settings.yml
We have decided to change the `Will it be on Find?` column on the courses table in the next cycle to match the one in the current cycle, which is `Is it on Find?`. 
This change was made so that users can switch between cycles and be able to see at a glance what is on Find as that is the header they would be used to seeing all year. 
- Change the `next_cycle_open_date` in `Settings.yml` to `2022-10-4`
- Change the `Will it be on Find?` header in the courses cycle to match what is displayed in the current cycle.
- Change the value in that column so that it makes sense in the new context
- Our recruitment cycle year is displaying incorrectly in the course creation flow. I've updated that too.  
The main thing that concerns me here is changing the date in `Settings.yml`. Is this change OK to …
=> Change heading and column content for will it be on find next recruitment cycle

app/lib/find_constraint.rb, config/routes.rb, config/settings/loadtest.yml, config/settings/production.yml, config/settings/qa.yml, config/settings/rollover.yml, config/settings/sandbox.yml, config/settings/staging.yml, spec/lib/find_constraint_spec.rb
domain constraint for the new find url
Add a domain constraint for the new find url
it redirects to `/find`
=> [380] Add a domain constraint for the new find url

.github/workflows/database-restore.yml
setup-cf-cli was moved from bat-infrastructure to github-actions
Need to update the database backup workflow as the restore step is currently failing
Update workflow to point to correct location
Check correct syntax
=> Update setup-cf-cli location in db backup workflow

app/javascript/find/application.js, app/views/layouts/_add_js_enabled_class_to_body.html.erb, app/views/layouts/application.html.erb, app/views/layouts/find_layout.html.erb
missing js-enabled class
Fixed missing js-enabled class
=> [xxxx] Fixed missing js-enabled class

app/serializers/api/public/v1/serializable_course.rb, app/services/courses/content_status_service.rb, spec/models/course/publish_enrichments_spec.rb, spec/services/courses/content_status_service_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml, swagger/public_v1/component_schemas/CourseFilter.yml, swagger/public_v1/component_schemas/ProviderAttributes.yml
https://trello.com/c/HzBaBvhu/407-update-course-status-send-via-the-api
- Streamlines course state values sent via the API. Keeps the logic in the service the same as some of the values are still relevant in our system
- Update api docs
=> [407] Streamline course state values in API

app/deserializers/api/v3/deserializable_course.rb, app/serializers/api/public/v1/serializable_course.rb, app/serializers/api/v3/serializable_course.rb, docs/source/release-notes.html.md.erb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/requests/api/v3/providers/courses/index_spec.rb, spec/requests/api/v3/providers/courses/show_spec.rb, spec/serializers/api/public/v1/serializable_course_spec.rb, spec/serializers/api/v3/serializable_course_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml
https://trello.com/c/9LZletSa/436-expose-new-course-visa-fields-via-the-api
- Expose new fields in serializers for V3 and Public API
- Document fields in API
- Query the api, assert new fields are exposed
- Fire up the docs locally and assert they're documented
=> [436] Expose new course visa fields via the api

app/components/find_interface/courses/apply_component/view.html.erb
Preview does not require the real apply link. This caused an error on the channel.
- https://sentry.io/organizations/dfe-teacher-services/issues/3562352360/?project=1377944&referrer=slack
- Navigate to a course on preview
- Click the Apply link
- Ensure you do not get an error
=> Fix Apply link on preview

app/services/courses/copy.rb, app/services/courses/copy_to_provider_service.rb, spec/services/courses/copy_to_provider_service_spec.rb
To simplify collecting visa information from providers, we're updating how and which providers provide their visa sponsorship information via their provider details page and when they create courses
Add visa fields to CopyToProviderService
Not sure if this is exactly correct, we have visa fields on both the course and provider, are we transitioning from one to the other?
=> #440 Update course copy service in Publish to handle visa fields

app/models/course.rb, app/services/course_search_service.rb, spec/docs/courses_spec.rb, spec/docs/providers/courses_spec.rb, spec/factories/courses.rb, spec/models/course_spec.rb, spec/requests/api/v3/courses/index_spec.rb, spec/services/course_search_service_spec.rb, swagger/public_v1/component_schemas/CourseFilter.yml
https://trello.com/c/FqQN9KZt/439-update-visa-search-filter-on-find-api
- Refactors the visa filters to query the course record instead of provider
- Update/Fix specs
You can fire up Find locally and query for visa courses against the review app in this PR or hit the endpoint directly with postman
Linked to https://github.com/DFE-Digital/find-teacher-training/pull/1491
=> [439] Refactor visa filters to query courses

app/components/caption_text/view.html.erb, app/components/caption_text/view.rb, app/views/publish/courses/accredited_body/new.html.erb, app/views/publish/courses/age_range/new.html.erb, app/views/publish/courses/applications_open/new.html.erb, app/views/publish/courses/apprenticeship/new.html.erb, app/views/publish/courses/degrees/start/edit.html.erb, app/views/publish/courses/fee_or_salary/new.html.erb, app/views/publish/courses/level/new.html.erb, app/views/publish/courses/modern_languages/new.html.erb, app/views/publish/courses/outcome/edit.html.erb, app/views/publish/courses/outcome/new.html.erb, app/views/publish/courses/sites/edit.html.erb, app/views/publish/courses/sites/new.html.erb, app/views/publish/courses/skilled_worker_visa_sponsorship/edit.html.erb, app/views/publish/courses/skilled_worker_visa_sponsorship/new.html.erb, app/views/publish/courses/start_date/new.html.erb, app/views/publish/courses/student_visa_sponsorship/edit.html.erb, app/views/publish/courses/student_visa_sponsorship/new.html.erb, app/views/publish/courses/study_mode/edit.html.erb, app/views/publish/courses/study_mode/new.html.erb, app/views/publish/courses/subjects/_form_fields.html.erb, app/views/publish/courses/subjects/new.html.erb, config/locales/en.yml, spec/components/caption_text/view_preview.rb, spec/components/caption_text/view_spec.rb
We are introducing a "Add course" hint label at the top of all pages in the Add new course flow. 
- Create a reusable view component with the correct css.
- Utilise the view component for all the pages in the new course flow.
- Add view preview and specs.
- Have I missed any of the pages?
=> Introduce "Add course" label to the new course flow and add course name and code to edit course views

app/controllers/publish/courses/apprenticeship_controller.rb, app/controllers/publish/courses/fee_or_salary_controller.rb, app/controllers/publish/courses/funding_type_controller.rb, app/controllers/publish/courses/skilled_worker_visa_sponsorship_controller.rb, app/controllers/publish/courses/student_visa_sponsorship_controller.rb, app/helpers/publish/visa_sponsorship_helper.rb, app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/apprenticeship/edit.html.erb, app/views/publish/courses/skilled_worker_visa_sponsorship/edit.html.erb, app/views/publish/courses/student_visa_sponsorship/_form_fields.html.erb, app/views/publish/courses/student_visa_sponsorship/edit.html.erb, config/locales/en.yml, config/routes/publish.rb, spec/features/publish/courses/editing_apprenticeship_spec.rb, spec/features/publish/courses/editing_funding_type_spec.rb, spec/support/page_objects/publish/courses/apprenticeship_edit.rb
Editing of visa for an apprenticeship course
When the course apprenticeship setting is changed  then the related visa question are asked.
Applicable to changing to and from an apprenticeship  draft/rollover course
there is no reset ability (separate card)
=> [0435] Handle visa editing in course show page for Scitts and HEIs

app/views/publish/courses/apprenticeship/_form_fields.html.erb, app/views/publish/courses/apprenticeship/edit.html.erb, app/views/publish/courses/confirmation.html.erb, app/views/publish/courses/skilled_worker_visa_sponsorship/_form_fields.html.erb, app/views/publish/courses/skilled_worker_visa_sponsorship/edit.html.erb, app/views/publish/courses/student_visa_sponsorship/_form_fields.html.erb, app/views/publish/courses/student_visa_sponsorship/edit.html.erb
https://trello.com/c/NsdcnpPi/530-snag-fix-visa-link-for-scitts-heis
- Fix the learn more link for HEIs/SCITTs to match up with prototype
- A couple of UI tweaks to align with prototype
- Check add course/edit visa flows for scitts/heis visually matches up with prototype
=> [530] Fix learn more link for heis/scitts

config/analytics.yml, config/analytics_blocklist.yml, config/analytics_pii.yml
All provider facing services (Publish, Manage and Register) each have their own provider users in their services. There is currently no shared identifier across the services for provider users that is accessible for analytics. Therefore there isn't a method through BQ to see which provider users engage with each service.
With ITT reform changing how we onboard providers into TS, it's important for us to have a true reflection of provider users across the service.
- Register has a dfe_sign_in_uid in the users table which is not anonymised.
- Apply has a dfe_sign_in_uid in the provider_users and support_users tables which *is* anonymised 
- Publish has a sign_in_user_id in the user table which I've confirmed with @avinhurry matches the above IDs, but currently isn't streamed at all (it's in …
=> Stream anonymised DfE Sign-in user id to bigquery

app/controllers/publish/courses/sites_controller.rb, app/helpers/view_helper.rb, docs/support_playbook.md
We've got a support request which will involve copying courses from one provider to another. These courses will have no locations set. When providers try to publish they'll see an error (below) where the link is currently broken. This PR fixes it so it takes them to the correct section to complete.
=> [xxx] Fix broken locations error link

app/models/course.rb, config/analytics_blocklist.yml, config/initializers/course_enums.rb, db/migrate/20220928150349_add_campaign_name_to_course.rb, db/schema.rb, spec/models/course_spec.rb
Some courses are created as part of a campaign to improve recruitment. The Engineers Teach Physics course is part of such a campaign. It is ultimately just a physics course but it will need to have a different title as part of the campaign.
We'll need to build a new step in the course flow to allow providers to create these types of courses.
Add a new field on the course table campaign_name? this would be an enum field which could contain other campaigns in the future eg engineers_teach_physics
Write database migrations
Success
We should have a way of tracking these types of courses either by the field above or some other way
we should be able to do something like course.engineers_teach_physics? or course.has_campaign? etc
Db migration for enum campaign_name
Should …
=> #536 add campaign_name enum

app/controllers/publish/publish_controller.rb
Now that Rollover has ended, some users who still have the last cycle year in their session will see an error unless they clear their cookies. This PR will do it for them as a fallback.
Fixes https://sentry.io/organizations/dfe-teacher-services/issues/3642874340/?environment=production&project=1377944&query=is%3Aignored
=> [xxx] Clear last cycle year in session if we're not in rollover

app/models/application_record.rb
Remove noisy code
Removed noisy code
Removes all this noise
```
2022-10-04 17:13:56.765022 I [78742:6740] Rails -- DEPRECATION WARNING: DfE::Analytics::Entities was manually included in a model (AccessRequest), but it's included automatically since v1.4. You're running v1.5.1. To silence this warning, remove the include from model definitions in app/models.
2022-10-04 17:13:56.765181 I [78742:6740] Rails -- DEPRECATION WARNING: DfE::Analytics::Entities was manually included in a model (Allocation), but it's included automatically since v1.4. You're running v1.5.1. To silence this warning, remove the include from model definitions in app/models.
2022-10-04 17:13:56.765234 I [78742:6740] Rails -- DEPRECATION WARNING: DfE::Analytics::Entities was manually included in a model (Contact), but …
```
=> [xxxx] Removed noisy code

app/forms/publish/base_model_form.rb, app/forms/publish/course_study_mode_form.rb, spec/forms/publish/course_study_mode_form_spec.rb
Study modes affects the locations vac status
This fixes the location update issues whereby the study mode is changed and the existing locations is not updated leading to when the locations are then manipulated it errors out
See trello ticket
=> [0617] Fixed study mode cascading issues on locations updates

app/forms/publish/course_location_form.rb, spec/forms/publish/course_location_form_spec.rb
Withdrawn/draft courses
They become findable when adding a location
Only set site status as findable if the course is findable
Findable courses and findable site statues can only occur when they have been published.
publishinng function is the chokepoint as that is when it sets the course as findable
original code circumvented it
=> [0619] Fixed location issues

db/data/20221011111721_fix_incorrect_withdrawn_findable_courses.rb, db/data/20221011111730_fix_incorrect_draft_findable_courses.rb
https://trello.com/c/vPsLFM54/694-fix-courses-appearing-on-find-when-in-withdrawn-draft-via-migrations
We have had support tickets about withdrawn/draft courses appearing in Find. The issue is that the `site_statuses` for these courses have been marked to be findable. This PR introduces a couple of data migrations to make them unfindable.
- Get the latest snapshot.
- Check this provider who has a draft course which is findable `publish/organisations/179/2023/courses` `3C2J`
- Check it appears on Find locally
- Run data migrations `bundle exec rails data:migrate`
- Check course shouldn't appear on Find
=> [694] Fix findable courses which shouldn't be

.github/workflows/database-restore.yml
https://trello.com/c/sNdDNMXW/678-remove-bat-cf-and-db-github-secrets
The database backup/restore workflow references some Github secrets that are also maintained elsewhere
- cf user and pwd, changed to reference Azure keyvault values
- cf space, changed to reference workspace variables
- Storage account connection key, changed to reference Azure keyvault values
Update database-restore workflow
Check workflow
=> Move CF and DB github secrets to Azure keyvault

.github/actions/deploy/action.yml, .github/workflows/build-and-deploy.yml, .github/workflows/build-nocache.yml, .github/workflows/delete-review-app.yml
Dependabot is creating too many distracting PRs
Pin to the major version and let the workflow use the latest minor version
Check the workflow run
=> Remove GitHub action minor version pinning

app/controllers/publish/courses/engineers_teach_physics_controller.rb, spec/features/publish/courses/new_engineers_teach_physics_spec.rb
We need to add validations to the ETP step on the new course flow
Success
The page shows validation errors if the user tries to submit without selection an option
validate in continue action on new etp page
Start a new course flow, pick secondary, then physics. On ETP page leave options unchecked, click continue to see error message
=> fix etp new page

db/data/20221020110844_fix_vac_status_on_published_courses.rb
https://trello.com/c/c4qmSGgA/731-bug-vacancy-status-doesnt-match-study-mode-for-some-courses
We have an issue where some published courses have an inconsistent study mode to their location (site) statuses reported by the Apply team. We fixed the underlying issue and updated all courses except for published. This PR is to do that
- Data migration to fix published courses with a `full_time_or_part_time` study mode but a non equivalent for its location statuses.
=> [731] Fix published courses with inconsistent vac status

app/controllers/find/sitemaps_controller.rb, app/views/find/sitemaps/show.xml.builder, config/routes/find.rb, spec/requests/find/sitemaps_spec.rb
Sitemap for `find`
Added Sitemap for `find`
~Should it be prefix `/find`?~
No, the sitemap needs to match as it is in place replacement
=> [0575] Added sitemap setup for Find

app/controllers/publish/courses/subjects_controller.rb, app/views/publish/courses/engineers_teach_physics/_edit_form_fields.html.erb, app/views/publish/courses/engineers_teach_physics/_form_fields.html.erb, spec/features/publish/courses/editing_engineers_teach_physics_spec.rb, spec/features/publish/courses/new_engineers_teach_physics_spec.rb, spec/features/publish/courses/new_subject_spec.rb, spec/features/publish/e2e/new_course_spec.rb
We need to make sure we're resetting the campaign_name back to nil when a user changes from ETP to a different subject.
Handle this edge case where ever the subject is changed so that the field is set back to nil on the course
clear campaign_name params for new action and update course model in update action in subjects controller
Create new Physics course then change course from confirmation page, then change back to Physics course, ETP radio buttons should be blank. Do same with existing course from basics details page.
=> [735]reset campaign name when changing from ETP

app/components/find_interface/courses/entry_requirements_component/view.rb, app/decorators/course_decorator.rb, spec/components/find_interface/courses/entry_requirements_component/view_preview.rb, spec/components/find_interface/courses/entry_requirements_component/view_spec.rb, spec/decorators/course_decorator_spec.rb
Use subject name not course title for qualifications needed to satisfy entry requirements. (This has been done for the current Find [here](https://github.com/DFE-Digital/find-teacher-training/pull/1555)).
The reason for this change is because if support changes the course title, the sentence may not make sense to the candidate.
Added a new method for this to handle course with two subjects.
Added a new method for this to handle courses with two subjects.
- Find a course
- Check the name in this section: `course/{PROVIDER_CODE}/{COURSE_CODE}#section-entry`
- Change the name in support and check the correct subject names still appear. 
- Experiment with multiple subjects
=> Use subject name not course title for qualifications needed 

app/services/course_search_service.rb, spec/models/course_spec.rb
In line with the "Engineers teach physics" work, we are adding a filter on Find to search for only these courses. This filter will appear when searching for the "Physics" subject.
These are the backend changes, see https://github.com/DFE-Digital/find-teacher-training/pull/1567 for frontend. 
- Add scope which returns courses with the campaign_name "engineers_teach_physics"
- Add the scope to the course search service
- Checkout this branch along with the respective branch on Find, [here](https://github.com/DFE-Digital/find-teacher-training/pull/1567)
- Perform a search for a Physics course on Find
- Try out the new filter
=> Implement engineers teach physics filter on Find

.github/actions/deploy/action.yml
The set-output command is being deprecated soon.
Resolution is to use $GITHUB_OUTPUT as per the workflow commands docs.
Confirm updated workflows tested where possible:
https://trello.com/c/3s3iC7UV
=> Stop using set-output in check_sp workflow

app/deserializers/api/v3/deserializable_course.rb, app/serializers/api/public/v1/serializable_course.rb, app/serializers/api/v3/serializable_course.rb, docs/source/release-notes.html.md.erb, spec/controllers/api/public/v1/courses_controller_spec.rb, spec/docs/courses_spec.rb, spec/docs/providers/courses_spec.rb, spec/requests/api/v3/providers/courses/index_spec.rb, spec/requests/api/v3/providers/courses/show_spec.rb, spec/serializers/api/public/v1/serializable_course_spec.rb, spec/serializers/api/v3/serializable_course_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml
We added ETP as a new course step in the course flow on Publish. This is the PR to expose the `campaign_name` field powering this logic via the public API.
- Expose `campaign_name` field as an attribute on the public API
- Update docs
Create a Physics course with the `campaign_name`: `engineers_teach_physics` and check that you can view the campaign name on the public api: `http://localhost:3001/api/public/v1/recruitment_cycles/2023/providers/{provider_code}/courses/{course_code}`
Repeat for a course not in that campaign and ensure it is `null`
=> Expose campaign name field in api and docs

app/components/find_interface/courses/international_students_component/view.html.erb, app/components/find_interface/courses/international_students_component/view.rb, app/decorators/course_decorator.rb, app/views/publish/courses/_basic_details_tab.html.erb, config/locales/en.yml, spec/components/find_interface/courses/international_students_component/view_preview.rb, spec/components/find_interface/courses/international_students_component/view_spec.rb, spec/decorators/course_decorator_spec.rb
State the 3-year residency rule for apprenticeship courses.
- Change the `apprenticeship?` method to return true or false 
- Add a new `apprenticeship` method for the basic details page (previously using `apprenticeship?` which is semantically incorrect.
- Utilise this in the view component to render the 3-year text if the course is an apprenticeship
- Add the word `also` if the course is an apprenticeship (as there is content before this now).
- Add view preview
- Check `#section-international-students` for apprenticeship courses and ensure the new content is there and is correct.
- Repeat for fee paying and salaried courses and ensure the new content is not present. 
- Checkout the view preview
=> Update guidance for international candidates

app/components/find_interface/feedback_component.html.erb, app/components/find_interface/feedback_component.rb, app/controllers/find/application_controller.rb, app/controllers/find/results_controller.rb, app/views/layouts/component_preview.html.erb, app/views/view_components/index.html.erb, app/views/view_components/previews.html.erb, config/application.rb, config/settings/loadtest.yml, config/settings/qa.yml, config/settings/review.yml, config/settings/sandbox.yml, config/settings/staging.yml, spec/components/find_interface/feedback_component_preview.rb, spec/components/find_interface/feedback_component_spec.rb
https://trello.com/c/LCDdyOYs/761-migrate-the-feedback-component
- Migrate the Find FeedbackComponent
- Create a separate layout for previewing view components so we can load the Publish and Find styles in order for components to display properly
- Give the layout a bit of love to look more on brand
https://publish-teacher-training-pr-3095.london.cloudapps.digital/find/results (bottom of page)
https://publish-teacher-training-pr-3095.london.cloudapps.digital/view_components
=> [761] Migrate the Feedback component

app/helpers/find/subject_helper.rb, spec/features/find/course_searches_spec.rb
Remove Ancient greek, Hebrew and Philosophy from the ignored list. We handle empty states on the course list, not by hiding subjects.
- Remove the `IGNORED_SUBJECTS` array and only reject modern languages.
- Perform a search on Find and ensure that you now see Ancient greek, Hebrew and Philosophy (you should see no courses with these subjects).
- Create these courses and search for them and ensure the courses created appear in the search.
=> Remove subjects from ignored list

app/views/publish/courses/fees/edit.html.erb
https://trello.com/c/VreIlSuJ/779-%F0%9F%90%9E-possible-display-bug-for-course-fee-field
- Remove explicit setting of course fee form values so it reads from the course form object
- Update the course fee of a course
- Assert the updated amount is shown when you go back to edit
=> [779] Display bug for course fee field

Gemfile, app/components/find_interface/courses/entry_requirements_component/view.html.erb, spec/components/find_interface/courses/entry_requirements_component/view_preview.rb, spec/components/find_interface/courses/entry_requirements_component/view_spec.rb
ETP courses
Update qualifications needed content for ETP courses
https://publish-teacher-training-pr-3114.london.cloudapps.digital/find/course/2CG/M064#section-entry
https://publish-teacher-training-pr-3114.london.cloudapps.digital/find/course/S66/Y193#section-entry
https://publish-teacher-training-pr-3114.london.cloudapps.digital/publish/organisations/S66/2023/courses/Y193/preview#section-entry
https://publish-teacher-training-pr-3114.london.cloudapps.digital/view_components
https://publish-teacher-training-pr-3114.london.cloudapps.digital/view_components/find_interface/courses/entry_requirements_component/view/fully_populated_with_etp_course
=> [0803] Update qualifications needed content for ETP courses for newer find

Gemfile, Gemfile.lock
Does anyone use this gem, if not can we remove it?
Remove the debug gem.
=> Remove the debug gem

app/components/find_interface/courses/financial_support/bursary_component/view.html.erb, app/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view.html.erb, app/decorators/course_decorator.rb, app/helpers/find/subject_helper.rb, app/lib/feature_flags.rb, config/settings.yml, spec/components/find_interface/courses/financial_support/bursary_component/view_spec.rb, spec/components/find_interface/courses/financial_support/fees_and_financial_support_component/view_spec.rb, spec/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view_spec.rb, spec/decorators/course_decorator_spec.rb, spec/features/publish/viewing_a_course_preview_spec.rb, spec/features/publish/viewing_a_course_spec.rb, spec/helpers/find/subject_helper_spec.rb
https://trello.com/c/KhLW22i6/813-move-over-missing-feature-flag-guard-clauses
We moved over the feature logic from Find, this PR reinforces the flags and their guard clauses currently used in the codebase. Due to the migration, two are now redundant:
- `cache_courses` no need for this
- `send_web_requests_to_big_query` already in place app wide for the publish codebase
=> [813] Clean up find feature flags

app/components/find_interface/deadline_banner_component.html.erb, app/components/find_interface/deadline_banner_component.rb, app/models/find/site_setting.rb, app/services/find/cycle_timetable.rb, app/views/layouts/find_layout.html.erb, spec/components/find_interface/deadline_banner_component_spec.rb, spec/services/find/cycle_timetable_spec.rb
https://trello.com/c/8vDGqCXG/576-deadline-banners
Migrate the deadline banner component from Find and related code.
This just migrates the banner itself and the tests. https://trello.com/c/jrhPxKuT/577-migrate-find-cycles-feature will provide the ability to preview the banner in different states in the service
=> [576] Migrate the deadline banners component

app/models/course.rb, app/services/course_search_service.rb, spec/models/course_spec.rb, spec/requests/api/v3/courses/index_spec.rb, spec/services/course_search_service_spec.rb
Ordering of courses
Courses are ordered ascending
When sorting by training provider ascending
Then sort by provider ascending (a to z)
and sort by course name ascending (a to z)
When sorting by training provider descending
Then sort by provider descending (z to a)
and sort by course name ascending (a to z)
=> [0780] Amended so that courses are order ascending

config/locales/find.yml
URL for info on Maths scholarship
Fixed incorrect URL for info on Maths scholarship
=> [0833] Fixed incorrect URL for info on Maths scholarship

spec/requests/api/v3/providers/courses/index_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml, swagger/public_v1/component_schemas/CourseFilter.yml
Change campaign_name to engineers_teach_physics
When you set the engineers_teach_physics filter to true it returns all courses in that campaign.
When you set the engineers_teach_physics to false it returns all courses, including those in the ETP campaign.
=> Campaign name api fix

app/javascript/find/filter-toggle-button.js
https://trello.com/c/dFIVoAea/822-close-filters-button-should-include-visually-hidden-text-close-filter-menu
This is the counterpart for https://github.com/DFE-Digital/find-teacher-training/pull/1607 but for the migrated Find work.
- Inspect the markup on the results page
=> [822] Make close filter button more accessible

app/components/find_interface/courses/entry_requirements_component/view.rb, app/decorators/course_decorator.rb, spec/components/find_interface/courses/entry_requirements_component/view_preview.rb, spec/components/find_interface/courses/entry_requirements_component/view_spec.rb, spec/decorators/course_decorator_spec.rb
In the entry requirements section, subjects which are also not a language should not be capitalised. 
- Add the subject codes which are a language to an array.
- Use this array to downcase all other subject names in the view.
- Ensure modern languages is not capitalised (using gsub).
- View the entry requirements on courses with the following criteria, and ensure the capitalisation is correct. 
`Note: You may have to insert the course in to the instance variable in `app/controllers/find/courses_controller.rb` and the provider on the view as the full search functionality of new Find hasn't been built yet.`
- A course with a single language subject
- A course with a single non language subject
- A course with two subjects, one language and one non language
- A modern languages course
- A …
=> Don't capitalise subjects unless the subject is a language

app/views/find/pages/privacy.html.erb, app/views/layouts/_find_footer.html.erb, app/views/layouts/_footer.html.erb, app/views/pages/privacy.html.erb, config/routes/find.rb, config/routes/publish.rb, spec/features/find/view_pages_spec.rb, spec/features/view_pages_spec.rb
https://trello.com/c/KabFoz5k/799-update-the-privacy-notice-for-find-and-publish
Updates the privacy notice as per the docs in the ticket above for both Publish and the currently migrated Find
Publish - https://publish-teacher-training-pr-3135.london.cloudapps.digital/privacy-policy
New Find - https://publish-teacher-training-pr-3135.london.cloudapps.digital/find/privacy-policy
=> [799] Update privacy notice for Publish and New Find

app/decorators/course_decorator.rb, app/models/course.rb, app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/confirmation.html.erb, spec/decorators/course_decorator_spec.rb
The order of the subjects on the check your answers page and course details page should match the order they were entered.
```For example:
If the user chose Physics and Chemistry, the list should display:
- Physics
- Chemistry
If the user chose Modern Languages, the list should display:
- Modern Languages
- Language choice 1
- Language choice ...n
Where language choice is in alphabetical order as per the selection page.
If the user chose Physics and Modern Languages, the list should display:
- Physics
- Modern Languages
- Language choice 1
- Language choice ...n
If the user chose Modern Languages and Latin, the list should display:
- Modern Languages
- Language choice 1
- Language choice ...n
- Latin
```
Display subjects in the order they were chosen, as per the requirements above.
- …
=> 781 fix subject order in check your answers and course details page

app/assets/stylesheets/components/find/_search-results.scss, app/components/find_interface/results/sort_by_component.html.erb
Sort field
Amended to show the sort button
Removed the related js that auto submits
=> [0827] The sort by field should not auto submit we should provide a submit button

app/views/find/result_filters/_degree_required_filter.html.erb, app/views/find/result_filters/_qualifications_filter.html.erb, app/views/find/result_filters/_salary_filter.html.erb, app/views/find/result_filters/_send_filter.html.erb, app/views/find/result_filters/_study_type_filter.html.erb, app/views/find/result_filters/_vacancy_filter.html.erb, app/views/find/result_filters/_visa_filter.html.erb
https://trello.com/c/pptKsZYi/823-update-filter-legends-to-make-more-descriptive
Add visually hidden text ("filter") to the filter legends
- Review the markup
=> [823] Add more descriptive context to filter legends

app/views/find/results/index.html.erb, app/views/find/search/subjects/index.html.erb, config/locales/find.yml
Mis match page title vs h1
Fixed mis match page title vs h1 
The page titles matches
=> [0824] Fixed mis match page title vs h1

app/views/find/result_filters/location/_form.html.erb
https://trello.com/b/yOZLQ2IK/find-pub-sprint-board
- Adds visually hidden text to inline error message when linked to no fields (eg submitting without an option on start page)
- Submit without entering a value on start page and check markup (do the same for other forms)
=> [825] Add visually hidden text to errors linked to no keys

app/controllers/api/public/v1/providers_controller.rb, app/models/provider.rb, spec/controllers/api/public/v1/providers_controller_spec.rb, spec/models/provider_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/ProviderFilter.yml
Additional filter options for the provider end pint
Added filter for provider_types
Added filter for region_codes
Added filter for can_sponsor_skilled_worker_visa
Added filter for can_sponsor_student_visa
https://publish-teacher-training-pr-3150.london.cloudapps.digital/docs/api-reference.html#recruitment_cycles-year-providers-get
https://publish-teacher-training-pr-3150.london.cloudapps.digital/docs/api-reference.html#schema-providerfilter
> can_sponsor_student_visa AND region_codes with yorkshire_and_the_humber OR london
https://publish-teacher-training-pr-3150.london.cloudapps.digital/api/public/v1/recruitment_cycles/2023/providers?[filter][can_sponsor_student_visa]=true&[filter][region_code]=yorkshire_and_the_humber,london
> can_sponsor_skilled_worker_visa AND provider_type with scitt …
=> [0830] Add additional filter options to the providers api endpoints

app/view_objects/find/result_filters/filters_view.rb, app/view_objects/find/results_view.rb, app/views/find/result_filters/_all.html.erb, app/views/find/result_filters/_engineers_teach_physics_filter.html.erb, spec/features/find/result_page_filters/engineers_teach_physics_spec.rb, spec/support/page_objects/find/results.rb
In line with the "Engineers teach physics" work, we are adding a filter on Find to search for only these courses. This filter will appear when searching for the "Physics" subject.
The was implemented in old Find, here: https://github.com/DFE-Digital/publish-teacher-training/pull/3086
- Add UI for filter checkbox
- Only render the checkbox if the "Physics" subject has been chosen
- Perform a search for a Physics course on Find
- Try out the new filter
=> Add ETP checkbox UI

app/controllers/api/public/v1/providers/courses_controller.rb, app/controllers/api/public/v1/providers/locations_controller.rb, app/controllers/api/public/v1/providers_controller.rb, spec/controllers/api/public/v1/providers/courses_controller_spec.rb, spec/controllers/api/public/v1/providers/locations_controller_spec.rb, spec/controllers/api/public/v1/providers_controller_spec.rb
Meta count
Added count for provider
Added count for provider's courses
Added count for provider's locations
https://publish-teacher-training-pr-3158.london.cloudapps.digital/api/public/v1/recruitment_cycles/2023/providers
https://publish-teacher-training-pr-3158.london.cloudapps.digital/api/public/v1/recruitment_cycles/2023/providers/T92/courses
https://publish-teacher-training-pr-3158.london.cloudapps.digital/api/public/v1/recruitment_cycles/2023/providers/T92/locations
=> [0829] Add meta count to providers, provider's courses and provider's locations api endpoints

app/models/course.rb, app/services/courses/generate_course_name_service.rb, config/locales/en.yml, spec/models/course_spec.rb, spec/services/courses/generate_course_name_service_spec.rb
https://trello.com/c/soElYNgr/821-course-name-does-not-reflect-subjects-chosen-and-languages-are-not-in-alphabetical-order
- Refactor `GenerateCourseNameService`, it was becoming a bit of a soup
- Implement fix to generate titles correctly for Modern language courses with an additional subject
- There is an existing bug with modern language courses not showing subjects/additional subjects correctly in the subject edit list. This was already carded up as https://trello.com/c/hsF1kHsx/818-changing-subject-does-not-maintain-first-and-second-subject-order
Review app - https://publish-teacher-training-pr-3149.london.cloudapps.digital/
- Create a course and choose modern languages with an additional subject (then the other way round) and check the title includes the additional subject
=> [821] Refactor course name generation service

Dockerfile
The fixed version for [vulnerability](https://security.snyk.io/vuln/SNYK-ALPINE315-EXPAT-3062885) is now installed by default when the dependency expat is required. We can therefore remove the manual installation of this from the Dockerfile.
Remove manual add of expat 2.5.0-r0
Confirm Snyk tests pass in build
https://trello.com/c/NkBxwoiL/714-libexpat-vulnerability
=> Remove the manual fix for expat vulnerability

app/controllers/publish/providers/access_requests_controller.rb, app/controllers/publish/users_check_controller.rb, app/controllers/publish/users_controller.rb, app/forms/form.rb, app/forms/publish/user_form.rb, app/forms/support/user_form.rb, app/forms/user_form.rb, app/helpers/navigation_bar_helper.rb, app/helpers/provider_helper.rb, app/models/user.rb, app/policies/provider_policy.rb, app/views/publish/providers/access_requests/new.html.erb, app/views/publish/shared/_aside_information_box.html.erb, app/views/publish/users/index.html.erb, app/views/publish/users/new.html.erb, app/views/publish/users_check/show.html.erb, config/locales/en.yml, config/routes/publish.rb, config/settings/review.yml, spec/features/publish/users/adding_user_to_provider_spec.rb, spec/forms/support/user_form_spec.rb, spec/models/user_spec.rb, spec/policies/provider_policy_spec.rb, spec/support/page_objects/publish/users_check.rb, spec/support/page_objects/publish/users_index.rb, spec/support/page_objects/publish/users_new.rb
Introducing a feature for providers to create Publish users and associate them with specific organisations. The users will also be sent an email, with the link and inviting them to sign up to DfE Sign in, if they haven't already.
- Create new views, routes, controllers and form.
- Store changes in redis when submitting the form and going to the check page.
- Update the database with the changes stored in redis on submission of the check page.
- Values in the form are persisted if you cancel or go back from the check page. If you have accidently gone to the wrong provider, when you go to the correct one the form will be prefilled.
- Utilise the `UserAssociationService`.
- If the user does not exist on Publish, create the user and associate them with the provider.
- If the user does exist …
=> Managing users in publish (Add user)

app/controllers/publish/users_controller.rb, app/views/publish/users/index.html.erb, app/views/publish/users/show.html.erb, config/locales/en.yml, spec/features/publish/managing_users_spec.rb, spec/support/page_objects/publish/users_show.rb
As a follow up to #3159 where we add the ability for provider users to add new provider users to organisations, this PR allow providers to to view these provider users. 
- Add a show page
- Link to the show page from the users list
- Checkout the show page `publish/organisations/1CS/users/{user_id}`
- There's a separate ticket for change links: https://trello.com/c/y70qffV4/864-managing-users-in-publish-edit-user
=> Managing users in publish (viewing users)

app/controllers/publish/users_check_controller.rb, app/controllers/publish/users_controller.rb, app/policies/provider_policy.rb, app/views/publish/users/delete.html.erb, app/views/publish/users/show.html.erb, config/locales/en.yml, config/routes/publish.rb, spec/features/publish/managing_users_spec.rb, spec/support/page_objects/publish/users_delete.rb, spec/support/page_objects/publish/users_show.rb
Following on from #3159 and #3166. The next feature in the managing users epic is the ability for providers to remove other provider users.
- Add routes for deleting
- Add the remove user link on the show page
- Add a `delete?` method to the provider policy
Try it out on the review app.
=> Managing users in publish (removing users)

app/controllers/publish/users_controller.rb, app/controllers/publish/users_edit_check_controller.rb, app/helpers/user_helper.rb, app/models/user.rb, app/views/publish/users/edit.html.erb, app/views/publish/users/show.html.erb, app/views/publish/users_edit_check/show.erb, config/locales/en.yml, config/routes/publish.rb, spec/features/publish/managing_users_spec.rb, spec/support/page_objects/publish/users_edit.rb, spec/support/page_objects/publish/users_show.rb
Following on from #3159, #3166, #3171. The final feature in the managing users epic is the ability for providers to edit other provider users.
- Add change links on the show page (only render these if the user does not have an associated DfE Sign in account)
- Add an edit view
- When the edit view is submitted, you are taken to a `/edit/check` page where you will be presented with your new details. 
- You can then confirm these details and the database is updated and an email is sent. 
Have a play around with the review app.
=> Managing users in publish (Editing users)

app/components/find_interface/courses/summary_component/view.html.erb, app/components/find_interface/courses/summary_component/view.rb, spec/components/find_interface/courses/sumary_component/view_preview.rb, spec/components/find_interface/courses/sumary_component/view_spec.rb
Course level and age range
Add level next to age range if a secondary course
`secondary` should show up on courses that has level secondary
https://publish-teacher-training-pr-3195.london.cloudapps.digital/find/course/2FD/C045
=> [0892] Add level next to age range if a secondary course

app/views/publish/courses/subjects/_form_fields.html.erb
What happened?
We recently pushed a fix for the subject dropdown not listing subjects correctly [818 fix modern languages issue](https://github.com/DFE-Digital/publish-teacher-training/pull/3180/files). But we also need to handle courses who do not have a master_subject_id set.
**What was supposed to happen?**
Courses who do not have the field above set should also have their subjects displayed correctly in the dropdow
Add fallback `selected_subject_ids.first` to select options
=> fallback for master subject id

app/controllers/api/public/v1/providers_controller.rb, spec/controllers/api/public/v1/providers_controller_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/ProviderFilter.yml
Filter for is_accredited_body
Added filter for is_accredited_body
https://publish-teacher-training-pr-3203.london.cloudapps.digital/api/public/v1/recruitment_cycles/2023/providers?filter[is_accredited_body]=true
=> [0892] Added filter for is_accredited_body

app/components/find_interface/courses/summary_component/view.html.erb, app/components/find_interface/courses/summary_component/view.rb, spec/components/find_interface/courses/sumary_component/view_preview.rb, spec/features/find/search/viewing_a_course_spec.rb, spec/features/publish/viewing_a_course_preview_spec.rb
A recent accessibility update on Find to expand PGCE, PGDE and QTS abbreviations has meant we have removed the study mode (full-time and part-time) from the lede paragraph.
Add the study mode tadjacent to the course length in the summary list on the course details.
Take a look at the show page for various study modes and course lengths.
=> Add study_mode to course show page

app/controllers/publish/courses/engineers_teach_physics_controller.rb, app/controllers/publish/courses/subjects_controller.rb, app/services/publish/course_creation_step_service.rb, app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/confirmation.html.erb, config/settings.yml, config/settings/review.yml, spec/features/publish/courses/editing_apprenticeship_spec.rb, spec/features/publish/courses/editing_funding_type_spec.rb, spec/features/publish/courses/editing_visa_sponsorship_spec.rb, spec/features/publish/courses/new_visa_sponsorship_spec.rb, spec/features/publish/viewing_a_course_details_spec.rb
We've got a few feature flags which could be cleaned up as the features have been released for a while now
Get rid of them
Tech notes
Mainly:
visa_sponsorship_on_course
engineers_teach_physics_on_course
user_management might be a candidate unless we have not released it yet **NOT DONE**
=> rm etp feature flag

swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/CourseAttributes.yml, swagger/public_v1/component_schemas/CourseFilter.yml
We recently added the ability to filter courses by `campaign_name`. However, in the API it's called `engineers_teach_physics`. 
- Change the CourseFilter param from `engineers_teach_physics` to `campaign_name`.
=> [868] Update course filter for ETP

spec/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view_spec.rb
Replace `rendered_component` with `page`. 
rendered_component is deprecated and will be removed in v3.0.0
Did I miss anything?
=> Replace `rendered_component` with `page`

app/services/course_search_service.rb
https://trello.com/c/htwlxe9F/934-bug-fix-campaignname-course-filter-option
=> [934] Fix campaign name filter

app/controllers/publish/users_controller.rb, app/models/user.rb, spec/models/user_spec.rb
We are sorting the users list alphabetically based on first name and then last name. 
- Sort the list using active record in the controller
Is the list ordered in the way we want it to be?
=> Alphabetize users list

config/settings.yml, config/settings/qa.yml, config/settings/review.yml, spec/features/publish/viewing_provider_users_spec.rb
Merging this PR will activate the user_management feature in production.
- Set feature flag to true in `Settings.yml`
- Remove feature flag from qa.yml and review.yml
- Deactivate the feature flag in a test for the old flow
:shipit:
=> Activate user management in production

terraform/modules/paas/variables.tf
Add find2 route for review apps, to allow review app testing for the find/pub merge
Update terraform variables to add find2-pr-xxxx route if we are deploying a review app
Deployed review app find2-pr-3246
make review deploy-plan APP_NAME=xxxx 
- should create new route
make qa deploy-plan
- no route changes
=> Add find2 route for review apps

app/lib/publish_constraint.rb
Smoke tests are failing as part of the deploy step as we're not checking the api domain which is stored in a sep. setting
=> [xxx] Include the api domain as a check

app/components/find/results/sort_by_component.html.erb, app/models/course.rb, app/services/course_search_service.rb, app/view_objects/find/results_view.rb, spec/features/find/sorted_by_filter_spec.rb, spec/models/course_spec.rb, spec/requests/api/v3/courses/index_spec.rb, spec/services/course_search_service_spec.rb, spec/view_objects/find/results_view_spec.rb
We are adding the ability to sort the results page on Find by course name.
- **Add course ordering (A-Z) (default)**
If identical course, ordering falls back to the provider, if identical providers, ordering falls back to the course code
- **Add course ordering (Z-A)**
If identical course, ordering falls back to the provider, if identical providers, ordering falls back to the course code
- Remove the unnecessary use of Sort. This was probably added for future proofing, but there has been no need for it and it just causes confusion.
- Remove the constants and compare directly with strings encompassed within methods. This will make it easier to remove the code relating to old find when we delete it.
Search for a few courses and check that the hierarchy above is correct.
=> Update results page ordering options

app/controllers/api/public/v1/providers_controller.rb, app/models/provider.rb, docs/source/release-notes.html.md.erb, spec/controllers/api/public/v1/providers_controller_spec.rb, spec/models/provider_spec.rb, swagger/public_v1/api_spec.json, swagger/public_v1/component_schemas/ProviderFilter.yml
On the api to be able to search via the provider name, similar to the the provider suggestions
Add provider name to ProviderFilter
https://publish-teacher-training-pr-3261.london.cloudapps.digital/docs/api-reference.html#schema-providerfilter
``` Javascript
let response = await fetch("https://publish-teacher-training-pr-3261.london.cloudapps.digital/api/public/v1/recruitment_cycles/2023/providers?filter[provider_name]=oxf", { 
method: "GET",
});
let data = await response.text();
console.log(data);
```
=> [0896] Add provider name to ProviderFilter

spec/docs/providers/locations_spec.rb, swagger/public_v1/api_spec.json
Invalid values from the API docs for provider locations include param
Remove invalid values from the API docs for provider locations include param
https://publish-teacher-training-pr-3263.london.cloudapps.digital/docs/api-reference.html#recruitment_cycles-year-providers-provider_code-locations-get
=> [0958] Amended documentation typos

app/lib/system_admin_constraint.rb, config/routes/publish.rb
Publish has had sidekiq setup for a while but we have never enabled the web interface to be available. This PR does that so we can diagnose jobs. Using the same constraint from Register.
=> [xxx] Enable the sidekiq dashboard for admins

guides/support_playbook.md
Add instructions for copying single course to a different provider to the support playbook.
=> Instructions for copying a single course to a new provider

app/controllers/find/application_controller.rb, app/controllers/publish/publish_controller.rb, app/controllers/support/support_controller.rb, config/initializers/dfe_analytics.rb
With Find being merged into Publish, we're going to stream events into one table but setup a different namespace for Find. 
https://trello.com/c/6nkOr3CU/944-handle-dfe-analytics-configuration
- Sets up a namespace for Find
- Tweaks the DFE config to send jobs async via diff. queue
=> [944] Set up different DFE namespace for Find

terraform/data.tf, terraform/modules/paas/data.tf, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/qa.tfvars.json
This is for the findpub merge
so that the routes can be managed by publish
Steps are 
- remove routes from find QA terraform state
- import find routes to publish QA terraform state
- merge this PR
Add variables
- find_app_gov_uk_host_names (list of find service hostnames i.e. qa, qa-assets)
- find_route_target (where the find routes point to i.e. find or publish)
- find_cloudapp_names (list of cloudapps hostnames i.e. find-qa, find-pr-1234)
Add find webapp as a data resource
Add resources for the find routes that will point to the app as per find_route_target setting
make qa deploy-plan
=> Add find qa routes to terraform state and code

terraform/modules/paas/data.tf, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/qa.tfvars.json
Removing the references for the find app route target, 
as we aren't using them now, and it breaks the review app.
Remove tf references to the find_route_target
Changed var to enable find (true or false)
Check review app deploys
=> Fix review app

app/components/find/courses/apply_component/view.html.erb, app/components/find/courses/apply_component/view.rb, app/controllers/concerns/apply_redirect.rb, app/controllers/find/courses_controller.rb, app/controllers/publish/courses_controller.rb, app/policies/course_policy.rb, config/routes/publish.rb, spec/components/find/courses/apply_component/view_preview.rb, spec/components/find/courses/apply_component/view_spec.rb, spec/controllers/find/courses_controller_spec.rb, spec/features/publish/viewing_a_course_preview_spec.rb
undefined method `find_apply_path`
There was a lot of missing items from like the actually controller and the behaviour and everything else that was needed to make it work. :face_in_clouds: 
Based on 
https://github.com/DFE-Digital/find-teacher-training/blob/37ee8d0b1d414bb05ec4a271a36fe77261c6d5e8/app/controllers/courses_controller.rb#L20-L33
=> [0974] Fix bug undefined method `find_apply_path`

terraform/workspace_variables/qa.tfvars.json
Increase app memory for QA from 512M to 1024M per instance
Due to increase in "out of memory" errors since the merge with find
Increase paas_web_app_memory in qa.tfvars.json
deploy-plan
Check QA after merge
=> Increase QA app instance memory

app/services/courses/generate_course_name_service.rb, spec/services/courses/assign_subjects_service_spec.rb, spec/services/courses/generate_course_name_service_spec.rb
When creating course names, the second subject should be lowercase unless it is a noun.
https://publish-courses-prototype.herokuapp.com/course-names
Update the course name generator to be sentence case unless the subject is a noun (e.g., English, French, Spanish, etc)
Add downcasing method
Covered by existing tests I think
=> Downcase non language subjects

config/rubocop/lint.yml
We have lots of tech debt because of cops not being enabled. This PR enables some of them and fixes the bad code. 
**This PR focuses on clearing out the `lint.yml` file.**
See commits
- Recommend reviewing commit by commit, as in each commit  one particular cop is enabled and all the code is adjusted to pass the linter.
- I've kept the exclusions for `Lint/UselessMethodDefinition` as `Rails/LexicallyScopedActionFilter` conflicts with it.
- Play around with the review app in areas which relies on lots of code working together to ensure there are no (untested) hidden breakages.
- Check everywhere (Find/Publish/Support)
=> Comply with rubocop (lint.yml)

config/routes.rb, public/robots.txt
We're now pointing https://staging.find-postgraduate-teacher-training.service.gov.uk/ to publish. We need to activate the routes so the app handles the incoming request.
This PR also disallows crawling of any page except for the Find sitemap in prod as staging/prod for Find are publicly available.
=> [xxx] Enable Find routes in staging

Rakefile, app/controllers/concerns/errorable.rb, app/controllers/publish/courses/sites_controller.rb, app/decorators/course_decorator.rb, app/forms/publish/age_range_form.rb, app/helpers/navigation_bar_helper.rb, app/models/course.rb, app/models/provider.rb, app/policies/provider_policy.rb, config/rubocop/rails.yml, db/migrate/20190626132627_add_course_ref_to_course_enrichment.rb, db/migrate/20190627151832_add_provider_ref_to_provider_enrichment.rb, db/migrate/20210527145331_add_visa_columns_to_the_database.rb, db/migrate/20210609081246_add_structured_degree_columns_to_the_course_table.rb, db/migrate/20210614130500_add_structured_gcse_columns_to_course_table.rb, db/migrate/20210623150714_remove_structured_gcse_columns_from_course_table.rb, db/migrate/20210712082658_remove_london_borough_and_travel_to_work_area_from_site.rb, db/migrate/20220825093437_add_visa_fields_to_course.rb, db/migrate/20221018084448_update_etp_field.rb, docs/lib/govuk_tech_docs/open_api/renderer.rb, spec/support/matchers/have_courses.rb, spec/support/matchers/have_providers.rb, spec/support/parse_text_table.rb
We have lots of tech debt because of cops not being enabled. This PR enables some of them and fixes the bad code. 
**This PR focuses on clearing out the `rails.yml` file.**
See commits
- Recommend reviewing commit by commit, as in each commit  one particular cop is enabled and all the code is adjusted to pass the linter.
- Do we want to keep any of these cops disabled?
- Play around with the review app in areas which relies on lots of code working together to ensure there are no (untested) hidden breakages.
- Check everywhere (Find/Publish/Support)
=> Comply with rubocop (rails.yml)

.rubocop.yml
Enable: `Rails/I18nLocaleTexts` and exclude the files which cause this to fail. We will fix these up later. This will help to stop code rot.
=> Comply with rubocop (rubocop.yml)

Gemfile, Gemfile.lock, config/environments/production.rb, config/initializers/cors.rb, config/settings/production.yml, config/settings/qa.yml, config/settings/sandbox.yml, config/settings/staging.yml
The current find implements an asset host server to serve assets from so they're cached by Cloudfront. We're trying to maintain that functionality in Find running on Publish.
This PR dynamically configures Find assets to be served from `{env}-assets.find-*`
Tested on QA:
=> [1015] Configure asset host for Find

app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/_description_content.html.erb, spec/features/publish/viewing_a_course_details_spec.rb, spec/features/publish/viewing_a_course_spec.rb
Change links for courses
Remove the change links for courses in the withdrawn state
No change links for withdrawn course
Go and withdraw a course or find a withdrawn course
https://publish-teacher-training-pr-3316.london.cloudapps.digital/publish/organisations/1QN/2023/courses/V163
https://publish-teacher-training-pr-3316.london.cloudapps.digital/publish/organisations/1QN/2023/courses/V163/details
=> [0957] Remove the change links for courses in the withdrawn state

app/views/publish/courses/confirmation.html.erb
Content changes on the check your answers page for locations
Update content on the check your answers page for locations
Find a provider that has one location, and go thro the motion
Removed uneeded text
Plural `Locations` vs singular `Location`
=> [0999] Content changes on the check your answers page for locations

config/routes.rb
We're going live today. We'll need to enable the Find routes before the domain switch so the app can handle requests from it. These routes won't be accessible until the domain switch has happened.
=> [xxx] Enable Find routes in prod

Makefile, service_unavailable_page/web/nginx.conf, service_unavailable_page/web/public/internal/find.html
**Merge when find prod running from publish**
Add find to the maintenance page
Update Makefile to map/unmap find routes to the maintenance app
Add find domain to nginx.conf so it directs to a find.html that displays Find instead of Publish
Tested against a review app
=> Add find to maintenance page

app/services/courses/assign_subjects_service.rb, spec/services/courses/assign_subjects_service_spec.rb
Course name and subjects and persisted status
Persisted course name can only be updated if it is valid
Non persisted course can be updated regardless
It works for both new course and existing courses
=> [1033] Amended to only change name when valid

app/controllers/find/application_controller.rb, app/controllers/find/courses_controller.rb, spec/controllers/find/courses_controller_spec.rb
https://trello.com/c/xgujREEG/1034-bug-handle-missing-providers-courses-gracefully
- Redirects to the not found page for missing providers/courses instead of blowing up
- Check `course/1A9/22J` (request which came into Sentry)
- Assert not found page is shown
=> [1034] Handle missing provider/courses

app/controllers/find/search/age_groups_controller.rb, app/controllers/find/search/subjects_controller.rb, spec/features/find/search/location_options_spec.rb
https://trello.com/c/IxI9RYJl/1026-bug-no-js-and-giberish-broke-it
The country parameter (`c`) can also default to a list of values if some invalid location is used. We only whitelisted the non-list version.
- Handle un-permitted parameter
- Add a test
- Try to location search some gibberish
=> [1026] Fix parameter bug

app/decorators/course_decorator.rb, app/views/publish/courses/applications_open/_form_fields.html.erb, app/views/publish/courses/applications_open/edit.html.erb, app/views/publish/courses/applications_open/new.html.erb, spec/features/publish/courses/new_accredited_body_spec.rb
Updating the radio buttons on the applications open page in line with the prototype. 
See commits.
- Have a look at the screenshots.
- Launch the review app and create a course, until you get to the applications open page (you can only see the non rollover page)
- If you want to see the rollover version and the screenshot doesn't provide sufficient context, message me.
=> Content changes to add edit flows applications open date

app/components/find/courses/entry_requirements_component/view.html.erb, app/components/find/courses/entry_requirements_component/view.rb, config/locales/find.yml, spec/components/find/courses/entry_requirements_component/view_preview.rb, spec/components/find/courses/entry_requirements_component/view_spec.rb
Context
We need to add some content about SKE to the entry requirements section for certain subjects as documented in this DH: https://bat-design-history.netlify.app/find-teacher-training/including-information-about-subject-knowledge-enhancement-ske-courses/
We need to add this content: "If your degree is not in [subject], or you’ve not used your subject knowledge in a while, you may be asked to complete a [subject knowledge enhancement (SKE) course](https://getintoteaching.education.gov.uk/train-to-be-a-teacher/subject-knowledge-enhancement)." for these courses:
biology
chemistry
computing
design and technology
English
languages (german spanish french)
mathematics
physics
religious education
For primary mathematics, we need to add:
"If you need to improve your primary mathematics …
=> [890] Add content about ske to entry requirements section

app/controllers/find/search/age_groups_controller.rb, app/controllers/find/search/subjects_controller.rb, app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
This PR fixes a few noisy Sentry errors causing failed requests and searches in prod. Specifically:
- https://dfe-teacher-services.sentry.io/issues/3937884858/?environment=production&project=1377944&query=is%3Aignored&referrer=issue-stream
- https://dfe-teacher-services.sentry.io/issues/3922486907/?environment=production&project=1377944&query=is%3Aignored&referrer=issue-stream
- https://dfe-teacher-services.sentry.io/issues/3914796102/?environment=production&project=1377944&query=is%3Aignored&referrer=issue-stream
- https://dfe-teacher-services.sentry.io/issues/3920146195/?environment=production&project=1377944&query=is%3Aignored&referrer=issue-stream
- Whitelist legacy Find query parameters before the results as our facade will swap them out anyway
- Handle qualification parameters …
=> [xxx] Fix a few Sentry errors

app/services/course_search_service.rb, spec/services/course_search_service_spec.rb
Fixes the following Sentry error https://dfe-teacher-services.sentry.io/issues/3936286223/?project=1377944&query=is%3Aunresolved&referrer=issue-stream
=> [xxx] Handle subject params coming in as a Hash for CourseSearchService

app/controllers/concerns/filter_parameters.rb, app/controllers/find/search/age_groups_controller.rb, app/controllers/find/search/subjects_controller.rb, app/services/course_search_service.rb, app/services/find/match_old_params.rb, spec/services/course_search_service_spec.rb, spec/services/find/match_old_params_spec.rb
This PR addresses https://trello.com/c/RMZ7UtkL/1083-bug-handle-old-find-paramaeters and a few other Sentry issues.
Resolves the following:
- https://dfe-teacher-services.sentry.io/issues/3922486907/?project=1377944&query=is%3Aignored&referrer=issue-stream
- https://dfe-teacher-services.sentry.io/issues/3949630182/?project=1377944&query=is%3Aignored&referrer=issue-stream
- https://dfe-teacher-services.sentry.io/issues/3944950394/?project=1377944&query=is%3Aignored&referrer=issue-stream
These issues can be reproduced locally in a different branch or in QA.
=> [1083] Sentry fixes

app/decorators/course_decorator.rb, app/models/concerns/courses/edit_options.rb, app/models/concerns/courses/edit_options/age_range_concern.rb, app/models/concerns/courses/edit_options/applications_open_concern.rb, app/models/concerns/courses/edit_options/can_sponsor_skilled_worker_visa_concern.rb, app/models/concerns/courses/edit_options/can_sponsor_student_visa_concern.rb, app/models/concerns/courses/edit_options/entry_requirements_concern.rb, app/models/concerns/courses/edit_options/is_send_concern.rb, app/models/concerns/courses/edit_options/qualification_concern.rb, app/models/concerns/courses/edit_options/start_date_concern.rb, app/models/concerns/courses/edit_options/study_mode_concern.rb, app/models/concerns/courses/edit_options/subjects_concern.rb, app/views/publish/courses/start_date/_form_fields.html.erb, app/views/publish/courses/start_date/edit.html.erb, app/views/publish/courses/start_date/new.html.erb, config/locales/en.yml, spec/decorators/course_decorator_spec.rb, spec/features/publish/courses/new_applications_open_spec.rb, spec/features/publish/courses/new_start_date_spec.rb, spec/features/publish/e2e/new_course_spec.rb, spec/features/support/providers/courses/editing_a_course_spec.rb, spec/forms/edit_course_form_spec.rb, spec/models/concerns/courses/edit_options/start_date_concern_spec.rb
Start date for courses
Change the drop down list to radio buttons
Also fixed error message as it is now very obvious
There is currently no edit functionality (change link)
https://publish-teacher-training-pr-3367.london.cloudapps.digital/publish/organisations/T92/2023/courses/start-date/new?course%5Bage_range_in_years%5D=3_to_7&course%5Bapplications_open_from%5D=2022-10-11&course%5Bcampaign_name%5D=&course%5Bcan_sponsor_skilled_worker_visa%5D=false&course%5Bfunding_type%5D=apprenticeship&course%5Bis_send%5D=0&course%5Blevel%5D=primary&course%5Bmaster_subject_id%5D=4&course%5Bqualification%5D=pgce_with_qts&course%5Bsites_ids%5D%5B%5D=11237736&course%5Bstudy_mode%5D=full_time&course%5Bsubjects_ids%5D%5B%5D=4
=> [0997] Content changes to add edit flows course start date

app/views/find/search/locations/_form.html.erb, app/views/find/search/locations/start.html.erb
The content added to the bottom of the Find homepage is currently not in the correct grid column. This PR fixes that.
:shipit:
=> Place Find homepage content in grid column

app/views/find/result_filters/_qualifications_filter.html.erb, app/views/find/result_filters/_study_type_filter.html.erb, spec/features/find/result_page_filters/degree_required_spec.rb, spec/features/find/result_page_filters/qualifications_spec.rb, spec/features/find/result_page_filters/salary_spec.rb, spec/features/find/result_page_filters/send_spec.rb, spec/features/find/result_page_filters/study_type_spec.rb, spec/features/find/result_page_filters/vacancies_spec.rb, spec/features/find/result_page_filters/visa_spec.rb
Some of the labels for the Find filters are not clickable, they should be.
- Fix non clickable checkbox labels on Find.
- Click the labels instead of the checkbox in tests (in order to catch these in the future).
The label text should be clickable as well as the checkboxes
=> Fix non clickable checkbox labels

app/views/publish/courses/confirmation.html.erb
We recently changed the titles of several pages in the ‘Add course’ and edit course flows. These changes impacted the check your answers and course details summary lists.
We also made improvements to the sub-navigation and summary lists.
Add a back link to check your answers page 
https://bat-design-history.netlify.app/publish-teacher-training-courses/updating-the-check-your-answers-and-course-details-pages/
✅ Make sure all information from the Trello card is in here
✅ Attach to Trello card
✅ Rebased main
✅ Cleaned commit history
✅ Tested by running locally
=> add back link to check your answers page

app/views/publish/courses/age_range/edit.html.erb, app/views/publish/courses/course_information/edit.html.erb, app/views/publish/courses/degrees/subject_requirements/edit.html.erb, app/views/publish/courses/fees/edit.html.erb, app/views/publish/courses/gcse_requirements/edit.html.erb, app/views/publish/courses/outcome/edit.html.erb, app/views/publish/courses/requirements/edit.html.erb, app/views/publish/courses/sites/edit.html.erb, app/views/publish/courses/skilled_worker_visa_sponsorship/edit.html.erb, app/views/publish/courses/student_visa_sponsorship/edit.html.erb, app/views/publish/courses/study_mode/edit.html.erb, app/views/publish/courses/subjects/edit.html.erb
We improved the content on the ‘Add course’, and edit course flows to make the language clearer and more specific to the options presented on the page.
At the same time, we changed some of the interactions to make adding and editing a course easier.
In the edit course flows, we updated all buttons to ‘Update [information being updated]’, for example, ‘Update qualification’.
https://bat-design-history.netlify.app/publish-teacher-training-courses/updating-the-check-your-answers-and-course-details-pages/
✅ Make sure all information from the Trello card is in here
✅ Attach to Trello card
https://trello.com/c/MQYEptOy/993-content-changes-to-add-edit-flows-buttons
✅ Rebased main
✅ Cleaned commit history
✅ Tested by running locally
=> [993] Updated the text for button from save to update

.github/workflows/build-and-deploy.yml
Our build process has become painfully slow, taking 20-25 mins on average to complete. This PR sets up parallelisation to speed things up. 
- Update the build_and_deploy workflow to use a matrix strategy for tests
- Do the same thing for lint but move them into their own group
See the build run with the new strategy, time is cut by about half https://github.com/DFE-Digital/publish-teacher-training/actions/runs/4294510017 (13 mins-ish)
=> [xxx] Split out lint task and parallelise tests

spec/features/publish/courses/editing_modern_languages_spec.rb
Efl was previously removed from subjects, so its no longer a valid subject.
Stop EFL from haunting us.
🚢
=> Remove efl from test

app/components/find/courses/international_students_component/view.html.erb, app/components/find/courses/international_students_component/view.rb, app/models/course.rb, app/services/courses/generate_course_name_service.rb, config/locales/find.yml, spec/components/find/courses/international_students_component/view_spec.rb
https://trello.com/c/Tu6wycNm/926-add-content-about-relocation-payments-to-international-candidates-section
- Update the content for the international candidates component used via the Find course show page and the Publish course preview
- Also updates some existing content in this component to match with the prototype
Review app - https://find-pr-3370.london.cloudapps.digital
Check one of the qualifying courses for a relocation payment and one without. Assert the relocation text is shown correctly.
=> [926] Add content about relocation payments to international candidates section

app/views/publish/courses/_basic_details_tab.html.erb, app/views/publish/courses/confirmation.html.erb, spec/features/publish/course_confirmation_spec.rb, spec/features/publish/viewing_a_course_details_spec.rb, spec/support/page_objects/find/results.rb, spec/support/page_objects/publish/provider_courses_details.rb
https://trello.com/c/da4K12BO/1001-content-changes-on-the-check-your-answers-page-summary-list-headings
- Updates the summary list headings on the check your answers page when creating a course and the course details page
- Update specs
- Create/edit a course and check the summary list headings match the prototype
Design history - https://bat-design-history.netlify.app/publish-teacher-training-courses/updating-the-check-your-answers-and-course-details-pages/
=> [1001] Content changes to summary list headings

app/controllers/publish/courses/engineers_teach_physics_controller.rb, app/models/concerns/publish/course_basic_detail_concern.rb, spec/features/publish/course_confirmation_spec.rb, spec/support/page_objects/publish/courses/new_locations.rb
When attempting to update locations from the course confirmation page, if you click continue you're put back into the flow. It should return you back to the confirmation page.
https://trello.com/c/0lZZHfco/1132-bug-fix-location-editing-in-new-course-flow
We seem to have two ways to retrieve `[:goto_confirmation]` have put behind a method for now as not yet confident if we can completely replace it with the one nested in a course eg `params[:course][:goto_confirmation]`
- Add a new course
- Edit locations
- Click continue, assert you're taken back to the confirmation page
=> [1132] Fix location bug

Procfile.dev, app/decorators/course_decorator.rb
When creating a new course and on the check your answers page, if you have selected two subjects and attempt to update them - you are taken back to the subjects form but the second subject is lost.
https://trello.com/c/EpcaUDU6/1133-bug-fix-subject-editing-in-new-course-flow
- Fix call to get subject ids. For some reason `pluck` returns an empty array here (even when there are two records present). 
Given this will only be two subjects, switch to map to get the ids
- Have also moved the caddy process into the Procfile so it can all be fired up in one command
=> [1133] Fix secondary subject not displaying

app/controllers/publish/courses/sites_controller.rb, app/decorators/course_decorator.rb, app/services/courses/creation_service.rb, app/views/publish/courses/sites/new.html.erb
User - provider(2A6) with a large number of locations encounters cloudfront URL length error 494 when continuing from locations new page, as the URL created hits Cloudfronts hard limit.
This occurs even if only a single option is selected, as the unselected option still enter the url query.
In qa testing, a 413 error was raised rather than a 494?
Alter the locations/new view to present sites_ids[] rather than site_statuses_attributes. This will not fix the issue if the user selects all locations from a very long list, but will help if only a portion of options are selected.
test in qa, create a new course with provider 2A6
=> 1139 locations error

terraform/modules/paas/main.tf
Worker app deploy failing with
2023-03-16T10:28:30.13+0000 [CELL/0] ERR Cell 2fe28b9e-5dd4-4388-87e0-73737373 failed to create container for instance c02bd359-82d6-427c-7373-7373: running image plugin create: making image: creating image: applying disk limits: disk limit is smaller than volume size
2023-03-16T10:28:30.13+0000 [CELL/0] ERR : exit status 
Currently worker app uses default quota of 1G
current usage
state     since                  cpu    memory           disk         details
#0   running   2023-03-15T17:06:12Z   0.4%   211.2M of 512M   **856M of 1G**
failing pr wants
state     since                  cpu    memory           disk           details
#0   running   2023-03-15T18:39:19Z   0.2%   157.3M of 512M   **1.1G of 1.5G**
Add disk_quota = 1500 to worker app
make env …
=> Increase disk quota for worker app

terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/production.tfvars.json, terraform/workspace_variables/qa.tfvars.json, terraform/workspace_variables/sandbox.tfvars.json, terraform/workspace_variables/staging.tfvars.json
find2 routes were used for the find migration to publish,
but they can be removed now as that's complete.
Remove find2 routes from terraform
make env deploy-plan 
deploy review app
=> Remove find2 routes

terraform/modules/paas/main.tf
Need to increase the disk quota for the webapp, as we alert at 60% usage, and we are now at 77%
i.e. using 1.1G of 1.5G
This PR increases the disk quota to 2G
Increase webapp disk quota
make env deploy-plan
deploy review app
=> Increase webapp disk quota to 2G

app/views/layouts/_find_footer.html.erb
Fallout from govuk component major version bump
Changed it
The footer is there.
https://find-pr-3433.london.cloudapps.digital/
=> [1168] Fixed missing footer

app/forms/publish/location_form.rb, app/models/site.rb, config/locales/en.yml, spec/features/publish/managing_locations_spec.rb, spec/features/support/providers/locations/creating_multiple_locations_spec.rb, spec/features/support/providers/locations/managing_locations_spec.rb, spec/models/site_spec.rb, spec/support/page_objects/publish/location_new.rb, spec/support/page_objects/sections/location_form.rb
Add a presense validation to the town or city field in locations.
- Add presence validation to town or city field 
- Allow tests to pass validation
=> Add validation to town city

app/controllers/concerns/success_message.rb, app/controllers/support/locations_controller.rb, app/controllers/support/providers/locations/check_multiple_controller.rb, app/controllers/support/providers/locations/new_multiple_controller.rb, app/decorators/provider_decorator.rb, app/decorators/site_decorator.rb, app/views/support/providers/locations/check_multiple/show.html.erb, app/views/support/providers/locations/new_multiple/show.html.erb, config/locales/en.yml, config/routes/support.rb, spec/features/support/providers/locations/creating_multiple_locations_spec.rb
The confirm page for the multiple locations flow and felshing out the change links and back links on the confirm and show pages. 
- Add view, routes, controller
- Save and update db on submission of confirm form
- Cancel the operation on clicking the cancel button
- Enable the back links to redirect to the correct page.
- Enable the change links to work correctly
Click `Add multiple locations` on support, enter a couple of rows of information. Submit the form, ensure the subsequent forms pass validation and submit those too. You should then arrive at the confirm page (as shown in the screenshot).
=> Bulk uploads confirm and save csv locations

app/components/find/courses/contents_component/view.html.erb, app/components/find/courses/contents_component/view.rb, app/components/find/courses/entry_requirements_component/view.html.erb, app/controllers/publish/courses/degrees/grade_controller.rb, app/controllers/publish/courses/degrees/start_controller.rb, app/controllers/publish/courses/degrees/subject_requirements_controller.rb, app/controllers/publish/courses/gcse_requirements_controller.rb, app/views/publish/courses/degrees/grade/edit.html.erb, app/views/publish/courses/degrees/start/edit.html.erb, app/views/publish/courses/degrees/subject_requirements/edit.html.erb, app/views/publish/courses/gcse_requirements/edit.html.erb, spec/components/find/courses/entry_requirements_component/view_preview.rb, spec/components/find/courses/entry_requirements_component/view_spec.rb, spec/features/publish/viewing_a_course_preview_spec.rb
To give providers a clearer view on which information they provide and which is generated by the service, we’re updating the course preview page to show missing information before a course is published.
**This PR relates to do the entry requirement section for "Degree and GCSE".**
- Utilise `course_preview_missing_information` feature flag
- Use the `MissingInformationComponent` to generate inset text linking to the relevant page on Publish if there is no content.
- Add dynamic back link (dependent on whether you come from preview or description)
Create a bare bones course and click the preview button. Check that the inset text is displayed. Click the link and fill in some information. Now the information you filled in should be displayed.
Should we gaurd against showing this on live …
=> Course preview missing information (Degree and GCSE)

app/components/find/courses/fees_component/view.html.erb, app/controllers/publish/courses/base_funding_type_controller.rb, app/controllers/publish/courses/fees_controller.rb, app/views/publish/courses/fees/edit.html.erb, spec/features/publish/viewing_a_course_preview_spec.rb
Course preview
Added missing information component
1. Create a fee-based course and preview it
2. Click on the `Enter details about fees and financial support`
3. The ` Course length and fees ` page 
- Check the `back` link  
- Check the valid form submission take you to the preview page
- Check after invalid form submission that the above two items still works
https://publish-teacher-training-pr-3456.london.cloudapps.digital/publish/organisations/2A2/2023/courses
=> [1152] Course preview fees and financial support

Dockerfile
Current libcrypto version has a snyk vulnerability
Updated to 1.1.1t-r3, and removed the pinned versions for pkgconf and git, as fixed in the base image
Update Dockerfile
Check build passes SNYK scan
=> Removed pinned pkg versions as now in base image

app/views/publish/providers/schools/_school.html.erb, app/views/publish/providers/schools/index.html.erb, app/views/support/schools/index.html.erb
We used to show a red missing text for schools with no URN but we need to update to the default placeholder we're now using.
https://trello.com/c/aOJdtBAI/1199-bug-school-urn-placeholder-text
Before:
After:
=> [1119] Fix school urn empty text
