.github/actions/smoke-test/action.yml
.tool-versions
Dockerfile
Gemfile
Gemfile.lock
package.json

Bumping to Ruby 3.2.0 to enable YJIT for performance improvements to the language. Also bumps Node to current stable LTS
Bumps relevant files

[xxx] Bump Ruby 3.2.0 and Node 18.x

---

app/views/support/providers/schools/new_multiple/show.html.erb
app/views/support/schools/_form.html.erb

[xxx] Fix URN hint text link

---

app/components/find/courses/contents_component/view.html.erb
app/controllers/publish/providers_controller.rb
app/views/find/courses/_train_with_disabilities.html.erb
app/views/publish/courses/preview.html.erb
app/views/publish/providers/about.html.erb
spec/features/publish/viewing_a_course_preview_spec.rb

To give providers a clearer view on which information they provide and which is generated by the service, we’re updating the course preview page to show missing information before a course is published.
Within the “Training with disabilities and other needs” section, we need to create a component which will render information about the course provider’s Training with disabilities and other needs field.
https://publish-courses-prototype.herokuapp.com/sign-in
✅ Make sure all information from the Trello card is in here
✅ Attach to Trello card
✅ Rebased main
✅ Cleaned commit history
✅ Tested by running locally
n/a Inform data insights team due to database changes

1154 course preview training with disabilities and other needs

---

app/controllers/pages_controller.rb
app/views/pages/add_an_organisation.html.erb
app/views/pages/add_and_remove_users.html.erb
app/views/pages/change_an_accredited_provider_relationship.html.erb
app/views/pages/course_summary_examples.erb
app/views/pages/help_writing_course_descriptions.html.erb
app/views/pages/how_to_use_this_service.html.erb
app/views/pages/roll_over_courses_to_a_new_recruitment_cycle.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/how_to_use_this_service_spec.rb
spec/features/view_pages_spec.rb

Updating the structure and content of our guidance pages. The link for this sits in the footer of Publish.
- Reorganise guidance pages within a single index page
- Link to each guidance page from the index page
- Add breadcrumbs on guidance pages
- Skip authentication for these pages
- Add feature test to test H1's and breadcrumbs
- Click on [this link](https://publish-teacher-training-pr-3491.london.cloudapps.digital/how-to-use-this-service)
- Click on `How to use this service` in the footer in Publish
- Try out all the links
- Check if the content is correct
- Check that the breadcrumbs work as expected
- Check that new URL's are what we want them to be

Add guidance pages to the how to use this service page

---

app/helpers/navigation_bar_helper.rb
app/views/publish/training_providers/courses/index.html.erb
app/views/publish/training_providers/index.html.erb
config/locales/en.yml
spec/features/publish/primary_nav_spec.rb
spec/support/page_objects/publish/primary_nav.rb

For APs, we need to update the wording in the nav bar to view their **training partners**.

[xxx] Update wording based on prototype for training partners

---

terraform/custom_domains/environment_domains/workspace_variables/find_pentest.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_pentest.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json
terraform/custom_domains/infrastructure/workspace_variables/find.tfvars.json

Remove the `multiple_hosted_zones` variable as the find and publish domains don't have education.gov.uk equivalents.
1. Remove the `multiple_hosted_zones` variable from the find and publish DNS zone configuration
2. Fix the find DNS zone name
Check for typos

236 find pub dns fixes

---

app/controllers/publish/providers_controller.rb
app/forms/publish/provider_contact_form.rb
app/forms/support/provider_form.rb
app/models/provider.rb
app/validators/ukprn_format_validator.rb
config/locales/en.yml
spec/factories/providers.rb
spec/forms/support/provider_form_spec.rb
spec/models/provider_spec.rb
spec/validators/ukprn_format_validator_spec.rb

We are tightening the validation for UKPRN, as these should begin with a 1. There are several instances in the database where they do not. Tightened validation should try to help prevent these from getting into the database in future. 
- Tighten validation on UKPRN, preventing any value that does not begin with a 1 and is not 8 integers from being saved. 
- Change the content on the validation message
- Attempt to change the UKPRN to a non valid entry in the various places that we ask the question.

Tighten UKPRN validation

---

app/views/publish/courses/accredited_body/_provider_search_field.html.erb

Hint text is incorrectly displayed on the accredited provider (AP) page. 
This is a quick temp fix as adding another AP will be removed from here soon.
:shipit:

Remove incorrectly displayed hint text

---

config/settings.yml
config/settings/development.yml
config/settings/review.yml
spec/components/find/courses/about_schools_component/view_spec.rb

`course_preview_missing_information`
Amended `course_preview_missing_information` to be true

[xxxx] Amended `course_preview_missing_information` to be true

---

terraform/workspace_variables/staging.tfvars.json

It alerts frequently as memory usage is frequently 60-80%
Double staging webapp memory
Check memory usage on https://grafana-bat.london.cloudapps.digital/d/eF19g4RZx/cf-apps?orgId=1&refresh=10s&var-SpaceName=bat-staging&var-Applications=publish-teacher-training-staging

Increase staging webapp memory

---

app/forms/publish/provider_contact_form.rb
config/locales/en.yml
spec/forms/publish/provider_contact_form_spec.rb

The provider details address form was recently updated to support address line 3. It was discovered that the form did not contain any validation.
Add validation to the address. The following are required:
address line 1
town or city
postcode
website
Done when
the address form contains validation for address line 1, town or city, website and postcode
postcode is a valid format

[1257] add validations to form

---

app/components/course_preview/missing_information_component.rb
app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/about_schools_component/view.rb
app/components/find/courses/entry_requirements_component/view.html.erb
app/components/find/courses/entry_requirements_component/view.rb
app/components/find/courses/fees_component/view.html.erb
app/components/find/courses/fees_component/view.rb
app/helpers/preview_helper.rb
app/views/find/courses/_about_course.html.erb
app/views/find/courses/_about_the_provider.html.erb
app/views/find/courses/_train_with_disabilities.html.erb
spec/components/course_preview/missing_information_component_preview.rb
spec/components/course_preview/missing_information_component_spec.rb

The incomplete section inset link was found on Find. This component is for preview only.
Add a gaurd to prevent the component rendering on Find
Check that the component no longer renders in the review app. 
- Course on preview: https://publish-teacher-training-pr-3534.london.cloudapps.digital/publish/organisations/17B/2023/courses/Q902/preview
- Find the course above on Find, following this link and ensure the component does not render: https://find-pr-3534.london.cloudapps.digital

[1254] Add guard to prevent rendering on Find

---

app/forms/publish/provider_contact_form.rb
app/forms/support/provider_contact_form.rb
app/models/provider.rb
app/validators/phone_validator.rb
config/locales/en.yml
spec/forms/publish/provider_contact_form_spec.rb
spec/forms/support/provider_contact_form_spec.rb
spec/models/contact_spec.rb
spec/models/provider/validation_spec.rb
spec/validators/phone_validator_spec.rb

Tighten telephone validation and improve error messages. 
For consistency, we are bring our telephone validation pattern in line with Notify and Apply.
- Prevent users submitting the form without entering a phone number
- Prevent users entering invalid phone numbers, e.g letters
- Prevent users entering numbers which contain 15 numbers or more
- Prevent users entering numbers which contain 8 numbers or less
- Add new custom content in the validation for the errors above.
**Examples of telephone numbers which are permitted** 
```
'+447123 123 123',
'+407123 123 123',
'+1 7123 123 123',
'+447123123123',
'07123123123',
'01234 123 123 --()+ ',
'01234 123 123 ext 123',
'01234 123 123 x123',
'(01234) 123123',
'(12345) 123123',
'(+44) (0)1234 123456',
'+44 (0) 123 4567 123',
'123 1234 1234 ext …
```

Tighten telephone validation

---

app/views/find/courses/_about_the_provider.html.erb

Prevent H3 from rendering if no content.
- Preview version of course: https://publish-teacher-training-pr-3541.london.cloudapps.digital/publish/organisations/14B/2023/courses/2CMS/preview
- Find version of course: https://find-pr-3541.london.cloudapps.digital/course/14B/2CMS#section-about-provider

[xxxx] Prevent H3 from rendering if no content

---

app/components/accredited_provider.html.erb
app/components/accredited_provider.rb
spec/components/accredited_provider_preview.rb
spec/components/accredited_provider_spec.rb

Accredited body summary card component
Added accredited body summary card component
https://publish-teacher-training-pr-3542.london.cloudapps.digital/view_components/accredited_provider/default

[1269] Added accredited body summary card component

---

app/controllers/publish/providers/accredited_providers_controller.rb
app/views/publish/providers/accredited_providers/index.html.erb
app/views/publish/providers/accredited_providers/new.html.erb
app/views/publish/providers/accredited_providers/results.html.erb
config/routes/publish.rb
spec/features/publish/accredited_provider_spec.rb

Following from #3540, this PR builds out the `/new` pages. 
- We have a button on the AP tab for a lead school, which takes you to a page that allows you to search for an accrediting provider without autocomplete.
- The search returns a list of possible AP to choose from or returns the user back to the search to try a new term.
- After selecting an AP the search takes you to the next step upon submission.
The continue button in the last screenshot will take you back to the accredited providers page but won't currently show the acccredited provider added.

[1227] Providers add accredited provider (step 1 non js)

---

terraform/custom_domains/environment_domains/workspace_variables/find_pentest.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json

Tidy-up the domain configuration post Find DNS migration to Azure.
Revert the TTL for the Find domain to pre-migration values.
Remove the environment_tag which is no longer used.
Confirmed no changes apart from TTL values by running `make find ENV domains-plan`

Revert Find TTL, remove environment_tag

---

app/views/publish/providers/accredited_providers/index.html.erb
spec/features/publish/accredited_provider_spec.rb

We created the accredited provider summary component in #3542. This PR surfaces the component on the index page if there are accredited providers present.
Surface the accredited provider component on the index page if there are accredited providers present.
- View a provider with accredited providers.
- View a provider without accredited providers.

[1277] Providers render the accredited provider summary component

---

app/models/provider.rb
app/views/publish/providers/accredited_providers/index.html.erb
spec/features/publish/courses/new_accredited_provider_spec.rb
spec/features/publish/edit_provider_details_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/models/provider/accredited_providers_spec.rb
spec/models/provider_spec.rb
spec/policies/provider_policy_spec.rb

Accredited bodies
Realign accrediting provider enrichment to be accredited bodies
The data flow direction has been reversed.
Instead of the course being the driver for who is the accredited provider, it is now from the the enrichments.
Course will no longer create relationship, dealt with by other PRs.
Enrichment will be creating the relationship, dealt with by other PRs.

[1272] Realign accrediting provider enrichment to be accredited bodies

---

app/controllers/concerns/support/clear_stashable.rb
app/controllers/support/providers/accredited_provider_search_controller.rb
app/controllers/support/providers/accredited_providers/checks_controller.rb
app/controllers/support/providers/accredited_providers_controller.rb
app/forms/support/accredited_provider_form.rb
app/helpers/support/goto_confirmation_helper.rb
app/services/stores/user_store.rb
app/views/support/providers/accredited_providers/checks/show.html.erb
app/views/support/providers/accredited_providers/new.html.erb
config/locales/en.yml
config/routes/support.rb
spec/features/support/providers/accredited_provider_search/searching_for_an_accredited_provider_spec.rb
spec/services/stores/user_store_spec.rb

https://trello.com/c/unxQot6W/1223-support-add-edit-accrediting-provider-step-2-about-ap
- Implements the second and final step of adding accredited providers in support
- Saving (final bit) is not implemented here, will be done in upcoming ticket
https://publish-teacher-training-pr-3546.london.cloudapps.digital/support/2023/providers/18689/accredited-providers
- Sign in as admin and search for an AP, enter some description and check the information is shown on the check your answers page
- Check you can change the info and return with updated information

[1223] Support: Add & Edit Accrediting Provider - Step 2 (About AP and Check Answers)

---

app/components/find/courses/about_schools_component/view.html.erb

https://trello.com/c/J2NXsN7O/1279-change-content-above-school-placements-list
- Update the copy used under the school placements section on Find
https://find-pr-3558.london.cloudapps.digital/

[1279] Update school placement copy

---

Gemfile.lock
Procfile.dev
app/controllers/publish/providers/school_search_controller.rb
app/javascript/publish/application.js
app/javascript/publish/autocomplete.js
app/views/publish/providers/school_search/new.html.erb

https://trello.com/c/fmC7d0ae/1292-bug-adding-a-school-in-publish
Fixes a bug in the school autocomplete search where selecting a school from the dropdown can still trigger a search. The fix is to set the school id form the JS and skip the search all together unless a value isn't selected which should then trigger a search.
- Go to the school search
- Try searching for the URN `144065`
- Assert that if you select the provider it doesn't trigger search
I've left the current implementation in where if you do not select a school but search a query where we match on one result then also skip the search otherwise we'll just show the results page with one option.

[1292] Fix school search bug

---

app/controllers/publish/providers/accredited_providers_controller.rb
app/views/publish/providers/accredited_providers/_can_remove.html.erb
app/views/publish/providers/accredited_providers/_cannot_remove.html.erb
app/views/publish/providers/accredited_providers/delete.html.erb
app/views/publish/providers/accredited_providers/index.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/accredited_provider_spec.rb

Following on from #3559, #3547, #3568 and #3573. This PR deals with removing an accredited provider which is already in the database. 
- Add the ability to remove AP if they are **not** used by the provider.
- Show a "not possible" view if the user attempts to remove an AP which **is** in use by the provider.
- Add a new AP on publish as a lead school and click the remove button to remove it. 
- Try to remove an AP on publish as a lead school where they accredit some courses.

[1235] Remove a accredited provider (providers)

---

app/controllers/publish/providers/accredited_providers_controller.rb
app/controllers/support/providers/accredited_providers_controller.rb
app/views/support/providers/accredited_providers/_can_remove.html.erb
app/views/support/providers/accredited_providers/_cannot_remove.html.erb
app/views/support/providers/accredited_providers/delete.html.erb
app/views/support/providers/accredited_providers/edit.html.erb
app/views/support/providers/accredited_providers/index.html.erb
config/locales/en.yml
config/routes/support.rb
spec/features/support/providers/accredited_providers_spec.rb

User need
As a user, I want to easily add accrediting providers to lead schools, so that these providers can be setup correctly in Publish
Why
This will give users and providers flexibility in managing their APs.
We need to implement the delete functionality for an AP in the new AP tab so they can be removed from the lead school
Done when
If an AP is removable, we are able to click the delete link and see a confirm page and remove the AP upon form submission
If an AP is not removable, we see a page with some content telling us the AP cannot be removed

[1229] delete support accredited provider

---

app/services/feature_service.rb
app/views/publish/courses/course_button_panel/_published.html.erb

`change vacancies` link on course show page
Remove `change vacancies` link on course show page

[1321] Remove change vacancies from course show page

---

app/views/publish/courses/_course_table.html.erb
app/views/publish/courses/_course_table_row.html.erb

User need
As a user, I want to be able to open or close my courses so candidates can be informed whether applications are open or not.
Why
We’re removing vacancies as research has shown they cause more confusion. We’re introducing a simple of concept to allow providers toggle whether courses are open or not.
Remove the ability to change vacancies on the course index
Done when
When the feature flag is set to on
Then there is no change vacancies on the course index

[1314] rm vacancies on course index

---

app/controllers/publish/courses/application_status_controller.rb
app/views/publish/courses/application_status/new.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/courses/editing_application_status_spec.rb

This is the confirm page for opening a course. The open button is out of scope for this card but this card deals with updating the database. 
- Add `get` and `post` route
- Add controller and view
- Add logic to update database on update action
Try it out on the review app by visiting `publish/organisations/{provider_code}/{recruitment_cycle_year}/courses/{course_code}/open`

[1315] Add applications open confirm page

---

app/controllers/publish/courses/application_status_controller.rb
app/views/publish/courses/application_status/_body_text.html.erb
app/views/publish/courses/application_status/_headline.html.erb
app/views/publish/courses/application_status/new.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/courses/editing_application_status_spec.rb

User need
As a user, I want to be able to open or close my courses so candidates can be informed whether applications are open or not.
Why
We’re removing vacancies as research has shown they cause more confusion. We’re introducing a simple of concept to allow providers toggle whether courses are open or not.
Implement close course confirmation page
Done when
When the feature flag is set to on
Then there is a route for /publish/organisations/#{provider_code}/#{recruitment_cycle_year}/courses/#{course_code}/close
Then there is an close course confirmation page
Then there is an ability to set a course to be close
Then there is an appropriate business logic to prevent setting a course to be close
Then on success it will redirect to the …

[1317] close course page

---

app/decorators/application_decorator.rb
spec/features/publish/courses/editing_application_status_spec.rb

In line with the removing vacancies epic, this PR uses the new `application_status` to determine whether we render the open or closed status labels. 
If feature flag is enabled, use the new column to decide which status tags to render.
Open and close a course

[1318] `status_tag` depend on `application_status`

---

app/controllers/publish/courses/accredited_provider_controller.rb
app/services/courses/creation_service.rb
app/services/publish/course_creation_step_service.rb
app/services/workflow_step_service.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/accredited_provider/edit.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/providers/about.html.erb
app/views/publish/providers/details.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/courses/new_accredited_provider_spec.rb
spec/features/publish/edit_provider_details_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/services/workflow_step_service_spec.rb

If only one AP is associated with a lead school, when adding a course the AP step should be skipped. On the summary page there should not be a change link to change the AP
If there is more than one AP associated with a lead school, when adding a course the AP step should be shown as per normal behaviour. On the summary page there should be a change link to change the AP.
Both of the above should apply to their respective edit pages (course details edit)
Remove the existing row for adding information about their AB from the org details page for a lead school
Links to research, designs, etc
The prototype for this work can be found [here](https://publish-courses-prototype.herokuapp.com/organisations/96d90282-3ce7-4fc7-aa60-e03d7bf8a0f1/cycles/2023/schools). To be able to see this …

1236 providers modify course flow based on ap availability

---

app/components/course_preview/missing_information_component.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/providers/about.html.erb
app/views/publish/providers/details.html.erb
config/settings/qa.yml
spec/components/course_preview/missing_information_component_spec.rb

Handles a few edge cases where turning on/off the AP search flag creates some weird side effects. The flag when off should still maintain existing functionality.

[xxx] Fix the AP flag behaviour

---

app/serializers/api/public/v1/serializable_course.rb
docs/source/release-notes.html.md.erb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/serializers/api/public/v1/serializable_course_spec.rb
swagger/public_v1/api_spec.json
swagger/public_v1/component_schemas/CourseAttributes.yml

We added `application_status` as a new column on the course table. This PR exposes the column on the public API.
- Expose `application_status` column as an attribute on the public API.
- Update docs.
- Public API: `http://publish.localhost:3001/api/public/v1/recruitment_cycles/2023/providers/{provider_code}/courses/{course_code}`
- https://publish-teacher-training-pr-3605.london.cloudapps.digital/docs/api-reference.html#schema-courseattributes

[1284] Expose application status on the API

---

Dockerfile

Fix for:
https://security.snyk.io/vuln/SNYK-ALPINE315-CURL-5561304
https://security.snyk.io/vuln/SNYK-ALPINE315-CURL-5561305
https://security.snyk.io/vuln/SNYK-ALPINE315-CURL-5561307
Manually install the fixed version of libcurl `libcurl=8.1.2-r0`

Bump libcurl version to fix CVE-2023-28322

---

Dockerfile

Bump libcrypto1.1 version to fix CVE-2023-2650
Update `libcrypto1.1` to version `1.1.1u-r0`

Bump libcrypto1.1 version to fix CVE-2023-2650

---

app/controllers/publish/providers/study_sites_controller.rb
app/forms/publish/school_form.rb
app/forms/support/school_form.rb
app/views/publish/providers/study_sites/_form.html.erb
app/views/publish/providers/study_sites/edit.html.erb
app/views/publish/providers/study_sites/new.html.erb
config/locales/en.yml
spec/features/publish/managing_study_sites_spec.rb

For this ticket we’ll need to add a way to update existing study sites from their show pages.
Done when
I can update any of my study site’s information from the study sites index page
GOTO study sites index, click on the name link and update away!

[1325] update study sites

---

app/components/find/courses/apply_component/view.html.erb
app/components/find/courses/apply_component/view.rb
app/components/find/courses/contents_component/view.html.erb
app/models/course.rb
app/views/publish/courses/_course_table_row.html.erb
app/views/publish/courses/preview.html.erb
spec/components/find/courses/apply_component/view_spec.rb
spec/components/find/courses/contents_component/view_preview.rb
spec/components/find/courses/contents_component/view_spec.rb
spec/factories/courses.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/models/course_spec.rb

https://trello.com/c/tMH6Iwbq/1362-issue-with-publish-closed-courses-are-open-and-open-open-courses-closed
The apply button is still lingering off some old vacancy logic so causing confusion to providers with a warning message being incorrectly shown.
- Update the logic to render apply button
- Also revert the view logic to align application status but update the underlying method as it contains some other rules around the open date and the course being findable
- Open/Close a course and check apply button/warning text is shown as expected

[1362] Fix apply button logic

---

app/services/sites/copy_to_course_service.rb
spec/services/sites/copy_to_course_service_spec.rb

`vac_status` from CopyToCourseService
Remove it
:shipit:

[1332] Remove `vac_status` from CopyToCourseService

---

app/helpers/study_sites_helper.rb
app/models/study_site_placement.rb
app/views/publish/providers/study_sites/delete.html.erb
app/views/publish/providers/study_sites/index.html.erb
config/locales/en.yml
config/routes/publish.rb
config/rubocop/rspec.yml
config/settings/review_aks.yml
spec/factories/study_site_placements.rb
spec/features/publish/managing_study_sites_spec.rb
spec/features/publish/searching_for_a_study_site_spec.rb
spec/models/study_site_placement_spec.rb

https://trello.com/c/lzMP9YbB/1323-remove-study-sites
- Implements study site removal logic
- Add a study site
- Assign it to the course (not done yet, needs to be manual in the console)
- Try to remove it (then do the same without assigning it to any course)

[1323] Implement study site removal

---

app/views/publish/courses/confirmation.html.erb

We have a allocations row appearing on the summary page for fee paying rolled over courses. This is redundant and we no longer require it, so we are removing it.
:shipit:

[1373] rm redundant allocations row

---

app/services/courses/copy_to_provider_service.rb
app/services/providers/copy_to_recruitment_cycle_service.rb
app/services/rollover_provider_service.rb
app/services/sites/copy_to_course_service.rb
app/services/sites/copy_to_provider_service.rb
spec/services/courses/copy_to_provider_service_spec.rb
spec/services/providers/copy_to_recruitment_cycle_service_spec.rb
spec/services/rollover_provider_service_spec.rb
spec/services/rollover_service_spec.rb
spec/services/sites/copy_to_course_service_spec.rb
spec/services/sites/copy_to_provider_service_spec.rb

https://trello.com/c/TfW7KIQp/1364-add-study-sites-to-rollover-script
- Adds a provider and course's study sites to the rollover process
Has to be tested manually.

[1364] Add study sites to rollover script

---

app/models/course.rb
app/services/courses/content_status_service.rb
spec/features/publish/viewing_a_course_spec.rb
spec/models/course_spec.rb
spec/services/courses/content_status_service_spec.rb
spec/services/courses/copy_to_provider_service_spec.rb

Currently when you create a new course in the new cycle it appears as rolled over. It should be draft.
- Make new courses created in the new cycle draft by default 
🚢

[1375] return draft if enrichment is blank

---

Dockerfile

Bump pkgconf version to fix CVE-2023-24056
Update pkgconf to version 1.8.1-r0

Bump pkgconf version to fix CVE-2023-24056

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/about_schools_component/view.rb
app/components/find/courses/contents_component/view.html.erb
config/rubocop/rspec.yml
spec/components/find/courses/about_schools_component/view_preview.rb
spec/components/find/courses/about_schools_component/view_spec.rb
spec/components/find/courses/contents_component/view_spec.rb
spec/decorators/course_decorator_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/support/page_objects/publish/course_preview.rb

https://trello.com/c/UI9KpAab/1326-show-study-sites-in-publish-course-preview-page
- Updates the course preview and find course details page to show study sites
- Also updates the section copy based on the prototype/design history
- Add study site sites
- Add to course (manual as ticket is in flight) 
- Check the preview

[1326] Add study sites to find course show page

---

app/views/publish/courses/details.html.erb
app/views/publish/courses/index.html.erb
app/views/publish/courses/show.html.erb

We have an issue where courses opened or closed on Publish wont be reflected on Apply.
- Add a notfication banner to course index page
- Add a notfication banner to course show page

[263] Add a notification banner to publish

---

Gemfile
Gemfile.lock

We are getting build failures on Publish due to this: https://github.com/ilyakatz/data-migrate/issues/267
We need to downgrade so that we can continue deploying.

[268] Downgrade data_migrate to version 9

---

app/models/course.rb

Removing the validation from study sites as providers are unable to publish courses. 
We will need to add this back but only enforce from the next cycle (when the study sites feature will also be launched)
:shipit:

[xxxx] Remove validation from study_sites

---

app/controllers/publish/courses/study_sites_controller.rb
app/helpers/navigation_bar_helper.rb
app/helpers/recruitment_cycle_helper.rb
app/helpers/view_helper.rb
app/models/course.rb
app/services/workflow_step_service.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/courses/index.html.erb
app/views/publish/courses/study_sites/edit.html.erb
config/locales/en.yml
spec/features/publish/add_course_button_spec.rb
spec/features/publish/course_confirmation_spec.rb
spec/features/publish/courses/editing_study_sites_spec.rb
spec/features/publish/e2e/new_course_spec.rb
spec/models/course/update_valid_spec.rb

We are enforcing providers to attach study sites to courses after rollover. This will mean before a provider can see the add course button, they will need to have created at least one study site. 
When the "Add course" button appears, it will be a requirement for providers to attach at least one study site when creating a course. 
Show Add course button under the following conditions:
- If it's the current cycle
- if the provider has any study sites attached
- if the `study_sites` feature flag is off
Enforce validation of at least one study site on courses for the next cycle
Remove the study sites flow from the current cycle
May be easier to screenshare, as rollover hasn't been done on the review app.

[14] Enforce study sites post rollover

---

bin/setup
guides/setup-development.md

Simplify developer setup instructions.
Encourage developers to use `./bin/setup` in order to initialise the application locally

Simplify dev setup instructions

---

app/controllers/publish/courses/skilled_worker_visa_sponsorship_controller.rb
app/decorators/course_decorator.rb
app/models/course.rb
app/services/courses/assign_program_type_current_cycle_service.rb
app/services/courses/assign_program_type_service.rb
app/services/workflow_step_service.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/courses/funding_type/_form_fields.html.erb
spec/components/find/courses/financial_support/fees_and_financial_support_component/view_preview.rb
spec/features/publish/e2e/new_course_spec.rb
spec/requests/reporting_spec.rb
spec/services/course_reporting_service_spec.rb
spec/services/courses/assign_program_type_current_cycle_service_spec.rb

Enable all provide types to create salaried courses.
**Important note: This will have a downstream effect on Register in the next academic cycle.**
-  Replace apprenticeship step with funding type for SCITT's and Unis
- Add the following program types: `higher_education_salaried_programme`, `scitt_salaried_programme`
- Only enable these changes if in the next cycle
- You will either need a rolled over environment, or we can do a screenshare.

[283] Update funding type question for all provider types

---

app/components/find/courses/summary_component/view.html.erb
app/components/find/results/search_result_component.html.erb
app/decorators/course_decorator.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/features/find/search/course_results_spec.rb

One of the priorities for the initial teacher training (ITT) reforms is to make ITT less complex for providers, candidates and trainees.
We are improving how we show course funding information to make it easier for candidates to understand.
Replace the ‘Financial support’ section with ‘Fee or salary’ on the courses list and course details pages.
If the course is funded through fees, we show additional information:
- Bursaries and student finance are available if you’re eligible
- Scholarships or bursaries, as well as student finance, are available if you’re eligible
- Student finance is available if you’re eligible
Navigate to various courses on the review app, and check that the funding information is displayed correctly for each course.

[319] Update financial support row in Find search results

---

app/controllers/publish/courses/study_sites_controller.rb

Require all Course creations to explicitly specify StudySites for the new course.
The previous flow was to automatically assign the study site if only one existed.
Now, the form is required to be completed by the admin even in only one study site exists.
review
https://trello.com/c/zkJ8XYko/317-dont-skip-the-study-site-step

Allow all Providers to add StudySites

---

.github/workflows/database-restore.yml

The restore-aks job runs alongside the backup job so it will restore the previous days sanitised backup not the current day.
Making the restore-aks job depend on the backup ensures the current days backup is used.
Make the restore-aks job depend on the backup job

[434] Add dependency on backup for AKS QA and staging

---

Gemfile
config/application.rb
spec/controllers/find/courses_controller_spec.rb
spec/rails_helper.rb
spec/support/mock_logger.rb

Rails Semantic Logger appears to less useful in development.
Much of the output is dedicated to printing the timestamp and the
server details on each line. This is not particularly useful in
development.
Also, the default logger conveys the seapartion of requests more
distinctly by separating each new http request with a new line.
This is particularly useful when the application triggers over three
consecutive redirects.
Use Rails ActiveSupport::Logger in development environment.
This is achieved by moving the gem declaration into only the production, qa, sandbox groups in the Gemfile
Ensure that the changes only affect the development environment.

Use Rails default logger in development environment

---

app/views/publish/providers/school_search/new.html.erb
app/views/publish/providers/study_site_search/new.html.erb
app/views/publish/providers/study_sites/_form.html.erb
app/views/publish/providers/study_sites/edit.html.erb
app/views/publish/providers/study_sites/new.html.erb

Fix a snag from implementing the Study Site form.
Wrap each of the headings in the `new` and `edit` templates in a `content_for` block. This block can be evaluated within the form and the content placed above below the error message.
This important documentation was consulted when deciding how to create the layout for the PR.
https://design-system.service.gov.uk/styles/layout/

Move Error summary for Study Site forms above the heading

---

config/settings.yml
config/settings/development.yml
config/settings/review.yml
config/settings/review_aks.yml
spec/features/publish/add_course_button_spec.rb

Activating the study sites feature in all environments. 
Note that study sites have a after 2023 cycle check so it will only be active in the next cycle.
🚢

Activate study sites in all environments

---

app/controllers/publish/courses/study_sites_controller.rb
app/forms/publish/course_study_site_form.rb
app/models/course.rb
app/views/publish/courses/study_sites/edit.html.erb
config/locales/en.yml
spec/forms/publish/course_study_site_form_spec.rb

There is a bug which causes a study site validation to kick in when the course doesn’t have at least one study site attached and other attributes on the course basic details are updated.
- Remove the presenece validation on update from the course.
- Use a form object to validate presence when updating the form. 
**Product:** Ask for a screenshare as study sites are only active in the next cycle
**Dev:** Ensure you are in the next cyclea and study sites are activated, then head to a courses basic details page and attempt to update the study site with no sites selected.

[353] Fix study sites validation bug

---

app/components/add_course_button.html.erb
app/components/add_course_button.rb
app/views/publish/courses/index.html.erb
spec/components/add_course_button_preview.rb
spec/components/add_course_button_spec.rb
spec/features/publish/add_course_button_spec.rb

Before adding a course in the next cycle, you will have to have filled in some of the organisation details. If the organisation details have not been filled in the "Add course" button will be hidden. 
Hide the add course button under the following conditions:
- If the provider doesn't have any accredited providers attached and the provider is not an accredited provider
- If the provider doesn't have any schools
- If the provider doesn't have any study sites
- Link to these sections if the add course button is hidden
Product: As this is only enabled in the next cycle, it will be easiest to do a screenshare. 
Dev: As above or you can rollover your local environment and be sure to activate the `study_sites` feature flag.

[318] Hide add course button when organisation details are missing (next cycle only)

---

app/views/publish/courses/fees/edit.html.erb

https://trello.com/c/gJ9LBS6V/357-add-full-stop-to-financial-support-content
I noticed a missing full stop.
I added a missing full stop.
Did I miss any tests?

High value content tweak

---

.github/workflows/scheduled-aks-db-restore.yml

We already restore GOV.UK PaaS sandbox data to AKS nightly. We also need to restore the production database too.
Add production to the matrix of environments we create the restore job for.

[434] Add production to the daily paas to aks db restore

---

.github/workflows/build-and-deploy.yml

Make sandbox AKS depend on prod AKS. Currently it depends on GOV.UK PaaS prod.
Make sandbox AKS depend on prod AKS

Make sandbox AKS depend on prod AKS

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/about_schools_component/view.rb
app/controllers/concerns/copy_course_content.rb
app/controllers/publish/courses/course_information_controller.rb
app/controllers/publish/courses/fees_controller.rb
app/controllers/publish/courses/requirements_controller.rb
app/decorators/course_decorator.rb
app/models/course.rb
app/services/courses/content_status_service.rb
app/services/courses/copy.rb
app/views/find/courses/_about_course.html.erb
app/views/find/courses/_interview_process.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/_course_length_field.html.erb
app/views/publish/courses/course_information/edit.html.erb
app/views/publish/courses/fees/edit.html.erb
app/views/publish/courses/requirements/edit.html.erb
config/locales/en.yml
spec/components/find/courses/about_schools_component/view_preview.rb
spec/factories/course_enrichments.rb
spec/features/publish/courses/copy_from_list_spec.rb
spec/features/publish/courses/publishing_a_course_spec.rb
spec/models/course_spec.rb
spec/services/courses/copy_spec.rb

There are currently two bugs existing in Publish:
**Bug no1:**
The ordering of `course_enrichments` (_an enrichment stores additional information about a course for things like the interview process_) is not consistent across environments and there are currently two approaches to returning the latest `course_enrichment`:
- The **first approach** is to use `@course.enrichments.last[:about_course]`
- The **second approach** is to use `@course.about_course`
The first approach is what causes the inconsistency – locally this returns the expected result but in all envs up to prod it does not. The second is consistent because it utilises the `scope :most_recent, -> { order(created_at: :desc, id: :desc) }` scope on the `CourseEnrichment` model.
On this page we're using the second approach:
On …

Fix the Publish course information bug

---

app/components/add_course_button.rb
app/views/publish/courses/course_button_panel/_published.html.erb
spec/components/add_course_button_spec.rb
spec/features/publish/add_course_button_spec.rb
spec/features/publish/viewing_a_course_spec.rb

Following a review of the rollover environment there a a few small snags that we should address.
- The links that show before you can create a course e.g “Add a study site” etc should have lowercase “a”
- The order of the links above should follow the same order as the nav bar items
- For scheduled courses it should have a preview link, not a view on Find link

[362] A few rollover snags

---

app/forms/accredited_provider_form.rb
spec/forms/accredited_provider_form_spec.rb

We are unable to edit accredited providers in the next cycle, this is the fix.
Make the recruitment cycle dynamic.
:shipit:

[366] Fix editing AP in next cycle

---

app/forms/publish/subject_requirement_form.rb
app/views/publish/courses/degrees/_additional_degree_subject_requirements.html.erb
app/views/publish/courses/degrees/subject_requirements/edit.html.erb
config/locales/en.yml
spec/forms/publish/subject_requirement_form_spec.rb

Restrict degree subject requirement to 250 words
Attempt to submit the degree subject requirement form with over 250 words

[358] Add degree subject requirement validation

---

app/models/course.rb
spec/models/course_spec.rb

There is a bug in the next cycle which prevents users from being able to delete draft courses with study sites attached.
Destroy all the associated StudySitePlacement records when a Course is destroyed.
Try to delete a course with a study site attached, preferably in the next cycle.

[374] Destroy StudySitePlacements with Course

---

app/helpers/find/location_helper.rb

This blows up locally – we've just never hit it on prod:
The translation should actually be `en.find.fields.provider`:
`config/locales/find.yml:37`
but it's not an error anyway.
🚮

Remove unnecessary check from find

---

app/controllers/concerns/filter_parameters.rb
app/controllers/find/search/age_groups_controller.rb
app/controllers/find/search/subjects_controller.rb
app/controllers/find/search/visa_status_controller.rb
app/forms/find/visa_status_form.rb
app/views/find/result_filters/location/_form.html.erb
app/views/find/search/locations/_form.html.erb
app/views/find/search/subjects/_primary_subjects.html.erb
app/views/find/search/subjects/_secondary_subjects.html.erb
app/views/find/search/visa_status/new.html.erb
config/locales/find.yml
config/routes/find.rb
spec/features/find/result_page_filters/engineers_teach_physics_spec.rb
spec/features/find/search/across_england/further_education_spec.rb
spec/features/find/search/across_england/primary_spec.rb
spec/features/find/search/across_england/secondary_spec.rb
spec/features/find/search/editing_a_search_spec.rb
spec/features/find/search/location_options_spec.rb

We're seeing a high number of candidates that are applying for courses that won't sponsor their visa. Whilst we do have a visa sponsorship filter available on Find, it's appearing at the bottom of the page. 
We're going to make this more prominent by introducing a new page to the Find journey that will then pre filter the courses based on the candidates visa requirements.
|New page | Hitting validation|
|---|---|
|<img width="674" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/47917431/ce70a641-6f51-4c19-8b5a-981631774368">|<img width="910" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/47917431/e2f1d4c4-6213-478a-b80c-7f1dad166e5c">|

Find visa status page

---

app/helpers/navigation_bar_helper.rb
spec/helpers/navigation_bar_helper_spec.rb

Ensure accredited provider tab appears unless the provider is an accredited provider.
Check a HEI and ensure that it does not have the AP tab. Downgrade that org on support and check that AP tab now appears.

[379] Ensure accredited provider tab appears

---

.github/workflows/build-and-deploy.yml
.github/workflows/database-restore.yml
.github/workflows/deploy.yml
.github/workflows/smoke-test.yml
config/settings/qa_aks.yml
terraform/aks/workspace_variables/qa_aks.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_qa.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_qa.tfvars.json

Change required to migrate QA from GOV.UK PaaS to the Teacher Services Cloud AKS platform.
This builds an image where the QA AKS environment uses the proper QA domains and includes the DNS changes to point QA (for find and publish) and QA API (for publish) to the new AKS environment.
- Update the qa_aks environment configuration to use the qa domain. Previously qa2.
- Remove the existing CNAME records that are used by the GOV.UK PaaS environment
- Remove the qa2 and qa2.api front door configuration currently used by the QA AKS environment
- Add the CNAME record for QA, QA API to point to the previously provisioned front door endpoint

Migrate QA env to AKS

---

.github/workflows/build-and-deploy.yml

Now that AKS QA is the main QA environment, production should also depend on it in the deployment jobs.
Make the production environment depend on the AKS deployment jobs.

[504] Make PaaS prod depend on AKS

---

Gemfile
Gemfile.lock

The gem was added because the 2.10.0 release of `better_errors` broke
the build. A new release 2.10.1 fixed the issue and SASSC is no longer
needed in the application.
The css is compiled and included in the built gem.
Breaking Change: https://github.com/BetterErrors/better_errors/pull/498
Fix: https://github.com/BetterErrors/better_errors/pull/520

Remove SASSC gem

---

app/forms/accredited_provider_form.rb
spec/forms/accredited_provider_form_spec.rb

Providers in the next cycle are unable to add accredited providers. This is the fix

[388] Fix adding new ap's in the new cycle

---

app/models/site.rb
spec/models/site_spec.rb

Code is no longer in use and this is causing unecessary Sentry errors.
https://dfe-teacher-services.sentry.io/issues/4312626004/?alert_rule_id=11137790&alert_type=issue&project=1377944&referrer=slack

[378] Remove validation for code

---

terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json

This configures front door for the staging environment but crucially does not update the CNAME record.
- Add staging to find and publish domains, and staging.api to the publish domain
- Exclude the CNAME records to ensure the live service is not impacted
- `make find staging domains-plan` 6 additions with no CNAME record
- `make publish staging domains-plan` 12 additions with no CNAME records

[504] Prepare front door, DNS for staging AKS migration

---

app/controllers/api/public/v1/providers_controller.rb
app/serializers/api/public/v1/serializable_provider.rb
docs/source/release-notes.html.md.erb
spec/controllers/api/public/v1/providers_controller_spec.rb
spec/rails_helper.rb
swagger/public_v1/api_spec.json
swagger/public_v1/component_schemas/ProviderAttributes.yml
swagger/public_v1/component_schemas/ProviderFilter.yml

https://trello.com/c/nR0xM6aq/266-delete-providers-that-have-no-region-code-on-manage-and-dont-exist-on-publish
Apply/Manage needs a way to identify `Provider`s that have been discarded. The current API filters out discarded providers at the definition of the association between `RecruitmentCycle` and `Provider`. We can `unscope` this exclusion in the API for the purposes of returning discarded providers.
This is a non-breaking change to the API. API consumers do not need to be made aware of this change. It can be an undocumented feature if that is preferred.  There is probably no reason a consumer of the API would need to access discarded `Provider`s
Provider API accepts `filter[discarded]=true` which returns discarded Providers.
When the `filter[discarded]=true` is passed, only …

Filter for discarded providers in public API

---

app/components/course_preview/missing_information_component.rb
spec/components/course_preview/missing_information_component_spec.rb

The incomplete accredited provider preview link was trying to take the user to the edit page of a non existing accredited provider. If the accredited provider does not exist under the AP tab, we should redirect them to add an AP.
This is a temporary fix until we resolve our data rot.
Redirect the user to the add accredited provider journey if the accredited provider doesn't exist under the accredited provider tab.
- Click the link (as seen in the screenshot above): https://publish-review-3746.test.teacherservices.cloud/publish/organisations/2BY/2024/courses/2XNN/preview
- Should the content of the link be updated to reflect that we are now taking them on an "Add accredited provider" journey?

Fix incomplete accredited provider preview link

---

app/views/publish/courses/_basic_details_tab.html.erb
spec/features/publish/courses/adding_an_accredited_provider_to_an_existing_course_spec.rb
spec/features/publish/courses/adding_an_accredited_provider_to_an_unpublished_course_spec.rb

Providers which have been reclassified from an accredited provider to a non accredited provider in the new cycle have rolled over courses which do not have an accredited provider. We need to create a journey for them to add these.
Enable reclassified providers to add accredited providers
Reclassify an accredited provider to a non accredited provider using support, then navigate to that provider and try to assign an accredited provider to a course.

[392] Enable reclassified providers to add AP's

---

.github/workflows/build-and-deploy.yml
.github/workflows/database-restore.yml
.github/workflows/deploy.yml
.github/workflows/smoke-test.yml
config/settings/staging_aks.yml
terraform/aks/workspace_variables/staging_aks.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json

Change required to migrate staging from GOV.UK PaaS to the Teacher Services Cloud AKS platform.
This builds an image where the staging AKS environment uses the proper staging domains and includes the DNS changes to point staging (for find and publish) and staging API (for publish) to the new AKS environment.
- Removal of staging input and jobs from various GitHub action workflows and actions.
- Update the staging_aks environment configuration to use the staging domain. Previously staging2.
- Remove the existing CNAME records that are used by the GOV.UK PaaS environment
- Add the CNAME record for staging, staging API to point to the previously provisioned front door endpoint. This may fail first time unless the existing CNAME deletion happens quickly enough

[504] Migrate staging env to AKS

---

terraform/aks/workspace_variables/sandbox_aks.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json

Add monitoring resources to the AKS sandbox environment and configures front door for the sandbox environment but crucially does not update the CNAME record.
- Enable alerting for the `sandbox_aks` environment
- Add front door and certificate configuration of sandbox to find and publish domains, and sandbox.api to the publish domain
- Exclude the CNAME records to ensure the live service is not impacted
- Lower the TTL of the CNAME records for sandbox and sandbox.api across the two DNS zones
- `make sandbox_aks action-group-resources ACTION_GROUP_EMAIL=firstname.lastname@domain.com` to deploy the resource group and action group resources to support the monitoring resources
- `make sandbox_aks deploy IMAGE_TAG=current_image_tag` to see the plan of the monitoring resources that will be …

[504] Sandbox AKS migration prep

---

.github/workflows/build-and-deploy.yml

Ensure production only deploys when qa_aks and staging_aks succeed
Remove continue on error for test environment deployments

Ensure prod deploys with both test envs pass

---

terraform/custom_domains/environment_domains/workspace_variables/find_staging.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_staging.tfvars.json

We need to tidy-up the staging2 environment configuration now we have migrated from GOV.UK PaaS to AKS.
Remove the staging2 front door and associated DNS configurations.
Already applied as we had reached our limit of front door endpoint configurations for the publish profile.

Remove staging 2 front door configuration

---

app/components/accredited_provider.html.erb
app/controllers/publish/courses/accredited_provider_controller.rb
app/helpers/view_helper.rb
app/models/course.rb
app/models/provider.rb
app/views/publish/courses/accredited_provider/edit.html.erb
app/views/publish/providers/accredited_providers/index.html.erb
config/locales/en.yml
spec/controllers/publish/courses_controller_spec.rb
spec/features/publish/courses/add_accredited_provider_when_publishing_a_course_spec.rb
spec/features/publish/courses/publishing_a_course_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/course/publishable_spec.rb
spec/models/provider_spec.rb
spec/support/page_objects/publish/courses/accredited_providers.rb
spec/support/page_objects/publish/courses/new_accredited_provider.rb
spec/support/page_objects/publish/provider_accredited_providers_index.rb
spec/support/page_objects/publish/provider_accredited_providers_search.rb
spec/support/page_objects/publish/provider_courses_show.rb

[Validate a course has an accrediting provider](https://trello.com/c/Ox93dbSJ/393-itt-reform-prevent-publication-of-an-incomplete-course)
[Users can add accredited provider to their account when selecting an accredited provider for a course](https://trello.com/c/YsMU17Nu/404-when-publish-users-click-change-links-for-study-site-or-accredited-provider-in-course-description-and-they-only-have-1-surface-a)
**Course's accredited provider is no longer accredited.**
https://publish-review-3747.test.teacherservices.cloud/publish/organisations/1JE/2024/courses/3FNB
**Course has no accredited provider associated**
https://publish-review-3747.test.teacherservices.cloud/publish/organisations/1JE/2024/courses/2B76 (edited) 
When a course is published, the course must:
- have an accrediting provider …

Invalidate incomplete course on publish

---

.github/workflows/build-and-deploy.yml
.github/workflows/deploy.yml
.github/workflows/scheduled-aks-db-restore.yml
.github/workflows/smoke-test.yml
config/settings/sandbox_aks.yml
terraform/aks/workspace_variables/sandbox_aks.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json

Change required to migrate sandbox from GOV.UK PaaS to the Teacher Services Cloud AKS platform.
This builds an image where the sandbox AKS environment uses the proper sandbox domains and includes the DNS changes to point sandbox (for find and publish) and sandbox API (for publish) to the new AKS environment.
- Removal of sandbox input and jobs from various GitHub action workflows and actions.
- Update the sandbox_aks environment configuration to use the sandbox domain. Previously sandbox2.
- Remove the existing CNAME records that are used by the GOV.UK PaaS environment
- Add the CNAME record for sandbox, sandbox API to point to the previously provisioned front door endpoint. This may fail first time unless the existing CNAME deletion happens quickly enough

[504] Migrate sandbox to AKS

---

terraform/custom_domains/environment_domains/workspace_variables/find_sandbox.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_sandbox.tfvars.json

Ensure we have enough quota on the publish front door to prepare the production endpoints by removing the now redundant sandbox2 entries.
Remove the sandbox2 front door configuration.

[504] Remove sandbox2 front door configuration

---

app/services/user_associations_service/create.rb
spec/services/user_associations_service/create_spec.rb

Allow users to be added in the next cycle
If the next recruitment cycle is active, add the user to the next recruitment cycle provider in addition to the current recruitment cycle provider.
Try it on the review app.

Fix adding user in next cycle

---

app/components/find/results/results_component.html.erb
app/views/find/search/locations/_form.html.erb
spec/components/find/results/results_component_spec.rb

- Requests from Gemma in GIT, the links we use here currently serve no purpose
- Updated copy
- I've made this PR such that we can revert in September
- Does this work?

Update events links in Find as there are no events currently

---

app/models/course.rb
config/locales/en.yml
spec/features/publish/courses/add_accredited_provider_when_publishing_a_course_spec.rb
spec/models/course/publishable_spec.rb

Courses belong to an accredited provider. In the code, this association is labeled `accrediting_provider`. 
All references to a courses `accrediting_provider` must be phrased as `accredited` rather than accrediting in the UI.
Rails generates error messages based on the association name. Here we alias the association attribute to `accredited` and update the key in the locale file.
Any errors related to the courses accredited provider will describe use the correct terminology by default in the error messages.

Fix accrediting provider error text on Course

---

app/views/publish/courses/accredited_provider/edit.html.erb
app/views/publish/providers/accredited_providers/index.html.erb
spec/features/publish/courses/add_accredited_provider_when_publishing_a_course_spec.rb
spec/support/page_objects/publish/courses/accredited_providers.rb

https://trello.com/c/YsMU17Nu/404-when-publish-users-click-change-links-for-accredited-provider-in-course-description-and-they-only-have-1-surface-a-link-button-t
Update the user flow when adding accredited provider to their training provider account.
Govuk design standards require we change use a link instead of a button where the user wants to go to a place they can add a new accredited provider to their provider account.
The button and the link are grouped.
The link targets the accredited provider search page instead of the accredited provider index.

Add accredited provider button changed to link

---

app/services/courses/copy_to_provider_service.rb
spec/services/courses/copy_to_provider_service_spec.rb

Update rollover script to handle the correct `application_start_date`.
If the course `applications_open_from` date is the same as the current cycle `application_start_date` set the next recruitment cycle `application_start_date` as the course `applications_open_from` date 🤯 🤯 🤯 
You can try it with manual rollover in the review app. It should be easy to find a course with a `applications_open_from` date as the 11th of October. Currently this would be rolled over to the 11th of October the following year. With this change it be the 10th of October when rolled over.

[414] Update rollover script to handle the correct `application_open_from` date

---

Dockerfile

builds failing due to: https://security.snyk.io/vuln/SNYK-ALPINE315-PCRE2-5811559
As per:
```
How to fix?
Upgrade Alpine:3.15 pcre2 to version 10.42-r0 or higher.
```

Update pcre2 dockerfile

---

spec/features/find/switcher_cycles_spec.rb

Builds are failing:
This is because these tests are not frozen in time. The Apply 1 deadline banner has just gone live on production so these tests are failing because we never render the Apply 2 deadline banner due to the first branch of the `if` statement returning `true`.
Freeze the test at the start of the 2022 cycle.

Freeze cycle switcher specs

---

app/models/course.rb
spec/features/publish/courses/2024_itt_provider_market_reform/publishing_a_course_as_an_accredited_provider_spec.rb

We need to tweak earlier validations as accredited providers who publish courses will have an accredited provider value as ‘nil’ on the course. 
We should not prevent publication when the value is nil - in fact this should be the only situation where this happens.
Do not check for the presence of `accrediting_provider` on a `course` if the provider is accredited.

Allow accredited providers to publish courses

---

app/helpers/recruitment_cycle_helper.rb
app/services/user_associations_service/create.rb
spec/services/user_associations_service/create_spec.rb

Fixes for the add user flow.
https://dfe-teacher-services.sentry.io/issues/4347111016/?alert_rule_id=11137790&alert_type=issue&project=1377944&referrer=slack
- Fix it.
- Make developers happy (no more Sentry errors)
- Make users happy (they can add other users during rollover)
- Make support happy (they can support users during rollover)
- Play around with the functionaiity in the review app.
- Test Publish
- Test suppoort
- Test both cycles

[450] Fixes for the add user flow

---

app/services/user_associations_service/create.rb
spec/services/user_associations_service/create_spec.rb

Support encountered an error when creating a new organisation and adding a user before creating the organisation in the next cycle.
Although this wasn't blocking the users from being added, we should add a guard so we don't get an error.
https://dfe-teacher-services.sentry.io/issues/4377371108/?alert_rule_id=11137790&alert_type=issue&project=1377944&referrer=slack
- Add a guard to protect against `provider.users.nil?`
- Create a brand new org in one cycle using support without adding the org to the next cycle.
- Attempt to add a user to it, and it should work.
- If you try the same thing in QA you should get an error (although it will still work).

Add guard to handle no users

---

terraform/aks/workspace_variables/production_aks.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json

Add monitoring resources to the AKS production environment and configure front door for the production environment but crucially does not update the CNAME record.
- Enable alerting for the `production_aks` environment
- Add front door and certificate configuration of `www` to find and publish domains, and `api` to the publish domain
- Exclude the CNAME records to ensure the live service is not impacted
- Lower the TTL of the CNAME records for `www` and `api` across the two DNS zones
- `make production_aks action-group-resources ACTION_GROUP_EMAIL=firstname.lastname@domain.com` to deploy the resource group and action group resources to support the monitoring resources
- `make production_aks deploy IMAGE_TAG=current_image_tag` to see the plan of the monitoring resources that will be …

[504] Production AKS migration prep

---

app/controllers/publish/courses/applications_open_controller.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/applications_open/_form_fields.html.erb
app/views/publish/courses/applications_open/edit.html.erb
app/views/publish/courses/applications_open/new.html.erb
config/initializers/date_formats.rb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/courses/editing_applications_open_spec.rb
spec/features/publish/viewing_a_course_details_spec.rb
spec/forms/edit_course_form_spec.rb

We are enabling applications open date to be edited for courses in a `draft` or a `rolled_over` state.
- Surface the change link
- Add routes
- Fix validation error message
- Update text on submit button
- Disable change link on withdrawn courses
- Update the hint text so that the date is one that can actually be submitted (I've used the first date that applications are open)
- Add cancel link
- Go to a `draft` course or a `rolled_over` course in any cycle and update the applications open date within the basic details section. 
- Create a new course in any cycle and ensure the applications open question is still functioning the same.

[433] Enable editing of applications open date for draft courses

---

app/controllers/publish/courses/start_date_controller.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/start_date/edit.html.erb
config/routes/publish.rb
spec/features/publish/courses/editing_course_start_spec.rb
spec/features/publish/viewing_a_course_details_spec.rb

We are enabling applications open date to be edited for courses in a `draft` or a `rolled_over` state.
- Surface the change link
- Add routes
- Update text on submit button
- Add cancel link
- Go to a `draft` course or a `rolled_over` course in any cycle and update the course start date within the basic details section.

[433] Enable editing of start date for draft courses

---

app/controllers/api/accredited_provider_suggestions_controller.rb
app/controllers/publish/providers/accredited_provider_search_controller.rb
app/controllers/support/providers/accredited_provider_search_controller.rb
app/forms/accredited_provider_search_form.rb
app/javascript/publish/autocomplete/__snapshots__/accredited_provider.spec.js.snap
app/javascript/publish/autocomplete/accredited_provider.js
app/javascript/publish/autocomplete/accredited_provider.spec.js
app/services/accredited_providers/search_service.rb
app/views/publish/providers/accredited_provider_search/new.html.erb
config/routes/api.rb
spec/controllers/api/accredited_provider_suggestions_controller_spec.rb
spec/services/accredited_providers/search_service_spec.rb

The list of accredited providers is not recruitment cycle dependant. We need to make it dependant so that if an accredited provider in the current cycle is not an accredited provider in the next cycle, they are not seen in the list in the next cycle. 
More importantly, we need to ensure that providers who wern't accredited providers in the current cycle but are in the next cycle, are shown in this list - as this would prevent providers from adding and publishing courses. 
Pass in the recruitment cycle and generate the list of accredited providers based on the recruitment cycle.
- Go to a provider which is not an accredited provider in both cycles
- Check that they are not in the list when adding an accredited provider
- Change them to an accredited provider in one cycle
- Check that they …

[412] Populate accredited provider list based on recruitment cycle

---

terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json

Tidy-up old environment front door and DNS configurations.
Remove www3 and api3 records used for production AKS env.

Remove front door config used for migration env

---

Dockerfile

Fix for occasional Snyk step failures. In [this](https://github.com/DFE-Digital/publish-teacher-training/actions/runs/5952813434/job/16145642690) case libpq and libcrypto1.1.
We can search for the available packages in the [Alpine Linux package site](https://pkgs.alpinelinux.org/packages?name=&branch=v3.15&repo=&arch=&maintainer=).
We can check when the Ruby image we use was last updated to see if the packages will be part of the base image by default. Even if the alpine3.15 base image has been updated with the fixed packages, we use the [ruby:3.1-alpine3.15](https://hub.docker.com/_/ruby/tags?page=1&name=3.1-alpine3.15) image so we have to wait for that to be updated, or manually add the fixed packages as we are doing in this PR.
Currently the latest version of:
- libpq is 14.9-r0
- …

Update libpq to fix CVE-2023-39417

---

app/components/find/deadline_banner_component.html.erb
app/controllers/find/pages_controller.rb
app/services/find/cycle_timetable.rb
app/views/find/pages/cycle_has_ended.html.erb
spec/features/find/view_pages_spec.rb

Fixing the cycle switcher and updating our content on the banners and pages in line with multiple applications.
The cycle switcher was not working once we were in one of the "between" periods. The if statement would always return true for the first conditional because the second part of this "or" statement would always be true.
`current_cycle_schedule == :today_is_after_find_opens || Time.zone.now.between?(find_opens, apply_2_deadline)`
- Fix cycle switcher
- Update content on Find banners
- Update content on "Applications closed" page

[549] Update deadline banners/pages and fix cycle switcher

---

app/components/find/results/results_component.html.erb
app/views/find/search/locations/_form.html.erb
config/locales/find.yml
spec/components/find/results/results_component_spec.rb

Reverts DFE-Digital/publish-teacher-training#3755
Events are now back live on the GIT Website, so we can cleanly revert this PR to go back to promoting events.

Revert "Update events links in Find as there are no events currently"

---

app/services/subjects/financial_incentive_creator_service.rb
spec/services/subjects/financial_incentive_creator_service_spec.rb

Updates to financial incentives for the 2024 cycle.
**Note:** This PR doesn't seed the values. We will do that in a data migration in a follow up PR after rollover has ended and the new cycle has started. 
- Update the figures and subjects in line with the new list provided (see Trello ticket)
Compare the figures in the PR with the figures attached to the Trello card.

[579] Update financial incentives for 2024 cycle

---

app/helpers/navigation_bar_helper.rb
app/services/workflow_step_service.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
config/settings.yml
spec/components/add_course_button_spec.rb
spec/features/publish/add_course_button_spec.rb
spec/features/publish/course_confirmation_spec.rb
spec/features/publish/courses/editing_study_sites_spec.rb
spec/features/publish/courses/new_schools_spec.rb
spec/features/publish/e2e/new_course_spec.rb
spec/features/publish/managing_study_sites_spec.rb

Removing the study sites feature flag. The feature has been live for a good few months now. 
See commits
Check the functionality still works as expected.

[620] Remove `study_sites` feature flag

---

config/settings.yml

Courses will go live on the third, not the fourth this year

Fix scheduled date (for courses going live this year)

---

app/views/support/schools/index.html.erb
config/settings.yml
spec/features/support/providers/schools/creating_multiple_schools_spec.rb

Removing the `add_multiple_schools` feature flag, because it's been active for a few months now and adds unnecessary complexity.
- Remove the feature flag
- Remove the usages
- Did I miss anything?
- Does the functionality still work as expected?

[623] Remove `add_multiple_schools` feature flag

---

app/components/course_preview/missing_information_component.rb
app/components/find/courses/about_schools_component/view.rb
app/components/find/courses/contents_component/view.html.erb
app/views/find/courses/_train_with_disabilities.html.erb
app/views/publish/courses/preview.html.erb
config/settings.yml
spec/components/course_preview/missing_information_component_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb

Removing the `course_preview_missing_information` feature flag, because it's been active for a few months now and adds unnecessary complexity.
- Remove the feature flag
- Remove the old logic
- Did I miss anything?
- Does the functionality still work as expected?

[629] Remove `course_preview` feature flag

---

app/views/publish/providers/schools/index.html.erb
app/views/publish/providers/study_sites/index.html.erb
config/settings.yml

Removing the `gias_search` feature flag, because it's been active for a few months now and adds unnecessary complexity.
- Remove the feature flag
- Remove the usages
- Did I miss anything?
- Does the functionality still work as expected?

[631] Remove `gias_search` feature flag

---

app/components/course_preview/missing_information_component.rb
app/helpers/navigation_bar_helper.rb
app/views/layouts/provider_record.html.erb
app/views/publish/courses/accredited_provider/new.html.erb
app/views/publish/providers/about.html.erb
app/views/publish/providers/details.html.erb
config/settings.yml
spec/components/course_preview/missing_information_component_spec.rb
spec/features/publish/accredited_provider_spec.rb
spec/features/support/providers/accredited_provider_search/searching_for_an_accredited_provider_spec.rb
spec/features/support/providers/accredited_providers_spec.rb

Removing the `accredited_provider_search` feature flag, because it's been active for a few months now and adds unnecessary complexity.
- Remove the feature flag
- Remove the usages
- Did I miss anything?
- Does the functionality still work as expected?

[636] Remove `accredited_provider_search` feature flag

---

Dockerfile

Update libcurl to 8.3.0-r0
Remove hardcoded pkg versions from the Dockerfile, that are no longer required.
Old versions are breaking the build-no-cache workflow
Update Dockerfile
Check build/build-no-cache workflow

Remove hardcoded pkg versions from Dockerfile

---

app/helpers/find/subject_helper.rb
app/views/find/search/subjects/_secondary_subjects.html.erb
config/locales/en.yml
spec/features/find/search/across_england/secondary_spec.rb
spec/helpers/find/subject_helper_spec.rb

Adding a banner to Find which will be displayed at the start of the new cycle before scholarships and bursaries have been announced.
- Add a banner to be displayed when bursaries and scholarships have not been announced.
- Put this behind the existing `bursaries_and_scholarships_announced` feature flag. This means when the `bursaries_and_scholarships_announced` flag is deactivated the figures will disappear and the banner will **appear**. 
- Add a holding line if feature flag is inactive.
- This change will only be applied on the "Secondary subjects" page. Do we not want this on any other page?
- Currently the end of cycle banner is there, this banner is due to disappear after Find closes which is the 3rd of October. 
- [This is the page on the review …

[692] Add financial support banner

---

app/components/find/courses/contact_details_component/view.html.erb

Change UCL contact details
Ported from https://github.com/DFE-Digital/find-teacher-traini…ng/pull/1534/commits/981e8e2cf92ae858f8941f63c09c4648849d41ac
It shows the right thing.
The original stop gap was missed in the merge, porting it across

[1239] Change UCL contact details

---

app/helpers/find/subject_helper.rb
spec/helpers/find/subject_helper_spec.rb

- We recently shipped a PR to scrub bursary values ahead of the cycle opening
- This PR left in some content relating to scholarships and bursaries being available
- However, this announcement has not yet been made/confirmed, so we should not be presenting any information in relation to this.
- reverting some of the changes in this PR to ensure policy compliance.
Bursaries and scholarships have not been announced yet, so we should scrub any reference to them until we have the approved values.
Before: 
After:
What have we done previously:
2021: https://github.com/DFE-Digital/find-teacher-training/pull/1014
2022: https://github.com/DFE-Digital/publish-teacher-training/pull/3050
In both, we showed no suggestion of bursaries and scholarships.

Scrub content on search filters relating to FIs - mirroring what we did in 2021 and 2022

---

app/services/find/cycle_timetable.rb
spec/controllers/find/courses_controller_spec.rb
spec/features/find/cookie_preferences_spec.rb
spec/features/find/maintainance_page_spec.rb
spec/features/find/result_page_filters/applications_open_spec.rb
spec/features/find/result_page_filters/degree_required_spec.rb
spec/features/find/result_page_filters/engineers_teach_physics_spec.rb
spec/features/find/result_page_filters/qualifications_spec.rb
spec/features/find/result_page_filters/salary_spec.rb
spec/features/find/result_page_filters/send_spec.rb
spec/features/find/result_page_filters/study_type_spec.rb
spec/features/find/result_page_filters/visa_spec.rb
spec/features/find/search/across_england/further_education_spec.rb
spec/features/find/search/across_england/primary_spec.rb
spec/features/find/search/across_england/secondary_spec.rb
spec/features/find/search/course_results_spec.rb
spec/features/find/search/editing_a_search_spec.rb
spec/features/find/search/location_options_spec.rb
spec/features/find/search/provider_options_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/find/sorted_by_filter_spec.rb
spec/features/publish/courses/publishing_a_course_spec.rb
spec/requests/find/locations_suggestions_spec.rb
spec/requests/find/sitemaps_spec.rb

The Find/Publish app is currently set to UTC. I did explore updating the config to use the London timezone (as we do on apply). This had knock on impact throughout the code base, so instead I've gone for more of a temporary fix until we have more time to review this.
Within the CycleTimetable class we use the `.find_down?` method to determine rendering content and redirecting. Such as the redirect in the ApplicationsController:
```
def redirect_to_cycle_has_ended_if_find_is_down
redirect_to find_cycle_has_ended_path if CycleTimetable.find_down?
end
```
For the workaround I'm setting 3 points in time to the expected London time – 2 of which are used within the `.find_down?` method. The other is used to determine if Find should open and then I haven't updated the apply 2 deadline, as we …

Hide and show find on London timezone

---

bin/setup

`OS.windows?` throws an error when running the setup on MacOS `uninitialized constant OS (NameError)`.
I'm assuming this was tested on Linux. CC @inulty-dfe

Fix OS check on MacOS

---

app/views/find/search/subjects/_secondary_subjects.html.erb

Now we've bumped the recruitment cycle year, these values are wrong.
Amending the incorrect values in this image:
Hardcoding these values to:
- 2024 to 2025 academic year
- September 2023 and July 2024
It shou;d look like this:

Update FI banner now we've moved recruitment cycle

---

app/views/find/search/subjects/_secondary_subjects.html.erb

Closing rollover jumped the year forward in Find – we've then hardcoded the values due to the comms we will start sending at 12. Now reverting these back to automated dates.
|Before|After|
|---|---|
|<img width="1043" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/47917431/1c5ce0e5-3e2c-44d3-83a0-7f2497d528e4">|<img width="1082" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/47917431/29b1bd6c-4992-4db2-ba8d-8a323bfe1d97">|

Set the financial support banner to use cycle timetable

---

app/models/course.rb
spec/components/find/courses/entry_requirements_component/view_spec.rb

https://becomingateacher.zendesk.com/agent/tickets/138675
UCL are changing their Grade requirements from Grade 5 to Grade 4. We previously had a special case for them in Publish to reflect this Grade 5 requirement. We have also confirmed that this change back to Grade 4 will apply to their training partners. The code ensures this flows down to UCL's training partners too.
This is a quick change to remove them from the code, but the other provider remaining in this array does not appear to exist, so we should look at removing this whole function around `course.gcse_grade_required` and perhaps move back to hardcoding this to 4.
Remove `U80` from the code that renders Grade 5 as the GCSE requirements.
Amend tests that check for Grade 5 from UCL's provier code to the only outstanding provider …

Remove UCL from grade 5 requirements

---

app/helpers/find/provider_helper.rb
spec/helpers/find/provider_helper_spec.rb

https://trello.com/c/ACtolcvq/2282-mulberry-college-of-teaching-does-not-show-on-find
Some providers could have leading/trailing whitespace in their names which breaks the autocomplete from setting them correctly. Here is an example of how the option is received by the js logic. 
It fails the comparison check here https://github.com/DFE-Digital/publish-teacher-training/blob/422241cf81c6d2ff6eb3fe57d2efa3c5f3ecc9c9/app/javascript/find/dfe-autocomplete/dfe-autocomplete.js#L48
- Strip from source 
You can re-produce the issue by searching `5V5` in the Find provider lookup. If you try to go to the next step it'll trigger an error. Try this in the review app and it should be fixed.

[2282] Fix provider name mapping for autocomplete

---

app/components/find/courses/financial_support/bursary_component/view.html.erb
app/components/find/courses/financial_support/scholarship_and_bursary_component/view.html.erb
app/views/find/courses/financial_support/_loan.html.erb
config/locales/find.yml

We wrongly link to this gov uk page that has now been withdrawn. We should point to where this withdrawn guidance points.
https://www.gov.uk/government/publications/train-to-teach-in-england-non-uk-applicants/train-to-teach-in-england-if-youre-a-non-uk-citizen -> https://getintoteaching.education.gov.uk/non-uk-teachers/train-to-teach-in-england-as-an-international-student
Old link destination: 
New link destination: 
Also updated visa pages. Visa destination:
Does this look right?

Update non uk guidance link to not link to withdrawn guidance

---

app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
spec/components/find/courses/sumary_component/view_preview.rb
spec/components/find/courses/sumary_component/view_spec.rb

Adding the ‘Visa sponsorship’ row to the course page to make it easier to see if the course has visa sponsorship available or not.
- Add visa sponsorship status to find course show page
- Add visa sponsorship status to find course results page
Visit a few courses, salaried, non salaried, can sponsor visas and cannot sponsor visas. Feel free to use [this link](
https://find-review-3909.test.teacherservices.cloud/results?can_sponsor_visa=true&study_type%5B%5D=full_time&study_type%5B%5D=part_time&qualification%5B%5D=qts&qualification%5B%5D=pgce_with_qts&qualification%5B%5D=pgce+pgde&degree_required=show_all_courses&applications_open=false&applications_open=true&l=2&subjects%5B%5D=09) to go to the review app.

[823] Add visa sponsorship row on Find

---

app/controllers/support/courses_controller.rb
app/forms/support/edit_course_form.rb
app/views/support/courses/edit.html.erb
spec/features/support/providers/courses/editing_visa_sponsorship_spec.rb

We receive a number of support requests from providers asking us to change the visa sponsorship status of a course. We want to introduce support functionality to enable the support team to do this.
- Render student visa checkbox if the course if fee paying
- Render skilled checkbox if the course is salaried or apprenticeship
Test [here](https://publish-review-3910.test.teacherservices.cloud/support/2024/providers), with a fee paying course, a salaried course and an apprenticeship course. Ensure the value is updated and the corrected checkbox is rendered depending on the course.

[890] Add visa sponsorship edit functionality to support

---

app/models/provider.rb
app/views/support/providers/_list.html.erb
config/locales/en.yml
spec/components/filter/provider_attributes/view_spec.rb
spec/features/support/providers/providers_filter_spec.rb

Occasionally when the support team receive requests from providers they will provide their UKPRN number. Adding this as an additional search field will help reduce back-and-forth with the provider
- Add a new UKPRN column on the provider index page
- Add the ability to be able to search by UKPRN
Search for a provider using a UKRPN [here](https://publish-review-3912.test.teacherservices.cloud/support/2024/providers).

[891] Enable support to search by UKPRN

---

app/views/support/providers/_list.html.erb

Update the width for a more balanced look, since the introduction of the UKPRN column.

Update width on provider index support page

---

.tool-versions

Was getting the following error:

Update Azure CLI to 2.53.1 to avoid Python incompatibility issues

---

app/views/support/courses/edit.html.erb

Currently you can't change the SEND or visa sponsorship fields to false using the support console. This is the fix.
See commit

Fix the editing of visa sponsorship and SEND in support

---

Gemfile.lock

Reverts DFE-Digital/publish-teacher-training#3917
Builds are falling – sidekiq is broken:
https://qa.publish-teacher-training-courses.service.gov.uk/healthcheck
_Could_ be due to this bump?

Revert "Bump sidekiq-cron from 1.10.1 to 1.11.0"

---

app/views/publish/courses/subjects/_secondary_form.html.erb

A full stop is missing, we need to add it. It surfaced in a Publish demo.
:shipit:

Add missing full stop

---

app/controllers/support/revert_withdrawal_controller.rb
app/services/support/courses/revert_withdrawal_service.rb
app/views/support/courses/edit.html.erb
app/views/support/revert_withdrawal/edit.html.erb
config/routes/support.rb
guides/support_playbook.md
spec/factories/courses.rb
spec/features/support/providers/courses/reverting_a_withdrawal_spec.rb
spec/services/support/courses/revert_withdrawal_service_spec.rb

We often see providers unintentionally withdrawing courses, so we are building the ability to revert withdrawn courses as a feature into our support UI.
- Show course status on all courses within support
- Show a `Revert withdrawal` link below the course status if the course status is `Withdrawn`
- When the course is reverted, the `course_status` is set to `published` and the `last_published_timestamp_utc` is set to the current time.
- Go to Publish, withdraw a course.
- Navigate to the same course on support.
- Revert the withdrawal.
- Go back to Publish and ensure the course is back how it was.
- Try to revert the withdrawal of a course that isn't withdrawn (there should be no link).

[924] Revert withdrawals (support)

---

terraform/aks/.terraform.lock.hcl
terraform/aks/databases.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/staging_aks.tfvars.json

https://github.com/DFE-Digital/publish-teacher-training/actions/runs/7021208705/job/19103158989
This reverts commit 5a2678e5ccd863895df5ed94211acd9a0cfdcdcf. We need to revert because this relies on a alert_window_size, which is not in the stable release of Terraform modules - We will reintroduce the change when it is released

Revert "Add alert_window_size to postgres and redis modules"

---

README.md
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/details.html.erb
spec/features/publish/viewing_a_course_details_spec.rb

Allow the change of visa sponsorship value for provider courses, regardless of course status.
**Note:** Make sure you hide whitespaces when looking at the diff.

Allow providers to change the visa sponsorship value

---

Gemfile
Gemfile.lock

Some of us need to change the database user and password in the `database.yml` file. We can use dotenv-rails to store the user and password in a `.env` file that is gitignored.
Didn't add a `.env.example` as it seems it doesn't use other envs locally

Add dotenv-rails gem

---

Gemfile
Gemfile.lock
config/initializers/dfe_analytics.rb
config/settings/production.yml

EntityTableCheck is a job which sends a row_count, a checksum and a timestamp for each entity table sent to Big Query and it’s purpose is to serve as a tool for confirming database tables match Big Query tables and then help to debug where they don’t match.
This PR enables the job and schedules it to run daily at 00:30
Please check the scheduling looks correct and advise if there is a better time for the job to run. I went for low_priority as the queue and enabled it only in the production.yml.
N.B If it is possible, testing this PR prior to deployment would be ideal - I can help with that

Enable entity_table_check_job

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/about_schools_component/view.rb
app/components/find/courses/contact_details_component/view.html.erb
app/components/find/courses/contact_details_component/view.rb
app/controllers/publish/courses/course_information_controller.rb
app/services/configs/course_information.rb
app/views/publish/courses/course_information/edit.html.erb
config/course_information.yml
spec/components/find/courses/about_schools_component/view_preview.rb
spec/components/find/courses/contact_details_component/view_spec.rb
spec/features/publish/courses/editing_course_information_guidance_spec.rb
spec/services/configs/course_information_spec.rb

Remove explicit references to Provider and Course codes in view templates.
We are extracting the logic for storing configuration related to conditionally showing aspects of the views based on the provider and course.
Create a config file for what providers and courses should trigger the alternative view content.
`config/course_information.yml` holds the data mapping configurations for paricular `Provider`s, `provider_type`s `Course` `program_type`s
`Config::CourseInformation` is a class that encapsulates the loading and lookup behaviour providing an abstracted public interface for interacting with the config data. It is used throughout the application where provider / course specific checks need to happen.
I would like to create a class that encapsulates the views config database. …

Refactor references to provider codes in view templates

---

.rubocop.yml

Avoid:
```shell
The following RuboCop extension libraries are installed but not loaded in config:
* rubocop-factory_bot
```

Require factory_bot in `rubocop.yml`

---

app/controllers/api/public/v1/application_controller.rb
app/controllers/api/public/v1/courses_controller.rb
app/controllers/api/public/v1/providers/courses/locations_controller.rb
app/controllers/api/public/v1/providers/courses_controller.rb
app/controllers/api/public/v1/providers/locations_controller.rb
app/controllers/api/public/v1/providers_controller.rb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/controllers/api/public/v1/providers/courses/locations_controller_spec.rb
spec/controllers/api/public/v1/providers/courses_controller_spec.rb
spec/controllers/api/public/v1/providers/locations_controller_spec.rb
spec/controllers/api/public/v1/providers_controller_spec.rb
spec/docs/courses_spec.rb
spec/docs/providers/courses/locations_spec.rb
spec/docs/providers/courses_spec.rb
spec/docs/providers/locations_spec.rb
spec/docs/providers_spec.rb
swagger/public_v1/api_spec.json

The School Placements and Track & Pay services need to retrieve a list of providers from the [Teacher Training Courses API](https://api.publish-teacher-training-courses.service.gov.uk/docs/).
Within this app, providers belong to a recruitment cycle. The existing [GET /recruitment_cycles/{year}/providers](https://api.publish-teacher-training-courses.service.gov.uk/docs/api-reference.html#recruitment_cycles-year-providers-get) endpoint requires clients to specify which recruitment cycle they want to get providers for.
However in the case of School Placements and Track & Pay, we will always need to retrieve providers for the **current recruitment cycle**. Moreover, recruitment cycle years do not align with calendar years, meaning clients need to understand how to calculate the current …

Support getting resources from the current recruitment cycle

---

app/controllers/find/feature_flags_controller.rb
app/services/find/cycle_timetable.rb
app/views/find/switcher/cycles.html.erb
config/application.rb
spec/rails_helper.rb

Fix to the production check. Rails.env now returns `production_aks` instead of `production`.
This is a temporary fix until we address the route cause.

Fix production check

---

config/initializers/console.rb
config/rubocop/rails.yml

On Apply when you enter the rails console we output the environment, and make a distinction if it's prod. This is a useful visual indication!

Log env to the rails console

---

Gemfile
Gemfile.lock

This should fix an issue which currently prevents access to the production console due to: 
```undefined method `red' for "**************************************************":String```
in: `config/initializers/console.rb`
:shipit:

Add colorize gem

---

app/helpers/view_helper.rb
app/models/course.rb
spec/helpers/view_helper_spec.rb
spec/models/course_spec.rb

There was a bug which allowed users to publish a course which has a `applications_open_from` date outside of the current recruitment cycle. 
[Sentry error](https://dfe-teacher-services.sentry.io/issues/4928616591/?alert_rule_id=11137790&alert_type=issue&notification_uuid=ee949ea3-81e2-4199-a47e-e2a66464f250&project=1377944&referrer=slack)
There is validation which prevents users being able to enter an `applications_open_from` date outside of the recruitment cycle, so I am not entirely sure how this happened. It only affected the one provider. 
Support has reached out to the provider to find out if this was intentional or not. 
- Add validation to prevent users publishing a course which has a `applications_open_from` date outside of the current recruitment cycle. 
- Update the error …

[1240] validate `applications_open_from` when publishing a course

---

bin/dev

We accidentally deleted the bin/dev executable to start the application in development through the Procfile.dev
Reintroduce the executable

bin/dev was accidentally deleted - recreate it

---

Gemfile.lock

Include `arm64-darwin-23` platform in `gemfile.lock` for enhanced compatibility with macOS on apple silicon macs.

Update gemfile.lock to extend apple silicon support

---

spec/forms/support/provider_contact_form_spec.rb

Fix flaky test by normalising HTML before comparison, avoiding a mismatch in the encoding of apostrophes.
- Run the test as many times as you can: `spec/forms/support/provider_contact_form_spec.rb:38`
- Ensure it never unexpectedly fails

[1316] Fix flakey test

---

app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
app/components/find/results/search_result_component.html.erb
app/components/find/results/search_result_component.rb
spec/components/find/courses/sumary_component/view_preview.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/components/find/results/search_result_component_spec.rb

Small changes to the Find results and show page in an attempt to improve the visibilities of fees. This is an attempt to reduce the number of candidates withdrawing due to financial constraints. 
[Review app](https://find-review-4093.test.teacherservices.cloud/)
- Add new labels to the results page and show page
- Add logic to generate the value for the new labels
- Re-order existing labels on the results page

[1340] Improve the visibility of fees

---

app/view_objects/notifications_view.rb
spec/features/publish/editing_notification_preference_spec.rb
spec/view_objects/notifications_view_spec.rb

Fixing the "opt-in and opt-out of notifications" feature. 
- Updating the regex pattern to specifically use `[^/]+` to match characters up to but not including the next `/` . This change fixes an encoding issue encountered in the previous version where `%2F` (the URL-encoded version of `/`) was being incorrectly included in the matched sections of the URL. 
- Also prefixing the match with `publish`, which is the correct URL.
- Try to switch notifications on and off.
- Ensure the back link on that page works as expected. 
- It appears this is cycle independent.

[1265] Fix opt-in and opt-out of notifications

---

guides/adr/0011-tda-courses.md

This PR adds a ADR (and return of ADRs) about the Degree apprenticeship work.
Glossary:
TDA / PGTA: Course that awards a degree with QTS (qualified teacher status).
The problem: We need to include PGTA (with QTS) to courses but if we do, we need to decide what to do on Publish API
We separate into two columns the advantages and disavantages of changing v1 or creating a v2 to accomodate TDA courses:
On this ADR I proposed for changing V1 and talking with Vendors, Register, Providers and Apply (our team yay!).
But is all of us responsibility to accept and move forward with the proposal.

The degree apprenticeship ADR

---

app/components/find/courses/about_schools_component/view.html.erb
spec/components/find/courses/about_schools_component/view_spec.rb

We currently only show schools on Find if there is more than one attached the the course on Publish.
I think the reasoning behind this might be because previously if the provider only had one school that would always be called main site, which didn't mean a lot. This might still be the case for some providers who haven't changed it.
We have decided to remove this restriction as it’s confusing providers who are expecting to see their school listed on Find.
- Show schools on Find even if there is only one. 
- Course on QA: https://qa.find-postgraduate-teacher-training.service.gov.uk/course/1KV/G149#training-locations 
- Course on the review app: https://find-review-4109.test.teacherservices.cloud/course/1KV/G149#training-locations 
**Note: You may need to refresh the review app link after …

[1423] Show schools on Find even if there is only one attached to the course on Publish

---

app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb

Removing the date you can apply from on Find if it has passed.
- Show the row if the date has not passed.
- Don't show the date if the date is the same.
- Don't show the date if the date has passed.
Update the date [here](https://publish-review-4110.test.teacherservices.cloud/publish/organisations/1Z1/2024/courses/A853/details) to be before/after today, then check the row is rendered or not rendered [here](https://publish-review-4110.test.teacherservices.cloud/publish/organisations/1Z1/2024/courses/A853/preview).

[1403] Remove date you can apply from on Find if it has passed

---

app/controllers/support/users_controller.rb
app/models/user.rb
spec/features/support/users/creating_a_new_user_spec.rb

Users were being added with unintentional leading and proceeding white space, causing login issues.
Strip the white space before and after the email address.
[Test it out here](https://publish-review-4112.test.teacherservices.cloud/support/2024/users/new)

Strip whitespace before adding new users to the database

---

app/forms/publish/course_fee_form.rb
config/locales/en.yml
spec/forms/publish/course_fee_form_spec.rb

Prevent users adding course fee values which are less than £1. This aims to prevent candidates from thinking these courses are free.
- Prevent users adding international fee values which are less that £1
- Prevent users adding UK fee values which are less that £1
Try and update either of the fees on the link below to be less than £1
https://publish-review-4116.test.teacherservices.cloud/publish/organisations/2AT/2024/courses/3CXG

[1416] Prevent course fee values which are less than £1

---

.github/dependabot.yml

See for fuller explanation: https://github.com/DFE-Digital/apply-for-teacher-training/pull/9258
- Add the audited gem to dependabot ignore so it won't accidentally get merged in later
https://trello.com/c/pepJCZgL

Add audited to dependabot ignore list

---

app/view_objects/find/results_view.rb
spec/features/find/search/location_options_spec.rb

As part of the Find hack day, we are decreasing the location range that Find uses when searching by postcode from 50 miles to 10 miles.
🚢

Decrease the find radius search range to 50 miles

---

Gemfile

On RVM  I am getting:
```
Unknown ruby interpreter version (do not know how to handle): ~>3.2.3
```
Removing the `~>` works.

Just to make ruby version manager adaptable

---

Gemfile
Gemfile.lock

This library renders our api documentation but it is erroring now. We need to update the version so it starts to work again.
Update `open-api-rswag` version to one compatible with ruby 3.2
[Docs render in Review App](https://publish-review-4130.test.teacherservices.cloud/docs/#about)

Update open-api-rswag to v0.2.0

---

app/components/find/courses/qualifications_summary_component/view.html.erb
app/decorators/course_decorator.rb
app/models/concerns/with_qualifications.rb
app/views/find/result_filters/_qualifications_filter.html.erb
config/locales/en.yml
config/locales/find.yml
spec/components/find/courses/qualifications_summary_component/view_spec.rb
spec/decorators/course_decorator_spec.rb
spec/features/find/result_page_filters/qualifications_spec.rb
spec/features/find/search/course_results_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/features/publish/viewing_a_course_details_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/services/course_attribute_formatter_service_spec.rb

There is inconsistency of terminology between GiT and Find. GiT use “QTS with PGCE” (which is more clear/intuitive) whereas Find uses “PGCE with QTS”.
Replace "PGCE with QTS” with "QTS with PGCE".
When it comes from qualifications is an easy change but because the terminology is inside of the course description from the TTAPI we need to replace part of the string.
1. All the places in Find/Publish being replaced?
https://trello.com/c/eftEZsWL/1283-review-and-replace-existing-instances-of-pgce-with-qts-with-the-correct-terminology-of-qts-with-pgce-in-ui-only

Replace 'PGCE with QTS' with 'QTS with PGCE'

---

app/components/find/courses/international_students_component/view.html.erb
config/locales/find.yml
spec/components/find/courses/international_students_component/view_spec.rb

Updates to the content around Qualifications gained outside the UK on Find.
Navigate to the review app: https://find-review-4163.test.teacherservices.cloud/
Find a course and go to the "International candidates" section, checkout the new content in line with the screenshots above.

[1530] Update content on international qualifications section (Find)

---

Makefile

The Publish and Apply repos are managed by the same team and there are features that exist in one and not the other.
One such feature is convenient commands to login to console environments such as production and sandbox.
Login to any environment exactly like Apply:
```
make qa get-cluster-credentials
make staging get-cluster-credentials
make sandbox get-cluster-credentials
make production get-cluster-credentials
```

Makefile environment names to be equal to Apply

---

app/controllers/concerns/apply_redirect.rb
app/models/provider.rb
spec/controllers/find/courses_controller_spec.rb

A candidate is clicking the Apply button on a course listed on Find and it’s raising an exception.
https://dfe-teacher-services.sentry.io/issues/5254968455/?alert_rule_id=11137790&alert_type=issue&notification_uuid=edb746ad-0dad-4c7a-a414-4f5e6d9abbe5&project=1377944&referrer=slack
Make searching of provider and course, case insensitive.
1. Does it work?
2. Does it affect somewhere else?

Make sure apply button on Find searches for case insensitive codes

---

app/controllers/publish/terms_controller.rb
spec/features/publish/accepting_terms_spec.rb

We are skipping authentication on the terms and conditions page. This means if someone navigates to `https://qa.publish-teacher-training-courses.service.gov.uk/publish/accept-terms` without being authenticated they hit an internal server error. 
Ensure the user is authenticated before allowing them to reach this page. 
Can you think of any reason to not authenticate on this page?

[1558] Authenticate before displaying the terms and conditions

---

db/schema.rb

We upgraded to rails 7.1, but the schema doesn't reflect that. As a result, every time someone runs `bin/setup`, the schema is updated. 
Change the schema version to reflect rails version

Update schema to reflect rails version

---

app/models/course.rb
app/models/provider.rb
spec/models/provider_spec.rb

This PR defines the check we will be using for most of the TDA work.
Add a helper method:
- To check for the next recruitment cycle
- To check for an Active TDA feature flag
Does the check cover what we need it to?

Add helper method to check for next recruitment cycle and TDA

---

app/controllers/heartbeat_controller.rb

The active? method only returns true if a connection was established prior to the call, which is not guaranteed.
Making an explicit query will make that return true or false and also guarantees that we can query the DB.

Execute a connection to the database on healtcheck

---

app/controllers/publish/courses/outcome_controller.rb
app/decorators/course_decorator.rb
app/models/concerns/courses/edit_options/qualification_concern.rb
app/models/concerns/publish/course_basic_detail_concern.rb
app/models/concerns/with_qualifications.rb
app/models/course.rb
app/services/courses/creation_service.rb
app/services/workflow_step_service.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
config/locales/en.yml
spec/decorators/course_decorator_spec.rb
spec/factories/courses.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/courses/new_tda_course_with_feature_flag_off_spec.rb
spec/models/concerns/courses/edit_options/qualification_concern_spec.rb
spec/models/course_spec.rb
spec/requests/reporting_spec.rb
spec/services/course_reporting_service_spec.rb
spec/services/workflow_step_service_spec.rb
spec/support/page_objects/publish/course_confirmation.rb
spec/support/page_objects/publish/courses/new_outcome.rb

We are now in a position to start building the TDA functionality for Publish. See the Trello card for what is in scope for this PR.
This PR deals with the add course logic changes to the add course multi step form.
- Add a new qualification for TDA
- Incorporate the new qualification in the Add course flow
- Skip questions and set defaults if the course is TDA (study mode, visa sponsorship and funding type)
- Remove change links on the Add course flow summary page for the above questions if the course is TDA
If you want to pull this down locally and review it on the UI, you have two options. 
1) You can rollover your local machine
2) you can turn the `teacher_degree_apprenticeship` feature flag on locally in `development.local.yml` and change your `current_recruitment_cycle_year` to …

[1671] Add course flow TDA changes

---

spec/features/publish/courses/new_tda_course_spec.rb

We should not show TDA option from add course - further education flow. 
The implementation does automatically under the file https://github.com/DFE-Digital/publish-teacher-training/blob/main/app/models/concerns/courses/edit_options/qualification_concern.rb#L8
But it is best to increase our coverage for that scenario so this PR only adds a spec to guarantee the functionality is tested and working.
https://trello.com/c/1GZDGD5K/1676-remove-tda-option-for-further-education

Add test for teacher degree apprentice and further education

---

app/services/courses/creation_service.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/services/courses/creation_service_spec.rb

Because the degree apprenticeship will awards a degree then these fields needs to be the default when provider is adding the course
https://trello.com/c/5MJ3HpDI/1674-default-additional-degree-info-to-false-for-tda-courses

Set default degree requirements for TDA courses

---

app/decorators/course_decorator.rb
app/views/publish/courses/_description_content.html.erb
spec/features/publish/courses/new_tda_course_spec.rb

Users don't need to enter and can't change the degree requirements for a course that offers undergraduate degree.
Therefore we're hiding the degree requirements row when the course is teacher degree aprenticeship.
https://trello.com/c/mQzGTkS9/1672-hide-degree-requirement-rows-for-tda-courses

Don't show the degree requirements section on TDA courses

---

app/decorators/course_decorator.rb
app/views/publish/courses/_description_content.html.erb
spec/features/publish/courses/new_tda_course_spec.rb
spec/support/page_objects/publish/provider_courses_show.rb

We are hiding the change links for the course length on TDA courses. The course length is fixed for these courses and this will be the default (the default part is being handled in another PR).
- Hide change links for TDA courses
TDA courses can only be salaried teaching apprenticeships but i've added the logic to the fee paying page too as a precaution.
- Fix test
The method name is suggesting that you are clicking on description when the code is actually clicking on basic details
- Create a TDA course and check there is no change link for course length on the description section.
- Create a non TDA course and check there is a change link for course length on the description section.

[1673] Hide course length change link for TDA courses

---

app/controllers/publish/courses/study_mode_controller.rb
app/controllers/publish/courses_controller.rb
app/forms/publish/course_study_mode_form.rb
app/models/concerns/courses/edit_options/study_mode_concern.rb
app/models/concerns/publish/course_basic_detail_concern.rb
app/services/courses/creation_service.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/courses/study_mode/_form_fields.html.erb
app/views/publish/courses/study_mode/edit.html.erb
app/views/publish/courses/study_mode/new.html.erb
app/views/publish/shared/_errors.html.erb
config/locales/en.yml
spec/features/publish/courses/editing_course_study_mode_spec.rb
spec/features/publish/courses/new_funding_type_spec.rb
spec/features/publish/courses/new_study_mode_spec.rb
spec/features/publish/e2e/new_course_spec.rb
spec/forms/publish/course_study_mode_form_spec.rb
spec/services/courses/creation_service_spec.rb
spec/support/feature_helpers/new_course_param_helper.rb
spec/support/page_objects/publish/course_study_mode_edit.rb
spec/support/page_objects/publish/courses/new_study_mode.rb

from the [Trello ticket](https://trello.com/c/zTDCLOFE):
Following a review of historic design/research findings:
1. Change from radio buttons to checkboxes
2. Removing the ‘Full time or Part time’ field
3. Amend wording to correlate to an either/or choice
Replace radio buttons with checkboxes when selecting study pattern, for both editing a course and creating a new course.
https://github.com/DFE-Digital/publish-teacher-training/assets/44073106/8bcf5122-fbf5-47d6-8d02-60c0aa86b7ef
- [NA] Inform data insights team due to database changes

[1567] full-time part-time study change from radio buttons to checkboxes

---

app/services/courses/creation_service.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/services/courses/creation_service_spec.rb

We have defaulted all TDA courses to a length of 4 years. 
After this the course can be published. So we need to test the publishing mechanism for a TDA course.
I am not sure why, but the course length has two patterns:
1. Enumerator: OneYear, TwoYears
2. Free text: 3 years, etc
I optin for a free text. Let me know if you disagree.
1. Does it save 4 years?
4. Does the API returns 4 years as free text?
https://trello.com/c/KRuhpAaL/1675-add-4-year-default-for-tda-courses

1675 add 4 year default for tda courses

---

app/controllers/publish/courses/fees_controller.rb
app/controllers/publish/courses/length_controller.rb
app/controllers/publish/courses/salary_controller.rb
app/forms/publish/course_fee_form.rb
app/forms/publish/course_length_form.rb
app/forms/publish/course_salary_form.rb
app/forms/publish/funding_type_form_methods.rb
app/services/courses/copy.rb
app/views/publish/courses/_course_length_field.html.erb
app/views/publish/courses/_description_content.html.erb
app/views/publish/courses/_other_course_length_field.html.erb
app/views/publish/courses/fees/edit.html.erb
app/views/publish/courses/length/edit.html.erb
app/views/publish/courses/salary/edit.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/courses/editing_course_funding_type_spec.rb
spec/features/publish/courses/editing_course_length_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/forms/publish/course_fee_form_spec.rb
spec/forms/publish/course_length_form_spec.rb
spec/forms/publish/course_salary_form_spec.rb
spec/support/page_objects/publish/course_fee_edit.rb

We are making improvements to the publish workflow for providers. This PR moves the course length editing functionality to its own page, removing it from the 'Course length and salary' and the 'Course length and fees' pages. 
[Trello card](https://trello.com/c/XKuALLag)
https://github.com/DFE-Digital/publish-teacher-training/assets/44073106/8c190847-e859-4823-b819-8019376ce8ca
- Create a course and edit the length
- Edit the salary / fees of a course to make sure nothing has broken there. 
- [NA] Inform data insights team due to database changes

[1576] Move Course Length to its own page

---

.github/actions/smoke-test_v2/action.yml
.tool-versions
Dockerfile
Gemfile
Gemfile.lock

Github actions stopped working ([here](https://github.com/DFE-Digital/publish-teacher-training/actions/runs/9221004605/job/25369134547?pr=4227) and [here](https://github.com/DFE-Digital/publish-teacher-training/actions/runs/9218111748/job/25361139064?pr=4229) and [here](https://github.com/DFE-Digital/publish-teacher-training/actions/runs/9221603057/job/25371003676))
Security issue noted here: https://security.snyk.io/vuln/SNYK-ALPINE319-GIT-6854155
[Trello card](https://trello.com/c/R1W7ISKX/1727-bug-publish-github-actions-failing)
Need to upgrade the image we use for the docker build. This requires upgrading a patch version of ruby (3.2.3. no longer supported, see [docker docs](https://hub.docker.com/_/ruby))

Upgrade ruby patch version

---

terraform/aks/providers.tf
terraform/custom_domains/environment_domains/terraform.tf
terraform/custom_domains/infrastructure/terraform.tf

Our builds are failing because this version was automatically upgraded and there is a breaking change. See https://github.com/hashicorp/terraform-provider-azurerm/issues/26098
Pin the version to the latest working version, on the advice of @saliceti

Pin hasicorp-azurerm version to 3.104.2

---

spec/features/publish/courses/new_tda_course_spec.rb
spec/support/page_objects/base.rb

Added the back links check when we choose a TDA course.
1. Does it need more specs?
https://trello.com/c/2aheIEsW/1677-fix-back-links-on-the-add-course-flow-and-basic-details-page?filter=label:Squad%20B,label:Squad%20Unassigned

Add spec for back links when TDA

---

config/settings/production.yml
config/settings/production_aks.yml

Data from the EntityTableCheckJob hasn't been sending to BigQuery - I enabled the job in the wrong folder (production.yml rather than production_aks.yml)

Move scheduling of job to correct folder

---

app/controllers/publish/courses/interview_process_controller.rb
app/forms/publish/course_interview_process_form.rb
app/services/courses/copy.rb
app/views/publish/courses/_description_content.html.erb
app/views/publish/courses/about_this_course/edit.html.erb
app/views/publish/courses/course_information/edit.html.erb
app/views/publish/courses/interview_process/_copy_interview_process_content_warning.html.erb
app/views/publish/courses/interview_process/edit.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/courses/copy_from_list_spec.rb
spec/features/publish/courses/editing_course_information_spec.rb
spec/features/publish/courses/editing_course_interview_process_copy_content_spec.rb
spec/features/publish/courses/editing_course_interview_process_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/forms/publish/course_interview_process_form_spec.rb
spec/support/page_objects/publish/course_information_edit.rb

We are moving the three sections of the 'course information' page into their own separate pages. 
'About this course' has already been merged
'How school placements work' is in the next PR
This PR moves the 'Interview process' section into it's own page.
[Trello ticket](https://trello.com/c/uICb3WCc)
- Move Interview process onto its own page
- preserved the 'copy content' functionality
https://github.com/DFE-Digital/publish-teacher-training/assets/44073106/51ec9c23-460b-4939-825b-3e831ec78393
- [NA] Inform data insights team due to database changes

[1573] publish cut down course information move interview process to its own page

---

app/services/courses/assign_program_type_service.rb
spec/services/courses/assign_program_type_service_spec.rb

In the past, developers decided it was a good idea to try to save a `Course` record when assigning an attribute.
This is a hang over from when Publish used an API to create `Course`s. [This API has been deleted](https://github.com/DFE-Digital/publish-teacher-training/pull/2677) and I can find no reason why this code should continue to exist.
The functionality behaves in a very unexpected way:
```ruby
c = Provider.last.courses.new
c.funding_type = 'fee'
```
```ruby
FactoryBot.build(:course, funding_type: 'fee').errors
=> #<ActiveModel::Errors [#<ActiveModel::Error attribute=subjects, type=course_creation, options={}>]>
```
If there are undesirable results from this change we know the area the change will affect and should learn about that quite quickly. The worst outcome I can expect is …

Do not expect attribute setter to save the record

---

terraform/aks/workspace_variables/app_config.yml

This allows the Data Insights team to perform some maintenance on live streamed tables in BigQuery.
Any events to be sent to BigQuery are queued up in Redis and sent after the maintenance window is over.
Requires dfe_analytics GEM Versions >= 1.12.7
Proposed time: 04-06-2024 18:15 - 18:30 UTC
Please note that UTC is 1 hour behind of BST.
Link to trello card: https://trello.com/c/OLgfjgl9

Add a BigQuery maintenance window

---

app/controllers/publish/courses/funding_type_controller.rb
app/controllers/publish/courses/outcome_controller.rb
app/controllers/publish/courses/study_mode_controller.rb
app/forms/publish/course_funding_form.rb
app/models/concerns/publish/course_basic_detail_concern.rb
app/models/course.rb
app/services/courses/creation_service.rb
app/services/publish/courses/assign_tda_attributes_service.rb
app/views/publish/courses/funding_type/_form_fields.html.erb
app/views/publish/courses/outcome/new.html.erb
app/views/publish/courses/study_mode/edit.html.erb
app/views/publish/courses/study_mode/new.html.erb
config/settings/review_aks.yml
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/services/courses/creation_service_spec.rb
spec/services/publish/courses/assign_tda_attributes_service_spec.rb
spec/support/page_objects/publish/courses/outcome_edit.rb
spec/support/test_data_cache.rb

We need to ensure the attributes are correct for TDA courses and non TDA courses.
There are certain attributes which are set by default on TDA courses, so when a user changes from a non TDA course to a TDA course we need to ensure these attributes are correctly set:
- `study_mode: 'full_time'`
- `funding_type: 'apprenticeship'`
- `can_sponsor_student_visa: false`
- `can_sponsor_skilled_worker_visa: false`
When a user changes from a TDA course to a non TDA course, we need to step the user back through the options which were previously defaulted.
The controllers are heavy, we will think of a good way to refactor in a following PR as there are a lot of changes in here already. 
Try and break it. Contact me if you'd like a demo.

[1697] TDA edge cases

---

config/settings/review_aks.yml

Remove the rollover activation in the review app.
This was used in this commit: https://github.com/DFE-Digital/publish-teacher-training/pull/4223/commits/d8d32025e8a95087af672a685a75d6a1b7fbf841
It should have been removed before merging, so it doesn't confuse people testing on other review apps.

Remove rollover activation from review app

---

guides/support_playbook.md

Remove visa sponsorship guidance issue from support playbook
This is not required anymore. The underlying issue was resolved in: https://github.com/DFE-Digital/publish-teacher-training/pull/3861
:shipit:

Remove visa sponsorship guidance issue from support playbook

---

app/controllers/publish/courses_controller.rb
app/models/provider.rb
app/models/recruitment_cycle.rb
app/views/publish/courses/_description_content.html.erb
config/routes/publish.rb
config/settings.yml
config/settings/development.yml
config/settings/qa_aks.yml
config/settings/review_aks.yml
spec/features/publish/courses/editing_course_requirements_2024_spec.rb
spec/features/publish/courses/editing_course_requirements_2025_spec.rb
spec/features/publish/viewing_a_course_2024_spec.rb
spec/features/publish/viewing_a_course_2025_spec.rb
spec/models/recruitment_cycle_spec.rb
spec/support/feature_flags.rb
swagger/public_v1/api_spec.json

Remove the opportunity for a provider to add Personal qualities or Other requirements to courses from after the 2024 RecruitmentCycle.
- make safe RecruitmentCycle specs so they don't fail after cycle changes
- Add Settings feature `:course_requirements_deprecated`
- Hide the links to the requirements page from the course show page if the the course is after the 2024 recruitment cycle or the feature `:course_requirements_deprecated` is enabled
- Add tests for the requirements features for both 2024 and 2025. These need to be merged in the next cycle.
No work has been done on Find, I haven't looked into it and I'm not sure that's a requirement of this particular ticket. However, it looks like don't show anything in find for those attributes if they are not present. They won't be present in …

[1579] Remove personal qualities and other requirements from publish

---

app/assets/stylesheets/components/publish/_secondary-navigation.scss
app/assets/stylesheets/publish_application.scss
app/components/secondary_navigation_component.html.erb
app/components/secondary_navigation_component.rb
app/views/publish/courses/_course_navigation.html.erb
app/views/publish/courses/_description_content.html.erb
app/views/publish/courses/details.html.erb
app/views/publish/courses/show.html.erb
config/locales/en.yml
spec/support/page_objects/publish/provider_courses_show.rb

We are making lots of small changes to the publish interface. This is a change leftover from last year to replace the tabs with secondary navigation.
[Trello card](https://trello.com/c/wOOp6BHO)
- implements a secondary navigation component and nav items
- adds style sheet for secondary navigation (copied and pasted from prototype)
| Before    | After      |
| -------- | -------- |
| <img width="808" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/44073106/8da456fa-3054-4dbc-af82-a9def4969f2b"> | <img width="865" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/44073106/27808d31-004b-4ef9-bb8c-a509957a0fd1"> |
- [NA] Inform data insights team due to database changes

[1720] Replace tabs with secondary navigation component

---

app/decorators/course_decorator.rb
app/helpers/application_helper.rb
app/services/courses/copy.rb
app/views/publish/courses/_description_content.html.erb
app/views/publish/courses/details.html.erb
app/views/publish/courses/show.html.erb
app/views/publish/providers/details.html.erb
config/locales/en.yml
spec/components/course_preview/missing_information_component_spec.rb
spec/components/find/courses/about_schools_component/view_preview.rb
spec/components/find/courses/about_schools_component/view_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/courses/editing_course_school_placements_copy_content_spec.rb
spec/features/publish/courses/editing_course_school_placements_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/courses/publishing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/course/publishable_spec.rb

We have made lots of small changes to the content relevant to the course description. This [trello ticket](https://trello.com/c/wOOp6BHO) just does some final clean up of the content on that page. 
- The main visual change is that we no longer truncate the information on the page. So the long text passages are all visible. To make the text more readable, we use the full width instead of the normal 2/3.
- There are a few small text changes to match the designs:
- How school placements work  => How placements work
- Course outline => About this course
- Fee details => Fees and financial support (optional)
| Before     | After        |
| --------- | --------- |
| <img width="902" alt="image" src="https://github.com/DFE-Digital/publish-teacher-training/assets/44073106/c208ac3e-b4a0-42f8-b51d-b …

[1638] publish amends to course description tab

---

config/locales/en.yml

The hidden text translation is missing, this is causing translation errors.
Add the translation.

Add hidden text translation

---

app/controllers/publish/courses/outcome_controller.rb
spec/features/publish/courses/editing_course_outcome_spec.rb

Certain defaults are set when a TDA course is created. We need to ensure all of these are set back to nil when a user changes from a TDA course to a non TDA course.
Set the following enrichment attributes back to nil when changing a TDA course to a non TDA course:
- `course_length`
- `salary_details`
The controllers are heavy, there is a card to try and refactor the whole flow.

[1750] Reset previously defaulted enrichment attributes back to nil (TDA courses)

---

app/views/sign_in/_default_signin_content.html.erb

The govuk-link class is missing in the mailto link on our sign in page. We should add it.
🚢

Add missing govuk-link

---

.github/workflows/disable-maintenance.yml
.github/workflows/enable-maintenance.yml

We need to add workflows for maintenance page
- Workflow for enabling maintenance page
- Workflow for disabling maintenance page

Add enable and disable maintenance page workflows

---

app/views/publish/courses/_description_content.html.erb

- Hide Financial support in Course Description view if the Recruitment Cycle is 2025
- ~Merge fee details and financial support into fee details when rolling over a course from 2024 to 2025~
~There is a word limit on Fee details.~
~I've clipped the text copied to fee details so it fits in the validation.~
**This PR now only hides the fincial support on the Course description. We elected to contact each provider that has content in Financial Support and manuallly copy it across to 2025 if they wish. This avoids any potential issues in rollover.**
|2024|2025|
|---|---|
|![image](https://github.com/DFE-Digital/publish-teacher-training/assets/135042929/629535dc-7e5e-4a1c-ba00-ae8f50a27725)|![image](https://github.com/DFE-Digital/publish-teacher-training/assets/135042929/c6ef7772-efa3-4d3d-9ad6 …

Hide Financial support in 2025

---

app/controllers/publish/courses_controller.rb
app/helpers/publish_helper.rb
app/models/provider.rb
app/views/publish/courses/_description_content.html.erb
config/settings.yml
config/settings/development.yml
config/settings/qa_aks.yml
config/settings/review_aks.yml
spec/features/publish/courses/editing_course_requirements_2024_spec.rb
spec/features/publish/courses/editing_course_requirements_2025_spec.rb
spec/features/publish/courses/publishing_a_course_2025_spec.rb
spec/features/publish/viewing_a_course_2024_spec.rb
spec/features/publish/viewing_a_course_2025_spec.rb

We've added a route constraint to prevent some endpoints being accessible for the 2025 recruitment cycle.
However, these named routes are still evaluated even if they are not executed in the view.
_Remove the Feature Flag for course requirements deprecation. It's not necessary becuase of the separation of courses by recruitment cycle._
Wrap the named routes in a block that executes conditionally to prevent routing error.

Hiding Other Requirements doesn't prevent course from being published in 2025

---

.rubocop.yml
Gemfile
Gemfile.lock
config/rubocop/naming.yml
config/rubocop/rspec.yml

Rubocop updated to v3 recently, some things were not attended to during the upgrade.
Also disable numbers in variables cop, it is not helpful
1. Rubocop RSpecRails exists now: Add it to the gem file and require it in rubocop.yml
2. Add `RSpecRails/HaveHttpStatus` and `RSpec/Dialect` back in
3. ignore restrictions around numbers in variable names.

Rubocop changes

---

app/lib/find_constraint.rb
config/environments/production.rb
config/initializers/cors.rb
config/settings.yml
config/settings/production.yml
config/settings/production_aks.yml
config/settings/qa.yml
config/settings/qa_aks.yml
config/settings/review.yml
config/settings/review_aks.yml
config/settings/rollover.yml
config/settings/sandbox.yml
config/settings/sandbox_aks.yml
config/settings/staging.yml
config/settings/staging_aks.yml
spec/lib/find_constraint_spec.rb

Due to undergraduate courses appearing we will change Find domain.
Because this repo contain several domains into the same app we need to change the application logic to allow a new domain.
We’ll look to handle multiple domains (to enable a seamless transition from one domain to the other).
1. Allow multiple domains to function
2. Infra team to set up redirect from old to new domain
3. We remove this second domain and renamed the old domain to the new one in the app.
Allow multiple domains to function
1. Does it needs change anywhere else?

Find Domain change - We will have to sustain 2 domains until the domain redirect is applied

---

.github/workflows/database-restore.yml

There's been an increase in overnight backup failures.
Some are in the initial connection to the webapp at 0400 when the backup starts, and it could be related to what looks like a  regular process that occurs around this time.
Change the backup start time from 03:00 UTC to 01:00 UTC
Confirm ok with the change in time

Change overnight backup to run at 0100 UTC

---

app/services/find/cycle_timetable.rb

The `applications_open_from` date on all the rolled over courses where they were using the default date in the previous cycle were defaulting to the 12th of October instead of the 8th of October in the new cycle.
This is because we need to update our dates for the 2025 recruitment cycle, now that they have been confirmed.
Failing linter is unrelated, [once this gets merged](https://github.com/DFE-Digital/publish-teacher-training/pull/4296) I will rebase and they will pass.
Update the following dates for the 2025 recruitment cycle: 
- `find_opens`
- `apply_opens`
- Ensure the dates match the published dates here: 
https://www.apply-for-teacher-training.service.gov.uk/provider/service-guidance/dates-and-deadlines
- Ensure our services are aligned: …

[1837] Update dates for 2025 cycle

---

app/helpers/view_helper.rb
spec/features/publish/courses/publishing_a_course_with_validation_errors_spec.rb
spec/helpers/application_helper_spec.rb
spec/helpers/view_helper_spec.rb

Ensure that the links shown to providers alerting them of validation
errors on a course bring them to the relevant pages to correct the
course and allow them to publish.
[Screencast from 21-06-24 16:27:23.webm](https://github.com/DFE-Digital/publish-teacher-training/assets/135042929/1fdeee37-5c3e-4fa9-8348-c2ec2cfa8444)

Update Publish course validation links

---

app/controllers/publish/courses_controller.rb
app/services/courses/copy_to_provider_service.rb
spec/features/publish/courses/publishing_a_course_spec.rb
spec/services/courses/copy_to_provider_service_spec.rb

When a course is rolled over, it is rolled over to the “rolled over” state.
It is currently rolled over with the same `application_status` it had in the previous cycle.
It doesn’t make sense from a data analysis point of view for the course to be `unpublished` and `open` at the beginning of the cycle.
Therefore we should roll over courses and set the course `application_status` to closed until it is `published`.
We automatically open a course during the publish step to avoid the multi-step process of 'publish', 'open', 'confirm'.
Now the provider needs only to publish a closed course and it will be open for applications pending it's scheduled open date.
When a provider publishes a course, they must "Open" the course, even if the course was open in the previous cycle.
We've changed this …

Rolled over courses are closed by default and automatically opened on publish

---

maintenance_page/scripts/failback.sh

The disable maintenance workflow had an error
Add 'update image tag' step into failback.sh for maintenance page

Add update image tag for failback maintenance page

---

app/components/find/deadline_banner_component.html.erb
app/components/find/deadline_banner_component.rb
app/helpers/recruitment_cycle_helper.rb
app/services/find/cycle_timetable.rb
app/views/find/switcher/cycles.html.erb
config/locales/find.yml
spec/components/find/deadline_banner_component_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/find/switcher_cycles_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/services/find/cycle_timetable_spec.rb

We are consolidating the `apply_1` and `apply_2` deadlines into one `apply_deadline`. This is overhanging tech debt from before we had continuous applications. 
- Remove the `apply_1_deadline` banner and all related code
- Rename `apply_2_deadline` to `apply_deadline`
- Update the date of the `apply_deadline`
Does all the functionality still work without the two deadlines? Are their any edge cases that might catch us out?

[1779] Consolidate `apply_1` and `apply_2` deadlines into `apply_deadline`

---

app/views/layouts/_add_js_enabled_class_to_body.html.erb
config/initializers/content_security_policy.rb

Add the hash of the inline script to the Content Security Policy header from the server.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe_inline_script
1. Open Dev tools
2. Visit the root of the application
3. Clear cookies
4. Refresh the page with CTRL-r
5. See no CSP errors in the console.
This actually highlights other areas where the attempt to add a nonce value is not working.
This fixes the issue in the ticket though.

Add script hash to rails CSP configuration

---

app/controllers/find/courses_controller.rb
spec/features/find/viewing_courses_in_various_states_spec.rb

Courses which are draft, rolled over and withdrawn should not be on Find. Currently you can access these courses if you manually type in the URL.
These courses are already hidden from the Find search and wont be shown in the results page.
Render a 404 if the course is in a state where it should not be on Find.
- https://qa.publish-teacher-training-courses.service.gov.uk/publish/organisations/4Y1/2024/courses/E588
- https://qa.find-postgraduate-teacher-training.service.gov.uk/course/4Y1/E588
- https://publish-review-4312.test.teacherservices.cloud/publish/organisations/4Y1/2024/courses/E588
- https://find-review-4312.test.teacherservices.cloud/course/4Y1/E588

[1873] Render 404 if course should not be on Find

---

app/validators/chars_count_validator.rb
app/wizards/a_level_steps/what_a_level_is_required.rb
config/locales/en.yml
spec/wizards/a_level_steps/what_a_level_is_required_spec.rb

Added a max character validation for the minimum grade required on the A level page "What A level is required?".
1. Does it work?
2. Does the error validation link works?
https://trello.com/c/rOBwmvpX/1869-a-levels-add-length-validation-to-minimum-grade-required

A levels add max character length validation to minimum grade required

---

app/components/a_level_row_component.html.erb
app/components/a_level_row_component.rb
config/locales/en.yml
spec/components/a_level_row_component_spec.rb
spec/features/publish/courses/editing_a_levels_tda_course_spec.rb

We need to display the A levels required for TDA a courses on Publish.
The “A levels” row in on the “Description” tab displays the required A levels, including the different variations if Grade is added, and if pending or equivalency tests are accepted.
1. Does it work in any scenarios with content being added?
https://trello.com/c/91pWQbZL/1792-a-levels-7-7-display-a-levels-on-publish-summary-page-and-find-preview-for-tda-courses-on-publish

Display A levels on publish summary page

---

app/components/a_level_subject_requirement_row_component.rb
app/controllers/publish/courses/a_level_requirements/a_level_requirements_controller.rb
app/controllers/publish/courses/a_level_requirements/remove_a_level_subject_confirmation_controller.rb
app/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller.rb
app/models/course.rb
app/views/publish/courses/a_level_requirements/add_a_level_to_a_list/new.html.erb
app/views/publish/courses/a_level_requirements/remove_a_level_subject_confirmation/new.html.erb
app/views/publish/courses/a_level_requirements/what_a_level_is_required/new.html.erb
app/wizards/a_level_steps/remove_a_level_subject_confirmation.rb
app/wizards/a_levels_wizard.rb
app/wizards/a_levels_wizard_store.rb
app/wizards/remove_a_level_subject_confirmation_store.rb
app/wizards/what_a_level_is_required_store.rb
config/locales/en.yml
config/routes/publish.rb
spec/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller_spec.rb
spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
spec/models/course_spec.rb
spec/wizards/a_level_steps/remove_a_level_subject_confirmation_spec.rb
spec/wizards/a_levels_wizard_store_spec.rb
spec/wizards/remove_a_level_subject_confirmation_store_spec.rb
spec/wizards/what_a_level_is_required_store_spec.rb

We need to add the ability for providers to change or remove a required A level they have added to TDA a course on Publish, in order to enable TDA applications.
1. Does the validations work?
2. Does the change work? (from other subject to any subject and vice versa)
3. Does the remove work? (when you remove any or all subjects)
To enable the TDA locally you need to run the rollover script and be on 2025 cycle (see rollover guide for more details)
https://trello.com/c/ic2phanj/1789-a-levels-4-7-add-change-and-remove-a-required-a-level-question-page-for-tda-courses-on-publish

Change and remove a required A level

---

app/views/support/courses/edit.html.erb
spec/features/support/providers/courses/editing_a_course_spec.rb
spec/support/page_objects/support/provider/course_edit.rb

Our support console in Publish allows someone to set a course as any day in any month.
However, if the provider went through the normal flow of creating a course, this is impossible. We default this to the first of the month. We should align the two.
We do not render this to the candidate, so it will not make any difference to candidates, but will help keep our data consistent.
There will be follow up work to set all course start days to the 1st of the month.
Remove the day field from support

[453] Omit course start day field on support

---

app/components/find/courses/contents_component/view.html.erb
app/components/find/courses/entry_requirements_component/view.html.erb
app/components/find/courses/international_students_component/view.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb
config/locales/find.yml
spec/components/find/courses/entry_requirements_component/view_spec.rb
spec/components/find/courses/international_students_component/view_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb

Currently, entry requirements are listed further down the page and contain information on personal qualities and other requirements, which can be problematic for candidates.
We want to update the order and content of this section.
- The Entry requirements section is moved above the Course summary section.
- The 'Personal qualities' and 'Other requirements' sections are removed.
- The section 'Qualifications gained outside the UK' is moved to the 'Entry requirements' section.
Review the preview page of a course and the course on find page and compare it to the ticket requirements screenshot on this PR

Change the content of the course view

---

app/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller.rb
spec/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller_spec.rb

If the user add 4 levels and somehow (manually) tries to enter on the add A level page - we should redirect away.
If the user enters manually on the What A level is required or via back in the browser and try to create another A level, the user will be redirect to the list as there are already 4 A levels.
Redirect away when user tries to create more than 4 A level subject requirements.
1. Are you able to create 5 A levels?
2. Everything is working?
3. Is the change A level subject when there is 4 maximum, still working? (automated and manual tests say yes but good to review!)

Edge case - Redirect away from adding more A level subjects when maximum A levels

---

app/services/enrichments/copy_to_course_service.rb
spec/services/enrichments/copy_to_course_service_spec.rb

We recently removed `other_requirements` and `personal_qualities` from Publish. 
We do not want to copy these over to the next cycle.
This code can be removed once rollover for the 2023-2024 recruitment cycle is complete.
Don't copy over `other_requirements` and `personal_qualities` into the next recruitment cycle.
Rollover a course, ensure it retains `other_requirements` and `personal_qualities` in the current cycle but removes it from the next cycle.

[1889] Do not rollover `other_requirements` and `personal_qualities`

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/about_schools_component/view.rb
app/controllers/find/placements_controller.rb
app/controllers/publish/courses/school_placements_controller.rb
app/models/course.rb
app/views/find/placements/index.html.erb
app/views/publish/courses/school_placements/index.html.erb
app/views/shared/courses/_placements.html.erb
config/locales/en.yml
config/locales/find.yml
config/routes/find.rb
config/routes/publish.rb
spec/components/find/courses/about_schools_component/view_spec.rb
spec/controllers/find/placements_controller_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/models/course_spec.rb

Currently, school placements are listed on course pages, which can be
problematic for candidates as there is quite a lot of content on this
page.
We want to move this information to a separate page.
New route/controller and view for the placements.
Link to the new view from the course show page, in find and publish
Review the show page of the course in publish(preview) and in find.
You should see a link to the school placements
https://github.com/DFE-Digital/publish-teacher-training/assets/11318084/b35474b1-9ff6-4d7f-b351-7fdd9ac206e4

Move school placements into its own view

---

app/components/a_level_row_component.rb
app/components/a_level_subject_requirement_row_component.rb
app/components/find/courses/a_level_component/grouped_a_level_subject_requirements.rb
app/components/find/courses/a_level_component/view.html.erb
app/components/find/courses/a_level_component/view.rb
app/components/find/courses/entry_requirements_component/view.html.erb
app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.html.erb
app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.rb
config/locales/en.yml
config/locales/find.yml
spec/components/find/courses/a_level_component/grouped_a_level_subject_requirements_spec.rb
spec/components/find/courses/a_level_component/view_spec.rb
spec/components/find/courses/entry_requirements_component/view_preview.rb
spec/components/find/courses/entry_requirements_component/view_spec.rb
spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb
spec/features/publish/preview_teacher_degree_apprenticeship_course_spec.rb

We need to add the ability for providers to input A level requirements for TDA courses on Publish, in order to enable TDA applications.
Once they have inputted their A level requirements, they need to preview how this will look for candidates on Find.
1. Does the grouping working?
2. Does other subject works?
3. Does the GCSEs word appear?
4. Does degrees content are hidden?
To enable TDA you need to enable rollover and be on 2025 cycle.
https://trello.com/c/1mxaXiCk/1808-a-levels-add-find-preview-for-tda-courses-on-publish

A levels  - Add find preview for TDA courses on publish

---

app/components/a_level_row_component.html.erb
app/components/a_level_row_component.rb
app/controllers/publish/courses/a_level_requirements/a_level_requirements_controller.rb
app/helpers/application_helper.rb
app/helpers/view_helper.rb
app/models/course.rb
app/validators/a_level_course_validator.rb
app/views/publish/courses/_description_content.html.erb
config/locales/en.yml
spec/components/a_level_row_component_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
spec/models/course/publishable_spec.rb
spec/support/page_objects/publish/provider_courses_show.rb

We need to add a validation for the A levels when publishing a course.
https://trello.com/c/BzbwKssS/1895-a-level-validation-when-publishing-a-course
https://lucid.app/lucidspark/ba759696-865b-46b4-ab23-9d3af92d79fb/edit?view_items=ohfKW2nmrz23&invitationId=inv_fa1f4bfe-7a1f-49d1-ae9c-1e46971e8f85
Please see trello card AND the lucid board for more details.
I added the option render_errors: with default being true to avoid breaking existing code but passing false to A levels Because:
* The A levels are a multi step form and I need to inject the error on the row in any way is described in the card
* The row has the wizard step name attached to the link so different from the way GCSEs or degrees or others are doing when publishing
1. Is it working all the validations?
2. Is it working all …

Validating A levels when publishing for teacher degree apprenticeship courses

---

app/components/find/courses/about_schools_component/view.html.erb

Our automated study sites wording on Find does not reflect that a user can have multiple study sites.
Pluralize the word location if the user has multiple study sites.
The whole study sites section is not shown if the user doesn't have any study sites.

[225] Update wording to reflect multiple study sites

---

app/services/enrichments/copy_to_course_service.rb
spec/services/enrichments/copy_to_course_service_spec.rb

We previously opened a PR to delete the keys. This causes validation to kick in and prevents the rollover script from executing properly. 
We still have `personal_qualities` and  `other_requirements` in the current cycle.
Set `personal_qualities` and `other_requirements` to `nil` during rollover.

[1980] Set `personal_qualities` and `other_requirements` to nil during rollover

---

config/initializers/dfe_analytics.rb
terraform/aks/application.tf

This is part of a wider BigQuery Assurance piece to to harden the security around BigQuery.
It allows the use of OAuth mechanism for authentication to BigQuery rather than relying on plain text JSON API Keys.
The Data Insights ticket is [here](https://trello.com/c/IDG7vXFy).
Enable Azure workload identity federation within DfE Analytics.
Set GOOGLE_CLOUD_CREDENTIALS secret in the key vault for each environment. 
See [Dfe Analytics GEM](https://github.com/DFE-Digital/dfe-analytics) for further details.
This change involves the following steps
- Set GOOGLE_CLOUD_CREDENTIALS by downloading from GCP. This should be done for each environment.
- Enable WIF in the Azure Infrastructure
- Enable WIF in the App. We can remove references to the the JSON API Key at the same time
- Enable WIF in the …

Rollout workload identity federation to all environments 

---

app/decorators/course_decorator.rb
spec/decorators/course_decorator_spec.rb

Do not show the A levels change link for a withdrawn course.
Remove the change link for a withdrawn course.
https://trello.com/c/y0tYPgD4/2005-bug-tda-incorrectly-able-to-change-a-levels-on-a-withdrawn-course
If you access the pages directly you can edit, but this is log in a different card therefore in a different PR: https://trello.com/c/BQDAr1dm/2017-bug-can-access-the-edit-page-of-a-withdrawn-course-by-navigating-directly-to-url-using-course-code?search_id=dba419e6-1429-4ebb-8e24-2bd430913acd

Don't show the A level change link when the course is withdrawn

---

app/controllers/publish/users_controller.rb
app/controllers/support/providers/users_controller.rb
app/forms/user_form.rb
spec/features/publish/managing_users_spec.rb
spec/features/support/providers/users/adding_user_to_provider_spec.rb

With out current implementation a user can add another user even if they already exist under that provider. This then updates the already existing user with the new first name and last name.
This will prevent submission of the `/new` page if the email address that is inputted already exists in the database under the provider.
Try to add a user with an email which already used in the provider that you are logged in as.

[2016] Prevent the creation of a user which already exists under the same provider

---

terraform/aks/workspace_variables/staging_aks.tfvars.json

https://trello.com/c/BoARcUFk/1922-publish-increase-staging-db-cpu-alert-window
To stop the alerts for staging postgres db cpu usage during the nightly backup restore
Increase alert_window_size from 30m to 1h
make staging deploy-plan

Increase alert_window_size to 1h for stg monitors

---

app/components/find/deadline_banner_component.html.erb
app/components/find/deadline_banner_component.rb
config/locales/deadline_banner_component.yml
spec/components/find/deadline_banner_component_preview.rb
spec/components/find/deadline_banner_component_spec.rb
spec/features/find/switcher_cycles_spec.rb

We’ve identified some banners in publish that need updating as part of the end of cycle.
This ticket is just related to the banner users see after 30 July, alerting them of the apply deadline.
We [agreed in this slack thread](https://ukgovernmentdfe.slack.com/archives/C077NRS8K8D/p1720520008204449) that we would use the same content as the banner we show candidates who are applying for courses
https://trello.com/c/myMbTZ4Q
- Updated text
- Added preview for deadline banner
Before
After

[2027] Update apply deadline banner in publish

---

app/models/course.rb
spec/forms/edit_course_form_spec.rb
spec/models/course_spec.rb

The `applications_open_from` recruitment cycle range error message is not in line with style guide.
https://design-system.service.gov.uk/components/date-input/#error-messages

[1996] Update validation error message for `applications_open_from`

---

app/components/course_preview/missing_information_component.rb
app/components/find/courses/contents_component/view.html.erb
app/controllers/concerns/goto_preview.rb
app/controllers/find/courses/training_with_disabilities_controller.rb
app/controllers/publish/courses/training_with_disabilities_controller.rb
app/controllers/publish/providers_controller.rb
app/forms/publish/about_your_organisation_form.rb
app/helpers/find/goto_preview_helper.rb
app/helpers/preview_helper.rb
app/views/find/courses/_train_with_disabilities.html.erb
app/views/find/courses/show.html.erb
app/views/find/courses/training_with_disabilities/show.html.erb
app/views/publish/courses/preview.html.erb
app/views/publish/courses/training_with_disabilities/show.html.erb
app/views/publish/providers/about.html.erb
config/locales/en.yml
config/locales/find.yml
config/routes/find.rb
config/routes/publish.rb
spec/components/course_preview/missing_information_component_spec.rb
spec/controllers/concerns/goto_preview_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/forms/publish/about_your_organisation_form_spec.rb
spec/helpers/find/goto_preview_helper_spec.rb

The course show page on find and the preview page on publish contains
too much information that might be off-putting for the user.
This commit tries to fix this by putting this section into its own view
accessible from the course page
347fce874492a8cb967521fa7b5679f0128af0cd This implements the view/controller/routes changes
91f3fa13a3c6efc513817597003e403847f3179a This is a bit of a refactor of the `goto` methods that tell the `about_your_organisation` form where to redirect
Description of 91f3fa13a3c6efc513817597003e403847f3179a:
There are a few `goto` methods that tell the about your organisation
form where to redirect the user after update or when the user clicks the
back links.
Basically, both back links and update success methods can go to the same
path based on the `goto` param. …

Training with disabilities view on courses

---

app/components/find/courses/contents_component/view.html.erb
app/components/find/courses/international_students_component/view.html.erb
app/components/find/courses/international_students_component/view.rb
app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
app/helpers/view_helper.rb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb
config/locales/find.yml
spec/components/find/courses/international_students_component/view_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/helpers/view_helper_spec.rb
spec/support/page_objects/find/course_show.rb

The International students section is going to be removed from the
publis/find course show pages. This is part of a redesign of the course
page to make it easier for users to view the information without being
overwhelmed
The visa sponsorship content will now be in a drop-down details tag. The
content inside has also been tweaked.
`InternationalStudentsComponent` now will display the info in a details tag.
Moved the provider_url helper methods in a more global place.
View a course on publish and find and open the visa sponsorship dropdown
https://github.com/DFE-Digital/publish-teacher-training/assets/11318084/a4bc44e4-a659-4235-8b2d-7a26a3bbff21

Redesign visa sponsorship on course page

---

terraform/aks/workspace_variables/staging_aks.tfvars.json

https://trello.com/c/BoARcUFk/1922-publish-increase-staging-db-cpu-alert-window
To stop the alerts for staging postgres db cpu usage during the nightly backup restore
Increase alert_window_size from 1h to 6h
make staging deploy-plan

Increase alert_window_size to 6h for stg monitors

---

terraform/aks/workspace_variables/staging_aks.tfvars.json

Increase of alert window to PT6H requires a change in the terraform-module as it fails with
Metric Alert Name: "s189t01-ptt-stg-pg-storage"): unexpected status 400 (400 Bad Request) with response: ***"code":"BadRequest","message":"Evaluation frequency must be greater than or equal to five minutes since the period is greater than four hours. 
Change window back to PT1H until the module is updated
make staging terraform-plan

Decrease alert_window_size to 1h for stg monitors

---

app/assets/stylesheets/components/shared/_advice.scss
app/views/find/courses/_advice.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb
config/locales/find.yml

This simplifies the content and adds some styling to the support and advice section of the course page.
It also moves the summary component of the course page in the govuk 2 thirds body to match the rest of the content.
Review the support and advice section for a course, in publish and find

Redesign support and advice section on course page

---

app/views/publish/courses/a_level_requirements/a_level_equivalencies/new.html.erb

There is an accessibility issue when the validation is triggered on the equivalency page. 
When you click validation error, focus should be on the first radio
1. Does it focus when you click in the validation error message?

When you click validation error, focus should be on the first radio

---

app/services/courses/copy_to_provider_service.rb
spec/features/publish/viewing_a_course_spec.rb

When we manually rollover a course it has a `content_status` of `draft` but we want a manually rolled over course to have a `content_status` of `rolled_over`.
They are currently `draft` because they don't have any enrichments and in these cases we default the `content_status` to `draft`.
The code that causes the `content_status` to get set to rolled over is never hit in `content_service_status.rb` because there is no enrichment to `dup`.
Give a course being rolled over an enrichment if it doesn't have any enrichments.
Does this cause any unexpected side effects?

Give a course with no enrichments being rolled over an enrichment

---

app/components/find/courses/entry_requirements_component/view.html.erb
app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.html.erb
app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.rb
config/locales/en.yml
spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb

When there are no A level and the user clicks to preview the course, a link to enter A levels should be there.
```
GIVEN I have created a TDA course
AND there are no A level requirements
WHEN I look at the preview and navigate to the A levels
THEN I should see a link to add A levels
```
1. Does it work on preview?

Add link to add A levels requirements from preview page

---

config/settings.yml
config/settings/production_aks.yml
config/settings/qa_aks.yml
config/settings/review_aks.yml
spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
spec/features/publish/editing_notification_preference_spec.rb
spec/models/concerns/courses/edit_options_spec.rb

Now that courses have been rolled over in all the various environments and TDA is active in production, we should activate the flags in all environments.
🚢

[2039] Activate TDA and rollover in all environments

---

app/forms/find/location_filter_form.rb
app/view_objects/find/result_filters/filters_view.rb
app/view_objects/find/results_view.rb
app/views/find/result_filters/_all.html.erb
app/views/find/result_filters/_radius.html.erb
config/locales/find.yml
spec/features/find/search/location_options_spec.rb
spec/view_objects/find/result_filters/filters_view_spec.rb

Filter only displays if the `radius` parameter is in the URL
Added radius filter to Results view
https://github.com/DFE-Digital/publish-teacher-training/assets/8854356/8459e4a4-b0e8-492c-b496-cf02f6d86562
https://trello.com/c/Ymct9lT2

Added Radius filter to Search results

---

app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.rb
spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb

I added the wrong attribute name for #4375 
It should be A levels not GCSE.

Fix wrong attribute name when previewing the course

---

config/settings.yml

Find opens on the 1st of October this year, not the 3rd.
🚢

Update next cycle open date

---

spec/components/add_course_button_preview.rb
spec/features/publish/courses/editing_study_sites_spec.rb

Fixing a couple of tests which will fail when the current cycle ends. 
Fix the tests dynamically so they work in both cycles.
Do the tests pass all the time regardless of the cycle?

[2061] Fix tests which will fail when the current cycle ends

---

app/components/find/results/search_result_component.html.erb
app/components/find/results/search_result_component.rb
app/decorators/course_decorator.rb
spec/components/find/results/search_result_component_spec.rb
spec/decorators/course_decorator_spec.rb

We want to add the Age Range and Level to Course Results to highlight differences between courses
https://trello.com/c/Iwh2Yc1n
Added age range with level to Course results
- View course results

Added age range to course summary in search results

---

app/decorators/course_decorator.rb

`age_range_in_years` can be blank 🤦‍♂️ this is causing [errors](https://dfe-teacher-services.sentry.io/issues/5618386329/?referrer=slack&notification_uuid=30e095ab-0276-46d1-abbd-f053929ca39f&alert_rule_id=11137790&alert_type=issue)
Error introduced in #4381 
Add a check for blank age ranges

Return nil if age_range_in_years is blank

---

app/components/find/courses/a_level_component/view.html.erb
app/components/find/courses/entry_requirements_component/view.html.erb
app/components/find/courses/entry_requirements_component/view.rb
app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.html.erb
app/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view.rb
app/models/course.rb
config/locales/find.yml
spec/components/find/courses/a_level_component/view_spec.rb
spec/components/find/courses/entry_requirements_component/view_preview.rb
spec/components/find/courses/entry_requirements_component/view_spec.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/models/course_spec.rb

This is part of a redesign of the course show page both on apply and
find.
This will put all the entry requirements info into a summary list with
details(dropdown) which should help the user navigate this page better
Entry requirements are in a summary list with details tags
Visa sponsorship is part of the entry requirements
TDA:
Check the preview course page on publish and the course show page on find.
For TDA and other course entry requirement options

New format for Course show entry requirements

---

app/components/find/phase_banner/view.html.erb
app/jobs/find/slack_notification_job.rb
app/views/find/pages/accessibility.html.erb
app/views/find/pages/privacy.html.erb
app/views/find/pages/terms.html.erb
app/views/pages/add_an_organisation.html.erb
app/views/pages/add_schools_and_study_sites.html.erb
app/views/pages/course_summary_examples.erb
app/views/pages/help_writing_course_descriptions.html.erb
app/views/pages/how_to_use_this_service.html.erb
app/views/pages/privacy.html.erb
app/views/pages/roll_over_courses_to_a_new_recruitment_cycle.html.erb
app/views/pages/terms.html.erb
app/views/publish/courses/_course_table.html.erb
app/views/publish/courses/course_button_panel/_published.html.erb
app/views/publish/notifications/index.html.erb
app/views/publish/shared/_aside_information_box.html.erb
config/locales/en.yml
service_unavailable_page/web/public/internal/find.html
spec/components/find/phase_banner/view_spec.rb
spec/features/find/view_pages_spec.rb
swagger/public_v1/template.yml

We need to update the new service name for Find, so that we can enable Teacher Degree Apprenticeship (TDA) courses.
The new service name is:
Find teacher training courses
1. Check each page changed on this PR on the review app and the service name should match with the above.
2. Is there any other place mentioning postgraduate that we should change?
It doesn't change the links. This will be done in a future card/PR.

Change Find service name now that we are accepting undersgraduate courses

---

app/components/find/results/search_result_component.html.erb
app/components/find/results/search_result_component.rb
app/decorators/course_decorator.rb
config/locales/en.yml
spec/components/find/results/search_result_component_spec.rb
spec/decorators/course_decorator_spec.rb
spec/features/find/search/course_results_spec.rb
spec/support/page_objects/find/results.rb

We want to update the "Study type" to "Course length" on Course Results to improve consistency between the results and the detail view
https://trello.com/c/2aQcYZBW
- Updated the label from "Study type" to "Course length" on Course Results
- Updated the text rendered to include the Course length and Study mode
- View course results
|---|---|
| ![Capture-2024-07-18-114543](https://github.com/user-attachments/assets/2c08097c-1594-470f-9891-beac08a4e167) | ![Capture-2024-07-18-113950](https://github.com/user-attachments/assets/9ded142e-e534-4e9f-b66b-e891724619f6) |

Update course length data on search

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/contents_component/view.html.erb
app/components/find/courses/summary_component/view.html.erb
app/views/find/courses/_about_course.html.erb
app/views/find/courses/_advice.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb
config/locales/en.yml
config/locales/find.yml
spec/components/course_preview/missing_information_component_spec.rb
spec/components/find/courses/about_schools_component/view_spec.rb
spec/components/find/courses/contents_component/view_spec.rb
spec/features/publish/courses/editing_course_about_this_course_from_preview_page_spec.rb

This commit updates the course contents summary list to make it easier
for users to navigate the course show/preview page. This is part of a
course page redesign.
Updated the items in the `app/components/find/courses/contents_component`
|---|---|
| ![Screenshot from 2024-07-19 12-04-29](https://github.com/user-attachments/assets/509340fb-5349-49db-913c-89f5b8c08849) | ![Screenshot from 2024-07-19 11-51-43](https://github.com/user-attachments/assets/64566b87-8742-49ea-ac6b-b1e56c6f587c) |
View a course on find and preview it on publish, does the contents_component make sense?

Update section headers for courses

---

app/components/find/courses/fees_component/view.html.erb
app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
config/locales/find.yml
spec/components/find/courses/fees_component/view_spec.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb

This is part of the course show/preview page redesign.
We want to make it easier for users to view this page.
Edit `app/components/find/courses/summary_component.rb`
|---|---|
| ![Screenshot from 2024-07-19 15-50-35](https://github.com/user-attachments/assets/3955cc5d-4904-42ab-aa8b-078cb9d94ae5) | ![Screenshot from 2024-07-19 15-52-27](https://github.com/user-attachments/assets/cef8b5df-520d-48c6-b03b-dd68e23a0880) |
View a course on publish as preview and one on find. Does the summary component make sense?

Reformat summary course 

---

app/components/find/courses/contents_component/view.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb

This is part of a redesign of the course preview(publish) and show page on find
| -- | -- |
| ![Screenshot from 2024-07-22 17-13-28](https://github.com/user-attachments/assets/bcb3fac6-ce15-4b69-a8dc-3f99e0cdd3db) | ![Screenshot from 2024-07-22 17-07-31](https://github.com/user-attachments/assets/bd1c016e-82eb-4aa3-b1cd-2bdac4494a3d) |
Preview a course on publish and view a course on find on the review app

Entry requirements before contents list on course

---

app/views/publish/courses/a_level_requirements/a_level_equivalencies/new.html.erb
app/views/publish/courses/a_level_requirements/consider_pending_a_level/new.html.erb
spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb

Given I have a TDA course
And no A levels
When I try to publish a course
And I click on the error message
And I am on A level page (accept pending A level OR equivalency page) 
And I click back
Then I should be on the course page
1. Does the back links work from course page and from normal wizard?

Change back link when user comes from the course page while trying to publish the course

---

app/assets/stylesheets/components/find/_search-results.scss
app/assets/stylesheets/components/find/_summary-card.scss
app/components/find/courses/entry_requirements_component/view.html.erb
app/components/find/courses/entry_requirements_component/view.rb
app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
app/components/find/results/results_component.html.erb
app/components/find/results/search_result_component.html.erb
app/components/find/results/search_result_component.rb
app/decorators/course_decorator.rb
app/view_objects/find/results_view.rb
app/views/find/results/_non_university.html.erb
app/views/find/results/_university.html.erb
config/locales/en.yml
config/locales/find.yml
spec/components/find/courses/entry_requirements_component/view_preview.rb
spec/components/find/courses/entry_requirements_component/view_spec.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/components/find/results/results_component_spec.rb
spec/components/find/results/search_result_component_spec.rb
spec/decorators/course_decorator_spec.rb
spec/features/find/search/course_results_spec.rb

This is part of a redesign of the course pages and will bring the results page in line with the show/details page
It also includes a refactor of some methods that are used to display the course information on the results page as well on the details page. This way we can change the content in 1 place and have it mirrored in 2 places and will help with content consistency.
| -- | -- |
| ![Screenshot from 2024-07-23 11-49-36](https://github.com/user-attachments/assets/e6240142-c1cd-4d5a-9db4-0e704c63e4f9) | ![Screenshot from 2024-07-23 11-48-58](https://github.com/user-attachments/assets/0e28e719-21cd-455e-8d27-d3463083b2a1) |
Go on review app and search for courses

Update results format for the course index page

---

README.md
config/initializers/canonical_rails.rb
config/initializers/content_security_policy.rb
config/locales/en.yml
config/settings/production.yml
config/settings/production_aks.yml
config/settings/qa.yml
config/settings/qa_aks.yml
config/settings/review.yml
config/settings/review_aks.yml
config/settings/sandbox.yml
config/settings/sandbox_aks.yml
config/settings/staging.yml
config/settings/staging_aks.yml
config/settings/test.yml
maintenance_page/manifests/production_aks/ingress_external_to_main.yml
maintenance_page/manifests/production_aks/ingress_external_to_maintenance.yml
maintenance_page/manifests/qa_aks/ingress_external_to_main.yml
maintenance_page/manifests/qa_aks/ingress_external_to_maintenance.yml
public/robots.txt
service_unavailable_page/web/nginx.conf

The Find domain has change.
We should point to the new domain.
1. All links pointing to find are updated to use the new domain?
2. Is the content security policy working?
3. Is the maintenance page working?

Change Find domain links in all of our services

---

spec/forms/support/provider_contact_form_spec.rb

There is a flakey spec that sometimes are triggered when [deployment ](https://github.com/DFE-Digital/publish-teacher-training/actions/runs/10094751223/job/27913477990).
```
expected: "2431 Collins Tunnel<br> Willow Village<br> O'Hara Row<br> Yundtside<br> Idaho<br> UN5 8BA"
got: "2431 Collins Tunnel<br> Willow Village<br> O&#39;Hara Row<br> Yundtside<br> Idaho<br> UN5 8BA"
```
Fixing so it never happens again.

Fix address to avoid flakey spec when generating single quotes address

---

config/initializers/content_security_policy.rb

This is an attempt to fix the issue:
Refused to connect to 'https://www.google.com/pagead/landing ...'

Add google to content security policy

---

config/initializers/content_security_policy.rb

A continuation of #4406 
This is an attempt to fix the issue:
Refused to connect to 'https://googleads.g.doubleclick.net/ ... '

Add google double click to content security policy

---

app/models/provider.rb
app/services/courses/assign_program_type_service.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/models/course/assign_program_type_spec.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/services/courses/copy_to_provider_service_spec.rb

- Currently when you update the `provider_type` on the provider the `program_type` on the course isn't updated.
Add an `after_save` callback to loop through and recalculate the `program_type` on courses after the `provider_type` has been changed.
- Check the `program_type` of a course in the rails console: `RecruitmentCycle.current.providers.find_by(provider_code: {provider_code}).courses.course_code(course_code: {course_code}).program_type`
- change the `provider_type` in support, e.g: `/support/2025/providers/21213/edit`
- Ensure the `program_type` has correctly updated on all the courses.
- Ensure the other cycle courses haven't inadvertently been affected.

[1876] Ensure `program_type` is updated when `provider_type` changes

---

app/services/courses/assign_program_type_service.rb
spec/models/course/assign_program_type_spec.rb

A TDA course is an apprenticeship, but it has its own `program_type`. We need to ensure the `program_type_service` does not override that.
If the `program_type` is  `teacher_degree_apprenticeship`, it should remain that and not change to `pg_teaching_apprenticeship`.
- Create a TDA course in the next cycle
- Update the `provider_type`
- Check that the `program_type` is still `teacher_degree_apprenticeship`

[1876] Ensure `program_type_service` correctly handles TDA courses

---

app/components/find/courses/qualifications_summary_component/view.html.erb
config/locales/find.yml
spec/components/find/courses/qualifications_summary_component/view_spec.rb

There wasn't any content for tda qualification in the summary component for the course page.
| -- | -- |
| ![Screenshot from 2024-07-31 14-16-16](https://github.com/user-attachments/assets/55bc9225-c5d3-41a2-b038-c0a0c48b491a) | ![Screenshot from 2024-07-31 14-12-08](https://github.com/user-attachments/assets/cd28b6fa-b7e2-4821-9d40-c53d14ec2837) |

Add qualification tda content

---

app/components/find/courses/contact_details_component/view.html.erb
app/controllers/concerns/get_into_teaching_redirect.rb
app/controllers/concerns/provider_website_redirect.rb
app/controllers/find/courses_controller.rb
app/views/find/courses/_advice.html.erb
config/locales/en.yml
config/locales/find.yml
config/routes/find.rb
spec/components/find/courses/contact_details_component/view_preview.rb
spec/features/find/search/viewing_a_course_spec.rb

We have improved our course pages and we need a way of monitoring how our users are interacting with them
[Trello card](https://trello.com/c/y3NKamG9)
The redirect allows us to capture the initial click in big query before sending people out to the provider or get-into-teaching websites.
We can only tests that the redirects take us where we ultimately want to go. We will only know that they are being registered in BigQuery in production.

Git and provider website redirects

---

config/analytics_hidden_pii.yml
config/analytics_pii.yml

We are sending the hidden PII fields separately from other fields that we send to Bigquery.
This means on Bigquery the fields will obfuscated depending on the policy permissions the user has when querying.
For more information about the hidden API there are more details in the Readme:
https://github.com/DFE-Digital/dfe-analytics

Move field from pii to hidden pii

---

app/models/course.rb
spec/models/course_spec.rb

This will also change the description/summary of the course that apply gets from publish. But the sync job should handle this correct as it's just a small content change to the description.
| -- | -- |
| ![image (2)](https://github.com/user-attachments/assets/9fcc8835-937e-472b-a206-57175a4c8820) | ![Screenshot from 2024-08-01 11-39-40](https://github.com/user-attachments/assets/ffbc4e3c-07ce-4046-afac-4c820550ff6f) |
https://publish-review-4418.test.teacherservices.cloud/api/public/v1/recruitment_cycles/2025/providers/4A3/courses/Y704
Go on publish review app and check if content of the course is correct on the index page

Fix the course summary for TDA

---

app/models/course.rb
spec/models/course_spec.rb

Following on from #4415 we are defining an enum for `course_type`  
- Add `course_type` enum (_suffix is required because of naming clash)
See: https://github.com/DFE-Digital/publish-teacher-training/pull/4415#discussion_r1699656588

[2114] Add `course_type` enum

---

config/application.rb

This is not needed as the unpermitted parameters are filtered out before being used. Raising an error is really only recommended for development purposes.
Sentry error: https://dfe-teacher-services.sentry.io/issues/4537046100/?referrer=slack&notification_uuid=d3ec59e7-1eb2-4928-bd00-195b4f64a3c0&alert_rule_id=11137790&alert_type=issue
Removed configuration which raises an error for unpermitted params.

Removed configuration which raises an error for unpermitted params.

---

app/assets/stylesheets/components/shared/_advice.scss
app/assets/stylesheets/govuk_style_setup.scss

We have components that we want styled similarly to the GiT website branding. 
Updated CSS border colours so they are a closer match to the GiT branding
|---|---|
| ![03026c98fd598d46ddc798caf49c63f2](https://github.com/user-attachments/assets/97190c43-35d1-4b90-983c-26cf78d470af) | ![75a44cdf9da6a7b809e694a4c8d6ae99](https://github.com/user-attachments/assets/81b1b82d-8e6c-4fc7-84f0-5b1408a5b625) |
| ![d87e12f67c129923f0e1c7b8a4e68331](https://github.com/user-attachments/assets/10a24fd0-0ffe-4e7c-b5e8-e5a94e81367b) | ![d957447d4f63c41ebdb76118648ad824](https://github.com/user-attachments/assets/0c1ce1fd-dd4a-4867-a256-a72e33ed7876) |

Update styling to match GiT website

---

app/models/course.rb
spec/models/course_spec.rb

Following on from  #4421 we are defining an enum for `funding`. 
Once #4421 is merged, this PR will be rebased to remove the migration.✅ 
- Add `funding` enum.
- ~~**Only the second commit needs to be reviewed, the first commit should be reviewed in #4421.**~~
- Are the predicate methods ok?

[2116] Add `funding` enum

---

app/controllers/publish/courses/outcome_controller.rb
app/services/publish/courses/assign_tda_attributes_service.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/services/publish/courses/assign_tda_attributes_service_spec.rb

We have added a new `course_type` column to our database. 
The majority of our course will be `postgraduate`, the TDA courses are the only exception. Currently there is only one TDA course.
- Set `course_type` to `undergraduate` when creating a TDA course.
- Set `course_type` to `undergraduate` when changing to a TDA course.
- Set `course_type` back to `postgraduate` when changing from a TDA course to a non TDA course.
- Create a non TDA course, check the `course_type` is `postgraduate`
- Change the course to a TDA course, check the `course_type` is now `undergraduate`
- Change the course back to a non TDA course, check the `course_type` is `postgraduate` once again.

[2123] Update `course_type` to `undergraduate` for Teacher Degree Apprenticeship courses

---

app/models/course.rb
config/settings.yml

We are introducing a new database backed `funding` column on the `course` table, replacing the non database backed `funding_type`. This change will allow us to manage funding directly through the database.
To ensure a smooth transition, we will initially place this change behind a feature flag. This approach will allow us to:
- Control the rollout of the new funding column.
- Backfill the `funding` column with existing data through a data migration.
- Provide an easy way to revert the change if necessary.
- The feature flag will remain off in all environments until the migration and feature implementation are complete. Once the feature has been stable in production for a sufficient period, we will remove the feature flag.
- Add the feature flag
- Set to inactive by default
- Add logic to …

[2124] Add `funding` feature flag

---

app/services/find/cycle_timetable.rb

As we approach the new cycle, we will need to have the next cycle defined, so adding it now. There are still some dates to be confirmed, but the opening dates and reject by default dates are agreed.
This PR keeps the dates in sync with the dates defined in Apply. See [this PR](https://github.com/DFE-Digital/apply-for-teacher-training/pull/9678)
- Added dates with an note about what needs to be confirmed later.
- Updated the 2025 dates that have been confirmed.

[1884] Add 2026 cycle dates to codebase

---

app/views/find/courses/_advice.html.erb
config/locales/find.yml
spec/factories/courses.rb
spec/features/find/search/undergraduate/viewing_a_course_spec.rb

TDA courses are not eligible for teacher training advisers.
This ticket is to display a variation of the support and advice section for TDA courses.

Add specific support and advice content for TDA courses

---

Gemfile
Gemfile.lock

DataMigrate 9.4.4 has been yanked from RubyGems
https://rubygems.org/gems/data_migrate

DataMigrate 9.4.4 has been yanked from RubyGems

---

app/serializers/api/public/v1/serializable_provider.rb
bin/build-docs
docs/source/release-notes.html.md.erb
guides/api.md
spec/controllers/api/public/v1/providers_controller_spec.rb
spec/factories/providers.rb
spec/serializers/api/public/v1/serializable_provider_spec.rb
swagger/public_v1/api_spec.json
swagger/public_v1/component_schemas/CourseAttributes.yml
swagger/public_v1/component_schemas/ProviderAttributes.yml

We have added a property to Provider, `selectable_school`. We want to provider this property via the API.
This property must be documented in the API docs.
- Add `selectable_school` to the ProviderAttributes API response.
- Update documentation on how to develop the API docs
https://publish-review-4465.test.teacherservices.cloud/docs/#about
```sh
curl -H 'content-type: application/json' http://publish.localhost:3001/api/public/v1/recruitment_cycles/2024/providers/2AT | jq '.data.attributes.selectable_school'
```
http://publish.localhost:3001/api_docs`
[Update Publish API to return selectable school as part of the Providers API](https://trello.com/c/pew33sLd/2202-update-publish-api-to-return-selectable-school-as-part-of-the-providers-api)

Update Teacher Training API to return `selectable_school`

---

app/controllers/api/public/v1/courses_controller.rb
app/controllers/api/public/v1/providers/courses_controller.rb
app/services/api_course_search_service.rb
app/services/course_search_service.rb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/controllers/api/public/v1/providers/courses_controller_spec.rb
spec/services/api_course_search_service_spec.rb

We need to make sure undergraduate AND postgraduate courses are returned on the API.
This was necessary because the CourseSearchService is used in Find web service although there we will have to filter by course type always on the current designs.
Also added the order by to remove the duplications to be happening on the API

Make sure undergraduate courses and non duplicates appear on the API

---

config/routes/find.rb

This change was made as a result of investigating the following logit errors:
While this change aims to resolve issues related to routing errors, ongoing monitoring will be essential to determine its effectiveness and to identify if further actions are needed.
Remove the `show` route for the `LocationsController` since there is no corresponding `show` action in the controller.
By removing the route, any requests to the non-existent `show` action will now result in a more graceful 404 error page.
Are there any edge cases or unintended consequences that might arise from removing the show route?

[2200] Tighten up routes

---

Gemfile.lock

Reverts DFE-Digital/publish-teacher-training#4481
Could be the cause of Sentry errors that started occurring today. We will revert and monitor: 
https://dfe-teacher-services.sentry.io/issues/5787597219/?alert_rule_id=11137790&alert_type=issue&notification_uuid=302a01e6-c872-418b-bc1b-44851eb7b0e4&project=1377944&referrer=slack

Revert "Bump pagy from 9.0.6 to 9.0.8"

---

Gemfile
Gemfile.lock

Upgrade the data migrate gem to 11 rc3 which is pretty much ready to be 11.0
We are getting errors: 
https://dfe-teacher-services.sentry.io/issues/5787827580/?alert_rule_id=11137790&alert_type=issue&notification_uuid=8bebb020-94ef-47d9-9df3-c8628f5aabf8&project=1377944&referrer=slack

Update data migrate to version 11.0.0.rc3

---

app/controllers/publish/courses/funding_type_controller.rb
app/controllers/publish/courses/visa_sponsorship_controller.rb
app/forms/publish/course_funding_form.rb
app/helpers/publish/back_link_helper.rb
app/models/course.rb
app/policies/course_policy.rb
app/services/courses/creation_service.rb
app/services/publish/courses/assign_tda_attributes_service.rb
app/views/publish/courses/funding_type/_form_fields.html.erb
app/views/publish/courses/skilled_worker_visa_sponsorship/edit.html.erb
app/views/publish/courses/student_visa_sponsorship/edit.html.erb
config/locales/en.yml
spec/factories/course_enrichments.rb
spec/features/publish/courses/editing_apprenticeship_spec.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/features/publish/courses/editing_visa_sponsorship_spec.rb
spec/features/publish/courses/new_accredited_provider_spec.rb
spec/features/publish/courses/new_funding_type_spec.rb
spec/features/publish/courses/new_funding_type_with_db_backed_funding_inactive_spec.rb
spec/features/publish/e2e/new_course_spec.rb
spec/forms/publish/course_funding_form_spec.rb
spec/forms/publish/course_funding_form_with_db_backed_funding_feature_disabled_spec.rb
spec/models/course_enrichment_spec.rb
spec/policies/course_policy_spec.rb
spec/services/courses/creation_service_spec.rb

We have recently added a new `funding` column on the `Course` table which will replace our current implementation of `funding_type` which is not database backed. 
The correct value from the new column is displayed if the funding value has been updated to a real funding value, i.e `fee`, `salary` or `apprenticeship`. 
In this PR we need to ensure that the `funding` value can be updated when creating a new course and updating existing courses. **A backfill is required for this to work properly in production and other environment**s. I've completed the backfill on the review app (to enable more effective reviews).
Note that there are areas where `funding_type` is used for branching.
The branching for the old implementation of `funding_type` will be removed along with the feature flag, so a …

[2234] Ensure `funding` column updates correctly

---

app/services/courses/creation_service.rb
spec/services/courses/creation_service_spec.rb

Fix this sentry error https://dfe-teacher-services.sentry.io/issues/5568099106/?alert_rule_id=11137790&alert_type=issue&notification_uuid=0a46756c-9f13-400d-8c6f-c522c786e80b&project=1377944&referrer=slack
Coerce the study mode params into an array in the creation service.

Fixes sentry error where the study mode param is not always an array

---

terraform/aks/statuscake.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/production_aks.tfvars.json

The certificate expires every 6 months and must be revalidated or users will lose access to the site.
https://trello.com/c/N5YIQd6A/1982-ssl-check-for-find-teacher-training-courses
Add SSL check for the apex domain [find-teacher-training-courses.service.gov.uk](http://find-teacher-training-courses.service.gov.uk/)

Add SSL check for find-teacher-training-courses

---

config/rubocop/rails.yml
lib/tasks/update_selectable_schools.rake
spec/lib/tasks/update_selectable_school_rake_spec.rb

We've identified 11 Provider who wish for their candidates to choose a
school placement. This rake task updates the providers accordingly.
Add Rake task to update specific providers `selectable_school` to true.

Add rake task to set selectable_school to true

---

config/settings/qa_aks.yml
lib/tasks/undergraduate_courses.rake

For the bug party tomorrow, I am enabling the new cycle (to test Find) and add a script that adds new undergraduate (TDA) courses.
To run:
```
rake undergraduate:create # will create 100 undergraduate courses for the first 100 providers from 2025 cycle
PROVIDERS_COUNT=1000 rake undergraduate:create # will create 1000 undergraduate courses for the first 1000 providers from 2025 cycle
```

Create tda courses script and enable new cycle in QA

---

lib/tasks/undergraduate_courses.rake

All qa, staging and other envs are not starting the pod due to faker gem, so let's load inside of the task.
```
bin/rails aborted!
NameError: uninitialized constant Faker (NameError)
Faker::Config.locale = 'en-GB'
^^^^^^^^
/app/lib/tasks/undergraduate_courses.rake:4:in `<main>'
```

Make sure faker does not load in boot time

---

app/models/course.rb
spec/models/course_spec.rb

Adding a way to calculate `training_route` based on a courses `funding` and `course type`.
This is in line with Register, for the routes which apply to Publish.
https://becoming-a-teacher.design-history.education.gov.uk/becoming-a-teacher/routes-into-teaching/
Implement a hash map to easily return `training_route` based on the different combinations of course types and funding types.
- Do the values returned make sense to you? They are in line with Register to help make our services more consistent.
- Any thoughts on having this as  a database backed column? I decided not to do this, as `training_route` should always be calculated the same way, it didn't make sense to me to combine two strings and put it in a new column.

[2267] Implement `training_route`

---

app/models/course.rb
spec/decorators/course_decorator_spec.rb
spec/models/course_spec.rb
spec/serializers/api/public/v1/serializable_course_spec.rb
spec/serializers/api/public/v1/serializable_course_with_db_backed_funding_type_feature_disabled_spec.rb

We need to ensure `program_type` stays in sync with the `funding` column, as although this will be deprecated, we and other services are still dependent on it. 
Add a callback to `Course` which updates `program_type` every time the `funding` is updated. (On the UI or in the console).
- Check `course.program_type` on an unpublished course
- Update `funding` on the course (in the UI or console)
- Check `course.reload.program_type` on the course again and ensure it has been updated to the correct `program_type`
- Ensure the correct text is displayed for the updated course on the course index page

Add a callback to update `program_type` when `funding` updates

---

app/models/course.rb
spec/models/course_spec.rb

We are deprecating `funding_type`. The database backed `funding` column should be used instead going forward.
Put a deprecation warning on `funding_type`
Is this the correct way to do the deprecation warning now? Is there a more appropriate way?
https://everydayrails.com/2021/07/31/rails-custom-deprecation-warnings.html
`ActiveSupport::Deprecation.warn` was deprecated in rails 7.1 and [removed in rails 7.2](https://www.redmine.org/issues/41141#:~:text=The%20usage%20of%20ActiveSupport%3A%3A,with%20a%20custom%20deprecation%20object.)

[2303] Deprecate `funding_type`

---

app/controllers/api/public/v1/application_controller.rb
app/models/recruitment_cycle.rb
spec/controllers/api/public/v1/providers_controller_spec.rb

Handles [Method Not Found Error](https://dfe-teacher-services.sentry.io/issues/4233014348/?alert_rule_id=11137790&alert_type=issue&notification_uuid=3d612f94-fbda-4c93-a06a-77e687acbfcf&project=1377944)
- Added a `RecruitmentCycle#current_recruitment_cycle!` method which will raise a `RecordNotFound` error if the cycle does not exist. The API will return a 404 at this point rather than continue to call `#providers` on a `nil` value

Allow API to 404 when no recruitment cycle is found

---

app/components/find/results/search_result_component.html.erb
config/locales/find.yml
spec/features/find/search/undergraduate/course_results_spec.rb

On find results page, the degree required row should not show any degree requirements.
1. Create and publish a TDA course on publish
2. Make sure Find is on 2025 cycle
3. Search on Find and answer that you don't have a degree, see the results page for undergraduate courses

Degree required for undergraduate should be mentioned differently

---

app/views/find/result_filters/_all.html.erb
config/settings/review_aks.yml
spec/features/find/search/undergraduate/course_results_spec.rb

Observed during Bug Party 3 (10th Sept).
when you search for a TDA course by entering a location (not across England), there is no search radius drop down in the left filters.
We should show when searching by location
1. Search by location
2. When on degree question (choose "yes I have a degree" for postgraduate results and "No, I do not have a degree" for undergraduate results.
3. Check filters

Add search radius filter to undergraduate results

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/contents_component/view.html.erb
app/components/find/courses/training_locations/view.html.erb
app/components/find/courses/training_locations/view.rb
config/locales/en/components/find/training_locations.yml
config/locales/find.yml
spec/components/find/courses/about_schools_component/view_preview.rb
spec/components/find/courses/about_schools_component/view_spec.rb
spec/components/find/courses/contents_component/view_spec.rb
spec/components/find/courses/training_locations/view_preview.rb
spec/components/find/courses/training_locations/view_spec.rb

We are improving the way we display school placements and study sites to candidates.
- Add new text (different depending on salaried course or not)
- Update heading and contents link
- Add component to render the new table
- Loop through school placements attached to the course and render them in the table
- Loop through study sites attached to the course and render them in the table
- Pluralise study sites and school placements if there is more than one
- Visit the course show page on Find and look at the component
- Update the course to have more study sites/school placements
- Remove all the school placements
- Etc
Feeling lazy and can't be bothered? ☝🏼 
I've done the work for you:
[no_study_sites_and_one_placement_fee_paying](https://publish-review-4522.test.teacherservices.cloud/view_ …

[2288] Improve Locations (1/6) Add Training Location Information to course Page

---

app/serializers/api/public/v1/serializable_course.rb
docs/source/release-notes.html.md.erb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/serializers/api/public/v1/serializable_course_spec.rb
swagger/public_v1/api_spec.json
swagger/public_v1/component_schemas/CourseAttributes.yml

- We added `degree_type` as a new column on the course table. 
- We added a calculated `training_route` method to the course model based on `funding` and `degree_type`. 
This PR exposes both of those ☝🏼  on the public API.
- Expose `degree_type` column as an attribute on the public API
- Expose `training_route` column as an attribute on the public API
- Update docs
**Locally (easy)** 
- `api/public/v1/recruitment_cycles/2024/providers/1BJ/courses/2JQP`
**Review app (easier)** 
- https://publish-review-4529.test.teacherservices.cloud/api/public/v1/recruitment_cycles/2024/providers/1BJ/courses/2JQP
**Screenshot - important bits highlighted in yellow (easiest)**

[2336] Add `training_route` and `degree_type` to the API

---

app/components/publish/providers/school_placements/explainer_component.html.erb
app/components/publish/providers/school_placements/explainer_component.rb
app/components/publish/providers/study_sites/explainer_component.html.erb
app/components/publish/providers/study_sites/explainer_component.rb
app/controllers/publish/providers/study_site_search_controller.rb
app/views/publish/providers/schools/index.html.erb
app/views/publish/providers/study_sites/index.html.erb
config/locales/en.yml
spec/components/publish/providers/school_placements/explainer_component_spec.rb
spec/components/publish/providers/study_sites/explainer_component_spec.rb
spec/features/publish/managing_schools_spec.rb

We want to improve Provider understanding around School Placements and Study Sites
- Implemented view components for both sections of content
- Updated content on each section to match requirements
Check wording - it was copy and pasted from the Trello card
|--------|-------|
| ![b94fea61c3d218813a17bfb15e13a14d](https://github.com/user-attachments/assets/b9b3ca75-62a7-4025-a1f4-36455fae9dca) | ![83e5b241c4385010db40edcb4555f564](https://github.com/user-attachments/assets/64e02c5f-58ba-41b9-afa3-d61ce4f6e6b3)    |
| ![09e780acd0434d97f5ce1b93c5be672c](https://github.com/user-attachments/assets/c1d2a0c0-4255-4bd4-9a64-a1839942dfcb)    |  ![61f51fdd8a79d6c89b2dfffbcb653848](https://github.com/user-attachments/assets/97576b5f-3e74-41e5-b61e-aca50176a3f7)  |

Updated school placement and study site provider details

---

app/components/find/courses/about_schools_component/view.html.erb
app/components/find/courses/training_locations/view.html.erb
app/components/find/courses/training_locations/view.rb
app/components/find/results/search_result_component.html.erb
app/components/find/results/search_result_component.rb
app/services/find/cycle_timetable.rb
spec/components/find/courses/about_schools_component/view_spec.rb
spec/components/find/courses/training_locations/view_preview.rb
spec/components/find/courses/training_locations/view_spec.rb
spec/components/find/deadline_banner_component_preview.rb
spec/components/find/show_apply_deadline_banner_cycle_timetable.rb
spec/components/find/show_apply_opens_soon_banner_timetable.rb
spec/components/find/show_cycle_closed_banner_timetable.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/services/find/cycle_timetable_spec.rb

In the 2025 Recruitment Cycle, some providers will allow candidates to choose preferred school placement locations.
For those providers we will show a link on the Find Course page so the candidates can see the potential school placements.
For the providers who will not give the candidates the opportunity to choose a preferred school placement, we do not show that link.
> The link to view school placements and the separate page is hidden by default.
> 
> Logic is added to only display the link and the separate page when providers have asked for an exception.
> 
> Schedule the change to go live on 1 October 2024
**I have not blocked the path to the school placements page, I feel this can be deprioritised.**
**Hide View School placements link for courses in 2025+ where school_selectable is …

[2304] Improve locations: 2/6 Add logic to hide school placements

---

config/settings/qa_aks.yml

People within the team wants to take a look how Find would look like when Find opens next week, so switching the cycle in QA.

Changing cycle on Find QA

---

guides/support_playbook.md

We are adding guidance for changing TDA courses to a non TDA course And vice versa as there are a lot of steps involved and something could easily be missed.
Ideally this would be handled by the support team, but the guidance is there incase it does go to dev.

Add guidance for changing TDA courses to a non TDA course

---

app/controllers/publish/providers/school_placements_controller.rb
app/views/publish/providers/details.html.erb
app/views/publish/providers/school_placements/edit.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/features/publish/edit_provider_details_spec.rb
spec/support/page_objects/publish/provider_details_show.rb

Providers have the ability to change the setting which shows/hides the School Placements page to candidates when they are applying of any of their courses.
This only affects the courses for which the provider is the training provider.
Add provider controls for turning on and off the school placement selection in apply and also showing / hiding the link on Find courses that shows the list of potential placement schools available.
[Screencast from 25-09-24 09:01:00.webm](https://github.com/user-attachments/assets/4d235a67-1620-44fe-a797-958aa0b54d3f)

Provider can set selectable school property

---

config/settings/qa_aks.yml

While QA is in the next cycle, we should close the second cycle because the 2026 cycle does not exist.

Close the next cycle on QA

---

spec/components/find/courses/entry_requirements_component/view_preview.rb

Our Component Preview is not showing the SKE notice because the Subject code used in it doesn't correspond to a subject for which the SKE notice should be displayed

Use a SKE subject code in entry requirements component preview

---

lib/tasks/update_selectable_schools.rake

Add another provider to the set of providers that should have `selectable_school` enabled for 2025.
See the [Trello ticket](https://trello.com/c/pDpPujWe/2203-add-datamigration-to-set-selectable-school-on-providers) for the list of providers to enable

Add provider E69 to rake task for enabling `selectable_schools`

---

terraform/aks/workspace_variables/production_aks.tfvars.json

We know that a large proportion of the total number of applications are made within the first week of apply opening (8 October). In the run up to this, potential candidates will be searching for courses as soon as find opens on 1 October. 
Increases the number of web replicas. We will revert this change after apply has been open for a week (15 October). 
We are not increasing the workers at this point, but can do it on the fly if required.

[2367] Scale pods for start of cycle

---

app/components/find/results/no_results_component.html.erb
app/components/find/results/no_results_component.rb
app/view_objects/find/results_view.rb
config/locales/en/components/find/no_results_component.yml
config/settings/review_aks.yml
spec/components/find/results/no_results_component_spec.rb
spec/components/find/results/results_component_spec.rb
spec/features/find/search/undergraduate/course_results_spec.rb

When Teacher Degree Apprenticeships launches it is likely there will be no or very little courses available.
This may cause a dead end on the search results page, which isn’t a good user journey.
Adding a more detailed explanation could help users.
This is a short term solution and there are talks for a long term solution if this problem persists.
1. Enter on review
2. Answer that you don't have a degree
3. See no results page and see content

Show specific no results message when searching undergraduate courses

---

app/decorators/course_decorator.rb
app/helpers/view_helper.rb
app/views/find/courses/accrediting_providers/show.html.erb
app/views/find/courses/providers/show.html.erb
app/views/find/courses/training_with_disabilities/show.html.erb
app/views/find/placements/index.html.erb
app/views/publish/courses/course_button_panel/_published.html.erb
app/views/support/_menu.html.erb
config/settings.yml
config/settings/loadtest.yml
config/settings/production.yml
config/settings/production_aks.yml
config/settings/qa.yml
config/settings/qa_aks.yml
config/settings/review.yml
config/settings/review_aks.yml
config/settings/rollover.yml
config/settings/sandbox.yml
config/settings/sandbox_aks.yml
config/settings/staging.yml
config/settings/staging_aks.yml
spec/decorators/course_decorator_spec.rb
spec/features/find/search/viewing_a_course_spec.rb
spec/requests/find/feature_flags_spec.rb

We use FeatureFlags to control some aspects of the Find services state. These FeatureFlags are not easily found. We can add a link to the feature flags in the Publish Support console.
1. Add a link in the Publish Support console Navigation Bar to the Find Feature Flags
2. Replace `Settings.search_ui.base_url` with `Settings.find_url`
3. Replace ViewHelper#search_ui_url` with `#x_find_url`
The `x_` prefix is to help easily distinguish a method we've added from rails named routes that are generated.

[2349] Add a link to the Find service's Feature Flags in Publish Support Interface

---

config/settings.yml
config/settings/qa_aks.yml
spec/components/find/courses/training_locations/view_spec.rb
spec/controllers/publish/courses/outcome_controller_spec.rb
spec/features/find/result_page_filters/back_to_results_spec.rb
spec/features/find/result_page_filters/engineers_teach_physics_spec.rb
spec/features/find/search/across_england/primary_spec.rb
spec/features/find/search/across_england/secondary_spec.rb
spec/features/find/search/editing_a_search_spec.rb
spec/features/find/search/undergraduate/course_results_spec.rb
spec/features/find/search/undergraduate/viewing_a_course_spec.rb
spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
spec/features/publish/preview_teacher_degree_apprenticeship_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb

**This PR will end rollover. Do not merge until Tuesday 1st of October 2024.**
This PR will close the `2024` recruitment cycle and the `2025` recruitment cycle will become the `current_recruitment_cycle`.
- Update `recruitment_cycle_year`
- Remove rollover settings from QA (these would now be duplicated)
- Fix failing tests
Have a general click around on the review app and ensure all the functionality still works as expected.

[2049] End rollover 2024

---

app/components/find/courses/summary_component/view.rb
app/components/find/results/search_result_component.rb
app/decorators/course_decorator.rb
app/services/publish/courses/assign_tda_attributes_service.rb
spec/components/find/courses/sumary_component/view_preview.rb
spec/components/find/courses/sumary_component/view_spec.rb
spec/components/find/results/search_result_component_spec.rb
spec/decorators/course_decorator_spec.rb
spec/factories/courses.rb
spec/services/publish/courses/assign_tda_attributes_service_spec.rb

Found one TDA course on QA/Production with fees on it.
TDA courses shouldn't have fees. This bug happens when the user switch from postgraduate to undergraduate courses.
On Find the fee shouldn’t be displayed as the course fee is only for fee funding courses.
The potential reason of this bug is when changing Non TDA to TDA course might have set the fee and not being erased when the course is changed to TDA
Erase fees if course is changed from Non TDA to TDA courses. If the user change back they will have to enter fees again.
1. Create a postgraduate courses
2. Enter fees
3. Switch to a TDA course (basic details -> qualifications)
4. Check if the fees are visible (or in the database)

2382 course fee is wrong when changing non tda to tda course

---

lib/tasks/undergraduate_courses.rake
spec/factories/courses.rb

For some time we won't have any TDA course so for now we need to generate many courses to test Find or Publish.
So this rake task create TDA courses and make sure the data is more correct (no fees, no secondary courses for primary schools, etc)
1. Run the rake task `rake undergraduate:create`
2. Does it work locally when searching on Find?

Setup test undergraduate courses data for Find

---

app/services/enrichments/copy_to_course_service.rb
spec/services/enrichments/copy_to_course_service_spec.rb

We added this to the rollover script in #4347 to remove all the `personal_qualities` and `other_requirements` from all of the courses since we no longer surface the information.
Now that all courses have had this information erased, we should remove this from the rollover script as it is unnecessary and could confuse people in the future.

Revert removing `personal_qualities` and `other_requirements` from rollover script

---

app/controllers/find/feature_flags_controller.rb
spec/requests/find/feature_flags_spec.rb

We have a redirect that comes into effect before we re-open Find. This redirect prevents us from reaching the Feature Flags on Find. We need to reach the feature flags to turn off bursary information
Skip the redirect on the feature flags controller

Feature flags must be available even if Find is down

---

app/decorators/course_decorator.rb
app/mailers/course_publish_email_mailer.rb
app/mailers/course_update_email_mailer.rb
app/models/course.rb
app/models/provider.rb
app/serializers/api/public/v1/serializable_course.rb
spec/components/find/courses/sumary_component/view_preview.rb
spec/controllers/publish/courses/outcome_controller_spec.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/features/publish/courses/editing_funding_type_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/mailers/course_publish_email_mailer_spec.rb
spec/mailers/course_update_email_mailer_spec.rb
spec/models/course/assign_program_type_spec.rb
spec/models/course_spec.rb
spec/services/courses/assign_subjects_service_spec.rb
spec/services/courses/creation_service_spec.rb
spec/services/publish/courses/assign_tda_attributes_service_spec.rb

We have added a deprecation warning to `funding_type` and re-directed people to the database backed version (`funding`) instead.
We want to update our code to use the `funding` instead of `funding_type` so that it is cleaner and it doesn’t cause confusion in the future.
We are aiming for the low hanging fruits here, so if there are any that are particular difficult, this will be out of scope.
- We have updated `funding_type` to `funding` in the codebase (all or at least most)
- We receive less (or no) deprecation warnings relating to `funding_type`
Have a click around and ensure all functionality continues to work. Especially functionality related to funding, e.g creating a course, changing funding, changing to a TDA course etc.
`funding_type` is still coming through on the API

[2415] Update `funding_type` to `funding`

---

app/components/a_level_row_component.html.erb
app/components/a_level_row_component.rb
app/components/a_level_subject_requirement_row_component.rb
app/components/find/courses/a_level_component/grouped_a_level_subject_requirements.rb
app/components/find/courses/a_level_component/view.html.erb
config/locales/en.yml
spec/components/a_level_row_component_spec.rb
spec/components/find/courses/a_level_component/grouped_a_level_subject_requirements_spec.rb
spec/components/find/courses/a_level_component/view_spec.rb
spec/components/find/courses/entry_requirements_component/view_spec.rb
spec/components/find/courses/teacher_degree_apprenticeship_entry_requirements/view_spec.rb
spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
spec/features/publish/preview_teacher_degree_apprenticeship_course_spec.rb

We received feedback from a provider that they cannot add a TDA course, as they want the A level requirements to be more flexible to include equivalent qualifications, such as level 3 qualifications.
See trello card for the prints
1. Create TDA course and many A level variations (Grade A, Grade A*, custom grade).
2. See card for the content changes for the variations

Add content on A levels to include equivalent qualifications

---

app/components/shared/courses/financial_support/fees_and_financial_support_component/view.html.erb
app/models/recruitment_cycle.rb
app/views/publish/courses/_description_content.html.erb
config/locales/en.yml
spec/features/find/search/viewing_a_course_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb
spec/models/recruitment_cycle_spec.rb

Provider raised a support ticket about financial support duplication, Reading the code I understood this field is only for "< 2025 courses"
Support ticket: 
https://trello.com/c/7pXkBeQ8/309-fees-and-financial-support-info-duplicated

Use old financial support field only for 2024 courses and previous cycles only

---

.github/CODEOWNERS

We want to automatically include all @DFE-Digital/publish-and-find developers in all PR reviewers.
By adding a CODEOWNERS file, we can automatically set code owners as reviewers.
We require, at minimum, a single review from anyone in the team.
- Add `.github/CODEOWNERS` file.
Nothing in particular.

Add @publish-and-find CODEOWNERS to cover entire repo

---

config/initializers/console.rb

When working in the console it's useful to have ActiveRecord objects printed with all their attribute values.
Rails by default will not print the attributes apart from the id anymore.
This change will restore the printing of all attributes on all objects unless the environment is production.
(If you really want to see the attributes in production, just run 
```ruby
ActiveRecord::Base.attributes_for_inspect = :all
SomeModel.attributes_for_inspect = :all
```
To change it back to the default
```ruby
ActiveRecord::Base.attributes_for_inspect = [:id]
SomeModel.attributes_for_inspect = [:id]
```
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/260bace4-c768-464a-8dee-25aff225e546)|![image](https://github.com/user-attachments/assets/83861987-114e-43f0-93f0-8f3d080c5f6 …

Show ActiveRecord object attributes in console except production

---

app/controllers/find/application_controller.rb
app/controllers/find/search/subjects_controller.rb
app/controllers/find/search/university_degree_status_controller.rb
app/controllers/find/search/visa_status_controller.rb
app/models/concerns/courses/edit_options/qualification_concern.rb
app/models/course.rb
app/models/provider.rb
config/settings.yml
config/settings/development.yml
spec/controllers/publish/courses/outcome_controller_spec.rb
spec/features/find/search/across_england/further_education_spec.rb
spec/features/find/search/undergraduate/course_results_spec.rb
spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/courses/publishing_a_teacher_degree_apprenticeship_course_with_validation_errors_spec.rb
spec/features/publish/preview_teacher_degree_apprenticeship_course_spec.rb
spec/models/concerns/courses/edit_options/qualification_concern_spec.rb
spec/models/concerns/courses/edit_options_spec.rb
spec/models/provider_spec.rb

Once the TDA work is live for a while and we are in the 2025 cycle, we should remove the feature flag and TDA checks.
Remove all feature flag checks for Find and Publish for teacher degree apprenticeship feature.
This means that:
1. The option "Teacher degree apprenticeship" on qualifications page in Publish will be shown always
2. The question "Do you have a university degree" in Find will be shown always
1. Is the feature flag checks got removed?
3. Is the feature flag active? `FeatureService.enabled?(:teacher_degree_apprenticeship)` should be `false`
4. Can you create a teacher degree apprenticeship?  - it should allow to create TDA courses no matter if the feature is active or not. ([one example](https://publish-review-4597.test.teacherservices.cloud/publish/organisations/4A3/2025/cour …

Remove the Teacher degree apprenticeship feature flag from Find & Publish

---

app/controllers/find/placements_controller.rb
app/views/shared/courses/_placements.html.erb
config/locales/en.yml
spec/controllers/find/placements_controller_spec.rb
spec/features/find/search/viewing_a_course_spec.rb

The school placements page is only shown for courses which have chosen to show placement locations (selectable_school_on). 
These providers want candidates to be able to choose a placement location, which means [the existing content is wrong](https://trello.com/1/cards/66e05f6b535a2312652618f9/attachments/66e05fbe6de03ba9a1c982fa/download/find-teacher-training-courses.service.gov.uk_course_G70_G615_placements_(1).png).
This PR is about the change of this content.
And make sure the couses which you can't select a school, can't render the `/placements` page.
**Before**
**After**
1. No links to school placements page should show if the provider didn't enable the setting to select a school placement
2. And if you try to go manually to any /placements for the courses on step 1, you should a …

Replace content on school placements page

---

app/services/publish/accredited_provider_updater.rb
spec/services/publish/accredited_provider_updater_spec.rb

We have identified several Providers that have incorrect Accredited Provider details. We want to be able to update these Providers and their Courses.
Added service to handle the logic involved in updating the Accredited Provider
This is loosely based on a [gist](https://gist.github.com/avinhurry/ab64d4dc83dbc018b1dbda1eb2195624) shared by @avinhurry 
N/A

Added a AccreditedProviderUpdater service

---

app/services/publish/accredited_provider_updater.rb
spec/services/publish/accredited_provider_updater_spec.rb

Amendment to an existing data migration.
We want the updated_at to change so the incremental sync in apply will pick up
the changes
Use the `update` methods to update providers and courses. This will update the `updated_at` column and schedule the models for updating in the TTAPI.

Run migration with callbacks to update updated_at

---

app/controllers/component_previews_controller.rb
app/controllers/support/component_previews_controller.rb
app/views/layouts/component_preview.html.erb
app/views/support/_menu.html.erb
app/views/view_components/index.html.erb
app/views/view_components/previews.html.erb
config/application.rb
config/routes.rb

Good to have a link to the View Component Previews so everyone can access them.

Add link to View Component previews in Support

---

app/components/find/courses/about_schools_component/view.rb
app/components/find/courses/contents_component/view.html.erb
app/decorators/course_decorator.rb
app/views/find/courses/show.html.erb
config/locales/find.yml
spec/components/find/courses/contents_component/view_preview.rb
spec/components/find/courses/contents_component/view_spec.rb

Currently, the order of the course page is problematic for candidates, as they have to skip over some sections to get to key information they need to narrow down courses before delving into the detail. [See example of the live site](https://trello.com/1/cards/66df067eb52d058bd38651e4/attachments/66df073ffef4da0a1a4afd68/download/find-teacher-training-courses.service.gov.uk_course_2FR_X558.png).
* Update “Course details” title Update “Course details” to “About the course”
* Reorder of the contents section and the content
* Make sure contents section has the same equivalent check on render the content as well.
The order of the sections on the course page and in the contents list should be as follows:
Where you will train
Fees and financial support
About the course
Interview process
Training …

Reorder contents section on course pages

---

db/data/20241024085622_publish_2024_course.rb

Register team are having problems importing an Application from Apply due to the Course not being visible on Publish API.
As a fix we want to publish the Course in question. To do this openly it has been put into a Data Migration
Data Migration publishes a specific course
- N/A

Publish a 2024 Course

---

app/views/support/providers/accredited_providers/index.html.erb
spec/features/support/providers/accredited_providers_spec.rb

When inspecting a training providers accredited providers, there is not link to easily navigate to the accredited provider from that page.
Add a link to we 
1. Enter on one provider (a lead school e.g `support/2025/providers/21176`)
2. Click on accredited providers tab
3. See the links ✌️

Add a link to the accredited provider on support page

---

app/components/publish/providers/school_placements/explainer_component.html.erb
app/views/pages/add_schools_and_study_sites.html.erb
spec/components/publish/providers/school_placements/explainer_component_spec.rb

Now that some training providers can opt to show placement school locations in Find and Apply, we can update the content in Publish to reflect this option to improve awareness.

Change content about the service in relation to placement locations

---

spec/features/publish/searching_for_a_school_spec.rb

A test keeps failing intermittently on CI.
```
Failures:
1) Searching for a school from the GIAS list i can search for a school by query
Failure/Error: expect(page).to have_no_content @school.name
expected not to find text "Bernard" in "Cookies on Publish teacher training courses\nWe use some essential cookies to make this service work.\nWe’d also like to use analytics cookies so we can understand how you use the service and make improvements.\nAccept analytics cookies Reject analytics cookies View cookies\nSkip to main content\nGOV.UK Publish teacher training courses\nSign out (Micheline Stokes)\nTest This is a new service – your feedback will help us to improve it.\nCourses Schools Study sites Users Accredited providers Organisation details\nBack\nAdd school 3 results found for …
```

Fix intermittent spec

---

.github/PULL_REQUEST_TEMPLATE.md
guides/development-workflow.md

The PR checklist is often ignored due to its stagnant nature. Let's remove it from the PR template to ensure PR descriptions only contain significant information.
Additionally, let's move the PR checklist into developer docs about PR guidelines.
- Review [the Development Workflow documentation](https://github.com/DFE-Digital/publish-teacher-training/blob/dd/remove-checklist-from-pr-template/guides/development-workflow.md).

Remove checklist from PR template

---

app/components/persona.html.erb
app/controllers/publish/providers_controller.rb
app/controllers/publish/publish_controller.rb
config/routes/publish.rb
config/settings/test.yml
spec/controllers/sessions_controller_spec.rb
spec/features/publish/editing_notification_preference_spec.rb
spec/features/publish/viewing_a_course_spec.rb
spec/requests/publish/authorization_spec.rb

This PR fixes a bug that allowed any provider user to visit the courses pages (and more ) of any provider in the system. 
We've added an `authorize provider` call to a before action in the parent PublishController which authorizes all requests to any action in that controller.
Some of the tests had to be changed so that the user perfroming the action under test had an explicit association with the provider they are interacting with in the test.

Users should not see any providers without explicit association

---

app/controllers/publish/providers_controller.rb
spec/requests/publish/providers_controller_spec.rb
spec/support/authentication/mode/request_specs_dfe_signin.rb
spec/support/derived_metadata.rb
spec/support/dfe_sign_in_user_helper.rb

Bug fix. I mistakenly removed call to authorize without explicitly skipping the authorization.
We have an after_action call back that asserts that some authorization was done, unless we explicitly skip it.
- Add some request spec helpers for authentication
- Add before action to all request specs setting the apps host so it can be reached

Skip authorization on /publish/providers/suggest

---

config/settings.yml

There is inconsistency of terminology between GiT and Find. GiT use “QTS with PGDE” (which is more clear/intuitive) whereas Find uses “PGDE with QTS”. 
It was decided by Apply and Find teach leads to change the API content of the course description to the expected ones (PGCE with QTS becomes QTS with PGCE and PGDE with QTS becomes QTS with PGDE).
This is a simple PR that just adds the feature flag.
Will be `false` as default in all environments.
1. Merge the feature flag PR (this PR!)
2. Merge the code that uses the feature flag (#4645 )
3. Turn on the feature flag on QA when having a session with Register & Apply (needs a PR and deployment) 
4. Have the Register & Apply sign off that everything worked 
5. Turn on the feature flag on Production (needs a deployment) and also deploy the API …

Add feature flag for the API summary content change

---

config/initializers/webrick.rb

Long URLs, due to selecting _many/all_ secondary subjects breaks the web application due to default security constraints.
The default maximum length is 2083 characters long.
- Double the maximum URI length to 4166.
- Visit the following url before and after:
- http://find.localhost:3000/results?age_group=secondary&applications_open=true&can_sponsor_visa=false&has_vacancies=true&l=2&subjects%5B%5D=A1&subjects%5B%5D=A2&subjects%5B%5D=W1&subjects%5B%5D=C1&subjects%5B%5D=08&subjects%5B%5D=F1&subjects%5B%5D=09&subjects%5B%5D=Q8&subjects%5B%5D=P3&subjects%5B%5D=11&subjects%5B%5D=12&subjects%5B%5D=DT&subjects%5B%5D=13&subjects%5B%5D=L1&subjects%5B%5D=Q3&subjects%5B%5D=15&subjects%5B%5D=F8&subjects%5B%5D=17&subjects%5B%5D=L5&subjects%5B%5D=V1&subjects%5B%5D=18&subjects%5B%5D=19&subjects%5B%5D=A0&s …

Increase max uri length

---

app/components/find/courses/qualifications_summary_component/view.html.erb
app/components/find/courses/qualifications_summary_component/view.rb
app/components/find/courses/summary_component/view.html.erb
app/models/concerns/with_qualifications.rb
app/models/course.rb
app/serializers/api/public/v1/serializable_course.rb
app/views/publish/courses/_course_table_row.html.erb
config/locales/en.yml
config/locales/find.yml
spec/components/find/courses/qualifications_summary_component/view_preview.rb
spec/components/find/courses/qualifications_summary_component/view_spec.rb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/features/publish/courses/editing_course_outcome_spec.rb
spec/services/course_attribute_formatter_service_spec.rb

There is inconsistency of terminology between GiT and Find. GiT use “QTS with PGDE” (which is more clear/intuitive) whereas Find uses “PGDE with QTS”.
This PR replaces all instances of `PGDE with QTS` to `QTS with PGDE`. 
It was decided by Apply and Find teach leads to change the API content of the course description to the expected ones 
1. PGCE with QTS becomes QTS with PGCE
2. PGDE with QTS becomes QTS with PGDE
In order to coordinate this change with this other team this PR:
1. Changes everything in the UI
2. Uses a feature flag for the `course.summary` field in the API.
So this is the plan to deploy this:

Replace instances of PGDE with QTS / change API course summary

---

app/controllers/publish/notifications_controller.rb
app/controllers/publish/publish_controller.rb
spec/requests/publish/authorization_spec.rb
spec/requests/publish/providers_controller_spec.rb

- do not try to authorize a provider instance.
- return a 200
- return a 403
- return a 404
We added a `before_action` in the `PublishController` to enable an allow list for provider authorization. This means that by default we try to protect all actions by authorizing the user making the request.
Not all actions will need to instantiate a provider and will not send a `provider_code_param` (collection actions) so we need to ignore the authorization call for those actions.
We removed the exception raising version of the provider find method because we were calling it with nil. Now that we are avoiding that, we can raise an exception when the param does not find a record in the database. (404)
If a user passes a provider code that they are not authorized for, we retreive it from the …

Handle publish providers 404

---

terraform/aks/workspace_variables/production_aks.tfvars.json
terraform/aks/workspace_variables/qa_aks.tfvars.json
terraform/aks/workspace_variables/sandbox_aks.tfvars.json
terraform/aks/workspace_variables/staging_aks.tfvars.json

Statuscake alerts for publish-find need to go to a separate contact group from apply
https://trello.com/c/ffXbQoj8/2136-publish-update-statuscake-group
Update new contact group in terraform
make qa deploy-plan

Add new statuscake contact group

---

.gitignore
bin/setup
config/settings.yml
config/settings/development.yml
docker-compose.yml

Some minor cleanup.
- Add `.env.local` and `.env.*.local` to `.gitignore`.
- The recommendation is to use `.env.development.local` for local ENV vars - namely to avoid any clash with other environments or in the very rare case that this file is added to git, it doesn't effect production - Unlike `.env` would.
- Update local default authentication mode to `persona`.
- Expose ports of `docker-compose.yml` services.
- Does this break any of your workflows?

Update miscellaneous development setup

---

Gemfile
Gemfile.lock
app/views/layouts/provider_record.html.erb
app/views/support/courses/index.html.erb
app/views/support/providers/_list.html.erb
spec/features/support/providers/providers_filter_spec.rb

As we are currently trying to sort out provider relationships, namely the accredited providers associated with courses and therefore lead partners, we want to add visual assistance to our support console.
This should act as visual aid when discussing these topics.
- Surface provider type on provider details support pages.
- Surface provider type on provider list.
- Surface ratifying provider on provider course list support pages.
- Visit the review app.

Add more provider and course information to support lists

---

app/views/find/result_filters/_qualifications_filter.html.erb
app/views/find/result_filters/_study_type_filter.html.erb
spec/features/find/result_page_filters/applications_open_spec.rb
spec/features/find/result_page_filters/degree_required_spec.rb
spec/features/find/result_page_filters/qualifications_spec.rb
spec/features/find/result_page_filters/salary_spec.rb
spec/features/find/result_page_filters/send_spec.rb
spec/features/find/result_page_filters/study_type_spec.rb
spec/features/find/result_page_filters/visa_spec.rb
spec/support/filters_feature_specs_helper.rb

Currently the default view of filters has the ‘Study type’ and ‘Qualifications’ checkboxes checked to indicate that they are all selected.
We want to change this to all the checkboxes being unchecked by default, still to indicate that they are all selected.
*Before*
*After*
1. Do a Find search
2. Study type and qualification filters should be unchecked by default
3. Select all study types and qualfications
4. Study type and qualification filters should be checked
5. Now filter by specific study type or qualification
6. Does the filters still continuing to work as expected?

Update filter default: uncheck Study type & Qualifications checkboxes

---

app/views/publish/providers/school_placements/edit.html.erb
config/locales/en.yml

We implemented radio buttons in Publish to allow providers to select whether they want to display school locations to candidates in Find and allow them to select a placement in Apply.
To get this functionality in by the start of the cycle we used holding content. 
This PR is to make some small changes to make the content more descriptive of what the buttons do.
1. E.g Visit https://publish-review-4691.test.teacherservices.cloud/publish/organisations/4A3/2025/details
2. E.g Visit https://publish-review-4691.test.teacherservices.cloud/publish/organisations/4A3/2025/school_placements
3. Does the content looks as expected in the trello card?

Enhancements to the selectable school content

---

config/routes.rb

The `www2` host is no longer resolved within our DNS routes. We can safely drop this routing constraint/redirection.
The `www2` host was used as a preview host for the new publish application: https://github.com/DFE-Digital/publish-teacher-training/pull/2655
- Drop the `www2` route group.
- Try visiting https://www2.publish-teacher-training-courses.service.gov.uk/, it should fail. This means we can safely drop the host constraint and routes within the group.

Remove www2 route redirection

---

app/views/support/providers/_list.html.erb

It is useful for our team to see which accredited providers are
missing an accredited provider number
Show a providers' accredited Provider number in the support console.
[Review App Support Console](https://publish-review-4688.test.teacherservices.cloud/support/2025/providers)

Add accredited provider number / id to Support Provider list

---

config/puma.rb
config/settings.yml
config/settings/development.yml

We don't need to setup SSL on our local machines. If we needed to test SSL locally, we can use a secure tunnelling service.
- Remove all `use_ssl` references.
- Remove SSL config in `config/puma.rb`.
Try running `rails s` and `bundle exec puma` locally. Both should work.

Remove local SSL configurations

---

app/models/provider.rb
spec/models/provider_spec.rb

Provider names should not not contain multiple spaces.
- Normalize `Provider#provider_name` to de-dup whitespaces and strip excess ones.
- Should we add a data migration to clean up existing records?

Normalize provider names

---

config/environments/production.rb

We do not need to send all of DfE analytics to our logs.
Do not log DfE analytics.
1. Does logit on this review app logging DfE analytics?

Don't log DfE analytics events

---

app/controllers/publish/training_providers/course_exports_controller.rb
app/models/course.rb
app/services/exports/accredited_course_list.rb
spec/factories/courses.rb
spec/features/find/result_page_filters/salary_spec.rb
spec/features/publish/courses/editing_course_length_spec.rb
spec/models/course_spec.rb
spec/services/exports/accredited_course_list_spec.rb

The accredited provider's download of all courses they ratify times out for some providers. We need to investigate the cause and how to fix it.
- Remove `.includes` call when loading the accredited course list. More information in commit message: [137a46e](https://github.com/DFE-Digital/publish-teacher-training/pull/4708/commits/137a46e4adb8a4724f23d41e8620c6795009197e)
- Change the program type re-assignment based on fee to run before a database write occurs. (Whilst testing the `spec/services/exports/accredited_course_list_spec.rb` spec, it would fail _`course.program_type == course.program_type`_. This is because one of the instances was taken from the database, one ran the after_save callback.
- Visit http://publish.localhost:3000/publish/organisations/C58/2025/training-providers and …

Stop pre-loading accredited course list associations

---

app/services/courses/publish_service.rb
spec/services/courses/publish_service_spec.rb

Courses may be #published? and still not appear in the API. When we
publish a course, we should expect it to appear in the API.
When publishing a course we should undiscard the course if it has been
discarded
PunlishService will undiscard a course in the process of publishing it.

Undiscard the course when publishing

---

config/settings/qa.yml
config/settings/review.yml

Now that the PGDE/PGCE changes are live (see https://github.com/DFE-Digital/publish-teacher-training/pull/4645 ) we can enable the feature in QA in order to ask Apply and Register to test their sync on QA.
Enable the API content changes in QA for Register & Apply team.
After merging this PR, you can request any course in the QA API and the summary attributes will be changed from:
1. "PGCE with QTS" into "QTS with PGCE ..." 
2. "PGDE with QTS" into "QTS with PGDE ..."

Enable API course description changes in QA

---

Gemfile
Gemfile.lock
app/lib/publish_constraint.rb
config/rubocop/style.yml
spec/rails_helper.rb
spec/spec_helper.rb
spec/support/dfe_sign_in_user_helper.rb
spec/support/system_test_config.rb
spec/system/find/load_the_service_spec.rb
spec/system/publish/load_the_service_spec.rb
spec/system/support/load_the_service_spec.rb

- Bundle selenium-webdriver to enable system tests to launch in the browser.
- Add starter tests for each service.
Cannot yet run javascript tests in CI. Have not yet figured out how the chromedriver gets automatically installed by Selenium Manager.
How can we get js tests running in CI?

Add selenium / system_test

---

.github/actions/restore/action.yml
.github/workflows/database-restore.yml
guides/setup-development.md

We want to use an Azure storage account for all backups
Update database backup and restore workflow and action
- check code
- test run with qa restore https://github.com/DFE-Digital/publish-teacher-training/actions/runs/12056187697

Use azure storage account for all backups

---

app/controllers/find/v2/results_controller.rb
config/routes/find.rb
config/settings.yml
spec/features/find/v2/results/search_results_disabled_spec.rb
spec/features/find/v2/results/search_results_enabled_spec.rb
spec/features/find/v2/results/search_results_feature_flag_disabled_spec.rb
spec/features/find/v2/results/search_results_feature_flag_enabled_spec.rb

The goal of this PR is to create a second results page (behind a feature flag) that we can start to consolidate the good foundation for the search engine intelligence.
A new course results page is added
For now we won’t display any courses or anything (to be done in the next cards) This page is behind a feature flag
Add an empty controller and view behind a feature flag for now.
1. Is the `V2` naming good? (If not, please provide suggestions)
The tests are remporarily until the next card where will show all courses paginated.
Then later down the line we will add one filter at a time with sorting coming last.
[Any doubt check the outcome card and its checklist](https://trello.com/c/hoQqU8XQ/256-outcome-improve-course-search-engine-by-setup-a-good-foundation-for-the-pre-filter-work)

Add new results page to create our new search mechanism

---

config/application.rb

Sidekiq needs to be explicitly enabled in Skylight.
https://www.skylight.io/support/background-jobs#using-skylightyml
https://www.skylight.io/support/background-jobs#enabling-frameworks
Enable our Application Performance Monitoring tool to collect data on our background jobs
[Link to the review process](https://www.skylight.io/app/applications/P29Oy7glIJ6w/recent/5m/endpoints) (might disappear by the time you see this)

Enable ActiveJob in skylight

---

app/components/providers/provider_list/view.html.erb
app/controllers/support/providers_controller.rb
app/forms/support/update_provider_form.rb
spec/forms/support/update_provider_form_spec.rb
spec/system/support/update_provider_spec.rb

Only Accredited providers should have an `accredited_provider_number`
Add simple UpdateProviderForm
It accepts attributes and uses `ActiveRecord::Base#assign_attributes` to assign the attributes. Not much needs to be tested here.
It removes the `accredited_provider_number` if the attribute assignment changes `accrediting_provider` to `'not_an_accredited_provider'`
The main point in the video below is that the Accredited provider number is not there when we change the provider back to an Accredited provider.
[Screencast from 29-11-24 15:09:10.webm](https://github.com/user-attachments/assets/0fcfd11e-f4b2-4faa-a8f1-b4f47061c121)
Pick it apart and recommend changes

Clear the accredited_provider_number when removing provider accreditation

---

app/controllers/api/public/v1/courses_controller.rb
app/lib/required_qualifications_summary.rb
app/models/course.rb
app/serializers/api/public/v1/serializable_course.rb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/lib/required_qualifications_summary_spec.rb
spec/models/course_spec.rb

Counting the number of courses in a recruitment cycle is very expensive. We do this on every request to the courses endpoint.
The tests were run with Siege.
[Siege documentation](https://linux.die.net/man/1/siege) 
All tests were run against review apps. The review apps all had 1 replica with 512MiB memory.
```
inulty-dfe ~/Code/publish-teacher-training ( perf-api-providers) $ siege -c 10 -t 1m -if app/controllers/api/loadtest-urls-other-branch.txt
{       "transactions":                           91,
"availability":                       100.00,
"elapsed_time":                        59.50,
"data_transferred":                    19.95,
"response_time":                        5.97,
"transaction_rate":                     1.53,
"throughput":                           0.34,
"concurrency": …
```

Perf: Better response times from api/public/v1/courses

---

Gemfile.lock

This reverts commit 4a90fe8832492e85b0ef2406b9041a210446e9ab.

Revert "Bump mock_redis from 0.46.0 to 0.48.1"

---

.adr-dir
guides/adr/0012-formalize-accredited-provider-relationships.md
guides/adr/index.md

Proposal to address the technical debt around the self join association between Training Providers and Accredited Providers.
[Link to Visio document](https://educationgovuk.sharepoint.com/:u:/r/sites/TeacherServices/Shared%20Documents/Find%20and%20Apply%20Team/01.%20Publish/Publish%20user%20and%20provider%20relationships%20and%20permissions.vsdx?d=wbd2db8f09cf949289e89319cc11111dd&csf=1&web=1&e=Sd9OPn)
The proposed changes are outlined in the ADR.
- [Rendered ADR](https://github.com/DFE-Digital/publish-teacher-training/blob/create-conventional-accredited-provider-relationships/guides/adr/0012-formalize-accredited-provider-relationships.md)

Propose ADR to formalise the Accredited/Training provider relationships

---

Dockerfile

Our servers seem to be restarting and failing to deploy with this change.
- Revert commit 1e1a4879578a992aff41cb5ae3d5bd0f3ade6ea7.

Revert "Use JSON arguments for Dockerfile CMD"

---

app/controllers/find/v2/results_controller.rb
app/decorators/course_decorator.rb
app/models/course.rb
app/services/courses_query.rb
app/views/find/v2/results/index.html.erb
spec/decorators/course_decorator_spec.rb
spec/models/course_spec.rb
spec/services/courses_query_spec.rb

Start to populate the `/v2/results`
This PR adds all courses and paginate all courses. And add only the course title (provider name, course name and code) to the summary card (for now).
1. Access the review app /v2/results 
2. See all courses paginated
Next I will start to implement the filters, one by one and later add the no course scenario along side with the content of amount of courses listed.

V2 results - Add all courses, pagination and card title

---

app/forms/support/update_provider_form.rb
app/models/provider.rb
app/services/providers/create_fake_provider_service.rb
app/validators/accredited_provider_number_format_validator.rb
config/locales/en.yml
spec/components/providers/provider_list/view_spec.rb
spec/controllers/api/public/v1/providers_controller_spec.rb
spec/factories/courses.rb
spec/factories/providers.rb
spec/features/publish/courses/2024_itt_provider_market_reform/publishing_a_course_as_an_accredited_provider_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/validators/accredited_provider_number_format_validator_spec.rb

The presence of an `accredited_provider_number` is validated when a provider is being onboarded but not when an existing provider is promoted from a Lead partner to an Accredited Provider
- Accredited provider cannot be a school
- Accredited provider number must be present when saving an Accredited provider.
- University accredited providers number format starts with a 1
- SCITT accredited providers number format starts with a 5
- Add specific Accredited provider number error messages for SCITT and University
- Update `scitt` and `university` provider factory traits - they are not automatically accredited providers anymore
Any tips on the form would be useful. How do we want to use forms going forward?
[Screencast from 06-12-24 15:20:51.webm](https://github.com/user-attachments/assets/ba73 …

Validate `accredited_provider_number` on update too

---

config/environments/development.rb

Disable partially the semantic logger in development in order to be as close as we can from Rails default in development.
Following semantic logger documentation and comment on the issue: https://github.com/reidmorrison/rails_semantic_logger/issues/213
There is no way to disable entirely rails semantic logger without the `require: false` as the issue above described. I opt-in for the solution proposed in the issue above.
The image below are from the docs: https://logger.rocketjob.io/rails.html
1. The review app logs in JSON?
2. If you pull locally the logs are near to the Rails default as we can?

Partially disable semantic logger in development

---

app/components/notification_banner.rb
app/components/tab_navigation.html.erb
app/controllers/support/providers/copy_courses_controller.rb
app/forms/support/copy_courses_form.rb
app/javascript/publish/autocomplete/accredited_provider.js
app/services/courses/copy_to_provider_service.rb
app/views/support/courses/index.html.erb
app/views/support/providers/copy_courses/new.html.erb
app/views/support/providers/show.html.erb
config/locales/en.yml
config/routes/support.rb
spec/forms/support/copy_course_form_spec.rb
spec/requests/support/copy_courses_spec.rb
spec/services/courses/copy_to_provider_service_spec.rb
spec/system/support/providers/copy_courses_to_provider_spec.rb

Support are often asked to copy courses from one provider to another. This PR provides the ability for users to copy courses via the Support console.
1. Copy all courses
2. Copy schools and study sites or not
- What if the target provider already has copied the courses?
- The courses are not recopied
- What if the target provider already has copied the courses and deleted them?
- The courses are not recopied
- What if there are 1000 courses
- It will take a while to copy all the courses across.
- Could this be a background process?
- Lets see if that is necessary
[Screencast from 09-12-24 15:27:18.webm](https://github.com/user-attachments/assets/065d4116-2ce3-45f0-8a0c-def86ad6bae4)

Copy courses between providers in Support console

---

app/controllers/support/application_controller.rb
app/controllers/support/contact_details_controller.rb
app/controllers/support/courses_controller.rb
app/controllers/support/data_exports_controller.rb
app/controllers/support/providers/accredited_provider_search_controller.rb
app/controllers/support/providers/accredited_providers/checks_controller.rb
app/controllers/support/providers/accredited_providers_controller.rb
app/controllers/support/providers/copy_courses_controller.rb
app/controllers/support/providers/onboarding/checks_controller.rb
app/controllers/support/providers/onboarding/contacts_controller.rb
app/controllers/support/providers/onboardings_controller.rb
app/controllers/support/providers/schools/check_multiple_controller.rb
app/controllers/support/providers/schools/multiple_controller.rb
app/controllers/support/providers/schools/new_multiple_controller.rb
app/controllers/support/providers/schools_check_controller.rb
app/controllers/support/providers/users_check_controller.rb
app/controllers/support/providers/users_controller.rb
app/controllers/support/providers_controller.rb
app/controllers/support/recruitment_cycle_controller.rb
app/controllers/support/revert_withdrawal_controller.rb
app/controllers/support/schools_controller.rb
app/controllers/support/user_permissions_controller.rb
app/controllers/support/users/providers_controller.rb
app/controllers/support/users_controller.rb
app/helpers/layout_helper.rb

We want to conventionalise base class naming conventions. For example:
- Base models should be named `ApplicationRecord`.
- Base controllers should be named `ApplicationController`.
- Base mailers should be named `ApplicationMailer`.
Each namespace should have a base class implementation. For example:
- `Find::ApplicationController < ::ApplicationController` and `Support::ApplicationController < ::ApplicationController`.
- Rename `Support::SupportController` to `Support::ApplicationController`
-

Rename SupportController to Support::ApplicationController

---

app/controllers/find/v2/results_controller.rb
app/forms/search_courses_form.rb
app/services/courses_query.rb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/features/find/v2/results/search_results_enabled_spec.rb
spec/services/courses_query_spec.rb

This PR adds the "Qualification" and "Further education" filter to the new search results that we will replace the live one in the future.
In production if you go to the live page and select "Across England" and "Further education" the parameter will be "age_group: further_education" and if you apply the filter "Further education (PGCE or PGDE without QTS)" the parameter will be: "qualification[]: pgce_pgde".
I changed to just: further_education=true (I might change to level=further_education when primary and secondary are added).
2. Does each filter (qualifications and further education) work as expected?

Foundation for the pre filter work: add qualification filter and further education filter

---

app/controllers/find/v2/results_controller.rb
app/forms/search_courses_form.rb
app/services/courses_query.rb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/features/find/v2/results/search_results_enabled_spec.rb
spec/forms/search_courses_form_spec.rb
spec/services/courses_query_spec.rb

This PR adds the funding type filter on the v2 results page
For backwards compatibility the funding is string on the live site (v1 results page). This PR adds an array but also accept the funding as string for compatibility.
2. Does it work with all three checkboxes? Choosing one, two, three, zero?

Foundation for the pre filter work add Funding filter

---

Gemfile
Gemfile.lock

We have no need for this gem since moving onto Azure.
- Remove the `cloudfront-rails` gem.

Remove the cloudfront-rails gem

---

app/controllers/publish/courses_controller.rb

There is a performance issue for some providers which has many courses to display in the courses list page.
The line in the controller in the culprit:
```ruby
def provider
@provider ||= recruitment_cycle.providers
.includes(courses: %i[sites site_statuses enrichments provider
])
.find_by!(provider_code: params[:provider_code])
end
```
This is generating a rails default query where the main nested loop are being higher and making the query takes more than 500ms on average sometimes reaching more than x seconds (it varies).
Taking a look on the query that the includes generates:
```
EXPLAIN ANALYZE SELECT
"course_site".*
FROM
"course_site"
INNER JOIN
"site"
ON "site"."id" = "course_site"."site_id"
INNER JOIN
"course_site" AS "site_statuses"
ON "site_statuses"."site_id" = "site"."id"
WHERE …
```

Remove includes course sites on provider courses page

---

app/forms/publish/about_your_organisation_form.rb
spec/forms/publish/about_your_organisation_form_spec.rb

Currently, the `AboutYourOrganisationForm` has a lot of logic around accepting arguments relating to Accredited bodies. This appears to be functionality that may have been used in the past but is not longer relevant.
Delete code that serves no pupose anymore.
|What|Image|
|---|---|
|Show|![image](https://github.com/user-attachments/assets/ff6b85ac-72f6-443b-8f68-4d65b826d9e4)|
|Form (1)|![image](https://github.com/user-attachments/assets/475c575f-2758-40b4-9a95-b309239e4781)|
|Form (2)|![image](https://github.com/user-attachments/assets/6344d200-6a95-4afd-bcc6-ec227caa3743)|

Remove references to accredited provider in `AboutYourOrganisationForm`

---

config/settings.yml

This feature flag will be used to enable / disable routes and toggle the
return values of certain methods so we can merge the updated provider
partnerships code incrementally while maintaining the current
behaviour.
In test files we can have functional tests test the existing behaviour
and the new implementation by switching on the feature flag
for example:
allow(Setttings.features).to receive(:provider_partnerships).and_return(true)

Add `Settings.features.provider_partnerships` feature flag

---

app/controllers/find/v2/results_controller.rb
app/forms/search_courses_form.rb
app/services/courses_query.rb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/features/find/v2/results/search_results_enabled_spec.rb
spec/services/courses_query_spec.rb

Add secondary filter to the `/v2/results`.
I divided this work in three parts (and will be three PRs):
* Part 1: the filter working - This PR!
* Part 2: Move the /v2/results specs to system specs and divide the filter into different specs - future PR
* Part 3: the "search" JS component within the secondary filter - a future PR!
2. Check some secondary filters or all of them individually. Does it work?

PART 1 - Add secondary filter to the v2 results page 

---

app/controllers/find/v2/results_controller.rb
app/forms/search_courses_form.rb
app/services/courses_query.rb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/forms/search_courses_form_spec.rb
spec/services/courses_query_spec.rb
spec/system/find/v2/results/search_results_enabled_spec.rb

This PR changes the further education filter:
1. Use `level` as parameter (to map the data modelling)
2. Makes compatible with "old" parameters (the current live version that soon will be replaced):
- "age_group" parameter is used when user answer the second question and chooses "Further education"
- "qualification" as "pgce pgde" parameter is used when user answer the qualification "further education" filter 
Also changed the content of the filter as the trello card: 
1. Visit /v2/results page
2. Does the further education filter works?
3. Go to live site and answer the second question and go to results page. Copy the parameters and paste into `/v2/results?...." 
4. Does the further education filter works?
5. Go to live site and filter the qualification to further education. Copy the …

Change further education filter

---

app/forms/search_courses_form.rb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/system/find/v2/results/search_results_enabled_spec.rb

This PR adds the primary filter to the `/v2/results` page.
1. Visit /v2/results page
2. Does the primary filter work as expected?
3. Does also work with secondary filter?

Add primary subjects filter

---

Gemfile
Gemfile.lock

table_print and terminal-table are not used in the app
[Commit where they were added](https://github.com/DFE-Digital/publish-teacher-training/commit/6d73a4a04a32c3cb82a9e6a5d1c5ae5657dc6f3f)

table_print and terminal-table are not used in the app

---

app/lib/constraints/partnership_feature.rb
spec/lib/constraints/partnership_feature_spec.rb

Part of the work to move from `AccreditedProviderEnrichments` to `ProviderPartnership`
Toggling the provider_partnerships feature flag will be used to make
available sets of routes in the applicaiton
https://trello.com/c/NUdxv9XW/377-add-routing-constraint-to-enable-provider-partnerships-urls-based-on-feature-flag

Add routing constraint to switch routes on a feature flag

---

terraform/aks/.terraform.lock.hcl
terraform/aks/statuscake.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/find_production.tfvars.json
terraform/custom_domains/environment_domains/workspace_variables/publish_production.tfvars.json

Monitor apex domain certificates so they can be renewed before they expire
Monitor SSL certificate of:
- find-teacher-training-courses.service.gov.uk
- find-postgraduate-teacher-training.service.gov.uk
- publish-teacher-training-courses.service.gov.uk
Add 2 domain redirects to catch all potential web traffic:
- Redirect publish-teacher-training-courses.service.gov.uk to www.publish-teacher-training-courses.service.gov.uk
- Redirect www.find-teacher-training-courses.service.gov.uk to find-teacher-training-courses.service.gov.uk
- make staging deploy-plan (No change)
- make production deploy-plan CONFIRM_PRODUCTION=yes
- make find production domains-plan CONFIRM_PRODUCTION=yes
- make publish production domains-plan CONFIRM_PRODUCTION=yes
Run terraform for production domains

[2199] Monitor apex ssl certificates

---

Gemfile.lock

We need to run `bundle lock --add-platform x86_64-linux-musl` to keep the musl build of nokogiri in the Gemfile.lock file
https://nokogiri.org/tutorials/installing_nokogiri.html#supported-platforms
Permanently add `x86_64-linux-musl` platform to our Gemfile

Add musl to Gemfile.lock PLATFORMS

---

db/migrate/20250116123350_remove_access_requests_if_table_exists.rb
db/schema.rb

Their is an `access_request` table in the production database which is missing from other environments. It is unused. We can remove it.
- Add a migration to drop the table if it exists.
Pull down the backup and run this migration. Your schema should be unchanged.

Remove access_request table

---

db/data/20250114155946_update_ratifying_provider.rb
lib/update_ratifying_provider_for_course.rb
spec/lib/update_ratifying_provider_for_course_spec.rb

Support Request
Update the ratifying provider for all courses of a given set of training providers in the current recruitment cycle.
https://trello.com/c/wTPmCvLG/479-update-accrediting-provider-for-hubs

Change ratifying provider for courses

---

lib/update_ratifying_provider_for_course.rb
spec/lib/update_ratifying_provider_for_course_spec.rb

A data migration is failing in Sandbox environment.
This PR adds safe navigation to the code to prevent an exception being raised.
Add safe navigation to data migration to stop errors

Add safe navigation to data migration

---

app/components/phase_banner.rb
config/skylight.yml
terraform/aks/locals.tf

We can send our Skylight metrics for review apps out into separate environments. In the case that we want to understand the performance of a review app, we will be able to distinguish between each review app and its metrics.
- Send review app metrics to Skylight per PR number.
- See https://www.skylight.io/app/applications/2qpKL45hvoni/recent/5m/endpoints for example.

Split skylight metrics for review apps out per review app

---

app/components/courses/summary_card_component.html.erb
app/components/courses/summary_card_component.rb
app/controllers/find/v2/results_controller.rb
app/models/course.rb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/components/courses/summary_card_component_spec.rb
spec/models/course_spec.rb

This PR adds all the course summary content into the search result.
The goal was:
* Simplify the views and the component and the locales in comparison from the old search result (you can compare with `SearchResultComponent` if you want)
If you wanna see the details of each field please read the commit message.
* There are N+1 queries on this PR - this will be addressed in future PR.

Add course summary card to the new results page

---

.git-blame-ignore-revs

We have a handful of formatting-only commits that remove the git blame context from a line of code. This makes it less convenient to fetch the context around a change.
GitHub provides a way to ignore certain commits from git blame: https://docs.github.com/en/repositories/working-with-files/using-files/viewing-and-understanding-files#ignore-commits-in-the-blame-view
- Add fa9bb3bdd1f105043ccdad8cbde124c0fa776cbf to the `.git-blame-ignore-revs` file.
Visit the `Gemfile` file on [main](https://github.com/DFE-Digital/publish-teacher-training/blob/main/Gemfile) vs in [this branch](https://github.com/DFE-Digital/publish-teacher-training/blob/dd/add-git-blame-ignore-revs-file/Gemfile) in GitHub. The blame will differ.

Add single-quotes lint changes to git blame ignore file

---

app/controllers/find/errors_controller.rb

When renaming the Find layout in https://github.com/DFE-Digital/publish-teacher-training/pull/4831, a `find_layout` reference was missed.
- Rename remaining `find_layout` reference to `find`.

Set Find errors controller layout to 'find'

---

app/controllers/publish/errors_controller.rb

When merging the Publish layout into plain "application", https://github.com/DFE-Digital/publish-teacher-training/pull/4831, a "publish" layout reference was missed.
- Remove the explicit `layout 'publish'` call and fallback to the default `application` layout.

Unset Publish errors controller layout to default 'application'

---

app/assets/stylesheets/govuk_style_setup.scss

When re-organising the asset files, it seems the path` set in `govuk_style_setup.scss` are relative to the caller. This made all the font and image paths become prefixed with `/find` or `/publish`.
- Update `$govuk-fonts-path` and `$govuk-images-path` both to `"/"`;
Visit the review app. There should be no console errors.

Set $govuk-fonts-path and $govuk-images-path to '/'

---

docker-compose.yml
terraform/aks/databases.tf

Azure postgis version is 3.2.3 - let's represent the same version on CI and review apps.
Azure postgres is fixed
https://learn.microsoft.com/en-us/azure/postgresql/extensions/concepts-extensions-versions#postgis
although they do mention update via
https://learn.microsoft.com/en-us/azure/postgresql/extensions/how-to-allow-extensions?tabs=allow-extensions-portal%2Cload-libraries-portal#update-extensions
So it may not update more than 3.2.3 for pg 14, so fixing the version in CI and in review apps
1. Does it work on the review app? 
- Run in the review db: `SELECT postgis_full_version();` (e.g `ActiveRecord::Base.connection.execute("SELECT postgis_full_version();").values`) 
- It should return the 3.2.3
- run `SELECT *  FROM spatial_ref_sys LIMIT 10;`
- run `SELECT * FROM geometry_columns …

Represent the same postgis version as production

---

app/components/filters/provider_attributes/view.html.erb
app/components/paginated_filter.rb
app/controllers/support/providers_controller.rb
app/services/support/filter.rb
config/locales/en.yml
spec/system/support/remove_accredited_status_from_accredited_provider_spec.rb
spec/system/support/support_filter_providers_spec.rb

I noticed a bug I introduced when changing `Provider#accrediting_provider` to `Provider#accredited`
1. Editing Accredited status of a provider in support console works correctly now
2. Updated the param names and properties from `accrediting_provider` to `accredited` to match the model property in the filtering code
https://trello.com/c/7wmekQgP/399-bug-accredited-provider-update-and-filter-bug

Bug fix: Updating and filtering accredited providers in support console

---

spec/components/find/courses/entry_requirements_component/view_spec.rb

If the course is created with provider code I30 the test will fail
predicatably
Update flaky test
The alternative case is tested explicitly in the file.

Set course's provider explicitly in test

---

db/data/20250124164607_remove_accredited_provider_number.rb

No Lead Partner should have an accredited_provider_number value
We have updated the support interface now so that when we change an accredited provider to unaccredited then we remove the `accredited_provider_number`.
There are still some unaccredited providers with accredited provider numbers.
112 to be precise
Delete the `Provider#accredited_provider_number` from all unaccredited providers
https://trello.com/c/Rl1xNeFS/274-datamigration-remove-accredited-provider-number-from-all-non-accredited-providers

Add data migration to nullify unaccredited provider number

---

app/components/courses/summary_card_component.rb
app/controllers/find/v2/results_controller.rb
app/forms/courses/search_form.rb
app/services/courses/query.rb
spec/factories/locations.rb
spec/forms/courses/search_form_spec.rb
spec/rails_helper.rb
spec/services/courses/query_spec.rb
spec/support/matchers/match_collection.rb

For the new results page, we need to enhance the location search functionality:
Allow users to search for courses within a specific radius of a given location.
Sort the results by courses with the nearest available placements.
We are replacing the current search mechanism with PostGIS for geolocation searches, which offers improved performance and accuracy.
* Users can search for courses by location within a specified radius.
* If no radius is provided, a default radius is applied.
* Results are sorted by courses with the nearest placements.
* The implementation uses PostGIS for geolocation calculations.
* The site latitude and longitude geometry ST_MakePointM(float x, float y, float m) could be store in the Database but this will be done in a further iteration.
* This is only the …

Foundation work implement location search and radius filter

---

app/models/provider.rb
app/services/publish/accredited_provider_updater.rb
app/views/support/providers/_list.html.erb
config/locales/en.yml
spec/forms/accredited_provider_form_spec.rb
spec/models/course_spec.rb
spec/models/provider_spec.rb
spec/services/publish/accredited_provider_updater_spec.rb

We recently replaced the use of `accrediting_provider` with `accredited` on the Provider model.
Some of the code was not updated.
This PR finishes the migration by removing all references to the old column
Any remaining references to `accrediting_provider` should be relevant to the course only.
Change all places where `Provider#accrediting_provider` is used to determine if a provider is accredited to `Provider#accredited`
Has all references correctly been removed?
https://trello.com/c/VhkOfHZG/410-remove-all-remaining-references-to-provideraccreditingprovider

Remove all `Provider#accrediting_provider` code

---

app/controllers/publish/errors_controller.rb

We have a recurring error happening in some environments.
https://dfe-teacher-services.sentry.io/issues/6234856794
- Skip the `verify_authorized` after action callback in the `Publish::ErrorsController`.
Visit the following pages:
| Environment | URL                                                               |
| ----------- | ----------------------------------------------------------------- |
| QA          | https://qa.publish-teacher-training-courses.service.gov.uk/onetwo |
| Review      | https://publish-review-4881.test.teacherservices.cloud/onetwo     |

Skip verify_authorized for Publish::ErrorsController

---

app/views/support/courses/index.html.erb
app/views/support/providers/_navigation.html.erb
app/views/support/providers/accredited_partnerships/index.html.erb
app/views/support/providers/accredited_providers/index.html.erb
app/views/support/providers/show.html.erb
app/views/support/providers/users/index.html.erb
app/views/support/schools/index.html.erb

A lot of support currently requires us to visit the Provider pages from Publish directly. It's a hassle to navigate to a provider or course in Publish from Support.
- Add links to Publish from Support.
- Sign into Support.
- Find a provider.
- Click on the heading, it will take you to the provider on Publish.
- Sign into Support.
- Find a provider.
- View their courses.
- Click on "View on Publish", it will take you to the course on Publish.

Add shortcuts to Publish from Support

---

app/controllers/publish/courses/ratifying_provider_controller.rb
app/decorators/course_decorator.rb
app/helpers/view_helper.rb
app/models/concerns/publish/course_basic_detail_concern.rb
app/models/course.rb
app/serializers/api/public/v1/serializable_course.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/courses/index.html.erb
app/views/publish/courses/ratifying_provider/_provider_suggestion.html.erb
app/views/publish/courses/ratifying_provider/edit.html.erb
app/views/publish/courses/ratifying_provider/new.html.erb
app/views/publish/courses/ratifying_provider/show.html.erb
config/locales/en.yml
config/routes/publish.rb
spec/components/add_course_button_enrichments_preview.rb
spec/components/add_course_button_preview.rb
spec/features/publish/courses/add_ratifying_provider_when_publishing_a_course_spec.rb
spec/features/publish/courses/adding_a_ratifying_provider_to_an_unpublished_course_spec.rb
spec/features/publish/courses/new_accredited_provider_spec.rb
spec/features/publish/courses/new_ratifying_provider_spec.rb
spec/features/publish/courses/new_schools_enrichments_spec.rb
spec/features/support/view_components_enrichments_spec.rb
spec/helpers/view_helper_spec.rb
spec/models/course_spec.rb
spec/serializers/api/public/v1/serializable_course_spec.rb
spec/support/page_objects/publish/courses/new_accredited_provider.rb
spec/support/page_objects/publish/courses/new_ratifying_provider.rb
spec/support/page_objects/publish/courses/ratifying_providers.rb

The final part of the work to migrate Provider Relationships from `AccreditedProviderEnrichments` to `ProviderPartnerships`.
This work implements the ProviderPartnerships model into the course management area of the applicaiton.
When a Lead Partner wants to create a course they must assign a Ratifying provider. This provider is chosen from the list of Accredited partners they have established.
Now the provider will choose from the list of accredited partners in the `ProviderPartnership` system rather than the `AccreditedProviderEntrichment` association.
- Add RatifyingProvider routes, controller, views.
- These will be used when `Setting.features.provider_partnerships feature flag` is enabled.
- The named routes helpers and the URLs change from `accrediting` provider to `ratifying` …

Add provider partnerships to course ratification

---

app/serializers/api/public/v1/serializable_course.rb
spec/controllers/api/public/v1/courses_controller_spec.rb
spec/serializers/api/public/v1/serializable_course_spec.rb
swagger/public_v1/api_spec.json
swagger/public_v1/component_schemas/CourseAttributes.yml

[Trello card on the Apply / Manage board](https://trello.com/c/cgxezeG7)
We want to enable providers to add early deadlines for candidates who require visa sponsorship (on courses that sponsor visas).  The [outcome card](https://trello.com/c/AyrMu8s3) is also on the Apply / Manage board.
This is just an enabling task to allow work to move forward on the Apply side. There are future tickets written / planned for the rest of the work on the publish side (@dp-daly and @dcyoung-dev are working on this together, I believe)
- You can see the new field in the API response in the review app https://publish-review-4887.test.teacherservices.cloud/api/public/v1/recruitment_cycles/2025/courses
- have a look at the [revised api documentation here](https://publish-review-4887.test.teacherservices.cloud/ …

[610] Add visa sponsorship application deadline attribute to course object

---

terraform/aks/.terraform.lock.hcl
terraform/aks/storage.tf
terraform/aks/variables.tf
terraform/aks/workspace_variables/production.tfvars.json

There is a requirement to create a storage account to store sanitised backups
https://trello.com/c/FWUebqgi
Creates a storage account
Check the azure storage account in azure console

Add storage account for sanitised backups

---

db/data/20250124165440_migrate_provider_partnerships_from_enrichments.rb

Now we have the `provider_partnerships` table we need a data migration to backfill the `provider_partnerships` table with the existing `AccreditingProviderEnrichment`s
There are 7237 provider records with enrichments
```ruby
Provider.where.not(accrediting_provider_enrichments: nil).count
```
2705 of them are empty.
```ruby
Provider.where.not(accrediting_provider_enrichments: nil).count { |p| p.accrediting_provider_enrichments.empty? }
=> 2705
```
84 enrichments either don't have a provider code at all or the provider doesn't exist in the database.
```ruby
Provider.where.not(accrediting_provider_enrichments: nil).find_each do |provider|
provider.accrediting_provider_enrichments.each do |enrichment|
no_provider_exists += 1 unless Provider.exists?(recruitment_cycle:provider.recruitment_cycle, …
```

Add Data migration to create ProviderPartnerships from enrichments

---

app/controllers/find/search/locations_controller.rb
app/forms/find/location_filter_form.rb
spec/features/find/search/location_options_spec.rb
spec/fixtures/files/google/geocode/cornwall.json
spec/fixtures/files/google/geocode/london.json
spec/forms/find/location_filter_form_spec.rb
spec/support/geocoder_helper.rb

When people search for courses near Cornwall, we give them a 10 mile radius by default.
When people search Cornwall, they expect to see all the courses run in Cornwall, not just ones within 10 miles of the "centre" of Cornwall.
If a user searches for a large area like Cornwall, our Geocoding API identifies Cornwall as an `administrative_area_level_2`. Using this information, we can change the default radius of the search from the default 10 mile radius to 50 mile radius.
This will include almost all courses run in Cornwall.
Some places are not `administrative_area_level_2`, but instead are `colloquial_areas`
We've identified these `colloquial_areas`
- Yorkshire
- Buckinghamshire
There are likely more. We can include these location types in a further change if we decide it's a good idea …

Find results on location on large areas

---

app/controllers/publish/providers/accredited_partnerships_controller.rb
spec/features/publish/accredited_partnership_spec.rb

The way we use the ProviderPartnershipForm and redirect from the
accredited provider search is haphazard. We need to maintain state in
the form, but the form is designed to update a model.
This change gets the chosen accredited provider id from the params or
form. It will always be in one.
Added a spec to test this scenario specifically.
[Screencast from 11-02-25 17:15:38.webm](https://github.com/user-attachments/assets/0a6dc43b-3316-4c66-8f3d-467163b50b64)
This code is far from ideal. Any immediate suggestions on how to improve it are welcome.
https://trello.com/c/9J5caX5Q/457-bug-fix-allow-user-to-change-accredited-partnership-description-before-save

Bug fix: can change accredited provider description before save

---

spec/factories/courses.rb
spec/features/publish/courses/copy_from_list_spec.rb
spec/models/course/publishable_spec.rb

Some tests are failing when the Provider partnership Setting is enabled.
Make changes to the test suite so that all tests are passing when provider partnerships is enabled
All changes are affecting the test suite, and specifically when the `Settings.features.provider_partnerships` setting is enabled.
These tests all pass when run in the settings matrix defined in [this PR](https://github.com/DFE-Digital/publish-teacher-training/pull/4915)

Get provider partnership tests passing

---

.github/workflows/build-and-deploy.yml
spec/rails_helper.rb

When we build features behind feature flags, we often want to know that existing tests pass when the feature flag is enabled and disabled.
Add a way to override Settings in CI and run the suite with settings enabled and disabled
There's probably a better way to work with the workflows. Any improvements are welcomed!

Enable CI Settings matrix test runs

---

app/assets/stylesheets/find/components/_accordion.scss
app/views/find/v2/results/courses_guidance/_show.html.erb
app/views/find/v2/results/index.html.erb
config/locales/find.yml

Add a new banner with GiT links in the results page.
Visit `/v2/results`
1. Are the links working?
2. Are the links being tracked?
3. Is the banner responsive?

Improve results update get into teaching banner on the search results page

---

app/views/find/courses/show.html.erb
spec/system/find/v2/results/view_course_spec.rb

This PR fixes the bug on the pre-filtering work that you can't return to the search after you view a course.
Steps to replicate (on main branch)
2. Apply any filters
3. Click on any course.
4. Then click “Back to results”.
The search on step 2 should be there.
The reason the bug exists si that back to results relies on the params in the url and this solution is flakey.
**Solution:** I used the referrer if is a permitted referrer.
**Solution:** I used the referrer if is a permitted referrer.
1. Is it secure to use the permitted referrer instead relying on the parameters?

Fix issue where you search, click on a course and return to search

---

.github/workflows/postgres-ptr.yml
.github/workflows/postgres-restore.yml

add restore workflows required for disaster recovery 
add 2 new workflows from template to do database restore and restore to point in time for a selected env.
Check code
I'll test the workflows after merge.
[Publish: Plan for DR test - Feb 2025](https://trello.com/c/RYfgWcjk/2196-publish-plan-for-dr-test-feb-2025)

Workflows for Disaster Recovery

---

app/controllers/publish/courses/student_visa_sponsorship_controller.rb
app/services/courses/creation_service.rb
app/views/publish/courses/student_visa_sponsorship/new.html.erb
spec/forms/publish/course_funding_form_spec.rb
spec/services/courses/creation_service_spec.rb

It is possible to create a course that "can sponsor" Student visas and Skilled worker visas.
If the user uses the Add course flow and chooses Fee funding and chooses to sponsor student visas, when they reach the confirmation page they can change the funding type to apprenticeship or salary and add Skilled working visa sponsorship.
When that course is created it is create with both sponsorship types.
We will force the Skilled Worker sponsorship to `false` if the funding is `fee` or force the Student sponsorship to `false` if the funding type is `salary` of `apprenticeship`.
https://trello.com/c/9yxsiYG0/383-fix-visa-sponsorship-data-in-the-database

Prevent both types of visa sponsorship during course creation

---

app/assets/stylesheets/find/components/_filter-search.scss
app/views/find/v2/results/index.html.erb

So the users can see is a scrollable section
See trello card for more info:
https://trello.com/c/52wJBhfW/428-bug-primary-and-secondary-filters-have-incorrect-height
BEFORE:
AFTER:
1. It it right height on the web?
2. And on mobile?

The scrollable filter items needs to be partially hidden

---

db/data/20250218095818_correct_course_visa_data.rb

Salary courses shouldn't be sponsoring student visa.
Fee courses shouldn't sponsoring worker visa.
Apprenticeship courses shouldn't be sponsoring student visa.
Add a DataMigration to corrrect data in the database.
https://trello.com/c/9yxsiYG0/383-fix-visa-sponsorship-data-in-the-database

DataMigration correct visa sponsorship data

---

app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/accredited_provider/edit.html.erb
app/views/publish/courses/accredited_provider/new.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/courses/ratifying_provider/edit.html.erb
app/views/publish/courses/ratifying_provider/new.html.erb
spec/features/publish/courses/editing_course_ratifying_provider_spec.rb
spec/support/page_objects/find/course_show.rb
spec/support/page_objects/publish/course_confirmation.rb
spec/support/page_objects/publish/course_preview.rb
spec/support/page_objects/publish/courses/details.rb
spec/support/page_objects/publish/provider_courses_details.rb

The correct link for editing the ratifying provider of a course was not applied when provider partnerships is enabled
Set the correct URL for `Change ratifying provider`
[Screencast from 13-02-25 16:07:35.webm](https://github.com/user-attachments/assets/dcb69a87-b7ee-4e28-952d-e3b6c10fd0a8)
https://trello.com/c/h1iAfSzg/465-correct-url-for-changing-ratifying-provider-of-a-course

Correct Course edit "Change ratifying provider" link for provider partnerships

---

app/services/courses/nearest_school_query.rb
app/services/courses/query.rb
app/services/courses/school_distances_query.rb

This update wraps ST_MakePoint calls with
ST_SetSRID(..., 4326) across all spatial queries.
SRID 4326 corresponds to the WGS 84 coordinate system, ensuring that latitude/longitude values are interpreted correctly for accurate distance computations.
You can learn more about SRID 4326 and the WGS 84 coordinate system here:
- [PostGIS Documentation – ST_SetSRID](https://postgis.net/docs/ST_SetSRID.html)
- [PostGIS Documentation – Spatial Reference System Identifiers (SRID)](https://postgis.net/docs/using_postgis_dbmanagement.html#spatial_ref_sys)
- [EPSG:4326 on EPSG.io](https://epsg.io/4326) (Provides a visual representation and detailed metadata)
- [Wikipedia – World Geodetic System (WGS 84)](https://en.wikipedia.org/wiki/World_Geodetic_System)
1. Test the location search (for …

Set SRID 4326 for spatial queries in course location calculations

---

app/lib/feature_flags.rb
app/lib/find_v1_results_constraint.rb
app/lib/find_v2_results_constraint.rb
app/views/find/courses/show.html.erb
app/views/find/search/locations/_form.html.erb
config/settings.yml
config/settings/qa.yml
config/settings/review.yml
spec/system/find/v2/quick_links/primary_subjects_spec.rb
spec/system/find/v2/quick_links/secondary_subjects_spec.rb
spec/system/find/v2/results/search_results_enabled_spec.rb
spec/system/find/v2/results/search_results_no_results_spec.rb
spec/system/find/v2/results/search_results_ordering_spec.rb
spec/system/find/v2/results/search_results_subject_and_location_spec.rb
spec/system/find/v2/results/search_results_tracking_spec.rb
spec/system/find/v2/results/view_course_spec.rb

It is better we enable or disable the prefiltering work through the browser rather than yaml file that requires a deployment.
Visit `/feature-flags`.
1. Visit `/feature-flags`.
2. Activate the  pre-filtering.
3. Visit '/'
4. Does the prefiltering work is working?
5. Deactivate the prefiltering feature flag
6. Does the old search is working?

Enable pre filtering feature flag through /feature-flags

---

app/controllers/find/v2/results_controller.rb
app/forms/courses/search_form.rb
app/services/courses/query.rb
app/views/find/v2/results/filters/_all.html.erb
app/views/find/v2/results/index.html.erb
config/locales/find.yml
spec/forms/courses/search_form_spec.rb
spec/services/courses/query_spec.rb
spec/system/find/v2/results/search_results_enabled_spec.rb

Add a new filter (same as the live site).
The filter is only visible when user is searching for physics.
1. Search for physics
2. Does the new filter appears?
3. Check the new filter.
4. Does the Engineers teach Physics course appear?
5. If you uncheck Physics. 
6. Does the filter still appear?

Add Engineers teach physics filter

---

Procfile.dev

bin/dev that runs the Procfile.dev doesn't reload publish javascript bundle in dev because the package.json script calls two commands joined by && and only watches the last one run (find)
The previous command only watched the last command in the package
script (find)
yarn run build:js:publish && yarn run build:js:find
We need to watch the builds separately to have them both reload

Watch find and publish javascript in Procfile.dev

---

app/components/find/courses/training_locations/view.html.erb
app/decorators/site_decorator.rb
app/views/shared/courses/_placements.html.erb
spec/components/find/courses/training_locations/view_spec.rb
spec/features/find/course/viewing_a_course_spec.rb
spec/models/provider_spec.rb

We're getting flaky tests because the address of a Study site is having single quotes converted to ascii left quotes and our tests don't account for this.
I think it's better to convert the content for smart quotes in the decorator. We can assert the content rendered more easily that way
"smart quotify" site addres and name in the SiteDecorator

Smart quote site name and address in SiteDecorator

---

spec/services/authentication_service_spec.rb

Misuse of Timecop.freeze leads to flaky tests.
Call Timecop.freeze inside the example.

Timecop.freeze only works reliably inside the example

---

app/controllers/find/v2/results_controller.rb
app/helpers/find/view_helper.rb
app/views/find/courses/accrediting_providers/show.html.erb
app/views/find/courses/providers/show.html.erb
app/views/find/courses/show.html.erb
app/views/find/placements/index.html.erb
spec/features/find/course/viewing_a_course_spec.rb
spec/features/find/result_page_filters/back_to_results_spec.rb
spec/system/find/v2/results/view_course_spec.rb

There is a bug in the back link on the Course show page in Find.
Normally the user arrives at the course show page via a link on the results page. If this was always the case, we could use the request referer to generate the link back to the exact results from which the user came.
However, the user may click the provider information link on the course page and then click the back button to arrive back on the course show page. At this point we have lost the original referer.
Save the fullpath of the find search results everytime the user makes a search. Keeping this in the session means it's always available to us to generate a back link on the course show page.
https://github.com/user-attachments/assets/c1708f78-4310-4a09-af32-a59ce7a6bbc1 …

Fix backlinks on course show page in Find

---

app/components/courses/summary_card_component.rb
spec/components/courses/summary_card_component_spec.rb

Showing decimal-precision distance of potential placements looks to show certainty of where a trainee could be placed. To put reduce the emphasis on distance, we want to round up the miles to the nearest whole number.
- Round up distances in the results summary cards.
- Search a location, you should only see whole numbers in the returned results distances.

Round up school placement distances in results summary cards

---

app/javascript/find/controllers/provider_autocomplete_controller.js

when a user selects a value in the dfe-autocomplete component the
underslying select tag has the value selected. When the text is
removed from the input, the underlying select tag is not reset.
We add an event listener to the dfe-autocomplete text input on 'input'
event and reset the select tag value to empty string (falsey).
Ideally this should be handled by the library
The solution is copied from the subject autocomplete component. Thanks to @tomas-stefano for pointing that out
https://github.com/user-attachments/assets/18663eaf-ddfb-4b79-ac6f-d818c34f36a9
https://trello.com/c/i421ZwzJ/485-bug-training-provider-search-persists-after-removal

Clear the dfe-autocomplete select value on input

---

app/views/find/v2/results/index.html.erb

When a user filters results and there are none left, the sort and filter buttons disappear. We have no need to change the sort order of 0 results, but we may want to change filters to get some results.
- Add the filter button to the no results condition
- Try searching for something with no results, e.g. Ancient Greek.
- You should see the filter button.

Show filter button when there are no results

---

app/forms/courses/search_form.rb
spec/forms/courses/search_form_spec.rb

When a user searches for Cornwall, we want to widen the default radius
from 10 to 50 miles, otherwise many training locations in Cornwall are
not returned in the search results
We identify a large area by the presence of
"administrative_area_level_2" in the types property returned by Google
Geocoder API:
```
"types": [
"administrative_area_level_2",
"political"
]
```
If a course search has been made relative to a location, if the location is a large area - according to Google - we increase the search radius to 50 miles from the default 10 miles. If an explicit radius is provided, that radius is used to filter the results.
https://github.com/user-attachments/assets/a822d676-b53e-4c92-bba5-49ed47dc9fd1
https://trello.com/c/huzf9Dlw/484-bug-searching-for-cornwall-the-default-radius-is-10miles …

Set search radius of 50 on large geocoded areas

---

terraform/aks/workspace_variables/production.tfvars.json

Next week we are releasing pre-filtering work and we are slightly increasing the number of pods.
The new /results page on Find needs to hit Google API for the location searches on the first time only, then it caches for 30 days. This is IO bound but with 5 concurrency as limitation, a low risk but better to increase slightly for the first week and decrease if needed after.
Increasing the number of pods slightly just as manner of cautious while we monitor the DB CPU and application performance next week.

Increase the number of pods

---

app/controllers/find/v2/results_controller.rb
app/forms/courses/search_form.rb
spec/forms/courses/search_form_spec.rb
spec/system/find/v2/results/search_results_subject_and_location_spec.rb

After went through a CSV from Logit to get all parameters from the prod requests I saw some bugs around backwards compatibility:
* qualification is now qualifications
* study_type is now study_types
* lq is now location
Also there are values conversion for more meaninful values
1. Visit the live site and go to the results page
2. Check all filters
3. Copy and paste the url (without the domain) to the review app and see the filters applied.
4. Do the same for search by provider
5. Do the same for search by location

Make sure all old parameters work with the prefiltering work

---

app/views/find/v2/results/index.html.erb
spec/system/find/v2/results/search_results_tracking_spec.rb
spec/system/find/v2/results/view_course_spec.rb

When I search for without a location, the sort dropdown appear correctly. However it does not have a label to indicate how the list of sorted on default load of the page.
Remove the include blank option on ordering.
1. Visit /results
2. Change options around sorting.

Remove include blank from sorting results

---

app/controllers/find/v2/primary_subjects_controller.rb
app/controllers/find/v2/secondary_subjects_controller.rb
app/views/find/search/locations/_form.html.erb
spec/system/find/v2/quick_links/primary_subjects_spec.rb
spec/system/find/v2/quick_links/secondary_subjects_spec.rb
spec/system/find/v2/results/search_results_enabled_spec.rb
spec/system/find/v2/results/search_results_subject_and_location_spec.rb
spec/system/find/v2/results/search_results_tracking_spec.rb

Same as the live site, the applications open filter should be on by default.
1. Click in all homepage links (include the main search).
2. Does the applications open filter is on by default?

Show only open courses by default on Find searches

---

lib/tasks/populate_subject_groups.rake

When viewing the list of secondary subjects, "Physical education with an EBacc subject" is missing from the "Health and physical education" subject group.
- Add "Physical education with an EBacc subject" to the populate subject groups rake task.
- Try running `rails create_and_populate_subject_groups` locally.
- The "Physical education with an EBacc subject" subject should now be present.

Add PE with an EBacc subject to subject group

---

app/views/find/search/locations/_form.html.erb
spec/system/find/v2/results/search_results_subject_and_location_spec.rb

Add provider search to the homepage.
1. Search by a provider on the homepage?
2. Does it filter on the results page?
3. Does the provider field is open on the results page?
4. Does it work on mobile?

Add provider search into the homepage

---

app/components/courses/summary_card_component.rb
app/components/find/courses/summary_component/view.html.erb
app/components/find/courses/summary_component/view.rb
app/decorators/course_decorator.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
config/locales/en.yml
config/locales/find.yml
spec/components/find/courses/sumary_component/view_spec.rb
spec/features/find/course/viewing_a_course_spec.rb
spec/features/publish/courses/new_tda_course_enrichments_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/viewing_a_course_details_spec.rb
spec/features/publish/viewing_a_course_preview_spec.rb

The salary details of a course in the course details page currently has 1) Incorrect grammar (missing period) and 2) Mentions there are no fees for Salaried courses, which can be incorrect.
- Change the course details page salary information to match the v2 results page.
- Search for salary, fee, and, apprenticeship courses.
- Check the inner page details match the results page details - specifically the salary or fee part.
- https://trello.com/c/2mecaJDh/480-grammar-on-course-fee-content-for-salaried-apprenticeship-bug-party-1-2025-content-feedback

Update salary details on course details page to match results page

---

app/services/courses/query.rb
spec/services/courses/query_spec.rb

Users bookmarked bad formatted URLs from the old live site.
With the prefiltering this won't happen anymore but if the user bookmarked their searches we need to make sure we don't break the prefiltering results.
Default radius if radius can't be parsed.
1. Attempt to visit a bad formatted radius with degrees on it `radius=10ºdegree_required=show_all_courses` 
2. Radius should use the default

Default radius if radius parameter can not be parsed

---

db/data/20250303121528_backfill_provider_partnerships.rb

A training provider must be in a partnership in order for their
coursees to be ratified by an accredited partner.
There are some training providers whose courses are ratified by
accredited providers but there does not exist a partnership between
the providers.
This data migration will create the partnerships where they are
required.
All training providers with published courses that are ratified by accredited providers have accredited partnerships created.
These partnerships are created in AccreditedProviderEnrichments, and they will be created as ProviderPartnerships with a datamigration before launch.
The enrichments limit the number of words to 100. This migration takes as much of the accredited providers `#train_with_us` attribute an populates the partnership description with it. …

Backfill the provider partnerships for ratified courses

---

app/services/find/analytics/search_results_event.rb
spec/services/find/analytics/search_results_event_spec.rb
spec/system/find/v2/results/search_results_tracking_spec.rb

Both Find and Publish events are sent to the events_publish table. The namespace field allows us to split out the two services when creating downstream tables in Dataform e.g. find_searches, course_details_publish and find_sessions_extended. E.g: namespace = ‘find’ or namespace = ‘publish’.
Some of the events in Find are currently sending through a null namespace value, in particular the search_results events.
1. Does it includes the find namespace in the events hash to DfE analytics?

Add FInd namespace to search results event

---

db/data/20250303121528_backfill_provider_partnerships.rb

In sandbox, accredited provider are not always being found in the current cycle for the provider relationships data migration.
- Skip associating provider relationships when the accredited provider is not found in the current cycle.
- Should we take an alternative route to addressing this?
- Do we need to clean up the sandbox data?

Skip provider relationship association if accredited provider is not found

---

app/controllers/support/providers/copy_courses_controller.rb
spec/requests/support/copy_courses_spec.rb

Inconsistent ordering of course codes in the Copy courses feature is leading to flakey tests.
Sort the codes we display in the UI to make sure the test subjects are consistent

Sort courses copied codes to consistency and stability

---

terraform/aks/workspace_variables/production.tfvars.json

The graphs are almost unchanged so we can safely return to 4 pods.
Nonetheles it is always good to be cautious in a launch of a redesign of the whole site and its search mechanisms. 
1. See Azure DB CPU percentage and mem used
2. See Redis cache size
3. See Grafana metrics
4. Are we good to return to 4 pods?

Return the number of pods pre filtering launch

---

.rubocop.yml

rubocop-rspec extension supports plugin, specify `plugins:
rubocop-rspec` instead of `require: rubocop-rspec` in
/.../publish-teacher-training/.rubocop.yml.
For more information, see
https://docs.rubocop.org/rubocop/plugin_migration_guide.html.
There are PRs on rubocop-capybara and rubycop-factory_bot to migrate those projects to the plugin system but they have not been released yet

rubocop-rails and rspec should use plugin format

---

.github/workflows/build-nocache.yml

Add input for the SNYK scan level in the build-no-cache workflow, so the default can be changed on manual run.
Add level input to the workflow
see https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13783834957

Add snyk scan level input for build-no-cache

---

app/views/find/placements/index.html.erb
app/views/shared/courses/_placements.html.erb
config/locales/en.yml

We continue to receive feedback from providers that the new changes to how we communicate location have resulted in confusion or inaccuracy.
One thing that needs to be improved is the content on the school placements page, to make it clearer that the schools have been attached to the course and not the provider.

change title on school placements page

---

.github/workflows/build-and-deploy.yml
Makefile
bin/domains_healthcheck.sh
terraform/custom_domains/environment_domains/output.tf

Implement cicd for domains infrastructure
Add steps to build-and-deploy workflow
Add terraform output for environment urls, required for environment healthchecks
Changes to Makefile
script domains-hc added as publish has 2 separate terraform state files (find & publish).
- raised backlog ticket to investigate merging into one
https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13807385592
retest after updates
https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13833214381
make domains-infra-plan
make qa|staging|sandbox|production domains-plan

Implement cicd for domains infrastructure

---

spec/models/course_spec.rb

The `course_spec.rb` needs to be better arranged. There is a `describe "scopes"` block but many of the tests for scopes are not in this block and are mislabled.
Rearrange Course unit tests 
- Move all the tests in `context 'ordering'` into `describe 'scopes'`
- Move `#modern_language_subjects` test into 'associations' block
- Move `.changed_since` scope into `scopes` block
- Move `.by_name_*` scope tests into `scopes` block

Arrange course tests better

---

app/assets/stylesheets/govuk_style_setup.scss

The `govuk-frontend` library [introduced a new type scale](https://design-system.service.gov.uk/styles/type-scale/#:~:text=February%202024%3A%20GOV.UK%20Frontend,view%20the%20old%20type%20scale.) that increases the mobile text font sizes. It is currently behind a feature flag, but we should take advantage of the upcoming standard.
- Set the `$govuk-new-typography-scale` variable to `true`.
- View the service on mobile, this is where the majority of changes should be.
- Compare it with production on mobile.
- View the service on desktop, there should be no changes between the changes on this PR and production.

Use the new govuk typography scale

---

app/services/subjects_cache.rb
spec/services/subjects_cache_spec.rb

Modern languages is a "virtual" subject on our data that represents more like a subject group rather than one specific subject.
So removing from the autocomplete for now.
This changes the cache so we could:
1. Wait for the cache to expiry
2. Run `Rails.cache.delete('subjects:all')` to refresh the cache
1. Modern languages should not appear in the autocomplete when searching for a subject.
- Visit review app
- Search "Mode" on Subject. 
- Only "Modern languages (other)" should appear.
- Visit the results page
-  Search "Mode" on Subject. 
- Only "Modern languages (other)" should appear.

Do not show modern languages subject on autocomplete

---

Procfile.dev

without splitting, the first defined yarn command does not get watched
The publish scss files are not auto loaded if this is the yarn command run in the Procfile
```json
"build:css": "yarn run build:css:publish && yarn run build:css:find",
```
Split the Procfile "build:css" between Publish and Find

Split SCSS build watch into find and publish processes

---

Gemfile
Gemfile.lock
spec/controllers/find/courses_controller_spec.rb
spec/controllers/find/placements_controller_spec.rb
spec/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller_spec.rb
spec/controllers/publish/courses/outcome_controller_spec.rb
spec/controllers/sign_in_controller_spec.rb
spec/requests/support/copy_courses_spec.rb

We want to reduce the dependencies we use and need to maintain.
- Remove usage of `assigns` and access the controller's instance variables directly.
- Tests should pass.

Remove the 'rails-controller-testing' gem

---

app/components/find/courses/apply_component/view.html.erb
app/views/find/courses/_course_closed.html.erb
config/locales/en/components/find/courses/apply_component.yml
config/locales/en/components/find/courses/course_closed.yml
spec/components/find/courses/apply_component/view_spec.rb

TDA providers want to publish courses that are searchable on Find, but that cannot be applied to. They want to gauge interest in candidate demand without having to deal with applications.
As a result, they want the content returned for these courses, modified, to include a recommendation for candidates to contact the provider off-service via email.

changed content from courses are currently closed

---

app/components/accredited_provider_component.html.erb
app/controllers/support/providers/accredited_partnerships_controller.rb
app/views/support/providers/accredited_partnerships/edit.html.erb
spec/features/support/providers/accredited_partnerships_spec.rb

When submitting an invalid description, the user raises a 500 error.
This was due to a misplaced identifier that serves no purpose.
- Remove identifier.
- Add spec for invalid description case.
- Add missing `govuk_error_summary`
https://trello.com/c/HBdXhS9B/587-changing-description-of-accredited-partnership-raises-error

Fix server error submit blank description change

---

config/settings.yml

Enable the Provider Partnerships feature in production.
This feature upgrades the associations between Training providers and accredited Providers in our system.
Before this change, An accredited provider partnership existed on a column called `accrediting_provider_enrichments` on the Training provider. Now there is a join table called `provider_partnerships` that maintains the relationships in a normalised structure.
Enable a feature flag
https://trello.com/c/5vwjxjUn/402-enable-provider-partnerships-feature-flag-in-production

Enable provider partnerships

---

config/locales/en.yml
spec/components/find/courses/about_schools_component/view_spec.rb
spec/components/shared/courses/school_placements_advice/view_spec.rb
spec/features/publish/courses/editing_course_school_placements_spec.rb

Providers sometimes want candidates to secure their own employing school before they apply. We need to reflect this in the Where you’ll train information on salaried course pages.
Changing content on How school placements work content to reflect the need for candidates to secure their own placements.

Change content on how school placements work salaried

---

app/helpers/breadcrumb_helper.rb
app/views/publish/recruitment_cycles/_courses_accredited_provider.html.erb

During the move from provider enrichments to partnerships, some
templates didn't have feature flags wrapping the enrichments. Now
partnerships is released we'll just replace enrichments with
partnerships.
Replace code that depends on accrediting provider enrichments to instead depend on provider partnerships.
No feature flag added because Provider Partnerships is live
Any where else that needs updating?

Replace enrichments with partnerships where they were missed

---

app/javascript/publish/autocomplete/accredited_provider.js
app/views/publish/providers/accredited_provider_search/new.html.erb
app/views/support/providers/accredited_provider_search/new.html.erb

The accredited provider search api requires the recruitment cycle. We
now get the appropriate recruitment cycle year from the window.location (the url)
Get the required recruitment cycle year from the url to search the accredited providers
https://publish-review-5078.test.teacherservices.cloud/support/2025/providers/20584/accredited-providers/search
Is there a better way to get the recruitment cycle year?
Is the implementation sound?
https://trello.com/c/mvWmywc7/588-autocomplete-is-not-working-for-provider-search

Fix support accredited provider autocomplete

---

app/controllers/find/results_controller.rb
spec/requests/find/results_spec.rb

Some requests are returning 500.because requests are adding custom value to the page parameter.O
e.g /results?page=something
This PR handle this parameter by fallback to first page if something is wrong with params[:page]
1. Visit `/results?page=something`
2. Does it fallback to the first page?
3. Apply filters and then change the page parameter again
4. Does it fallback to the first page?

Fallback to page 1 if page parameter can not be parsed

---

app/views/find/results/filters/_all.html.erb

Moved the further education as the last filter on the search results
1. Visit /results page
2. See further education filter (desktop, mobile)
3. It should be the last filter

Move further education filter to the bottom

---

.dockerignore
bin/restore-backup
guides/setup-development.md

It's good to test locally with up to date sanitized backup from prod. It's a bit annoying to have to download in the browser.
This script downloads the sanitzed backup, drops and recreates the database and seeds the local development database with the sanitized backup.
Add a convenience script to reload local db with sanitized backup.
A similar script already exists, I discovered after writing this one.
https://github.com/DFE-Digital/publish-teacher-training/blob/main/bin/download-nightly-backup
I don't think we need all those environment variables set. But lets test.

Add script to download DB backup and restore to development

---

app/lib/google_old_places_api/client.rb
app/services/geolocation/coordinates_query.rb
app/services/geolocation/suggestions.rb
guides/geolocation.md

Add a markdown doc describing what Geolocation/Geocoding we do and where to find it.
Why is `Query` in`CoordinatesQuery`, and not `Suggestions`
https://github.com/DFE-Digital/publish-teacher-training/blob/8f50906ed7afadd4fbb057afc551745a49cc9848/guides/geolocation.md

Add some docs around Geolocation in the service

---

app/models/course.rb
spec/models/course_spec.rb
spec/serializers/api/public/v1/serializable_course_spec.rb

Previously we would show the description that the training provider
entered on the partnership but this is inconsistent.
|Course page|Course ratifying provider page|
|---|---|
|![image](https://github.com/user-attachments/assets/c9522e37-721e-41f4-9668-bba8e8169e1f)|![image](https://github.com/user-attachments/assets/5d21710f-74e9-4a73-b47c-42dcf45f9c7b)|
https://trello.com/c/ahJv8TTh/599-display-accredited-providers-about-us-content-in-the-courses-about-accredited-provider-page

Show ratifying providers' train_with_us for their description on course

---

app/components/find/courses/apply_component/view.html.erb
app/components/find/courses/apply_component/view.rb
config/locales/en/components/find/courses/apply_component.yml
spec/components/find/courses/apply_component/view_spec.rb

We have added the the visa sponsorship deadlines to the create flow and have a PR out for the edit flow. This PR show the deadline in find. 
[Trello card](https://trello.com/c/eXqdI8cu)
| Before | After |
| ------ | ------ | 
| <img width="732" alt="image" src="https://github.com/user-attachments/assets/08674e35-6a21-4c6e-9fe3-e142a8492ed9" /> | <img width="729" alt="image" src="https://github.com/user-attachments/assets/84e6fd92-6b02-4920-a32f-f7f24dda0509" /> |
- Create a publish a course with a deadline for visa sponsorship.
- Look at that course on find. You should the date under the button.

[340] Add visa sponsorship deadline to find

---

.tool-versions

Azure seem to remove their kubelogin versions once a new version is released. This is annoying when you go to use kubelogin and it won't install.

Set azure-kubelogin version to latest

---

app/forms/support/provider_form.rb
app/models/provider.rb
config/locales/en.yml
spec/forms/support/provider_form_spec.rb
spec/models/provider_spec.rb
spec/services/find/analytics/search_results_event_spec.rb

We had a support issue some time back where someone created a provider and one or more of the letters were entered downcase. The providers courses would not load on find.
Validate that when creating a new Provider that their provider code is the correct format:
- 3 characters long
- At least one number
- the other two characters can be numbers or letters.
- Any order
Add normalization to the provider_code column so that any input is upcased.
|Provide code length|Doesn't validate upcase|Validates invalid format|
|---|---|---|
|![image](https://github.com/user-attachments/assets/33d47cd9-c515-4d78-89c7-2b95d6012de3)|![image](https://github-production-user-asset-6210df.s3.amazonaws.com/135042929/430851720-bf9e0964-dcb7-460b-b047-92c8935186d7.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credenti …

Validate provider code is uppercase

---

app/views/publish/courses/_course_table_row.html.erb

We received a support ticket mentioning that all courses of a provider could not be found (404 error). It seems the issue is that the link is incorrectly pointing to the accredited provider, not the training provider when signed in as the accredited provider.
- Update "on find" call to `course.on_find(course.provider)`.
- Visit courses of training providers while viewing the accredited provider's page.

Always link to the course's provider in the _course_table_row partial

---

app/controllers/support/recruitment_cycles_controller.rb
app/forms/application_form.rb
app/forms/courses/search_form.rb
app/forms/support/recruitment_cycle_form.rb
app/jobs/rollover_job.rb
app/lib/multiple_parameters_date_type.rb
app/lib/potential_date.rb
app/services/recruitment_cycle_creation_service.rb
app/validators/multiple_parameters_date_validator.rb
app/views/support/recruitment_cycles/index.html.erb
app/views/support/recruitment_cycles/new.html.erb
config/initializers/active_record_config.rb
config/locales/en/activemodel.yml
config/locales/en/support/recruitment_cycles.yml
spec/forms/support/recruitment_cycle_form_spec.rb
spec/services/recruitment_cycle_creation_service_spec.rb
spec/system/support/settings/recruitment_cycles/add_recruitment_cycle_spec.rb

Add the possibility to add a recruitment cycle via support interface this will call the RolloverJob
* For now the Rollover job is empty and will be done in future PR.
1. Visit Support
2. Click Settings
3. Click Recruitment cycles
4. Click Add recruitment cycle
5. Test validations
6. Create one recruitment cycle

Add recruitment cycle via Support interface

---

app/models/course.rb

The error we were seeing is that courses from previous recruitment cycles may have providers that are not in the current cycle.
We can safely return the description of a ratifying provider's details from a previous recruitment cycle.
- Use the `accrediting_provider` instance directly instead of trying to re-lookup the provider.
Try using the API to fetch a course from a previous cycle where their provider is not in the current cycle, it will break.
> https://api.publish-teacher-training-courses.service.gov.uk/api/public/v1/recruitment_cycles/2024/courses
Try using the review app, it will succeed.

Update course ratifying provider description

---

app/components/secondary_navigation_component.rb

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Reference/Attributes/aria-current#page
Add `aria-current="page"` to current page navigation link
Is the current page highlighted
https://github.com/user-attachments/assets/10e0ee4d-0f09-4d1d-93d3-397ccbfe2edd
https://trello.com/c/2Xbwyy84/616-bug-description-basic-details-tab-is-not-highlighted-on-the-publish-course-page

aria-current must have a value "page"

---

.github/workflows/build-and-deploy.yml
.rubocop.yml

Our CICD pipeline currently installs all gems from scratch for every job that need Ruby and gems installed. We can improve this by caching the installed gems.
In previous attempts, caching was problematic as the `bundle exec rubocop` command was failing.
After some thorough investigation, we ran into https://stackoverflow.com/questions/69415433/bundle-exec-rubocop-failling-on-github-actions-but-runs-successfully-locally that outlined the potential cause. Robocop configurations were being picked up from the `./vendor` path.
The solution is to add the following configuration to _our_ `.rubocop.yml` configuration.
```yaml
inherit_mode:
merge:
- Exclude
```
This works, as the `rubocop-rails` gem defines an exclusion of the `./vendor/**/*` files: …

Use setup-ruby bundler cache

---

.github/workflows/build-and-deploy.yml

When optimising the CI pipeline, I forgot to think about the `main` branch deployments.
- Run the `build` step on `main`, always.
\-

Build when running in main

---

terraform/aks/locals.tf

Azure has removed `plphsql` from their list of extensions. This is causing our terraform deployments to fail.
List of Azure Postgres extensions: https://learn.microsoft.com/en-us/azure/postgresql/extensions/concepts-extensions-versions
- Remove `plpgsql` from azure extensions in terraform
- Refer to https://github.com/DFE-Digital/register-early-career-teachers-public/pull/484 for example reference.

Remove `plpgsql` from azure extensions

---

.git-blame-ignore-revs

We recently made a large linting change to adopt the GOV.UK ruby code styles. This causes a lot of our git blame calls to be less useful.
- Add 30dc154189ec222a157a8ddf806b7fdc454c93a2 to ignored commits
- View [app/forms/publish/visa_sponsorship_application_deadline_date_form.rb](https://github.com/DFE-Digital/publish-teacher-training/blob/main/app/forms/publish/visa_sponsorship_application_deadline_date_form.rb), there should be no git blame references to the `rubocop-govuk` changes.

Add rubocop-govuk lint changes to git blame ignore file

---

.github/workflows/build-and-deploy.yml

Use the [actions/upload-artifact](https://github.com/actions/upload-artifact) to upload screenshots of test failures
> Zip archives
> When an Artifact is uploaded, all the files are assembled into an immutable Zip archive. There is currently no way to download artifacts in a format other than a Zip or to download individual artifact contents.
I tried this but it didn't work and I don't know how to debug it easily
```
env:
TEST_GROUP: ${{ matrix.tests.name }}
....
- name: Upload screenshots
if: ${{ failure() && startsWith(env.TEST_GROUP, 'System') }}
```

Split System tests and upload screenshots on failure

---

app/views/find/primary_subjects/index.erb
app/views/find/secondary_subjects/index.erb
spec/system/find/homepage/quick_links/primary_subjects_spec.rb
spec/system/find/homepage/quick_links/secondary_subjects_spec.rb

On Find, there are currently no back links on the Primary and Secondary filter pages to return to the initial search page.
Trello: https://trello.com/c/9SQU1ORY/637-add-back-links-to-primary-and-secondary-filter-pages
Added a govuk back link to the [Primary](https://find-teacher-training-courses.service.gov.uk/primary) and [Secondary](https://find-teacher-training-courses.service.gov.uk/secondary) pages which return the user to the Find homepage.
- check placement and functionality of the new back link.
- ensure tests are put together correctly and passing.

Add back links to Primary and Secondary filter pages

---

config/locales/find.yml
spec/components/find/courses/entry_requirements_component/view_spec.rb
spec/components/find/courses/sumary_component/view_spec.rb

The content on the course page doesn’t match the content on the results page. The content on the results page was iterated based on user research.
Trello: https://trello.com/c/9tD0TgTb/613-bug-content-on-course-page-doesnt-match-results-page
- updated content for course page in `find.yml` which is used in the 'Course summary' and 'Entry requirements' section of the course page:
Updated label `Age range` to `Age group`
Updated label `Qualification` to `Qualification awarded`
Updated label `Degree` to `Degree required`
- adapted spec tests to reflect new content.
- check label names on course page are correct and match up with results page.

Updated labels on the course page to match the results page

---

.git-blame-ignore-revs

The commit SHA for the "Adopt GOV.UK's RuboCop configuration" is incorrect.
- Fix the rubocop-govuk git blame ignore commit SHA
- Also rearrange the `.git-blame-ignore-revs` file and add the commit title as a comment for reference.
Commits should be ignored correctly now.

Fix the rubocop-govuk git blame ignore commit

---

spec/support/derived_metadata.rb
spec/support/features.rb
spec/system/auth/magic_link_spec.rb
spec/system/auth/persona_spec.rb
spec/system/auth/provider_user_signs_in_spec.rb
spec/system/auth/support_user_signs_in_spec.rb
spec/system/canonical_tags_spec.rb
spec/system/support/filters/provider_course_search_filters_spec.rb
spec/system/support/filters/provider_filters_spec.rb
spec/system/support/filters/user_filters_spec.rb
spec/system/support/providers/switching_between_recruitment_cycles_spec.rb
spec/system/support/providers/view_components_spec.rb
spec/system/support/users/creating_a_new_user_spec.rb
spec/system/support/users/deleting_a_user_spec.rb
spec/system/support/users/deleting_user_from_provider_spec.rb
spec/system/support/users/editing_a_user_spec.rb
spec/system/support/users/providers_list_spec.rb
spec/system/support/users/users_list_spec.rb
spec/system/view_pages_spec.rb

We are aiming to move away from feature tests and rely only on Rails system tests. This will allow us to remove DatabaseCleaner and move forward with more canonical testing methodologies.
Move the base feature tests to the system test directory.

Move specs from features to system 1

---

package.json
yarn.lock

We want to ensure that `dfe-autocomplete` is always the correct version. A recent update to the `dfe-autocomplete` package updated the package version to align with the gem version.
- Pin `dfe-autocomplete` to `v0.2.1`.
Everything works as expected.

Pin `dfe-autocomplete` to v0.2.1

---

app/controllers/find/courses/accrediting_providers_controller.rb
app/controllers/find/courses/providers_controller.rb
app/controllers/find/courses/training_with_disabilities_controller.rb
app/controllers/find/homepage_controller.rb
app/controllers/find/primary_subjects_controller.rb
app/controllers/find/results_controller.rb
app/controllers/find/secondary_subjects_controller.rb
app/controllers/find/track_controller.rb

When referencing ruby classes from within a module, Ruby attempts to find class references from within the same module first, before bubbling up to the next module levels.
```ruby
module Find
Analytics # Looks for `Find::Analytics`. If not found, only then does it look for `Analytics`.
end
```
- Remove superfluous `Find` namespace from `Find` module nested class calls.
- Review that tests pass and app works - specifically the Find service.

Remove unnecessary Find namespaces

---

app/components/find/header/view.html.erb
app/controllers/find/pages_controller.rb
app/decorators/course_decorator.rb
app/helpers/view_helper.rb
app/views/find/courses/training_with_disabilities/show.html.erb
app/views/find/primary_subjects/index.erb
app/views/find/secondary_subjects/index.erb
app/views/find/sitemaps/show.xml.builder
app/views/publish/courses/course_button_panel/_published.html.erb
app/views/support/settings/index.html.erb
config/routes/find.rb
spec/components/find/header/view_spec.rb
spec/features/find/maintainance_page_spec.rb
spec/features/find/maintenance_banner_spec.rb
spec/requests/find/sitemaps_spec.rb
spec/system/find/homepage/quick_links/primary_subjects_spec.rb
spec/system/find/homepage/quick_links/secondary_subjects_spec.rb
spec/system/find/results_helper.rb

The find `root` is defined outside of the `find` namespace. There is no reason for this to be the case.
- Move the `find` root into the `find` namespace. Remove the `as` configuration and leave it as the default, `find_root`. `find_root_path`
- Add a host default to find to point find's url helpers to find's domain.
- Remove `x_find_url` helpers. We don't need these.
- Find works as it does.
- Publish links to Find also work as expected.
- Specs are all happy.

Update find route to find_root

---

app/components/find/courses/contents_component/view.html.erb
app/components/shared/courses/financial_support/fees_and_financial_support_component/view.html.erb
app/views/find/courses/_salary.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb
config/locales/en.yml
config/locales/find.yml

The ‘Salary’ section of the course pages is often empty, or contains very little information. The callout box in the ‘Fees and financial support’ section of salaried courses refers to salary, which is confusing. We need to merge the two sections, so that the provider free text about salary sits alongside the call out box that refers to salary.
Trello: https://trello.com/c/Yi1bM2cG
- merged 'Salary' into 'Fees and financial support' section.
- removed standalone 'Salary' section.
- adapted `_salary` partial to remove title and any styling so it can be rendered within the `FeesAndFinancialSupportComponent`.
- adapted title of section to render either 'Salary and financial support' or 'Fees and financial support' depending on the context.
- updated contents list on page to dynamically render …

Improved courses page - Merged 'Salary' and 'Fees and financial support sections

---

app/helpers/find/view_helper.rb

There was a lingering reference to `Settings.find_valid_referers`. We can safely remove it.
- Remove `Settings.find_valid_referers` reference.
- Update code to use Find and Publish hosts instead.
- Navigate to a course details page from searching.
- Click on some links and click back. All should be fine.

Remove references to `Settings.find_valid_referers`

---

config/settings/production.yml
config/settings/qa.yml

Since we added the ability to configure multiple valid hosts, we can now add the additional temp URLs.
> The temp ingress for both prod and qa env are below.
> 
> **Production**
> - publish-temp.teacherservices.cloud
> - find-temp.teacherservices.cloud
> - api-publish-temp.teacherservices.cloud
> 
> **QA**
> - publish-temp.test.teacherservices.cloud
> - find-temp.test.teacherservices.cloud
> - api-publish-temp.test.teacherservices.cloud
- Add temp URLs to production and QA settings.
- Review https://github.com/DFE-Digital/publish-teacher-training/pull/5202

Add temp hosts to valid Production and QA hosts

---

app/jobs/rollover_job.rb
app/jobs/rollover_provider_job.rb
app/services/recruitment_cycle_creation_service.rb
app/services/rollover_provider_service.rb
spec/jobs/rollover_job_spec.rb
spec/jobs/rollover_provider_job_spec.rb
spec/services/rollover_provider_service_spec.rb

Originated from this PR comment:
https://github.com/DFE-Digital/publish-teacher-training/pull/5154#discussion_r2039199331
When running the rollover will be good to specify the recruitment cycle.

Specify the recruitment cycle when running automated rollover

---

maintenance_page/manifests/production/ingress_temp_to_main2.yml
maintenance_page/manifests/production/ingress_temp_to_main3.yml
maintenance_page/manifests/qa/ingress_temp_to_main2.yml
maintenance_page/manifests/qa/ingress_temp_to_main3.yml
maintenance_page/scripts/failback.sh
maintenance_page/scripts/failover.sh

There is a requirement for applications to be DR ready.
Adding the temp ingress for the find and api-publish entry points
Review the ingress
https://trello.com/c/dxDVXong/2237-publish-dr-test

Adding temp ingress for the find and api-publish

---

app/controllers/support/recruitment_cycles_controller.rb
app/forms/support/recruitment_cycle_form.rb
app/services/recruitment_cycle_creation_service.rb
app/views/support/recruitment_cycles/_form.html.erb
app/views/support/recruitment_cycles/index.html.erb
app/views/support/recruitment_cycles/show.html.erb
config/locales/en/activemodel.yml
config/locales/en/activerecord.yml
spec/factories/recruitment_cycles.rb
spec/features/publish/viewing_a_course_spec.rb
spec/forms/support/recruitment_cycle_form_spec.rb
spec/system/support/settings/recruitment_cycles/add_recruitment_cycle_spec.rb
spec/system/support/settings/recruitment_cycles/edit_recruitment_cycle_spec.rb

Add the field "available in publish from" date field to recruitment cycle support. Also added on index and show actions.
1. Can you add a new cycle and add the available from field?
2. Can you edit the cycles and change the available from field?
3. Does it show in index and show actions?

Add available in publish from date in Publish

---

app/components/find/courses/apply_component/view.html.erb
app/forms/publish/visa_sponsorship_application_deadline_date_form.rb
app/services/courses/assign_visa_sponsorship_application_deadline_service.rb
spec/features/publish/courses/new_visa_sponsorship_application_deadline_spec.rb
spec/services/courses/creation_service_spec.rb

We are doing testing of the visa sponsorship application deadlines and come across a few little bugs. 
First, just a formatting change, there wasn't any margin between the button and the text saying that there was a deadline. 
| Before | After |
| ------ | ------ |
| ![Screenshot 2025-05-02 at 17 09 56](https://github.com/user-attachments/assets/4e97bebf-3ffa-4c45-b1e1-75c80b1fa2aa) | ![image](https://github.com/user-attachments/assets/da753895-85bc-4f87-b0b7-06cd67d1449b) |
Next, a problem with time. 
- In one place, saving the time as 11:59 instead of 23:59.
- Everywhere, we were not including the intended time zone, which should be 11:59 local to London.

900 bug wrong time stamp on visa sponsorship deadline

---

.github/workflows/build-and-deploy.yml
guides/prototype-branches.md

We need a way to rapidly deploy review apps for Prototypes.
"Prototypes" are UI-focused branches that are primarily built by the team's Interaction Designer. Their purpose is to provide realistic service functionality for User Research and user testing sessions.
- Add new condition for the `lint` step. It will not run for PRs with the `prototype` label.
- Add new condition for the `build` and `deploy-review-app` steps to run for PRs with the `prototype` label.
- Review the GitHub Action run: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/14992818313
- Only the `build` and `deploy-review-app` steps should run.
- Review the [Prototype branches](https://github.com/DFE-Digital/publish-teacher-training/blob/dd/allow-deployments-for-prototypes/guides/prototype-branches.md) …

Skip linting and testing for prototype deployments

---

.github/workflows/build-and-deploy.yml

The `deploy-review-app` is running on pushes to `main`. We should prevent this from happening.
- Clean up the `build-and-deploy.yml` GitHub Action workflow, namely the following jobs:
- `build`
- `deploy-review-app`
- Check the new logic.
- See reference comment here: https://github.com/actions/runner/issues/491#issuecomment-850884422
- See the `prototype` labeled run result: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/15018013495

Skip review apps on main

---

.github/workflows/build-and-deploy-prototype.yml
.github/workflows/build-and-deploy.yml

We're having difficulty conditionally starting at the `build` job for prototype workflows whilst also preventing `build` and `deploy-review-app` from running on `main` pushes _and_ when previous steps fail.
- Split out the prototype PR workflow from the main development workflow.
When a PR is tagged as a prototype, it won't run the main development workflow and will just deploy a review app.
It might also be worth adding the condition of flagging `prototype/` branches automatically as prototype PRs.

Separate out prototype workflow from main development workflow

---

config/routes/publish.rb
spec/requests/publish/training_partner_course_exports_spec.rb

Providers are trying to use ‘download CSV file’ option under the training partners tab in Publish, but it is showing a 505 Internal Sever Error page.
The reason is because the route is pointing to a controller that was deleted.
1. Go to Publish (UCL as example)
2. Click on Training parterns tab
3. Click Download CSV
It should download on the review app. You can compare with QA too.

Fix training partners course export

---

.github/workflows/build-and-deploy-prototype.yml
guides/prototype-branches.md

All PRs are now triggering the prototype workflows and being immediately skipped.
This creates a lot of noise in the actions history.
- Set the `build-and-deploy-prototype.yml` workflow to only trigger on pull requests for branches prefixed with `prototype/`.
- Update prototype documentation.
- Review the [updated documentation](https://github.com/DFE-Digital/publish-teacher-training/blob/dd/exclude-non-prototype-branches-from-prototype-workflow/guides/prototype-branches.md).

Exclude non "prototype/" branches from prototype workflow runs

---

app/models/gias_school.rb
lib/gias/importer.rb
spec/lib/gias/importer_spec.rb
spec/models/gias_school_spec.rb
spec/rails_helper.rb

Gias Schools are not searchable because when we save them, we aren't running the ActiveRecord Callbacks.
The CSV we receive has open schools with blank columns that we are currently validating the presence of.
We decided to use `upsert_all` because it was fast. But this is in a background job, run at night, once a week.
We will save each GiasSchool with callbacks that has changed during the import.
Remove presence validation on columns that are nullable in the source CSV.
https://trello.com/c/5q1tqcZ8/725-gias-schools-are-not-searchable

Ensure that saving GiasSchool creates pg_search_vectors

---

app/forms/publish/visa_sponsorship_application_deadline_date_form.rb
spec/features/publish/courses/editing_visa_sponsorship_deadline_spec.rb
spec/features/publish/courses/editing_visa_sponsorship_spec.rb
spec/features/publish/courses/new_visa_sponsorship_application_deadline_spec.rb

I mistakenly assumed that the application end date was the apply deadline, but it is not. This means that potentially providers could set visa sponsorship application deadline dates _after_ applications have closed. (flagged by @tomas-stefano). Though in practice, no applications would be accepted after the apply deadline, and no providers have done so yet. 
Sets the upper deadline for visa sponsorship application deadlines to match the apply deadline.
In the review app, try setting a visa sponsorship application deadline for a 2025 course after the apply deadline (16 September). You should receive an error.

[941] Set upper bound of visa sponsorship deadline to eq apply deadline

---

app/components/find/courses/summary_component/view.html.erb
app/views/find/courses/show.html.erb
app/views/publish/courses/preview.html.erb
spec/features/publish/viewing_a_course_preview_spec.rb

The "applications closed" message is not in the same location as the top "Apply" button. We want to align the position of the "applications closed" message to be in the same place as the top "Apply" button.
- Move up the "applications closed" partial.
| Before | After |
| ------ | ----- |
| ![CleanShot 2025-05-20 at 11 42 23](https://github.com/user-attachments/assets/2ba3c1d6-6dfb-4d87-8cd9-deaddd5f5c93) | ![CleanShot 2025-05-20 at 11 42 07](https://github.com/user-attachments/assets/820fcecc-557f-414a-848e-82e2044c0adc) |

Move up the course applications closed notification

---

guides/disaster-recovery.md

We recently conducted disaster recovery tests on our service WRT our postgres database.
We decided to create a detailed step by step guide including direct links and references to the resources within our service to make the process of handling a disaster more efficient and less confusing.
Add a guide for handling a database outage in Publish
[READ THE DOCUMENT HERE](https://github.com/DFE-Digital/publish-teacher-training/blob/im/disaster-recovery-guide/guides/disaster-recovery.md)
Is it good?
Does it make sense?
https://trello.com/c/7bTGOvNA/646-write-up-disaster-recovery-documentation-specific-for-the-publish-and-find-service?filter=member:mcnultyiain

Add disaster recovery guide

---

app/components/find/courses/apply_component/view.rb
app/controllers/publish/courses/visa_sponsorship_controller.rb
app/decorators/course_decorator.rb
app/lib/feature_flags.rb
app/models/concerns/publish/course_basic_detail_concern.rb
app/services/workflow_step_service.rb
spec/components/find/courses/apply_component/view_spec.rb
spec/features/publish/course_confirmation_spec.rb
spec/features/publish/courses/editing_apprenticeship_spec.rb
spec/features/publish/courses/editing_funding_type_spec.rb
spec/features/publish/courses/editing_visa_sponsorship_deadline_spec.rb
spec/features/publish/courses/editing_visa_sponsorship_spec.rb
spec/features/publish/courses/new_tda_course_spec.rb
spec/features/publish/courses/new_visa_sponsorship_application_deadline_spec.rb
spec/features/publish/courses/new_visa_sponsorship_spec.rb
spec/features/publish/e2e/new_course_spec.rb
spec/services/workflow_step_service_spec.rb
spec/system/support/settings/feature_flags/view_feature_flags_spec.rb

This feature flag is not necessary anymore. The visa sponsorship deadline feature is permanent.
Removed `visa_sponsorship_deadline` feature flag where it's used

Remove visa sponsorship deadline feature flag

---

app/views/publish/pages/performance_dashboard.html.erb
spec/requests/publish/pages/performance_dashboard_spec.rb

Performance Dashboard is broken because when the controller was moved, the paths to the views were not updated in the template.
Fix the paths to the partials loaded in the performance dashboard
Add request spec to verify the page loads

Update the path to performance dashboard partials

---

app/controllers/application_controller.rb
app/controllers/find/application_controller.rb
app/middleware/request_logging_tags.rb
config/application.rb

Rails.logger.tags are piling up and not being cleared after each request.
I've decided to use a different way of logging values. Instead of the `config.log_tags` I've added a custom middleware to log request_id and session_id. This needs to go in middleware otherwise not every relevant log line will be tagged.
Piling up request ids:

Use SemanticLogger.tagged to log session_id and request_id

---

app/queries/rollover_progress_query.rb
app/services/partnerships/copy_to_provider_service.rb
app/services/providers/copy_to_recruitment_cycle_service.rb
app/services/rollover_provider_service.rb
app/views/support/recruitment_cycles/show.html.erb
config/locales/en/support/recruitment_cycles.yml
spec/queries/rollover_progress_query_spec.rb
spec/services/partnerships/copy_to_provider_service_spec.rb
spec/services/providers/copy_to_recruitment_cycle_service_spec.rb
spec/services/rollover_provider_service_spec.rb
spec/services/rollover_service_spec.rb

The partnerships was a new work added this year so this is not included during the rollover.
This PR adds to the rollver script the partnerships records.
Also added the rollover progress numbers to eh recruitment cycle page:
Now we can see the number of partnerships created in the page.
**There are some discarded providers which has partnerships so I have to exclude them from numbers in rollover progress summary card.**
During the rollover process, we need to create provider records one by one. Each provider may have partnerships (as a training provider or an accredited provider) that also need to be created. However, a partnership can only be created if **both** providers involved (training and accredited) already exist in the database.
- When processing a single provider, it's possible …

Rolled over provider partnerships during rollover

---

app/controllers/support/recruitment_cycles_controller.rb
app/forms/support/review_rollover_form.rb
app/models/recruitment_cycle.rb
app/policies/recruitment_cycle_policy.rb
app/services/recruitment_cycle_creation_service.rb
app/views/support/recruitment_cycles/review_rollover.html.erb
app/views/support/recruitment_cycles/show.html.erb
config/locales/en/activemodel.yml
config/locales/en/support/recruitment_cycles.yml
config/routes/support.rb
spec/forms/support/review_rollover_form_spec.rb
spec/policies/recruitment_cycle_policy_spec.rb
spec/services/recruitment_cycle_creation_service_spec.rb
spec/system/support/settings/recruitment_cycles/confirm_rollover_spec.rb

This PR enhances the support interface for confirming recruitment cycle rollover. 
It improves user guidance, eligibility explanation, summary statistics, and only after confirmation the rollover will be run.
* Confirmation Form: Users must type confirm rollover to proceed, with custom error messages for blank or incorrect input.
I fill these tomorrow morning.
1. Visit the support interface, navigate to a future recruitment cycle, and review the rollover confirmation flow.
2. Confirm that eligibility, summary, and timing information is clear.
3. Test both valid and invalid confirmation submissions.
4. Ensure the flash message and job enqueueing behave as expected.
5. Visit /sidekiq to see rollover running.

Change the rollover trigger

---

bin/restore-backup

This PR refactors the database restore Bash script to improve readability. 
The script now supports a --no-download flag, allowing us to skip the backup download and decompression steps if the SQL file is already available locally.
Strict mode: Enables set -euo pipefail for robust error handling.
Modularization: Breaks the script into clear functions for each major operation.
Argument parsing: Adds a --no-download flag and a help option, with usage instructions.
Help: Run with --help to see usage instructions.

Refactor database restore script and add --no-download flag

---

.github/workflows/build-and-deploy.yml

When you create a PR, and you know you want it to be deployed to a review app, before creating the PR you will add the deploy label.
This actually triggers two builds.
1. github.event.action = 'opened'
2. github.event.labled
The 'opened' workflow will run lint, tests, and build the image.
The 'labeled' workflow will run lint, tests, build and deploy.
If we create a PR with the deploy label, we want to skip the build for 'opened'.
The opened workflow is skipped
Skipped

Do not run build on PR open when deploy label is present

---

app/controllers/support/recruitment_cycles_controller.rb
app/forms/support/recruitment_cycle_form.rb
app/services/recruitment_cycle_creation_service.rb
app/views/support/recruitment_cycles/_form.html.erb
app/views/support/recruitment_cycles/index.html.erb
config/locales/en/activemodel.yml
spec/factories/recruitment_cycles.rb
spec/forms/support/recruitment_cycle_form_spec.rb
spec/services/recruitment_cycle_creation_service_spec.rb
spec/system/support/settings/recruitment_cycles/add_recruitment_cycle_spec.rb
spec/system/support/settings/recruitment_cycles/edit_recruitment_cycle_spec.rb

During the course rollover process, support users need the ability to access next cycle course data in both the Support and Publish interfaces before it becomes available to general Publish users.
This PR adds this field to be set via support interface when creating a new cycle.
1. Enter on Support
2. Settings > Recruitment cycles -> Add recruitment cycle
3. Set the dates
**For now this work is only setup the field and not using. This will be part 3 (next PR!).;**

Add "available for support users" field to support interface

---

.github/workflows/build-and-deploy.yml

I changed when the lint job runs in our CI workflows recently to prevent it running on the pull_request opened event if and when the label deploy was added to prevent the build running on "opened" and "labeled".
I did not sepcify that lint should always happen on the main branch and now the build isn't running when we merge PRs.
Always run lint job in CI on the main branch

CI linting should always run on main branch

---

app/controllers/find/results_controller.rb
app/forms/courses/search_form.rb
app/services/courses/query.rb
spec/forms/courses/search_form_spec.rb
spec/services/courses/query_spec.rb

The Apply service would like to direct Candidates to "recommended courses" which would exclude courses that they have previously applied to. 
- Added the `excluded_courses` search param to the results page - this param is not used in the Find UI filters
- ~Controversially added a JSON response from the Results page.~
~The JSON response was put in to see how easy it could be. Ideally this would exist, allowing the Apply service to programatically check if there would be any results for a course recommendation query, before offering it to the Candidate.~
~This PR should act as a conversation on the possibilities/approach~

Add excluded course param to search results

---

app/components/support_title_bar.rb
app/components/title_bar.rb
app/controllers/publish/application_controller.rb
app/controllers/publish/providers_controller.rb
app/controllers/support/recruitment_cycle_controller.rb
app/helpers/application_helper.rb
app/helpers/recruitment_cycle_helper.rb
app/helpers/title_bar_helper.rb
app/models/provider.rb
app/models/recruitment_cycle.rb
app/models/user.rb
app/services/rollover_period.rb
app/services/user_associations_service/create.rb
app/views/layouts/support.html.erb
app/views/publish/pages/performance_dashboard.html.erb
app/views/publish/recruitment_cycles/_show_during_rollover.html.erb
app/views/support/recruitment_cycle/index.html.erb
app/views/support/recruitment_cycles/show.html.erb
spec/components/support_title_bar_spec.rb
spec/components/title_bar_spec.rb
spec/features/publish/providers_index_spec.rb
spec/system/support/providers/switching_between_recruitment_cycles_spec.rb

During the course rollover process, support users need the ability to access next cycle course data in both the Support and Publish interfaces **before** it becomes available to general Publish users.
This requires a new date field in the recruitment cycle: "Available for Support Users Date".
Support users: Can see next cycle courses **in both Support and Publish interfaces** from this date.
Publish users: Can only see next cycle courses after the standard "Available in Publish From" date.
This PR adds the links when they are available depending on the dates and the types of the user.
1. Visit support
2. Click Settings > Recruitment Cycles > Add recruitment cycle
3. Add 2026 cycle
4. Add the dates that the next cycle will be available for support users and publish users
5. If both in the …

Enable early access for support users during rollover (Part 3)

---

app/models/course.rb
spec/features/publish/viewing_a_course_spec.rb
spec/models/course_spec.rb

Do not show the button "Roll over course" for publish users if "today's date" is before the recruitment cycle date that is available for publish users.
Only shows the button after the date is available for publish users.
1. Run the rollover
2. Enter as provider user 
3. Enter on a provider page **on the current 2025 cycle**
4. See a rolled over courses from the current cycle (this course can be rolled over to the next cycle)
5. The button "Rollover course" should only appear after the recruitment_cycle.available_in_publish_from date.

Only show manually rollover button after is available to publish users

---

Gemfile
Gemfile.lock
app/components/govuk/one_login_header_component.rb
app/controllers/find/authentication/sessions_controller.rb
app/javascript/find/one-login-header.js
app/lib/authentications/candidate_config.rb
config/initializers/omniauth.rb
config/routes/find.rb
config/settings.yml
config/settings/production.yml
config/settings/test.yml
spec/lib/authentications/candidate_config_spec.rb
spec/requests/find/authentication_error_spec.rb

_Yesterday, July 1st, version all versions of the `omniauth-govuk-one-login` gem were yanked from RubyGems. I'm investeigating what is happening with this gem. For now, we're pulling the library in from the GitHub repo._
`Settings.one_login.enabled` must be true, for candidates can log in at `/auth/one-login`
If `Settings.one_login.enabled` is false, then candidates can log in at `/auth/find-developer`
This should never be true in Production.
|Environment| Settings.one_login.enabled|Details|
|---|---|---|
|Production|Yes|Obvious|
|Test|No|We cannot stub every request in system tests|
|Development|Can be|If you are testing the integration you can enable it. There will be documentation|
|Review|Can be|If you are testing the integration you can enable it. There will be documentation|
_This …

Candidate can Sign In via One Login

---

app/views/publish/courses/modern_languages/_form_fields.html.erb
app/views/publish/courses/modern_languages/edit.html.erb
config/locales/en.yml

Trello: https://trello.com/c/nEFiztVI/779-bug-unexpected-content-when-changing-modern-foreign-language-course-in-publish
On the Modern Foreign Language course page in Publish there are a few things that need to be removed/edited:
1. There is an extra caption on the page saying 'Add course' which should not be there
2. There is a ^ symbol in both the error summary at the top and in the error message with the label
3.  There is an additional error message above the caption and H1 which should not be there
- remove the ^ symbol from error message in locale file
- remove the rendering of `error_messages` partial on the page which appears to add an additional error message which is not needed. The error message now only appears in the error summary and with the form label when a user does not …

Remove bug: Unexpected content when changing Modern Foreign language course in Publish

---

app/controllers/application_controller.rb
app/controllers/concerns/errorable.rb
app/controllers/find/application_controller.rb
app/controllers/find/errors_controller.rb
app/controllers/publish/providers_controller.rb
app/views/errors/not_acceptable.html.erb
spec/controllers/publish/courses/a_level_requirements/what_a_level_is_required_controller_spec.rb
spec/requests/find/errors_spec.rb
spec/requests/publish/errors_spec.rb

When a request is made to our app with an unexpected extension, we try to render a not found template, but the request is asking for a format that we don't provide.
Like, `find.com/x/y/z.json` will effectively try to render `404.json`. We crash when we can't find the matching template.
`include Errorable` in `Find::ApplicationController` and `ApplicationController` so it's available througout our controllers.
Move all `rescue_from` macros into the Errorable concern
Add 406 / not_acceptable error handling.
Add tests for 404, 406, 500 in Find and Publish
https://find-review-5359.test.teacherservices.cloud/results.json
We get a lot of these
This also fixes this
https://qa.publish-teacher-training-courses.service.gov.uk/publish/organisations/asdfasdf/2025/courses/J522 …

Handle uncaught exceptions

---

app/components/notification_banner.html.erb
app/components/notification_banner.rb
app/views/publish/authentication/sign_in/index.html.erb
app/views/publish/courses/index.html.erb
config/locales/en/publish.yml

Trello: https://trello.com/c/apMloMgz/840-publish-banner-a-notification-banner-that-communicates-the-new-date-of-rollover
Research with providers shows that they don’t see all comms that are communicated via email, for example that the date of rollover has changed.
- add a notification banner that communicates the new date of rollover in Publish
- adapt `NotificationBanner` component to take in `text_body` with `class="govuk-body"` (non bold text), as this is needed to display the content correctly. 
- add notification banner to top of Publish Sign in page and Organisation page (Courses tab)
**Publish sign in page**
**Organisation page**
- check notification banner on Publish sign in page 
- check 'Courses' page of different organisations to test banner is correct/present.

Add a notification banner that communicates the new date of rollover in Publish

---

Gemfile
Gemfile.lock

We have forked the omniauth_govuk_one_login library from OPSS.
This means we are now hosting it ourselves in `DFE-Digital`
https://github.com/DFE-Digital/omniauth-govuk-one-login
We can sync the fork for updates provided by OPSS and the original author.
Bundle our own version of `omniauth-govuk-one-login`
https://trello.com/c/RaC22hLN/868-onelogin-make-the-gem-available-again

Bundle omniauth_govuk_one_login from DFE-digital fork

---

app/controllers/concerns/find/authentication.rb
app/controllers/find/authentication/sessions_controller.rb
app/models/authentication.rb
app/services/find/candidate_authenticator.rb
spec/factories/authentications.rb
spec/factories/candidates.rb
spec/services/find/candidate_authenticator_spec.rb
spec/support/candidate_auth_helper.rb
spec/system/find/results_page/ordering_spec.rb
spec/system/find/signin_with_different_email_spec.rb

A Candidate user can change their email address in One Login.
If they do that, we want to be able to authenticate them correctly and update their email address in our system.
Upon authentication, find the Authentication matching the subject_key of the One Login authentication hash.
Find the associated candidate. If the email does not match the auth hash, then update the email address.
https://trello.com/c/52YVeMdS/825-one-login-account-can-change-email-and-keep-same-candidate-account

Handle email change for candidate accounts

---

app/lib/authentications/candidate_omni_auth.rb
spec/lib/authentications/candidate_omni_auth_spec.rb

One Login should be enabled in any environment that Settings.one_login.enabled is true.
FindDeveloper should replace One Login if Settings.one_login.enabled is false.
Production should *never* have FindDeveloper enabled
FindDeveloper logs the user in with a specific email, resolving to a specific user. Is this ok in QA, Staging, Sandbox?
If for any reason we disable One Login in a lower environment, we want the Find Developer strategy to be enabled.
Is there any environment other than Production that we should not enable the FindDeveloper Strategy?

Find developer is enabled when one-login is disabled except production

---

app/controllers/concerns/errorable.rb

When our application receives a request directly to `/500`, no error is passed and this triggers an `ArgumentError`.
The argument is optional because when `/500.php`, for example, is
requested directly, no error is passed to the method
https://trello.com/c/0GwRzRnI/876-error-rescuing-error

Param passed to internal_server_error handler is optional

---

app/controllers/find/authentication/sessions_controller.rb
app/services/find/authentication/backchannel_logout.rb
config/routes/find.rb
spec/requests/find/backchannel_logout_spec.rb

When a user signs out of One Login, One Login will send a request to our registered backchannel logout URL so that we can end the session of the users in Find.
Implement the `OmniAuth::OneLoginStrategy::BackchannelLogoutUtility`
This module securely accepts a token from the One Login IDP with an instruction to sign out a specific user from Find when their session is ended in One Login.
According to the specification, the BackchannelLogout only gets sent when a user explicitly signs out, not when their session expires.
https://trello.com/c/tBj00o4a/826-one-login-backchannel-logout

One Login backchannel logout

---

app/controllers/support/candidates_controller.rb
app/views/layouts/support.html.erb
app/views/support/candidates/index.html.erb
config/locales/en.yml
config/locales/en/layouts/support.yml
config/locales/en/support/candidates.yml
config/routes/support.rb
spec/system/support/candidates/list_candidates_spec.rb

List all the candidates that have logged into our service
- Add an index in the Support Console for listing Candidates.
- The index is paginated

Add Index for Candidates in Support

---

app/models/authentication.rb
spec/models/authentication_spec.rb

When an authentication is created, when we check if it is valid,
we should exclude itself from duplication checks
Check if an Authentication is unique by excluding itself from the check
[Unique Authentication validation bug](https://trello.com/c/x6JMQsxL/912-unique-authentication-validation-bug)

An existing authentication should not trigger unique validation error

---

app/models/data_hub/update_sites_from_gias_process_summary.rb
app/services/data_hub/update_sites_from_gias/dry_run_site_updater.rb
app/services/data_hub/update_sites_from_gias/executor.rb
app/services/data_hub/update_sites_from_gias/schools_gias_diff_query.rb
app/services/data_hub/update_sites_from_gias/site_updater.rb
app/services/data_hub/update_sites_from_gias/summary_builder.rb
config/analytics_blocklist.yml
lib/tasks/update_sites_from_gias.rake
spec/services/data_hub/update_sites_from_gias/dry_run_site_updater_spec.rb
spec/services/data_hub/update_sites_from_gias/executor_spec.rb
spec/services/data_hub/update_sites_from_gias/schools_gias_diff_query_spec.rb
spec/services/data_hub/update_sites_from_gias/site_updater_spec.rb
spec/services/data_hub/update_sites_from_gias/summary_builder_spec.rb

This PR introduces a new DataHub script for batch updating Site records from GIAS, addressing the need to:
* Detect and update Site records with any field differing from their joined GIAS record for a given recruitment cycle.
* Support both real-run (persisting updates) and dry-run (no DB updates, for preview/audit) via dependency-injected updater strategies, following prior DataHub service patterns.
Provide auditability via process summaries: per-field counts, before/after per-row hashes, and clear reporting.
To use in console:
```ruby
cycle = RecruitmentCycle.find_by(year: "2025")
DataHub::UpdateSitesFromGias::Executor.new(recruitment_cycle: cycle).execute
```
```ruby
DataHub::UpdateSitesFromGias::Executor.new(recruitment_cycle: cycle, updater_class: …
```

Implement DataHub::UpdateSitesFromGias batch update

---

terraform/aks/workspace_variables/qa.tfvars.json

* Increase QA main_app memory limit to 1.5Gi.
* This change is in response to observed memory usage during recent register school import rake task, which peaked at approximately 557Mi locally. 
* Setting the memory limit to 1.5Gi provides a safe buffer for fluctuations and ensures reliable operation during heavy workloads.
Helps prevent OOMKilled pod failures during imports.

Increase main_app memory limit to 1.5Gi in QA configuration

---

app/helpers/publish/course_schools_helper.rb
app/views/publish/courses/_basic_details_tab.html.erb
app/views/publish/courses/confirmation.html.erb
app/views/publish/courses/schools/edit.html.erb
app/views/publish/courses/schools/new.html.erb
config/locales/en/publish.yml
config/locales/en/publish/courses/confirmation.yml
spec/features/publish/course_confirmation_spec.rb
spec/helpers/publish/course_schools_helper_spec.rb

Trello: https://trello.com/c/XvfnwVdg/910-add-content-to-the-schools-page-when-adding-a-course
This ticket is to update the content on the Schools page when a provider adds a course (it is part of the parent ticket to [Add location controls at a course level](https://trello.com/c/FOWwybxi/350-add-location-controls-at-a-course-level))
- update content on the Add a Course flow’s Schools page and Check Your Answers page.
- modify the Basic Details tab/page after course creation.
- conditionally render "Placement school(s)" or "Employing school(s)" labels based on whether the course is fee-based or salaried on the above pages.
- create a new helper (`Publish::CourseSchoolsHelper`) to handle dynamic labels and warning text.
- add specs for the new helper to ensure correct behaviour.
**Schools …

Add content to the schools page when adding a course

---

spec/features/publish/searching_for_a_school_spec.rb
spec/features/publish/searching_for_a_study_site_spec.rb

One of our test runs failed because we named a school Bernard, searched schools with that term, and another school was returned as well because it's address was generated as North Bernard.
Tests can become flaky if we use text that might be autogenerated by
Faker. Try use text that won't match something generated by Faker
https://github.com/DFE-Digital/publish-teacher-training/actions/runs/16821154975/job/47648183672?pr=5485

Replace "Bernard" from test subjects

---

app/controllers/publish/application_controller.rb
app/controllers/support/application_controller.rb
app/models/current.rb

We often have to discover what the current recruitment cycle is, by using `@recruitment_cycle` , passing the recruitment cycle as an argument into components, etc.
It would be good to have a single source of truth about recruitment cycle. It's a fairly global attribute in the application so maybe suitable for CurrentAttribute.
This will be set on every request.
It will be available inside Components too
If you test a component in isolation, and the component uses Current,
you'll need to initialize it
```ruby
before { Current.recruitment_cycle = .... }
```

Add Current.recruitment_cycle

---

app/components/course_preview/missing_information_component.html.erb
app/components/course_preview/missing_information_component.rb
app/controllers/publish/providers/course_fields/why_train_with_us_controller.rb
app/forms/publish/why_train_with_us_form.rb
app/models/recruitment_cycle.rb
app/serializers/api/public/v1/serializable_provider.rb
app/views/publish/providers/course_fields/why_train_with_us/edit.html.erb
app/views/publish/providers/details.html.erb
config/locales/en/publish/providers/course_fields/why_train_with_us.yml
config/locales/en/publish/why_train_with_us_form.yml
config/routes/publish.rb
spec/features/publish/edit_provider_details_2026_spec.rb
spec/forms/publish/why_train_with_us_form_spec.rb
spec/serializers/api/public/v1/serializable_provider_spec.rb

Information is stored on the Provider model that is shared across all the providers courses in Find. This PR updates the details that a provider displays when describing to a candidate what their organisation is.
This information is available on every course the provider runs or accredits.
**These changes will be visible starting in the 2026 recruitment cycle.**
Change from using the `train_with_us` column to using two columns `about_us` and `value_proposition`.
The Provider is required to fill in both these inputs.
`train_with_us` is available in the API. I've concatenated the two fields and made them available through the API on that attribute.
|Provider console|API response|
|---|---|
|<img width="1156" height="624" alt="image" …

[Longform] Why train with us

---

app/controllers/publish/courses_controller.rb
app/decorators/course_decorator.rb
app/views/find/courses/_v1_components.html.erb
app/views/find/courses/show.html.erb
app/views/find/courses/v2/_components.html.erb
app/views/find/courses/v2/_school_placement.html.erb
app/views/publish/courses/preview.html.erb
config/locales/en/find/courses.yml
config/locales/en/find/courses/v2/school_placement.yml
spec/system/find/courses/long_from_content/school_placement_spec.rb

Currently we do not have a structure to separate V1 from V2 in find, this PR should offer guidance to every dev working on this so that we engineer this solution in a similar fashion.
introduction of new partials, specifically displaying content for V1 and V2 (Pre and post long form content go live).
It also has changes to the course page preview in publish. Both sides will share the same partials and components to keep it dry and consistent.

[Longform] Seperation of V1 and V2 in find

---

app/components/course_preview/missing_information_component.rb
app/controllers/publish/providers/course_fields/disability_support_controller.rb
app/forms/publish/disability_support_form.rb
app/views/publish/providers/course_fields/disability_support/edit.html.erb
app/views/publish/providers/details.html.erb
config/locales/en/publish/providers/course_fields/disability_support.yml
config/locales/en/publish/providers/providers.yml
config/routes/publish.rb
spec/components/course_preview/missing_information_component_2026_spec.rb
spec/features/publish/edit_provider_details_2026_spec.rb
spec/system/publish/providers/courses/missing_disability_information_2026_spec.rb

Conditionally render old and new Training with disabilities sections in Publish.

[Longform] Training with Disabilities

---

app/components/find/courses/contact_details_component/view.html.erb
app/views/find/courses/providers/show.html.erb
app/views/find/courses/v2/_components.html.erb
app/views/find/courses/v2/_train_with_us.html.erb
config/locales/en/find/courses.yml
config/locales/en/find/courses/v2/train_with_us.yml

Update/Add Why train with us on provider and course page
Add content and add new sections

Longform: Add 'Why train with us' to Find

---

app/assets/stylesheets/publish/application.scss
app/assets/stylesheets/publish/components/_newly_added_tag.scss
app/components/publish/newly_added_tag_component.html.erb
app/components/publish/providers/school_placements/outcome_explainer_component.html.erb
app/components/publish/schools/notification_banner_component.html.erb
config/locales/en/components/publish/outcome_explainer_component.yml
config/locales/en/components/publish/schools/notification_banner_component.yml
config/locales/en/components/publish/schools_changed_banner_component.yml

1. Schools landing page notification banner Replace paragraph:
```
We automatically upload all schools you are working with.
```
With:
```
You will no longer need to manually add all your schools to your account. We automatically upload all schools you are working with.
```
2. School landing page intro content Replace ‘add’:
Your courses will not appear in candidates‘ location searches if you do not add placement schools to them.
With ‘attach':
Your courses will not appear in candidates‘ location searches if you do not attach placement schools to them.
Remove extra space before full stop at the end of sentence:
You can choose whether to show or hide the placements from candidates in Organisation details .
3. Attached schools notification banner Change position of full stop from:
Find out …

Action minor feedback changes on schools outcome

---

app/controllers/publish/courses/fields/where_you_will_train_controller.rb
app/helpers/find/where_you_will_train_helper.rb
app/views/find/courses/v2/_components.html.erb
app/views/find/courses/v2/_where_you_will_train.html.erb
app/views/publish/courses/_v2_description_content.html.erb
app/views/publish/courses/fields/where_you_will_train/edit.html.erb
spec/system/publish/courses/previews/course_preview_where_you_will_train_spec.rb

"Where you will train" is displayed in course preview and live in Find
- If it is rendered on Find, show only the published values for the fields
- If in preview, show the latest enrichment values regardless if they are published.
- If none of the values are present, show the missing information component
We only need to check the presence of the required fields, we omit the optional ones.

Where you will train displayed correctly in live and preview

---

app/decorators/course_decorator.rb
app/views/publish/courses/_v2_description_content.html.erb
config/locales/en/publish/providers/courses/description_content.yml

This is a bug that is also in V1 prior to the longform changes. The row for salaried courses was missing. If this does not get fixed before the new cycle rolled over courses could not change their salaried section
Adding salaried row to publish course as a row
Tested it already, just need a code review

[Longform] Adding Salary details to main page in publish

---

config/settings/sandbox.yml

As part of the launch of Candidate Accounts in production, we want to test that the One Login integration is working in production.
We can safely do this in Sandbox.

Enable One Login in Sandbox

---

config/settings/production.yml
config/settings/sandbox.yml

We're seeing an error of mismatched `issuer` in Sandbox. I can see our config does not have a `/` at the end of the issuer, I expect this change to work.
You can see what One Login expects by looking at their well-known configuration
https://oidc.integration.account.gov.uk/.well-known/openid-configuration
```json
{
...
"issuer": "https://oidc.integration.account.gov.uk/",
...
```

Add slash to end of One Login OAuth issuer

---

config/analytics.yml
config/analytics_blocklist.yml
config/analytics_hidden_pii.yml

We are removing the email address until we can confirm beyond doubt
that our recording of this information is reasonable unter data
protection policy. We may need to provide a privacy policy before we
can record such data.
Remove candidate email address from analytics until we can confirm it is acceptable to record  it with our current data protection guideline adherance.

Remove candidate email_address from analytics

---

db/data/20250917072746_update_applications_open_from.rb
spec/system/find/courses/apply_for_course_spec.rb

Some courses were created when the `RecruitmentCycle.applications_open_date` was set to September 7th.
These courses are now invalid and their dates need to be updated to October 7th 2026, the real date when apply opens.

Data migration to update applications_open_from

---

Gemfile
Gemfile.lock
config/database.yml

In order to do the optimisations for Find I need to create spatial fields and index them.
So we need to have available the postgis types to active record so the db/schema.rb is generated without problem. 
Otherwise we would have to change the schema format to sql...
This PR adds the postgis as adapter following [postgis readme](https://github.com/rgeo/activerecord-postgis-adapter)

Add postgis adapter gem

---

config/locales/en/publish/providers/providers.yml
spec/features/publish/edit_provider_details_2026_spec.rb

The 'Training with disabilities and other needs' row label in the 'Organisation details' tab should be 'Training with disabilities'
Change label text.

Update training with disabilities row label

---

app/services/find/cycle_timetable.rb
spec/services/find/cycle_timetable_spec.rb

The banners on Find are set to change dynamically depending on the time/date set in the cycle timetable. We recently noticed that the last banner switched over an hour later than expected due to the fact that the app/cycle timetable operates in UTC; locally we are currently in BST which is 1 hour ahead. 
We initially tried to rectify this by setting the application TimeZone to 'Europe/London', however we encountered a test failure that we wouldn't have expected to fail after making this change: https://github.com/DFE-Digital/publish-teacher-training/pull/5639
This PR updates the cycle timetable to use London local time for all key dates.
- Switch cycle timetable dates to `ActiveSupport::TimeZone["London"]` to ensure deadlines follow UK local time (BST/GMT) while the app continues to run …

Use London time zone for cycle timetable dates

---

config/settings.yml
spec/features/publish/courses/editing_course_start_spec.rb
spec/features/publish/courses/editing_design_technology_spec.rb
spec/features/publish/courses/editing_visa_sponsorship_spec.rb
spec/features/publish/courses/new_design_technology_spec.rb

We are not using `Settings.current_recruitment_cycle_year` anymore and we need to remove any references from the codebase.
Remove all `Settings.current_recruitment_cycle_year`

Remove Settings.current_recruitment_cycle_year from tests

---

app/views/find/pages/cycle_has_ended.html.erb

Find closed is now in the new cycle so the dates in the find down template should reference years one fewer than they did before.
Deduct 1 year from all the dates in the find closed screen to match it's place in the new cycle.

Correct the dates for find closes screen

---

app/components/find/courses/entry_requirements_component/view.rb
spec/features/find/course/viewing_a_further_education_course_spec.rb

On the course show page, the text describing what GCSE requirements are necessary for Further Education courses is missing.
- Add the text for GCSE requirements to Further Education courses
- Add test for viewing a Further Education course
|Before|After|
|---|---|
|<img width="771" height="566" alt="image" src="https://github.com/user-attachments/assets/4217579b-591e-4dc4-910f-25b8286a55f3" />|<img width="920" height="537" alt="image" src="https://github.com/user-attachments/assets/233d6270-259a-429f-ab89-8eafe71e6322" />|

Add GCSE requirements text to Further Education course

---

app/lib/feature_flag.rb
spec/lib/feature_flag_spec.rb

When a FeatureFlag is activated or deactivated in production we send a
Slack Notification. The URL helper in the FeatureFlag class threw an
error until we fully scoped it to the routes.url_helpers
Resolve the Sentry error on release
https://dfe-teacher-services.sentry.io/issues/6844627102/?alert_rule_id=11137790&alert_type=issue&notification_uuid=2ea51dc8-936a-4e83-93ed-7628bfd8729b&project=1377944&referrer=slack
When using route helpers in lib directory, use full namespace

FeatureFlags don't raise error in production and send Slack notification

---

config/settings/production.yml

Must remove the trailing slash from the config to match the config on
OneLogin
`https://find-teacher-training-courses.service.gov.uk`
not
`https://find-teacher-training-courses.service.gov.uk/`
Logging out of One Login doesn't redirect users successfully to the root url in find unless the urls match exactly
```
error_description=client%20registry%20does%20not%20contain%20post_logout_redirect_uri
```

Correct the production OneLogin post logout url

---

spec/services/courses/query_spec.rb

The provider code is generated by the factory in the test suite. If we set the provider code on a test subject explicitly we risk conflicting with one that was generated.
```log
Failures:
1) Courses::Query.call when searching excluding courses excludes specified courses from the results
Failure/Error: provider: create(:provider, provider_code: "P99"))
ActiveRecord::RecordInvalid:
Validation failed: Provider code Provider code already taken
Finished in 49.64 seconds (files took 9.06 seconds to load)
220 examples, 1 failure
Failed examples:
rspec ./spec/services/courses/query_spec.rb:598 # Courses::Query.call when searching excluding courses excludes specified courses from the results
```

Avoid explictly setting Provider code to avoid uniqueness errors

---

config/initializers/sentry.rb

The fitlering on our Sentry implementation is filtering out imporant information captured by the Omniauth gem.
Without this logging information we cannot understand the error and so we cannot fix it.
Removing error filtering on "One Login Error"

Skip Sentry filtering on One Login failure
