DFE-Digital/publish-teacher-training

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Add issue and pull request templates
> Add Github Templates

- .travis.yml
Update travis to deploy to Azure and not Heroku.
Note: We need to create the environments on Azure.
> Update travis deploy

- app/controllers/application_controller.rb
- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
- spec/features/sign_in_spec.rb
- spec/features/view_pages_spec.rb
Setup properly for prod
- Remove placeholder text on homepage
- Ensure we force sign on entry to mimic `manage-courses-ui`
- You should be redirected to signin on page load
- Homepage should contain any content
> Update auth flow

- .travis.yml
This allows us to deploy using Docker instead of localgit.
- Delete previous deploy section
- Pull in the `docker` integration on Travis
- On success on the `master`, `staging`, or `prod` branches, build a docker image (tagged with the branch name) and push it to our private container registry
Review without whitespace changes.
I've tested this locally by running the commands manually, but the real test is when we merge this if it successfully gets picked up.
There's quite a lot of duplication of the `batdevcontainerregistry` name but I'm cool with it because I think we'll revisit this very soon™.
> Build and push docker images on successful build

- .travis.yml
- Dockerfile
This removes a duplicate bundle etc that was happening outside the container
> Run tests in docker

- .travis.yml
- docker-push.sh
Needs to be in separate script it seems
> Fix deploy command

- config/initializers/canonical_rails.rb
Fixes #19 
Update canonical meta to match service domain 
Check canonical meta tag
> Update canonical meta tag

- app/assets/stylesheets/_cookie-banner.scss
- app/assets/stylesheets/application.scss
- app/javascript/packs/application.js
- app/javascript/scripts/cookie-banner.js
- app/views/layouts/application.html.erb
- app/views/pages/cookies.html.erb
- config/application.rb
Fixes #18 
- Update cookie policy
- Add cookie banner
- Add Google Analytics
- Add no follow robots meta tag
Check `/cookies` and the cookie banner displays
> Udpate cookie policy

- README.md
- config/initializers/omniauth.rb
Token and Refresh token is not being returned
Supply prompt consent 
remove redundant call to super in callback_phase
verify access_token contains token and refresh_token
> supply the prompt consent to ensure refresh token comes back from OIDC

- .travis.yml
The previous syntax doesn't actually work.
> Fix the deploy regexp

- .travis.yml
> Fix the travis deploy condition

- Gemfile
- Gemfile.lock
- config.ru
Logging errors on Azure
Add application_insights
> Setup application insights

- Dockerfile
Going alpine
Gone alpine
I think there maybe some weird race condition in the docker-compose.yml
@tvararu can actually give it proper thrashing
> Going alpine

- .rspec
- Gemfile
- README.md
- azure-pipelines.yml
- azure/template.json
This PR enables support for Azure Pipelines build and release.
* Add ARM templates
* Add azure-pipelines.yml
* Use dockerhub to store images
* Use RspecJunitFormatter to expose and publish test results
* Check build badge
* Check if you are happy with the build config
> Add support for AZ Pipelines

- azure-pipelines.yml
Bring inline with manage-courses-backend
* Build all branches
* Don't build PRs
* Check azure-pipelines.yml
* Build is green for any branch
> Include all branches and not PRs

- azure/template.json
This PR aligns ARM template conventions with our guidelines and preferred styles
* Update template variables
* Add resourceEnvironment and serviceName parameters
> Align arm template conventions

- azure/template.json
Aligning app settings with legacy dev
New app settings for manage courses backend URL, manage UI URL and settings auth secret
Pre-merge tasks
> New manage app settings

- Gemfile
- Gemfile.lock
- README.md
Setup Sentry
Add Sentry gem and readme instructions
`SENTRY_DSN=URL_FROM_SENTRY_UI rails server`
> Setup sentry

- Gemfile
- Gemfile.lock
- app/controllers/pages_controller.rb
- app/controllers/providers_controller.rb
- app/helpers/view_helper.rb
- app/models/provider.rb
- app/views/pages/home.html.erb
- app/views/providers/_provider.html.erb
- app/views/providers/index.html.erb
- config/routes.rb
- spec/features/sign_in_spec.rb
- spec/features/view_pages_spec.rb
- spec/helpers/view_helper_spec.rb
- spec/spec_helper.rb
- spec/support/feature_helpers.rb
Show list of organisations
Create `providers#index`
`/organisations`
> [960] Add organisations index view

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
duplicated json stringifying payload
Removed duplicated json stringifying payload
https://github.com/DFE-Digital/manage-courses-backend/pull/173
> [993] Removed duplicated json stringifying payload

- app/views/errors/forbidden.html.erb
- app/views/errors/internal_server_error.html.erb
- app/views/errors/not_found.html.erb
- app/views/layouts/application.html.erb
- app/views/providers/index.html.erb
- Add beta phase banner
- Remove `main` element from layout
> Add phase banner

- app/models/provider.rb
- app/views/providers/_provider.html.erb
Replicate https://bat-dev-manage-courses-ui-app.azurewebsites.net/organisations
Add course count below each org name
`/organisations`
> Add course count to org list

- app/views/providers/_provider.html.erb
- spec/features/providers_spec.rb
https://github.com/DFE-Digital/manage-courses-frontend/pull/49
Add missing spec
`rake spec` or `rspec`
> [960] Add missing providers spec

- README.md
- config/settings.yml
Working in development with new config gem
Help developers run the app locally
> Add dfe secret instructions to readme

- app/controllers/providers_controller.rb
- app/views/providers/_provider.html.erb
- app/views/providers/show.html.erb
- config/routes.rb
- spec/features/providers_spec.rb
- spec/features/sign_in_spec.rb
- spec/fixtures/provider-A0.json
- spec/fixtures/providers.json
- spec/support/feature_helpers.rb
Replica of the current c# ui 🤓 
Add org show view
> [1096] Add org show

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- spec/controllers/application_controller_spec.rb
issues whereby the user has circumvented session create hence the user is half authenticated
Fixed issues whereby the user has circumvented session create hence the user is half authenticated
> [1124] Fixed issues whereby the user has circumvented session create hence the user is half authenicated

- app/controllers/courses_controller.rb
- app/models/course.rb
- app/models/provider.rb
- app/models/site.rb
- app/models/site_status.rb
- app/views/courses/vacancies.html.erb
- config/routes.rb
- spec/factories/courses.rb
- spec/features/courses_spec.rb
`providers#course#vacancies`
- Add course vacancies edit view
> [1136] setup course vacancies view

- app/helpers/view_helper.rb
- app/views/courses/_course_table_row.html.erb
- spec/features/courses/index_spec.rb
Now that the environment variable is defined, we can update the URL.
> [1210] Fix Find URL on courses table

- app/controllers/sites_controller.rb
- app/models/provider.rb
- app/views/providers/show.html.erb
- app/views/sites/_site.html.erb
- app/views/sites/index.html.erb
- config/routes.rb
- spec/factories/providers.rb
- spec/features/locations_spec.rb
Provider locations
Add locations :)
> [1233] Add locations

- app/models/provider.rb
Revert change made here https://github.com/DFE-Digital/manage-courses-frontend/pull/134
/organisations
> Hot fix org index

- app/models/provider.rb
- spec/features/providers_spec.rb
- spec/features/sign_in_spec.rb
Temp measure to disable specs on provider index whilst we do a long term fix for the factories
> Hotfix providers index

- app/models/provider.rb
- spec/factories/providers.rb
- spec/features/providers_spec.rb
- spec/features/sign_in_spec.rb
- spec/support/mock_jsonapi_serializable.rb
Somehow JSON parsing the object returned by the factory returned
something vaguely similar to what we actually expected, so tests still
passed. This wasn't at all what we should be getting back from the API
though.
This commit fixes that.
> Attempt to fix provider list factory

- app/controllers/courses_controller.rb
- app/views/courses/show.html.erb
- spec/features/courses/show_spec.rb
`courses#show`
Setup basic scaffolding for `courses#show`
> [1244] Setup course show page

- app/helpers/course_helper.rb
- app/views/courses/_course_table_row.html.erb
- spec/factories/courses.rb
- spec/features/courses/index_spec.rb
- spec/helpers/course_helper_spec.rb
> [1210] Add ucas_status to courses table

- app/controllers/pages_controller.rb
- app/views/pages/guidance.html.erb
- spec/features/view_pages_spec.rb
> Dont require auth for guidance page

- azure/template.json
UCAS env release broken. This is the fix. 
Adding handle on custom domain name to stop it borking where no custom host name is being used.
erm...
> Add condition to app service certificate deployment

- app/views/layouts/application.html.erb
Follow-up to https://github.com/DFE-Digital/manage-courses-frontend/pull/144#discussion_r272077126
> [1241] Tweak mailto subject

- app/controllers/courses_controller.rb
Course table ordering
- Sort by code after name
> [1285] Update course table ordering

- app/views/sites/_site.html.erb
Editing locations
Fix edit site link
`/organisations/XXX/locations`
> Fix location edit link

- app/views/courses/vacancies/edit.html.erb
- spec/features/courses/vacancies/edit_spec.rb
> [1237] Switch edit course vacancies links to mc-fe

- app/controllers/courses/vacancies_controller.rb
- spec/features/courses/vacancies/edit_spec.rb
> [1157] Return user to courses index after editing vacancies

- app/views/courses/_course_table_row.html.erb
- spec/features/courses/index_spec.rb
Find column on course table (courses#index)
Expand on content when a course is not "findable"
/courses
> [1238] Update findable column on courses table

- app/controllers/sites_controller.rb
- app/views/sites/edit.html.erb
- spec/features/locations/edit_spec.rb
- Display the old location name when it is changed
- Add better error message for location name uniqueness
> [1294] Snagging

- app/controllers/courses_controller.rb
> HOTFIX: Fix courses index

- app/views/providers/show.html.erb
- app/views/sites/index.html.erb
You can add and edit locations now
> Tweak location content on organisation page

- app/views/providers/show.html.erb
- app/webpacker/stylesheets/application.scss
Make support easier to find for providers.
Port related styles from manage-courses-ui:
https://github.com/DFE-Digital/manage-courses-ui/blob/b5284ed7c1c4bea7d29c1c7e14c62f2e193b32b2/src/ui/Assets/Styles/components/_related.scss
> Add support and guidance section

- package.json
- yarn.lock
Lightly tested this, it shouldn't have breaking changes, only additions and bug fixes.
:shipit:
> [XXXX] Update govuk-frontend

- app/views/courses/show.html.erb
> [XXXX] Use abbreviation for SEND in courses page

- app/views/courses/show.html.erb
- app/webpacker/stylesheets/application.scss
Editing basic course details
Add information for providers who want to edit "running" courses
> [1341] Add course editing status box

- app/models/course.rb
- app/views/courses/show.html.erb
Editing a "new" course
Update content
> [1343] Update course status box for new courses

- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/show.html.erb
- spec/features/courses/show_spec.rb
This PR (https://github.com/DFE-Digital/manage-courses-frontend/pull/205) is getting too big
Clean up `courses#show` - basic details
No difference
> [XXXX] Clean up course show view and specs

- Procfile.dev
- README.md
- config/puma.rb
- lib/tasks/dev_ssl_generator.rake
Removes one step from the initial setup.
> [XXXX] Make puma auto-generate SSL certificates

- app/controllers/users_controller.rb
We are not entirely sure how this works without this.
> [XXXX] Add authenticate to users controller

- app/helpers/application_helper.rb
- app/views/courses/_description_content.html.erb
- app/views/courses/_status_panel.html.erb
- app/views/courses/description.html.erb
- app/webpacker/stylesheets/application.scss
- spec/factories/courses.rb
- spec/features/courses/description_spec.rb
- spec/helpers/application_helper_spec.rb
- spec/site_prism/page_objects/page/organisations/course_description.rb
Course published status
Add published status panel to the description page
> Ignore white space
> [1255] add publishing panel

- Gemfile
- Gemfile.lock
- app/controllers/courses_controller.rb
- app/decorators/application_decorator.rb
- app/decorators/course_decorator.rb
- app/helpers/application_helper.rb
- app/models/base.rb
- app/views/courses/_status_panel.html.erb
- spec/decorators/course_decorator_spec.rb
- spec/helpers/application_helper_spec.rb
- Add and setup draper
- Convert `formatted_date` to draper method
- Hide `last_published_date` if nil as this doesn't seem relevant to display when `nil`
Examples
- Happy Paths  `https://localhost:3000/organisations/2AT/courses/35L5/description`
- Sad path `https://localhost:3000/organisations/2HO/courses/3B7S/description`
> [1370] Add draper

- app/controllers/sessions_controller.rb
- app/decorators/course_decorator.rb
- app/models/provider.rb
- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/_course_table_row.html.erb
- app/views/courses/index.html.erb
- app/views/sites/_site.html.erb
- app/views/sites/index.html.erb
- spec/factories/providers.rb
- spec/factories/users.rb
- spec/features/courses/index_spec.rb
- spec/features/locations/index_spec.rb
- spec/features/sign_in_spec.rb
All providers are now `opted_in`
Remove `opted_in`
> [1418] Remove opted_in

- app/controllers/courses_controller.rb
- app/models/course.rb
- app/views/courses/status_panel/_unpublished.html.erb
- config/routes.rb
- spec/requests/courses_spec.rb
Course publishing in the new world aka rails
Add publishing ability
- View any "unpublished" course and click "publish"
> [1396] Add course publishing

- config/environments/new_qa.rb
- config/settings/new_qa.yml
- config/webpacker.yml
Add new QA environment and settings to support testing
New rb and yml files and update of webpacker
> Add newqa env

- app/controllers/application_controller.rb
- azure/template.json
- config/settings.yml
- config/settings/development.yml
- spec/controllers/application_controller_spec.rb
`SETTINGS__AUTHENTICATION__SECRET`
`SETTINGS__AUTHENTICATION__SECRET`
renamed to 
`SETTINGS__MANAGE_BACKEND__SECRET` for the consumer end
You need approve the respective PR as well as this one
> [1440] Fixed aligned secrets

- app/views/courses/vacancies/edit.html.erb
- app/views/courses/withdraw.html.erb
UCAS now refresh from our API more frequently.
> Copy changes around Apply refresh timescales.  

- app/views/courses/delete.html.erb
- app/views/courses/withdraw.html.erb
Withdraw / delete course
Add "back" links
`CORUSE_CODE/withdraw`
`CORUSE_CODE/delete`
> [XXXX] Add missing backlinks to delete and withdraw

- app/controllers/courses_controller.rb
- app/views/courses/fees.html.erb
- app/webpacker/stylesheets/_currency-input.scss
- app/webpacker/stylesheets/application.scss
- config/routes.rb
- spec/features/courses/fees_spec.rb
- spec/site_prism/page_objects/page/organisations/course_fees.rb
Re-creating `/organisation/2cf/course/self/2yn6/fees` in rails
Add `/fees` to a course
> This is a "dumb" read only form at present because there is some backend work todo 
c# | rails
:--:|:--:
> 1463 add courses fees page

- app/controllers/courses_controller.rb
- app/helpers/course_helper.rb
- app/helpers/view_helper.rb
- app/views/courses/_description_content.html.erb
- app/views/courses/description.html.erb
- app/webpacker/stylesheets/application.scss
- spec/factories/errors.rb
- spec/features/courses/description_spec.rb
- spec/helpers/course_helper_spec.rb
- spec/helpers/view_helper_spec.rb
- spec/requests/courses_spec.rb
- spec/site_prism/page_objects/page/organisations/course_description.rb
Implement validation messages for publishing a course.
- Parse and display errors from backend
- Deep link to manage-courses-ui from the errors
> [1404] Added basic validation message

- app/controllers/courses_controller.rb
- app/views/courses/_related_sidebar.html.erb
- app/views/courses/about.html.erb
- app/views/courses/requirements.html.erb
- app/webpacker/stylesheets/application.scss
- spec/features/courses/requirement_spec.rb
- spec/features/courses/requirements_spec.rb
- spec/requests/courses/requirements_spec.rb
Copying course requirementscontent
Add "Copy from" select to enable users to copy content from another course within their org
Example - `/organisations/2AT/courses/3CXD/requirements`
> 1477 copy course requirements

- app/controllers/courses_controller.rb
- app/views/courses/_course_length.html.erb
- app/views/courses/fees.html.erb
- spec/features/courses/fees_spec.rb
- spec/requests/courses/fees_spec.rb
Copying course length and fees content
Add "Copy from" select to enable users to copy content from another course within their org
Example - `/organisations/2AT/courses/3CXD/fees`
> [1475] Copy length and fees

- app/views/courses/_copy_content_warning.html.erb
- app/views/courses/about.html.erb
- app/views/courses/fees.html.erb
- app/views/courses/requirements.html.erb
- app/views/courses/salary.html.erb
Cleaner code
Move copy content warning into partial to avoid duplicated code
No visual or functional change, just DRYer code.
> [1500] Move copy content warning into partial

- app/controllers/sites_controller.rb
- app/helpers/provider_helper.rb
- app/views/sites/index.html.erb
- config/settings.yml
- spec/factories/providers.rb
- spec/features/sites/new_spec.rb
- spec/helpers/provider_helper_spec.rb
- spec/site_prism/page_objects/page/locations_page.rb
Hooks up the form created in https://github.com/DFE-Digital/manage-courses-frontend/pull/283.
To be rebased and merged after that.
> [1495] Change add location button to link to form

- azure-pipelines.yml
Reduce build time by implementing layer caching
Add task to push master builds as latest tags
Add task to pull latest tag for each build
> Implement layer caching

- app/controllers/courses_controller.rb
- app/views/courses/preview.html.erb
- app/webpacker/stylesheets/application.scss
- config/routes.rb
- spec/features/courses/preview_spec.rb
- spec/site_prism/page_objects/page/organisations/course_preview.rb
Course preview part 1
Setup course#preview scaffolding
> [1483] Setup course preview page

- app/models/site.rb
- app/views/courses/preview.html.erb
- app/views/courses/preview/_apply.html.erb
- spec/factories/site_statuses.rb
- spec/factories/sites.rb
- spec/features/courses/preview_spec.rb
- spec/site_prism/page_objects/page/organisations/course_preview.rb
Course preview
Add apply section with `sites` and `site_statuses`
> [1483] Add apply section to course preview

- app/decorators/course_decorator.rb
- app/helpers/application_helper.rb
- app/lib/govuk/markdown_renderer.rb
- app/views/courses/preview.html.erb
- app/views/courses/preview/_apply.html.erb
- app/views/courses/preview/_interview_process.html.erb
- app/webpacker/stylesheets/application.scss
- spec/features/courses/preview_spec.rb
- spec/lib/govuk/markdown_renderer_spec.rb
- spec/site_prism/page_objects/page/organisations/course_preview.rb
Course preview page
Minor improvements based on current implementation
| old  | new  |
|---|---|
| ![bat-dev-manage-courses-ui-app azurewebsites net_organisation_13e_course_self_3bqq_preview(Laptop with MDPI screen)](https://user-images.githubusercontent.com/3071606/58636080-61b7c300-82e7-11e9-8ec5-75b8311fd4c3.png) | ![localhost_3000_organisations_13e_courses_3bqq_preview(Laptop with MDPI screen)](https://user-images.githubusercontent.com/3071606/58636090-67ada400-82e7-11e9-8aac-82b22e4de644.png) |
> 1438 improve course preview page

- app/views/courses/preview.html.erb
- app/views/courses/status_panel/_unpublished.html.erb
Course preview
Update course preview link to use our new rails version
View any course that's new or in draft i.e. `/organisations/13E/courses/38HN/description`, then click preview
> [1569] Update course preview link

- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/_entry_requirements.html.erb
- spec/factories/courses.rb
- spec/features/courses/show_spec.rb
- spec/site_prism/page_objects/page/organisations/course.rb
Course minimum GSCE requirements
Render "Course minimum GSCE requirements" on course basic page 
Example - `/organisations/2CG/courses/2YXH`
> [#1526] Show course entry requirements

- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/_entry_requirements.html.erb
- spec/features/courses/show_spec.rb
- spec/site_prism/page_objects/page/organisations/course.rb
* Use one row and list all subjects
* Combine each description into one paragraph and remove confusing lists
* Add a section to explain, and list all the possible codes
* Use the UCAS code description alongside the number for easy reference
|-|-|
|![Screen Shot 2019-06-05 at 15 25 27](https://user-images.githubusercontent.com/319055/58964057-2a915800-87a6-11e9-9e96-a046d0dcaf2a.png)| ![Screen Shot 2019-06-05 at 15 26 10](https://user-images.githubusercontent.com/319055/58964119-47c62680-87a6-11e9-9579-ec6a9d6e4172.png)|
> [1526] Combine UCAS requirements into one row

- config/environments/new_staging.rb
- config/settings/new_staging.yml
- config/webpacker.yml
Add rails env and settings for new staging environment
Addition of env, setting files and update to webpacker
> Add new_staging rails env

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/show_spec.rb
- spec/site_prism/page_objects/page/organisations/course.rb
Link to the edit locations screen if a provider has more than one site
- Add tests for change link
- Add tests for manage all locations link
> [1512] Add link to edit locations

- app/views/courses/_basic_details_tab.html.erb
Link to change locations on courses is broken.
Fix the link
This still needs a feature spec.
> [1512] Fix the Change link for course locations

- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/index.html.erb
- app/views/pages/new_features.html.erb
- app/views/providers/show.html.erb
- app/views/sites/edit.html.erb
- app/views/sites/index.html.erb
- app/views/sites/new.html.erb
Providers can now self-serve, we don't need them to contact us. Instead signpost them in the right direction.
- Point to basic details tab on course pages
- Update features list
- Link to videos of features
> [1630] Update guidance on assigning locations

- app/helpers/view_helper.rb
- app/views/layouts/_beta-banner.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
- app/webpacker/stylesheets/_environments.scss
- app/webpacker/stylesheets/application.scss
- config/settings.yml
- config/settings/development.yml
- config/settings/new_qa.yml
- config/settings/new_staging.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
- config/settings/test.yml
- spec/features/view_pages_spec.rb
Make it harder for the team to accidentally make changes in production.
Use different styles and labels for:
- QA
- Staging
- Development
- Production
Production styles remain unchanged
> Label environments

- app/views/courses/description.html.erb
- app/views/courses/index.html.erb
- app/views/courses/show.html.erb
- app/views/providers/show.html.erb
- app/views/sites/edit.html.erb
- app/views/sites/index.html.erb
- app/views/sites/new.html.erb
Courses are more frequently changed.
> Move locations below courses

- app/views/courses/_course_length.html.erb
Course length wasn't being posted to the backend properly so it the data wasn't being saved
Re-factor form to handle 1year, 2years and "Other"
No visual change.
Note: We need to address the backend to save the "other" value correctly.
> [1629] Fix up course length

- app/models/course.rb
- app/views/courses/fees.html.erb
- spec/features/courses/description_spec.rb
- spec/features/courses/fees_spec.rb
- spec/requests/courses/fees_spec.rb
UK and International Fees
Specifical set UK and International fees to integer
Post should not be a string
> [1623] Update uk and international fee data type

- app/views/courses/_course_length.html.erb
- app/views/courses/about.html.erb
- app/views/courses/fees.html.erb
- app/views/courses/requirements.html.erb
- app/views/courses/salary.html.erb
- app/views/shared/_form_field.html.erb
This allows them to display the validation error red highlight. `course_length` is treated as a special case.
> [1624] Wrap all enrichment fields with form component

- azure-pipelines.yml
- azure/template.json
Enable App Service Logs for the service.
Add a resource deployment to the apps ARM template that references the App Service Log building block.
> 80 enable app service logs

- app/views/pages/guidance.html.erb
A second guidance video has been created and needs to be added to the guidance. This PR adds this video and transcript and also tweaks the wording of the guidance. 
- Add second video
- Add transcript
- Small tweaks to the wording of the guidance
> [1637] Amend guidance and add second guidance video/transcript

- app/views/courses/about.html.erb
- app/views/courses/fees.html.erb
- app/views/courses/requirements.html.erb
- app/views/courses/salary.html.erb
- app/webpacker/packs/application.js
- spec/features/courses/about_spec.rb
- spec/features/courses/fees_spec.rb
- spec/features/courses/requirements_spec.rb
- spec/features/courses/salary_spec.rb
- spec/site_prism/page_objects/page/organisations/course_about.rb
- spec/site_prism/page_objects/page/organisations/course_fees.rb
- spec/site_prism/page_objects/page/organisations/course_requirements.rb
- spec/site_prism/page_objects/page/organisations/course_salary.rb
We shouldn't show the "You have unsaved changes" warning when a user tries to save their changes.
- Copy course content on an enrichment page
- Try to click save
> Don't warn users about unsaved changes on save

- app/controllers/recruitment_cycles_controller.rb
- config/routes.rb
- spec/requests/courses/about_spec.rb
- spec/requests/courses/fees_spec.rb
- spec/requests/courses/requirements_spec.rb
- spec/requests/courses/salary_spec.rb
- spec/requests/courses/vacancies/edit_spec.rb
- spec/requests/recruitment_cycles_spec.rb
- spec/requests/sites_spec.rb
Redirect old URL's to new URL's
Redirects
🚢
> [1648] Redirect legacy urls to include recruitment cycle

- app/helpers/course_helper.rb
- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/_course_table.html.erb
- app/views/courses/_course_table_row.html.erb
- app/views/courses/_related_sidebar.html.erb
- app/views/courses/_status_panel.html.erb
- app/views/courses/preview.html.erb
- app/views/courses/preview/_about_course.html.erb
- app/views/courses/preview/_about_schools.html.erb
- app/views/courses/preview/_about_the_provider.html.erb
- app/views/courses/preview/_entry_requirements_qualifications.html.erb
- app/views/courses/preview/_fees.html.erb
- app/views/courses/preview/_salary.html.erb
- app/views/courses/preview/_train_with_disabilities.html.erb
- app/views/layouts/application.html.erb
- app/views/providers/show.html.erb
- app/webpacker/stylesheets/_cookie-banner.scss
- app/webpacker/stylesheets/application.scss
- spec/helpers/course_helper_spec.rb
- spec/site_prism/page_objects/page/organisations/courses.rb
Add `app-` to classes that aren't from the GOV design system
> [1742] Refractor CSS class 

- app/views/pages/new_features.html.erb
The new features does not currently give a detailed forecast for future feature roll out
> [1737] Update new features guidance

- app/views/courses/sites/edit.html.erb
- app/views/layouts/_flash.html.erb
- app/views/shared/_errors.html.erb
- app/webpacker/packs/application.js
Updates from product review.
- Updated error messages to have `data-ga-event-form`
- Added `data-error-message` to errors
- Changed `form-publish` to `form-submitted`
> [1748] Updates to "Record the form error messages to GA"

- config/settings/qa.yml
Updated environment variable rollover to false in qa.yml file to bring it inline with production env settings
Add rollover: false in file qa.yml
> Adding rollover false to qa yaml file

- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/_related_sidebar.html.erb
- app/views/courses/about.html.erb
- app/views/courses/fees.html.erb
- app/views/courses/requirements.html.erb
- app/views/courses/salary.html.erb
- app/views/courses/show.html.erb
- app/views/providers/show.html.erb
Fixed accessibility issues and tidy up semantic HTML
> [1764] Accessibility testing and semantic updates

- config/settings/new_prod.yml
Add config bits for new production env
Add config for database and rails env
- created config/settings/new_prod.yml file
> Added new production environment config in .yml file

- config/settings/qa.yml
> [1654] Flip on rollover flag in QA

- app/views/pages/rollover.html.erb
Point to GOV.UK article for clarification.
> Mention changes to skills test on the rollover screen

- app/controllers/providers_controller.rb
- app/views/providers/contact.html.erb
- app/views/shared/_form_field.html.erb
- config/routes.rb
- spec/features/providers/contact_spec.rb
- spec/site_prism/page_objects/page/organisations/organisation_contact.rb
Move 'contact details' form from C# to rails
Page and test, nothing special, nothing hooked up yet.
:shipit:
> [1780] Create provider contact page

- app/helpers/view_helper.rb
`qualifications` vs `required qualifications`
Fix up qualifications error link when a user tried to publish an invalid
🚢
> [1747] Update required qualifications error message

- app/views/courses/_basic_details_tab.html.erb
- app/views/pages/new_features.html.erb
- Rollover is done
- UCAS eligibility is done
- Remove July section
- Indicate that eligibility can now be edited directly
> [1692] Update new features page

- app/controllers/courses_controller.rb
- app/views/courses/delete.html.erb
- config/routes.rb
- spec/features/courses/destroy_spec.rb
- spec/requests/courses/delete_spec.rb
Deleting courses
Add real course delete functionality
`/organisations/:provider_code/2019/courses/:course_code/delete`
> [1812] Setup course delete

- app/decorators/course_decorator.rb
- app/views/courses/_basic_details_tab.html.erb
- spec/factories/courses.rb
- spec/features/courses/details_spec.rb
- spec/site_prism/page_objects/page/organisations/course_details.rb
New age range
Add new age range (years) to basic details
> [1845] Add age range to basic details

- app/controllers/application_controller.rb
- app/controllers/courses_controller.rb
- app/controllers/providers_controller.rb
- app/controllers/recruitment_cycles_controller.rb
- app/controllers/sites_controller.rb
- app/models/base.rb
- app/models/course.rb
- app/models/provider.rb
- app/views/providers/about.html.erb
- app/views/providers/contact.html.erb
- app/views/providers/details.html.erb
- config/routes.rb
- spec/controllers/providers_controller_spec.rb
- spec/factories/errors.rb
- spec/features/providers/about_spec.rb
- spec/features/providers/contact_spec.rb
- spec/features/providers/details_spec.rb
- spec/features/sign_in_spec.rb
- spec/helpers/view_helper_spec.rb
- spec/site_prism/page_objects/page/organisations/organisation_about.rb
- spec/site_prism/page_objects/page/organisations/organisation_contact.rb
Prerequisite: https://github.com/DFE-Digital/manage-courses-frontend/pull/486
Moving provider enrichment editing to Rails from C#.
- Hooks `#update` method with backend
- Creates `#publish` method, adds button to trigger it
Known issues:
- "Contact address" does not get highlighted with an error message, this will be addressed in a separate PR
Review commit by commit. 🤞
> [1792] Provider enrichment validations

- app/controllers/concerns/edit_basic_detail.rb
- app/controllers/courses/age_range_controller.rb
- app/decorators/course_decorator.rb
- app/views/courses/age_range/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/factories/courses.rb
- spec/features/courses/age_range_in_years/edit_spec.rb
- spec/features/courses/details_spec.rb
- spec/site_prism/page_objects/page/organisations/course_age_range.rb
Edit course age range
Enable editing of course age range
`/organisations/<PROVIDER_CODE>/2019/courses/<COURSE_CODE>/age-range`
> [1846] Allow editing of course age range in years

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/age_range_in_years/edit_spec.rb
- spec/features/courses/details_spec.rb
- spec/site_prism/page_objects/page/organisations/course_details.rb
Course age range
Add the "change" link
🚢
> [1846] add change age range link

- app/views/courses/_basic_details_tab.html.erb
- app/views/pages/new_features.html.erb
We are shipping things, stuff's out of date yo
- Updates content in basic details sidebar and features page
:shipit:
> [1907] Update content about available features

- app/controllers/providers_controller.rb
- app/views/providers/about.html.erb
- app/views/providers/details.html.erb
- app/views/shared/_form_field.html.erb
- spec/factories/providers.rb
- spec/features/providers/about_spec.rb
- spec/site_prism/page_objects/page/organisations/organisation_details.rb
~❗️  Cannot be merged until https://github.com/DFE-Digital/manage-courses-backend/pull/680 is done ❗️~
> [1807] Add accrediting_providers to provider enrichment form

- app/controllers/access_requests_controller.rb
- app/controllers/sites_controller.rb
- app/models/access_request.rb
- app/views/access_requests/new.html.erb
- app/views/sites/_form.html.erb
- app/views/sites/edit.html.erb
- app/views/sites/new.html.erb
- config/routes.rb
- spec/factories/errors.rb
- spec/features/access_requests_spec.rb
Pull Request access for someone onto Rails
Adds the route, controller action, view, model, test.
¯\\\_\(ツ\)\_\/¯ :shipit:
Paired with @defong.
> [1909] Add page to create access requests

- app/webpacker/scripts/cookie-banner.js
Tidy up the `cookie-banner.js` where Code-climate has highlighted complexity
I've allowed `prettier` to format the file. The actual changes are on line [20](https://github.com/DFE-Digital/manage-courses-frontend/blob/333afbb9313e09680ca0727eb9328a4f9f5b5a8c/app/webpacker/scripts/cookie-banner.js#L20)
> [xxxx] cookie complexity tidy up

- app/controllers/providers_controller.rb
- app/views/providers/about.html.erb
- spec/features/providers/about_spec.rb
> [1926] Fix link for accredited bodies validation error link

- app/controllers/courses/start_date_controller.rb
- app/views/courses/start_date/edit.html.erb
- config/routes.rb
- spec/features/courses/start_date/edit_spec.rb
- spec/site_prism/page_objects/page/organisations/course_start_date.rb
Setup basic details edit page for course start dates
> [1855] setup course start dates edit

- app/views/providers/about.html.erb
> [1943] Fixed typo to Training with disabilities and other needs

- app/views/providers/about.html.erb
- app/views/providers/details.html.erb
> [1942] reorder about your organisation info

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/start_date/edit_spec.rb
Added back in the link & the test
> [1940] Add start date link & include test

- app/controllers/courses/applications_open_controller.rb
- app/decorators/course_decorator.rb
- app/models/course.rb
- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/applications_open/edit.html.erb
- config/environment.rb
- config/routes.rb
- spec/factories/recruitment_cycles.rb
- spec/features/courses/applications_open/edit_spec.rb
- spec/site_prism/page_objects/page/organisations/course_applications_open.rb
Edit the value of "Applications open"
> [1925] edit course applications open

- app/controllers/courses/send_controller.rb
- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/send/edit.html.erb
- config/routes.rb
- spec/features/courses/send/edit_spec.rb
- spec/site_prism/page_objects/page/organisations/send.rb
Edit course SEND value 
Requires https://github.com/DFE-Digital/manage-courses-backend/pull/710 to be deployed.
> [1881] edit course send

- app/controllers/courses/study_mode_controller.rb
- app/controllers/courses_controller.rb
- app/views/courses/_basic_details_tab.html.erb
- app/views/courses/request_change.html.erb
- app/views/courses/study_mode/edit.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/courses/study_mode/edit_spec.rb
- spec/site_prism/page_objects/page/organisations/course_details.rb
- spec/site_prism/page_objects/page/organisations/course_request_change.rb
- spec/site_prism/page_objects/page/organisations/course_study_mode.rb
Course study mode
Allow editing of study mode
i.e. `/organisations/1JA/2019/courses/2ZRL/full-part-time`
> Will need some content love from Mr Genders -
> [1899] Allow editing of study mode

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/applications_open/edit_spec.rb
:ship: 
:ship: 
:ship: 
reversal of #530
> [1978] Amended  re-enable editing applications open from

- app/controllers/errors_controller.rb
- app/controllers/providers_controller.rb
- app/controllers/sessions_controller.rb
- app/views/errors/unauthorized.html.erb
- config/routes.rb
- spec/controllers/errors_controller_spec.rb
- spec/controllers/providers_controller_spec.rb
- spec/requests/providers_spec.rb
Unauthorized users
Add `/401` page and route as per manage courses ui
🚢
> [1983] Add unauthorized route, action and page

- app/views/courses/_basic_details_tab.html.erb
- app/views/pages/new_features.html.erb
> [2008] update new features and sidebar

- app/controllers/courses_controller.rb
- spec/features/courses/new_spec.rb
- spec/support/helpers.rb
New course action
Add new course action
🏅
> [1937] Add new course action

- app/controllers/courses_controller.rb
- app/views/courses/confirmation.html.erb
- config/routes.rb
- spec/features/courses/confirmation_spec.rb
- spec/site_prism/page_objects/page/organisations/course_confirmation.rb
New course confirmation page
- Setup confirmation page
👷
> [1958] Setup new course confirmation page

- .gitignore
> [xxxx] Added IDE items to be ignored

- app/views/courses/_basic_details_tab.html.erb
:ship: 
Fixed link for PE allocations
:ship:
> [2028] Fixed link for PE allocations

- app/controllers/courses/study_mode_controller.rb
- app/views/courses/study_mode/_form_fields.html.erb
- app/views/courses/study_mode/edit.html.erb
- app/views/courses/study_mode/new.html.erb
- config/routes.rb
- spec/factories/courses.rb
- spec/features/courses/study_mode/edit_spec.rb
- spec/features/courses/study_mode/new_spec.rb
- spec/site_prism/page_objects/page/organisations/courses/new_study_mode_page.rb
new page for course full or part time
Add new page for course full or part time
New endpoints for study mode
-  study_mode/new
-  study_mode/continue
Added course edit_options for study_modes in the course factory
> [2025] Add new page for course full or part time

- config/routes.rb
Kill C#
Redirect legacy URL's from `manage-courses-ui` 
🚢
> [2043] redirect legacy urls

- README.md
> [xxxx] Removed greenkeeper badge

- app/controllers/application_controller.rb
- config/settings.yml
- config/settings/development.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
- config/settings/test.yml
- spec/controllers/sessions_controller_spec.rb
Kill  C#
Redirect to authorized instead of manage courses ui
🚢
> [2036] Remove last reference of manage course ui

- package.json
- yarn.lock
https://github.com/DFE-Digital/manage-courses-frontend/network/alert/yarn.lock/set-value/open
🚢 
🚢
> [2047] Manually bump set-value npm package

- app/controllers/courses/age_range_controller.rb
- app/views/courses/age_range/_form_fields.html.erb
- app/views/courses/age_range/edit.html.erb
- app/views/courses/age_range/new.html.erb
- config/routes.rb
- spec/features/courses/age_range_in_years/new_spec.rb
- spec/site_prism/page_objects/page/organisations/courses/new_age_range_page.rb
New courses
Add "age range" selection for new course flow
🚢 
Note: Validation to be handled via the backend later
> [2039] Select age range for new course

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/apprenticeship/edit_spec.rb
- spec/features/courses/fee_or_salary/edit_spec.rb
> [2046] unhide edit-apprenticeship and edit fee or salary links

- config/routes.rb
- spec/features/courses/entry_requirements/new_spec.rb
- spec/site_prism/page_objects/page/organisations/courses/new_entry_requirements_page.rb
Consistent routes/paths/urls
Match new course routes with edit course routes
🚢
> [2041] Ensure new course routes match edit routes

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/accredited_body/edit_spec.rb
Editing course basic details
Adds a link to access the page.
:ship:
> [2051] Add change link to edit accredited body

- app/controllers/courses/accredited_body_controller.rb
- app/decorators/provider_decorator.rb
- app/views/courses/accredited_body/edit.html.erb
- app/views/providers/about.html.erb
- app/views/providers/details.html.erb
Fixing a small bug.
Add a method to the decorator to do this wherever it's used.
:shipit:
> [2050] Sort accredited bodies alphabetically

- app/controllers/courses/apprenticeship_controller.rb
- app/views/courses/apprenticeship/_form_fields.html.erb
- app/views/courses/apprenticeship/edit.html.erb
- app/views/courses/apprenticeship/new.html.erb
- config/routes.rb
- spec/factories/courses.rb
- spec/features/courses/apprenticeship/new_spec.rb
- spec/site_prism/page_objects/page/organisations/courses/new_apprenticeship_page.rb
New courses
Add apprenticeships page
🚢
> [2057] Add apprenticeships page for new courses

- app/controllers/courses/fee_or_salary_controller.rb
- app/views/courses/fee_or_salary/_form_fields.html.erb
- app/views/courses/fee_or_salary/edit.html.erb
- app/views/courses/fee_or_salary/new.html.erb
- config/routes.rb
- spec/features/courses/fee_or_salary/new_spec.rb
- spec/site_prism/page_objects/page/organisations/courses/new_fee_or_salary_page.rb
New courses
Add "fee or salary" selection for new course flow
🚢
> 2064 add new page for fee paying or salaried

- config/webpack/development.js
This fixes the slow running tests we're seeing in CI.
https://i.redd.it/4ypiuonxsik31.png
> [2036] Fix webpack dev server https key paths

- README.md
I was setting up from scratch and what to put in the local.yml tripped me up
Add more detailed info
:ship:
> Readme - add more detailed information on DfE Sign-in setup

- config/environments/new_qa.rb
- config/environments/new_staging.rb
> [XXXX] remove legacy environment settings

- config/routes.rb
UCAS have a hard-coded link to this.
Pointing it to / will check the users' session and sign them in if necessary.
:ship: :fire:
> [2036] Redirect /auth/cb path

- app/views/courses/level/new.html.erb
- app/views/courses/start_date/new.html.erb
> [XXXX] Fix level and start_date form path for new courses

- app/views/courses/_status_panel.html.erb
> [xxxx] fix font on destructive links

- app/controllers/courses/accredited_body_controller.rb
- app/controllers/provider_suggestions_controller.rb
- app/views/courses/accredited_body/_provider_search_field.html.erb
- app/webpacker/packs/application.js
- app/webpacker/scripts/__snapshots__/autocomplete.spec.js.snap
- app/webpacker/scripts/autocomplete.js
- app/webpacker/scripts/autocomplete.spec.js
- config/routes.rb
- package.json
- spec/features/courses/accredited_body/edit_spec.rb
- yarn.lock
In https://github.com/DFE-Digital/manage-courses-frontend/pull/593 we redirect the users to a page of suggestions if they enter a new accredited provider.
Add automatic suggestions to the new accredited provider box. Also adds plumbing for Javascript testing.
Initially authored by @faissalMT.
🚢
> [2080] Allow users to search for accredited body with JS

- azure/template.json
Enable Http2.0 for MCFE
Added additional parameters to the ARM template
> [148] Added enable http20 parameter in app service deployment

- app/views/providers/show.html.erb
- spec/features/providers_spec.rb
UCAS Contacts
Add link to org show page
🚢
> [2075] Add link to UCAS contacts

- app/controllers/pages_controller.rb
- app/views/layouts/_footer.html.erb
- app/views/pages/accessibility.html.erb
- config/routes.rb
- spec/features/view_pages_spec.rb
https://accessibility.campaign.gov.uk/
- Add accessibility statement 
🚢
> [2210] Add accessibility statement

- app/views/pages/accessibility.html.erb
- spec/features/view_pages_spec.rb
> [2210] Fixed typo

- app/views/courses/preview/financial_support/_salaried.html.erb
https://sentry.io/organizations/dfe-bat/issues/1239960414/?project=1407453&referrer=slack
Add missing salary partial
🚢
> [2195] Add missing salarried partial

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- azure/template.json
- config/environments/production.rb
- config/initializers/logstash.rb
- config/settings.yml
Applications Insights is insufficient.
Send our logs to logit.io
✂️ 🌲 🌲 🌲 ✂️
> [2221] add logging to logit

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- config/environments/development.rb
- config/environments/production.rb
- config/settings.yml
- config/settings/development.yml
We're trying to chase down a particularly thorny bug which is hard to replicate locally that seems to be related to the auth process.
Build ontop of the recent logstash additions to add optional debug-level output to gain insights of what's happening during a user's authentication process. (i.e. a bunch of debug logging)
The location of the debug output has been "carefully" selected to try to make sense in terms of the login / auth flow. If you see anywhere else that might be especially useful for gaining insight, without flooding the logs with noise let me know.
> [2195] add debug logging for user auth

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
> [2195] Strip emails from debug logs

- config/settings.yml
Toggling the setting:
- Tweaks the Publish button text
- Changes "Will it be on Find" to "Is it on Find"
- Adds view online links
- Shows vacancies column on courses table
> The current cycle is now open on Find

- app/views/ucas_contacts/index.html.erb
> [2270] Fix UCAS contacts support email

- app/views/providers/_provider.html.erb
This reverts commit b55a1f50023fc69feacd790fdeadd4218cf6e9f9.
https://github.com/DFE-Digital/manage-courses-backend/pull/862
Put course count back
🚢
> Revert "[2267] Temporarily remove course counts"

- app/controllers/courses_controller.rb
- app/decorators/application_decorator.rb
- app/models/course.rb
- app/views/courses/_course_table_row.html.erb
- app/views/courses/_status_panel.html.erb
- app/views/courses/withdraw.html.erb
- app/webpacker/stylesheets/_phase-tag.scss
- config/routes.rb
- spec/features/courses/withdraw_spec.rb
- spec/models/course_spec.rb
Withdrawing courses
- Ensure withdrawing a course is "self-service"
Find a running course and click withdraw in the sidebar.
> [2181] Hook up course withdraw

- app/views/courses/preview/_apply.html.erb
This updates the course preview with the correct URL.
> [2266] Update URL to Apply for 2020

- app/decorators/application_decorator.rb
- app/models/course.rb
- app/views/courses/_course_table_row.html.erb
- spec/decorators/course_decorator_spec.rb
- spec/models/course_spec.rb
Status badges were not showing up for new courses
> Fix course status badges not showing up for new courses

- app/controllers/concerns/course_basic_detail_concern.rb
- app/controllers/courses/subjects_controller.rb
- app/decorators/course_decorator.rb
- app/models/subject.rb
- app/views/courses/subjects/_form_fields.html.erb
- app/views/courses/subjects/edit.erb
- spec/decorators/course_decorator_spec.rb
- spec/factories/subjects.rb
- spec/features/courses/confirmation_spec.rb
- spec/features/courses/subjects/edit_spec.rb
- spec/support/helpers.rb
Users should be able to modify their subjects rather than having to go through support to do so.
Allows the user to set single subjects.
> [1857] Complete and refactor subject editing for master subjects

- .github/PULL_REQUEST_TEMPLATE.md
> Copy pr checklist from backend

- app/views/pages/new_features.html.erb
- app/views/providers/show.html.erb
Content  ✏️ 
- Update new features page content
- Remove content RE: Rollover
> 2394 update features page

- app/views/pages/new_features.html.erb
> [2394] Fix typo on new features page

- app/views/courses/_basic_details_tab.html.erb
- spec/features/courses/details_spec.rb
- spec/features/courses/subjects/edit_spec.rb
Subject editing isn't quite right yet
Remove change subjects link
🚢
> [XXXX] remove change subject link

- app/controllers/ucas_contacts_controller.rb
- app/views/ucas_contacts/alerts.html.erb
- app/views/ucas_contacts/show.html.erb
- spec/features/providers/ucas_alerts_spec.rb
- spec/features/providers/ucas_contacts_spec.rb
- spec/site_prism/page_objects/page/organisations/ucas_contacts.rb
- spec/site_prism/page_objects/page/organisations/ucas_contacts_alerts.rb
- spec/support/helpers.rb
> [2175] Add editing of alert email address

- Guardfile
- Rakefile
- bin/bundle
- bin/spring
- config.ru
Many warnings with `guard`
Results of running:
`bundle exec rubocop -a`
:ship:
> Rubocop auto-fixes

- app/views/courses/subjects/new.erb
> [2428] Fixed sub heading

- app/controllers/courses/subjects_controller.rb
- spec/features/courses/subjects/edit_spec.rb
> [2408] Correct misspelling and remove dead code

- app/views/layouts/application.html.erb
> [2452] Add Google Tag Manager

- app/controllers/application_controller.rb
- spec/controllers/application_controller_spec.rb
- spec/factories/user_factory.rb
- spec/support/helpers.rb
Admin user
Added the admin value to user from session
:shipit:
> [2484] Added the admin value to user from session

- config/environments/pentest.rb
- config/settings/pentest.yml
- config/webpacker.yml
Added a pentest.yaml file in config/settings folder to bring app settings setup inline with other environments.
> 2506-Add a config yaml file for pentest env

- app/views/courses/about.html.erb
- app/views/courses/requirements.html.erb
- app/views/providers/about.html.erb
Guidance text
Amended guidance text
> [2448] Amended guidance text

- app/views/courses/_new_fields_holder.html.erb
- Remove HRs from course creation to better match the prototype
> [2580] Remove stray HRs from course creation

- app/views/courses/sites/new.html.erb
The new course locations page is not in line with the prototype
- Refactor the new course locations page be in line with the prototype
> [2586] New course locations styling fixes

- app/views/courses/fee_or_salary/_form_fields.html.erb
The fee or funding page is not in line with the prototype
- Refactor the fee or funding page be in line with the prototype
https://manage-courses-prototype.herokuapp.com/new/V978/funding
> [2584] Fix incorrect styling on fee or funding page

- app/views/courses/accredited_body/edit.html.erb
- app/views/courses/accredited_body/new.html.erb
Same as previous PRs. Aligning with the prototype.
- Styling fix for accredited body search bar
> [2587] Styling fix for accredited body search bar

- spec/features/courses/start_date/new_spec.rb
- spec/features/courses/subjects/new_spec.rb
Tests were broken in master, this fixes them
> [2629] Fix broken tests

- azure/template.json
> [2618] Fix google maps api key env variable

- app/views/courses/preview/_apply.html.erb
- app/views/layouts/application.html.erb
Course#Preview location map
Ensure google map loads properly every time (very intermittent at present)
🚢
> [2618] Move google init to after application js

- app/views/pages/cookies.html.erb
- app/views/pages/privacy.html.erb
- app/views/pages/terms.html.erb
Service name
Update service name on static pages
🚢
> 2671 update service name on static page

- azure-pipelines.yml
Include integration test related files in the build artifact
> 2549-add test files and folders to the artifact

- app/controllers/courses/outcome_controller.rb
Master wasn't merged before PR was - added new linting error due to changes
Fix linting error
> Fix linting

- maintenance/azure-pipelines.yml
- maintenance/template.json
Automate deployment of maintenance page.
- Build pipeline (azure-pipelines.yml file)
- ARM template for app service deployment (template.json)
> 2681 configure maintenance page for publish

- app/controllers/organisations_controller.rb
- app/views/organisations/index.html.erb
- config/routes.rb
This view isn't used int the current support app, it wasn't tested in publish and therefore doesn't work 🤦‍♂ 
Remove route, controller action and view
🚢
> [2576] Remove org without active users

- azure-pipelines.yml
Remove package.json from build artifact.
> 2684-Remove package.json from build artifact

- app/webpacker/stylesheets/_environments.scss
- Staging is red
- QA is orange, not the focus colour
> Use the same environment colours as Apply

- azure/template.json
Add availability test for hostname  and custom hostnames in application insight
> 2715 integrate alerts setup in frontend template

- config/settings.yml
- config/settings/development.yml
- config/settings/pentest.yml
- config/settings/qa.yml
- config/settings/test.yml
DfE Sign-in URL's
Update "profile" and "search" URL's to use vanity URL.
🚢
> [2712] Update DfE Signin URL's

- app/controllers/concerns/course_basic_detail_concern.rb
- spec/features/courses/age_range_in_years/new_spec.rb
- spec/site_prism/page_objects/page/organisations/courses/new_age_range_page.rb
The custom age range flow currently just returns "other" rather than the from and to values
- Implement the above
> [2735] Implement custom age range flow for course create

- azure/template.json
Automate email alerts rules and availability checks creation for app services
Added resource deployment tasks for action-group, availability test and alert in ARM template
template.json
> 2747 automate availability test alerts in arm templates

- end-to-end-tests/cypress/integration/organisations.js
integration user and related test
Amended tests to reflect integration user that has only a single provider/organisation relationship.
Previously the test was tailored to users that has multiple provider/organisation access
CI pipeline may needs to be adjusted
For local machine with the right credentials for `user@example.com` and that database setup as well as https://github.com/DFE-Digital/manage-courses-frontend/blob/master/README.md#executing-tests
``` bash
psql -d "your_db" -c "INSERT INTO \"user\" (email, first_name, last_name, state, accept_terms_date_utc) VALUES ('user@example.com', 'integration', 'tests', 'transitioned', current_timestamp) ON CONFLICT (email) DO nothing;"
psql -d "your_db" -c "INSERT INTO \"provider\" (provider_code, provider_name, recruitment_cycle_id, …
```
> [2730] Amended tests to reflect integration user that has only a single provider/organisation relationship

- README.md
- end-to-end-tests/cypress/integration/organisations.js
test description
additional required setup for cypress tests
Amended test description
Added additional required setup for cypress tests 
:ship:
> 2730 rectify integration tests followup

- app/views/courses/entry_requirements/_page_intro.html.erb
- app/views/courses/entry_requirements/edit.html.erb
- app/views/courses/entry_requirements/new.html.erb
Content update to GCSE requirements
Update content
🚢
> [2766] Update equivalency intro content

- app/views/courses/entry_requirements/edit.html.erb
- app/views/courses/entry_requirements/new.html.erb
> Fix entry requirements page intro partial name

- config/settings.yml
dfe signin issuer
Amended dfe signin issuer
Need to check pipeline for the public url
> [2833] Amended dfe signin issuer

- app/helpers/provider_helper.rb
- app/views/courses/index.html.erb
- spec/features/courses/index_spec.rb
- spec/site_prism/page_objects/page/organisations/courses_page.rb
This reverts commit 1f54b1bb0fa82449bbdcaf7df2aed90fa06ce780, reversing
changes made to 1be68e8452e3908da1c27a5fd6a035730951758e.
> Revert "Merge pull request #883 from DFE-Digital/2371-change-create-course-link"

- spec/features/courses/index_spec.rb
- spec/features/courses/study_mode/new_spec.rb
- spec/features/sites/index_spec.rb
- spec/site_prism/page_objects/page/locations_page.rb
- spec/site_prism/page_objects/page/organisations/course_preview.rb
- spec/site_prism/page_objects/page/organisations/courses/new_study_mode_page.rb
- spec/views/preview.html.erb_spec.rb
Due to the pipeline giving false-positives and a change in Capybara master began failing.
This fixes the tests by moving more things to site prisms.
> [2878] Fix tests for new version of Capybara

- azure-pipelines.yml
Build must terminate if failures are detected in `Run Tests` task 
Put if condition to validate test results
https://trello.com/c/72HRuTa5/2878-figure-out-why-master-is-failing
> 2878 fix ci

- app/controllers/application_controller.rb
- app/controllers/providers_controller.rb
- app/controllers/users_controller.rb
For some reason it seems that user info is missing, causing the backend to have issues sending the welcome email, because this requires the user's first name.
Log warnings when various user details are missing.
Also tries to make the user login workflow a tad easier to read.
- ~~[] Tested by running locally~~
> [2978] Add debugging for missing user info

- azure-pipelines.yml
Create `prbranch.info` file with details of the pull request branch. Branch name from this file will be used for naming the preview app in Azure.
> 3090-Include PR branch name in artifact

- .github/auto-comment.yml
Add a config file for auto-comment app in `.github` folder. 
Auto-Comment bot app is designed to add a comment to every pull request. Comment contents are static and comes from `auto-comment.yml` file 
Add `.github\auto-comment.yml` file
https://trello.com/c/pNfDKfM0/3090-get-review-apps-working-for-publish
> Add Auto-comment.yml file

- .github/PULL_REQUEST_TEMPLATE.md
We now do product review on review-apps *before* merging.
* Add product review to PR checklist
This will be a handy reminder in the right place.
1. Consider if we like this as a team.
2. :ship:
> Add product review to PR checklist

- app/controllers/courses/vacancies_controller.rb
- app/models/course.rb
- spec/features/courses/vacancies/edit_spec.rb
Search and Compare is dead
Remove course syncing
🚢
> [269] Remove syncing

- app/views/courses/subjects/new.erb
Small PR to fix a potential bug with layout, styling & A11y.
> Fix h2 closing tag

- app/controllers/providers/allocations_controller.rb
- app/views/providers/allocations/_request_status.html.erb
- app/views/providers/allocations/index.html.erb
Fixes #1018 
- login as an admin user
- visit https://s121d02-1018-ptt-as.azurewebsites.net/organisations/B20/2020/allocations 
- keep refreshing the page to generate random status for the given providers
> 1018 Update  allocations table to reflect latest designs

- app/controllers/pages_controller.rb
- app/views/pages/accredited_body_new_features.html.erb
- config/routes.rb
This is just a basic page layout. We will need to do some more tweaks to
it.
Closes #1071 
login and view 
https://s121d02-3294-ptt-as.azurewebsites.net/accredited-body-new-features
> [3294] Inform accredited bodies of new features

- app/views/recruitment_cycles/_courses_accredited_body.html.erb
> Fix minor spacing issue "courses as..." section

- app/views/notifications/index.html.erb
- Fix title
- Add smart quotes
> Content tweaks to notifications page

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/models/session.rb
- app/models/user.rb
- app/services/feature_service.rb
- app/services/magic_link/generate_and_send_service.rb
- app/views/sessions/magic_link_sent.html.erb
- app/views/sessions/new.html.erb
- azure/template.json
- config/routes.rb
- config/settings.yml
- spec/models/session_spec.rb
- spec/requests/authorisation_spec.rb
- spec/requests/sessions_spec.rb
- spec/services/feature_service_spec.rb
- spec/services/magic_link/generate_and_send_service_spec.rb
- spec/support/features.rb
> [3343] add magic link login

- app/controllers/providers_controller.rb
The original design ordered courses by name not code. This has been lost
somewhere and production currently orders by code.
Order courses by name.
> [3364] Update course ordering

- app/views/providers/allocations/_request_status.html.erb
- app/views/providers/allocations/index.html.erb
- app/webpacker/stylesheets/_tables.scss
- app/webpacker/stylesheets/application.scss
> [3362] Update allocations landing screen copy and markup

- app/views/providers/allocations/requests/_yes_requested.html.erb
Minor copy changes to bring the service inline with the prototype
> [3385] Update copy on the allocation confirmation page

- app/controllers/providers/allocations_controller.rb
- app/flows/initial_request_flow.rb
- app/views/providers/allocations/initial_request.html.erb
- app/webpacker/packs/application.js
- config/routes.rb
- spec/features/providers/allocations_spec.rb
- Adds Autocomplete to initial allocation request provider search field
- Refactors some of the initial flow so its easier to understand.
> [3323] "Who are you requesting a course for" page needs autocomplete added

- app/views/pages/accredited_body_new_features.html.erb
Accredited body users will be shown this page once on login to direct them to newly available features.
Update the copy and formatting.
> [3389] Update accredited body interruption page

- app/form_objects/initial_request_form.rb
- app/views/providers/allocations/initial_request.html.erb
- spec/features/providers/allocations/initial_allocation_spec.rb
> [3464] Update error copy and add guidance to view

- app/views/providers/allocations/index.html.erb
- app/views/providers/allocations/requests/_not_requested.html.erb
- app/views/providers/allocations/requests/_yes_requested.html.erb
> 3465 Fix minor copy changes for Allocations

- app/controllers/providers/allocations_controller.rb
- app/controllers/providers/edit_initial_allocations_controller.rb
- app/models/allocation.rb
- app/view_objects/allocations_view.rb
- app/views/providers/allocations/_request_status.html.erb
- app/views/providers/edit_initial_allocations/check_answers.html.erb
- app/views/providers/edit_initial_allocations/do_you_want.html.erb
- app/views/providers/edit_initial_allocations/number_of_places.html.erb
- config/routes.rb
- spec/features/providers/allocations/edit_initial_allocation_spec.rb
- spec/features/providers/allocations/repeat_allocations_spec.rb
- spec/site_prism/page_objects/page/providers/allocations/edit_initial_allocations/check_answers_page.rb
- spec/site_prism/page_objects/page/providers/allocations/edit_initial_allocations/do_you_want_page.rb
- spec/site_prism/page_objects/page/providers/allocations/edit_initial_allocations/number_of_places_page.rb
- spec/support/helpers.rb
- spec/view_objects/allocations_view_spec.rb
https://trello.com/c/T6kURpH0/3426-m-change-initial-allocation-requests
This isn't using the same flow setup as creating an initial allocation, as we ran into some problems when trying to implement it. Instead we went for a new controller! There may be a case for refactoring later on to bring both of them together somehow. 
* Add edit_initial_allocations controller 
* Add templates for editing initial allocations
> [3426] change initial allocation requests

- app/views/providers/allocations/index.html.erb
- app/views/providers/allocations/number_of_places.html.erb
- app/views/providers/allocations/requests/_not_requested.html.erb
- app/views/providers/allocations/requests/_yes_requested.html.erb
- app/views/providers/edit_initial_allocations/number_of_places.html.erb
- app/views/recruitment_cycles/_allocations.html.erb
- spec/features/providers/allocations/edit_initial_allocation_spec.rb
- spec/features/providers/allocations/initial_allocation_spec.rb
- spec/features/providers/allocations/repeat_allocations_spec.rb
> [3474] Update copy across allocations pages

- README.md
> [3502] Add Code Climate badges to README

- app/views/providers/allocations/index.html.erb
> [3501] Add link to survey to allocations summary

- config/environments/rollover.rb
- config/settings/rollover.yml
- config/webpacker.yml
We're building out a rollover env to test rollover.
Add a `rollover` Rails env.
> [3510] add rollover env

- .azure_parallel
- azure-pipelines.yml
> [3502] Adds JavaScript test coverage

- Gemfile
- spec/spec_helper.rb
Fix for failing QA build
- Move aasm gem to default group
- Remove aasm/rspec helpers (not used)
> Fix failing build

- spec/views/footer.html.erb_spec.rb
- spec/views/header.html.erb_spec.rb
> Scope methods to just the describe they relate too

- app/controllers/pages_controller.rb
- app/services/performance_dashboard_service.rb
- app/views/pages/performance_dashboard.html.erb
- app/webpacker/stylesheets/_performance-dashboard.scss
- app/webpacker/stylesheets/application.scss
- config/routes.rb
- spec/fixtures/performance-dashboard.json
- spec/services/performance_dashboard_service_spec.rb
- spec/site_prism/page_objects/page/performance_dashboard_page.rb
- spec/views/pages/performance_dashboard.html.erb_spec.rb
- Adds a new endpoint `/performance-dashboard`
- Includes initial high level indicators
- https://s121d02-3404-ptt-as.azurewebsites.net/performance-dashboard
> [3404] Add a new reporting dashboard

- app/services/performance_dashboard_service.rb
- app/views/pages/performance_dashboard.html.erb
- app/views/pages/performance_dashboard/_initial_performance_indicators.html.erb
- app/views/pages/performance_dashboard/_providers_tab.html.erb
- app/webpacker/stylesheets/_performance-dashboard.scss
- spec/fixtures/performance-dashboard.json
- spec/services/performance_dashboard_service_spec.rb
- spec/site_prism/page_objects/page/performance_dashboard_page.rb
- spec/views/pages/performance_dashboard.html.erb_spec.rb
- https://s121d02-3610-ptt-as.azurewebsites.net/performance-dashboard
> [3610] Add Provider data to performance dashboard

- app/views/pages/performance_dashboard.html.erb
- app/views/pages/performance_dashboard/_allocation_content.html.erb
- app/views/pages/performance_dashboard/_courses_tab.html.erb
- app/views/pages/performance_dashboard/_providers_tab.html.erb
- app/views/pages/performance_dashboard/_users_tab.html.erb
- app/webpacker/stylesheets/_performance-dashboard.scss
- app/webpacker/stylesheets/application.scss
- app/webpacker/stylesheets/patterns/_tabs.scss
- Adjust font styling for "secondary/tertiary" stats
- Add custom style to active tab.
> [3622] Fixes Performance Dashboard styling issues

- azure/template.json
We have implemented a magic link signin alternative but it isn't correctly configured.
Set the necessary environment variables so as they are available in Azure.
> [3595] Set magic link environment variables

- app/views/courses/preview/qualification/_pgce.html.erb
- app/views/courses/preview/qualification/_pgce_with_qts.html.erb
- app/views/courses/preview/qualification/_pgde.html.erb
- app/views/courses/preview/qualification/_pgde_with_qts.html.erb
- app/views/courses/preview/qualification/_qts.html.erb
https://trello.com/c/rLs2TBct/3584-change-qts-pgce-definitions-on-find
> [3584] changed qts and pgce definitions in publish preview

- app/views/personas/index.html.erb
- https://trello.com/c/xA11zDVq/3685-m-persona-login
- Fixes a typo on the persona copy page
- Fixes a typo on the persona copy page
- Visit persona login page
- Typo should be fixed
> [3685] Fix copy on persona login page

- app/views/personas/index.html.erb
- https://trello.com/c/xA11zDVq/3685-m-persona-login
- Tweaks to persona login page
- Spacing changes
- Copy changes
- Load the persona login page via review app
- Should see small tweaks
> [3685] Styling and copy tweaks to persona login

- app/decorators/course_decorator.rb
- app/helpers/provider_helper.rb
- app/helpers/view_helper.rb
- app/views/courses/subjects/_form_fields.html.erb
- app/views/courses/subjects/new.erb
- app/views/pages/accessibility.html.erb
- app/views/ucas_contacts/show.html.erb
- spec/decorators/course_decorator_spec.rb
Addresses some tech debt we have and adds some tests to some methods we use in the views.
See individual commits for details
> Refactor view helpers

- app/controllers/courses/vacancies_controller.rb
- spec/features/courses/vacancies/edit_spec.rb
Given I am a user associated with an accredited body
I want to be notified when a provider whom I accredit updates the vacancy status of some locations
So that I can (update my records? and) do amazing things
- Please see related API PR - https://github.com/DFE-Digital/teacher-training-api/pull/1500
- the `send_vacancies_updated_notification` API endpoint now takes site statuses as a param. This is so that we can allow the API determine which vacancies notification to send rather than the client.
- Make sure your user is associated with the correct accrediting body
- Make sure you have a Notify test key
- Update a course that is accredited by the accrediting body. Specifically you want to update the vacancy status of a course that has multiple locations. Deselect some of the locations …
> [3701] - trigger course vacancies updated notification when some locations vacancy statuses have been updated

- azure-pipelines.yml
published terraform folder
published terraform folder
> publish terraform folder as build artifact

- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/staging.yml
Allocations are now confirmed.
Set `Settings.features.allocations.state` to 'confirmed'.
> [49] Set allocation state

- Gemfile
- Gemfile.lock
- config/application.rb
> Add govuk-components gem

- Gemfile
> [xxxx] Fixed linter issues

- app/views/courses/preview/financial_support/_placeholder.html.erb
- config/routes.rb
- config/settings.yml
- spec/features/courses/accredited_body/new_spec.rb
- spec/features/courses/age_range_in_years/new_spec.rb
- spec/features/courses/applications_open/new_spec.rb
- spec/features/courses/confirmation_spec.rb
- spec/features/courses/entry_requirements/new_spec.rb
- spec/features/courses/fee_or_salary/new_spec.rb
- spec/features/courses/modern_languages/edit_spec.rb
- spec/features/courses/modern_languages/new_spec.rb
- spec/features/courses/new_spec.rb
- spec/features/courses/preview_spec.rb
- spec/features/courses/study_mode/new_spec.rb
- spec/features/providers/allocations/edit_initial_allocation_spec.rb
- spec/features/providers/allocations/initial_allocation_spec.rb
- spec/features/providers/allocations/repeat_allocations_spec.rb
- spec/requests/providers_spec.rb
Rollover
Rollovered
Best to view per commit.
> 0208 update settings to complete rollover

- app/views/pages/performance_dashboard.html.erb
- spec/views/pages/performance_dashboard.html.erb_spec.rb
> [xxx] Hide Rollover partial content if not in rollover period

- config/settings.yml
- spec/features/courses/preview_spec.rb
Financial incentives placeholder
Removal Financial incentives placeholder
Requires new financial incentives to be in place
> 0254 remove financial incentives placeholder

- app/decorators/course_decorator.rb
- spec/decorators/course_decorator_spec.rb
The content on find has been updated to make funding information clearer. Update the preview content here to match.
'bursaries and' rather than 'bursaries or'
> [333] Course funding info content changes

- .github/workflows/deploy.yml
- terraform/variables.tf
- terraform/workspace_variables/app_config.yml
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/staging.tfvars
Keep non-secret app environment variables in a YAML file to easy visibility and editing.
`app_config.yml` file to configure non secret application environment variables and feature flags.
> YAML configuration file for managing environment variables

- .dockerignore
- .github/workflows/build.yml
- .gitignore
GitHub Actions workflow to build docker image and trigger deployment to QA PaaS
To be merged once #1433 & #1434 is merged.
> Build workflow in GitHub Action

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
Trigger smoke tests
Wait for smoke tests to complete and then trigger deployment to next environment.
> Deploy to staging and production

- .github/workflows/build.yml
Run rspec and yarn tests before deploying to QA
> Run ruby and javascript tests before triggering deploy

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Individual input parameters to control
deployments to qa, staging and production
> Use matrix deployment strategy

- config/settings/rollover.yml
Ensure prod matches staging i.e. DSI
Enable DSI for staging
🚢
> Enable DSI on staging

- .github/workflows/deploy.yml
Wait for other inprogress run in the matrix selection job.
> Wait for inprogress runs in matrix job

- .github/workflows/build.yml
Add missing turnstyle check in build workflow
> Add turnstyle check in build workflow

- Makefile
- config/environments/review.rb
- terraform/variables.tf
- terraform/workspace_variables/app_config.yml
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/review.tfvars
- terraform/workspace_variables/review_backend.tfvars
- terraform/workspace_variables/staging.tfvars
Make commands to deploy to qa, staging and production.
Be able to create and destroy review apps.
> Terraform commands in Makefile

- azure/template.json
App Service checks for valid 2xx response from the
configured path for each instance and
removes any unhealthy instance from the load balancer pool.
Prevents traffic from being routed to an unhealthy app instance.
> Config healthCheckPath

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
- .gitignore
- Makefile
- config/environments/sandbox.rb
- config/settings/sandbox.yml
- terraform/modules/statuscake/main.tf
- terraform/workspace_variables/app_config.yml
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/sandbox.tfvars
- terraform/workspace_variables/sandbox_backend.tfvars
- terraform/workspace_variables/staging.tfvars
Deploy app to sandbox environment
Include `sandbox` in deploy workflow.
Terraform configuration to deploy app to sandbox environment.
> Sandbox environment configuration

- .github/workflows/deploy.yml
- .gitignore
- terraform/data.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/sandbox.tfvars
- terraform/workspace_variables/staging.tfvars
Use secrets stored on AzureKey Vault
Use secrets stored on AzureKey Vault
> 956 store paas secrets in azure key vault

- terraform/workspace_variables/qa.tfvars
> Fix typo in terraform variable name

- config/environments/production.rb
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/workspace_variables/qa.tfvars
Configure syslog drain to send logs to LogIt.
Add and configure a user-provided log service to send STDOUT logs to logit.
> Configure log service for PaaS

- .github/workflows/smoke-test.yml
reverted this
https://github.com/DFE-Digital/publish-teacher-training/pull/1538/commits/39f504be37a66c13f5abb4a2a44e7b3097a9a3af
> [1056] Amended pipelines

- Makefile
- terraform/workspace_variables/local.sh
We use Azure key vault to store the secrets. We can leverage this to store the secrets required for local development.
Store local dev env secrets in key vault and automate the creation of config/settings/development.local.yml
Run make local print-app-secrets > config/settings/development.local.yml.new
> 1089 configure local dev environment via key vault

- app/views/providers/details.html.erb
> [1488] Fixed illogical heading

- Rakefile
- app.json
- app/webpacker/stylesheets/_environments.scss
- config/settings.yml
- config/settings/review.yml
- config/webpacker.yml
- spec/requests/authorisation/persona_spec.rb
> [1616] Amend basic app.json file

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- config/initializers/sentry.rb
- spec/controllers/application_controller_spec.rb
Upgrade sentry-raven to sentry-ruby
Gem upgrade and add sentry initializer
> [1703] Upgrade sentry-raven to sentry-ruby/sentry-rails

- app/views/courses/preview/_apply.html.erb
Uses `GovukComponent:: StartNowButton ` to render panel component (via `govuk-components` `govuk_start_now_button` helper method).
> Use GovukComponent::StartNowButton

- app/views/providers/allocations/requests/_yes_requested.html.erb
Uses `GovukComponent::Panel` to render panel component (via `govuk-components` `govuk_panel` helper method).
> Use GovukComponent::Panel

- app/models/provider.rb
Fixes a bug which allows us to view the next cycle
`Note:` You won't be able to review this using the review app
- You'll need the following setting in `development.local.yml`: `can_edit_current_and_next_cycles: true`
- You'll also need rolled over providers locally
- Then navigate to a provider and check that you can click on the next cycle link successfully.
> [1805] - Next cycle page bug fix

- config/settings/rollover.yml
Flipping a switch in rollover env
> Flipping a switch in rollover env

- docs/allocations.md
https://trello.com/c/Lfmb9xtS/1749-document-allocations-steps
- Adds documentation for Allocations
> [1749] Add Allocations documentation

- docs/allocations.md
https://trello.com/c/ueCalDVw/1878-flesh-out-allocations-documentation-with-learnings-from-2021-switch-on
Flesh out the allocations docs to help with product / code review.
Details what should provider should be able to see at each step, and what data changes are expected.
... Read the docs.
> [1878] Flesh out allocations docs

- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
- terraform/modules/paas/variables.tf
- terraform/workspace_variables/review.sh
- terraform/workspace_variables/review.tfvars
Have review apps for each open pull_request
Workflow changes to deploy review app.
Terraform changes for review app environment.
> Deploy review app on pull_request

- Gemfile
- Gemfile.lock
> [1829] Add sentry-sidekiq gem

- Dockerfile
- Gemfile
- Gemfile.lock
- app/controllers/providers/allocations_controller.rb
- app/models/allocation.rb
- app/view_objects/allocations_view.rb
- config/settings/review.yml
- spec/features/providers/allocations/edit_initial_allocation_spec.rb
- spec/features/providers/allocations/initial_allocation_spec.rb
- spec/features/providers/allocations/repeat_allocations_spec.rb
- spec/view_objects/allocations_view_spec.rb
> [Xxxx] revert 1905

- Gemfile
- Gemfile.lock
As part of my card i'm beginning to add in quite a bit of logic to the views. 
We should be using view components so we can unit test things thoroughly
- Add the view_component gem
> Add view_component gem

- app/decorators/course_decorator.rb
- app/views/courses/status_panel/_unpublished.html.erb
- app/views/pages/rollover.html.erb
- app/views/providers/_show_during_rollover.html.erb
- app/views/providers/show.html.erb
- config/initializers/date_formats.rb
- config/settings.yml
- docs/rollover.md
The copy has been updated in the Publish prototype.
https://trello.com/c/wh33iXZr
Match updates made in the Publish prototype.
**Before**
**After**
Page is visible at `/rollover`.
> Update copy on rollover page

- app/views/recruitment_cycles/show.html.erb
Content for this page has been updated in the prototype.
Match content changes in the prototype.
- Update copy
- Swap position of courses and locations
A scan of the diff and comparison of the screenshots ought to do it.
> Update content on next cycle page

- app/views/access_requests/new.html.erb
- app/views/providers/access_requests/new.html.erb
- config/locales/helpers.yml
Update 2 access request forms to use form builder.
> Use form builder for access request forms

- .github/workflows/delete-review-app.yml
Failing delete review app job : https://github.com/DFE-Digital/publish-teacher-training/runs/2951559851?check_suite_focus=true
Add missing step id
> [2089] Fix delete review app

- config/settings.yml
Allocations are closing today.
Update the config to disable the interrupt page and close the allocations.
> [xxx] Close allocations

- app/helpers/view_helper.rb
We've updated another validation message in TTAPI. 
Support it. Removal of the old formats will be in a subsequent PR.
> [xxx] Support extra validation message

- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
- .gitignore
- Makefile
- terraform/terraform.tf
- terraform/variables.tf
Make it easy to manage depployments via Makefile
Use docker image tag from master if not specified
Enforce passcode when running deploy from Makefile
Run terraform commands from the terraform directory
Enable review apps via Makefile
- Run deploy-plan
- Successful deployment: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/1008831128
- Successful delete: https://github.com/DFE-Digital/publish-teacher-training/runs/3018051003?check_suite_focus=true
> [2145] Update Makefile

- .github/workflows/deploy.yml
Make deployment process more consistent
Add confirmation so that deployment can happen on production
> [2145] Enable automated deployment to production

- .github/workflows/smoke-test.yml
- .tool-versions
- Dockerfile
- Gemfile
New ruby version  released
see https://www.ruby-lang.org/en/news/2021/07/07/ruby-2-7-4-released
Upgrade to ruby 2.7.4
> Upgrade to ruby 2.7.4

- app/views/providers/details.html.erb
> [2196] Show lead school urn instead of ukprn

- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- Dockerfile
- Makefile
Improve build time
- Use the PR branch name in docker build
- Move ARG to bottom to enable caching
- Remove paas- prefix in docker tag
- BUGFIX: Makefile terraform destroy
Check workflow runs
> Use review app PR head branch as Docker tag

- Gemfile
- Gemfile.lock
- spec/features/courses/show_spec.rb
- spec/helpers/application_helper_spec.rb
Help make some failing specs pass while upgrading to GOV.UK Components v2.
> Govuk components v2

- app/views/sites/index.html.erb
- spec/factories/providers.rb
- spec/features/sites/new_spec.rb
We no longer limit the number of sites per provider, see #1785 
🚢
> [2339] Remove sites limit method

- package.json
- yarn.lock
Reverts DFE-Digital/publish-teacher-training#1870
> Revert "Bump @rails/webpacker from 5.4.0 to 5.4.2"

- Gemfile.lock
Reverts DFE-Digital/publish-teacher-training#1869
> Revert "Bump webpacker from 5.4.0 to 5.4.2"

- app/views/providers/allocations/_allocation_report_confirmed_state.html.erb
- app/views/providers/allocations/_allocation_request_confirmed_state.html.erb
- app/views/recruitment_cycles/_allocations.html.erb
- config/locales/en.yml
- config/settings.yml
- config/settings/review.yml
- [This trello ticket](https://trello.com/c/p3UPZ8g7/95-pe-allocations-update-the-allocations-page)
- Content changes for PE allocations
- Go to an Accredited Body Provider and scroll down to the allocations section
> Content changes for allocations

- app/views/providers/allocations/_allocation_request_confirmed_state.html.erb
> [187] Style links on allocations page

- app/views/layouts/_phase_banner.html.erb
Feedback link is incorrectly styled
Use govuk_link_to to correct styling.
> [xxx] Feedback link is a govuk-link

- app/views/providers/allocations/_allocation_report_confirmed_state.html.erb
- spec/features/providers/allocations/initial_allocation_spec.rb
- spec/features/providers/allocations/view_allocation_spec.rb
- spec/site_prism/page_objects/page/providers/allocations/index_page.rb
- spec/support/resource_list_to_jsonapi.rb
- spec/support/serializers/allocation_uplift_serializer.rb
> [xxx] Pluralize uplifts

- app/views/courses/_basic_details_tab.html.erb
Whose line is it anyway?
Return the line
> [xxxx] Fixed stolen lines

- .github/PULL_REQUEST_TEMPLATE.md
While we're working on a gradual migration of Publish over to TTAPI,
we'll need to be careful how we handle changes to parts of Old Publish
that are in the process of being migrated.
Add a reminder to the PR checklist to discuss this as required.
na
> Add migration reminder to PR template checklist

- app/views/providers/show.html.erb
- app/views/recruitment_cycles/_provider_info.html.erb
- app/views/recruitment_cycles/show.html.erb
- spec/support/helpers.rb
- spec/support/sign_in_helper.rb
- spec/views/providers/show_spec.rb
Differing views
Aligned differing views
They are aligned
> [0444] Fixed differing provider info show page

- app/views/providers/no_providers.erb
- spec/requests/providers_spec.rb
No provider associated with user
Amended copy text
> [459] Amended no provider content

- app/views/courses/_course_abilities_blurb.html.erb
- app/views/courses/_description_content.html.erb
- app/views/courses/about.html.erb
- app/views/courses/index.html.erb
- app/views/courses/status_panel/_unpublished.html.erb
- app/views/recruitment_cycles/_courses_info.html.erb
- app/views/shared/_aside_information_box.html.erb
- spec/features/courses/about_spec.rb
- spec/requests/courses/about_spec.rb
- https://trello.com/c/bVLrHZvO/473-content-updates-for-round-1a-courses-5-pages
Some copy updates
> [473] Content updates for round 1.a: courses

- app/views/courses/delete.html.erb
- app/views/courses/fees.html.erb
- app/views/courses/sites/edit.html.erb
- app/views/courses/sites/new.html.erb
- app/views/courses/vacancies/_multiple_sites.html.erb
- app/views/courses/withdraw.html.erb
- config/locales/helpers.yml
- spec/features/courses/destroy_spec.rb
- spec/features/courses/sites/edit_spec.rb
- spec/features/courses/sites/new_spec.rb
- spec/features/courses/withdraw_spec.rb
Content update 
Amended withdraw courses copy text
Amended delete course copy text
Amended course fees copy text
Amended locations copy text
Amended personal qualities copy text
Amended location pick vs select copy text
> [0468] Content updates for round 1b courses 6 pages

- app/models/organisation.rb
- app/views/organisations/_organisation.html.erb
- spec/factories/organisation.rb
- https://trello.com/c/DtSlYsgT/437-remove-nctlorganisation
- Remove references to NCTL
API related PR is here https://github.com/DFE-Digital/teacher-training-api/pull/2355
> [437] Remove references to nctl

- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/staging.yml
- spec/features/providers/about_spec.rb
- spec/features/providers/contact_spec.rb
- spec/features/providers/details_spec.rb
- spec/features/providers/visa_spec.rb
Corresponding PR https://github.com/DFE-Digital/teacher-training-api/pull/2482
> Enable first migrated section in prod

- app/views/recruitment_cycles/_locations_info.html.erb
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/staging.yml
Enable linking to new publish for locations management in dev/qa/staging
> Enable new publish locations management for qa/staging

- app/views/shared/_aside_information_box.html.erb
- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/staging.yml
Enable the users section in qa/staging
> Enable users section in staging
