app/views/layouts/application.html.erb, app/views/pages/cookies.html.erb, app/views/pages/home.html.erb, app/views/pages/privacy.html.erb, app/views/pages/terms.html.erb, config/routes.rb
SEO and legal pages
- Add page title
- Create legal pages (cookies, privacy, terms) taken from manage-courses-ui
- Remove copyright content from footer
- Add service title into header
- Ensure crown links to gov.uk
- View `/terms-conditions`, `/cookies`, `/privacy-policy`
=> Add page title, footers links and remove copyright

.travis.yml
This should allow us to build with a cache of the previous layers, which should be much quicker because it should skip bundling when the Gemfile doesn't change.
=> Login to AzureCR and pull master docker layers before building

Gemfile, README.md, Rakefile, lib/tasks/govuk_lint.rake
We often forget to lint our code before raising a PR (which causing a build failure) so if we get into the habit of running `rake` then you know the code(pending review) is good to go 👌 
- Override `rake` to run the specs and linters (ruby and scss)
```
bundle exec rake
```
=> Extend default rake task

azure/template.json
Follow up to https://github.com/DFE-Digital/manage-courses-frontend/pull/68
Remove legacy `ENV`'s
=> [1060] Remove legacy envs

config/webpack/production.js, package.json, yarn.lock
This should re-enable the fonts and other contents of govuk-frontend.
This was initally a WIP with a worse solution, I'm much happier with the webpack copy method than re-enabling the asset pipeline compile flag in production mode.
=> [1068] Copy assets to public folder using webpack

config/application.rb
Previous default was when user close the browser
Amended the session to expire in 5 minutes
Sign in stay inactivity for 5+ minutes then traverse the site
When traversing the site browser first go to sign in and sign in via `openconnect` seamlessly.
After a period of time has elapse the user will not sign in via `openconnect` seamlessly, instead they will need to reenter their credentials.
=> [1067] Amended the session to expire in 5 minutes

app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
It's possible for an existing DfE Sign-in user to try accessing Publish, but they're not a known user in the Manage Courses database.
This is a temporary stop-gap which redirects unknown users to Manage Courses UI.
Manage Courses UI then shows a "we don't know who you are" page to those users.
I paired with @defong on this.
=> [1108] Handle unknown users

azure-pipelines.yml
This PR changes azure-pipelines.yml to use the standard azure pipelines docker task provided by Microsoft.
* Use Docker task rather than standard script commands
* Conventions / formatting
* Do tests fail and publish results
* Do linters fail and provide appropriate feedback.
=> Update build definition to use az docker task

config/application.rb
We tried 5 minutes to see how sign-in would behave but ran afoul of it's ~20-30
minute session expiry. We need to implement access token renewal with the
refresh token, but until we do that (hopefully before go-live) we'll extend the
session to 6 hours here.
=> [1112] extend session timeout to 6 hours

app/controllers/pages_controller.rb, config/routes.rb, spec/features/sign_in_spec.rb, spec/features/view_pages_spec.rb, spec/support/feature_helpers.rb
`pages#show` was from the boilerplate, we don't need that
- Be explicit with our controller actions to ensure they match our routes
- Add specs for all `pages`
- Add temp override for authentication because we always redirect to root after success which needs updating at a later date
=> Refactor pages spec

app/controllers/application_controller.rb, spec/controllers/sessions_controller_spec.rb
Without the `(true)` parameter, Base.connection will re-use the same instance of the connection class between connections. If multiple users are hitting the app simultaneously, this can cause re-use of tokens among them and undesirable behaviours.
=> [1108] Rebuild the connection when adding session token

app/controllers/application_controller.rb, app/controllers/providers_controller.rb, spec/controllers/providers_controller_spec.rb, spec/fixtures/providers-empty.json, spec/support/helpers.rb
Users should be redirected to the "We don’t know which organisation you’re part of" page in manage-courses-ui when the providers list is empty.
=> [1139] Redirect to manage-courses-ui when providers list is empty

app/controllers/providers_controller.rb, app/views/providers/show.html.erb, spec/controllers/providers_controller_spec.rb, spec/features/providers_spec.rb
Redirects the index action if there's only one provider.
The breadcrumbs are also hidden because they are not useful in this scenario. This is done by querying the full Providers endpoint for the full list, which is a bit annoying/slow, but can be changed in the future if necessary.
=> [1146] Redirect to organisations#show page when there is 1 provider

app/controllers/application_controller.rb, spec/controllers/sessions_controller_spec.rb
When a new user logs into the service, they should be asked to tick the terms and conditions if they haven't done so already.
=> [1165] Redirect to manage-courses-ui when API returns 403

.gitignore, app/controllers/application_controller.rb, app/controllers/providers_controller.rb, app/views/pages/cookies.html.erb, spec/controllers/application_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/features/providers_spec.rb
We currently do a request for the whole list of providers when we hit the `organisation#show` page. This is fairly inefficient, and moreover, we'll need this in the future on every page that has breadcrumbs (almost all of them).
When initialising a user session, query the list of providers in order to get the total count and save it to a cookie. This can then be referenced from the controller/view templates in order to decide whether we need to show the breadcrumbs.
Note that this call in the session is still quite slow (for a God user), so it slows down initial signin, but it's only done once. We can choose to further optimise it down the line.
This is a spike more or less, so haven't touched the tests, but if the idea looks good, just request changes and I'll add/update the requisite …
=> [1194] Add provider count cookie

app/helpers/view_helper.rb, spec/helpers/view_helper_spec.rb
`<%= manage_ui_link_to_back("/organisation/#{params[:provider_code]}/courses/#{@course.course_code}") %>` 
vs
`<%= manage_ui_link_to "Back", "/organisation/#{params[:provider_code]}/courses/#{@course[:course_code]}", class: "govuk-back-link" %>`
Add helper method for back link to manage courses ui
=> Add back link helper for manage ui

app/controllers/courses/vacancies_controller.rb, app/views/courses/vacancies/edit.html.erb, app/views/layouts/_flash.html.erb, app/webpacker/stylesheets/_flash.scss, app/webpacker/stylesheets/application.scss, spec/features/courses/vacancies/edit_spec.rb
Show user success state
- Setup flash messages
- Add flash success to courses#vacancies#edit
=> [1136] add success flash to course vacancies

app/controllers/courses/vacancies_controller.rb, spec/features/courses/vacancies/edit_spec.rb
The attributes on the checkboxes changed in this big PR https://github.com/DFE-Digital/manage-courses-frontend/pull/106 and this change missed.
The happy path is working but adding vacancies for a course where the vacancy status is nil isn't working. This should fix it
Update checkbox input attributes in the controller
Example course `https://localhost:3000/organisations/2DQ/courses/3272/vacancies`
The test here doesn't actually test the failure but it's good to add. Once we have proper factories from https://github.com/DFE-Digital/manage-courses-frontend/pull/109 then we should add some tests and probably a controller test.
=> Fix courses vacancies edit

.rubocop.yml, Gemfile, Gemfile.lock, README.md, azure-pipelines.yml, docker-build.sh, lib/tasks/govuk_lint.rake
GOV.UK Lint is being deperacated, this is the new way of using it.
GOV.UK Lint is being deprecated, it's recommended to be used in this way instead.
I haven left the SCSS listing in there, they recommend using node based tooling for that instead.
Switch from govuk-lint-ruby to Rubocop configured to use govuk-lint's rules.
=> Use Rubocop instead of govuk-lint-ruby for linting

app/controllers/courses/vacancies_controller.rb, spec/features/courses/vacancies/edit_spec.rb
Course vacancies
When a user selects the no vacancies radio button we should set all the site statuses to `no_vacancies`
e.g. `https://localhost:3000/organisations/2DQ/courses/3272/vacancies`
=> [1136] Update all site statuses if radio button is checked

app/views/layouts/application.html.erb
* Remove duplicate `mailto:`
* Set subject separately
```html
<a class="govuk-link" href="mailto:mailto%3Abecomingateacher@digital.education.gov.uk%3Fsubject%3DPublish%2520teacher%2520training%2520courses%2520feedback">feedback</a>
```
```html
<a class="govuk-link" href="mailto:becomingateacher@digital.education.gov.uk?subject=Publish%20teacher%20training%20courses%20feedback">feedback</a>
```
Please run this locally when reviewing.
=> Fix mail_to links

app/controllers/application_controller.rb, app/controllers/courses_controller.rb, app/controllers/providers_controller.rb, app/views/courses/index.html.erb, app/webpacker/stylesheets/_phase-tag.scss, app/webpacker/stylesheets/application.scss, spec/factories/courses.rb, spec/features/courses/index_spec.rb
This will allow users to view their courses and edit vacancies from the shiny new Rails frontend.
I've added strident red borders around the parts of the table that are still unimplemented / stubbed out.
=> [1210] Add courses table

app/helpers/view_helper.rb, app/views/courses/vacancies/edit.html.erb, app/views/providers/show.html.erb, spec/features/courses/vacancies/edit_spec.rb, spec/helpers/view_helper_spec.rb
The link from the vacancies edit page in this app to Manage Course UI doesn't work.
- fix the 'Cancel changes' link
- fix the course page URL
- re-cut helper responsibility
Alternative to #121 with some more code tidy-up. Best reviewed commit-by-commit.
=> [1207] Fix Manage Courses UI course page link

config/environments/qa.rb, config/environments/staging.rb, config/settings/qa.yml, config/settings/staging.yml, config/webpacker.yml
Proper environments i.e. `staging` and `qa` (for https://bat-dev-manage-courses-frontend-app.azurewebsites.net/)
- Add `{staging, qa}.rb` - duplicates of `production.rb`
- Add settings for `staging` and `qa`
`bin/rails server -e staging -b "ssl://localhost:3000?key=config/localhost/https/localhost.key&cert=config/localhost/https/localhost.crt" `
=> Setup proper staging and qa environment

azure/template.json, config/settings.yml, config/settings/development.yml, config/settings/production.yml, config/settings/test.yml
The courses table links directly to find, so we need to add this. Requires a Terraform change as well: https://github.com/DFE-Digital/bat-infrastructure/pull/120
Also updates the VSTS settings with some missing keys.
=> [1210] Add search-and-compare-ui base url to settings

app/views/courses/index.html.erb, spec/features/courses/index_spec.rb
Very small but self contained so may as well get it out while I do the rest.
=> [1210] Fix stubbed out link to course page in courses table

.gitignore, Gemfile, Gemfile.lock, spec/rails_helper.rb
See test coverage
Add [simplecov](https://github.com/colszowka/simplecov) gem and setup
`$ bundle exec rspec` 
```ruby
Coverage report generated for RSpec to /Users/Dan/Git/manage-courses-frontend/coverage. 705 / 740 LOC (95.27%) covered.
```
=> [1222] Add simple cov for test coverage

app/models/provider.rb, spec/controllers/providers_controller_spec.rb, spec/factories/courses.rb, spec/factories/providers.rb, spec/features/courses/index_spec.rb, spec/features/providers_spec.rb, spec/features/sign_in_spec.rb
The provider factory was never modified to produce JSONAPI responses in the same manner as the course and site factories. This PR is a precursor to 1219.
* Provider factory now produces JSONAPI responses
* Provider now `has_many :courses`
=> [1219] Change provider factory to produce JSONAPI

app/helpers/vacancy_helper.rb, app/views/courses/vacancies/_site_status_checkbox.html.erb, spec/helpers/vacancy_helper_spec.rb
Refactoring a repetitive and confusing helper method.
This helper is to return true or false in order to check individual the checkboxes on Courses#Vacancies#Edit. We compare the course `study_mode` and the site status `vac_status`
Refactor main helper method into two smaller helpers
N/A - probably best to ignore whitespace when viewing the diff
=> [1136] refactor vacancy checkbox helper method

spec/factories/courses.rb, spec/features/courses/vacancies/edit_spec.rb
Our pipeline was failing because of this message
> WARNING: ignoring the provided expectation message argument ({:chosen=>true}) since it is not a string or a proc.
I've fixed the test triggering this, which was also broken.
* Added study mode traits to course factory
* Fixed test to get rid of warning (and actually fix the test)
=> Fix ignoring provided expectation message warning

app/helpers/course_helper.rb, app/views/courses/_content_status_tag.html.erb, app/views/courses/_course_table_row.html.erb, spec/factories/courses.rb, spec/features/courses/index_spec.rb, spec/helpers/course_helper_spec.rb
This is now being pulled in from the API and displayed in the table.
=> [1210] Implement content_status in courses table

app/views/layouts/application.html.erb
Add support email link to footer
=> [1241] Add support email link to footer

app/controllers/courses/vacancies_controller.rb, app/models/course.rb, app/models/provider.rb, spec/features/courses/vacancies/edit_spec.rb
After updating vacancies, call custom endpoint to cause course to by
synced with search and compare.
* Added custom endpoint
* Perform call after **ALL** site statuses have been updated
=> [1219] Sync course with search and compare

app/controllers/courses/vacancies_controller.rb, app/models/site_status.rb, app/views/courses/vacancies/edit.html.erb, spec/factories/site_statuses.rb, spec/features/courses/vacancies/edit_spec.rb
Running `site_statuses`
- Refactor vacancies controller
- Filter `site_statuses` to those only with a status of running
=> 1238 running site statuses

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/guidance.html.erb, config/routes.rb, spec/features/view_pages_spec.rb
This will be used by providers to learn how to use the new features.
=> [1246] Add a guidance page

app/controllers/sites_controller.rb, app/models/provider.rb, app/views/sites/index.html.erb, spec/factories/providers.rb, spec/features/locations_spec.rb
Opted in providers
- Only show new location CTA if the provider is opted in
- Sort location by name
Example: `/organisations/1MN/locations`
=> Fix add location link

config/environments/ucas.rb, config/settings/staging.yml, config/settings/ucas.yml, config/webpacker.yml
Also minor fixes to qa and staging envs.
https://trello.com/c/0zd6xRn9/1257-add-ucas-rails-environment-to-mc-fe
The UCAS environment  is running in `development`. We want this env to run like the others with it's own `RAILS_ENV` so that we can configure parts of it in the app itself. Part of the reason we want to change this is that the ucas environment is currently broken because it needs the env var `SETTINGS__MANAGE_BACKEND__BASE_URL` but we don't have access to add that in VSTS. If we add a proper Rails env we can just set it using the standard env settings.
Add `ucas` environment.
The `qa` and `staging` environments were both missing the setting `Settings.search_ui.base_url` in the settings file. In `qa` this was being supplied in the application settings in Azure, but for `staging` …
=> [1257] add 'ucas' rails env

azure/template.json
Remove unnecessary settings env vars from Azure template. They're being set in the appropriate settings files for the envs.
=> [1257] remove uneeded setting env vars for base urls

app/controllers/providers_controller.rb, app/views/courses/_course_table_row.html.erb, app/views/courses/index.html.erb, app/views/providers/_provider.html.erb, app/views/providers/show.html.erb, app/views/sites/index.html.erb, spec/controllers/providers_controller_spec.rb, spec/factories/providers.rb, spec/features/locations_spec.rb, spec/features/providers_spec.rb
This is needed to match the frontend with the backend API V2. See https://github.com/DFE-Digital/manage-courses-backend/pull/249
Just rename all mentions of `institution_code` to `provider_code`, no other changes were needed.
=> [1259] Rename institution_code to provider_code

app/controllers/courses/vacancies_controller.rb, spec/features/courses/vacancies/edit_spec.rb, spec/requests/courses/vacancies/edit_spec.rb
This is needed to match up with changes on the backend: https://github.com/DFE-Digital/manage-courses-backend/pull/245
These changes cause the API request to ask for site statuses and sites
to be included in the course.
=> [1258] Explicitly include sites on vacancy pages

app/controllers/courses_controller.rb, app/models/provider.rb, app/views/courses/index.html.erb, spec/factories/courses.rb, spec/features/courses/index_spec.rb
**Ignore the branch name, this is a precursor to doing that.** 
Before we were trying to map them with `provider_code`, which isn't an
attribute on course. The API returns the `provider_code` as
`institution_code` instead.
I've fixed these and fixed all the tests that failed by doing so. Most
of them were due to explicitly looking providers up by `provider_code`.
This allows us to look up a provider and do `provider.courses`, assuming
that we included courses in the provider lookup.
Likewise, we can do `course.provider`, assuming the provider was
included in the course lookup.
Change all mentions of `provider_code` to correctly call `institution_code`. The exception to this is the routes and `params`, because the route is still `/provider` and this `code` becomes `provider_code`.
This …
=> [1217] Fix relation between provider and course

app/controllers/courses_controller.rb, app/views/courses/delete.html.erb, app/views/courses/withdraw.html.erb, config/routes.rb, spec/features/courses/delete_spec.rb, spec/features/courses/index_spec.rb, spec/features/courses/show_spec.rb, spec/features/courses/withdraw_spec.rb
Withdrawing and delete courses
- Add /withdraw
- Add /delete
Find a course on the frontend app and navigate to `/courses/XXX/withdraw` and `/courses/XXX/delete`
=> [1252] add course delete and withdraw pages

app/views/courses/delete.html.erb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, app/views/courses/vacancies/edit.html.erb, app/views/courses/withdraw.html.erb, app/views/errors/forbidden.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/pages/cookies.html.erb, app/views/pages/guidance.html.erb, app/views/pages/privacy.html.erb, app/views/pages/terms.html.erb, app/views/providers/index.html.erb, app/views/providers/show.html.erb, app/views/sites/index.html.erb
Clean code 😍 
Move `main` element into layout file and introduce `before_content` block for page specific breadcrumbs and backlinks
No visual change.
> Ignore whitespace changes to see actual changes
=> Refactor and dry up page layout

app/controllers/pages_controller.rb, app/views/pages/transition.html.erb, config/routes.rb, spec/features/view_pages_spec.rb
Transition 🎉 
- Add static `/transition` page ready to be hooked up the users in a later story/pr
=> [1247] add transition info page

app/views/courses/index.html.erb, app/views/providers/_provider.html.erb, app/views/providers/show.html.erb, app/views/sites/index.html.erb, spec/factories/providers.rb
This is needed to match the frontend with the backend API V2. See https://github.com/DFE-Digital/manage-courses-backend/pull/251
Just rename all mentions of `institution_name` to `provider_name`, no other changes were needed.
n/a
=> [1260] Rename institution_name to provider_name

app/controllers/courses_controller.rb, app/views/courses/_course_table.html.erb, app/views/courses/index.html.erb, spec/factories/courses.rb, spec/features/courses/index_spec.rb, spec/support/mock_jsonapi_serializable.rb
We need to display accrediting providers above each courses table on the courses page. Where the accrediting provider is set to the parent provider or is set to `null`, they should be displayed as self-accredited (no heading).
- pulls in the accrediting provider relation from the API
- groups them by their provider name
- sorts the providers by their names
- sorts the courses by their names
- splits out the self-accredited ones to be rendered separately
- tests to go
Paired with @heidar, we think there might be a better way to do the `sort_by` and `map(sort_by)` but we did a bit of code golfing and couldn't immediately think of something clearer.
Review without whitespace changes.
=> [1210] Add accrediting providers to the courses table

app/controllers/courses_controller.rb, app/helpers/view_helper.rb, app/views/courses/delete.html.erb, app/views/courses/withdraw.html.erb, app/views/errors/forbidden.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/application.html.erb, app/views/pages/privacy.html.erb, app/views/pages/terms.html.erb, config/settings.yml
There is a bit of duplication in how we generate the contact links in the service. Also, I've noticed that we don't include in the provider code in withdraw/delete course emails
- Add a view helper for generating contact emails
- Add missing provider code to withdraw/delete course emails
=> [1241] Tweaks to contact links

app/views/layouts/application.html.erb
Flash messages are important and should be read out when skipping to main content.
This also fixes the vertical alignment of the messages.
=> Move flash messages into main element

app/views/courses/vacancies/_site_status_checkbox.html.erb, app/views/courses/vacancies/edit.html.erb, spec/requests/courses/vacancies/edit_spec.rb
If a course is all part time or all full time, we don't need to add "Full time" and "Part time" to the end of the location label.
=> Suppress study mode for vacancies on some locations

app/models/course.rb, app/views/courses/_course_table_row.html.erb, spec/features/courses/index_spec.rb
The course table 'Applications' column was showing the wrong information.
Bolster spec coverage and fix the issue.
=> [1210] Courses table applications fix

config/settings/ucas.yml
Cannot sign into UCAS env with this set wrong.
Fix `dfe_signin.base_url` setting for UCAS env.
No ticket, too small.
=> Fix dfe_signin base_url for ucas env

app/helpers/course_helper.rb, app/helpers/provider_helper.rb, app/views/courses/index.html.erb, app/views/sites/index.html.erb, config/settings.yml, spec/factories/providers.rb, spec/features/courses/index_spec.rb, spec/helpers/provider_helper_spec.rb, spec/support/mock_jsonapi_serializable.rb
Add new course
"Add new course" CTA to `courses#index`
=> [1250] add new course cta

app/models/course.rb, app/views/courses/_course_table.html.erb, app/views/courses/_course_table_row.html.erb, app/webpacker/stylesheets/application.scss
Courses table
- Add dark bottom border to header row
- Don't render `open_for_applications`, `has_vacancies` or `content_status` if the course is not running
=> [1210] Update courses table

app/views/layouts/_footer.html.erb, app/views/sites/_site.html.erb, app/views/sites/index.html.erb, spec/features/locations/index_spec.rb
Edit training locations
Add link to edit training locations
!DO NOT MERGE!
=> [1262] Add link to edit training location

app/views/courses/index.html.erb
Breadcrumbs
Add `organisations` into breadcrumb on courses#index
/courses
=> [1284] Show org in breadcrumb on courses index

app/views/providers/show.html.erb, spec/features/providers_spec.rb
Courses table
Link to the rails courses#index instead of c# version
`/organisations/2AT` click "courses"
=> [1236] update courses index link

app/views/courses/_course_table_row.html.erb, spec/features/courses/index_spec.rb
Add a test for the `empty` content_status which is the default for a course AFAICT.
=> [1286] Always show publish status

app/views/sites/edit.html.erb
If a user has multiple providers they should see the full breadcrumb.
=> Add organisations to edit location breadcrumb

app/helpers/course_helper.rb, app/views/courses/_content_status_tag.html.erb, app/views/courses/_course_table_row.html.erb, spec/helpers/course_helper_spec.rb
* Make sure supporting text actually shows (fixes https://github.com/DFE-Digital/manage-courses-frontend/pull/180#pullrequestreview-225403845)
* Stop unpublished changes status from wrapping
=> Fix findable and publish status table columns

app/controllers/courses_controller.rb, app/helpers/course_helper.rb, app/views/courses/show.html.erb, app/webpacker/stylesheets/application.scss, spec/factories/courses.rb, spec/features/courses/delete_spec.rb, spec/features/courses/show_spec.rb, spec/features/courses/withdraw_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
We need to show further information about the course.
Populates the course basic details page with info from the course object.
This is a first PR that does most of the work and I aim to come back with separate PRs for the rest of the fields. We should merge this sooner than later to prevent it from growing and becoming harder to review.
=> [1253] Initial course page basic details

app/controllers/courses_controller.rb, app/helpers/course_helper.rb, app/views/courses/show.html.erb, spec/factories/courses.rb, spec/features/courses/delete_spec.rb, spec/features/courses/show_spec.rb, spec/features/courses/withdraw_spec.rb, spec/helpers/course_helper_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
We need to expose all the things.
Use the `funding` field which is now being passed in from the backend.
We don't have a request spec for the presence of the `apprenticeship` in the frontend and the hiding of the other two but ehhhh.
=> [1317] Display course apprenticeships and funding

app/helpers/course_helper.rb, app/views/courses/show.html.erb, spec/factories/courses.rb, spec/features/courses/show_spec.rb, spec/helpers/course_helper_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
We need to expose all the course information on the courses show page.
- Present applications_open in courses show view
When `applications_open_from` is set to null on the API, for example for courses that don't have any findable site statuses, the frontend will display the `Applications open` info but there will be an empty
string.
Almost there!
=> [1315] Display applications_open in courses show

app/helpers/course_helper.rb, app/views/courses/show.html.erb, spec/factories/courses.rb, spec/features/courses/show_spec.rb, spec/helpers/course_helper_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
We need to surface all course information to the user.
- Presents `SEND` status in the courses show page
Thanks @dankmitchell for writing this up, I'm just opening the PR. :)
=> [1321] Display course SEND

app/views/courses/show.html.erb, app/webpacker/stylesheets/_course-tabs.scss, app/webpacker/stylesheets/application.scss
We need to present the basic details on the frontend, and the enrichment information on the ui.
- Wrap courses table with tabs component
- "Description" tab directs to manage-courses-ui.
Review without whitespace changes.
=> [1328] Wrap courses table with tabs component

app/views/courses/show.html.erb, spec/factories/courses.rb, spec/features/courses/show_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
We need to display all the fields in the courses show page.
Use the `level` from the API.
🚢
=> [1326] Display course level in courses show page

app/models/course.rb, app/views/courses/_course_table_row.html.erb, spec/features/courses/index_spec.rb
> In user research, publishers were confused when seeing ‘not running’ in the UCAS status and ‘Published’ in the content status column of the courses table. 
- Don't render `content_status` if course is "Not running"
=> [1342] hide content status if course is not running

app/views/courses/show.html.erb, spec/factories/courses.rb, spec/features/courses/show_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
Course Subjects
Show course subjects on the basic details tab. These courses are generated from the Subjects Mapper.
=> [1320] Add DfE subjects to show details

app/views/courses/show.html.erb, spec/features/courses/show_spec.rb
Subjects aren't ordered alphabetically on the course page. They also aren't shown one per line.
Show subjects in alphabetical order, and one per line.
=> [1349] Show subjects in alphabetical order, one per line

config/initializers/filter_parameter_logging.rb
To prevent personally identifiable user info to be logged unnecessarily.
=> [1356] Filter out sensitive user params from log

app/controllers/sessions_controller.rb, spec/factories/users.rb, spec/features/sign_in_spec.rb
https://trello.com/c/6AtQ386u/1353-only-redirect-users-to-the-transition-info-screen-if-they-have-any-optedin-providers
Only opted-in users should see the transition page.
Check that a user is opted-in before redirecting them to the transition page.
Example - `http://localhost:3001/api/v2/users/10345`
See https://github.com/DFE-Digital/manage-courses-backend/pull/294
=> [1353] only show transition_info page if user is opted in

app/controllers/application_controller.rb, spec/controllers/sessions_controller_spec.rb
These seem to persist across connections. Needs confirming though.
This makes sure that we never leave bearer tokens in after a request.
=> Add an after action that removes bearer token

app/views/courses/_basic_details_tab.html.erb
This has been moved from manage-courses-ui because manage-courses-frontend is now displaying the basic details.
Haven't written tests because this is all going away in a week.
=> [1360] Display information for non opted in providers

app/controllers/application_controller.rb, app/controllers/courses/vacancies_controller.rb, app/controllers/courses_controller.rb, app/controllers/errors_controller.rb, app/controllers/pages_controller.rb, app/controllers/providers_controller.rb, app/controllers/sessions_controller.rb, app/controllers/sites_controller.rb, app/controllers/users_controller.rb
By default we don't authenticate users on frontend, but almost every controller explicitly authenticates users.
Authenticate users by default, and skip it where needed.
=> DRY controller authentication and auth by default

config/initializers/omniauth.rb
When a session expires, the Omniauth middleware throws an exception. We should redirect users to signin when this happens.
Adds try/catch to relevant part of Omniauth initialiser.
I'm not sure if the `ActionController::InvalidAuthenticityToken` is just for CSRF issues (possibly what I was testing with locally) or for any kind of expired auth.
Have tested this locally by going to the `/transition-info` page, logging out in a separate tab, and clicking the green button.
=> [1325] Redirect expired DFE sessions to signin again

app/controllers/application_controller.rb, config/settings/development.yml, spec/controllers/application_controller_spec.rb
We need to send the DfE-SignIn ID to the backend so we're not relying on only email for user lookup.
- Send DfE-SignIn ID to the backend in the JWT payload
- Remove special token handling in development to match backend changes
Tested on MacOS Mojave 10.14.4. (For real this time, it works!)
=> [1337] Send DfE-SignIn ID to backend

app/helpers/provider_helper.rb, app/views/courses/index.html.erb, app/views/sites/index.html.erb, config/settings.yml, spec/features/courses/index_spec.rb, spec/features/locations/index_spec.rb, spec/helpers/provider_helper_spec.rb
We use Google forms to allow publishers to submit certain information to us. Google permits pre-populating the forms which reduces the data entry burden on the publisher, and improves the quality of the data submitted to us.
- Add code for constructing Google form links which pre-populate provider code and publisher email on:
- the 'add new course' form
- the 'add new location' form
- Introduce extra settings which are used to construct the pre-population URLs
- Stub some of the feature specs at a lower level, so that the user email is available in the templates
This makes the Google form link building a bit more complex, but hopefully that's all encapsulated in the helper.
=> [1369] Pre-populate Google forms

app/views/courses/index.html.erb, app/views/providers/show.html.erb, app/views/sites/_site.html.erb, app/views/sites/edit.html.erb, spec/features/courses/index_spec.rb, spec/features/locations/edit_spec.rb, spec/features/locations/index_spec.rb, spec/site_prism/page_objects/page/location_page.rb, spec/site_prism/page_objects/page/locations_page.rb, spec/site_prism/page_objects/page/organisations/courses.rb, spec/site_prism/page_objects/page/organisations/organisation_page.rb
#228 was merged without using page objects in any of the changed code. This PR is cleaning this up.
- add some extra structure into the templates to make testing easier/more robust
- push selectors out of the feature specs and into page objects
=> [1369] Clean up feature specs with page objects

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb
The frontend will blow up if the API returns a 400 or a 500. The API will return 4xx when the user is already transitioned, and 500 for a variety of reasons.
Ensure users are always directed to the providers page.
The spec could be dried out, suggestions welcome!
=> [1372] Handle client / server errors on accept_transition_info

app/decorators/course_decorator.rb, app/views/courses/_course_table_row.html.erb
Product review.
Pass in the provider to `not_on_find` so that it can work in the courses index page, where courses do not have a provider attached to the `object`.
The existing tests already unit test this functionality; arguably this could do with an integration test.
=> [1383] Fix course.on_find decorated method

app/models/course.rb, app/views/courses/_status_panel.html.erb, app/views/courses/status_panel/_published.html.erb, app/views/courses/status_panel/_unpublished.html.erb, spec/features/courses/description_spec.rb, spec/site_prism/page_objects/page/organisations/course_description.rb
Preview unpublished course
- Render preview link if course is not published
- Hide vacancies info if course is not published
- Hide applications status if course is not published
=> [1384] add course preview link

app/decorators/course_decorator.rb
Course content status
- Typo in how `content_tag_unpublished` was being added to `content_status_badge`
- Remove `&nbsp;` as i'm unsure of its purpose...
=> [1383] Fix content status in decorator

app/decorators/course_decorator.rb, app/views/courses/_course_table_row.html.erb, app/views/courses/_status_panel.html.erb, spec/features/courses/description_spec.rb, spec/site_prism/page_objects/page/organisations/course_description.rb
Course content status after decorator change which introduced this bug
- Continue to hide course content status "badge" in the courses table
- Always show the course content status "badge" in the status panel on /description
=> [1383] Always show content status in status panel

app/decorators/course_decorator.rb, app/views/courses/_course_table_row.html.erb, app/views/courses/_status_panel.html.erb, spec/features/courses/description_spec.rb, spec/site_prism/page_objects/page/organisations/course_description.rb
Naming is hard
`content_tag` is a helper in rails so this code is confusing to read
Rename to `status_tag`
=> [1383] rename content status tag

.rubocop.yml, Gemfile, Gemfile.lock, Guardfile, README.md
This allows us to automatically run rspec on files that have changed. Uses spring so they run faster.
Add guard-rubocop, and ignore generated files when running rubocop.
=> [1409] Add guard

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, spec/features/sessions_spec.rb, spec/support/helpers.rb
https://trello.com/c/s3cyWAso/1415-dont-always-redirect-to-root-on-sign-in
On sign-in users would be redirected to `/` no matter where they were originally going.
Save where users were going before the sign-in and send them there after they are signed in. If not saved for any reason, they will still go to `/`.
=> [1415] redirect users back to where they were going on signin

app/controllers/application_controller.rb, app/models/base.rb, spec/controllers/application_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/features/backend_requests_spec.rb, spec/support/helpers.rb
https://trello.com/c/OnBKJMq6/1302-authorization-failure-when-updating-site-statuses
Apparently Faraday is not thread-safe and the way we were setting the
authorization token on the connection was opening us up to a race condition.
This plugs that hole by using the Thread key-value context to save the user
token, and using that when we generate the connection to mcb.
This PR requires #242 and is based off of that one.
=> [1302] fix authorization errors

app/views/courses/status_panel/_unpublished.html.erb, spec/features/courses/description_spec.rb, spec/site_prism/page_objects/page/organisations/course_description.rb
Follow up to https://github.com/DFE-Digital/manage-courses-frontend/pull/233
- Fix URL of course preview
- Add spec to check when it should and shouldn't be shown
A course /description page
=> [1384] Fix preview link and test presence

app/controllers/application_controller.rb, app/controllers/providers_controller.rb, app/views/providers/show.html.erb, spec/controllers/providers_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/users.rb, spec/features/backend_requests_spec.rb, spec/features/courses/delete_spec.rb, spec/features/courses/description_spec.rb, spec/features/courses/index_spec.rb, spec/features/courses/show_spec.rb, spec/features/courses/vacancies/edit_spec.rb, spec/features/courses/withdraw_spec.rb, spec/features/locations/edit_spec.rb, spec/features/locations/index_spec.rb, spec/features/providers_spec.rb, spec/features/sessions_spec.rb, spec/features/sign_in_spec.rb, spec/features/view_pages_spec.rb, spec/requests/courses/vacancies/edit_spec.rb, spec/support/helpers.rb
The tests mock out too much of the auth flow, they were too far from reality.
Change the tests to perform auth, only mocking out the data we get back from DfE-SignIn via OmniAuth.
=> [1419] Remove return URL hack from specs

app/controllers/providers_controller.rb, spec/requests/providers_spec.rb
Showing the user nice a 404 page when record not found - https://github.com/DFE-Digital/manage-courses-backend/pull/332
- Rescue `JsonApiClient::Errors::NotFound` and render our nice 404 page
Example `https://localhost:3000/organisations/T9`
=> [1431] Render the 404 page when provider not found

app/controllers/sessions_controller.rb, spec/requests/sessions_spec.rb
If a user session has expired making `current_user` is nil then a user attempts to signout from DfE-Signin a server error is thrown because DfE-Signin requires the users `id_token` which is stored in the `current_user` object
Check for the presence of `current_user` and redirect to root as their session has already expired
Do we need to think about a more robust strategy for this i.e. persist the `id_token` on the user when the signin?
Delete the session in your browser and hit `signout`
=> 1422 redirect to root if timed out user attempts to signout

app/controllers/courses_controller.rb, spec/features/courses/show_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
Users are getting 500 errors when a course does not exist.
Give the users a 404 biscuit instead of 500s.
=> [1442] return 404 when a course does not exist

app/controllers/application_controller.rb, app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb, spec/features/view_pages_spec.rb
Currently, the users get a blank page. This is an improvement.
The test I wrote resides in `view_pages_spec.rb ` which is probably not the best place?
=> [1444] Rescue from 500s by showing the generic 500 page

app/decorators/course_decorator.rb, app/models/site_status.rb, app/views/courses/_basic_details_tab.html.erb, spec/factories/site_statuses.rb, spec/features/courses/show_spec.rb
The course basic details view is currently showing sites (through site statuses) that are not-running
- Render site status "status" that are NOT running
- Sort sites by location name
=> [1430] Only display running site locations

app/controllers/courses_controller.rb, app/views/courses/about.html.erb, config/routes.rb, spec/features/courses/about_spec.rb, spec/site_prism/page_objects/page/organisations/course_about.rb
Re-creating `/organisation/2cf/course/self/2yn6/about` in rails
Add `/about` to a course
> This is a "dumb" read only form at present because there is some backend work todo 
c# | rails
:--:|:--:
=> [1459] Add course about form

app/views/courses/_status_panel.html.erb
Deleting doesn't remove a course from Find. If a course is on Find you can't delete it.
Keep the delete heading for screenreaders.
=> Update delete link to match design

app/controllers/courses_controller.rb, app/views/courses/requirements.html.erb, config/routes.rb, spec/features/courses/requirement_spec.rb, spec/site_prism/page_objects/page/organisations/course_requirements.rb
Re-creating `/organisation/2cf/course/self/2yn6/requirements` in rails
Add `/requirements` to a course
> This is a "dumb" read only form at present because there is some backend work todo 
c# | rails
:--:|:--:
=> [1462] Add course requirements and eligibility edit page

app/controllers/courses_controller.rb, app/views/courses/_course_length.html.erb, app/views/courses/fees.html.erb, app/views/courses/salary.html.erb, config/routes.rb, spec/features/courses/salary_spec.rb, spec/site_prism/page_objects/page/organisations/course_salary.rb
Re-creating `/organisation/2cf/course/self/2yn6/salary` in rails
Add `/salary` to a course
> This is a "dumb" read only form at present because there is some backend work todo 
c# | rails
:--:|:--:
=> [1461] Add course salary edit page

config/settings/production.yml
Use https://find-postgraduate-teacher-training.education.gov.uk instead of https://www.find-postgraduate-teacher-training.service.gov.uk.
`https://www.find-postgraduate-teacher-training.service.gov.uk` works but isn't the official URL yet.
The [start page](https://www.gov.uk/guidance/find-postgraduate-teacher-training-courses-in-england) on GOV.UK links to https://find-postgraduate-teacher-training.education.gov.uk
=> Use live search URL

app/controllers/application_controller.rb, config/application.rb, spec/controllers/users_controller_spec.rb, spec/features/view_pages_spec.rb
Better solution, turn on the relevant Rails flag.
Tests removed because there's no point in testing Rails itself.
=> [XXXX] Only display the 500 page in production mode

app/controllers/sessions_controller.rb, spec/controllers/sessions_controller_spec.rb
Our cookies were getting too big. With all the auth info from DSI (DfE Sign In) + encryption + some extra stuff, it overflows.
We only use the DSI ID, email, first and last name, and the ID token, the rest of the data we get from DSI we don't use
Only save the data we need from DSI, throw the rest away. This makes the cookie much smaller.
I want to refactor this badly, but I'm holding off so I can finish the factories. I'm hoping we can replace much of this code with a shared DSI gem.
=> [1485] Reduce cookie size

Gemfile, Gemfile.lock, spec/controllers/sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/factories/user_factory.rb, spec/features/courses/index_spec.rb, spec/features/locations/index_spec.rb, spec/features/sign_in_spec.rb, spec/support/define_factory_jsonapi_render_methods.rb, spec/support/helpers.rb, spec/support/initialize_factory_serializers.rb
Using the `jsonapi-rb` gems to render JSONAPI responses based on our factories. 
A few lines of metaprogramming magic to create serializers and make our models able to turn themselves into JSONAPI hashes.
TODO:
* Still need to do this for the rest of the factories (should be easy)
* Relations (easy to add in)
* Custom meta attributes (might be easier to declare the serializers manually for these)
* Need to support the `includes` parameter (should be easy)
* Need to figure out how to make this work with `build_list` (a bit of a pain)
=> [1458] Switch factories to use the JSONAPI renderer

app/helpers/view_helper.rb, app/views/layouts/_footer.html.erb, app/views/providers/show.html.erb
Some users struggle to use mailto links, either they don't have an email client set up on their machine or they don't know how to get the email from the link.
Expose the email address so it's easier to copy and paste for everyone.
The address is long, so allow it to wrap before the '@'
Side column on an organisation page and in the footer
=> Expose email address for copying and pasting

app/controllers/courses_controller.rb, app/views/courses/salary.html.erb, spec/features/courses/salary_spec.rb, spec/requests/courses/salary_spec.rb
Copying course length and salary content
Add "Copy from" select to enable users to copy content from another course within their org
Example - `/organisations/2AT/courses/3CXD/salary`
=> [1476] copy course length and salary content

app/controllers/pages_controller.rb, app/views/pages/new_features.html.erb, app/views/providers/show.html.erb, config/routes.rb, spec/features/view_pages_spec.rb
Give context to users about what we are working on and when they can expect these features.
* Add a `/new-features` page
* Link to it from the organisation page
I want the page to have a `Back` link that returns them to the organisation page they came from but couldn’t work out how to do this.
Draft PR because we might need to update the content based on feedback from @mtbleary and @benilovj 
https://trello.com/c/jnhDmnAQ/1471-create-page-for-roadmap
=> [1471] Add a new features page

app/views/pages/new_features.html.erb, spec/features/view_pages_spec.rb, spec/site_prism/page_objects/page/new_features_page.rb
Follow-on to #281.
- introduce a siteprism pageobject for the `/new-features` page
- update recently shipped feature
=> [1571] 'New feature' page updates

app/views/courses/_basic_details_tab.html.erb, app/views/courses/_status_panel.html.erb, app/webpacker/stylesheets/application.scss
The top border clashed with the new tab styles. Brings the sidebar inline with prototype design.
=> Remove blue border from sidebar

app/views/courses/preview.html.erb, app/views/courses/preview/_qualification.html.erb, app/views/courses/preview/qualification/_pgce.html.erb, app/views/courses/preview/qualification/_pgce_with_qts.html.erb, app/views/courses/preview/qualification/_pgde.html.erb, app/views/courses/preview/qualification/_pgde_with_qts.html.erb, app/views/courses/preview/qualification/_qts.html.erb, app/webpacker/stylesheets/_definition-list.scss, app/webpacker/stylesheets/application.scss, spec/factories/courses.rb, spec/factories/providers.rb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
Course preview
Add meta data to course preview
Example - `/organisations/2AT/courses/3CXD/preview`
=> [1483] Add course meta to preview page

app/models/site.rb, app/views/sites/_form.html.erb
Label for address2 should match the field for address2.
Also fix a typo in the regions.
<h3>Other important notes</h3>
PR number 300 💯 💯 💯
=> [XXXX] Fix incorrectly matched location form label

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/lib/govuk/markdown_renderer.rb, app/views/courses/preview.html.erb, app/views/courses/preview/_about_course.html.erb, app/webpacker/stylesheets/application.scss, spec/features/courses/preview_spec.rb, spec/lib/govuk/markdown_renderer_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
Course preview
- Setup course preview contents nav
- Add about course content
- Add markdown and a nice parser from [GDS RE team](https://github.com/alphagov/re-rotas/blob/master/app/lib/rotas/markdown_renderer.rb)
Example - `/organisations/2AT/courses/3CXF/preview`
=> 1483 course preview about course

app/models/provider.rb, app/views/courses/preview.html.erb, app/views/courses/preview/_advice.html.erb, app/views/courses/preview/_contact_details.html.erb, spec/factories/providers.rb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
Course preview
Add provider contact details to course preview
=> [1483] Add provider contact details to course preview

app/views/sites/edit.html.erb, app/views/sites/index.html.erb, app/views/sites/new.html.erb
Users need to contact us to assign locations to a course – we should tell them this in the places they might look for it.
This is especially true when adding a course.
* Add links to support on edit, new and index pages for locations
* Improve context setting for locations on index and new
* Check the email subjects
=> Add messaging around our location features

app/views/courses/preview/_about_the_provider.html.erb, app/webpacker/stylesheets/application.scss, spec/factories/courses.rb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
Frontend work to https://github.com/DFE-Digital/manage-courses-backend/pull/425 which needs to be merged before this
Add `about accrediting body` to course preview
Any course preview page with an accrediting body
=> [1438] Add about accrediting body to course preview

.rubocop.yml, app/controllers/courses/sites_controller.rb, app/decorators/course_decorator.rb, app/views/courses/sites/edit.html.erb, config/routes.rb, spec/features/courses/sites/edit_spec.rb
Prerequisite to adding the ability for users to edit locations attached to a course.
Adds the template, action, and route.
TODO:
=> [1511] Allow users to see locations attached to a course

config/settings/qa.yml
Update QA settings so that the Azure DevOps deployed QA environment can be used in place of the Travis CI deployed environment.
Supersedes: https://github.com/DFE-Digital/manage-courses-frontend/pull/295
Update QA yaml file
=> Updated QA base URL's

app/views/courses/_copy_content_warning.html.erb, app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb
Move copied fields out of partial and into parent calling the partial to better split the responsibility between the templates.
_copy_content_warning.html.erb now doesn't have logic that's specific to the about/fees/req's/salary forms.
=> [1505] Refactor copy content warning

app/controllers/courses_controller.rb, spec/features/courses/about_spec.rb
We were seeing an error when accessing the enrichment pages for a course offered by a school direct provider (ie one with no self-accredited courses):
* /requirements
* /about
* /salary
* /fees
```
undefined method `reject' for nil:NilClass
```
Example path:
`/organisations/1XO/courses/2FPL/salary`
- Added a failing test
- Fixed with a safe navigation operator
=> [1577] Fix error on enrichment pages when there are no self accredited courses

app/controllers/courses/sites_controller.rb, app/controllers/courses_controller.rb, app/decorators/course_decorator.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/sites/edit.html.erb, app/webpacker/stylesheets/_success-summary.scss, config/routes.rb, spec/factories/courses.rb, spec/features/courses/about_spec.rb, spec/features/courses/delete_spec.rb, spec/features/courses/description_spec.rb, spec/features/courses/fees_spec.rb, spec/features/courses/preview_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb, spec/features/courses/show_spec.rb, spec/features/courses/sites/edit_spec.rb, spec/features/courses/withdraw_spec.rb, spec/requests/courses/about_spec.rb, spec/requests/courses/fees_spec.rb, spec/requests/courses/requirements_spec.rb, spec/requests/courses/salary_spec.rb, spec/requests/courses_spec.rb, spec/site_prism/page_objects/page/organisations/course_locations.rb
This allows users to add locations to a course.
Creates the `courses/sites#update` action and wires up the form to `PUT` to it. This assigns the selected sites to the payload and then `saves` it.
Validation errors:
Success:
=> [1513] Hook up edit locations form

app/views/courses/_copy_content_warning.html.erb, app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb
Follow up to https://github.com/DFE-Digital/manage-courses-frontend/pull/332
- Send "course name" and "course code" into copy warning summary partial
- Only render the summary box when there is actually content being copied
- Only render deep links for content that's been copied
Example - `https://localhost:3000/organisations/2AT/courses/35L7/about?utf8=%E2%9C%93&copy_from=35L6` Message in the summary box should have course code `35L6`
=> [1578] Fix copy content summary message

app/controllers/courses/sites_controller.rb, spec/features/courses/sites/edit_spec.rb
Updating locations on courses is on dev but broken.
I switched from using `.to_i` in both places to only doing it on the `selected_site_ids` in a previous refactor, and did not notice it broke functionality. This adds more tests to make sure we send the right payload to the API.
=> [1513] Don't .to_i selected_site_ids in course locations update

azure-pipelines.yml
Since https://github.com/DFE-Digital/manage-courses-frontend/pull/336 the RSpec results xml is not generated therefore the results can't be published to Azure DevOps
Include export of results xml and format for import using PublishTestResults task
Tidy up formatting so it's a valid JUnit XML file
=> Add rspec results export

app/controllers/courses/sites_controller.rb, app/views/courses/sites/edit.html.erb
If a course is running - ie it's on Find – then changes to the locations will go live immediately. We previously based this on the enrichment status.
=> [1588] Indicate if locations changes will be published

app/views/courses/about.html.erb, app/views/courses/requirements.html.erb
Update page titles so they are specific. Follow the same format as the titles on fees and salary pages.
=> Fix titles on About this course and Requirements course enrichment pages

app/controllers/courses/sites_controller.rb, app/views/courses/sites/edit.html.erb, spec/features/courses/sites/edit_spec.rb
This will allow us to display an appropriate error message on the frontend when the user submits an empty array of sites.
=> [1580] Display validation errors when editing course locations

app/controllers/courses_controller.rb, app/views/courses/_copy_content_warning.html.erb, app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, spec/requests/courses/about_spec.rb, spec/requests/courses/fees_spec.rb, spec/requests/courses/requirements_spec.rb, spec/requests/courses/salary_spec.rb
Previously, in the live rails version, if a field was empty in the course being copied, it would cause that field to be emptied in the new course.
In the C# version if the field was empty in the course being copied, then that field would be left alone.
The C# version was correct.
* Move the logic for checking if a value is present out of view and into controller
* Only set values on the destination course if present in the source course
* Add a test to illustrate
* Test by copying from courses where only some data is available, but into courses that are otherwise complete (eg add something to an empty course and copy that to a published one).
* Seems like the copy course features are in the `spec/requests` when I'd expect to find them using SitePrism in `spec/features`. I've avoided …
=> [1584] When copying course fields, don't blank a field if the source was blank

app/views/courses/description.html.erb, app/views/courses/sites/edit.html.erb, spec/features/courses/description_spec.rb, spec/features/courses/sites/edit_spec.rb
They should contain "Error:" in case of validation errors, for better accessibility.
=> [1580] Update courses description and locations edit titles

spec/features/courses/sites/edit_spec.rb
In #348 the link to edit locations was fixed, but that PR didn't add in extra spec coverage that would have exposed the error.
Start the edit location journey on the course page, which then exercises the link.
=> [1512] 'Edit locations' link coverage in feature spec

app/controllers/courses_controller.rb, app/views/courses/description.html.erb, app/views/courses/fees.html.erb, spec/factories/courses.rb, spec/features/courses/description_spec.rb, spec/features/courses/fees_spec.rb, spec/requests/courses_spec.rb, spec/site_prism/page_objects/page/organisations/course_fees.rb
This is a precursor PR to this whole story. Although it does implement most of the functionality, it's still missing a couple of things that will be done separately.
This will unblock similar work that needs to be done on a few other forms.
The fee form was wired up to post to the publish endpoint. We added an
update action to the course controller and wired up the fees form to use
that instead.
Paired with Sau and Tim.
Validations are blocked by the backend implementing validation on update. Right now they only fire on publish.
=> [1480] Wire up course length and fees form to update course

app/views/courses/about.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, spec/features/courses/about_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb, spec/site_prism/page_objects/page/organisations/course_about.rb, spec/site_prism/page_objects/page/organisations/course_requirements.rb, spec/site_prism/page_objects/page/organisations/course_salary.rb
Allowing the user to update "about course"
The about form was wired up to post to the publish endpoint. We added an
update action to the course controller and wired up the fees form to use
that instead.
Validations are blocked by the backend implementing validation on update. Right now they only fire on publish.
=> [1478] Wire up update for about course

app/controllers/courses/sites_controller.rb, app/controllers/courses/vacancies_controller.rb, app/models/course.rb, spec/features/courses/sites/edit_spec.rb, spec/features/courses/vacancies/edit_spec.rb
The frontend doesn't necessarily know when a course is due to be synced with search-and-compare, the concern for that knowledge should be in the backend.
=> [1608] Don't sync when editing locations or vacancies

app/views/courses/_description_content.html.erb, app/views/courses/description.html.erb, app/webpacker/stylesheets/application.scss, spec/features/courses/description_spec.rb, spec/site_prism/page_objects/page/organisations/course_description.rb
On the C# version – a Not running course has no status column and a warning message:
https://bat-dev-manage-courses-ui-app.azurewebsites.net/organisation/2AT/course/self/35L7
We need to do the same thing in Rails:
https://bat-dev-manage-courses-frontend-app.azurewebsites.net/organisations/2AT/courses/35L7/description
* Hide status column
* Be more explicit about course states in description feature spec
* Show a warning message
* Fix heading sizes
=> [1611] Hide the status panel on Not running courses

app/views/courses/_description_content.html.erb, spec/features/courses/about_spec.rb, spec/features/courses/description_spec.rb, spec/features/courses/fees_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb
Allow users to edit course enrichments in rails and not c#
Update individual enrichment page links to point to our rails app
Example `/organisations/2AT/courses/35L7/description`
=> Update course enrichment links

app/views/courses/sites/edit.html.erb, spec/features/courses/sites/edit_spec.rb
Sort locations alphabetically but avoids refactoring the sorting into a new provider decorator.
=> [1615] Sort sites alphabetically when assigning to courses

app/controllers/courses/vacancies_controller.rb, app/models/course.rb, spec/features/courses/vacancies/edit_spec.rb
We removed this because we were planning on implementing it on the backend, but we're thinking about including it back in temporarily.
=> [1608] Sync courses when updating vacancies

app/views/courses/vacancies/edit.html.erb
Order the list of locations by name when editing vacancies
=> Sort site statuses by name

app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb
Cancel links on course enrichment pages
Update links to go back to the description page instead of the basic details page
Check links on `/about`, `/fees`, `/salary`, `/requirements`
=> [1617] Fix course enrichment cancel links

spec/features/courses/about_spec.rb, spec/features/courses/fees_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb, spec/site_prism/page_objects/page/organisations/course_about.rb, spec/site_prism/page_objects/page/organisations/course_fees.rb, spec/site_prism/page_objects/page/organisations/course_requirements.rb, spec/site_prism/page_objects/page/organisations/course_salary.rb
We had some request specs but no end to end tests for copying enrichments.
* Add interactions for selecting a course and copying it
* Checks the warning message shown
* Checks the correct values were copied
* Fixes existing checks by looking for `.value` rather than `.have_content` on an `input`
Follow up to #344
=> [xxxx] Add feature specs for copying each type of enrichment

app/controllers/courses_controller.rb, spec/factories/courses.rb
Due to the way we use the factories, it's difficult to set the
provider_code on the course without causing an endless loop.
Also, setting provider_code on the course factory gets overwritten by
the provider being set to nil in the factory, and removing that breaks
things.
This is further broken by a bug in the JSONAPI client.
Added workaround for broken factories/jsonapi client.
Removed workaround for `provider_code` not being in responses.
I cleaned up the test affected, some of that is unrelated to these changes, sorry.
=> [1610] Add provider code to course factory

app/controllers/courses_controller.rb, spec/requests/courses/about_spec.rb
```
Follow-up story to #1480, #1478, #1482, #1481. The forms were all wired up correctly but we're not actually passing the data over to the backend so it's failing to save since the params are `nil`
```
Pass course params over to the backend
Make a change to a course enrichment and hit save
=> [1681] Fix enrichment updates

app/controllers/courses_controller.rb, spec/factories/errors.rb
This is being removed from the API, as it causes pointers to not be associated correctly.
Depends on:
- https://github.com/DFE-Digital/manage-courses-backend/pull/497
Remove the `latest_enrichment__` prefix from course enrichment errors.
=> [1624] Don't strip latest_enrichment__ from enrichment errors

app/controllers/sites_controller.rb, spec/factories/errors.rb
These are now being sent from the API with correct formatting and can be directly displayed in the frontend.
Remove `map_errors`.
=> [1624] Simplify site validation errors

app/views/sites/_error_messages.html.erb, app/views/sites/_errors.html.erb, app/views/sites/_form.html.erb, spec/factories/errors.rb, spec/features/sites/edit_spec.rb
These were being "swallowed" by the template. Part of refactoring validations.
Refactor the errors template so it's DRYer and also iterate through all the errors being passed in.
Also tweak the Name heading so that it doesn't have an awkward space between it and the validation error underneath.
=> [1624] Display all site validation errors

app/views/courses/about.html.erb, app/views/courses/delete.html.erb, app/views/courses/fees.html.erb, app/views/courses/preview/_apply.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, app/views/courses/status_panel/_unpublished.html.erb, app/views/courses/withdraw.html.erb
Refactoring to prepare for validations.
The necessity of this is because when you do a `@course.update`, and it fails, the `@course.provider` is blatted away because the response from the backend API does not contain a provider, only course info. The provider info is still available in the `@provider` though.
This is also terser.
I have not manually tested this and am relying on the fact that none of these pages are live yet and mostly have coverage.
=> [1624] Refer to @provider instead of course.provider in html

app/controllers/courses_controller.rb, app/views/courses/_course_length.html.erb, spec/features/courses/fees_spec.rb, spec/site_prism/page_objects/page/organisations/course_fees.rb
Setting "other" course length
Pass across the "other" length into `course_length` when the user has selected it
Try setting "other" for course length
=> [1629] Fix other course length

Gemfile, Gemfile.lock, app/controllers/courses_controller.rb, app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, config/routes.rb, spec/features/courses/about_spec.rb, spec/features/courses/fees_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb, spec/requests/courses/about_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb, spec/site_prism/page_objects/page/organisations/course_about.rb, spec/site_prism/page_objects/page/organisations/course_base.rb, spec/site_prism/page_objects/page/organisations/course_description.rb, spec/site_prism/page_objects/page/organisations/course_fees.rb, spec/site_prism/page_objects/page/organisations/course_locations.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb, spec/site_prism/page_objects/page/organisations/course_requirements.rb, spec/site_prism/page_objects/page/organisations/course_salary.rb, spec/site_prism/page_objects/page/organisations/courses.rb
We need to display validation errors when users save course description fields.
Renders the shared errors template at the top of the about, fees, salary, and requirements pages.
The forms are updated to each contain a hidden field, for the `page` that they correspond to, to allow the `courses#update` action to render the correct page when responding with validation errors.
4 new `patch` routes are created, one for each page. This is because on the regular `update` endpoint, the URL is `/organisations/ORG/courses/CRS`. If a user takes this URL and submits it in the same browser tab, they'll be taken to the basic details, which is confusing.
There will be a follow-up PR to implement the red highlights on the form fields.
=> [1624] Display error summary at top of enrichment pages

app/controllers/courses_controller.rb, app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, spec/features/courses/description_spec.rb
- Back links on enrichment pages linked to the Basic details tab rather than the Description tab
- The success summary on publishing duplicated the publish message
=> Fix success summary and enrichment back links

app/helpers/view_helper.rb, app/views/shared/_form_field.html.erb, app/views/sites/_form.html.erb, spec/helpers/view_helper_spec.rb, spec/site_prism/page_objects/page/location_page.rb
This uses the [capture](https://api.rubyonrails.org/classes/ActionView/Helpers/CaptureHelper.html) feature I recently discovered to create a reusable partial for the site form fields. This will be reused in the enrichment validations.
Simplifies `site/_form` by creating a reusable `_field_with_error` partial / component.
There should already be adequate test coverage for this, this is just a refactor.
If we're happy with this pattern of doing a reusable frontend template, I would like to extend it to other parts of the frontend. In the future, we can switch to [ActionView::Component](https://github.com/rails/rails/pull/36388).
=> [1624] Abstract site form field logic into partial

app/decorators/course_decorator.rb, app/views/courses/_course_length.html.erb, spec/features/courses/fees_spec.rb, spec/features/courses/salary_spec.rb, spec/site_prism/page_objects/page/organisations/course_salary.rb
Fixes:
- Associate label with form field correctly
- Don't prefill field with OneYear or TwoYear special values
- Tweak casing of label and input width
=> [1667] Don't prefill other course length if 1/2 years

spec/features/courses/fees_spec.rb
Make sure that copying custom course lengths is tested and works as expected.
=> Update copy specs to include custom course length

app/controllers/courses/vacancies_controller.rb, app/models/course.rb, app/views/courses/vacancies/_multiple_sites.html.erb, app/views/courses/vacancies/_single_site.html.erb, app/views/courses/vacancies/edit.html.erb, app/views/shared/_errors.html.erb, spec/features/courses/vacancies/edit_spec.rb, spec/requests/courses/vacancies/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_vacancies.rb, spec/site_prism/page_objects/page/organisations/courses.rb
Update the code to match the design:
https://bat-design-history.herokuapp.com/publish-teacher-training/vacancies-iteration-14-jan
We built the complex version of vacancies when we launched the feature, but we didn't return to it to create the simpler toggle. The toggle should be used when there is only 1 site and the course has one study mode.
- Add check for if course is single site/single study mode
- Show a checkbox for toggling vacancies
- Use different update logic and template for single site/single study mode
- Refactor vacancies tests to:
- use SitePrism
- be explicit about the study mode and number of sites when testing a course
| State | No error | With error |
|--|--|--|
| With vacancies |![Screen Shot 2019-06-21 at 14 05 …
=> [1669] Iterate vacancies design for single site/single study mode courses

app/views/pages/new_features.html.erb
Add missing `govuk-link` classes
=> Fix styles on video links

app/views/errors/forbidden.html.erb, app/views/errors/internal_server_error.html.erb, app/views/errors/not_found.html.erb
Update our error page designs to match content in the design system.
Based on:
https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/
https://design-system.service.gov.uk/patterns/page-not-found-pages/
Also makes sure that the support email address is displayed so it can be copied if needed.
=> Update error page design to match design system

app/views/layouts/_footer.html.erb, app/views/pages/cookies.html.erb
Add the missing `govuk-link` class so the text renders in the right colour.
=> Fix Google Analytics link colour

app/controllers/courses_controller.rb, spec/features/courses/index_spec.rb
A couple of providers begin with a lowercase letter, eg e-Qualitas. Courses associated with this accredited body were appearing in a block at the bottom of the page instead of the expected alphabetical position.
|-|-|
| ![Screen Shot 2019-06-25 at 16 16 52](https://user-images.githubusercontent.com/319055/60110848-aeff4700-9764-11e9-834f-7716db5f43a4.png) | ![Screen Shot 2019-06-25 at 16 16 08](https://user-images.githubusercontent.com/319055/60110846-aeff4700-9764-11e9-91a1-349c1aac7248.png) |
=> [1484] Make accredited body sorting case insensitive

app/controllers/sites_controller.rb, spec/features/sites/edit_spec.rb
We shouldn't throw a 500 if the provider doesn't have the specified site ID.
When editing a site it throws a 500 if you mess with an edit location URL and put in a bad ID.
Because it can’t find a site you get:
```undefined method 'location_name' for nil:NilClass```
For example, a bad URL: `/organisations/135/locations/1000000000000/edit`
- Stop the 500
- Show a 404
=> [1298] 404 if site not found

config/settings/new_staging.yml
Update new staging environment to use non-Azure domains
Change base_url value in New_staging.yml file from default azure web app .azurewebsites.net urls to service domains
base_url updated in new_staging.yml file only.  New staging service domain urls are as follows:
mcapi: https://api.staging.publish-teacher-training-courses.service.gov.uk
mcbe: https://api2.staging.publish-teacher-training-courses.service.gov.uk
mcfe: https://www2.staging.publish-teacher-training-courses.service.gov.uk
mcspt: https://support.staging.publish-teacher-training-courses.service.gov.uk
mcui: https://www.staging.publish-teacher-training-courses.service.gov.uk
sacapi: https://api.staging.find-postgraduate-teacher-training.service.gov.uk
sacui: https://www.staging.find-postgraduate-teacher-training.service.gov.uk …
=> Updated base_url to use service domain in new_staging.yml

app/views/courses/_basic_details_tab.html.erb
Content should always read 'grade 4' not 'level 4' as GCSEs are not qualification level 4. Highlighted in a show and tell.
=> [1620] It's grade 4 not level 4

app/controllers/courses_controller.rb, spec/features/courses/preview_spec.rb
Preview page
Include `site_statuses` on the course#preview page because we need to get the `has_vacancies?` method from each site_status
Example - https://localhost:3000/organisations/1CS/courses/2DHM/preview
=> [1698] Fix up sites on preview page

app/models/course.rb, app/views/courses/fees.html.erb
Users are currently unable to save the empty string value on the course fee fields.
This prevents `json_api_client` from typecasting a valid value of '' (empty string) to `0`, which are two separate values in our system. It also removes some weird behaviour, like how `9,000.00` is cast to `9`.
We should revisit our own (or rather, now lack of any) casting and validations to make sure we're doing as much work as we can so that users don't constantly bump into "X is not a number" type errors when they type reasonable values like `£9,000.00`.
[The Design System encourages using input type='text' for currency values](https://design-system.service.gov.uk/components/text-input/). While it is not explicitly stated, it is because type='number' introduces potential accessibility issues.
No tests …
=> [1671] Course fee improvements

app/decorators/course_decorator.rb, app/views/courses/preview/_apply.html.erb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
Whereas on live we want to show only running sites, on preview the course might not be live – when in this state all sites will be in status "new".
- Restrict sites to just those that are new or running
- Add feature spec to check which sites and their vacancies are shown in preview
- Sites that are new or running but have no vacancies still show, but the vacancies column says "No"
- Adds sorting of sites
- Test with a new course
- Test with a running course
=> Only list new or running sites on course preview

app/views/courses/preview/_fees.html.erb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
This was missing from the new preview page.
The new course preview did not include the fee details section.
C#: https://github.com/DFE-Digital/search-and-compare-ui/blob/master/shared/Views/Shared/Components/CourseDetails/_Fees.cshtml#L53-L56
|-|-|
|![Screen Shot 2019-07-02 at 11 53 42](https://user-images.githubusercontent.com/319055/60507482-2a5e7c80-9cc0-11e9-9429-7cefc5a99f30.png)|![Screen Shot 2019-07-02 at 11 53 27](https://user-images.githubusercontent.com/319055/60507483-2cc0d680-9cc0-11e9-976d-57543b32fa89.png)|
- Add some fee details to a course
- Preview it
=> [1712] Add fee details to preview

app/models/course.rb
Rewriting publish validations so they are not as hacky on the frontend and can be displayed on multiple pages.
Write a custom method for the `course.publish` action that allows us to manually pass in an empty `attributes` hash. This is to enable upcoming changes to the backend that will make it associate `pointer`s correctly on the json-api response when publishing.
Tests already exist for this. :shipit:
=> [1664] Replace course publish method

app/views/courses/about.html.erb
Updated guidance from Paul G: https://docs.google.com/document/d/1BtW41GXnlIWPCjDl5AShM-B8Uup_d-9jj53hK1_rKcM/edit
- Move multiple courses in same subject guidance behind a disclosure
- Clarify what must be included and what _could_ be included
=> Tweak guidance for About this course and How placements work

app/controllers/courses_controller.rb, app/helpers/course_helper.rb, app/models/course.rb, app/views/courses/show.html.erb, spec/factories/errors.rb, spec/helpers/course_helper_spec.rb, spec/requests/courses_spec.rb
Making validation errors consistent across the course.
This makes the `@course.publish` method behave more similarly to `.save`, where it automatically populates `@course.errors` with the correct hash of errors. This is only possible now that the backend gives us back `pointer`s on the error object returned from `publish`.
There will be follow-up work to change this from using a flash to doing a `render` instead.
This will break if it's deployed without https://github.com/DFE-Digital/manage-courses-backend/pull/572. We should deploy backend end to end first.
=> [1664] Handle publish errors better

app/views/courses/about.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, app/views/courses/sites/edit.html.erb, app/views/courses/vacancies/edit.html.erb, app/views/sites/edit.html.erb, app/views/sites/new.html.erb, spec/features/courses/sites/edit_spec.rb
Cancel changes should take you back to where you came from – editing course locations is accessed from the details tab.
- Change cancel link destination
- Add `govuk-link--no-visited-state` to cancel links
=> Fix edit course locations cancel link

app/controllers/pages_controller.rb, app/controllers/sessions_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/pages/rollover.html.erb, config/routes.rb, config/settings.yml, config/settings/production.yml, config/settings/staging.yml, spec/controllers/users_controller_spec.rb, spec/factories/user_factory.rb, spec/features/sign_in_spec.rb, spec/site_prism/page_objects/page/rollover.rb
- Show rollover screen to transitioned users
- Continue showing transition screen to users who haven't seen it yet, they'll see this first (still about 60 per week seeing it)
- Only show the rollover screen once per user
- Introduce a new "rolled_over" state
Goes with https://github.com/DFE-Digital/manage-courses-backend/pull/577
We probably want to disable the redirect to the rollover screen until we are ready for it. What's the best way to do that?
=> [1387] Add rollover screen

app/controllers/recruitment_cycles_controller.rb, app/models/provider.rb, app/views/providers/show.html.erb, app/views/recruitment_cycles/_courses_info.html.erb, app/views/recruitment_cycles/_locations_info.html.erb, app/views/recruitment_cycles/show.html.erb, spec/features/courses/index_spec.rb, spec/features/providers_spec.rb, spec/features/sites/index_spec.rb, spec/requests/recruitment_cycles_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_page.rb
Rollover
- Remove courses and site from org show view
- Add a show view for each recruitment cycle for the courses and site
=> [1388] Refactor view for rollover

app/controllers/courses_controller.rb, app/decorators/course_decorator.rb, app/helpers/recruitment_cycle_helper.rb, app/helpers/view_helper.rb, app/views/courses/_course_table.html.erb, app/views/courses/_course_table_row.html.erb, app/views/courses/index.html.erb, config/routes.rb, config/settings.yml, spec/decorators/course_decorator_spec.rb, spec/features/courses/index_spec.rb, spec/helpers/recruitment_cycle_helper_spec.rb, spec/site_prism/page_objects/page/organisations/courses.rb
https://bat-design-history.herokuapp.com/publish-teacher-training/publishing-during-rollover
- Filter courses by recruitment_cycle_year
- During a rollover period, indicate if the courses shown are for the current or next cycle
- Add helpers to determine which cycle is being shown
- Show a slightly different table for the next cycle
- Show a simplified courses table for all cycles after 2019
What's intentionally missing from this PR:
- Breadcrumbs
- A link to a different "Add course" Google form
- Handling of the "Applications" column (depends on what we intend to do with rolled over courses)
- Handling of the courses page when the current cycle becomes a previous cycle
- Modify some local courses to be in the next recruitment cycle in backend, for example:
```ruby
next_cycle = …
```
=> [1394] Courses table for next and current cycles during rollover

app/views/providers/show.html.erb
Link didn't have the `.govuk-link` styling.
Switch `govuk_link_to` helper to `.govuk-link` as `data: {}` is replacing HTML options in helper.
=> [1738] Fix link style

app/controllers/courses_controller.rb, app/helpers/view_helper.rb, app/models/course.rb, spec/features/courses/show_spec.rb, spec/helpers/course_helper_spec.rb, spec/helpers/view_helper_spec.rb, spec/requests/courses_spec.rb
> When users publish a course, they are presented with validation errors. The fields to fix these errors are nested within a different page, such as the `about` page. When users navigate to this page after receiving a `publish` error, they should still see the error so they can correct it.
- Update validation links to navigate to the rails frontend app
- Display validation messages on the individual enrichment pages
- Try and publish an invalid course then click one of the validation message links
=> [1664] Retain enrichment error messages on edit

spec/features/courses/index_spec.rb, spec/features/sign_in_spec.rb
Failing specs found by changing rollover to false and running test suite.
- Correctly set expected rollover setting for each spec context.
- Remove some unnecessary test setup in courses/index_spec rollover context
- Best reviewed commit by commit
- Hide whitespace as some code blocks moved into new contexts
=>  Make sure tests past irrespective of rollover setting

app/views/courses/show.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/form-error-tracking.js
Record form errors/success on publish and send to Google Analytics.
Added the `data-ga-event-form` to error element and pass in values "error" or "success"
=> [1748] Record form errors/success on publish

app/views/courses/show.html.erb, app/webpacker/packs/application.js
Send form errors to GA.
Add `data-error-message` data attribute to error message `li` rather than targeting the inner text of the `li a`
=> [1748] Record the form error messages to GA

app/views/courses/_basic_details_tab.html.erb, spec/features/courses/details_spec.rb
This was showing if applications were open or closed, rather than the date applications opened.
The date applications opened isn't easily available.
Rather than risk showing the wrong information, comment out the section until a bug fix is in place for
https://trello.com/c/l0t1Oun3/
=> [1699][1479] Hide the "Applications open" line on basic details

app/helpers/provider_helper.rb, app/views/courses/index.html.erb, config/settings.yml, spec/features/courses/index_spec.rb, spec/helpers/provider_helper_spec.rb, spec/site_prism/page_objects/page/organisations/courses.rb
Now the new forms are set up, add links to them and pre-fill the correct fields.
Link to the right form based on current or next cycle and accredited or unaccredited providers.
=> [1758] Add URLs and entries for next cycle course forms

app/helpers/breadcrumb_helper.rb, app/views/courses/details.html.erb, app/views/courses/index.html.erb, app/views/courses/show.html.erb, app/views/providers/show.html.erb, app/views/recruitment_cycles/show.html.erb, app/views/shared/_breadcrumbs.html.erb
* DRY up our breadcrumbs with a partial
* Keep breadcrumb logic in one place
Example usage:
```erb
<%= content_for :before_content, render_breadcrumbs(:courses) %>
```
=> DRY up breadcrumbs with a helper and partial

app/views/pages/guidance.html.erb
Add a button to return to the referrer page so that the page no longer feels like a dead end.
Button to return back to the page the user came from no matter where they are.
Should this become a component/partial that we can reuse on other pages? Such as cookies, terms etc.
=> [1678] Added back link to guidance page

config/puma.rb
Rails is meant to extend Time with zone, but hasn't.
Rails isn't running as `config/puma.rb` is run.
Since we're just creating a certificate for dev/local, let's use Time.now.
None
=> Certificate can't be created, Time doesn't have method zone

app/controllers/sites_controller.rb, app/helpers/breadcrumb_helper.rb, app/views/sites/edit.html.erb, app/views/sites/index.html.erb, app/views/sites/new.html.erb, spec/features/sites/new_spec.rb
- Show the full breadcrumb on locations/edit location/add location
- Switch to using the breadcrumbs helper
- DRY up breadcrumb templates on sites pages
=> Show recruitment cycle in sites breadcrumbs

app/views/courses/_status_panel.html.erb, app/views/courses/status_panel/_unpublished.html.erb
Publishing will trigger a sync to `Find` which will currently fail on the server. Until we fix this, we should display some content instead.
Paired with @fofr.
=> [1796] Don't show publish button on rolled over courses

app/decorators/course_decorator.rb, spec/features/courses/show_spec.rb
Rollover
Display new `rolled over` status for users
=> [1800] Extend course content status for rollover

app/views/courses/show.html.erb, spec/features/courses/show_spec.rb
This message incorrectly shows for all saved changes, not just publishing.
This means it shows when editing an unpublished draft, or when editing a course in the new cycle, which is confusing.
As a quick fix, remove the message.
=> Remove "link for this course" message

config/settings/new_prod.yml, config/settings/production.yml, config/settings/qa.yml, config/settings/staging.yml
Allow providers to see the current AND next cycle
Remove overrides and leave the default 'true' for all environments
You should be able to see "cycles" when selecting a provider
> My prettier config is double quotes
=> [1654] Enable rollover across all environments

app/controllers/courses/entry_requirements_controller.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/_entry_requirements.html.erb, app/views/courses/entry_requirements/_subject_choices.html.erb, app/views/courses/entry_requirements/edit.html.erb, config/routes.rb, spec/features/courses/entry_requirements/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_entry_requirements.rb
We are allowing users to edit the UCAS equivalencies for Maths; English and Science. Providers are regularly contacting us through support to edit the equivalencies, often for individual candidates they are wanting to apply.
This is an MVP version of the design to allow us to ship editing sooner:
https://bat-design-history.herokuapp.com/publish-teacher-training/minimum-requirements-read-only-mvp
- Add controller, view and tests for editing entry requirements
- Link to the edit form from the basic details tab
- Depends on https://github.com/DFE-Digital/manage-courses-backend/pull/623 being merged and shipped
PR excludes:
- Validation if no code is provided, this is being handled separately
- Logic around specific requirements of Secondary/Primary/FE courses
=> [1692] Allow providers to edit their UCAS equivalency settings

app/views/providers/details.html.erb, spec/factories/providers.rb, spec/features/providers/details_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_details.rb
Moving provider enrichments to rails 🎉 
Add status panel for provider enrichments
TODO: Add the publish button once we have an endpoint on the backend to call
=> [1783] Add provider enrichments status sidebar

app/controllers/courses/entry_requirements_controller.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/entry_requirements/_subject_choices.html.erb, app/views/courses/entry_requirements/edit.html.erb, spec/factories/courses.rb, spec/features/courses/details_spec.rb, spec/features/courses/entry_requirements/edit_spec.rb
A cleaner approach to https://github.com/DFE-Digital/manage-courses-frontend/pull/473.
Lock down the editing options based on the legal rules
- Base all logic on gcse_required_subjects – DFE-Digital/manage-courses-backend#639
- Only show the required subjects for each course when editing entry requirements
- Don't show any entry requirements if there are none needed for the course and make the edit page 404 if the page is requested
- Remove the "No requirement" option, what is shown is always required
When the entry requirements form is submitted without providing an answer to one of the required subjects, show an error.
Doesn’t yet cover the case where an invalid option is passed in. That'll be a separate PR with a backend one.
=> [1692] Show only required GCSE subjects, includes validation

app/views/courses/_entry_requirements.html.erb, app/views/courses/entry_requirements/_subject_choices.html.erb, config/locales/en.yml, spec/factories/courses.rb, spec/features/courses/entry_requirements/edit_spec.rb
- Pull in options from backend rather than hardcoding
- Use keys to determine labels and help text
Goes alongside https://github.com/DFE-Digital/manage-courses-backend/pull/651
=> Use entry requirement options from backend

app/controllers/courses/outcome_controller.rb, app/decorators/course_decorator.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/outcome/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/decorators/course_decorator_spec.rb, spec/factories/courses.rb, spec/factories/errors.rb, spec/features/courses/details_spec.rb, spec/features/courses/outcome/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_outcome.rb
Allow providers to edit the outcomes of their courses
Depends on https://github.com/DFE-Digital/manage-courses-backend/pull/649
- Stop using the array of qualifications to generate the outcome
- Use the qualification returned from backend to show the one stored in en.yml.
- Removes the only frontend dependency on `course.qualifications` (`['qts', 'pgce']`), favouring `course.qualification` (`pgce_with_qts`).
=> [1827] Allow users to edit a course outcome

app/helpers/application_helper.rb, app/helpers/view_helper.rb, app/views/courses/_description_content.html.erb, app/views/providers/about.html.erb, app/views/providers/contact.html.erb, app/views/providers/details.html.erb, spec/features/providers/details_spec.rb, spec/helpers/application_helper_spec.rb, spec/helpers/view_helper_spec.rb
Some small bits of work I've extracted from the bigger provider publish/validations PR that is forthcoming, to slim it down.
- Add `Error:` to the page titles when errors are present
- Link the details directly to the contact and about pages and vice versa
- Add deep linking capabilities to the `enrichment_summary_item` helper for provider enrichments
Easiest reviewed commit by commit.
=> [1792] Provider enrichment improvements

app/views/courses/preview/_fees.html.erb, spec/features/courses/preview_spec.rb
We need to use the recruitment cycle to show which year the fees are for on course preview.
=> Show correct year against fees in preview

app/webpacker/stylesheets/application.scss
`mailto` links look a bit wonky in IE.
The `<wbr>` tag does not seem to work in some versions of IE. This adds some CSS to patch it up. Copy and pasting still works as expected.
Repro of the fix is deployed at https://ie9-wbr-fix.tvararu.now.sh.
|--------|-------|
| ![Screenshot 2019-08-02 at 15 39 23](https://user-images.githubusercontent.com/1650875/62378208-372ef400-b53c-11e9-97a5-8b74200707b4.png) | ![Screenshot 2019-08-02 at 15 39 38](https://user-images.githubusercontent.com/1650875/62378209-372ef400-b53c-11e9-9ab7-a3c1fc133a13.png) |
=> [1799] Fix <wbr> in IE9

app/controllers/concerns/edit_basic_detail.rb, app/controllers/courses/age_range_controller.rb, app/views/courses/age_range/edit.html.erb
Course age range
- Ensure `age_range_in_years` is present when splitting 
- Add validations for "other"
- Try and save the age range without choosing an option
=> [1886] move validations out of controller

config/settings/qa.yml
Update qa environment to use non-Azure domains
Change base_url value in qa.yml file from default azure web app .azurewebsites.net urls to service domains
base_url updated in qa.yml file only. New staging service domain urls are as follows:
mcapi: https://api.qa.publish-teacher-training-courses.service.gov.uk
mcbe: https://api2.qa.publish-teacher-training-courses.service.gov.uk
mcfe: https://www2.qa.publish-teacher-training-courses.service.gov.uk
mcspt: https://support.qa.publish-teacher-training-courses.service.gov.uk
mcui: https://www.qa.publish-teacher-training-courses.service.gov.uk
sacapi: https://api.qa.find-postgraduate-teacher-training.service.gov.uk
sacui: https://www.qa.find-postgraduate-teacher-training.service.gov.uk
=> updated base_url in config/settings/qa.yml

app/helpers/application_helper.rb, app/views/courses/_description_content.html.erb, app/views/providers/details.html.erb, spec/helpers/application_helper_spec.rb
Display all contact address errors.
- `"field"` to `"fields"` 
- `fields` is now an array rather than a single string
=> [1868] show all contact errors on provider editing

app/views/providers/details.html.erb, spec/features/providers/details_spec.rb
Was falling over with a nil error for new records.
(replaces #508 which had a typo in the branch name)
Handle providers with no published enrichment
Without the patch the updated test now fails
```
$ be rspec spec/features/providers/details_spec.rb -fd
2019-08-08 16:11:34 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrom
e::Service#driver_path= instead.
Run options: include {:focus=>true}
All examples were filtered out; ignoring {:focus=>true}
View provider
with empty provider details
renders correctly (FAILED - 1)
with draft provider details
Checking for expected text of nil is confusing and/or pointless since it will always match. Please specify a string or regexp instead.
renders correctly
with published provider details …
```
=> [1807] Bugfix - hide published-on if never published

config/settings/new_prod.yml, config/settings/new_staging.yml
DfE signin services have multiple env i.e. test, pre-prod and prod. To replicate our development workflow with DfE signin environments, our dev and qa is already pointing to DfE's test env. This change ensures that BAT's new prod and staging is pointing to DfE's prod and pre-prod respectively.   
Update DfE's signin issuer and profile urls to respective environments in yaml files
=> updated dfe sign-in details in config/settings/new_staging.yml file

app/views/providers/show.html.erb
Requesting access has been ported from the old C# application to the new Rails application, but the frontend still links to the old one and needs to be updated.
- Update the request access link to the manage-courses-frontend implementation rather than the C# implementation
=> [1929] Switch request access URL from ui to frontend

app/views/courses/preview/_about_the_provider.html.erb, app/views/courses/preview/_train_with_disabilities.html.erb, app/views/providers/show.html.erb
Links take you back to rails instead of c#
preview page 
- lack of `train_with_us` link takes you back to about provider page
- lack of `train_with_disability` link takes you back to about provider page
show page
- `About your organisation` links takes you to the details provider page
=> [1872] Amended urls to be all rails

app/helpers/view_helper.rb, spec/helpers/view_helper_spec.rb
`#manage_ui_url` is not being used. Remove dead code.
Delete dead code
Double check it is not being used.
=> [1961] Remove `#manage_ui_url` method

app/decorators/course_decorator.rb, spec/features/courses/applications_open/edit_spec.rb
The design is slightly different when the course is part of the current cycle.
=> [1925] Update content for applications open

app/views/courses/_basic_details_tab.html.erb, spec/features/courses/applications_open/edit_spec.rb
There's bugs with this feature so if it's in master, we can't ship frontend.
Hide the link.
This will allow us to ship while we iron out any remaining bugs.
:ship:
=> [1925] Temporarily disable link to edit applications from

app/decorators/course_decorator.rb, spec/features/courses/applications_open/edit_spec.rb
Editing applications open.
The logic was flawed; we should be comparing against the known current
cycle instead of the one being passed in. Updated the test as well.
=> [1925] Update logic for applications open for next cycle

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/applications_open_controller.rb, app/controllers/courses/entry_requirements_controller.rb, app/controllers/courses/outcome_controller.rb, app/controllers/courses/send_controller.rb, app/controllers/courses/start_date_controller.rb, app/controllers/courses/study_mode_controller.rb, app/models/course.rb, app/views/courses/outcome/_form.html.erb, app/views/courses/outcome/edit.html.erb, app/views/courses/outcome/new.html.erb, config/routes.rb, spec/factories/courses.rb, spec/features/courses/new_spec.rb, spec/features/courses/vacancies/edit_spec.rb, spec/models/course_spec.rb, spec/requests/courses/outcome/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_outcome_page.rb, spec/site_prism/page_objects/page/organisations/courses_page.rb, spec/support/helpers.rb
So users can set the outcome on their new course.
- renders same form fields as the edit page
- has a "Continue" button (not wired up yet)
Add "new" page for course outcomes.
This turned into more work than anticipated. I'm willing to put some time in the evenings to address any comments/questions on this PR, but pls keep in mind I'm trying to be on holiday so I'd greatly appreciate pro-active comments and, as always, encourage additional commits to help  get this over the line. :)
Some notes:
- I've cut up the PR into commits that should stand on their own, and that can (hopefully) be reviewed in order as a kind of narrative.
- This change relies on a `.../courses/new` endpoint on backend to return the possible outcomes for a course. This wasn't called out on the ticket and is the bulk …
=> [1938] add new page for course outcomes

app/views/courses/_basic_details_tab.html.erb, spec/features/courses/details_spec.rb, spec/site_prism/page_objects/page/organisations/course_details.rb
Allocations
Display basic allocations information to providers
=> [1968] Add allocations help text to course details

app/views/courses/_basic_details_tab.html.erb, app/views/courses/sites/edit.html.erb, spec/features/courses/details_spec.rb, spec/features/courses/sites/edit_spec.rb
For some of our courses there is bad data – some don't have any locations. We can't easily set locations for these course.
We were assuming that for providers with 1 location, all courses would have that location. That's not the case.
Most of the affected courses weren't running in 2019.
Make it possible for providers to self-serve and fix their courses by going in and adding the missing location.
Move guidance about managing locations to the Pick your locations page and make it available to all providers.
Supersedes #540.
=> [2007] Remove single location special case

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/entry_requirements_controller.rb, app/views/courses/entry_requirements/_form.html.erb, app/views/courses/entry_requirements/new.html.erb, config/routes.rb, spec/factories/courses.rb, spec/features/courses/entry_requirements/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_entry_requirements_page.rb
A new courses entry requirements
Added routes
Added a shared form
built upon #534 as the changes in there is fundamental 
There are going to be a few loose ends that most likely addressed in another PR
- This added `gcse_subjects_required_using_level` to make life easier, as the PR also requires a course `level`
- :man_shrugging: hidden fields, user journey isn't quite defined.
- If the course level is further_education user needs to go further
=> [1955] Added the new courses entry requirements

app/controllers/courses/entry_requirements_controller.rb, app/views/courses/entry_requirements/new.html.erb, config/routes.rb, spec/features/courses/entry_requirements/new_spec.rb
Hook up "Continue" on new course entry requirements 
Redirect to course outcomes after new course entry requirements
Pick a provider and manually  `https://localhost:3000/organisations/PROVIDER_CODE/2020/courses/entry_requirements/new` then click continue
=> [1956] Add continue to new course entry requirements

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/outcome_controller.rb, app/views/courses/outcome/new.html.erb, config/routes.rb, spec/features/courses/outcome/new_spec.rb
Hook up "Continue" on new course outcome
Redirect to course entry requirements
Go go `/organisations/2CG/2019/courses/outcome/new` and attempt to continue without choosing anything and then after choosing something.
=> [1939] Add continue to new course outcome

app/controllers/courses/level_controller.rb, app/views/courses/level/_form_fields.html.erb, app/views/courses/level/new.html.erb, app/views/courses/send/_form_fields.html.erb, app/views/courses/send/edit.html.erb, config/routes.rb, spec/features/courses/level/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_level_page.rb
Allow providers to select the level of a new course.
Adds a ontroller action for `continue`, view, page object, and feature spec.
=> [1897] Add course level new page

app/helpers/breadcrumb_helper.rb, app/views/providers/details.html.erb, app/views/providers/show.html.erb, app/views/recruitment_cycles/_about_organisation.html.erb, app/views/recruitment_cycles/show.html.erb, spec/factories/providers.rb, spec/features/providers/details_spec.rb, spec/features/recruitment_cyles/show_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_details.rb
Move "About your Organisation" link into the "Current Cycle" or "Next Cycle" page for organisations so that providers can edit the content or information about their organisation in advance of the next cycle without affecting the content or information presented on the current cycle.
- Move "About your organisation" link to recruitment cycle pages
- Add new breadcrumb helper for organisation details page
- Replace `back` link with breadcrumbs
- Fixes "may be confusing" error for details spec
=> [1854] Move about your org link to recruitment cycle page

app/controllers/courses/apprenticeship_controller.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/apprenticeship/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/courses.rb, spec/features/courses/apprenticeship/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_apprenticeship.rb
To enable users to edit whether or not their course is an apprenticeship
- Adds in the ability to edit the program type on the frontend, specifically for apprenticeships
- Supports both SCITT and non-scitt providers
- Check out this branch and https://github.com/DFE-Digital/manage-courses-backend/pull/743/ on the backend
- Go to a provider that can offer an apprenticeship
=> [1999] Add edit apprenticeship page

app/controllers/courses/start_date_controller.rb, app/views/courses/start_date/_form_fields.html.erb, app/views/courses/start_date/edit.html.erb, app/views/courses/start_date/new.html.erb, config/routes.rb, spec/features/courses/start_date/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_start_date_page.rb
Creating a new course
Add new course page for "start date"
Example: `/organisations/2CG/2019/courses/start-date/new`
=> [2037] Add course new start date page

app/controllers/courses/fee_or_salary_controller.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/fee_or_salary/edit.html.erb, config/locales/en.yml, config/routes.rb, spec/features/courses/fee_or_salary/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_fee_or_salary.rb
We need the ability to edit whether the course is fee-paying, salaried, or an apprenticeship
- Adds a new page for editing fee or salary
- Populates fields based on the backend
- **temporarily disabled**
- Check out this branch and https://github.com/DFE-Digital/manage-courses-backend/pull/743/ on the backend
- Uncomment out the line in the basic details tab
- Go to a course on a non-accredited body
- Edit fee or salary
=> [2002] Edit course salaried/fee/apprenticeship

app/controllers/courses/applications_open_controller.rb, app/models/course.rb, app/views/courses/applications_open/_form_fields.html.erb, app/views/courses/applications_open/edit.html.erb, app/views/courses/applications_open/new.html.erb, config/routes.rb, spec/features/courses/applications_open/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_applications_open_page.rb
Creating a new course
Add new course page for "applications open"
Example: `/organisations/2CG/2019/courses/applications-open/new`
=> [2033] add new page for course applications open

app/controllers/courses/accredited_body_controller.rb, app/views/courses/accredited_body/edit.html.erb, config/routes.rb, spec/features/courses/accredited_body/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_accredited_body.rb
Basic details editing
https://www2.qa.publish-teacher-training-courses.service.gov.uk/organisations/2FD/2020/courses/35JL/details
* Just existing accredited bodies for now; "other" to be added soon.
* This is a hidden feature, no link to it yet.
* Changing to  other providers can be done by support using  the existing contact link on the details page
The new screen:
:ship:
Find the hidden page at `/organisations/2FD/2020/courses/35JL/accredited-body`
=> [2018] Add editing of a course's accredited body

app/views/courses/_basic_details_tab.html.erb, spec/features/courses/applications_open/edit_spec.rb, spec/features/courses/send/edit_spec.rb, spec/features/courses/start_date/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_details.rb
Frontend counterpart to https://github.com/DFE-Digital/manage-courses-backend/pull/756  
This PR takes https://github.com/DFE-Digital/manage-courses-frontend/pull/570 and moves the logic into the backend to avoid having multiple sources of truth
Either show or hide edit buttons depending on whether `is_send`, `applications_open_from` and `application_start_date` are enabled.
=> [2065] Decide whether or not to show edit buttons based on edit options

Gemfile, Gemfile.lock
WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
Replaced chromedriver-helper with webdrivers
no more 
WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
`bundle install`
`bundle exec rake`
=> [xxxx] Replaced chromedriver-helper with webdrivers

config/routes.rb
This is in preparation of decomissioning the C# version of Publish. This is meant to be combined with a `CNAME`, pointing from `www.publish` to `mcfe`.
Adds a redirect to the routes file.
I've tested this locally by briefly changing the `host =>` check to `127.0.0.1` and doing a few `curl`s. Seems to work great, but the redirect is a 301 and not a 302. I haven't found the right place to put the `status: 302` argument that should fix this because the syntax is a bit kludgy / hard to wrap my head around with the proc and everything.
```diff
$ git diff
-  constraints(host: /www\./) do
+  constraints(host: /127\./) do
```
```bash
$ curl -ik "https://127.0.0.1:3000/foo?bar=baz"
HTTP/1.1 301 Moved Permanently
Location: https://localhost:3000/foo?bar=baz
Content-Type: text/html
Cache-Control: …
```
=> [2036] Redirect www. to www2.

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/age_range_controller.rb, app/controllers/courses/applications_open_controller.rb, app/controllers/courses/apprenticeship_controller.rb, app/controllers/courses/entry_requirements_controller.rb, app/controllers/courses/level_controller.rb, app/controllers/courses/outcome_controller.rb, app/controllers/courses/start_date_controller.rb, app/controllers/courses/study_mode_controller.rb, app/models/course.rb, app/views/courses/entry_requirements/new.html.erb, app/views/courses/level/_form_fields.html.erb, app/views/courses/outcome/new.html.erb, app/views/shared/_course_creation_hidden_fields.html.erb, spec/features/courses/age_range_in_years/new_spec.rb, spec/features/courses/applications_open/new_spec.rb, spec/features/courses/apprenticeship/new_spec.rb, spec/features/courses/entry_requirements/new_spec.rb, spec/features/courses/level/new_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/outcome/new_spec.rb, spec/features/courses/start_date/new_spec.rb, spec/features/courses/study_mode/new_spec.rb, spec/models/course_spec.rb, spec/requests/courses/outcome/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_entry_requirements_page.rb, spec/site_prism/page_objects/page/organisations/courses/new_level_page.rb, spec/site_prism/page_objects/page/organisations/courses/new_outcome_page.rb, spec/support/helpers.rb
In order to support the course creation flow, we need to pass parameters through between pages, and integrate with the `build_new` endpoint on the API
- Pass parameters through from `outcome` -> `entry requirements`
- Use hidden fields to continually carry them through
- Call `build_new` on `new` and `continue` actions to validate against the backend
Running locally:
- Check out this branch
- Check out https://github.com/DFE-Digital/manage-courses-backend/pull/777 on the backend
- (As of writing this will error on the `entry_requirements` page as the course will be invalid
- Go to `organisations/<provide_code>/2020/courses/new` and fill in an outcome
- See the param get passed as a get param to the next page
=> [2031] Pass course creation parameters through

config/routes.rb, config/settings/production.yml, config/settings/qa.yml, config/settings/staging.yml
Once DfE Signin have whitelisted the domain on the `bats2` identifier, and the CNAME is in place with Rails serving both `www2` and `www`, we can release this change to flip all users back to `www`.
Flips the redirect around and updates the signin `base_url`s.
This will be tested in both QA and Staging before going live.
=> [2036] Redirect www2 requests to www

config/routes.rb
We forgot to add the education domain, which UCAS still point to.
Adds another case for the host regex for the redirect.
:ship: :fire:
=> [2036] Redirect education domain users to service domain

app/views/courses/status_panel/_unpublished.html.erb, spec/features/courses/show_spec.rb
Allow publishing of courses in the next recruitment cycle
Render form to publish courses in the next recruitment cycle
🚢
=> [2069] Allow publishing of courses in next cycle

azure/template.json
On random occasions, Azure Pipeline Release fails on swapping of deployment slots.
Microsoft engineer has provided an environmental variable that may prevent these failures when added to the app settings.  I have tested it in QA and didn't see any issue.
Create and set following app setting with value=0
`WEBSITE_SLOT_POLL_WORKER_FOR_CHANGE_NOTIFICATION`
=> Added env variable to stop slot swap failures

app/controllers/application_controller.rb, app/controllers/courses/fee_or_salary_controller.rb, azure-pipelines.yml, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/show_spec.rb
We are getting an error with some users where they can't access their organisations because the system does not recognise them as belonging to any organisation. We think this is actually a flaw in how we handle authentication, but we can't reproduce this reliably yet so aren't quite sure.
Synchronise how we authenticate a user with how we decide whether to present them with a "Sign Out" or a "Sign In" link on the view page. The thinking being that the problem reports we've seen so far have shown a "Sign In" link for the user.
There are fixes for other test failures that seem to have gone undetected in our CI in this PR.
=> [2117] check current user present in authenticate

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/age_range_controller.rb, app/controllers/courses/fee_or_salary_controller.rb, app/models/course.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/show_spec.rb, spec/models/course_spec.rb, spec/support/helpers.rb
The API is being updated for this to not match the JSONAPI schema exactly, so we need to update the frontend.
Implement `Course.build_new` and update all the relevant tests and places it's used.
Ignore the first commit, it's unrelated and only meant to fix the nil warnings we were getting before.
🖌
=> [2119] Update course build_new to match new API shape

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/pages/accept_terms.html.erb, config/routes.rb, spec/controllers/sessions_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/features/sign_in_spec.rb, spec/site_prism/page_objects/page/accept_terms.rb
Users who log in and have not accepted terms and conditions get a "We don't know which org you're part of" page.
Implement the terms page.
🚢
=> [2117] Add accept terms page

app/controllers/courses/accredited_body_controller.rb, app/models/provider_suggestion.rb, app/views/courses/accredited_body/_provider_search_field.html.erb, app/views/courses/accredited_body/_provider_suggestion.html.erb, app/views/courses/accredited_body/edit.html.erb, app/views/courses/accredited_body/search.html.erb, app/views/pages/guidance.html.erb, app/views/shared/_error_messages.html.erb, config/initializers/backtrace_silencers.rb, config/routes.rb, spec/controllers/providers_controller_spec.rb, spec/factories/provider_suggestion.rb, spec/features/courses/accredited_body/edit_spec.rb, spec/features/providers_spec.rb, spec/models/course_spec.rb, spec/models/provider_suggestion_spec.rb, spec/requests/courses_spec.rb, spec/site_prism/page_objects/page/organisations/course_accredited_body_search.rb, spec/support/define_factory_jsonapi_render_methods.rb, spec/support/resource_list_to_jstonapi.rb, spec/support/serializers/provider_suggestion_serializer.rb
As part of adding provider suggestions and searching we'd like to search for providers from the frontend.  
Add a nojs provider search.  
#### Selecting the last option
=> [2053] Add nojs provider search

app/views/providers/details.html.erb, spec/features/providers/details_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_details.rb
Allow providers to publish their information (enrichment) info in advance of the next cycle so that providers can confirm they are satisfied their provider information is publishable and spread their workload before the start of the next cycle
- Add the publish button to the page following the designs outlined
- Checkout the branch
- Ensure you have "Search and Compare API" running
- Navigate to the "About your org" page for the next recruitment cycle
- Click "Publish in October"
=> [2152] Allow providers to publish details for next recruitment cycle

app/controllers/application_controller.rb, app/views/errors/unauthorized.html.erb, spec/controllers/sessions_controller_spec.rb, spec/features/unauthorized_api_requests_spec.rb, spec/site_prism/page_objects/page/unauthorized.rb
We need to render errors rather than redirect when the API returns unauthorized
=> [2157] Don't redirect on 401 from backend

app/controllers/application_controller.rb, spec/controllers/sessions_controller_spec.rb, spec/features/forbidden_api_requests_spec.rb, spec/features/sign_in_spec.rb
403 responses from the backend shouldn't always redirect users to the `/accept-terms` page, due to overloading from the API that happens.
This adds in a check for some meta information provided by the backend (https://github.com/DFE-Digital/manage-courses-backend/pull/817) and redirects/renders accordingly.
=> [2137] Don't redirect 403 errors from backend when terms have been accepted

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/age_range_controller.rb, app/controllers/courses/apprenticeship_controller.rb, app/decorators/course_decorator.rb, app/models/course.rb, app/views/courses/apprenticeship/_form_fields.html.erb, app/views/courses/fee_or_salary/_form_fields.html.erb, app/views/courses/fee_or_salary/edit.html.erb, app/views/courses/preview/financial_support/_financial_support.html.erb, config/environment.rb, spec/factories/courses.rb, spec/features/courses/apprenticeship/edit_spec.rb, spec/features/courses/apprenticeship/new_spec.rb, spec/features/courses/fee_or_salary/edit_spec.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/salary_spec.rb, spec/features/courses/show_spec.rb, spec/site_prism/page_objects/page/organisations/course_apprenticeship.rb, spec/site_prism/page_objects/page/organisations/course_fee_or_salary.rb, spec/site_prism/page_objects/page/organisations/courses/new_apprenticeship_page.rb, spec/site_prism/page_objects/page/organisations/courses/new_fee_or_salary_page.rb, spec/support/helpers.rb, spec/support/serializers/course_serializer.rb
This is the frontend counterpart to https://github.com/DFE-Digital/manage-courses-backend/pull/787, we want to switch away from feeding `program_type` and then using a translations file to determine how to present it to the user.
Change instances of `funding` to `funding_type`, also use new `funding_type` values. Also enable strict parameters.
=> [2159] Use funding_type instead of program_type

app/controllers/ucas_contacts_controller.rb, app/views/ucas_contacts/index.html.erb, config/routes.rb, spec/factories/providers.rb, spec/features/providers/ucas_contacts_spec.rb, spec/site_prism/page_objects/page/organisations/ucas_contacts.rb
UCAS contacts
Add `/ucas-contacts` and page
Manually navigate to `/organisations/XXX/ucas-contacts`
=> [2075] Setup UCAS contacts page

app/controllers/application_controller.rb, spec/features/forbidden_api_requests_spec.rb
`NoMethodError: undefined method `key?' for "":String` Was being thrown when getting `403` responses from the API due to incorrect assertions about the shape of the response in this situation.
- Check that the response is a hash before checking for metadata
=> [2224] Fix NoMethod Key for 403 handling

config/routes.rb
We don't want users to see incorrect 2019 pages before we've modified them to be read only, and before they represent their current state.
We will only add them back if needed.
=> Make 2019 routes 404

app/views/courses/preview/financial_support/_financial_support.html.erb, spec/features/courses/preview_spec.rb
Bursaries and scholarships haven't been announced yet.
Alternative to #662
Only modifies the financial support, doesn't affect fees or salaries or financial support text for salaried courses.
=> Hide financial support information in preview

app/views/providers/_provider.html.erb
Remove counts to avoid confusing users with incorrect numbers.
We should fix this properly in the backend:
https://trello.com/c/9EcGLugq/2267-course-counts-on-organisation-list-show-the-wrong-number-of-courses
=> [2267] Temporarily remove course counts from organisations page

app/views/courses/confirmation.html.erb, spec/features/courses/confirmation_spec.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/start_date/new_spec.rb, spec/site_prism/page_objects/page/organisations/course_confirmation.rb
We need to display the data for the course in the confirmation page so the user can see what they have selected at a glance
Adds the fields to the course confirmation page for the data we gather at the moment
=> [2020] Add fields to confirmation page

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
The backend needs to save users first and last name, and so it needs to be sent them from DfE SignIn
Send the first and last name in the payload to DfE SignIn
=> [2276] Send first and last name from dfe SignIn

app/controllers/providers_controller.rb, app/views/providers/about.html.erb, app/views/providers/contact.html.erb, app/views/providers/details.html.erb, spec/features/providers/about_spec.rb, spec/features/providers/details_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_details.rb
The backend publishes all information, regardless of enrichment state.
Reflect this in the design by removing content status label and publish button.
Update success text and save button to indicate publishing, and note how long it will take to propagate.
This is an MVP solution and doesn't tidy up all the now unused code.
=> [2281] Remove concept of drafts for About your org

app/views/courses/preview/financial_support/_financial_support.html.erb
- Hide for all courses until we have new financial incentives in manage-courses-frontend
- Hide for multi subject courses until we've correctly incorporated the logic (eg Physics with Maths)
We will need to re-enable this, probably in two stages.
Card for unhiding for new financial incentives:
https://trello.com/c/pIsLAc6m/2261-unhide-financial-incentives-after-announcement
Card for fixing multi-subjects:
https://trello.com/c/0BWV4OKF/2107-salaried-course-bursary-bug-zendesk-query
=> [2107] Temporarily disable financial support previewing

app/controllers/courses_controller.rb, app/views/courses/confirmation.html.erb, config/routes.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/new_spec.rb, spec/site_prism/page_objects/page/organisations/course_confirmation.rb
In order to actually create a course - the save button needs to post to the API
- Save the course
- Redirect if errors
- Show the saved course when created
=> [1963] Hook up course create button

app/decorators/course_decorator.rb, app/views/courses/_course_table_row.html.erb, app/views/courses/_description_content.html.erb, app/views/courses/_status_panel.html.erb, app/views/courses/show.html.erb, app/views/courses/status_panel/_withdrawn.html.erb, app/webpacker/stylesheets/_phase-tag.scss, spec/features/courses/show_spec.rb
- Improve text contrast on status tag
- Show that applications are closed and No vacancies in courses table
- Give better guidance text on course page
- Put status panel back
- Allow users to preview
- Give instructions on how to republish
(Note: There's no test changes for the courses table because we don't have a courses spec since the test went missing in https://github.com/DFE-Digital/manage-courses-frontend/pull/444, should be fixed separately)
| Page | Before | After |
|-|-|-|
| Course | ![Screen Shot 2019-10-09 at 14 28 13](https://user-images.githubusercontent.com/319055/66485693-243b2180-eaa1-11e9-8cc1-92d065c74d0e.png) | ![Screen Shot 2019-10-09 at 14 27 21](https://user-images.githubusercontent.com/319055/66485694-24d3b800-eaa1-11e9-9d4f-a59ca211a043.png) |
| Courses table | …
=> Improve design for withdrawn courses

app/views/courses/_status_panel.html.erb
Stop delete link and publish button from being too close to each other.
|-|-|
|![Screen Shot 2019-10-09 at 16 55 38](https://user-images.githubusercontent.com/319055/66498311-c402aa80-eab5-11e9-9b76-0186350d851c.png) | ![Screen Shot 2019-10-09 at 16 55 45](https://user-images.githubusercontent.com/319055/66498364-d250c680-eab5-11e9-9080-25ff703083f5.png)|
🤦‍♂
=> Add missing section break

app/controllers/providers_controller.rb, app/views/providers/no_providers.erb, spec/controllers/providers_controller_spec.rb, spec/requests/providers_spec.rb
Currently redirects to `/40x`
This means that a page refresh will work when the user is granted
access, and reduces risk of users incorrectly getting stuck here.
The new erb is a copy of `app/views/errors/unauthorized.html.erb`
This commit disentangles this use case from the generic 401/403
handling.
:ship:
=> [2308] Don't use a redirect for no-orgs page

app/controllers/application_controller.rb, app/views/errors/forbidden.html.erb, spec/features/forbidden_api_requests_spec.rb, spec/site_prism/page_objects/page/forbidden.rb
Previously showed the "We don't know which org...." page which was not
accurate becaause they might have access to other providers.
* Use the "forbidden" page when accessing unauthorized provider url
You can see that page currently at https://www.qa.publish-teacher-training-courses.service.gov.uk/403
We might want to improve the text on this page:
https://github.com/DFE-Digital/manage-courses-frontend/blob/462c82e8b61db354262675191ee0776af83f278e/app/views/errors/forbidden.html.erb#L5
This is the generic 403-forbidden page.
We could
* improve this page's copy
* have a page just for this specific circumstance with specific copy on it
=> [2308] Use the "forbidden" page when accessing unauthorized provider url

config/routes.rb, spec/features/sign_in_spec.rb, spec/requests/providers_spec.rb
Because they both render the same content
[2308] Redirect /organisations/ to /
:ship:
=> [2308] Redirect /organisations/ to /

app/controllers/health_checks_controller.rb, config/routes.rb, spec/requests/health_checks_spec.rb
We need to be able to check that the app is up on deployment.
A `/ping` endpoint to perform a simple check that the application is running.
:shipit:
=> [2332] add /ping health chech endpoint

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/applications_open_controller.rb, app/controllers/courses/sites_controller.rb, app/controllers/courses_controller.rb, app/decorators/course_decorator.rb, app/models/site.rb, app/views/courses/confirmation.html.erb, app/views/courses/sites/new.html.erb, app/views/shared/_course_creation_hidden_fields.html.erb, config/routes.rb, spec/factories/sites.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/sites/edit_spec.rb, spec/features/courses/sites/new_spec.rb, spec/features/courses/study_mode/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_locations_page.rb, spec/support/helpers.rb
The course creation flow was currently skipping the `locations` step, we need to add it to assign training locations to new courses
- Add in the page to the course creation flow
- Display locations on the confirmation page
=> [2038] New sites page

app/helpers/breadcrumb_helper.rb, app/views/ucas_contacts/show.html.erb
I understand from @fofr that the intention is only leaf-nodes on the
navigation to hae "back" and now that we've added another layer this
page should have the full breadcrumb.
* Convert ucas contacts to full breadcrumb
:ship:
=> [2175] Convert ucas contacts to full breadcrumb

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/applications_open_controller.rb, app/controllers/courses/subjects_controller.rb, app/controllers/courses_controller.rb, app/services/next_course_creation_step_service.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/confirmation.html.erb, app/views/courses/subjects/new.erb, config/routes.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/level/new_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/services/next_course_creation_step_service_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_subjects_page.rb, spec/support/shared_examples/course_creation.rb
We would like to be able to set single subjects during course creation.  
Add the new subject page and relevant plumbing.
=> [2365] Add subjects to course creation workflow

app/controllers/application_controller.rb, app/views/providers/no_providers.erb, spec/features/providers_spec.rb, spec/features/unauthorized_api_requests_spec.rb, spec/site_prism/page_objects/page/organisations/no_providers.rb
The backend returns 401 if there is no user account. The last cleanup of
the status handling code left this user journey showing the "something
went wrong" unauthorized page.
* Show no-organisations page if user has no user record
* All the test coverage
This change means that the same page is shown regardless of whether you
have no account in our database (401) or have an account but no access
to any providers (403), but the response codes to the browser are
reflective of which code the backend responded with (401/403).
:ship:?
=> [2405] Show no-organisations page if user has no user record

app/controllers/courses_controller.rb, spec/features/courses/fees_spec.rb
Be more flexible in what we accept from users.
A user has been struggling to input a number in the course fees box because our validations do not allow commas to be added. eg 9,000 is not accepted.
We need to loosen our validations to allow for this type of value to be entered.
https://www.qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2020/courses/3CX8/fees
=> [2414] Strip commas from course fees

spec/features/courses/fees_spec.rb
Because we massage the params on the way through to backend.
Suggested by @fofr after completion of the fee work.
Add test coverage for course length logic
:ship:
=> Add test coverage for course length logic

config/puma.rb
To avoid firefox refusing access after a git clean.
Some more context
* https://security.stackexchange.com/questions/141618/openssl-serial-number-error-sec-error-reused-issuer-and-serial
=> Randomize the development certificate serial number

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/fee_or_salary_controller.rb, app/controllers/courses_controller.rb, app/services/next_course_creation_step_service.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/outcome/new_spec.rb, spec/features/courses/sites/new_spec.rb, spec/services/next_course_creation_step_service_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_fee_or_salary_page.rb
Non-accredited bodies need to go through slightly different course creation flows due to what they're allowed to provide.  
- Add in pages for non-accredited bodies to the course flow
- Update the relevant pages tests
- Fix up a couple of things noticed when testing E2E locally
- Sites id's on creation
- Remove temporary name
=> [2325] Course creation flow for non-accredited body (SD)

app/controllers/courses/age_range_controller.rb, spec/features/courses/age_range_in_years/edit_spec.rb
This PR fixes two Code Climates issue in the AgeRange controller:
- "method update exceeds 25 lines of code"
- "Cognitive Complexity of 9 (exceeds 5 allowed)"
A missing feature spec has also been added to cover the scenario where a user wished to update the course age_range with custom values. (_This increases code coverage in the controller by 7% from 80% to 87%_)
- Extracts logic into private methods
- Add missing feature spec
=> [2433] - fix(AgeRange Controller): Code Climate issue

app/services/vacancy_status_determination_service.rb, spec/services/vacancy_status_determination_service_spec.rb
This PR fixes a Code Climates issue in the VacancyStatusDeterminationService:
- "Cognitive Complexity of 10 (exceeds 5 allowed)"
- Replaces nested if statement with simplified logic (?? - hopefully it's easier to read now?)
- Replaces spec double with factories
=> [2434] - fix(VacancyStatusDeterminationService): Code Climate issue

app/controllers/courses/modern_languages_controller.rb, app/controllers/courses/subjects_controller.rb, app/decorators/course_decorator.rb, app/views/courses/modern_languages/_form_fields.html.erb, app/views/courses/modern_languages/edit.erb, app/views/courses/subjects/_form_fields.html.erb, config/routes.rb, spec/decorators/course_decorator_spec.rb, spec/factories/subjects.rb, spec/features/courses/modern_languages/edit_spec.rb, spec/features/courses/subjects/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_modern_languages.rb, spec/support/helpers.rb
As it stands modern languages cannot be set for the modern language subjects.  
Add a page for modifying modern language subjects so that modern subjects can be set.
This also contains a fix for subjects not being autoselected as pointed out by @fofr
=> [2326] Add modern language subjects page

app/controllers/courses/age_range_controller.rb, app/helpers/age_range_errors_view_helper.rb, app/views/courses/age_range/_errors.html.erb, app/views/courses/age_range/_form_fields.html.erb, app/views/courses/age_range/edit.html.erb, config/locales/en.yml, spec/features/courses/age_range_in_years/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_age_range.rb
When a user selects a 'another age range' and does not fill in the 'From' and 'To' fields the correct errors are now appearing on the page. If an error is shown then the 'another age range' radio automatically expands in order to show errors. 
- fixes to front end error handling
- error copy updated
- increased test coverage
Validations included:
- missing 'from' and 'to' fields
- missing 'to' field
- missing 'from' field
- 'to' field greater than 'from' field
- course age range less than 4 years
=> [2435] - fix(course age range form): validation errors

README.md, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, spec/controllers/application_controller_spec.rb, spec/requests/authorisation_spec.rb, spec/requests/sessions_spec.rb, spec/support/helpers.rb
To reduce the friction to developing the app. So we can develop without requiring online access. etc.
Add support for basic auth in `development` env, and if special config is provided.
Tests still have to be fixed, but I've run this locally and it seems to work. That includes existing functionality of sign-in and sign-out with DFE Sign-In.
But ... is this even a good idea?
=> [2409] login without dfe sign in

config/initializers/omniauth.rb
When running the front end application for the first time, the user is required to create a `config/setting/development.local.yml` and add a value for DFE Sign in secret.
A couple of scenarios can occur which can result in errors that are not immediately obvious:
- An incorrect secret is entered
- A typo is made in the yaml file (if the key is incorrect, the default value is used)
https://trello.com/c/D9Ym3r5I/2407-manage-courses-frontend-technical-onboarding
- Rescue and log `Rack::OAuth2::Client::Error` (indicating that the `dfe_signin` secret _could_ be incorrect)
=> [2407] - Improve handling for missing / incorrect DFE Signin credentials (Development)

Rakefile, azure-pipelines.yml, lib/tasks/parallel_tests.rake
Part of a bigger section of work to run specs in parallel.
A simple change to the azure configuration so that specs are run in parallel on CI via the `parallel_tests` gem. Azure has _two_ available cores that can be utilised.
_Before_
min ~50 seconds
_After_
40 seconds
=> [2492] - Run specs in parallel on CI

azure-pipelines.yml
Reverting recent change to Azure pipeline config to run specs in parallel in order to unblock CI. Caused by suspected puma upgrade issue -
https://trello.com/c/rVx1gcbf/2530-investigate-puma-upgrade-issue
=> [2530] - revert running specs in parallel on CI

Gemfile, Gemfile.lock, Rakefile, azure-pipelines.yml, config/brakeman.ignore, lib/tasks/brakeman.rake
Static analysis is way to identifies security flaws in an application. _Brakeman_ is a gem that provides this functionality.
- Add Brakeman gem
- Create rake task to run static analysis locally
- Add Brakeman rake task to default rake task
- Add static analysis as a build step on CI. Build will fail if static analysis does not pass.
- Ignored 'dynamic render' issue as it's not possible to view sites of other provider if you do have permission. _See recording below_
```
bundle exec brakeman
```
=> [2522] - feat(security): add Brakeman Static Analysis

app/helpers/view_helper.rb
HTML was showing up in the change link
- Ensure HTML doesn't show up in the change link
- Go to the [course confirmation page](https://localhost:3000/organisations/2AT/2020/courses/confirmation?course%5Bage_range_in_years%5D=11_to_18&course%5Bapplications_open_from%5D=2010-10-08&course%5Benglish%5D=must_have_qualification_at_application_time&course%5Bfunding_type%5D=apprenticeship&course%5Bis_send%5D=1&course%5Blevel%5D=secondary&course%5Bmaths%5D=must_have_qualification_at_application_time&course%5Bqualification%5D=qts&course%5Bstart_date%5D=October+2019&course%5Bstudy_mode%5D=full_time)
- Look at the change confirmation link
=> [2485] Don't escape html on course confirmation page

azure-pipelines.yml, config/webpacker.yml, spec/support/webpacker.rb
When running specs in parallel we want to avoid workers compiling the same files at the same time. Believe this was the reason for this bug 👉 https://trello.com/c/rVx1gcbf/2530-investigate-puma-upgrade-issue
- Add a spec helper that compiles assets only once when running specs in parallel. It does this by creating a hexdigest of all webpacker assets and compiling only when this value changes.
- Run specs in parallel on CI (again!)
=> [2530] - compile Webpack once only when running specs in parallel

Gemfile, Gemfile.lock, spec/spec_helper.rb
The `simplecov-console` gem was added recently in order to print results to the console rather than publish results to the 'coverage' folder. However following discussion with team have concluded this is too noisy so am reverting back to the previous method.
- remove `simplecov-console` gem and associated config.
- threshold added for passing Simplecov (95%). Currently coverage is just over 95%.
- reduced noise in console when running specs in parallel
=> [2534] - Don't use Simplecov-console gem

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/base.rb, spec/controllers/application_controller_spec.rb
When a request comes in, add the value of the X-Request-ID to the logs, and ensure this value gets sent to the MCBE. This so we can track a requests journey through the system.
- Add RequestStore gem to store the request id safely (in a manner that is thread-safe)
- Log the request id
- Add the request id to the headers when making backend API requests
NB: Pull request on the back end is required to make this work
You can see the request id is now being tracked across the front and back end.
=> [2510] - Add Request ID support to MCBE

app/controllers/pages_controller.rb, spec/features/view_pages_spec.rb
The terms and condition show be viewable without user having to login.
Fixed terms page to be publicly available
https://localhost:3000/terms-conditions
:ship:
=> [2536] Fixed terms page to be publicly available

app/views/access_requests/new.html.erb
As it stands the meanings of the email fields in user permission granting is unclear and unintuitive, potentially leading to erroneous granting of permissions.
Mitigate this issue by clarifying what these fields do.
=> [2484] Clarify access request creation language

Gemfile
Move RequestStore gem out of the test/development group so that it is accessible in production
=> Move RequestStore gem

app/views/layouts/_header.html.erb, spec/features/access_requests_spec.rb, spec/features/view_pages_spec.rb, spec/site_prism/page_objects/base.rb
In order to allow support to use deal with access requests in a straightforward manner we need to link to the page in an accessible place.  
Adds a link to the access requests page that displays only if the user is an admin.
=> [2484] Add header link to access requests page

.tool-versions, app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/accredited_body_controller.rb, app/controllers/courses/entry_requirements_controller.rb, app/controllers/courses/study_mode_controller.rb, app/helpers/view_helper.rb, app/services/previous_course_creation_step_service.rb, app/views/courses/accredited_body/new.html.erb, app/views/courses/age_range/new.html.erb, app/views/courses/applications_open/new.html.erb, app/views/courses/apprenticeship/new.html.erb, app/views/courses/entry_requirements/new.html.erb, app/views/courses/fee_or_salary/new.html.erb, app/views/courses/level/new.html.erb, app/views/courses/outcome/new.html.erb, app/views/courses/sites/new.html.erb, app/views/courses/start_date/new.html.erb, app/views/courses/study_mode/new.html.erb, app/views/courses/subjects/new.erb, spec/features/courses/accredited_body/edit_spec.rb, spec/features/courses/accredited_body/new_spec.rb, spec/features/courses/entry_requirements/new_spec.rb, spec/features/courses/study_mode/new_spec.rb, spec/services/previous_course_creation_step_service_spec.rb, spec/site_prism/page_objects/page/organisations/course_base.rb
When going through the new course flow, the user should be able to see and use a `back` link to go to their previous steps, with the following circumstances:
- Going through the flow normally
- Going back to the confirmation page
- Going back past locations if there is only a single location
- Going back to different pages depending on the user being an accredited body
- Add in correct back links
- Add in view helper for doing back links with confirmation
=> [2370] Hook up back links for new course flow

app/decorators/course_decorator.rb, app/views/courses/preview/_financial_support.html.erb, spec/decorators/course_decorator_spec.rb, spec/views/preview.html.erb_spec.rb
If a course is excluded from the bursary the course preview page will not display bursary information in the Financial Support sections, rather, it will display loan information only.
Courses are excluded from bursaries if:
- They have two subjects
- The course name contains 'with' and starts with a subject that is on the exclusion list (PE, Physical Education, Media Studies, Drama)
E.g.
- Drama with English => excluded
- English with Drama => not excluded
- Drama and English - not excluded
- update 'financial options' and 'funding support' sections
I expect as least 5 rejections
=> [2573] - Determine which courses are excluded from bursaries

app/helpers/view_helper.rb, app/views/courses/subjects/_form_fields.html.erb, app/views/courses/subjects/new.erb, spec/features/courses/subjects/new_spec.rb
The subject select page needed to be brought in line with the prototype
- Display the correct title on the subjects page
- Default to blank select box
- Move the button below the select box
- Display the correct label
=> 2578 primary subject page style fixes

app/models/access_request.rb, app/views/layouts/_header.html.erb, spec/features/access_requests_spec.rb
The access request used to display the count of requested requests.
This was lost when it was ported to publish.
- Add the count back in
=> [2611] Add access request count to header

app/views/courses/accredited_body/new.html.erb
As it stands the entry requirements page does not work during course creation because it is not having the appropriate hidden fields passed to it.
Pass hidden fields from the accrediting body page during course creation.
Needs tests, not yet sure why the tests didn't pick it up before.
=> [2609] Make accrediting body page pass hidden fields

app/views/courses/applications_open/_form_fields.html.erb
Same as before. The new and edit applications open pages are slightly out of line with the prototype
- Change the value of the applications_open_from label from "Other" to "On a specific date"
=> [2588] Applications open style fix

app/views/courses/outcome/_form_fields.html.erb, app/views/shared/_edit_options_radio_buttons.html.erb
Update the outcome page to match the prototype
- Make the labels bold
- **Does not** change the ordering of the labels, that will need to happen in the edit options in manage courses backend
=> [2582] Make labels bold on outcome page

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/accredited_body_controller.rb, app/controllers/courses/age_range_controller.rb, app/controllers/courses/applications_open_controller.rb, app/controllers/courses/apprenticeship_controller.rb, app/controllers/courses/entry_requirements_controller.rb, app/controllers/courses/fee_or_salary_controller.rb, app/controllers/courses/level_controller.rb, app/controllers/courses/modern_languages_controller.rb, app/controllers/courses/outcome_controller.rb, app/controllers/courses/sites_controller.rb, app/controllers/courses/start_date_controller.rb, app/controllers/courses/subjects_controller.rb, spec/features/courses/age_range_in_years/new_spec.rb, spec/features/courses/applications_open/new_spec.rb, spec/features/courses/apprenticeship/new_spec.rb, spec/features/courses/entry_requirements/new_spec.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/level/new_spec.rb, spec/features/courses/outcome/new_spec.rb, spec/features/courses/start_date/new_spec.rb, spec/features/courses/study_mode/new_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/support/helpers.rb
Course creation did not handle validation as there was none implemented in the backend, this PR will now take into account any validation errors on the API (or in the frontend where there already exists some)
- Add method to filter out errors from the API to the appropriate page
- Add tests to pages with validation
- Keep current frontend validation
1. Check out this branch
2. Go through pages and attempt to get through them with nothing selected where possible
3. It _should_ display validation errors where the backend returns them
- There are some instances where the validation is not implemented on the backend
=> [2561] Handle validation errors on course creation

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/subjects_controller.rb, app/decorators/course_decorator.rb, app/views/courses/subjects/_form_fields.html.erb, app/views/courses/subjects/new.erb, spec/decorators/course_decorator_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_subjects_page.rb, spec/support/shared_examples/course_creation.rb
https://manage-courses-prototype.herokuapp.com/new/V978/subject (go back and select a level first)  
Secondary courses need to be able to have a subordinate subject in addition to the master subject.  
Add a second subject dropdown to the subjects/new page.
=> [2567] Add ability add a subordinate subject to course creation

app/decorators/course_decorator.rb, app/views/courses/confirmation.html.erb, app/views/courses/start_date/_form_fields.html.erb, app/views/courses/start_date/edit.html.erb, app/views/courses/start_date/new.html.erb, spec/decorators/course_decorator_spec.rb, spec/features/courses/start_date/edit_spec.rb, spec/features/courses/start_date/new_spec.rb
Style fixes for the start date page to bring it in line with the prototype
- Default drop-down to the current start date or the Sept of the next cycle.
=> 2589 start date style fixes

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/accredited_body_controller.rb, app/controllers/courses/modern_languages_controller.rb, app/controllers/courses/outcome_controller.rb, app/controllers/courses/send_controller.rb, app/helpers/organisation_helper.rb, app/models/course.rb, app/services/next_course_creation_step_service.rb, spec/features/courses/apprenticeship/new_spec.rb, spec/features/courses/modern_languages/edit_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/sites/new_spec.rb, spec/features/courses/start_date/new_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/models/course_spec.rb, spec/models/provider_spec.rb, spec/models/recruitment_cycle_spec.rb, spec/services/next_course_creation_step_service_spec.rb, spec/services/previous_course_creation_step_service_spec.rb, spec/site_prism/page_objects/page/organisations/course_base.rb, spec/site_prism/page_objects/page/organisations/courses/new_course_base.rb, spec/spec_helper.rb, spec/support/helpers.rb
We need to implement the further education workflow to make course creation useful for a wider range of users.
Refactor NextCourseCreationStepService to make workflows easier to read and adds the further education workflow.
Requires: https://github.com/DFE-Digital/manage-courses-backend/pull/1021
=> [2412] Add further education workflow to NextCourseCreationStepService

azure-pipelines.yml
Correction to Rspec formatting options on CI. At the moment it's just spitting out XML rather than just pretty printing results
Output now pretty printing. Note also CI fails if test fails
=> [2633] - Fix Rspec formatting on CI

public/maintenance.html
Offline maintenance page
> https://github.com/alphagov/govuk-design-system-backlog/issues/129
Add a hardcoded static maintenance page
`/maintenance`
=> [2620] Add static maintenance page for offline mode

app/models/site.rb, app/views/courses/preview/_apply.html.erb, app/views/layouts/application.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/locations-map.js, app/webpacker/scripts/map-popup.js, app/webpacker/stylesheets/_map.scss, app/webpacker/stylesheets/application.scss, azure/template.json, config/settings.yml, spec/factories/providers.rb, spec/factories/sites.rb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
Maps on course#preview
Add google map for locations on course#preview to match the course page on FIND (search and compare ui)
Any course#preview page i.e. `/organisations/XXX/2020/courses/XXXX/preview`
=> Setup google maps on course preview for locations

app/controllers/courses_controller.rb, app/views/courses/confirmation.html.erb, app/views/courses/show.html.erb, app/views/courses/subjects/_form_fields.html.erb, app/views/courses/subjects/new.erb, app/views/layouts/_flash.html.erb, spec/features/courses/age_range_in_years/new_spec.rb, spec/features/courses/applications_open/new_spec.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/level/new_spec.rb, spec/features/courses/outcome/new_spec.rb, spec/features/courses/start_date/new_spec.rb, spec/features/courses/study_mode/new_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/site_prism/page_objects/page/organisations/course_confirmation.rb, spec/support/helpers.rb
- Updates to the confirmation page to bring it in line with the prototype
- Add a change link for subjects (and support the confirmation redirect)
- Update applications open to display a user friendly message
- Display fee or salary / apprenticeship dependent on the provider type
- Update the title for the confirmation page
- Display accredited body information where appropriate
- Display a success message when a course is created
=> [2590] Confirmation page updates

app/views/courses/confirmation.html.erb, app/webpacker/stylesheets/application.scss, spec/features/courses/age_range_in_years/new_spec.rb, spec/features/courses/confirmation_spec.rb, spec/site_prism/page_objects/page/organisations/course_confirmation.rb
When a provider has a single location - they are not able to edit their locations for the course. Currently, a change link is shown that doesn't work.
- Don't show the change link on a provider with a single location
- Show help text when there is one location
- Create link to manage locations which opens in a new tab
=> [2569] Show help text when provider has a single location

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/modern_languages_controller.rb, app/helpers/view_helper.rb, app/services/course_creation_step_service.rb, app/views/courses/modern_languages/new.html.erb, app/views/courses/subjects/new.erb, config/routes.rb, spec/features/access_requests_spec.rb, spec/features/courses/details_spec.rb, spec/features/courses/modern_languages/edit_spec.rb, spec/features/courses/modern_languages/new_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/sites/new_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/helpers/view_helper_spec.rb, spec/services/course_creation_step_service_spec.rb, spec/site_prism/page_objects/page/organisations/course_base.rb, spec/site_prism/page_objects/page/organisations/courses/back_new_locations_page.rb, spec/site_prism/page_objects/page/organisations/courses/back_new_modern_languages_page.rb, spec/site_prism/page_objects/page/organisations/courses/new_course_base.rb, spec/site_prism/page_objects/page/organisations/courses/new_modern_languages_page.rb
As it stands standard subjects can be added during course creation but this neglects modern language subjects which require an additional page and set of functionality.
Add the modern language subjects page to course creation and insert it into the workflow. Also adds the back endpoint to decide whether or not to skip the step when going backwards.
=> [2566] Add modern languages to course creation

app/controllers/courses/outcome_controller.rb, spec/factories/courses.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/outcome/edit_spec.rb, spec/features/courses/outcome/new_spec.rb
In order to bring the prototype in line with the application, we need to order the choices for outcomes. 
Originally this was done in the backend, but as it is display logic, it was better suited to the frontend with some checks to have assurance there are no extra options needed to be displayed
- Order options for outcomes
- Add checks for provided edit options
=> [2614] Outcome page reorder choices

app/controllers/pages_controller.rb, spec/features/view_pages_spec.rb
No need to authenticate these static pages
Remove authentication from static content and legal pages
`/cookies`
`/privacy-policy`
`/new-features`
=> [2683] Make cookies, privacy and new features none authenticated

app/models/provider.rb, spec/models/provider_spec.rb
Provider enrichments are no longer in use, these fields are leftover from them.
Remove any references to providers' `content_status` or `last_published_date` and correct any tests broken by this.
Needs to be checked by @fofr but things seem to still work.
=> [2403] Remove content_status and last_published_date from provider

end-to-end-tests/cypress/integration/_publicly_visible/index.js
Tests that checks for pages being publicly visible occurs after tests that have logged the user in, leading to false positives.
Amended the folder name to start with an underscore therefore when running all tests it starts off with the user not logged in
=> [2695] Fixed tests that was polluted by ordering

app/controllers/courses/applications_open_controller.rb, app/controllers/courses/apprenticeship_controller.rb, app/controllers/courses/fee_or_salary_controller.rb, app/controllers/courses/sites_controller.rb, app/views/courses/sites/new.html.erb, spec/features/courses/apprenticeship/new_spec.rb, spec/features/courses/fee_or_salary/new_spec.rb, spec/features/courses/sites/new_spec.rb
Validation has been added in the backend (see: https://github.com/DFE-Digital/manage-courses-backend/pull/1052 & https://github.com/DFE-Digital/manage-courses-backend/pull/1062) which requires the frontend to be linked to the keys for the error
- Add error keys to the relevant pages to display validation errors from the backend
**Note**
This PR does not cover age range with years with custom validation, as that is currently handled in the frontend of the controller and will be solved in future PRs
- Check out `2640-create-a-course-validation-changes` on MCBE (unless it has been merged)
- Run through course creation
- Try to create a course without submitting anything
=> [2640] Support new validation added for course creation

app/controllers/courses/modern_languages_controller.rb, spec/features/courses/modern_languages/new_spec.rb
The backend now supports additional validations, to test these when developing the frontend had to be developed to connect to them. 
This adds support to the modern langauges page
- Check out the branch `2640-create-a-course-validation-changes` (or master if it is merged) on MCBE
- Attempt to create a modern langauges course with no selection
=> [2640] Add error handling to modern language selection

app/controllers/courses/subjects_controller.rb, app/views/courses/_basic_details_tab.html.erb, spec/features/courses/subjects/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_subjects.rb
As it stands the subordinate subject field on the edit page (added because we added the functionality for course creation) does not do anything.
Make this field function as expected, allowing the user to modify the subordinate subject.
Try modifying an existing course's master and subordinate subjects.
=> [2568] Edit course subordinate subjects

.azure_parallel, azure-pipelines.yml
- Create an rspec file specifically for CI and use this when running specs
- removal of local parallel spec rspec config
=> [2664] - Clean up Azure test output config

app/views/courses/subjects/new.erb, spec/features/courses/subjects/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_subjects_page.rb
PE courses should not be able to be created by providers as we need to ensure they have been allocated places.
- If the user is an admin allow PE creation as normal
- If not add guidance linking them to a google form
=> [2677] Add guidance and links for non-admin users requesting PE courses

azure-pipelines.yml
The Azure DevOps pipelines don't display what commands are running so it can be hard to understand what's happening just from the output.
Add set -x to all the steps' jobs in the build pipeline to enable built-in shell tracing.
:shipit:
=> 2700 setup tracing on azure pipeline commands

app/views/courses/subjects/new.erb
Jesse noticed that the google form link for PE courses should be above the continue button on the subjects new page
- Move the link above the continue button
=> [2677] Move PE google form link above continue

app/controllers/provider_suggestions_controller.rb, spec/requests/providers_spec.rb
Attempts to visit `/providers/suggest` whilst unauthenticated resulted
in a 500 rather than redirecting to signin.
Require authentication in the controller to remedy this and redirect the
user appropriately.
There is a big diff in the spec that has been caused by moving the majority of the existing specs into an 'authenticated' context to allow the new spec to be in an 'unauthenticated' one.  The actual new code is only 48 onwards.
=> [2537] Require login on/providers/suggest

app/models/provider.rb, app/models/site.rb
Manage Courses Frontend can be fiddled with via site and provider addresses.
Patch the thing by encoding untrusted input (either by explicitly encoding it or removing the use of `.html_safe()` depending on suitability.
Steps to reproduce:
Modify address data in site or provider contact information such that it contains HTML. The HTML should appear where it is rendered such as on the edit locations page.
PoC: https://www.qa.publish-teacher-training-courses.service.gov.uk/organisations/2AT/2020/courses/3CXF/locations
=> [2763] Fix dan's code

app/views/providers/show.html.erb, app/views/recruitment_cycles/_courses_accredited_body.html.erb, spec/features/providers/show_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_show.rb
The organisation#show page ('organisations/A01') should display a 'Courses as an accredited body' link if the organisation is an accredited provider.
https://manage-courses-prototype.herokuapp.com/
- Add an additional section on the org#show page for the above
- Currently hidden from non-admin users (to be removed later)
Future PRs will include:
This will include a page to display all the training providers and an additional page which shows the courses accredited by the provider run by each training provider
=> [1591] Add courses as accredited body section to org show page

config/locales/en.yml, spec/factories/courses.rb, spec/features/courses/details_spec.rb, spec/features/courses/entry_requirements/edit_spec.rb, spec/features/courses/entry_requirements/new_spec.rb
Content issue
- Rename Equivalence test to Equivalency test
🚢
=> [2676] Rename Equivalence test to Equivalency test

app/views/courses/_basic_details_tab.html.erb, app/views/courses/confirmation.html.erb, spec/features/courses/confirmation_spec.rb, spec/features/courses/details_spec.rb
Some how study mode can be nil
Make it more protected
:shipit:
=> [2793] Fixed exploding nil study mode

config/locales/en.yml, spec/factories/courses.rb, spec/features/courses/details_spec.rb, spec/features/courses/entry_requirements/edit_spec.rb
Fix for https://github.com/DFE-Digital/manage-courses-frontend/pull/867
The backend/API sends `equivalence_test` so that needed to remain.
🚢
=> [2676] Fix equivalency_test locales

app/controllers/providers_controller.rb, app/helpers/breadcrumb_helper.rb, app/models/provider.rb, app/views/providers/show.html.erb, app/views/providers/training_providers.html.erb, app/views/recruitment_cycles/_courses_accredited_body.html.erb, config/routes.rb, spec/features/providers/training_providers_spec.rb, spec/site_prism/page_objects/page/organisations/training_providers.rb
**Follow on PR from #858** 
This PR adds a page that list's training providers for an accrediting provider. 
There will be an additional PR once the backend work is completed which will allow a user to click onto one of these providers and see the courses for the training provider that the accrediting provider validates the qualification.
- Adds a page which lists the training providers for an accredited provider
- Redirects non-admin users back to their org page (this will be removed at a later date)
- The course count section on the page will be fixed once the backend work mentioned above is provided.
=> [1589] Add an accredited provider's training providers' page

app/views/providers/training_providers.html.erb, config/routes.rb
Training providers
- Update URL from `/training_providers` to `/training-providers`
- Remove link to the provider as it doesn't go anywhere yet
🚢
=> 1589 cleanup training providers

azure-pipelines.yml, config.sh, config/settings.yml
Rename all references for manage-courses-frontend to publish-teacher-training
Rename of docker hub repo isn't possible (https://success.docker.com/article/how-do-you-rename-a-docker-hub-repository).
A new repos have already been created automatically when this branch was committed.
dfedigital / publish-teacher-training
Please review to ensure no code is effected by this change.
Prior to merge with master all release pipeline and variable library needs updating.
https://trello.com/c/toDX7vbt/2830-rename-dockerhub-repos
=> 2830-Rename manage-courses

app/helpers/provider_helper.rb, app/views/courses/index.html.erb, spec/features/courses/index_spec.rb, spec/site_prism/page_objects/page/organisations/courses_page.rb
Course creation is done, so we want to begin opening it up for more users to use.
Provide a link to course creation for accredited bodies.
=> [2371] Add link to course creation for accredited bodies

app/views/courses/preview/financial_support/_bursary.html.erb, app/views/courses/preview/financial_support/_loan.html.erb, app/views/courses/preview/financial_support/_scholarship_and_bursary.html.erb
Co-authored-by: Aga Dufrat <aga.dufrat@digital.education.gov.uk>
To get a loan, postgrad teacher training applicants must apply for UNDERGRADUATE student finance.
The GOV.UK pages on student finance don't make this clear: https://www.gov.uk/student-finance and https://www.gov.uk/student-finance/new-fulltime-students. (These pages are linked to from the student finance pages on Get into Teaching).
We contacted GDS about this lack of clarity. As a result, they made an edit to this page: https://www.gov.uk/teacher-training-funding (under 'Postgraduates'). So it's clear there, at least, that postgrads need to apply for undergrad loans - but it's not clear anywhere else.
We should change the text on course pages in Find to address this. Currently we say "You may also be eligible for a loan …
=> [2856] Add info to loan text on preview page

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/controllers/pages_controller.rb, app/controllers/sessions_controller.rb, app/models/base.rb, spec/controllers/application_controller_spec.rb, spec/controllers/errors_controller_spec.rb, spec/models/provider_spec.rb, spec/models/recruitment_cycle_spec.rb, spec/requests/not_found_spec.rb
When https://www.publish-teacher-training-courses.service.gov.uk/guidance was visited by an admin user a 500 would occur because a request was being made to discover the number of access requests for the heading but this could not be done because the authentication procedure was not followed.  
Use a safer method for storing the user token & move the redirection of the user to the login page into an individually skippable function.
=> [2842] Prevent guidance page 500ing

app/services/course_creation_step_service.rb, spec/features/courses/level/new_spec.rb, spec/services/course_creation_step_service_spec.rb
Course creation had an issue where if you went back from the new level page, it took you to the confirmation page
- Reimplement the back link connection to the courses list
=> [2864] Return to the courses list when navigating back from the new level page

app/views/layouts/application.html.erb
We now use Google Tag Manager
Remove Google  Analytics
🚢
=> [2607] Remove Google  Analytics

app/views/courses/confirmation.html.erb
In certain circumstances, it was possible to spam click the button and create multiple courses. To prevent this as a stop-gap before preventing it more on the API we want to disable the button via javascript from sending multiple submissions.
- Add the prevent double click from the design system to the button
- Make a course
- Spam that click button
=> [2873] Prevent multiple course creations via JS

app/controllers/courses/modern_languages_controller.rb, app/views/courses/modern_languages/_form_fields.html.erb, app/views/courses/modern_languages/edit.erb, app/views/courses/modern_languages/new.html.erb, app/views/courses/subjects/_form_fields.html.erb, spec/features/courses/modern_languages/new_spec.rb, spec/site_prism/page_objects/page/organisations/courses/new_modern_languages_page.rb
Users cannot create modern language courses because the subjects attribute triggers an error once the modern language subject is selected preventing the user from proceeding.
Watch the `modern_languages_subjects` attribute for errors instead of the subjects attribute (which is no longer used for modern language errors)
Requires: https://github.com/DFE-Digital/teacher-training-api/pull/1159
=> [2859] Use new modern languages attribute for errors

app/views/providers/training_providers.html.erb
We should change _'count of courses the accredited body certifies to be added'_ to _'Courses will be added here shortly'_ .
| Before       | After          | 
| ------------- |:-------------:| 
| <img width="540" alt="text_before" src="https://user-images.githubusercontent.com/38078064/74157275-e9442880-4c0f-11ea-8388-86180f9dda0b.png"> | <img width="550" alt="text_after" src="https://user-images.githubusercontent.com/38078064/74157295-f103cd00-4c0f-11ea-94de-dd8fa8caba2c.png">
- visit an accrediting provider page eg https://localhost:3000/organisations/A60/2020/training-providers
=> [2919] Change holding message on 'Courses as an accrediting body' page

app/helpers/provider_helper.rb, app/views/courses/index.html.erb, spec/features/courses/index_spec.rb, spec/site_prism/page_objects/page/organisations/courses_page.rb
Create course is being enabled for accredited bodies
Enable create course flow for accredited bodies
- Checkout this branch
- Go to an accredited body -> Create course should take you to the new flow
- Go to a non-accredited body -> Create course should take you to the google form
=> [2371] Allow accredited bodies to start creating new courses

app/controllers/courses/modern_languages_controller.rb, spec/features/courses/accredited_body/new_spec.rb, spec/features/courses/modern_languages/new_spec.rb
The subject list contains duplicates of all the languages selected (1 per time you pressed continue).
This also causes a 500 server error if you try to submit
Ensure modern languages are unique in the controller
1. Create a new secondary course: https://localhost:3000/organisations/2AT/2020/courses/level/new
2. Select Modern Languages as the subject
3. Select a few languages and **Continue**
4. Press **Back** on the age range page
5. Press **Continue** on the pick languages page
6. Repeat steps 4 & 5 as many times as you like
7. Progress to the confirmation page
Languages should only be listed once
=> [2987] Don't duplicate modern languages when creating a course

app/controllers/courses/applications_open_controller.rb, app/views/courses/accredited_body/new.html.erb
Courses were being created with duplicate of the subjects specified when they were made for a school direct.
- Remove the hidden fields specified in the accrediting body view as they are provided by the course creation partial
- Additionally permit the `accrediting_provider_code` to prevent localhost from erroring
- Go to the course creation for a school direct
- Create a secondary course
- Specify one subject
- Go through to the confirmation page
- Ensure there's only copy of the subject
=> [3022] Prevent duplicate subjects being added to school direct courses

app/controllers/concerns/course_basic_detail_concern.rb, app/helpers/view_helper.rb, app/views/courses/accredited_body/new.html.erb, app/views/courses/age_range/new.html.erb, app/views/courses/applications_open/new.html.erb, app/views/courses/apprenticeship/new.html.erb, app/views/courses/entry_requirements/new.html.erb, app/views/courses/fee_or_salary/new.html.erb, app/views/courses/level/new.html.erb, app/views/courses/modern_languages/new.html.erb, app/views/courses/outcome/new.html.erb, app/views/courses/sites/new.html.erb, app/views/courses/start_date/new.html.erb, app/views/courses/study_mode/new.html.erb, app/views/courses/subjects/_form_fields.html.erb, app/views/courses/subjects/new.erb, spec/features/courses/modern_languages/new_spec.rb, spec/features/courses/subjects/new_spec.rb
user cannot transerve from subject to modern language page
Fixed modern language issues whereby user cannot transverse from subject to modern language page
Amended  usage of `goto_confirmation` to be in concern
Removed `course_creation_back_button` as it uses `goto_confirmation`
Amended `course_creation_back_button`to be just `govuk_back_link_to`
=> [2983] Fixed modern language issues whereby user cannot transverse from subject to modern language page

Gemfile, Gemfile.lock, app/controllers/health_checks_controller.rb, app/controllers/heartbeat_controller.rb, config/routes.rb, spec/requests/health_checks_spec.rb, spec/requests/heartbeat_spec.rb
This new `/healthcheck` endpoint checks whether the dependencies of this
service are up. By implication of having returned a 200 OK status you
can also tell that this service is up.
Failure of dependencies results in a 502 bad-gateway status and a json
body showing which dependencies failed.
Front-door will probably continue to check root `/` for a 200 status as
that doesn't have any dependencies currently, so no need for a ping
endpoint as well.
This code is based on
https://github.com/DFE-Digital/find-teacher-training/pull/159
=> [3032] Add a healthcheck endpoint

Gemfile
As we are using httparty in a controller action, it should not have been
added to the test group.
Fixes uninitialized constand HeartbeatController::HTTParty error.
=> [3032] HTTParty is not a test only dependencies

Gemfile, Gemfile.lock
As we using webdriver gem there is no need to include selenium driver gem.
=> [3067] Remove selenium driver gem

Gemfile, Gemfile.lock
- We are using the 'rubocop-govuk' gem so no need to also have the 'rubocop' gem.
- This will stop dependabot raising pr's for the rubocop gem.
=> Remove rubocop gem

app/controllers/courses/modern_languages_controller.rb, app/controllers/courses/subjects_controller.rb, app/decorators/course_decorator.rb, app/views/courses/modern_languages/_form_fields.html.erb, app/views/courses/subjects/_form_fields.html.erb, spec/decorators/course_decorator_spec.rb, spec/features/courses/modern_languages/edit_spec.rb, spec/features/courses/subjects/edit_spec.rb, spec/models/subject_spec.rb, spec/requests/heartbeat_spec.rb
- When updating a published course to include modern languages it was not possible to select languages as part of the process
- When changing subjects for a published course this now uses a wizard
- This allows for languages to be selected eg French, German
- Previously user could not select languages for the course
- An existing params mechanism is reused `course: { subjects_ids: [33] }`
- This query string is passed to wizard where it populates hidden fields
- This all this data is then sent to update endpoint
- Fix deprecation around `media_type`
- Removed un-needed pending test
- This PR depends on https://github.com/DFE-Digital/teacher-training-api/pull/1205 for the backend
- https://trello.com/c/8c9tBWQE/3051-m-make-editing-course-subjects-use-a-wizard
- For an existing course. Test …
=> [3051] Wizard for editing course modern languages

app/helpers/view_helper.rb, app/views/courses/_basic_details_tab.html.erb, spec/features/courses/details_spec.rb, spec/features/courses/show_spec.rb, spec/site_prism/page_objects/page/organisations/course_details.rb
The mailto link on the course details page was not listing the provider code.
Add a regression test and fix the issue.
=> [3077] Fix provider code for support mailto link on course details page

app/controllers/courses/modern_languages_controller.rb, app/controllers/courses/subjects_controller.rb, app/views/courses/modern_languages/_form_fields.html.erb, app/views/courses/modern_languages/edit.erb, spec/features/courses/confirmation_spec.rb, spec/features/courses/modern_languages/new_spec.rb
Use the modern languages edit options to filter out languages to stop them from being replaced when changing the subjects.
During course creation, when we reach the final review page and go to change the subjects, once we end up on the modern languages editing page the checked modern languages will be cleared.
* Modern language edit option is used to filter modern languages from the regular subjects so that they are not replaced when changing the subjects
* Cleanup - remove cause/workaround for duplicate `subjects_ids`
* Refactor spec - remove `build_course_with_selected_value_request`
* Fix missing language selections when editing new course, add test coverage for failure, update impacted code & tests
Read individual commit patches and messages.
repro:
* go through course creation as a …
=> [3054] Fix missing language selections when editing new course

app/controllers/courses/modern_languages_controller.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/modern_languages/new_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/subjects/new_spec.rb
The modern language subjects are now always given to publish, and this was historically used to distinguish between courses that needed the modern languages selection page and those that did not.
Use the presence of the modern language subject to decide whether or not to show the modern languages page.
Similar issues may exist during modification of subjects in existing courses, this should be investigated and put into another card if applicable.
=> [3100] Fix modern languages step always showing

app/controllers/providers_controller.rb, app/views/courses/_course_table.html.erb, app/views/courses/_course_table_row.html.erb, app/views/providers/training_provider_courses.html.erb, app/views/providers/training_providers.html.erb, config/routes.rb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_courses_as_an_accredited_body.rb, spec/site_prism/page_objects/page/organisations/training_providers.rb
As an accrediting body
I want to see all the courses I accredit
So that I know what providers are running courses on our  behalf
* There is a link on the "Courses as an Accredited Body" page for each of our training providers (this continues to only be visible to admins)
* On the training provider's course page, we can see the list of courses  provided by that training provider.
Out of scope of this PR:
- the course count text on the "Courses as an Accredited Body" page
- CSV download on the "Courses as an Accredited Body" page
- breadcrumbs
[Trello card](https://trello.com/c/NVngxJin/3017-m-show-list-of-courses-by-training-providers-to-their-accrediting-body)
- check if the links work for different providers eg https://localhost:3000/organisations/B20/2020/training-providers
- check if …
=> [3017] Show list of courses by training providers to their accrediting body

config/routes.rb
Underscores can be confused with spaces if they are printed out with an underline beneath the URL.
Update the route path.
The path should be `/organisations/W20/2020/training-providers/13A/courses`,
not `/organisations/W20/2020/training_providers/13A/courses`
Guidance to review
Should we set up redirects for the old URLs?
=> Change underscores in training_providers route path to dashes

app/helpers/breadcrumb_helper.rb, app/views/providers/training_provider_courses.html.erb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/features/providers/training_providers_spec.rb
Breadcrumbs navigation needed updating on the Training providers page and breadcrumbs had to be added to the Training provider courses page
- Training providers page <img width="664" alt="Screenshot 2020-03-18 at 08 48 49" src="https://user-images.githubusercontent.com/38078064/76985728-90fff500-6938-11ea-8f6a-d75e97fccb10.png">
- Training provider courses page <img width="659" alt="Screenshot 2020-03-18 at 08 49 18" src="https://user-images.githubusercontent.com/38078064/76985734-93fae580-6938-11ea-887e-1ad07077b9ec.png">
- Breadcrumbs are showing on the 
- Training providers page eg path `/organisations/W20/2020/training-providers`
- Training provider courses eg path `/organisations/W20/2020/training-providers/13A/courses`
- All breadcrumbs links work correctly
=> [3147] Add breadcrumbs on courses as accredited body pages

app/views/courses/applications_open/_form_fields.html.erb
The other option was not selectable, which reduced accessibility.
Correct the `for=` attribute to match the radio button.
=> [3159] Make 'other' option on applications open selectable

app/views/sites/_form.html.erb, spec/features/sites/new_spec.rb
Removing this form field as it is overridden by geocoding lookup.
It is no longer needed.
=> [3192] Remove region select so users cannot edit

app/views/courses/_course_table_row.html.erb, spec/features/providers/courses_as_an_accredited_body_spec.rb
Links to the courses on Find on Courses as accredited body page didn't work because they were created with accredited body code instead of training provider code.
The _course_table_row partial is shared between courses page and courses as an
accredited body page. The link was created using `@provider` code, however for
accredited body page it has to use `@training_provider`'s code.
See below
- link on Find works correctly on /organisations/B20/2020/training-providers/2FY/courses
=> [3205] Fix the link to the course on Find

README.md
This eliminates the need to update the versions in the readme.
Using asdf makes setup a lot less steps.
=> Readme - use asdf-vm to install dependencies

app/decorators/application_decorator.rb, app/webpacker/stylesheets/_phase-tag.scss, app/webpacker/stylesheets/application.scss
This brings status tags inline with [GOV.UK Design System](design-system.service.gov.uk/components/tag).
=> 3204 Update tag component to be inline with GOV.UK Design System patterns

app/models/course.rb, spec/features/courses/entry_requirements/edit_spec.rb
The api can support `/api/v2/recruitment_cycles/2020/courses/*`, which was
added here https://github.com/DFE-Digital/teacher-training-api/pull/1288 so we
want the provider to be optional.
Make provider a shallow_path on the Course model.
Tests are passing.
=> [3211] Use new course api endpoint

app/controllers/providers_controller.rb, app/views/providers/_search.html.erb, app/views/providers/index.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/__snapshots__/autocomplete.spec.js.snap, app/webpacker/scripts/autocomplete.js, app/webpacker/scripts/autocomplete.spec.js, config/routes.rb, spec/features/providers/search_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_page.rb, spec/site_prism/page_objects/page/root_page.rb
Both org#index pages have a big hit on our API. We should had search then pagination to improve the performance (and UX)
- Add ability to search by provider name or provider code. Includes autocomplete functionality. This is available to admin users only
=> [3203] - Add Provider search to Organisation Index page

app/controllers/providers_controller.rb, app/views/providers/training_providers.html.erb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/features/providers/training_providers_spec.rb
As an accrediting body
I want to see all the courses I accredit
So that I know what providers are running courses on our behalf
* The course count text appears on the "Courses as an Accredited Body" page for each training provider
- only courses accredited by that specific accredited body are included
<kbd><img width="682" alt="Screenshot 2020-03-23 at 09 18 38" src="https://user-images.githubusercontent.com/38078064/77303838-830cf400-6ceb-11ea-912b-4b16bc8e2919.png"></kbd>
visit https://localhost:3000/organisations/B20/2020/training-providers
=> [3149] Add course count on training providers page

app/controllers/courses_controller.rb, app/controllers/providers_controller.rb, app/views/courses/delete.html.erb, app/views/courses/withdraw.html.erb, app/views/layouts/_flash.html.erb, app/views/providers/_search.html.erb, spec/features/courses/destroy_spec.rb, spec/features/courses/withdraw_spec.rb, spec/features/providers/search_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb, spec/site_prism/page_objects/page/root_page.rb
Following scenarios are not displaying error messages correctly i.e. not meeting GOVUK standards
- searching for a provider on the root page
- withdrawing a course
- deleting a course
Note that an error message audit for Publish is pending that may uncover more issues.
- fixes the `_flash.html.erb` partial that all the above scenarios use
- pass in an `id` so that a book mark link can be created that links the top section to the _offending_ form field
=> [3226] - Fix error messages 

README.md, app/controllers/application_controller.rb, spec/support/helpers.rb
- Can now login to review apps as a normal user and as an admin
- Previously could not login as admin
- This now allows an array of authorised_users
- This means multiple users can be set for basic auth
- Allowing multiple users to bypass dfe signin
- This is used by the review apps
- Update README on how to set this up locally
- visit review app - https://s121d02-3245-ptt-as.azurewebsites.net/ -  use incognito for different multiple logins
- find updated credentials on confluence https://dfedigital.atlassian.net/wiki/spaces/BaT/pages/316407835/Find+and+Publish-+all+the+links#Review-Apps
- login as normal user, should see app as normal user
- close window to logout
- new incognito window, https://s121d02-3245-ptt-as.azurewebsites.net/
- login as admin user, should be able to paginate …
=> [3245] Allow multiple authorised_users

app/controllers/providers/allocations_controller.rb, app/views/providers/allocations/_request_status.html.erb, app/views/providers/allocations/index.html.erb, app/views/ucas_contacts/show.html.erb, spec/features/allocations_spec.rb, spec/site_prism/page_objects/page/providers/allocations/index_page.rb
Update copy of existing "Request PE courses for 2021/22" page.
Website: https://s121d02-3228-ptt-as.azurewebsites.net
- Login to the review app as an admin user
- Go to https://s121d02-3228-ptt-as.azurewebsites.net/organisations/O33
- Scroll to the admin feature at the bottom of the page
- View the requests for PE allocations
- Page loads and shows a table with three providers, their status and actions. 
At this moment, the list of providers is a static list and the links do not take the user to any particular part of the service.
=> [3228] Add accrediting bodies allocation report

app/controllers/training_providers_courses_controller.rb, app/decorators/course_decorator.rb, app/views/providers/training_providers.html.erb, spec/decorators/course_decorator_spec.rb, spec/requests/providers_spec.rb
Improved accredited body courses csv
- Humanize header names
- Add Find URL
- Add application open date
- Humanize study type, outcome and content status
- visit review app - https://s121d02-3263-ptt-as.azurewebsites.net/ - use incognito for different multiple logins
- find updated credentials on confluence https://dfedigital.atlassian.net/wiki/spaces/BaT/pages/316407835/Find+and+Publish-+all+the+links#Review-Apps
- login as admin user
- Navigate to `/organisations/U80/2020/training-providers`
=> 3263 update accredited body courses csv

app/controllers/providers/allocations_controller.rb, app/views/providers/allocations/requests.html.erb, config/routes.rb, spec/features/allocations_request_spec.rb
The request form page
Add the request form page
Just the page is done
Log in as admin and navigate directly to the request form page
```https://s121d02-3229-ptt-as.azurewebsites.net/organisations/B1T/2020/allocations/#{provider_code}/requests```
replace `#{provider_code}` with a proper one.
ie
https://s121d02-3229-ptt-as.azurewebsites.net/organisations/B1T/2020/allocations/E14/requests
https://s121d02-3229-ptt-as.azurewebsites.net/organisations/B1T/2020/allocations/M20/requests
=> [3229] add allocations request form page

app/controllers/providers/allocations_controller.rb, app/views/providers/allocations/_request_status.html.erb, spec/features/allocations_spec.rb, spec/site_prism/page_objects/page/providers/allocations/index_page.rb
```
Given I am on the "Request PE courses for 2020/21" page
When I view the list of training providers on that page
Then I see that the list of training providers is limited to those that offer courses I accredit
And the list of training providers is also limited to those that offer courses that have the subject physical education
And the list of training providers is also limited to those that offer courses that are fee-funded
```
- Use the filtering on the v2 https://github.com/DFE-Digital/teacher-training-api/pull/1306 to list only training providers that provide PE, fee-funded course
- add a link to the Request form if the allocation status is "NOT YET REQUESTED".
<kbd><img width="644" alt="Screenshot 2020-04-14 at 16 20 30" src="https://user-images.githubusercontent.com/38078064/79243 …
=> [3254] List only training providers that provide PE, fee-funded course

Dockerfile
Webpacker 5.1.0 removed yarn integrity checker. This commit ensures that
we also use the yarn.lock we generated while developing rather than updating
it. It should also fail if package.json & yarn.lock are out of sync.
Yarn's own maintainer discourages its use: https://github.com/yarnpkg/yarn/issues/6427#issuecomment-434499073
and suggests the following solution:
>Solution
Remove the integrity initializer and the configuration options. Encourage
developers to ensure yarn install in local environments and
yarn install --frozen-lockfile as part of deployment.
Other references:
https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile
https://github.com/rails/webpacker/pull/2518
=> Add --frozen-lockfile to docker image yarn install

app/views/providers/allocations/_request_status.html.erb, app/views/providers/allocations/index.html.erb, spec/features/allocations_spec.rb, spec/site_prism/page_objects/page/providers/allocations/index_page.rb
```
As an accredited body
I need not see extra content if there is no data or action available
So that I can stay focused on the actions I can take
```
Closes #1030 
When the training providers don't have any PE fee-founded courses, 'Request PE again' section and some other elements of the text are not showing.
| PE fee-founded courses | No PE fee-founded courses | 
| ------------- |:-------------:| 
| <img width="424" alt="Screenshot 2020-04-21 at 18 26 56" src="https://user-images.githubusercontent.com/38078064/79894693-bda6a100-83fd-11ea-8ffa-161e867037d4.png">|<img width="507" alt="Screenshot 2020-04-21 at 18 19 01" src="https://user-images.githubusercontent.com/38078064/79894444-5f79be00-83fd-11ea-81d7-d202b4a21b19.png"> |
- `/organisations/2AT/2020/allocations` looks like the …
=> [3286] Allocations when no training providers returned from the API

app/views/providers/_search.html.erb
The Autocomplete Search field on the organizations page is only for admin. When it was implemented the admin styling was not applied.
=> Admin only features should be marked as such

app/controllers/providers/allocations_controller.rb, app/views/providers/allocations/_request_status.html.erb, app/views/providers/allocations/requests/_not_requested.html.erb, app/views/providers/allocations/requests/_yes_requested.html.erb, app/views/providers/allocations/show.html.erb, spec/features/providers/allocations_spec.rb, spec/site_prism/page_objects/page/providers/allocations/index_page.rb, spec/site_prism/page_objects/page/providers/allocations/show_page.rb
closes #1032 
- Adds a partial for when training provider decides not to request 
- wire up "View Confirmation" link to the show page.
- Visit https://s121d02-3249-ptt-as.azurewebsites.net/organisations/B20/2020/allocations
- Click "Confirm choice" 
- select "no" and continue
- Declined confirmation should appear
- view a "requested" confirmation
- view a "not requested"  confirmation
=> [3249] Allocations no path journey

app/controllers/providers/allocations_controller.rb, app/models/allocation.rb, app/models/provider.rb, spec/features/providers/allocations_spec.rb
- https://trello.com/c/xZDgo5YV/3298-m-4d-create-allocation-request-action
- going thru yes and no journey should create an allocation in the api with the correct `number_of_places`
- When accepting PE allocations call API to create allocation with
unspecified `number_of_places`
- When declining PE allocations call API to create allocation with zero
`number_of_places`
- wire up api from https://github.com/DFE-Digital/teacher-training-api/pull/1323
- or if merged, test on review app
- go thru yes journey
- allocation with 42 `number_of_places` should have been created
- go thru no journet
- allocation with 0 `number_of_places` should have been create
- NOTE: as endpoint is not idempotent it is possible to have more that one allocation where there should only be one
=> [3298] Create allocation thru API

app/views/providers/allocations/requests/_not_requested.html.erb, app/views/providers/allocations/requests/_yes_requested.html.erb
login as an admin and visit /organisations/S21/2020/allocations
check confirmations pages for request and not requested allocations.
Pages should playback the training provider name on the page.
FOr requested allocations, the page should display the Accredited bodies email address where the confirmation would have been sent to
=> [3133] Dynamically display provider details

Rakefile, lib/tasks/js_spec.rake, package.json
Currently, we are not running javascript unit tests (Jest) as part of our
pipeline or as part of our standard development process. This commit adds
jest testing command to rake so that for the moment we will at least be
running some sort of JS testing locally before pushing to github.
The implementation was copied from Find.
=> [2943] Add JS testing to Rake default task

app/controllers/provider_suggestions_controller.rb, app/webpacker/scripts/autocomplete.js, app/webpacker/scripts/autocomplete.spec.js, spec/fixtures/api_responses/provider-suggestions.json, spec/requests/provider_suggestions_spec.rb
https://trello.com/c/4nSbRPzG/3276-s-publish-provider-autocomplete-not-encoding-request-correctly
Changed the way the autocomplete generates the query string - now uses the encodeURIComponent function to help protect against unicode contamination. See this PR for a similar change on Find https://github.com/DFE-Digital/find-teacher-training/pull/204
=> [3276] Add encoding for autocomplete queries

Gemfile, Gemfile.lock
We want to start using DFE developed 'govuk_design_system_formbuilder'
to build out our forms. This will help ensure that we are using consistent
markup and should hopefully speed up the development process for creating forms,
Before completely migrating all existing forms to the new builder we
should try and create new forms using the builder. We can achieve this by
specifying the formbuilder as a `form_with` or `form_for` param
https://github.com/DFE-Digital/govuk_design_system_formbuilder#setup-
Once all forms have been migrated we can look to make it our default formbuilder
and remove all the extra formbuilder params added as part of the rollout.
Repo: https://github.com/DFE-Digital/govuk_design_system_formbuilder
Documentation and demos: https://govuk-form-builder.netlify.app/
More …
=> Adds DFE developed GOVUK Design System Formbuilder Gem

app/webpacker/stylesheets/_admin-only.scss
=> Make Admin section text inputs background white

README.md, config/environments/development.rb, config/puma.rb, config/settings.yml, config/settings/development.yml
Having to deal with SSL certificates is a pain.
Skip SSL in local dev mode.
🚀
=> [3337] don't require SSL in development mode

app/controllers/providers/allocations_controller.rb, app/views/providers/allocations/initial_request.html.erb, spec/features/requesting_new_allocations_spec.rb
Only list training providers without previous allocations on the "Who are you requesting a course for?" page
**User story**
```
As an accredited body, 
I need to see all the organisations I accredit 
that didn't offer fee-funded PE last year, 
So that I can select one to request allocations on their behalf
```
We decided to implement it in Publish instead of adding negated filtering to the API. The controller action will make 2 API calls
Closes #1059
* All organisations that have a course accredited by the accredited body last cycle **not including fee-funded PE** are listed
<kbd><img width="501" alt="Screenshot 2020-05-01 at 13 14 24" src="https://user-images.githubusercontent.com/38078064/80804666-baee3d80-8bad-11ea-82bd-375ee19e3b20.png"></kbd>
- go to …
=> [3339] Only list training providers without previous allocations

app/controllers/providers/allocations_controller.rb, app/models/allocation.rb, app/services/allocation_services/create.rb, app/services/service_pattern.rb, spec/features/providers/allocations_spec.rb, spec/services/allocation_services/create_spec.rb
We have implemented `request_type` on the Allocation API endpoint.
This PR updates publish to pass the `request_type` param to the API
Initial (new) allocation requests send:
`request_type: "initial"`
`number_of_places: <int>`
Repeat allocations requests send:
`request_type: "repeat"`
Declining an repeat allocation send:
`request_type: "decline"`
Initial requests update `number_of_places`
Repeat and declined requests have the request type changed: `repeat|declined`
=> 3331 send request type from publish when creating updating an allocation

app/form_objects/initial_request_form.rb, spec/features/requesting_new_allocations_spec.rb
If the user is attempting to search for a provider which we do not have
on the system, we display an error message with some advice to contact
support to get the provider added.
- Login as an accredited body user
- Go to request new allocation (https://s121d02-3250-ptt-as.azurewebsites.net/organisations/B20/2020/allocations/request) 
- Search for a provider who would not be on the system
- Displays error message with hint text to contact support
- Try a search for the provider but do not type in the provider name
- Error message saying you need to type in more information
=> [3250] Update the error copy for search field

app/controllers/sessions_controller.rb, app/views/sessions/new.html.erb, app/webpacker/stylesheets/_banner.scss, app/webpacker/stylesheets/application.scss, azure/template.json, config/settings.yml, spec/features/sessions_signin_intercept_spec.rb
When Signin is unavailable we need to be able to display an alternative login interface/system. 
This was previously open as https://github.com/DFE-Digital/publish-teacher-training/pull/1061 which was approved.
Add a start page that can be enabled with a feature flag. This start page will ultimately provide a magic link interface for users to login. (not included in this PR).
This is relatively straightforward but it turned out to be complex to add a test that when the feature isn't enabled we still redirect to DfE Signin. Turns out we don't have an explicit test for this (as far as I could see in any case). 
DfE Signin doesn't actually return to us when authentication fails but mocking failure out seemed to be the only way to test that it was included and we were redirecting when the …
=> [3340] start page

spec/features/sessions_signin_intercept_spec.rb
Fixes the linting errors that make builds fail following the rubocop-govuk update from 3.8.0 to 3.9.0
=> Fix linting errors that make builds fail

app/controllers/providers/allocations_controller.rb, app/flows/initial_request_flow.rb, app/models/allocation.rb, app/views/providers/allocations/check_your_information.html.erb, app/views/providers/allocations/number_of_places.html.erb, app/views/providers/allocations/places.html.erb, app/views/providers/allocations/requests/_yes_requested.html.erb, spec/features/requesting_new_allocations_spec.rb, spec/site_prism/page_objects/page/providers/allocations/check_your_information_page.rb, spec/site_prism/page_objects/page/providers/allocations/number_of_places_page.rb
As an accredited body, 
I need to review my number before submitting, 
So that I know it is right
```
Given I am on the "How many places would you like to request?" page
When I input a number into the box and click continue
Then I should move to the "Check your information before sending your request" page 
Given I am on the "Check your information before sending your request" page 
When I review the number and click "submit"
Then I should move to the "Request sent confirmation" page 
Given I am on the "Check your information before sending your request" page 
When I click "change" beside the number
Then I should move back to the "How many places would you like to request?" page
```
Closes #1085
- add "Check your information" page <kbd>
- user is able to change the number of places by …
=> [3251] Add check your information page and create initial allocation request

app/controllers/providers_controller.rb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/features/providers/training_providers_spec.rb
Users are getting 403 responses when trying to view courses as an accredited body.
There were some remnants of this being an admin only feature left in the code. Remove them so as non-admin users don't get redirected or 403-ded
Change the way that we request courses from the API to avoid going through the provider#show endpoint and hitting the authorization failure.
NB: This requires https://github.com/DFE-Digital/teacher-training-api/pull/1354 to be merged
This needs to be reviewed as a non-admin user on the review app. I'm not sure whether we have a non-admin user that belongs to an accredited body so manual checking requires a bit of finagling in the console. I can pair on that bit if it helps.
We don't check authorization in the frontend as we rely on the API to enforce that so we …
=> [3364] User getting 403 errors when viewing their training providers on the courses as an accredited body page

app/controllers/providers_controller.rb
We updated the 'Courses as an accredited body' functionality to avoid 403 errors that some users were experiencing (these were due to using the providers endpoint to retrieve the courses)
Prior to the update introduced the results were sorted by course code.
Add sorting to the course results. The API doesn't currently support this and there is no pagination so we can just sort in the frontend.
=> [3364] Add sorting to training provider courses

app/views/notifications/index.html.erb, app/views/providers/_notifications_sign_up_link.html.erb
There is a concern that we aren't being clear enough that the notifications we are about launch are email notifications.
We have decided to make minor copy updates to included the phrase "email'.
What does success look like?
The following are updated to match attached designs and prototype
- Copy under Notifications heading in the sidebar (design attached)
- Copy and radio button label on the Manage Notifications page (prototype link attached)
=> [3390] Update notification page copy

app/controllers/providers/allocations_controller.rb, app/models/allocation.rb, app/services/allocation_services/create.rb, app/view_objects/allocations_view.rb, app/views/providers/allocations/_request_status.html.erb, app/views/providers/allocations/index.html.erb, app/views/providers/allocations/repeat_request.html.erb, app/views/providers/allocations/requests/_yes_requested.html.erb, spec/features/providers/allocations_spec.rb, spec/features/requesting_new_allocations_spec.rb, spec/services/allocation_services/create_spec.rb, spec/site_prism/page_objects/page/providers/allocations/new_page.rb, spec/view_objects/allocations_view_spec.rb
- https://trello.com/c/tZVaEdzD/3383-use-last-year-allocations
- Now that we have imported last years allocations we can start using them instead of dummy data
- `request_type` now part of api and not via a virtual attribute
- Remove hard coded dummy data
- Confirmation page `number_of_places` placeholder now uses API data
- Depends on https://github.com/DFE-Digital/teacher-training-api/pull/1361
- Request a repeat allocation
- This allocation should have same number_of_places as previous allocation and can be seen on the confirmation page
=> [3383] Use last years allocation from API

app/views/providers/allocations/index.html.erb
- https://trello.com/c/tZVaEdzD/3383-use-last-year-allocations
- If an accredited body does not have any associated training
providers and they create a new inital allocation the table showing
these allocations is missing
- This change fixes the above
- We now use the actual allocations to determine if there are initial
allocations
- Find a provider without any associated training providers eg `B16`
- Create an initial allocation
- This allocation should be visible in the initial allocations table on the index page
=> [3383] Missing inital allocations table

Guardfile, app/controllers/providers/users_controller.rb, app/models/provider.rb, app/views/providers/users/index.html.erb, config/routes.rb, spec/factories/providers.rb, spec/features/providers/user_spec.rb, spec/site_prism/page_objects/page/providers/users/index_page.rb, spec/support/serializers/provider_serializer.rb
**Note** that API changes need to be merged / deployed first - https://github.com/DFE-Digital/teacher-training-api/pull/1360
As a provider
I need to see the other users that have access to my org
So that I can check the right people have access
- Creation of new page that lists users that have access to a particular provider (organisation)
- This is dependent on API changes so you will need to test locally
- Run the API on branch `3305-return-user-association-from-provider`
- Visit a providers fancy new users page `/organisations/K30/users`
=> [3305] - Create org users page

app/controllers/providers_controller.rb, spec/features/providers/training_providers_spec.rb
- https://trello.com/c/Hwg5ZBqT/3422-accredited-bodies-should-be-able-to-request-pe-allocations
- The API has changed and now training providers returns itself if there offer their won courses
- There is a view in publish where we do not want the provider itself to be show and has therefore been removed on the frontend
- There is an API change and now training providers list returns the
current provider if they themselves offer courses
- We don't want this in publish training providers page so has been
removed here
- Depends on https://github.com/DFE-Digital/teacher-training-api/pull/1374
- Find a provider that also has their own courses eg http://localhost:3000/organisations/2AT/2020/training-providers
- They should not see themselves on the training providers page
=> [3422] Remove own provider from training providers

app/view_objects/allocations_view.rb, spec/view_objects/allocations_view_spec.rb
Allocation status was pluralised incorrectly. When number of places is `1` the status should not be pluralised. 
* **Before**<kbd> <img width="979" alt="Screenshot 2020-05-21 at 11 22 05" src="https://user-images.githubusercontent.com/38078064/82549991-c4881700-9b55-11ea-83a5-eb13f0c36fd6.png"></kbd>
* **After** <kbd><img width="981" alt="Screenshot 2020-05-21 at 11 21 31" src="https://user-images.githubusercontent.com/38078064/82550003-c81b9e00-9b55-11ea-84c0-15624e5ebf81.png"></kbd>
-  create a new initial allocation with 1 place
- view index page
=> [3414] Correctly pluralise allocation status

Gemfile.lock
Reverts DFE-Digital/publish-teacher-training#1120
Backing this out as there is an [issue with 0.3.4](https://github.com/m0n9oose/omniauth_openid_connect/issues/59) which is preventing login with DfE Signin.
=> Revert "Bump omniauth_openid_connect from 0.3.3 to 0.3.4"

.rspec_parallel, app/controllers/providers/allocations_controller.rb, app/flows/initial_request_flow.rb, app/form_objects/initial_request_form.rb, app/views/providers/allocations/initial_request.html.erb, spec/form_objects/initial_request_form_spec.rb, spec/requests/heartbeat_checks_spec.rb
- https://trello.com/c/o5I1mnwd/3398-m-adding-validation-to-who-are-you-requesting-a-course-for-page
- There is missing validation on the first page of the initial request journey when the user does not select a radio option and continues
- Add validation to initial request flow
- Fix deprecation warning when running test suite
- Added .rspec_parallel config to speed up local tests
- Create an initial allocation request
- On the first page do not select a radio option and continue
- Should see validation message
=> [3398] validation no provider

app/flows/initial_request_flow.rb, app/views/providers/allocations/initial_request.html.erb, spec/views/providers/allocations/initial_request.html.erb_spec.rb
- https://trello.com/c/6Znq0sUB/3402-when-there-are-no-associated-providers
- On the initial request journey on the first page when there are no associated providers the radio button divider would show and only one radio button with the provider search option
- When there are no associated providers hide the radio buttons and only show the search field
- Create a new initial request for a provider that does not have any associated providers
- On the first page should not show radio buttons and only search field should be present in the form
=> [3402] Tweak Initial request form when there are no associated providers

app/controllers/notifications_controller.rb, app/models/user_notification_preferences.rb, app/view_objects/notifications_view.rb, app/views/notifications/index.html.erb, config/routes.rb, spec/controllers/notifications_controller_spec.rb, spec/factories/user_notification_preferences.rb, spec/features/notifications_spec.rb, spec/models/user_notification_preferences_spec.rb, spec/site_prism/page_objects/page/notifications/index_page.rb, spec/support/resource_list_to_jsonapi.rb, spec/support/serializers/user_notifications_preferences_serializer.rb, spec/view_objects/notifications_view_spec.rb, spec/views/notifications/index_spec.rb
We are adding a feature to enable a user (from an accredited body only at this stage) to enable/disable email notifications when a course that their accredited body ratifies is created or updated.
Update the existing implementation to use the new API endpoint at `/user_notification_preferences`
Runs with [this API branch](https://github.com/DFE-Digital/teacher-training-api/pull/1369) which has yet to be approved/merged.
=> [3392] Integrate notifications endpoint

app/views/providers/_notifications_sign_up_link.html.erb
We are using `request.referer` to get the provider_code on the notifications page so we don't need to pass it in the query string.
=> [3392] Don't pass provider_code in the query string

app/helpers/provider_helper.rb, app/views/courses/index.html.erb, spec/features/courses/index_spec.rb, spec/helpers/provider_helper_spec.rb, spec/site_prism/page_objects/page/organisations/courses_page.rb
**User story**
```
As a provider 
I need to publish a course and choose an accrediting body
So that I can recruit and have the course accredited by another provider
```
* If the accrediting body has opted-in to receive email notifications they are notified when a course is created - Done in #1111
* ALL providers can now create courses i.e. no more google form
- Try to create a course for a provider that is not an accredited body
=> [3442] Allow all providers to create a new course

app/flows/initial_request_flow.rb, app/form_objects/initial_request_form.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/form_objects/initial_request_form_spec.rb
API has been updated to allow for two character provider searches. See https://github.com/DFE-Digital/teacher-training-api/pull/1378
- During the initial allocation flow, a validation error is displayed on the form if the accredited body searches for a provider with a query string containing only one character
- Run this branch against https://github.com/DFE-Digital/teacher-training-api/pull/1378
- Request an initial allocation. Select other provider and enter a single character in the search field. Validation error should be displayed
- Need some copy guidance on the error message
- I've followed the existing validation pattern for `blank_search_query`
=> [3399] - Initial allocation flow: provider search validation

app/views/providers/allocations/initial_request.html.erb, app/views/providers/allocations/pick_a_provider.html.erb
During a demo we identified that the autocomplete was not enabled on
some of the provider search fields. This did not block the user from
completely their task as the progressive enhanced version was able to
allow them to complete it successfully.
=> [3461] Fix missing autocomplete functionality

app/controllers/providers/allocations_controller.rb, app/form_objects/repeat_request_form.rb, app/views/providers/allocations/check_your_information.html.erb, app/views/providers/allocations/edit.html.erb, app/views/providers/allocations/new_repeat_request.html.erb, spec/site_prism/page_objects/page/providers/allocations/new_page.rb
Fixes an 500 error a user would get if they did not select yes/no.
This commit also removed the "allocation" namespace we added awhile ago.
=> [3454] Add validations to repeat allocations

app/views/providers/_notifications_sign_up_link.html.erb, spec/features/notifications_spec.rb, spec/views/providers/show_spec.rb
A [previous
PR](https://github.com/DFE-Digital/publish-teacher-training/pull/1118) was merged that released the notifications feature to all accredited body users. Unfortunately there is an issue with the notifications not being sent on course update.
This reverts that PR (Couldn't easily git revert as there were conflicts) while we address the issue.
=> Make notifications admin only

app/views/providers/_notifications_sign_up_link.html.erb
The notifications link has been made an admin only feature. 
Add the markup to show it as such in the UI.
=> Add admin feature markup

app/views/providers/_notifications_sign_up_link.html.erb, spec/features/notifications_spec.rb, spec/views/providers/show_spec.rb
We are releasing the notification preferences feature to users so no longer need the 'Admin feature' flag.
Revert the PRs that added the restriction and markup.
=> 3472 Remove admin only from notifications

app/controllers/providers_controller.rb, app/view_objects/provider_view.rb, app/view_objects/providers_view.rb, app/views/providers/_notifications_sign_up_link.html.erb, app/views/providers/index.html.erb, app/views/providers/show.html.erb, spec/features/notifications_spec.rb, spec/site_prism/page_objects/page/root_page.rb, spec/view_objects/provider_view_spec.rb, spec/view_objects/providers_view_spec.rb, spec/views/providers/index_spec.rb, spec/views/providers/show_spec.rb
Since turning notifications on enables them for all organisations the notifications link should appear on the organisations page if the user has more than one accredited body.
When a user is associated with more than one accredited body display a notifications link in the right sidebar on the organisations index page (at`/`) and don't display it on the organisation show pages (e.g. `/organisations/T92`)
- <kbd><img width="791" alt="Screenshot 2020-05-28 at 14 46 29" src="https://user-images.githubusercontent.com/38078064/83411563-68a07680-a410-11ea-98a5-3f37b9c3bdee.png"></kbd>
- log in as a user with multiple accredited bodies 
- visit root path
- notifications link appears on the organisations page (index) `/`
- notifications link does not appear on the providers page e.g. …
=> [3455] Conditionally show notifications link on the organisations page

app/flows/initial_request_flow.rb, app/form_objects/initial_request_form.rb, app/views/providers/allocations/number_of_places.html.erb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/fixtures/api_responses/provider-suggestions.json, spec/form_objects/initial_request_form_spec.rb, spec/requests/provider_suggestions_spec.rb
When the accredited body enters the number of places they require for an initial allocation, we can only accept positive integers greater than 0.
Validation error shown on "How many places would you like to request page" if user enters the following values in the 'number of places' field:
- empty value (e.g "")
- 0
- non-integer (e.g. "a")
- Go to a provider's allocation page (e.g. `/organisations/K30/2020/allocations/) and select the 'initial allocation' flow. Once you reach the 'How many places would you like to request' page, please try and break it.
- Was considering using HTML `input=number` to handle some of the validation but apparently this has [fallen out of favour due to accessibility concerns](https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-th …
=> [3433] - Add validations to "How many places would you like to request?" page

.rubocop.yml, app/flows/initial_request_flow.rb, app/models/allocation.rb, app/views/providers/allocations/pick_a_provider.html.erb, spec/features/providers/allocations/initial_allocation_spec.rb
- https://trello.com/c/dtbw2raY/3440-stop-filtering-out-providers-from-provider-search-initial-allocation-request
- When searching for a provider for an allocation we now return providers that also have allocations
- As a result if one of these are selected we now take the user to modify the allocation
- When creating a new allocation we now check if an allocation already
exists
- If yes, proceed to edit the existing allocation
- If now, proceed with the current journey to create the allocation
- Depends on https://github.com/DFE-Digital/teacher-training-api/pull/1388
- Create a new allocation. Search for a provider that already has an initial, repeat or allocation
- With Javascript the autocomplete will select the provider and on submit will take the user to edit the existing allocation …
=> [3440] Check for existing allocation then proceed

app/flows/initial_request_flow.rb, app/form_objects/initial_request_form.rb, app/models/allocation.rb, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/form_objects/initial_request_form_spec.rb, spec/models/allocation_spec.rb
Discovered that a combination of letter and number was still considered 'valid' when filling out the 'number of places' field when creating or updating an initial allocation
- Adds regex to validate that 'number of places' only contains numbers
- Add Allocation model validation specs
- Remove unused code from Allocation model
When you fill out the 'number of places' field with a letter-number combination (e.g. '3a') you should now see a validation error.
=> [3433] - Add new 'number_of_places' validation

app/controllers/providers/users_controller.rb, app/helpers/breadcrumb_helper.rb, app/views/providers/access_requests/new.html.erb, app/views/providers/show.html.erb, app/views/providers/users/index.html.erb, spec/features/providers/index_spec.rb, spec/features/providers/user_spec.rb
Display "users"
https://s121d02-3479-ptt-as.azurewebsites.net/
Go to any organisation page and click on the "users" link in the sidebar
=> [3479] Add users link to org show sidebar

app/controllers/provider_suggestions_controller.rb, app/controllers/providers/allocations_controller.rb, app/controllers/providers/edit_initial_allocations_controller.rb, app/flows/initial_request_flow.rb, app/models/provider.rb, app/models/provider_suggestion.rb, app/views/recruitment_cycles/_allocations.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/autocomplete.js, config/routes.rb, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb, spec/views/providers/show_spec.rb
- https://trello.com/c/QpRrdwxL/3466-pre-launch-task-make-accredited-bodies-able-to-see-allocation-pages
- Allocations is currently feature flagged to admins only, this change removes that
- Admin only restriction has been lifted
- Users of accredited bodies can access allocations
- Depends on https://github.com/DFE-Digital/teacher-training-api/pull/1394
- Access allocations as a user of an accredited body
- Should able to access allocations pages
=> [3466] Allocations no longer restricted to admins

app/views/layouts/_header.html.erb, app/webpacker/stylesheets/_header.scss, app/webpacker/stylesheets/application.scss
Product name is now closer to GOV.UK logo and position the navigation
to the far right
=> [3474] Updates header design to match prototype

config/initializers/assets_cache_header.rb
None of our assets were being cached by the browser because cache-control
was not being set. I set it to a 1 year because our assets use a cache
busting technique so if we were to update their content the filename would
be different and therefore the browser would fetch and use the updated
assets.
Reference:
mikerogers.io/2019/11/02/how-to-set-cache-control-headers-for-rails-webpacker-and-sprockets-assets.html
visit https://s121d02-3409-ptt-as.azurewebsites.net/
Check asset headers and see if cache control is set to expire in a years time
=> [3409] Set cache control in assets header

azure-pipelines.yml
- https://trello.com/c/angQ7t5X/2943-m-run-js-tests-as-part-of-the-ci-pipeline
- This runs the javascript tests as part of the build
- Added task to CI to run js tests
- Linting now occurs before tests
- Added a failing js test
- Run in CI
- Build should fail
=> [2943] Run javascripts tests as part of build

app/controllers/providers_controller.rb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/features/providers/training_providers_spec.rb
“Courses as accredited body” page is extremely slow, 20-40sec Time to First Byte. This is because the API endpoint returning the list of training providers or course counts are extremely slow.
- The V2 end point has been updated to calculated the accredited_body
course counts, resulting in faster load times - see https://github.com/DFE-Digital/teacher-training-api/pull/1400. Publish therefore needs to be updated to handle the new response.
See https://github.com/DFE-Digital/teacher-training-api/pull/1400 for guidance on running locally and manually testing the changes
=> [3341] - Optimise courses as an accredited body query

app/views/providers/allocations/edit.html.erb, app/views/providers/allocations/new_repeat_request.html.erb, app/views/providers/allocations/number_of_places.html.erb, app/views/providers/edit_initial_allocations/do_you_want.html.erb, app/views/providers/edit_initial_allocations/number_of_places.html.erb, spec/features/providers/allocations/initial_allocation_spec.rb
Previously the dfe govuk design system form builder did not support
captions and as a work around they were placed outside the label/heading.
This caused issues with error styling where the caption would not be include
in the error group.
Caption support reported and fixed https://github.com/DFE-Digital/govuk_design_system_formbuilder/issues/133
Login as an accredited body user
Create/edit allocations and try force validation errors
=> [3508] Fix caption styling error

app/views/providers/edit_initial_allocations/number_of_places.html.erb, spec/features/providers/allocations/edit_initial_allocation_spec.rb
https://trello.com/c/8JXumJFG/3463-s-change-link-on-check-your-answer-page-does-not-playback-the-correct-number-of-places-entered-on-how-many-places-would-you-like
Specify number of places to be pre-filled if there's an existing param
=> [3463] Prefil number of places if param exists

app/views/courses/subjects/_form_fields.html.erb, spec/features/courses/subjects/edit_spec.rb, spec/features/courses/subjects/new_spec.rb, spec/site_prism/page_objects/page/organisations/course_subjects.rb, spec/site_prism/page_objects/page/organisations/courses/new_subjects_page.rb
When editing a secondary course with multiple subjects, the second subject field is closed, even if a subject is selected.
- Open the details element when the second subject is present
- Remove inline styles, replace with classes
- Tweak spacing
- Fix naming of test variable
(Ignore whitespace when reviewing)
https://trello.com/c/RyXdo7Ry/3512-open-the-secondary-subject-field-when-present
=> Open the secondary subject field when present

app/views/courses/accredited_body/edit.html.erb, app/views/courses/accredited_body/new.html.erb, app/views/courses/age_range/_form_fields.html.erb, app/views/courses/applications_open/_form_fields.html.erb, app/views/courses/applications_open/edit.html.erb, app/views/courses/applications_open/new.html.erb, app/views/courses/apprenticeship/_form_fields.html.erb, app/views/courses/confirmation.html.erb, app/views/courses/fee_or_salary/_form_fields.html.erb, app/views/courses/index.html.erb, app/views/courses/modern_languages/_form_fields.html.erb, app/views/courses/modern_languages/edit.erb, app/views/courses/modern_languages/new.html.erb, app/views/courses/send/edit.html.erb, app/views/courses/sites/new.html.erb, app/views/courses/start_date/edit.html.erb, app/views/courses/start_date/new.html.erb, app/views/courses/study_mode/_form_fields.html.erb, app/views/providers/index.html.erb, app/views/shared/_edit_options_radio_buttons.html.erb, config/locales/en.yml, spec/features/courses/modern_languages/new_spec.rb
- Stop spacing from jumping around in new course journey
- Fix spacing on "Add course" button at the top of the courses list
- Indicate that the equivalency test option is the "most flexible" option
- Don't show an empty grey box on providers list
- Update modern languages page titles to match design ("Pick all the languages for this course" vs "Pick modern languages")
Compare:
https://bat-design-history.netlify.app/images/publish-teacher-training-courses/new-course-wizard-available/pick-the-locations-for-this-course.png
with
https://bat-design-history.netlify.app/images/publish-teacher-training-courses/new-course-wizard-available/when-will-applications-open.png
Some pages don't have legends in the right place, making them inconsistent. For now classes have been used to keep pages …
=> Small spacing and content fixes

app/controllers/concerns/course_basic_detail_concern.rb, app/controllers/courses/accredited_body_controller.rb, app/controllers/courses/applications_open_controller.rb, app/controllers/courses_controller.rb, app/controllers/providers_controller.rb, app/controllers/training_providers_courses_controller.rb, app/views/courses/accredited_body/_provider_suggestion.html.erb, app/views/courses/accredited_body/edit.html.erb, app/views/courses/accredited_body/new.html.erb, app/views/courses/accredited_body/search.html.erb, app/views/courses/accredited_body/search_new.html.erb, spec/features/courses/accredited_body/edit_spec.rb, spec/features/courses/accredited_body/new_spec.rb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/features/providers/training_providers_spec.rb, spec/requests/providers_spec.rb
**NB: This must be deployed with https://github.com/DFE-Digital/teacher-training-api/pull/1407 in an out-of-hours deploy as there may be a few seconds of incompatibility between publish and the api during the deploy.**
This is the correct naming and is necessary for compatibility with
https://github.com/DFE-Digital/teacher-training-api/pull/1407
Rename `accrediting_provider_code` -> `accredited_body_code`
This needs to be tested with https://github.com/DFE-Digital/teacher-training-api/pull/1407
=> [3472] Rename accrediting_provider_code

app/lib/govuk/markdown_renderer.rb, spec/lib/govuk/markdown_renderer_spec.rb
We don't want to allow providers to mark content in italics, bold or bold italic using markdown.
These are currently undocumented markdown features in Publish, but for any providers who know their markdown, they'll find that they currently work.
This will be consistent with how GOV.UK renders content.
Goes with https://github.com/DFE-Digital/find-teacher-training/pull/338
https://trello.com/c/4uABb34i/3519-disable-emphasis-markdown
=> Disable emphasis markdown

Gemfile, Gemfile.lock, azure-pipelines.yml
We need a way to surface code smells and test coverage. Code climate is used in API and Code Climate was configured to analysis this repo but it did not include the test coverage.
- Sets simplecov version to 0.17.x so that code climates test reporter will work
- Add new script to the pipeline to push the test coverage score to code climate (This is only run if all our existing tasks pass.
I checked on Code Climate and can confirm that Code climate is receiving the requests sent to it
=> 3502 Add Code Climate test coverage

app/views/notifications/index.html.erb, app/views/pages/accredited_body_new_features.html.erb
- Updates interruption page copy and spacing
- Updates notification page copy to mirror the interruption
- Add missing page title
Login as an accrediated body user and visit 
https://s121d02-3521-ptt-as.azurewebsites.net/accredited-body-new-features
=> [3521] Update copy and design on interruption page

app/decorators/course_decorator.rb, spec/decorators/course_decorator_spec.rb
financial information for apprenticeships
Fix financial information
Ported from https://github.com/DFE-Digital/find-teacher-training
https://github.com/DFE-Digital/find-teacher-training/pull/59
https://github.com/DFE-Digital/find-teacher-training/pull/321
=> 3507 financial support section displaying incorrect information for provider

app/views/layouts/application.html.erb, app/webpacker/packs/application.js, app/webpacker/scripts/form-error-tracking.js
Removes code which was missed off https://github.com/DFE-Digital/publish-teacher-training/pull/926.
For Publish we do not use GA or GTM at all and do not offer the option to accept GA cookies
- Removes obsolete JS that relied on GA. As we are no longer loading in GA, none of this code would ever be run.
- Remove mentions of GTM.
=> 3535 remove leftover ga code

app/webpacker/packs/application.js
There is already a FormCheckLeave module which replicates the behaviour
which this code was using. I checked where this code might of been triggered
from and spotted that all the instances were being to setup to use the
FormCheckLeave module anyway.
https://github.com/DFE-Digital/publish-teacher-training/blob/1956e57d131c621a97b3b3eeec495b4662726547/app/webpacker/scripts/form-check-leave.js#L9-L27
=> Remove duplicate warning message js

app/controllers/providers/edit_initial_allocations_controller.rb, app/form_objects/change_initial_request_form.rb, app/views/providers/edit_initial_allocations/do_you_want.html.erb, spec/features/providers/allocations/edit_initial_allocation_spec.rb
https://trello.com/c/lO5L7y4F/3509-s-editing-initial-allocation-causes-500-error-if-user-does-not-select-yes-or-no
Add error messaging to editing initial allocations page
=> [3509] Add error message when no option selected

app/controllers/courses/accredited_body_controller.rb, app/controllers/provider_suggestions_controller.rb, app/models/provider_suggestion.rb, app/webpacker/packs/application.js, config/routes.rb, spec/controllers/provider_suggestions_controller_spec.rb, spec/features/courses/accredited_body/edit_spec.rb, spec/features/courses/accredited_body/new_spec.rb, spec/requests/courses_spec.rb
- https://trello.com/c/OO8AqZZe/3500-course-creation-accredited-body-search
- Previously was only searching a very small subset or providers
- Use modified api endpoint to search all accredited bodies for suggestions
- note sure about the code climate failure given that overall test coverage has not dropped
- depends on https://github.com/DFE-Digital/teacher-training-api/pull/1425
- create a new course as user `anonimized-user-8272@example.org`
- on the page to select accredited body perform a search
- should run search and return relevant accredited bodies
- should work for non-js version
=> [3500] Fix accredited body searches

azure/template.json
The publish provider page offers current and next rollover cycles when rollover is set to true in Azure DevOps. The app must be deployed via rollback release pipeline for a rollover cycle to be displayed on the publish provider page. 
https://s121d04-rollover-ptt-as.azurewebsites.net/organisations/2AT
https://dfe-ssp.visualstudio.com/Become-A-Teacher/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=297&path=FIND%20-%20Rollover
https://dfe-ssp.visualstudio.com/Become-A-Teacher/_releaseProgress?_a=release-environment-logs&releaseId=7207&environmentId=36635
=> [3484]- Create-rollover-application-environment

app/views/providers/_show_during_rollover.html.erb, app/views/providers/show.html.erb
We added "Courses as accredited body" and "Requests for PE" feature during the last year. We need to tell users that they can still see this feature for either the current or next cycle.
- Moves rollover content into a new partial
- adds copy relating to being able to view "Courses as accredited body" which is only shown if the provider is an accredited body 
- adds copy relating to being able to view/make request for pe but only for the current cycle
- updates some other copy after a content review.
=> [3544] Add copy to rollover provider show page.

app/decorators/course_decorator.rb, spec/decorators/course_decorator_spec.rb
- https://trello.com/c/NJL3vOKK/3554-when-creating-a-course-in-the-next-recruitment-cycle-add-a-default-start-date
- During rollover course creation default start date is not set
- During rollover on course creation set default start date for the next cycle
- Create a course in the next cycle
- On the course start page
- September of next cycle should be selected as the default
=> [3554] Fix rollover course create start date

app/controllers/providers/allocations_controller.rb, app/controllers/providers_controller.rb, app/flows/initial_request_flow.rb, app/models/provider.rb, app/models/training_provider.rb, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb, spec/features/providers/courses_as_an_accredited_body_spec.rb, spec/features/providers/training_providers_spec.rb
- https://trello.com/c/6S5IQpl1/3563-accredited-bodies-cant-see-the-courses-they-accredit
- When viewing a training provider we are using the Provider#show endpoint which is only accessible to users that are associated with the provider via an organisation
- Switch to use a new endpoint that is accessible to users that are part of an accredited body on the provider
- Previously using Provider#show endpoint which was only accessible if
the user was associated to that provider via an organisation
- Given a training provider TrainingProvider#show endpoint is accessible
to users that are part of any accredited body of the training provider
thru the courses they offer
- This change depends on https://github.com/DFE-Digital/teacher-training-api/pull/1431
- Login as a user of an accredited body …
=> [3563] Use TrainingProvider#show endpoint

app/views/recruitment_cycles/_allocations.html.erb, app/views/recruitment_cycles/show.html.erb, spec/site_prism/page_objects/page/organisations/recruitment_cycle.rb, spec/views/recruitment_cycles/show_spec.rb
#1193 needs to be merged first
- Add "Requests for PE" to the current cycle so accredited body users can see their allocations
- Refactor the section header link to not include `data-qa`
Review last two commits.
=> [3467] Add "Request for PE" section to current cycle page

app/controllers/providers_controller.rb
- https://trello.com/c/o78fXqgF/3553-fix-course-statuses-on-training-provider-course-list-for-accredited-body
- Accredited body viewing training provider courses would pull in courses from the current cycle and not the specified cycle. This is an issue during rollover
- Accredited body viewing a training providers courses during rollover
would use the current cycle and not the cycle from the parameter
- This because this route is not restful and is nested
- As it is nested rails with prefix the param `year`
- So for the non restful route #training_provider_courses we must
consider both cases
- The better fix should be to move training providers to its own
resource and make everything restful
- Login as an accredited body user eg `anonimized-user-8916@example.org`
- View the courses of a …
=> [3553] Fix accredited body viewing courses

Gemfile, Gemfile.lock, app/controllers/courses_controller.rb, app/decorators/provider_decorator.rb, app/helpers/application_helper.rb, app/views/courses/preview/_advice.html.erb, app/views/courses/preview/_apply.html.erb, spec/decorators/provider_decorator_spec.rb, spec/helpers/application_helper_spec.rb
- https://trello.com/c/lD6tJVsR/3576-s-publish-preview-functionality-should-match-find
- There are differences between the Publish preview functionality and how it will actually look on find. This change hopes to remove these differences
- Links are now prefixed with `http` if there is no protocol specified. This is to prevent incorrect relative urls when they should be external links
- Smart quotes used when markdown is processed
- Markdown processor does some additional work to better render lists and bullet points to due incorrect markdown entered by users
-  Copy changes to the preview pages so it matches Find
- When a course is in `rolled_over` state and is being previewed we now show the "Apply section" as part of the preview
- Find a course in rolled over state and preview
- …
=> [3576] Preview tweaks

app/controllers/notifications_controller.rb, spec/controllers/notifications_controller_spec.rb, spec/models/user_spec.rb
- When a user updated their notification preferences after dismissing the notifications interruption screen, a state transition was accidentally being called. 
- When a user updates their notifications preferences we now check if the user is 'allowed' to transition their state to 'notifications_configured'. If true then their state is transitioned and they will no longer see the notifications interruption screen
=> [3336] - Bug fix: state transition error

app/controllers/pages_controller.rb, app/views/pages/notifications_info.html.erb, app/views/pages/rollover.html.erb, app/views/pages/rollover_recruitment.html.erb, config/routes.rb, spec/features/sign_in_spec.rb, spec/site_prism/page_objects/page/notifications_info.rb, spec/site_prism/page_objects/page/rollover.rb, spec/site_prism/page_objects/page/rollover_recruitment.rb
- Content updated for the existing rollover page
- a new recruitment reminder page is added to the flow
- state change should only happen after seeing rollover and recruitment
reminder. (Will be done as a separate PR)
=> [3544] Adds and updates rollover interruption page

app/views/layouts/_header.html.erb
Notification link in the header was being styled as the active link for every page. It should have only been active on the notifications page
=> [3607] Fixes bug with notification active link styling

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/user.rb, app/views/layouts/_footer.html.erb, spec/controllers/application_controller_spec.rb, spec/features/sign_in_spec.rb, spec/views/footer.html.erb_spec.rb
Currently users are unable to accept-terms (unauthorised)
- This commit reverts back to the original behaviour for allowing users to accept terms. This is because the api users update endpoint contains a guard to check if the user has accepted terms.
- Additional fix added - access request count is displayed in footer only if user has accepted terms. I noticed when manually testing the fix for accept terms that if you are an admin user `admin: true` when you reach the accept terms page, the footer makes a direct API call that results in a 403 loop. See https://github.com/DFE-Digital/publish-teacher-training/blob/2fe9b92fbb7ade233ec563280de32fab04edebb2/app/views/layouts/_footer.html.erb#L9
An additional guard has been added to the footer so that it does not blow up if the user is admin …
=> [3602] - Fix accept terms process

app/controllers/sessions_controller.rb, app/models/user.rb, spec/factories/user_factory.rb, spec/features/providers/index_spec.rb, spec/features/sign_in_spec.rb, spec/models/user_spec.rb
- https://trello.com/c/AMMShiva/3543-m-build-final-interruption-screen-for-roll-over
- When the user accepts rollover for 2021 we need to change state to keep track
- This adds a new state so we know user has accepted for the 2021 cycle
- When a user now acknowledges rollover they are set the state of `accepted_rollover_2021`
- depends on https://github.com/DFE-Digital/publish-teacher-training/pull/1221
- this can be easily tested if the following is cherry picked https://github.com/DFE-Digital/publish-teacher-training/pull/1216
- navigate to /auth/developer
- login as different users some examples: admins, new, rolled_over, transitioned, those who have not accepted the terms
- on login should see correct screens
- logout will also work with the cherry picked branch
- login back in as the …
=> [3543] Accept rollover for 2021

app/controllers/organisations_controller.rb, app/views/organisations/index.html.erb, spec/controllers/organisations_controller_spec.rb, spec/features/organisations_spec.rb
The organisations support page loads all organisations and is consequently very slow and ties up the API for too long per request. This adds pagination which is supported in https://github.com/DFE-Digital/teacher-training-api/pull/1453
Add pagination controls to the organisation support page (`/organisation-support-page`)
Requires https://github.com/DFE-Digital/teacher-training-api/pull/1453 so will not currently work in the review app until that is merged.
=> [3575] Add pagination to organisation support page

app/controllers/heartbeat_controller.rb, azure-pipelines.yml, config/routes.rb, config/settings.yml, spec/controllers/heartbeat_controller_spec.rb
- https://trello.com/c/w1Tsuu3M/3578-expose-commit-sha-as-sha
- We want to expose the application sha at /sha for debugging and integration reasons
- Expose the commit sha as part of the azure build at `/sha`
- create a file named `COMMIT_SHA` in the root directory of the rails app
- enter a random string eg `hello-world`
- visit `/sha`
- should see json content `{"sha":"hello-world"}`
=> [3578] Expose app sha at /sha

app/services/performance_dashboard_service.rb, app/views/pages/performance_dashboard.html.erb, app/views/pages/performance_dashboard/_allocation_content.html.erb, app/views/pages/performance_dashboard/_allocations_tab.html.erb, app/views/pages/performance_dashboard/_initial_performance_indicators.html.erb, app/webpacker/stylesheets/_performance-dashboard.scss, spec/fixtures/performance-dashboard.json, spec/services/performance_dashboard_service_spec.rb, spec/site_prism/page_objects/page/performance_dashboard_page.rb, spec/views/pages/performance_dashboard.html.erb_spec.rb
https://trello.com/c/nRP7a83K/3617-add-users-reporting-numbers-into-dashboard
Adding another tab to the dashboard allocations 
* Add allocations tab to the dashboard
* Add allocations data methods to dashboard service
* go to https://s121d02-3617-ptt-as.azurewebsites.net/performance-dashboard
* click on allocations tab
=> [3617] Add allocations reporting numbers

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/controllers/sessions_controller.rb, spec/controllers/pages_controller_spec.rb, spec/features/providers/index_spec.rb, spec/features/sign_in_spec.rb
If users try to visit to an interruption screen that they have previously actioned, and accept the interruption screen again they receive an an error as a result of the recent addition of the state machine to publish. This is most likely because these users have bookmarked the interruption pages.
Before allowing a user to see an interruption screen we first check if their state is valid. If they already have the state transition that results from accepting the interruption screen then they are redirected to the next interruption screen and so on.
Set your user state to 'rolled_over' and try and visit the following interruption screens - `/transition-info`, `/rollover`. Rather than seeing flames you should be redirected.
=> [3589] - Skip signin redirect to interruption pages

app/services/performance_dashboard_service.rb, app/views/pages/performance_dashboard.html.erb, app/views/pages/performance_dashboard/_users_tab.html.erb, spec/fixtures/performance-dashboard.json, spec/services/performance_dashboard_service_spec.rb, spec/site_prism/page_objects/page/performance_dashboard_page.rb, spec/views/pages/performance_dashboard.html.erb_spec.rb
https://trello.com/c/hgfaz71Z/3620-add-users-reporting-numbers-into-dashboard
Adding a users tab to the performance dashboard
Adds a users tab to the dashboard
* visit /performance-dashboard
* select users tab
=> 3620 add users reporting numbers into dashboard

app/controllers/courses/age_range_controller.rb, config/locales/en.yml, spec/features/courses/age_range_in_years/edit_spec.rb
- https://trello.com/c/4OdjeI1q/3615-make-age-range-a-required-field-for-courses-in-2020-cycle
- We want to improve data collected for courses
- Therefore age range is now mandatory when updating the age range
- This is done with client side validation
- Cannot be easily done as an API side validation with the current
setup. Otherwise when updating another field this validation would be
triggered
- The codeclimate issue seems fine unless you can offer a better solution
- Find a course that has `age_range_in_years` set to `nil`
- Navigate to the edit the age range page for the course
- Attempt to save without entering an age range
- Should see validation message
=> [3615] Age range now mandatory when updating

app/controllers/sessions_controller.rb, config/settings.yml, spec/controllers/sessions_controller_spec.rb
We want to be able to disable signin by DfE signin if there is a problem with the service.
Adds a feature flag to disable signin via DfE signin.
When the feature is disabled an attempt to login via DfE signin renders the magic link signin page (`sessions#new`) or redirects to it if the user has actually come from signin already.
=> [3594] Add setting to disable DfE Signin

app/decorators/course_decorator.rb, app/views/courses/_course_length.html.erb, spec/decorators/course_decorator_spec.rb
- https://trello.com/c/lMuMuYoE/3623-m-when-creating-a-course-and-completing-course-fees-section-we-should-not-set-a-default-for-the-course-length
- A default course length is being set for the user which means less that accurate is being collected about the course
- On first setting of course length we no longer set the default value
to other
- Instead the user can choose what value to select from the choice of
radios
- Before publication the user is forced to enter a value so the user
must enter the data
- This aims to collect more accurate data about the course
- https://s121d02-3623-ptt-as.azurewebsites.net/
- Create a course
- View/Edit the course in publish
- Under the `Description` tab, click `Course length and fees`
- Hit `Save` button
- Navigate back to this page
- The course …
=> [3623] No default course length

app/controllers/providers_controller.rb, app/views/providers/contact.html.erb, spec/views/providers/contact.html.erb_spec.rb
- https://trello.com/c/KXiJdzYT/3573-m-make-provider-name-editable
- Admin users of publish want to be able to update provider names for convenience
- In the contact details page admins can see the `provider_name` field
- Non-admins cannot see this field
- The API determines if the user is allowed update this field or not
- https://s121d02-3573-ptt-as.azurewebsites.net/
- This change depends on https://github.com/DFE-Digital/teacher-training-api/pull/1461
- Login in a non-admin
- Navigate to contact page of a provider
- Should not see admin panel with `provider_name` field
- Logout
- Login as admin
- Navigate to contact page of a provider
- Should see an admin panel with the `provider_name` field
- Change the `provider_name` to something else
- Submit form
- Navigate to provider
- …
=> [3573] Admins panel to update provider name

app/controllers/courses/vacancies_controller.rb, app/models/course.rb, spec/features/courses/vacancies/edit_spec.rb
Co-authored-by: Toby Retallick <toby.retallick@gmail.com>
https://trello.com/c/5q8MIq3C/3629-duplicate-notification-emails-sent-out-to-accredited-provider
User got sent 10 emails! This PR is the publish side of things, and introduces a change where an API call is made to send a notification once a course has no vacancies left. https://github.com/DFE-Digital/teacher-training-api/pull/1465
* Add API call to send notification after a course has no remaining vacancies
=> 3629 Add notification call for no vacancies

end-to-end-tests/cypress/integration/organisations.js
The login spec in the Publish E2E is broken for reasons unknown. 
Rather than potentially have @defong spend hours trying to fix we will skip the login spec and make plans to port the E2E test suite to Ruby.
=> [3649] - Skip login E2E spec

app/controllers/courses/title_controller.rb, app/models/base.rb, app/models/course.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/title/edit.html.erb, config/routes.rb, spec/controllers/courses/title_controller_spec.rb, spec/factories/courses.rb, spec/features/courses/age_range_in_years/new_spec.rb, spec/features/courses/confirmation_spec.rb, spec/features/courses/entry_requirements/new_spec.rb, spec/features/courses/new_spec.rb, spec/features/courses/outcome/edit_spec.rb, spec/site_prism/page_objects/page/organisations/course_details.rb, spec/views/courses/_basic_details_tab.html.erb_spec.rb
- https://trello.com/c/bKhHARtf/3572-m-make-course-title-editable
- This allows admins to modify course names via publish
- Add a new controller and views only accessible to admins that allows the changing of course titles
- Added `Change` link from the course that is only visible to admins to be able navigate to the new controller and view
- Fix `Course` factory where `level` was return a symbol whereas the API actually returns a string
- CSS changes have not been applied and can be done later in another PR
- Depends on https://github.com/DFE-Digital/teacher-training-api/pull/1463
- https://s121d02-3572-ptt-as.azurewebsites.net
- Login as admin
- Find a course
- Should see change link for course title
- Click on link
- Should be taken to new page to change course title
- Change to the …
=> [3572] Course titles can be modified by admins

app/controllers/users_controller.rb, spec/controllers/users_controller_spec.rb, spec/features/sign_in_spec.rb
- https://trello.com/c/sDVFcGD0/3660-update-session-when-user-accepts-terms
- After the user accepts term we keep the session in sync with this new data
- This is to make https://trello.com/c/IQbTVjZV/3638-m-all-interruptions-are-not-being-displayed-when-the-user-next-signs-in easier
- As we will now have a source of truth on whether or not the user has accepted terms or not
- After the user accepts term we keep the session in sync with this new data
- This way we know when to display the terms page or not
- API also performs this check
- But now publish knows when to display the terms page
- Out of scope: there seem to other bits of hairy code working around the terms. We can change those to use this mechanism once merged 
- Depends on …
=> [3660] After accepting terms sync session data

app/controllers/courses/subjects_controller.rb, spec/features/courses/subjects/new_spec.rb
When a user tries to create a course, no matter the cycle, if they don't select a subject before submitting, they get a 500 error instead of a useful validation.
1. Go to the course table in either current or next cycle.
2. Click "Add a new course"
3. On the "What type of course?" page: Select either "Primary" or "Secondary", then "Continue"
4. On the "Pick a primary/secondary subject" page: Click "Continue" without selecting a subject
5. Admire the 500 error
User should see a validation error inviting them to choose a subject.
https://trello.com/c/7mVvxhKj/3641-500-error-when-no-subjects-selected-on-course-creation
fixed subjects 500 error and added feature test
=> fixed subjects 500 error and added feature test

config/settings.yml, config/settings/development.yml, config/settings/production.yml, config/settings/qa.yml, config/settings/research.yml, config/settings/rollover.yml, config/settings/staging.yml, config/settings/test.yml, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb
We told accredited bodies that "you have from Monday 1 June until midday on Friday 10 July to request any fee-funded PE, early years initial teacher training (EYITT) and undergraduate courses for 2021/22".
Changed allocation state settings to closed
Merge after merging a previous PR #1245 ?
=> [3655] Close allocations

app/helpers/breadcrumb_helper.rb, app/helpers/view_helper.rb, app/models/recruitment_cycle.rb, app/views/pages/performance_dashboard/_allocations_tab.html.erb, app/views/pages/rollover.html.erb, app/views/providers/_show_during_rollover.html.erb, app/views/providers/allocations/_allocation-request-closed-state.html.erb, app/views/providers/allocations/_allocation-request-open-state.html.erb, app/views/providers/allocations/requests/_not_requested.html.erb, app/views/providers/allocations/requests/_yes_requested.html.erb, app/views/recruitment_cycles/_allocations.html.erb, spec/features/courses/preview_spec.rb, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb, spec/models/recruitment_cycle_spec.rb
We need to change hyphens to 'to' because it's:
- better/easier for screenreaders to read out "to" than 'dashes'
- recommended in the GDS Style guide https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates
- To be consistent with Apply
- Replacing all `&thinsp;–&thinsp;` with ` to ` for year periods
- Replacing all `2020&thinsp;–&thinsp;2021` with  `2020 to 2021`
=> [3666] Changing ' - '  to 'to' in line with GDS guidance

app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, spec/requests/sessions_spec.rb
When a user signs in via magic link and then attempts to sign out they receive an error. 
```
Error
invalid_request
unrecognized route or not allowed method (GET on /)
```
This is because the app is attempting to sign out of DFE signin.
- Enable sign out if a user has signed in via 'magic link'.
- Sign in via magic link. To this add the following to your `development.local.yml`
```
features:
signin_intercept: true
signin_by_email: true
dfe_signin: false
```
- Click 'sign out' in the header. You should be redirected to `/signin`.
=> [3662] - Allow users to sign out when 'magic link' enabled

app/controllers/users_controller.rb, app/decorators/course_decorator.rb, app/models/provider.rb, app/models/recruitment_cycle.rb, app/models/user.rb, app/services/feature_service.rb, config/settings.yml, config/settings/test.yml, spec/decorators/course_decorator_spec.rb, spec/features/providers/about_spec.rb, spec/features/providers/contact_spec.rb, spec/features/providers/details_spec.rb, spec/features/providers/index_spec.rb, spec/features/providers/search_spec.rb, spec/features/sign_in_spec.rb, spec/features/sites/index_spec.rb, spec/models/recruitment_cycle_spec.rb, spec/models/user_spec.rb, spec/requests/recruitment_cycles_spec.rb, spec/services/feature_service_spec.rb
- Added support for nested features in Settings (Thank you @misaka)
- Renames `Settings.rollover` to `Settings.features.rollover.can_edit_current_and_next_cycles`
- Renames `Settings.current_cycle_open` to Settings.features.rollover.has_current_cycle_started?`
- Make `Settings.features.rollover.can_edit_current_and_next_cycles` default across all environments during rollover period 
- Easier to review commit by commit
- Review apps should now be operating in "Rollover" mode. 
- If you login as a single organisation user, you should see a page asking if you want to view/edit current/next cycle`
- If you login as a mult-organisation user, you should see a list of the organisations and if you click on one organisation, you should see a page asking if you want to view/edit current/next cycle`
=> [3668] Refactor rollover settings and ensure review apps are inline with production user journeys

app/controllers/courses_controller.rb, app/decorators/course_decorator.rb, app/views/courses/_description_content.html.erb, app/views/courses/about.html.erb, app/views/courses/preview.html.erb, app/views/courses/preview/_about_schools.html.erb, spec/decorators/course_decorator_spec.rb, spec/features/courses/about_spec.rb, spec/features/courses/preview_spec.rb, spec/requests/courses/about_spec.rb
Further Education courses in Publish contain the following header and links:
'How school placements work'
Change to 'How teaching placements work' for Further Education courses only
- [] Product Review
=> [3654] Changed 'school' to 'teaching' placements

app/controllers/providers_controller.rb, app/decorators/provider_decorator.rb, app/views/providers/about.html.erb, spec/features/providers/about_spec.rb, spec/site_prism/page_objects/page/organisations/organisation_about.rb
- Updates the form on the page to use GOV.UK Design System formbuilder
- Fixes issue where accredited body optional fields were displaying as errors if there were any validation errors for "training with us" and last text area "disabilities".
- removes old copy telling users it would take up to 2hrs for content to be updated on Find.
=> [3686] Fix character count on Organisation "About" page

app/views/courses/about.html.erb, spec/site_prism/page_objects/page/organisations/course_about.rb
- Switches the page to use GOV.UK Design System form builder
- Fixes styling issues where is any field had a validation error then all the fields were styled as having errors.
- Clicking on the Error summary should now take the user directly to the text area and set focus to it.
- Login as a user and try the following
- visit any courses "About page" and see how many words they have left for each textarea on the page
- edit each text area and notice how the word counter below that text area updates as you add/remove words
- Attempt to add more words than each text area allows. 
- clicking on the link in the error summary should take you directly to that field and it should have focus (yellow border)
=> [3699] Fix character counter on "About course" page

app/controllers/courses_controller.rb, app/helpers/application_helper.rb, app/helpers/view_helper.rb, app/views/courses/_description_content.html.erb, spec/features/courses/show_spec.rb, spec/requests/courses_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
- https://trello.com/c/97e3BxBu/3653-missing-broken-error-summaries-when-trying-to-publish-a-course-in-rollover
- If adding large validation error messages publish would store these in the flash and therefore cookies have a chance of causing a cookie overflow
- Previously on course publication any errors were stored in the flash
and shown on the next request after a redirect
- However we are using cookie based session store which has a limited
storage of 4kb
- Large error messages stored this way would cause the cookie to
overflow causing an error
- Instead we now render the same page on the request if validation fails
- This prevents the need to store data in the cookie
- `build_course` must be called again in controller as `JsonApiClient`
when calling `publish` removes associations …
=> [3653] On course publication render errors

app/controllers/courses/age_range_controller.rb, app/form_objects/age_range_form.rb, app/helpers/view_helper.rb, app/views/courses/age_range/edit.html.erb, config/locales/en.yml, spec/features/courses/age_range_in_years/edit_spec.rb, spec/form_objects/age_range_form_spec.rb, spec/site_prism/page_objects/page/organisations/course_age_range.rb
- https://trello.com/c/xsGZiaX2/3644-age-range-validation-message-link
- On attempt to publish with missing age range the error summary link would not navigate to the age range page so the user could fix the issue
- On attempting to publish if age range is missing the validation summary link now goes to the age range page
- From this link on page load of the age range page errors are displayed to the user
- The age range page now uses a form object
- Validations have been moved from the controller to the form object
- The age range page now uses the gov uk formbuilder
- Browser side validations have been ported to publish side validations
- Site prism page objects no longer use data-qa references and now use ids
- Some validation messages have been improved but can still do with …
=> [3644] age range validation

app/controllers/courses/accredited_body_controller.rb, spec/features/courses/accredited_body/edit_spec.rb, spec/features/courses/accredited_body/new_spec.rb
https://trello.com/c/7MOribyu/3643-create-a-course-error-when-leaving-accredited-body-field-empty
To fix this issue we initially looked at the API to see what errors were being thrown. It turns out that for this particular endpoint, there aren't errors when a bad query is sent, and only a `bad request` status is thrown back, with no other information. This meant that Publish would send a bad query, and be unable to understand why it was bad - and so didn't load the error partial properly. 
We've got a couple of options here 
1. We can add validation to Publish that will prevent users from submitting searches that wouldn't meet the API's specifications. This prevents bad requests being sent to the API.
2. We can add proper error messaging to the API, which would allow us to send bad …
=> 3643 provider suggestion error

app/views/courses/requirements.html.erb, spec/site_prism/page_objects/page/organisations/course_requirements.rb
- Switches the page to use GOV.UK Design System form builder
- Fixes styling issues where is any field had a validation error then all the fields were styled as having errors.
- Clicking on the Error summary should now take the user directly to the text area and set focus to it.
- go to https://s121d02-3714-ptt-as.azurewebsites.net/
- Login as a user and edit a course
- check the requirements page has word count
- try input more words than allowed 
- click on the link in the error at the top of the page. It should take to the form field that is invalid
=> [3714] Switch form to use GOV.UK Design System formbuilder

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
Currently the log safe current user was logging way to much details
Amended log safe current user to be lean
``` ruby
{
"email_md5"=>"email_md5", 
"sign_in_user_id"=>"sign_in_user_id", 
"user_id"=>"user_id"
}
```
Configure from config/settings.yml or config/settings/development.local.yml
```yml
logstash:
type: tcp
host: # Our hostname here
port: # Our port here
ssl_enable: true
```
Logs will be much more compact see [kibana example](https://kibana.logit.io/app/kibana#/doc/8ac115c0-aac1-11e8-88ea-0383c11b333a/logstash-2020.07.24?id=xrzQgHMB9CPnJIZAXLuS&_g=(refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now)))
=> [3642] Amended log safe current user to be lean

app/webpacker/scripts/autocomplete.js
This fixes a bug with the autocomplete. As soon as the users tabbed
out of the autocomplete or clicked on the submit button or anything which
meant the autocomplete lost focus, the `onConfirm` method would run.  When
it is evaluated a second time the "option" variable is null so the hidden
text field has its value set to an empty string.
This doesn't address our tech debt as to why this autocomplete is different
from all the others the application has. I did do an investigation and it
would seem as though we added this hidden field so that we didn't have to
do another provider lookup from the backend. I'd say from a data integrity and
security POV we should do a lookup from the backend and not rely on the frontend
alone. A user could edit the value or submit some xss.
- Login as admin …
=> [3707] Fix autocomplete clearing hidden input value

app/views/courses/show.html.erb, app/webpacker/stylesheets/_notice-summary.scss, app/webpacker/stylesheets/application.scss, spec/features/courses/show_spec.rb, spec/site_prism/page_objects/page/organisations/course.rb
This banner will be used to help notify users in the service when they
are missing data and need to correct it before the can publish courses
=> [3703] Add notice summary banner to course show page

app/controllers/notifications_controller.rb, app/views/notifications/index.html.erb, app/views/pages/rollover.html.erb, app/views/pages/rollover_recruitment.html.erb, spec/features/notifications_spec.rb, spec/features/sign_in_spec.rb
Copy updated to _notification preferences page_ and _notifications preferences saved success_ message.
=> [3732] - update user notification opt in content

app/views/courses/about.html.erb
- https://trello.com/c/fWHZmhOc/3760-copy-course-content-bug
- Fixes a regression that broke copy course content
- Previously there were 2 independent forms on the course about page
- A regression in the HTML markup caused these 2 forms to be nested and therefore invalid
- This change splits the forms so they are no longer nested
- A third non-submitable form has been added so if there are errors these can be rendered back to the user
- Login as admin or user with 2 courses
- Edit the course through the about page
- On the RHS use the copy content from another course feature
- Other course content should now be present on this course
=> [3760] Fix copy course content

.rubocop.yml, README.md, app/controllers/application_controller.rb, app/controllers/personas_controller.rb, app/controllers/sessions_controller.rb, app/views/personas/index.html.erb, config/initializers/omniauth.rb, config/routes.rb, config/settings.yml, config/settings/development.yml, config/settings/qa.yml, config/settings/research.yml, config/settings/rollover.yml, config/settings/staging.yml, spec/controllers/application_controller_spec.rb, spec/controllers/sessions_controller_spec.rb, spec/requests/authorisation_spec.rb, spec/support/helpers.rb
- https://trello.com/c/xA11zDVq/3685-m-persona-login
- Testing in review apps and other non-production environments was very difficult as only several user accounts were accessible
- Remove previous basic auth mechanism which would take these details to a mapped list of allowed users
- Basic auth is now hard coded to simply prevent unknown user access
- Basic auth is now feature flagged and can be enabled/disabled via settings yaml
- Added OmniAuth developer auth strategy which is controlled via settings yaml
- Added persona login page (see screenshot below) which represent some pre-selected users from anonymised dataset
- These pre-selected users simply user the developer auth behind the scenes
- There is a link from persona page to developer auth so you can login as any user as long as …
=> [3685] Persona login and dev auth

app/controllers/courses/vacancies_controller.rb, app/models/base.rb, app/models/course.rb, spec/features/courses/vacancies/edit_spec.rb
Currently, subscribed users are only being notified if a course has no vacancies (all locations).
See associated API PR - https://github.com/DFE-Digital/teacher-training-api/pull/1483. This also has notification examples.
- When a user updates course locations to from closed to open we want to trigger the vacancies updated notification. Specifically, the notification is triggered when a course has a single location and it is updated from closed to open, or when the course has multiple locations and all locations are changed to open.
- To run locally you will need to run this branch against  https://github.com/DFE-Digital/teacher-training-api/pull/1483 and have a Notify test key configured
=> [3678] - Course vacancies open (all locations)

app/views/courses/confirmation.html.erb, spec/features/courses/confirmation_spec.rb
* https://trello.com/c/H1d6Sd7Q/3733-age-range-should-not-be-displayed-in-the-check-your-answers-page-for-further-education-courses
When adding a new course accredited bodies/training providers do not need to specify an age range for Further Education courses. Therefore, on the 'Check your answers before confirming page', they do not need to see an empty age range field. 
Removes the age range field on 'Check your answers before confirming page' for FE course but keeps it for Primary and Secondary courses. 
Add a new course for FE and Primary/Secondary to see change in age range display on confirmation page
https://s121d02-3733-ptt-as.azurewebsites.net/
=> [3733] Age range display logic for FE courses

app/views/courses/_basic_details_tab.html.erb, app/views/courses/confirmation.html.erb, spec/features/courses/confirmation_spec.rb
* https://trello.com/c/xLKzxrwb/3734-s-training-providers-cannot-create-further-education-courses
* Non-accredited providers could not reach confirmation page when adding FE courses
Logic to allow non-accredited providers to reach confirmation page
Subject field removed from confirmation page and basic details tab as there is nothing else to change the subject to and does not appear in course creation wizard
https://s121d02-3734-ptt-as.azurewebsites.net/
=> [3734] Training providers cannot create further education courses

.azure_parallel, .rspec_parallel, azure-pipelines.yml
Our currently implementation seems not to be working anyway. To simplify
our process we are now using `.rspec_parallel` as a single config file
Azure should be able to use this output to report test coverage in azure.
- Tested locally running `bundle exec rake parallel:spec` and inspected the logged out xm files found in `rspec-output`.
- view "Tests" tab for the azure job once it has been completed
=> Fixes issue with rspec parallel xml outputs.

app/views/courses/requirements.html.erb
- https://trello.com/c/aRTa0DRx/3779-copy-course-content-bug
- Fixes a regression that broke copy course content
Based on the fix we applied here https://github.com/DFE-Digital/publish-teacher-training/pull/1283
- Previously there were 2 independent forms on the course requirements page
- A regression in the HTML markup caused these 2 forms to be nested and therefore invalid
- This change splits the forms so they are no longer nested
- A third non-submitable form has been added so if there are errors these can be rendered back to the user
- Login as admin or user with 2 courses
- Edit the course through the requirements page
- On the RHS use the copy content from another course feature
- Other course content should now be present on this course
=> [3779] Fix copy course content

app/models/allocation.rb, app/view_objects/allocations_view.rb, app/views/providers/allocations/_allocation-request-confirmed-state.html.erb, app/views/providers/allocations/_allocation_report_confirmed_state.html.erb, config/settings.yml, config/settings/development.yml, config/settings/qa.yml, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb, spec/models/allocation_spec.rb, spec/view_objects/allocations_view_spec.rb
Moved Settings.allocations_state into the features namespace. Also added
comments around the different valid options.
We decided to keep `state` key as it could potentially be used by other
methods / backend business logic
https://trello.com/c/mAtodzq4/3756-s-implement-allocations-results-screen
* Added allocations confirmed page templates
* Add view object method for returning only confirmed allocations
* Added tests for confirmed allocations view
* Changed allocation config settings naming
* Changed QA allocations feature state to confirmed for product review
- visit https://s121d02-3756-ptt-as.azurewebsites.net/ 
- login as a user of an accredited body
- view allocation page
=> [3756] Add "confirmed" state views for Allocations

app/models/allocation.rb, app/view_objects/allocations_view.rb, app/views/providers/allocations/_allocation_report_confirmed_state.html.erb, config/settings.yml, config/settings/development.yml, spec/view_objects/allocations_view_spec.rb
- https://trello.com/c/sAOGBGQF/3818-backend-allocation-for-final-numbers
- For confirmed allocation numbers we must use the correct data from the API
- Frontend changes to use confirmed allocation numbers from API
- API changes must be rolled out first before this change is released
- Depends on https://github.com/DFE-Digital/teacher-training-api/pull/1537
- Test in unison with https://github.com/DFE-Digital/teacher-training-api/pull/1537
- Find a provider with allocations eg B20
- Modify one of their allocations in the rails console and set confirmed_number_of_places to 123
- View the allocation via publisher web interface. Should see 123
- The other unset allocation should be blank i.e. the app does not throw an error
=> [3818] Use confirmed allocation numbers from API

end-to-end-tests/README.md, end-to-end-tests/cypress/integration/_publicly_visible/index.js, end-to-end-tests/cypress/integration/organisations.js
- https://trello.com/b/fXA6ioZN/find-publish-sprint-board
- Fix cypress test in QA and staging
- This was due to change in basic auth details due to persona login change
- Add basic README to give at least some hints on how to use the cypress tests
- Tweak cypress tests to be compatible with persona logins
- Speed up tests, now takes 100ms to scroll to the bottom of each page instead of 2 seconds
- See evidence of it passing https://dfe-ssp.visualstudio.com/Become-A-Teacher/_releaseProgress?_a=release-environment-logs&releaseId=8033&environmentId=46012
=> [3771] fix cypress tests due to persona login changes

end-to-end-tests/cypress/integration/organisations.js
- https://trello.com/c/cc7ehRNL/55-fix-cypress-tests
- Cypress tests for staging are currently broken when testing a user login
- For some reason the original user did not get rolled over correctly
- Therefore they no longer belong to an organisation
- As a workaround we login into another valid anonymised user
- Update `end-to-end-tests/cypress.json` with `baseUrl` to `https://www.staging.publish-teacher-training-courses.service.gov.uk/`
- run `npx cypress run --env password=SEE_CONFLUENCE_PAGE`
- all tests should pass
=> [55] Update cypress tests

terraform/backend.tf, terraform/provider.tf, terraform/resources.tf, terraform/terraform_prod.tfvars, terraform/terraform_qa.tfvars, terraform/terraform_staging.tfvars, terraform/variables.tf
Configured statuscake's Terraform pipeline to monitor Publish-teacher-training's website using Ping. 'healthcheck is not working at the moment' 
We have the status cakes. We have the /healthchecks. But /healthcheck on the API is returning false (Redis queues?).
API
* Figure out what is causing it to return false, fix it.
Publish
* Do we want to be using /ping or /healthcheck on API to determine our status? Sounds to me like it should be /ping, so this would need changing.
Terraform:- configured statuscake's monitor url for each environment to */ping
=> 59 healthcheck statuscake

config/settings/staging.yml
- https://trello.com/c/ZdQi6F25/48-import-final-allocation-numbers
- Allocations confirmed places has been imported into staging
- So testing of allocations in confirmed state can take place we need to enable the feature flag in staging
- Set staging allocations state to confirmed
- Code review only otherwise only testable once deployed to staging
=> [48] Set staging allocations to confirmed

app/decorators/course_decorator.rb, app/views/courses/applications_open/_form_fields.html.erb
* https://trello.com/c/d79wSVBk/32-check-that-the-when-will-applications-open-error-message-displays-the-correct-dates
* https://github.com/DFE-Digital/teacher-training-api/pull/1557
The 'for example' phrase was an invalid date. It needed to be between 13/10/2020 and 3/10/2021.
For example phrase was changed to 30/9/2021 (just an arbitrary date) that is valid because it's within the date range for the 2020 to 2021 recuitment cycle. Also, a simple copy change to change the '-' to a 'to' in line with the rest of Publish for '2020 - 2021'. 
When adding a new course you see the change when the partial is rendered for the 'when will the applications open' page
=> [32] Changes 'for example' phrase to a valid date

.github/workflows/deploy-paas.yml, terraform/paas/backend.tf
GitHub action is failing because of Cloudfoundry
updated the github location used for downloading
Cloundfoundry plugins
Check url
- [] Make sure all information from the Trello card is in here
- [] Attach to Trello card
=> update cloundfdry download location

app/views/recruitment_cycles/_allocations.html.erb, config/locales/en.yml, spec/views/providers/show_spec.rb, spec/views/recruitment_cycles/show_spec.rb
We need to change the link and section copy for allocations depending
on the state of allocations.
- Uses the allocation journey mode and i18n to switch out the different link text and copy.
=> [33] Update allocation copy on the providers page

app/helpers/provider_helper.rb, app/views/courses/subjects/new.erb, config/settings.yml, spec/helpers/provider_helper_spec.rb
- https://trello.com/c/M92Y7EQ3/34-s-update-the-next-cycle-google-forms-with-the-new-ones
- Remove `is_current_cycle` which seemed to hard code the current cycle forcing the link to always render the google form for the current cycle
- Check the provider's currently selected recruitment cycle and render correct google form
- Fire up localhost
- Visit `http://localhost:3000/organisations/T92/2020/courses/subjects/new?course%5Bis_send%5D=0&course%5Blevel%5D=secondary`. Click the Google form URL, should show current google form for current cycle
- Visit `http://localhost:3000/organisations/T92/2021/courses/subjects/new?course%5Bis_send%5D=0&course%5Blevel%5D=secondary`. Click the Google form URL, should show google form for next cycle
=> [34] Refactor google form url helper code to factor in next cycle

app/decorators/course_decorator.rb, app/views/courses/preview/_financial_support.html.erb, app/views/courses/preview/financial_support/_placeholder.html.erb, config/settings.yml, spec/decorators/course_decorator_spec.rb, spec/views/preview.html.erb_spec.rb
During the transition from old cycle to new cycle to current cycle, the financial incentives have not been confirmed.
Added a settings in config to determine the cycle in question should have a placeholder to state along the lines of tba.
=> [0096] Added the financial placeholder

app/services/performance_dashboard_service.rb, app/views/pages/performance_dashboard.html.erb, app/views/pages/performance_dashboard/_rollover_tab.html.erb, spec/fixtures/performance-dashboard.json, spec/services/performance_dashboard_service_spec.rb, spec/site_prism/page_objects/page/performance_dashboard_page.rb, spec/views/pages/performance_dashboard.html.erb_spec.rb
* https://trello.com/c/Fvyd6hPr/120-service-status-dashboard-rollover-tab
* https://trello.com/c/3C81CAYu/130-s-service-status-dashboard-rollover-data
This is the frontend PR/ticket for the new Rollover tab feature on the Performance Dashboard. 
Using the new rollover data at the /reporting endpoint
Only when rollover settings are set to true then tab will show
For comparison with the prototype:
* https://publish-dashboard-prototype.herokuapp.com/with-tables#rollover
=> 120 service status dashboard rollover tab

app/views/pages/rollover.html.erb, config/settings.yml, spec/features/sign_in_spec.rb, spec/site_prism/page_objects/page/rollover.rb
The rollover recruitment page needs to be feature flagged.
The rollover recruitment page be toggled.
https://s121d02-01-ptt-as.azurewebsites.net/
This affects the interruption page workflow
The rollover recruitment page contains dates that makes it no longer appropriate to be shown
:shipit: 
Affects new users or non-rollovered users
=> [0195] Added a feature flag for a rollover recruitment page

app/views/courses/preview/financial_support/_placeholder.html.erb, spec/features/courses/preview_spec.rb
Financial incentives/support placeholder changed
Copy changes
=> [0212] Amended place holder changes

app/controllers/contacts_controller.rb, app/controllers/ucas_contacts_controller.rb, app/models/contact.rb, app/models/provider.rb, app/view_objects/ucas_contact_view.rb, app/views/contacts/edit.html.erb, app/views/ucas_contacts/_contact.html.erb, app/views/ucas_contacts/_ucas_contact_list.html.erb, app/views/ucas_contacts/show.html.erb, config/locales/en.yml, config/routes.rb, spec/factories/contacts.rb, spec/factories/providers.rb, spec/features/providers/ucas_alerts_spec.rb, spec/features/providers/ucas_contacts_spec.rb, spec/features/providers/update_ucas_contact_spec.rb, spec/models/contact_spec.rb, spec/site_prism/page_objects/page/organisations/ucas_contacts.rb, spec/site_prism/page_objects/page/organisations/ucas_contacts_edit.rb, spec/support/define_factory_jsonapi_render_methods.rb, spec/support/resource_list_to_jsonapi.rb, spec/support/serializers/contact_serializer.rb, spec/support/serializers/provider_serializer.rb, spec/view_objects/ucas_contact_view_spec.rb, spec/views/contacts/_ucas_contact_list_spec.rb, spec/views/contacts/edit.html.erb_spec.rb
Users can't currently edit their UCAS contact details. Now they can 🥳 
* Treat `Contact` as 'a thing' rather than an element on `Provider`
* Add update contact feature
* View an organisation that has UCAS contacts. 1XO is our favourite
* Click the edit link on one of the contacts
* Make a change
* Submit the form
* Rejoice
* The form should require all fields
* The form should require that permission is given with the checkbox
* The UCAS administrator form has extra copy and the submit button value is 'Request changes' rather than 'Save'
=> [125] Make UCAS contacts updatable

config/initializers/semantic_logger.rb
Turns out this approach was not compatible with the standard way of logging and
can result in breaking the indexing for the 'duration' field, breaking
aggregation and other operations reliant on the 'duration' field. The correct
approach is to leave 'duration_ms', fix any discrepencies in the logit filters
to ensure that it's indexed as a number, and then use 'duration_ms' for
aggregation.
=> [342] revert duration/duration_ms formatting for logstash

azure/template.json
see https://azure.github.io/AppService/2020/10/15/Docker-Hub-authenticated-pulls-on-App-Service.html
configure App Service to authenticate with dockerhub using provided credentials 
Set in Azure Release pipelines. (done for QA)
```
-dockerRegistryUsername $(dockerRegistryUsername) -dockerRegistryPassword $(dockerRegistryPassword)
```
Update staging & production once/just before this is merged.
Changes have been tested in Find and Apply QA.
https://trello.com/c/qG7Lio3h/365-pipeline-and-arm-template-changes-to-include-dockerhub-credentials-to-overcome-rate-limit
=> Authenticate with DockerHub before pulling image

Gemfile, Gemfile.lock, config/routes.rb, spec/config/settings_spec.rb
We shouldn't need to hardcode the current/next recruitment cycle year.
=> [379] Use Settings recruitment cycle in the routes

.github/workflows/deploy-paas.yml, terraform/paas/resources.tf, terraform/paas/variables.tf
Authenticate with DockerHub to have increased rate limit.
See #1413 
Authenticate with DockerHub before pulling image in PaaS.
=> Authenticate with DockerHub (PaaS)

app/controllers/application_controller.rb, app/models/session.rb, app/services/jwt/encode_service.rb, app/services/magic_link/generate_and_send_service.rb, config/settings.yml, spec/config/settings_spec.rb, spec/controllers/application_controller_spec.rb, spec/models/session_spec.rb, spec/requests/authorisation_spec.rb, spec/services/jwt/encode_service_spec.rb, spec/services/magic_link/generate_and_send_service_spec.rb
JWT long shelf life
JWT tokens generated now has enough items of interest to enforce lifecycle termination due to
- expiration time
- mismatch
- audience
- issuer
- subject
This is the server side of the service, and produces the JWT.
Should be reviewed alongside
https://github.com/DFE-Digital/teacher-training-api/pull/1644
=> [378] JWT long shelf life (serverside)

app/services/jwt/encode_service.rb, spec/services/jwt/encode_service_spec.rb
6 hours not 5 minutes
6 hours not 5 minutes
JWT should be inline with cookie, cookie expires, JWT is refreshed.
https://github.com/DFE-Digital/publish-teacher-training/blob/d2be25159c30d443db83b4a9ea61e28953955647/config/application.rb#L37
=> [378] Amended 6 hours not 5 minutes

.github/workflows/build.yml, Dockerfile, app/controllers/heartbeat_controller.rb, azure-pipelines.yml, config/settings.yml, spec/controllers/heartbeat_controller_spec.rb
Set `COMMIT_SHA` as docker build argument
Stop writing to and reading COMMIT_SHA to a file.
Set COMMIT_SHA as build arg to docker build
`COMMIT_SHA` is prefixed with paas- in the app hosted in PaaS for identification while we are running on two platforms.
=> Read COMMIT_SHA from ENV hash

config/settings/staging.yml
Disable basic_auth in ./config/settings/staging.yml. This would allow DfE sign In
Set basic_auth: to  false
=> disable-basic_auth_in_staging

azure/template.json
Reverts #1498
This is causing slow response times, so revering this until further investigation.
#1498 is causing slow response times (as seen under Response time metrics )in Azure Portal.
=> Revert healthCheckPath

app/helpers/application_helper.rb, spec/helpers/application_helper_spec.rb
London Metropolitan University has included a url containing three consecutive dashes ( --- ) inside its 'about course' description. When the url is displayed on Find, RubyPants is converting the three consecutive dashes to an em dash, breaking the link.
[Monster Slack thread](https://ukgovernmentdfe.slack.com/archives/CN1MCQCHZ/p1610725336016200)
The RubyPants config has been updated to ignore three consecutive dashes and therefore not convert to an em dash
https://trello.com/c/mbieHoJC/127-find-url-error
=> Update Ruby Pants configuration (dashes)

Dockerfile
alpine has released version 3.13 with an updated version of node which might cause version conflicts.
use ruby:2.7.2-alpine3.12
=> Update base docker image to ruby:2.7.2-alpine3.12

terraform/modules/paas/data.tf
As part of the consolidation on other dfe services into PaaS,
there is the need rename the PaaS org name from "dfe-teacher-services" to "dfe"
As part of the consolidation on other dfe services into PaaS,
there is the need rename the PaaS org name from "dfe-teacher-services" to "dfe"
data cloudfoundry_org org {
name = "dfe"
}
=> Update PaaS org name to dfe

terraform/terraform.tf, terraform/variables.tf
Until change, it was difficult to run terrafrom locally without specifying
the Service Principal credentials. But this can now be achieved by just using
the credential of the person running the script.
With the introduction of collecting secrets from Azure keyvault bu means of using a ServicePrincipal. If terraform is executed locally, the current terraform configuration will try to authenticate using the ServicePrincipal, instead of using the context of the person running the terraform command. This issue is more evident or pronounced when using the make file
ignore the azure_credentials if it is not set
=> Allow using personal Azure credentials to run locally

app/helpers/view_helper.rb, app/views/layouts/_beta-banner.html.erb, app/webpacker/stylesheets/_environments.scss
https://trello.com/c/L1rjppxc/972-style-sandbox-banner-in-publish
Adds purple styling to the sandbox banner and updates the text.
- Pull down the code
- Update your `development.yml` to think it's in sandbox mode, by copying from `sandbox.yml`:
```yml
environment:
label: "Sandbox"
selector_name: "sandbox"
```
- Check that the banner is styled correctly.
=> [972] Style the sandbox banner

.github/workflows/deploy.yml, .gitignore, Makefile, terraform/workspace_variables/production.sh, terraform/workspace_variables/production.tfvars, terraform/workspace_variables/qa.sh, terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/sandbox.sh, terraform/workspace_variables/sandbox.tfvars, terraform/workspace_variables/staging.sh, terraform/workspace_variables/staging.tfvars
Validate the screte yaml file before it is saved. As is when a secret-file (yaml file) is not well formed and a `yamldecode` is attempted by Terraform. This would course terraform to fail and spilling out the contents of the secret-file in plain text in the logs.
Add `fetch_config.rb` as part of the terraform deploy process.
=> 976 validate secrets in the pipeline 2

.bundle/config, .dockerignore, .github/workflows/smoke-test.yml, .gitignore, .rspec_smoke, Gemfile, Gemfile.lock, app/controllers/heartbeat_controller.rb, config/settings.yml, config/settings/development.yml, config/settings/production.yml, config/settings/qa.yml, config/settings/sandbox.yml, config/settings/staging.yml, config/settings/test.yml, spec/requests/heartbeat_checks_spec.rb, spec/smoke/healthcheck_spec.rb, spec/spec_helper.rb, spec/spec_helper_smoke.rb
Smoke free
Added missing smoky tests
Amended pub healthcheck calls api ping instead of calling api healthcheck
Required gems
```bash
gem install bundler
echo 'gem "httparty"' >> Gemfile
echo 'gem "rspec"' >> Gemfile
bundle
```
Only works for 
```bash
RAILS_ENV=production ./bin/bundle exec rspec  spec/smoke --options ./.rspec_smoke
RAILS_ENV=qa ./bin/bundle exec rspec  spec/smoke --options ./.rspec_smoke
RAILS_ENV=sandbox ./bin/bundle exec rspec  spec/smoke --options ./.rspec_smoke
RAILS_ENV=staging ./bin/bundle exec rspec  spec/smoke --options ./.rspec_smoke
```
Due to self cert SSL, it will __NOT__ work for as its
```bash
RAILS_ENV=development ./bin/bundle exec rspec  spec/smoke --options ./.rspec_smoke
RAILS_ENV=test ./bin/bundle exec rspec  spec/smoke --options ./.rspec_smoke
``` …
=> 1056 basic smoke test

terraform/modules/paas/main.tf, terraform/workspace_variables/production.tfvars, terraform/workspace_variables/staging.tfvars
Publish is going live on paas
Set paas web app instances to 2 in staging and prod
This is the minimum to avoid downtimes
Run deploy-plan
=> 1065 configure 2 instances of publish in prod

app/models/course.rb, app/models/site.rb, app/views/courses/about.html.erb, app/views/courses/requirements.html.erb, spec/factories/providers.rb, spec/factories/sites.rb, spec/features/courses/about_spec.rb, spec/models/course_spec.rb, spec/support/helpers.rb, spec/support/serializers/provider_serializer.rb
In order to keep the content on publish inline with recent updates on find this PR
tweaks the layout and copy of the about this course and requirements pages. 
The requirements page has a details drop down added. The about page has a drop down
but it will render different information based on whether the course is at a uni
or a SCITT/Schools direct
Test still to be written. Currently blocked by TTW areas work.
=> Update copy on About this Course and requirements page

Makefile
Manage key vault secrets
Use generic [ instead of bash [[
Run `make install-fetch-config`
=> Fix install-fetch-config for non bash shells

app/views/courses/about.html.erb, app/views/courses/preview/placement/_scitt.html.erb, spec/features/courses/about_spec.rb
We've received some concerns from providers about the new schools placement guidance on the Find course page
- Offending paragraph removed from course preview and course create form guidance whilst further user testing is undertaken
https://trello.com/c/lpBrddjm/3080-remove-school-placement-guidance-from-find-and-publish
=> Remove schools placement guidance

config/settings/production.yml, config/settings/qa.yml, config/settings/staging.yml
Test connection from Publish to TTAPI on PaaS before migrating TTAPI over to PaaS
Point publish staging to https://teacher-training-api-prod.london.cloudapps.digital (TTAPI Paas Prod) for testing.
Update find urls
=> Update TTAPI url config

config/settings/sandbox.yml
Clicking the "view on find" link in Sandbox takes you to eg
https://sandbox.find-postgraduate-teacher-training.education.gov.uk/course/EES/A233
When you really want to go to
https://sandbox.find-postgraduate-teacher-training.service.gov.uk/course/EES/A233
Change the config so `search_ui_url` gets the correct domain when we use it to build the link.
=> Point "View on Find" links to the correct sandbox domain

app/controllers/provider_suggestions_controller.rb, spec/requests/provider_suggestions_spec.rb
- https://sentry.io/organizations/dfe-bat/issues/2244373584/?project=1407453&query=is%3Aunresolved
- This PR handles the issue above when dodgy characters are attempted to be sent in the query which raises a `JsonApiClient::Errors::ClientError`. In this scenario it will return an empty result set and remove the error noise in Sentry.
- Fire up publish and attempt to search for an organisation from the admin search view
- If you remove the error handling code and attempt to search with `(Reach Academy Feltham` it'll raise it in the logs. Add it back in and it shouldn't raise it.
=> [1182] Handle JsonApiClient::Errors::ClientError for providers/suggest

app/controllers/application_controller.rb, app/controllers/concerns/admin_only_maintenance_mode.rb, app/views/sign_in/index.html.erb, config/settings.yml, spec/features/sign_in_spec.rb, terraform/workspace_variables/app_config.yml
https://trello.com/c/UobfcRmi/1148-api-migration-implement-publish-maintenance-mode-and-admin-login-only
* Feature setting to enable maintenance mode, with a message.
* Admin users are able to sign in
* Non-admins redirected to sign in page
* Flash message is set on every page.
=> [1148] api migration implement publish maintenance mode and admin login only

config/settings/staging.yml
Publish Staging was pointing to TTAPI PaaS Prod
Point publish staging to the correct prod url
To be merged once testing with TTAPI PaaS Prod is complete.
=> Use correct TTAPI staging url

.github/workflows/build.yml, .github/workflows/deploy.yml, .github/workflows/smoke-test.yml
Alert `@channel` on build/deploy workflow failures
Add action to alert slack channel on build/deployment workflow failures.
=> Slack alert on build failures

.github/workflows/build.yml, .github/workflows/deploy.yml
Use `qa` env as a review environment untill we build review apps support on PaaS. 
Stop deployment to `qa` from `master`
Deploy to `qa` for code pushes to `qa` branch.
=> Deploy to QA env from qa branch

app/controllers/courses/study_mode_controller.rb, spec/features/courses/study_mode/edit_spec.rb
- https://trello.com/c/6zJEvCGc/1321-allow-courses-to-be-changed-to-partime-and-fulltime-by-providers
- Login via a persona, choose a provider/courses/course and update the study mode to full time or part time
- Assert your changes are saved
=> [1321] Allow course study mode to be updated to full time and part time

app/controllers/courses/study_mode_controller.rb, spec/features/courses/study_mode/edit_spec.rb
- https://trello.com/c/6zJEvCGc/1321-allow-courses-to-be-changed-to-partime-and-fulltime-by-providers
- Login via a persona, choose a provider/courses/course and update the study mode to full time or part time
- Assert your changes are saved
=> [1321] Allow study mode to be updated to full time and part time

app/views/personas/index.html.erb
- https://trello.com/c/qmIVxhxq/1480-dup-ids-on-personas-page
These ids are not being used so we're just setting them to nil so they aren't set by the form helpers.
=> [1480] Remove id generation for persona fields

app/views/courses/about.html.erb
- https://trello.com/c/gDoyMfAx/1481-dup-ids-on-about-this-course-page
- Don't generate ids for the hidden fields as they aren't used
=> [1481] Fix dup html ids on courses about view

app/views/courses/applications_open/_form_fields.html.erb, app/views/courses/applications_open/edit.html.erb, app/views/courses/applications_open/new.html.erb
https://trello.com/c/NBPYK2T3/1483-radio-elements-not-grouped-when-will-applications-open-page
From accessibility audit. It is also required that the fieldset has a
legend so the page header must be put inside the fieldset legend for
1 question pages.
**Before**
**After**
=> [1483] Group radios inside fieldset

app/controllers/sites_controller.rb, app/views/sites/_form.html.erb, spec/features/sites/new_spec.rb
We are starting to collect URN numbers on all sites. This PR surfaces the field on the edit locations page.
Add URN text field to the edit locations page
- Pull down the code and boot up the server
- Navigate to `...organisations/provider_code/2021/locations`
- Click on a location
- Enter a valid number in the URN box and save the changes
- Boot up the rails console and check that the change has been saved
=> [1502] Add URN text field to the locations edit page

app/decorators/course_decorator.rb, spec/decorators/course_decorator_spec.rb
Screen reader for ambiguous links
Added a more descriptive meaning for screen reader
=> [1489] Added a more descriptive meaning for screen reader

app/views/courses/show.html.erb
https://trello.com/c/bkB21acy/1484-tab-list-markup-course-show-page
* Adds role="tablist" to ul element
* Each list element has role "tab"
* Aria selected false to basic details tab which is not first selected on page load
* Tab index added so that tabs read as per screenshots below
Visit `organisations/1GT/2021/courses/28KJ/details` for example
=> [1484] Tab markup for accessibility

app/views/courses/accredited_body/edit.html.erb, app/views/courses/accredited_body/new.html.erb
https://trello.com/c/KHgbV0po/1482-radio-elements-not-grouped-accredited-body-page
Added fieldset around radio elements and legend around h1 within fieldset
I changed edit view too as identical markup
Tab through radio buttons, the text now gives more context and information
Unsure if acceptable for 2nd radio button to read 3 out of 3 when selected on screenreader?
=> [1482] Add fieldset and legend to group radio elements

app.json, app/views/providers/contact.html.erb, app/views/providers/details.html.erb, app/views/sites/_form.html.erb
URN and UKPRN
Improve labels and add hint text
=> 1634 Clean up URN UKPRN UI

app/views/providers/allocations/_request_status.html.erb, spec/features/providers/allocations/repeat_allocations_spec.rb
- https://trello.com/c/BoYsQbKJ/1680-m-delete-view-confirmation-links
- Removes the link allowing users to view allocations confirmation as required in the ticket above
The removed code.
=> [1680] Remove view allocation confirmation link

app/views/courses/preview.html.erb, spec/features/courses/preview_spec.rb, spec/site_prism/page_objects/page/organisations/course_preview.rb
This mirrors the changes made in this PR https://github.com/DFE-Digital/find-teacher-training/pull/777
Trello ticket https://trello.com/c/7GGhiNZp/3387-find-surface-age-range-metadata-from-publish
- Adds age range in years to the course details section of the preview page
=> Add age_range_in_years to the course preview page

app/helpers/view_helper.rb, app/views/layouts/_header.html.erb, app/webpacker/stylesheets/_environments.scss, app/webpacker/stylesheets/_header.scss, spec/features/view_pages_spec.rb
Following on from the doing the same on [_Find_](https://github.com/DFE-Digital/find-teacher-training/pulls?q=is%3Apr+label%3AComponents) and [_Apply_](https://github.com/DFE-Digital/apply-for-teacher-training/pulls?q=is%3Apr+label%3AComponents), I’m here to move _Publish_ over to using `govuk-components`. 👋 
* Use `GovukComponent::Header` to render headers (via `govuk-components` `govuk_header` helper method).
* Use same naming conventions for header style modifiers as used on _Apply_
=> Use GovukComponent::Header

app/views/layouts/_footer.html.erb
Uses `GovukComponent::Footer` to render footer component (via `govuk-components` `govuk_footer` helper method).
=> Use GovukComponent::Footer

app/helpers/view_helper.rb, spec/helpers/view_helper_spec.rb
Updates `govuk_back_link_to` helper to use `GovukComponent::BackLink` from `govuk-components`.
There should be no visual changes, although back links will no longer display when a page is printed.
=> Use GovukComponent::BackLink

app/views/layouts/application.html.erb
Uses `govuk_skip_link` helper from `govuk-components` to render skip link.
There should be no visual or behavioural changes.
=> Use govuk_skip_link helper

app/views/courses/_description_content.html.erb, app/views/courses/preview/_apply.html.erb, app/views/courses/request_change.html.erb, app/views/sites/index.html.erb
Uses `GovukComponent::Warning` to render warning text components (via `govuk-components` `govuk_warning` helper method).
=> Use GovukComponent::Warning

app/views/courses/confirmation.html.erb, app/views/courses/preview/financial_support/_placeholder.html.erb, app/views/ucas_contacts/show.html.erb
Uses `GovukComponent::InsetText` to render footer component (via `govuk-components` `govuk_inset_text` helper method).
=> Use GovukComponent::InsetText

app/views/courses/_entry_requirements.html.erb, app/views/courses/about.html.erb, app/views/courses/preview/qualification/_pgce.html.erb, app/views/courses/preview/qualification/_pgce_with_qts.html.erb, app/views/courses/preview/qualification/_pgde.html.erb, app/views/courses/preview/qualification/_pgde_with_qts.html.erb, app/views/courses/preview/qualification/_qts.html.erb, app/views/courses/requirements.html.erb, app/views/courses/subjects/_form_fields.html.erb, app/views/pages/guidance.html.erb, app/views/providers/allocations/pick_a_provider.html.erb, spec/features/courses/about_spec.rb
Uses `GovukComponent::Details` to render details component (via `govuk-components` `govuk_details` helper method).
Also… adds the `title` attribute to the YouTube video frames - good accessibility catch by SonorCloud.
There should be no visual or behavioural changes. Have removed some whitespace between paragraphs, and updated and straight quotes to use smart quotes inside where spotted inside any details content.
=> Use GovukComponent::Details

app/views/pages/terms.html.erb
Removes errant brackets around ‘Department of Education’ in Terms and Conditions.
=> Fix typo in Terms and Conditions

app/views/providers/allocations/_allocation_request_open_state.html.erb, app/views/providers/allocations/initial_request.html.erb, app/views/providers/allocations/number_of_places.html.erb, app/views/providers/edit_initial_allocations/number_of_places.html.erb, config/settings.yml
https://trello.com/c/KhdeasYu/1765-allocations-feature-content-updates
Makes the content changes as per the Trello ticket.
Note: dates and years are being handled in separate PRs, so these are unchanged in this one.
This is what the link looks like:
'Who are you requesting a course for?'
'How many places?'
=> [1765] Update content for allocations and add external link

app/models/provider.rb, app/views/recruitment_cycles/_allocations.html.erb, app/views/recruitment_cycles/show.html.erb, spec/models/provider_spec.rb, spec/views/recruitment_cycles/show_spec.rb
https://trello.com/c/7ZSXSb0X/1682-ensure-allocations-exists-in-both-current-cycle-and-next-cycle-sections-in-publish-when-mid-rollover
We want to show the same allocations section (for the current cycle)
on the Next Cycle page for providers, as users get confused that it 
‘disappears’
Show allocations section on the "Next Cycle" page for the "Current" cycle
=> [1682] Show allocations section on Next Cycle page

app/helpers/allocation_cycle_helper.rb, app/helpers/breadcrumb_helper.rb, app/helpers/recruitment_cycle_helper.rb, app/views/pages/performance_dashboard/_allocations_tab.html.erb, app/views/pages/rollover.html.erb, app/views/pages/rollover_recruitment.html.erb, app/views/providers/_show_during_rollover.html.erb, app/views/providers/allocations/_allocation_report_confirmed_state.html.erb, app/views/providers/allocations/_allocation_request_closed_state.html.erb, app/views/providers/allocations/_allocation_request_confirmed_state.html.erb, app/views/providers/allocations/_allocation_request_open_state.html.erb, app/views/providers/allocations/requests/_not_requested.html.erb, app/views/providers/allocations/requests/_yes_requested.html.erb, app/views/recruitment_cycles/_allocations.html.erb, config/locales/en.yml, config/settings.yml, config/settings/review.yml, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb, spec/features/sign_in_spec.rb, spec/views/recruitment_cycles/show_spec.rb
https://trello.com/c/bUofqbav/1730-allocations-change-hardcoded-2021-22-to-2022-23
* replaced hardcoded recruitment cycle year with helpers
* New settings for allocation year added `Settings.allocation_cycle_year`
* `Settings.allocation_cycle_year` should match correctly to ttapi's `Settings.allocation_cycle_year`
=> [1730] change hardcoded recruitment cycle years

config/settings/rollover.yml
This PR turns on the required settings for rollover, in the rollover environment. 
As documented [here](https://github.com/DFE-Digital/publish-teacher-training/pull/1655/files)
- Navigate to `https://publish-teacher-training-rollover.london.cloudapps.digital/organisations`
- Choose a provider and click on it
- Check that the page displays links for both the current cycle, and next cycle 
- 🚢
=> [1797] Turn on settings required for rollover (in rollover environment)

Gemfile, app/views/pages/rollover_recruitment.html.erb, spec/features/sign_in_spec.rb
Updating the content on the interruptions screen in preparation for the next cycle.
- Navigate to `/rollover-recruitment`
=> [1787] Update allocations interruption screen content for 2022-2023

app/helpers/allocation_cycle_helper.rb, app/views/providers/allocations/requests/_yes_requested.html.erb
We were showing the wrong date on the allocations requested page (the previous instead of the current cycle dates).
How it was:
How it is:
=> [xxxx] Fix date on allocations requested page

app/controllers/application_controller.rb, app/controllers/users_controller.rb, app/models/interrupt_page_acknowledgement.rb, app/models/user.rb, app/views/pages/rollover.html.erb, app/views/pages/rollover_recruitment.html.erb, config/routes.rb, spec/controllers/application_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/features/sign_in_spec.rb, spec/features/sites/index_spec.rb, spec/models/user_spec.rb, spec/requests/recruitment_cycles_spec.rb, spec/support/features.rb, spec/support/helpers.rb
https://trello.com/c/ztZfy8sZ/1809-avoid-adding-acceptedrollover2022-user-state
- Replaces the old mechanism for determining when to show interrupt pages based on user state
- Breaks apart the 2 rollover interrupt pages so they can be turned on independently 
- Calls a new endpoint on TTAPI for creating acknowledgements for interrupt pages per user/page type/recruitment cycle: https://github.com/DFE-Digital/teacher-training-api/pull/1942
Run locally in combination with https://github.com/DFE-Digital/teacher-training-api/pull/1942
- Check that the pages do not show up when rollover flags are off
- Create a new recruitment cycle on TTAPI (for the next year after the one you have set for current)
- Turn on `rollover.can_edit_current_and_next_cycles` and …
=> [1809] Use interrupt page acknowledgements for rollover interrupt pages

app/decorators/application_decorator.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/_status_panel.html.erb, app/views/courses/title/edit.html.erb, app/views/personas/index.html.erb, app/views/providers/_search.html.erb, app/views/providers/allocations/_allocation_report_closed_state.html.erb, app/views/providers/allocations/_request_status.html.erb, app/views/providers/contact.html.erb, app/webpacker/stylesheets/_phase-tag.scss, app/webpacker/stylesheets/_related.scss, app/webpacker/stylesheets/application.scss, spec/decorators/course_decorator_spec.rb
Uses `GovukComponent::Tag` to render panel component (via `govuk-components` `govuk_tag` helper method).
* Use `govuk_tag` for status tags
* Refactor `ApplicationDecorator` to use `govuk_tag` and supply `text` and `colour` values
* Update tests to check for `govuk--` colour modifiers instead of `phase-tag--` modifiers
* Refactor `app-related` CSS by consolidating SCSS files
* Fix some HTML markup surrounding tags, using the right elements and classes
=> Use GovukComponent::Tag

config/settings.yml, config/settings/test.yml
Allocations opened on 1 June 2021.
https://trello.com/c/yNzAoH7Q/1823-open-allocations-2021
This PR updates the required settings to allow users to request allocations for 2022/23, showing them an interrupt screen on first sign in.
=> Update settings to open allocations 2021

Makefile
We have a make command for opening a rails console.
Console was being opened on TTAPI. Fixed to open on Publish.
This will let us interact with the API from the console using Publish's
JSON client objects.
Open a console, check `ENV` is pointing at publish.
=> [xxx] Fix make console

app/views/shared/_form_field.html.erb, app/views/sites/_form.html.erb
Error is going all red
Make it less red
=> [1720] Error messages on Publish are not aligned with the actual error

config/initializers/sidekiq.rb
Redis connection string is not set for SideKiq
see: https://sentry.io/organizations/dfe-bat/issues/2434789702/?project=1407453
Read redis credentials from VCAP services injected by PaaS.
=> Read redis credentials from VCAP services

.rubocop.yml, app/views/access_requests/confirm.html.erb, app/views/courses/age_range/edit.html.erb, app/views/courses/details.html.erb, app/views/courses/show.html.erb, config/locales/en.yml, lib/rubocop/cop/govuk/govuk_button_to.rb, lib/rubocop/cop/govuk/govuk_link_to.rb, lib/rubocop/cop/govuk/govuk_submit.rb
Add custom cops to check for use of `govuk_link_to` and `govuk_button_to` helpers. Also added a cop to check for use of `govuk_submit`, but disabled until all forms are using the form builder.
This follows a similar PR to that on [Apply](https://github.com/DFE-Digital/apply-for-teacher-training/pull/4078).
* Add custom cops
* Fix instances of helpers not being used
* Fix a type (missing space in allocations copy)
=> Enforce use of govuk_link_to et al

docs/rollover.md
Updating the publish docs to have more information about changing the `has_current_cycle_started` setting.
Review the readme
=> [1816] Update publish docs to reflect updated rollover information

Dockerfile, Gemfile, Gemfile.lock, app/controllers/providers/allocations_controller.rb, app/models/allocation.rb, app/view_objects/allocations_view.rb, app/views/providers/allocations/_allocation_request_open_state.html.erb, config/settings/review.yml, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb, spec/view_objects/allocations_view_spec.rb
https://trello.com/c/BQ6F49Q6/1905-providers-unable-to-confirm-last-years-allocations
To be deployed after: https://github.com/DFE-Digital/teacher-training-api/pull/1962
We have been showing all training providers currently offering fee-funded PE for which an accredited body accredits courses in the re-request list for allocations.
This shows the same training providers, but filtered to those for which the accredited body requested allocations for in the previous recruitment cycle.
=> [1905] Show last year allocations for re-requests

app/views/providers/_search.html.erb
We lost the `govuk-body` class in this PR - https://github.com/DFE-Digital/publish-teacher-training/pull/1715/
Re-add `govuk-body` to the autocomplete wrapper
- Login in as an admin user
- Search for a provider
=> [1939] Fix typeface on org index autocomplete

app/controllers/providers/allocations_controller.rb, app/view_objects/allocations_view.rb, spec/controllers/providers/allocations_controller_spec.rb, spec/factories/providers.rb, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb
Allocations and accredited provider and its training providers
Previously the list of training providers (for making `repeat` request type) has actual relationship with its training providers. Based on that they are running a PE course for next year as will as they have previously being allocated.
Now the same list will be based solely on previously being allocated.
Commits are probably best to view as 2 parts with the first 3 of making the changes and its related tests. The latter 3 as make the changes downstream.
You need to actually spin this up, and use https://github.com/DFE-Digital/teacher-training-api/pull/1972 
Allocations
-  is a closed loop system
- it has a sliding window of time
- aka `journey mode`
- it has it own lifecycle from `open`  -> `closed` -> `confirmed`
- it has its …
=> [1918] Fixed to show previous allocations

app/views/providers/_show_during_rollover.html.erb
https://trello.com/c/LJWi1K8l/1907-s-allocations-bullet-point-should-be-in-both-cycles
- Updates the content for the allocations bullet point seen during rollover
- Copies the bullet point into the 'Next cycle' section
This is what it now looks like 'During rollover':
=> [1907] Update bullet point re allocations in rollover

app/views/contacts/edit.html.erb, app/views/courses/about.html.erb, app/views/courses/age_range/_errors.html.erb, app/views/courses/age_range/edit.html.erb, app/views/courses/requirements.html.erb, app/views/courses/show.html.erb, app/views/layouts/_flash.html.erb, app/views/providers/about.html.erb, app/views/providers/details.html.erb, app/views/shared/_errors.html.erb, spec/features/courses/about_spec.rb, spec/features/courses/age_range_in_years/edit_spec.rb, spec/features/courses/destroy_spec.rb, spec/features/courses/entry_requirements/edit_spec.rb, spec/features/courses/fees_spec.rb, spec/features/courses/outcome/edit_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb, spec/features/courses/withdraw_spec.rb, spec/features/providers/about_spec.rb, spec/features/providers/contact_spec.rb, spec/features/providers/search_spec.rb
The commonly used title for error summaries (and the default used by the form builder) is ‘There is a problem’. We should use this rather than a customised version.
Replace ‘You’ll need to correct some information.’ with ‘There is a problem’.
=> Use common error summary title

app/views/providers/_provider.html.erb, app/views/providers/training_providers.html.erb
* Show current cycle in caption, like for other sections
* Move sidebar up to below page title, like in other parts of the service
* Adjust heading sizes
| - | - |
| ![before](https://user-images.githubusercontent.com/813383/123006197-3e20b300-d3af-11eb-85b8-a9a360a202d6.png) | ![after](https://user-images.githubusercontent.com/813383/123006186-3a8d2c00-d3af-11eb-9bc4-29768cc3efe1.png) |
=> Fix layout for ‘Courses as an accredited body’ page

app/views/courses/age_range/_errors.html.erb, app/views/courses/vacancies/edit.html.erb, app/views/shared/_errors.html.erb, spec/features/courses/vacancies/edit_spec.rb
Follows on from #1741.
* Always use ‘There is a problem’, and don’t allow for customised error summary titles in shared partials.
=> Use common error summary title (part 2)

app/views/courses/_basic_details_tab.html.erb, app/views/courses/confirmation.html.erb, config/settings.yml, docs/rollover.md
https://trello.com/c/SX21cZax/1977-s-rollover-create-update-google-forms-for-the-next-cycle
Adds the urls for the google forms for adding a PE course to the next cycle.
=> [1977] Add google forms for next cycle

app/views/courses/_description_content.html.erb, app/views/providers/about.html.erb, app/views/providers/contact.html.erb, app/views/providers/details.html.erb, app/views/providers/visas/edit.html.erb, config/locales/helpers.yml, spec/features/providers/about_spec.rb, spec/features/providers/contact_spec.rb
* Update provider contact details form to use the form builder
* Adjust label sizes (use medium size)
* Add autocomplete values
* Use a fieldset around address fields
* Show correct hidden label text for building and street input lines
* Tidy up corresponding about page
* Adjust label sizes
* Fix typo
* Pluralise ‘accredited body’ based on number of accredited bodies provider works with
* Update markup and syntax style to match that used on contact page
=> Use form builder for provider forms

app/views/notifications/index.html.erb
* Adds ‘Error: ’ prefix when form has validation
* Correct heading size for legend (medium, not large)
* Simplified grid markup for layout
Worth nothing that this form doesn’t actually validate correctly; if no option is selected, a flash banner is shown, but the incorrect fields are not highlighted. That’s because this isn't using a form model. *C'est la vie*
=> Tidy up notifications form

app/views/courses/accredited_body/_provider_search_field.html.erb, app/views/providers/_search.html.erb, app/views/providers/allocations/initial_request.html.erb, app/views/providers/allocations/pick_a_provider.html.erb, app/webpacker/stylesheets/_autocomplete.scss, app/webpacker/stylesheets/application.scss
Adds the necessary CSS to style autocompletes, both the font used in the suggestions list, and when they are being validated.
| - | - |
| <img width="657" alt="Screenshot 2021-06-25 at 12 10 45" src="https://user-images.githubusercontent.com/813383/123416498-88bc4e00-d5ae-11eb-9fe6-883f6a18371c.png"> |  <img width="660" alt="Screenshot 2021-06-25 at 12 13 01" src="https://user-images.githubusercontent.com/813383/123416632-b903ec80-d5ae-11eb-9587-31c343a78831.png"> |
| <img width="694" alt="Screenshot 2021-06-25 at 12 10 31" src="https://user-images.githubusercontent.com/813383/123416495-8823b780-d5ae-11eb-9f2d-0dc386c008ac.png"> | <img width="695" alt="Screenshot 2021-06-25 at 12 10 05" src="https://user-images.githubusercontent.com/813383/123416491-8823b780-d5ae-11eb-8b …
=> Fix autocomplete styles

app/helpers/provider_helper.rb, app/models/provider.rb, app/views/courses/preview.html.erb, app/views/courses/preview/_international_students.html.erb, app/views/providers/details.html.erb, spec/features/providers/visa_spec.rb, spec/helpers/provider_helper_spec.rb
This PR is a follow up to https://github.com/DFE-Digital/publish-teacher-training/pull/1725
It adds an _International students_ section to the course preview page.
See https://trello.com/c/I2K4fchq/3441-add-visa-flow-to-publish
=> Visa sponsorship course preview

app/views/courses/status_panel/_unpublished.html.erb, app/views/pages/notifications_info.html.erb, app/views/pages/rollover.html.erb, app/views/pages/rollover_recruitment.html.erb, app/views/pages/transition_info.html.erb
There are few places where there are page submission buttons. These can use the `govuk_button_to` helper, to ensure they are styled using the design system.
* Use `govuk_button_to` for form submission buttons on pages
* Use `govuk_button_to` for form submission Publish button in course sidebar
* Any reason why you wouldn’t do this?
=> Use `govuk_button_to` helper

app/views/providers/contact.html.erb, app/views/sites/_form.html.erb, app/views/sites/_site.html.erb, app/views/sites/edit.html.erb, app/views/sites/index.html.erb, app/views/sites/new.html.erb, config/locales/helpers.yml, spec/factories/errors.rb, spec/features/sites/edit_spec.rb, spec/features/sites/new_spec.rb
Prior to removing the 37 limit, update the location forms to use the form builder.
* Update the location forms to use the form builder.
* Tweak markup on other pages to be consistent/correct.
=> Use form builder for site forms

.github/workflows/delete-review-app.yml
Delete review app may fail if the concurrent deploy takes too long
Increase to 30 min and fail the workflow immediately if the timeout is reached
=> [2089] Fix delete review app timeout

app/helpers/view_helper.rb, app/models/site.rb, app/views/sites/_site.html.erb, app/views/sites/index.html.erb
- https://trello.com/b/BBEuhbHM/publish-register-sprint-board
- Add a new column to display the URN for the locations table
- Render a `Missing` text if the URN isn't provided
- Link back to this page upon an invalid submission when attempting to publish a course
- Needs this branch on API https://github.com/DFE-Digital/teacher-training-api/pull/2016
=> [2122] Add URN column to locations table

app/webpacker/stylesheets/application.scss
The [new link styles](https://github.com/alphagov/govuk-frontend/releases/tag/v3.12.0) are currently opt-in. The main differences are:
> Links now have underlines that are consistently thinner and a bit further away from the link text.
>
> Links also have a clearer hover state, where the underline gets thicker to make the link stand out to users.
Version 3.13.0 of govuk-frontend [disables ink skipping of underlines in hover state](https://github.com/alphagov/govuk-frontend/pull/2251) to avoid large gaps appearing in the underline on hover in Safari and Firefox.
=> Enable new link styles

app/views/courses/degrees/grade/edit.html.erb, app/views/courses/degrees/start/edit.html.erb, app/views/courses/degrees/subject_requirements/edit.html.erb
Updates course degree forms to align with some recent changes.
* Make `page_title` a variable
* Use `title_with_error_prefix` helper for page title
* Use `hint` option for `degree_grade_required` fieldset
* Use `f` for forms that use the form builder
* Are the right errors being tested for in `title_with_error_prefix`
=> Tidy up course degree forms

app/models/provider.rb, app/views/providers/_show_during_rollover.html.erb, spec/features/sites/index_spec.rb, spec/models/provider_spec.rb
https://trello.com/c/EoqAKVNZ/2064-non-rolled-over-providers-get-an-error-when-clicking-into-the-next-cycle
* Add `from_next_recruitment_cycle` method on provider model that makes an api request to provider show controller endpoint. It detects whether the provider has been rolled over into the next recruitment cycle searching by provider code. If the provider has been rolled over next cycle link will show, otherwise not found error will be rescued returning nil and different text will show. 
* Add placeholder text to notify providers who weren't automatically rolled over that they need to contact support if they would like them/their courses to be
* Model spec to test the `from_next_recruitment_cycle` method
Follow instructions on [this …
=> [2064] Hide next cycle link for non rolled over providers

app/views/pages/rollover.html.erb
- https://trello.com/c/l4dxQqCP/1980-add-interruption-screen-for-rollover
- You'll need to follow the rollover steps in both publish and api to enable the next recruitment cycle
- Login as one of the personas
- Assert updated content
- [] Product Review
=> [1980] Update the rollover interruption screen content for the next cycle

app/helpers/site_helper.rb, app/models/site.rb, app/views/sites/_site.html.erb, app/views/sites/index.html.erb
- https://trello.com/c/ivuE1Rxi/2122-s-render-urn-on-publish-locations-table-and-link-back-to-it-from-an-invalid-course-publish-submission-due-to-missing-urn
Following up on the PR above, this PR only displays the new URN column from the next cycle onwards.
=> [2122] Only render the urn column from the 2022 cycle onwards

app/components/gcse_requirements_component.rb, spec/components/gcse_preview_component_spec.rb, spec/factories/courses.rb
In order to render different reqs for ucl courses I've added a method on
the course model to determine which courses are ucl. Added logic to the
view components to render different reqs in this case.
=> Add logic and content to GCSE components for UCL courses

docs/developing_against_teacher_training_api.md
When working on publish it's sometimes useful to be able to set up the Teacher Training API in a particular state to allow acceptance testing etc.
Document some options.
Read the docs. Reflect. Comment/Approve.
=> [xxx] Document API development options

.github/workflows/build.yml
PR check doesn't fail if review app deployment fails.
Wait for review app deployment in PR build workflow
and fail the PR build check, if the review app deployment fails
=> Wait for review app deployment to finish

app/helpers/provider_helper.rb, app/views/providers/details.html.erb, app/views/providers/visas/edit.html.erb, spec/helpers/provider_helper_spec.rb
This PR tidies up a couple of cosmetic issues with the recent addition of Provider visa sponsorship declarations.
1. Remove the 'You' in the copy for the  call to action in the _About your organisation_ summary card:
BEFORE:
AFTER:
2. Update the copy for the negative radio button under the _Can you sponsor Skilled Worker visas?_ question in line with the latest design:
BEFORE:
AFTER:
Original card: https://trello.com/c/I2K4fchq/3441-add-visa-flow-to-publish
Does this match the design?
=> Fix bug rendering visa sponsorship status

app/views/pages/guidance.html.erb, app/views/sites/index.html.erb
Related to https://github.com/DFE-Digital/teacher-training-api/pull/2025,
Remove note about limiting to 37 locations, as providers will now be allowed more than 37 locations.
**Locations page Current**
**Locations page Proposed**
**Guidance page Current**
**Guidance page Proposed**
=> [2091] Remove note about limiting to 37 locations

app/controllers/providers/references_controller.rb, app/form_objects/provider_references_form.rb, app/helpers/view_helper.rb, app/views/providers/references/edit.html.erb, config/routes.rb, spec/form_objects/provider_references_form_spec.rb
https://trello.com/c/OnSfBQvM/2121-s-display-required-notice-for-ukprn-with-form-to-set-it-on-publish
- Enrich UKPRN validation error with a link that takes the user to a new form page to capture the UKPRN value
- Checkout this [Training API branch](https://github.com/DFE-Digital/teacher-training-api/pull/2022) locally and run it
- Load up the Publish app locally so that it connects to the API mentioned previously
- Find a course from the 2022-2023 recruitment cycle
- Try and publish it
- You should get a validation error about missing UKPRN
- Click on the validation error which should take you to the new form
- Play around with validation to make sure it works, then enter a valid value
- Trying publishing the course again - should not display any validation error relating to UKPRN
=> [2121] Enrich missing UKPRN validation with link to UKPRN form

app/helpers/view_helper.rb, config/locales/helpers.yml
We should consistently capitalise the following:
* UK Provider Reference Number
* Unique Reference Number
=> Capitalise reference number abbreviations

app/helpers/view_helper.rb
The string returned by TTAPI has changed and the behaviour here is bound
to the string format.
Update the string.
=> [xxx] Fix UKPRN validation

app/components/gcse_preview_component.html.erb, app/components/gcse_row_content_component.html.erb, app/controllers/courses/gcse_requirements_controller.rb, app/form_objects/courses/gcse_requirements_form.rb, app/helpers/view_helper.rb, app/validators/word_count_validator.rb, app/views/courses/_basic_details_tab.html.erb, app/views/courses/gcse_requirements/edit.html.erb, app/views/courses/preview/_entry_requirements_qualifications.html.erb, app/views/courses/show.html.erb, config/locales/en.yml, spec/features/courses/gcse_equivalency_spec.rb, spec/form_objects/courses/gcse_requirements_form_spec.rb, spec/validators/word_count_validator_spec.rb, spec/views/courses/_basic_details_tab.html.erb_spec.rb
As part of a review of the structured GCSE feature at Dev Design meeting a number of actions were required:
https://trello.com/c/oLvRx47b/3497-add-the-structured-gcse-requirements-section-to-publish
This PR adds :
- validations to the check boxes for gcse equivalencies if none are selected. 
- length validation to the `additional_gcse_equivalencies` field along with word count, and saving formatted text.
- Removes the UCAS Apply row fro the basic details tab for next cycle course onwards.
- removes prepare for next cycle banner
- ensures that validations on course form link to correct section.
Test in the review App to check that criteria have been covered.
N.B. there is a follow up PR covering the `change` links on the course detail page and the  removal of the qualifications on the …
=> Structured gcse tidy up

app/views/courses/_description_content.html.erb, app/views/courses/requirements.html.erb, spec/features/courses/about_spec.rb, spec/features/courses/fees_spec.rb, spec/features/courses/requirements_spec.rb, spec/features/courses/salary_spec.rb, spec/features/courses/show_spec.rb
follow on from  #1788
https://trello.com/c/oLvRx47b/3497-add-the-structured-gcse-requirements-section-to-publish
Remove qualifications form requirments page for new cucle courses in order to prevent providers from updating value
for next cycle courses. New design of course page uses change links instead of linked headers.
Check in review app, ~~TTAPI fix pending for validations~~ Merged.
=> Update requirements page and course description page

config/settings.yml, config/settings/qa.yml, config/settings/sandbox.yml
Rollover has rolled over.
Enable next cycle in staging, production and review.
Left disabled in QA and sandbox as those environments aren't rolled over.
We can enable QA tomorrow and 'have a think ™️' about rolling over sandbox.
=> [xxx] Enable editing of next cycle courses

app/helpers/view_helper.rb
We need to change the validation error format which is set in TTAPI.
Unfortunately this is affects the functionality in publish.
Corresponding TTAPI PR -> https://github.com/DFE-Digital/teacher-training-api/pull/2042
Support both formats for now so as we don't break when the API changes
are made.
I'll take the old format out when the change has been made and deployed on TTAPI.
* Run publish against the current TTAPI
* Try to publish a course on a provider without a UKPRN
* Click the error message
* The UKPRN form should open
=> [2170] Support both UKPRN validation formats

config/settings/qa.yml, config/settings/sandbox.yml
We've rolled over production and staging but needed to wait until QA synced overnight before enabling the next cycle on that environment. Sandbox has also been done manually since as it doesn't sync.
Enable the next cycle in QA and sandbox.
=> [xxx] Switch rollover in QA & Sandbox

app/services/course_creation_step_service.rb, app/views/courses/confirmation.html.erb, spec/services/course_creation_step_service_spec.rb
Hot fix to prevent this from displaying to providers. Test will follow.
https://trello.com/c/76ayE2pT/3600-%F0%9F%93%90-remove-ucas-gcse-requirements-from-new-course-creation-flow
Update to `CourseBasicDetailConcern` to skip over step and fix back link. Conditionally render UCAS row on confirmation page.
=> Remove UCAS Apply GCSE requirements from next cycle

app/views/contacts/edit.html.erb, app/views/courses/_course_length.html.erb, app/views/courses/_related_sidebar.html.erb, app/views/courses/about.html.erb, app/views/courses/age_range/_form_fields.html.erb, app/views/courses/age_range/edit.html.erb, app/views/courses/age_range/new.html.erb, app/views/courses/confirmation.html.erb, app/views/courses/delete.html.erb, app/views/courses/fees.html.erb, app/views/courses/requirements.html.erb, app/views/courses/salary.html.erb, app/views/courses/sites/edit.html.erb, app/views/courses/subjects/new.erb, app/views/courses/withdraw.html.erb, app/views/pages/accept_terms.html.erb, app/views/providers/allocations/check_your_information.html.erb, app/views/providers/allocations/edit.html.erb, app/views/providers/allocations/initial_request.html.erb, app/views/providers/allocations/new_repeat_request.html.erb, app/views/providers/allocations/number_of_places.html.erb, app/views/providers/allocations/pick_a_provider.html.erb, app/views/providers/edit_initial_allocations/check_answers.html.erb, app/views/providers/edit_initial_allocations/do_you_want.html.erb, app/views/providers/edit_initial_allocations/number_of_places.html.erb, app/views/providers/visas/edit.html.erb, app/views/sign_in/dfe_sign_in_is_down.html.erb, config/locales/helpers.yml
Where we’re using the GOV.UK Form Builder, let’s use it consistently.
* Set `page_title` variable where this is needed twice
* Use `f` for forms that use the GOV.UK Form Builder, `form` for those that don’t, so that it’s clear which parts of the code base are using the older methods.
* Consistent code style, especially for `form_with`
* Consistent layout, with error summary always above the page heading
* Use localisation strings where possible
=> Tidy up forms that use GOV.UK Form Builder

app/views/courses/degrees/grade/edit.html.erb, spec/features/courses/degree_spec.rb
https://trello.com/c/0Zv8N4b8/2186-degree-grade-requirement-bug
* Fixed bug by correcting value on radio button element
* Added more coverage to tests to prevent it happening again
Check that you can select the third class degree option on the form
`organisations/#{code}/2022/courses/#{code}/degrees/grade`
=> [2186] Degree grade requirements bug

app/models/course.rb, app/models/site.rb, app/views/courses/preview/placement/_hei.html.erb, spec/factories/sites.rb, spec/features/courses/about_spec.rb, spec/models/course_spec.rb
We don't have immediate plans to utilise travel to work data as the design intent changed.
Remove references to travel to work data
https://trello.com/c/Tmk3UH8J/3628-remove-travel-to-work-api-dependency-from-the-ttapi
=> Remove references to 'travel to work' data

app/models/course.rb, app/views/courses/about.html.erb, app/views/courses/preview/_about_schools.html.erb, app/views/courses/preview/placement/_hei.html.erb, app/views/courses/preview/placement/_scitt.html.erb, spec/features/courses/about_spec.rb
The preview page on Publish has got out of line with Find for the 'Where you will train content'
There's some fairly niche behaviour that can be seen here 
- only render content about not getting to choose where you will train for SCITT courses that aren't Educate Teacher Training
- only render uni content for providers that aren't The Bedfordshire Schools Training Partnership (B31) & are unis
- Don't render content for school directs
=> Update the content around where you will train to be in line with find

app/views/providers/training_providers.html.erb, spec/features/providers/training_providers_spec.rb
- https://trello.com/c/LNFxpRa0/2301-remove-download-csv-link-when-no-training-providers-listed
- Head to http://localhost:3000/organisations/13S/2022/training-providers (as Colin), assert no CSV export is offered
- Head to http://localhost:3000/organisations/D87/2022/training-providers (as Susy) and assert CSV export is shown
=> [2301] Hide CSV export if there are no training providers

app/components/degree_row_content_component.html.erb, app/components/degree_row_content_component.rb, app/components/gcse_requirements_component.rb, app/components/gcse_row_content_component.html.erb, app/views/courses/_description_content.html.erb, spec/components/gcse_preview_component_spec.rb, spec/components/gcse_row_content_component_spec.rb
If a course page is showing validation, the messages for new Degree and GCSE fields should be red (`app-inset-text--error`), not blue (`app-inset-text--important`).
- Pass in the errors into the `DegreeRowContentComponent` and `GcseRequirementsComponent`.
- Declare a `#inset_text_css_classes` method on each component which returns the correct css classes depending on whether errors are present or not
Spin up Publish / API with a recent DB dumb. Find a provider who has courses in the next cycle (e.g. Claydon High School) and select a rolled over course. You should see that the GCSE and Degree fields are `blue` but when you try to publish, the error summary appears and those fields are now displayed in `red`.
This feels like a bit of a hack, however, currently we are reliant on the API to …
=> Display validation messages in 'red' when errors are present

terraform/workspace_variables/app_config.yml
We manage our environment variables using a combination of the settings gem (config/settings.yml etc) and secrets merged in from a key store. We don't need to set them in from terraform as the precedence is confusing.
Some env vars need to present when the app boots so they need to be set by terraform.
Tidy up the terraform file. Remove old unused variables and those that are in settings.
=> [XXX] Tidy up environment variables

app/components/degree_preview_component.html.erb, app/components/degree_preview_component.rb, app/components/gcse_preview_component.html.erb, app/components/gcse_preview_component.rb, app/views/courses/_markdown_formatting.html.erb, app/views/courses/_related_sidebar.html.erb, app/views/courses/degrees/subject_requirements/edit.html.erb, app/views/courses/gcse_requirements/edit.html.erb
The `GCSE` and `Degree` sections were recently added as new features within the `Requirements and eligibility` section. Markdown was considered out of scope. We need to add this to ensure consistency across Publish. 
- Add markdown to `Degree` and `GCSE` sections
- Add guidance text for markdown
- Refactor guidance text into partial
- Visit an organisation on Publish and go to a course in the next cycle: https://publish-teacher-training-pr-1842.london.cloudapps.digital/organisations/1A4
- Scroll down to the `Requirements and eligibility` section
- Click on change, follow the journey through and add markdown text in the free text field and save it
- Visit preview and ensure that the markdown has been translated to markdown
- Verify that the guidance text added is consistent with the rest …
=> [2377] Add markdown to Publish GCSE and Degree sections

app/components/gcse_preview_component.html.erb, app/views/courses/preview/_international_students.html.erb, app/views/courses/preview/placement/_hei.html.erb, app/views/courses/preview/placement/_scitt.html.erb, spec/features/providers/visa_spec.rb
Follow on work done in DFE-Digital/find-teacher-training#873 to bring the preview page in line with the updated content on Find. 
- Update the content on the course preview page to be in line with the content on Find
https://trello.com/c/eHkPZRRx/3787-update-content-on-find-publish-for-structured-quals
=> Update copy for the international candidates section of the find preview page

app/views/courses/_copy_content_warning.html.erb
- [This trello ticket](https://trello.com/c/02t0nzsy/2647-links-dont-work-when-copying-personal-other-details-from-another-course)
- Appended `course` and prepended `field` onto the error links to ensure they link to their corresponding input boxes
- Find a course (any course)
- Go to personal qualities and other requirements section
- Edit it
- Use the copy from dropdown and select another course and click copy
- You are met with a warning message. 
- This warning message has links, which now link to the corresponding input box they are referencing
=> [2647] Warning links now link to input box

app/views/courses/preview/_contact_details.html.erb, spec/features/courses/preview_spec.rb
We've been asked to add a custom address for one course provided by London School of Jewish Studies.
This has been ✅'d by Rachael 
Show the address found here https://www.publish-teacher-training-courses.service.gov.uk/organisations/28T/2022/courses/X104/locations for 28T X104 
I'll add the changes to the preview page on Publish in a PR now.
https://trello.com/c/Dvyc6Ozy/723-address-incorrect-for-1-course-for-provider-28t?filter=a%20leve&menu=filter
=> Add bespoke address logic for 28T X104

app/form_objects/provider_visa_form.rb, app/helpers/provider_helper.rb, app/helpers/view_helper.rb, app/views/courses/preview/_international_students.html.erb, app/views/pages/rollover.html.erb, app/views/providers/details.html.erb, app/views/providers/visas/edit.html.erb, spec/features/providers/visa_spec.rb, spec/helpers/provider_helper_spec.rb, spec/helpers/view_helper_spec.rb
This changes the visa sponsorship question from asking directly "Can you sponsor Skilled worker/Student visas?" to "Can candidates get a sponsored Skilled worker/Student visa for your fee-paying/salaried courses?"
The reason for this change is that we have now learnt that in some cases, the organisation doing the sponsoring won’t be the provider themselves, but might be the organisation accrediting the QTS status or school employing the person on the salaried course. This may or may not be the provider, depending on how the organisation is set up.
In addition we’ve also added some guidance text at the top which links to pages on GOV.UK which list organisations who have the sponsor licence (if they need to check), and to a guidance page on how to become able to sponsor visas.
See [changes …
=> Update visa sponsorship wording and guidance

Gemfile.lock, app/controllers/courses_controller.rb, spec/features/courses/requirements_spec.rb
- [This trello ticket](https://trello.com/c/KpMNPHrn/2646-when-copying-personal-other-details-from-another-course-banner-confirms-qual-info-have-been-copied-too)
- If the recruitment year is after 2021, we reject the `Qualifications needed` from the requirements array
- Go to 2022-23 recruitment year
- Click add course
- Fill out all details
- And on the review page, go down to the requirements and eligibility section
- Click a course to copy the details from, and see that the warning message no longer has qualifications needed in the message. 
- You can verify it hasnt been removed from the 2021 courses, if you repeat the same as above but in the previous cycle
=> [2646] Reject qualifications needed if course recruitment cycle after 2021

terraform/modules/paas/main.tf
https://github.com/DFE-Digital/publish-teacher-training/runs/3586753730
Apps take a long time to start (above 2 min) and they may breach the
timeout. Increased from 3 to 5 min.
=> Increase cloudfoundry apps start timeout

app/views/layouts/_flash.html.erb
- [This trello ticket](https://trello.com/c/Uk7rxZMX/71-notices-warning-success-error-have-a-duplicated-title)
- Replaced execution tags with expression tags to avoid duplication of notification message
- If you create and publish a course, the success message will only show one message
=> [71] Duplicated notification fix

app/views/courses/index.html.erb, app/views/providers/show.html.erb, app/views/recruitment_cycles/show.html.erb, config/settings/review.yml
- [This trello ticket](https://trello.com/c/rbExOfUP/128-add-banner-on-publishing-courses)
- Blue 'Important' banner at the top of the provider show page
- Navigate to the Provider Show Page and see the notification banner on the top of the page.
=> [127] Added Important banner with reminder to publish courses ahead of SoC

app/helpers/view_helper.rb, app/views/layouts/_phase_banner.html.erb, config/locales/en.yml, maintenance/maintenance.html, spec/helpers/view_helper_spec.rb
- [This trello ticket](https://trello.com/c/eaKdfhfj/140-change-feedback-hyperlink-with-survey-link)
- Feedback changed from mailto to google form link
- Click on the feedback link on the top of the page
=> [140] Changed feedback mailto link to googleform link

app/views/courses/_copy_content_warning.html.erb
- [This trello ticket](https://trello.com/c/yprBbBFm/153-bug-duplicate-heading-for-your-changes-have-not-yet-been-saved)
- Replaced execution tags with expression tags to avoid duplication of notification message
- Copy content from one course to another (such as GCSE information) and the notification only has a single title
=> [153] Removed execution tag to stop duplication of warning message

config/settings/production.yml
- Update cycle to 2022 in production
- Removed `current_cycle: 2021` and related info in `production.yml`. Will now fallback to `settings.yml`, where `current_cycle: 2022`
=> [167] Removed cycle in production.yml

app/controllers/providers/allocations_controller.rb, config/settings.yml, spec/features/providers/allocations/edit_initial_allocation_spec.rb, spec/features/providers/allocations/repeat_allocations_spec.rb
- Providers were no longer able to view their allocations
- Changed allocation view to consume the allocation cycle rather than recruitment cycle
- Go to an accredited body with allocations (on review app, durham SCITT) and view their allocations
=> Changed allocation view to consume allocation cycle not recruitment cycle

app/views/courses/index.html.erb, app/views/providers/show.html.erb, app/views/recruitment_cycles/show.html.erb
We show a banner to prompt users to publish their courses. It had content referencing the forthcoming cycle. The cycle is now open.
Update copy now that the cycle is open.
Check the banner on:
* providers show
* courses index
=> [xxx] Update publish course reminder

app/views/providers/show.html.erb, app/views/recruitment_cycles/show.html.erb, app/views/shared/_aside_information_box.html.erb, config/settings/review.yml, spec/features/providers/index_spec.rb
- [This trello ticket](https://trello.com/c/SeceG0Hr/158-getting-ready-for-start-of-cycle-05-10-at-9am)
- Content changes on cycle and provider show pages, limited to gray sidebar
- See the content changes (removal of UCAS contact and changes to SoC text) on the gray sidebar on the Provider and Cycle show pages
=> [158] content changes for soc

app/helpers/provider_helper.rb, config/settings.yml, spec/helpers/provider_helper_spec.rb, spec/site_prism/page_objects/page/organisations/courses_page.rb
PE forms are requested via a Google form. This is linked from the course subject page and there is a different form for each year. We add the new form when we open rollover (in the 'next_cycle' settings) and then this should be transferred to the `current_cycle` when the new cycle is opened. We hadn't done that this year so it reverted back to last years form.
* Change the link for the current cycle to the 2022/23 form
* Change the name to make it more obvious what the link is
* Run the app
* Create a new secondary course
* Click the 'separate Google form' link on the subject page
* Marvel at the 2022/23 form that opens
* The forms are different for accredited bodies and non-accredited providers so we should check both
=> [xxx] Update PE course form link

app/controllers/personas_controller.rb, app/controllers/sessions_controller.rb
- [This trello ticket](https://trello.com/c/zRL3bsvg/108-bug-json-api-pundit-errors-if-you-use-back-button-on-personas-on-qa)
- Added `skip_before_action :authenticate, on: :create` to ensure that pre-populated sessions that were invalid/not ended did not contaminate the authentication process. This was done where users could "log out" but their session not destroyed, by using the back button (which loads a cached sign-in page, enabling them to log in as another user while still in an active user session)
=> [108] Skip authenticate before action on session create

app/controllers/personas_controller.rb
We recently added this to clear the persona login if the user clicks the back link onto the index page. We also need to handle when the user first arrives at the index page without a session.
* Handle session[:auth_user] being nil
=> [373] Handle nil sessions

.github/workflows/deploy.yml
Some jobs are timing out https://github.com/DFE-Digital/publish-teacher-training/runs/4250898405?check_suite_focus=true
The wait may be longer than 15 minutes if waiting for other deployments to
finish.
- Increase to 1 hour using abort-after-seconds
- Add some other options for improved reliability
Same config as Apply, TTAPI, etc
=> Increase timeout on build workflow

app/controllers/access_requests_controller.rb, app/views/access_requests/_access_request.html.erb, app/views/access_requests/confirm.html.erb, config/routes.rb, spec/features/access_requests_spec.rb, spec/site_prism/page_objects/page/organisations/confirm_access_requests_page.rb, spec/site_prism/page_objects/page/organisations/list_access_requests_page.rb
- [This trello ticket](https://trello.com/c/Ham3owQ3/367-allow-access-requests-to-be-deleted-in-the-ui)
- Enable deletion of Access Requests from the UI
- Log in as Colin
- Make an Access Request
- Go to the Access Request
- Click on view 
- Click on Delete
- See the Success Message
=> [367] Enable deletion of access requests from UI

app/views/courses/_basic_details_tab.html.erb, spec/features/courses/send/edit_spec.rb
SEND to be editable by admins after a course is published
Amended for SEND to be editable by admins after a course is published
Requires https://github.com/DFE-Digital/teacher-training-api/pull/2289
=> [365] Amended for SEND to be editable by admins after a course is published

app/helpers/new_publish_helper.rb, app/views/recruitment_cycles/_about_organisation.html.erb, config/settings.yml, config/settings/development.yml, config/settings/production.yml, config/settings/qa.yml, config/settings/review.yml, config/settings/sandbox.yml, config/settings/staging.yml, config/settings/test.yml, spec/helpers/new_publish_helper_spec.rb
This section is now present in New Publish. We can start directing users there when they click through to it.
https://trello.com/c/hqN5Z7pB
Add a helper method and feature flag so we can conditionally link to About Your Org on New Publish.
Can be tested locally — clicking the About Your Organisation link will take you to dev TTAPI (localhost:3001 by default).
Is feature flagged, so can also be tested on QA after merge.
=> Add link to About Your Org on New Publish

config/settings/staging.yml
We can now start testing the migrated About Your Organisation section on staging.
Activate the feature flag which changes the link on the provider show page.
na
=> Activate about_your_org feature on staging

app/controllers/application_controller.rb, app/controllers/providers/visas_controller.rb, app/controllers/providers_controller.rb, app/helpers/new_publish_helper.rb, config/settings/review.yml, spec/controllers/application_controller_spec.rb, spec/helpers/new_publish_helper_spec.rb
Redirects
Added redirect for the details, about, contact & visas pages to new publish
Use case along the lines of a bookmark:
-  navigate and try to force your way pass
> ie  
`/organisations/T92/2022/details`
`/organisations/T92/2022/about`
`/organisations/T92/2022/contact`
`/organisations/T92/2022/visas`
=> [0570] Added redirect for the details page to new publish

terraform/workspace_variables/qa.tfvars, terraform/workspace_variables/staging.tfvars
QA and Staging alerts are currently routed to StatusCake Contact group BAT-DevOps-Slack-All which only forwards to email.
The contact group will be changed to BAT-DevOps-Slack-Prod which will be routed to Slack, email and mobile alerts instead of just email. Email and mobile alerts are a limited subset of users.  Updated contact groups in workspace variable files for qa and staging to match production and sandbox.  
https://trello.com/c/q3F2WvuS
Do the channels match the expected channels.
=> Update StatusCake contact groups

config/settings/qa.yml
There was a syntax error in the yaml which caused an issue with the parser for the QA environment.
=> Fix yaml syntax for QA

config/settings.yml, config/settings/development.yml, config/settings/qa.yml, config/settings/staging.yml, spec/features/providers/index_spec.rb, spec/features/sites/index_spec.rb
Enables the migrated locations section to route to new publish in prod
=> Enable locations for new publish in prod

.github/workflows/build-nocache.yml, .github/workflows/build.yml, Makefile, terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf
Containers for this repo are currently published to Dockerhub. Publishing images to GitHub container registry is simpler and more secure.
This commit migrates workflows from Dockerhub to the GitHub Container Packages registry.
- Confirm that image is being published as a GitHub Container Package
- Confirm that deployment is using the correct GitHub Container Package
https://trello.com/c/wVT0QcJ4
=> Migrate to GitHub container registry

.github/workflows/smoke-test.yml, .tool-versions, Dockerfile, Gemfile, Gemfile.lock, package.json
https://trello.com/c/RjLvJulr/744-update-docker-base-image
This is to resolve security vulnerabilities in the base image
alpine, ruby and nodejs will be updated in this change
ruby:2.7.4-alpine3.12 to ruby:2.7.5-alpine3.15
nodejs 12.18.3 to 16.14.0
ruby 2.7.4p191 to ruby 2.7.5p203
check locally
check review app
=> Update docker base image to ruby:2.7.5-alpine3.15

.github/workflows/build-nocache.yml
Fix Github Container Registry login for the build-no-cache workflow.
Alter workflow to use GHCR secrets instead of Dockerhub
Run workflow against branch
=> Fix GHCR login for build-no-cache workflow

.github/workflows/build.yml
Dependabot requires it's workflow permissions to be explicitly set.
Add necessary permissions to the build workflow.
- Changes have already been successfully applied to other workflows.  Unable to test fully until merged and a dependabot PR tries to build
- NOTE: the PR build failed to authenticate with GHCR on the first attempt.  The 2nd run succeeded, both runs had `Secret source: Actions` and the same `GITHUB_TOKEN Permissions` so there's no obvious explanation for the failure.
=> Add permissions to build workflow for dependabot

terraform/modules/paas/main.tf, terraform/modules/paas/variables.tf, terraform/terraform.tf, terraform/variables.tf, terraform/workspace_variables/production.tfvars.json, terraform/workspace_variables/qa.tfvars.json, terraform/workspace_variables/sandbox.tfvars.json, terraform/workspace_variables/staging.tfvars.json
Migrating from publish to ttapi
This will remove the service.gov.uk routes after they have been added to ttapi
=> Remove service.gov.uk routes as migrated to ttapi
