DFE-Digital/publish-teacher-training

- spec/requests/api/v1/provider_spec.rb
This makes the spec more verbose but provides more explicit regression coverage
and hopefully documents the API in the process.
> Add more detail to the provider requester spec

- app/controllers/api/v1/subjects_controller.rb
- app/models/subject.rb
- app/serializers/subject_serializer.rb
- config/routes.rb
- spec/factories/subjects.rb
- spec/models/subject_spec.rb
- spec/requests/api/v1/subject_spec.rb
- spec/serializers/subject_serializer_spec.rb
Subjects
Add `/api/v1/subjects`
Visit `/api/v1/subjects`
> Add subjects endpoint

- app/serializers/course_serializer.rb
- app/serializers/site_serializer.rb
- app/serializers/site_status_serializer.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v1/provider_spec.rb
Recruitment cycle
Hardcode recruitment cycle for courses and campuses
Check for recruitment cycle in `/api/v1/courses`
> Add recruitment_cycle to course and campus

- app/controllers/api/v1/courses_controller.rb
Fetching courses generates hundreds of DB queries.
The explicit `includes` avoids the n+1 query problem and making hundreds of unnecessary requests on the database.
> Include dependent entities on courses get

- db/seeds.rb
Work with some data locally
Add seeds data
`rake db:seed` and then hit an endpoint i.e. `/api/v1/subjects`
> Add seeds data

- config/initializers/kaminari_config.rb
Pagination
Increase pagination from 25 to 100
Access any endpoint
> Increase pagination to 100 for all endpoints

- app/serializers/provider_serializer.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
Fixed `provider_type` by wiring it up
Wiring up `provider_type`
> Fixed provider type by wiring it up

- .travis.yml
- wait-for-it.sh
The sleep 5 was a race condition that ended up flaking some of our test runs.
> Add wait-for-it.sh, wait for the database to spin up in CI

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/providers_controller.rb
- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/serializers/provider_serializer.rb
- spec/factories/provider_enrichment.rb
- spec/factories/providers.rb
- spec/models/provider_spec.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
Previous attempt to display contact details for providers had a bug in it, this is a fix.
Re-did how we figure out the address info for a provider. Also added `jsonb_accessor` to try to make JSON attribute access easier.
> Fix provider contacts

- app/models/site.rb
- app/serializers/site_serializer.rb
- spec/requests/api/v1/provider_spec.rb
> Site region_code enum to increase readability

- Gemfile
- Gemfile.lock
- app/models/course.rb
- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/models/site.rb
- app/models/site_status.rb
- app/models/subject.rb
- app/serializers/course_serializer.rb
- app/serializers/provider_serializer.rb
- app/serializers/site_serializer.rb
- app/serializers/site_status_serializer.rb
- app/serializers/subject_serializer.rb
- config/routes.rb
- spec/factories/courses.rb
- spec/factories/provider_enrichment.rb
- spec/factories/providers.rb
- spec/factories/sites.rb
- spec/factories/subjects.rb
- spec/models/course_spec.rb
- spec/models/provider_spec.rb
- spec/models/site_spec.rb
- spec/models/subject_spec.rb
- spec/serializers/course_serializer_spec.rb
- spec/serializers/provider_serializer_spec.rb
- spec/serializers/site_serializer_spec.rb
- spec/serializers/subject_serializer_spec.rb
Annotate models and other files with schema information.
Add `annotate` gem and annotations to models and routes files.
> Annotate model and similar files.

- README.md
Second run didn't work for me due to stale container, so add build flag.
Add detach to explicitly background it.
> Add build and detach to readme

- app/serializers/provider_serializer.rb
- spec/factories/providers.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
Is a provider and accrediting_provider?
Add accrediting_provider data to provider endpoint
`api/v1/providers`
> Add accrediting_provider to provider

- app/models/provider.rb
- app/serializers/provider_serializer.rb
- db/schema.rb
- spec/factories/providers.rb
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
Is a provider an accrediting provider?
Use new `accrediting_provider` instead of `scitt
n/a
> Fix accrediting_provider data on provider

- Gemfile
- Gemfile.lock
- config.ru
Logging errors on Azure
Add `application_insights`
> Setup app insights

- README.md
- config/database.yml
- db/create_dev_user.sql
- docker-compose.yml
- lib/tasks/create_dev_user.rake
This keeps our DB-use isolated from other apps.
> Add an app-specific user to use when connecting to the db

- README.md
The information is kind of out there, but this makes it easier to get started.
> Readme - add how to check if your local api is working

- db/schema.rb
> Pull in updates from manage-api schema

- config/environments/production.rb
Logging
Make logging consistent across all rails apps
> Update logging for prod

- docs/api.md
> Add scheme_member to api docs

- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/models/site.rb
- app/models/site_status.rb
- app/serializers/provider_serializer.rb
- app/serializers/site_serializer.rb
- lib/tasks/annotate_schema.rake
- spec/factories/provider_enrichment.rb
- spec/factories/providers.rb
- spec/factories/sites.rb
- spec/models/provider_spec.rb
- spec/models/site_spec.rb
- spec/serializers/provider_serializer_spec.rb
- spec/serializers/site_serializer_spec.rb
Database annotations
- update annotations
- ensure we update annotations every time we run `rake db:setup` or `rake db:schema:load`
`rake db:setup`
> Add annotate task to rake

- Gemfile
- Gemfile.lock
- README.md
Enabled by (but doesn't depend on): https://github.com/DFE-Digital/bat-infrastructure/pull/97
> Configure Sentry for exception logging

- spec/serializers/course_serializer_spec.rb
Educational pairing with Misha
> Stylistic change of test

- docs/api.md
https://trello.com/c/w7kXfqpK/872-fix-datatype-for-applicationsacceptedfrom
The docs weren't updated as part of https://github.com/DFE-Digital/manage-courses-backend/pull/46.
Docs changes
> Update course_open_date docs to align it to implementation

- spec/requests/api/v1/provider_spec.rb
Prep work for incremental fetch paging.
This is a big diff so sending this off to master to avoid future rebase hell.
Pure refactor
> Spec cleanup

- app/controllers/api/v1/providers_controller.rb
- app/models/provider.rb
`changed_since` query param
Move logic from controller into model
No change
> Simplify changed_since query param

- app/models/course.rb
- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/models/site.rb
- app/models/subject.rb
- config/application.rb
Table names
singularise table names
> Amended config to default to singularise table names

- app/controllers/error_controller.rb
- config/routes.rb
- spec/controllers/error_controller_spec.rb
This is for debugging our error logging services.
> Add an error route that raises an error

- docs/api.md
To eliminate overlap with traditional paging which is to be removed.
Todo: Need to update individual call documentation.
Traditional pagination is going away after discussing with @misaka and being replaced with date+id based paging & incremental fetch
Update first section of docs with new plan.
View rendered change here https://github.com/DFE-Digital/manage-courses-backend/blob/no-paging-doc/docs/api.md
Turn off whitespace when viewing diff. Maybe use kdiff to see full diff.
> Rewrite for differential fetch plus other improvements

- docs/api.md
Domain
Replace heroku with service domain
n/a
> Update heroku url to service domain

- app/controllers/application_controller.rb
- spec/controllers/api/v1/courses_controller_spec.rb
- spec/controllers/api/v1/providers_controller_spec.rb
- spec/controllers/api/v1/subjects_controller_spec.rb
bad db connection
Added config for bad connection to be http status 503
Using production config, hence no stack trace
before 
after
> 503 for bad db connection

- app/controllers/api/v1/courses_controller.rb
- app/serializers/course_provider_serializer.rb
- app/serializers/course_serializer.rb
- config/routes.rb
- docs/api.md
- spec/requests/api/v1/course_spec.rb
Performance
- Don't render address info for the provider on the course endpoint
- Preload subjects for courses endpoint
Check for N+1's
> DB optimisation

- Dockerfile
Docker disk space
added `--no-cache`
https://github.com/DFE-Digital/manage-courses-frontend/pull/46#discussion_r
> Fixed no-cache so that disk space is not used needlessly

- app/models/provider.rb
- spec/requests/api/v1/provider_spec.rb
Duplicated provider that was exhibited in json response
Fixed duplicated provider that was exhibited in json response
> Fixed duplicated provider that was exhibited in json response

- azure-pipelines.yml
> Build versioning

- app/serializers/provider_serializer.rb
- docs/api.md
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
Additional provider contact info
Add `email`, `contact_name` and `telephone`
`/api/v1/providers`
> Add contact info to provider

- db/schema.rb
I don't know if this is likely to cause issues, I don't entirely understand all the changes
I guess for review we need to make sure it works from clean.
> Update schema from sanitized prod export

- .travis.yml
- Gemfile
- README.md
Linting
Lint `Gemfile`
`$ bundle exec govuk-lint-ruby app config db lib spec Gemfile --format clang`
> Extend linting and correct gemfile

- app/controllers/api/v2/application_controller.rb
- app/controllers/api/v2/courses_controller.rb
- app/models/course.rb
- app/models/provider.rb
- app/models/site_status.rb
- app/serializers/api/v2/course_serializable.rb
- config/routes.rb
- spec/factories/site_statuses.rb
- spec/models/course_spec.rb
- spec/models/site_status_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/serializers/api/v2/course_serializable_spec.rb
Paired with @defong on this.
Course API needed for rendering course summary info in Publish.
Followed the patterns in #115.
> [950] Courses api v2

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/application_controller.rb
- app/controllers/api/v2/application_controller.rb
- app/controllers/api/v2/courses_controller.rb
- app/controllers/api/v2/users_controller.rb
- app/controllers/application_controller.rb
- app/models/provider.rb
- app/policies/provider_policy.rb
- app/policies/user_policy.rb
- config/application.rb
- spec/config/application_spec.rb
- spec/controllers/api/v2/application_controller_spec.rb
- spec/models/provider_spec.rb
- spec/policies/provider_policy_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/requests/api/v2/users_spec.rb
To prevent unauthorised publishers inadvertently gaining access to other publishers' data.
Introduce [Pundit](https://github.com/varvet/pundit), a commonly used authorisation framework and apply it to all `v1` and `v2` endpoints.
> [997] Authorisation with pundit

- README.md
- azure-pipelines.yml
Final steps to prepare for the az pipelines switch over
* Include all branches and not PRs
* Update build badge
* Check build badge
* Check if you are happy with the build config
> Azure Piplines config for master

- azure/template.json
This PR aligns ARM template conventions with our guidelines and preferred styles
* Update template variables
* Add resourceEnvironment and serviceName parameters
> align conventions

- README.md
- app/controllers/api/v2/application_controller.rb
- config/puma.rb
- docker-compose.yml
Post collision with its client, since client port change has external factors involved, its done here instead.
Amended default port to be used from 3000 to 3001
Client should now be in a position to be seeded with default values for development.
Soon rather than later it be nice to have the 2 rails chatting with one and another.
> [1036] Amended default port to be used from 3000 to 3001

- config/routes.rb
- spec/requests/api/v2/session_spec.rb
Correctiveness for sessions routing
Correctiveness for sessions specs
Corrected the sessions routing
Corrected the sessions specs
Being corrective.
> [993] Flushing out issues, routes and specs

- db/migrate/20190227124613_initialize_provider_changed_at.rb
- db/schema.rb
the ucas api relies on unique values for paging.
Copying data from provider.updated_at.
Consider alternative methods such as https://github.com/ilyakatz/data-migrate
> [1042] Initialized provider.changed_at

- app/models/provider.rb
- app/serializers/provider_serializer.rb
- docs/api.md
- spec/requests/api/v1/provider_spec.rb
`recruitment_cycle`
Add `recruitment_cycle` to the v1 providers endpoint
`/api/v1/providers`
> Add recruitment_cycle to providers

- azure/template.json
Aligning app settings with legacy dev
Add settings authentication secret
Pre merge tasks
> Added auth secret

- db/migrate/20190306122110_initialize_course_changed_at.rb
- db/schema.rb
Paging doesn't work without unique values.
Make values unique as per updated_at
:ship:
> [1052] Migration to set course.changed_at from updated_at

- Gemfile
- Gemfile.lock
- app/controllers/api/v2/courses_controller.rb
- app/models/provider.rb
- config/routes.rb
- Provider code as URL
- Add `friendly_id` to use the `provider_code` as the slug inside of the `id`
> Clean up hacky routes

- app/controllers/api/v2/providers_controller.rb
- spec/requests/api/v2/providers_spec.rb
`provider#show`
- Add providers show endpoint
`/api/v1/providers#{provider_code}`
> [1096] Add  provider show end point

- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/serializers/provider_serializer.rb
- spec/factories/providers.rb
- spec/models/provider_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
API::V1 contact details
Ensure we use provider enrichment data for `telephone` and `email` as well as the address data
> [1141] fix contact details

- app/controllers/api/v2/providers_controller.rb
- app/serializers/api/v2/serializable_provider.rb
/organisations
preload `courses` on `organisations`
/organisations
Before
`Completed 200 OK in 1323ms (Views: 948.1ms | ActiveRecord: 333.4ms)`
After
`Completed 200 OK in 805ms (Views: 739.2ms | ActiveRecord: 62.4ms)`
> Optimise count for org#index courses

- app/controllers/api/v2/courses_controller.rb
- app/policies/course_policy.rb
- app/serializers/api/v2/serializable_course.rb
- app/serializers/api/v2/serializable_site.rb
- app/serializers/api/v2/serializable_site_status.rb
- config/routes.rb
- spec/policies/course_policy_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/serializers/api/v2/serializable_site_spec.rb
- spec/serializers/api/v2/serializable_site_status_spec.rb
vacancy info on courses api v2
Exposed vacancy info on courses api v2
Paired with @heidar
> 1137 expose vacancy info on courses api v2

- db/seeds.rb
- spec/factories/courses.rb
- spec/factories/site_statuses.rb
- spec/requests/api/v2/providers/courses_spec.rb
Small fixes pulled out of #196 to make it smaller.
> [1131] Small seeds and specs fixes

- app/controllers/api/v2/courses_controller.rb
- app/policies/course_policy.rb
- spec/policies/course_policy_spec.rb
policy for updating course
Added policy for updating course
As long as the user has access to the course, for example to view it, then inherently they can update it as well.
> 1131 add policy for updating course

- app/models/site_status.rb
- spec/factories/courses.rb
- spec/factories/site_statuses.rb
- spec/models/course_spec.rb
- spec/models/site_status_spec.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
An alternative approach to #196.
Add validation to site statuses and fix the specs/factories that break as a result.
> [1131] Alternative implementation of site status validation

- app/models/provider.rb
- app/models/provider_ucas_preference.rb
- config/initializers/inflections.rb
- db/migrate/20190319163755_add_provider_ucas_preferences.rb
- db/schema.rb
- spec/factories/provider_ucas_preferences.rb
- spec/factory_specs/provider_ucas_preferences_spec.rb
- spec/models/provider_spec.rb
- spec/models/provider_ucas_preference_spec.rb
https://trello.com/c/1R5mTZjg/1172-provider-preferences-modify-provider-model
Adding support for provider UCAS preferences as per ticket.
Add migration and model for ProviderUCASPreference objects
> [1172] add ucas preferences to providers

- app/models/contact.rb
- app/models/provider.rb
- db/migrate/20190320144534_create_contact.rb
- db/schema.rb
- spec/factories/contacts.rb
- spec/factory_specs/contacts_spec.rb
- spec/models/contact_spec.rb
- spec/models/provider_spec.rb
https://trello.com/c/XanBgbYi/1177-provider-contacts-add-model-migrations
Adding support for provider UCAS contacts as per ticket.
Add migration and model for Contact objects
> [1177] add contacts for providers

- app/controllers/api/v2/courses_controller.rb
- spec/requests/api/v2/providers/courses_spec.rb
Course#show endpoint
- Courses should be found by provider
- Course code should be found by upcase
> [1206] Fix courses show endpoint

- config/database.yml
- config/environments/qa.rb
- config/environments/staging.rb
- config/settings/qa.yml
- config/settings/staging.yml
Proper environments i.e. `staging` and `qa` (for https://bat-dev-manage-courses-backend-app.azurewebsites.net/)
- Add `{staging, qa}.rb` - duplicates of `production.rb`
- Add settings for `staging` and `qa`
`bin/rails server -e staging`
`bin/rails server -e qa`
> Setup proper staging and qa environment

- app/models/course.rb
- app/serializers/api/v2/serializable_course.rb
- spec/models/course_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/serializers/api/v2/serializable_course_spec.rb
> [1210] Add ucas_status on course model and expose on serializer

- config/database.yml
- config/environments/ucas.rb
- config/settings/ucas.yml
https://trello.com/c/c0ttiADR/1256-add-ucas-rails-environment-to-mc-be
The UCAS environment  is running in `development`. We want this env to run like the others with it's own `RAILS_ENV` so that we can configure parts of it in the app itself.
Add a ucas rails env.
> [1256] add ucas rails env

- app/models/subject.rb
- app/serializers/api/v2/serializable_course.rb
- app/serializers/api/v2/serializable_subject.rb
- spec/factories/courses.rb
- spec/requests/api/v2/providers/courses_spec.rb
The option to include subjects on the course endpoint
Add subjects serializer and add to course endpoint 
`providers/XXX/courses/XXX?include=subjects`
> [1300] Add subjects to courses

- app/models/course.rb
- app/serializers/api/v2/serializable_course.rb
- spec/factories/courses.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/serializers/api/v2/serializable_course_spec.rb
We need to expose additional fields for use in the frontend.
- Add funding field
🚢
> [1314] Add funding field to courses

- app/models/user.rb
- spec/models/user_spec.rb
Follow up to https://github.com/DFE-Digital/manage-courses-backend/pull/259
Add auditing to the `User` model
> [1279] Audit user model

- app/models/course.rb
- app/serializers/api/v2/serializable_course.rb
- spec/factories/site_statuses.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/serializers/api/v2/serializable_course_spec.rb
We're exposing more course information for the courses show view.
- Add applications_open_from to course data
🚢
> [1315] Add applications_open_from to course data

- app/services/subject_mapper.rb
Subject of pain
A course related subjects can only fall in 1 of 3 subject level
Make it less deadly
Nothing breaks
> [1327] Expose course level info in SubjectMapper

- spec/serializers/api/v2/serializable_course_spec.rb
- spec/services/subject_mapper_spec.rb
Bad english
Better english
`regression test` skipped test that broke it to allow for a later fix
> [xxxx] Master was broken due to bad English

- app/controllers/api/v2/courses_controller.rb
- app/models/user.rb
- app/policies/course_policy.rb
- config/routes.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
Stub implementation of publishing.
This is enough for frontend to build on. The data modification is to
follow.
The request spec is a duplication of the sync spec as the same
constraints apply.
> [1305] Publish endpoint for courses

- Gemfile
- Gemfile.lock
- app/controllers/api/v2/users_controller.rb
- app/models/user.rb
- app/policies/user_policy.rb
- app/serializers/api/v2/serializable_user.rb
- config/application.rb
- config/routes.rb
- db/data/20190418114011_initialise_state_for_users.rb
- db/data_schema.rb
- db/migrate/20190416093524_add_aasm_state_to_users.rb
- db/migrate/20190418114021_change_aasm_state_default_and_nullable_on_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
- spec/requests/api/v2/session_spec.rb
- spec/requests/api/v2/users/accept_transition_screen_spec.rb
- spec/requests/api/v2/users_spec.rb
- spec/serializers/api/v2/serializable_user_spec.rb
This is more or less a fork of https://github.com/DFE-Digital/manage-courses-backend/pull/274.
- Implements the state machine pattern on the users model, with initial states around the users `transitioned`
> [1251] Implement state machine for user, add transitioned state

- Dockerfile
This will allow it to run in the pipeline.
> [1332] Add data migrate to docker setup

- config/initializers/filter_parameter_logging.rb
> [1356] Filter out sensitive parameters from DfE Sign-in

- spec/factories/users.rb
- spec/requests/api/v2/users_spec.rb
Got strung by a Smithy
https://travis-ci.org/DFE-Digital/manage-courses-backend/builds/523905764?utm_source=github_status&utm_medium=notification
Make it user under test have unique user info
> [xxxx] Fixed Mr Lottery

- app/models/contact.rb
- app/models/provider_ucas_preference.rb
- app/serializers/contact_serializer.rb
- spec/factories/contacts.rb
- spec/factories/provider_ucas_preferences.rb
- spec/models/contact_spec.rb
- spec/models/provider_ucas_preference_spec.rb
- spec/serializers/contact_serializer_spec.rb
Something changed, this happens on my and Tim's machine every time we run `rake`.
Ran `rake`, updated annotations generated.
> Update annotations from bigint(8) to bigint

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Guardfile
- README.md
This allows us to automatically run rspec on files that have changed.
This runs pretty slowly, about 3 seconds for a model spec with 2 assertions. Suggestions welcome on how to improve this.
> [1400] Add guard

- app/controllers/api/v2/courses_controller.rb
- app/controllers/api/v2/sites_controller.rb
- app/models/course.rb
- app/models/course_enrichment.rb
- app/validators/word_count_validator.rb
- app/validators/words_count_validator.rb
- spec/factories/course_enrichments.rb
- spec/factories/courses.rb
- spec/models/course/is_fee_based_spec.rb
- spec/models/course/publishable_spec.rb
- spec/models/course_enrichment_spec.rb
- spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
- spec/validators/words_count_validator_spec.rb
General validation of Pub
Added Pub checking based on the csharp counterpart
mandatory fields, word count, numerical input
Clueless for nested enrichment validation.
borrowed concept from https://www.justinweiss.com/articles/a-lightweight-way-to-handle-different-validation-situations/
> 1310 valid pubbing

- config/database.yml
- config/environments/new_qa.rb
- config/settings/new_qa.yml
Add new QA env and config to support readiness testing
Addition of various configs to support new_qa
> Add newqa env

- .github/PULL_REQUEST_TEMPLATE.md
Checklist for the things we need to do when opening a PR. Less stuff to remember, just follow the checklist.
Added checklist.
Feel free to add to this, I couldn't think of anything else.
> Update pull request template to have checklist

- db/seeds.rb
Without this it's hard to test the support app being able to action them
while connected to local development backend app.
> [1363] Add seeds for access request table

- .travis.yml
- README.md
- lib/tasks/code_climate.rake
Seeing test coverage in code climate (https://docs.codeclimate.com/docs/travis-ci-test-coverage)
Add code climate ID and reports score through simplecov
n/a
> [XXXX] setup test coverage for code climate

- README.md
> [XXXX] Fix readme code climate badges

- azure-pipelines.yml
- docker-compose.az.yml
Fixes issue communicating with Docker Hub
Update build to use more Docker tasks
Add new env var
> Update build tasks

- azure/template.json
Align ARM template with FE
Add default value to keyVaultName so it becomes an optional parameter
> Align keyVaultName req with FE

- config/locales/en.yml
- spec/requests/api/v2/providers/courses/publish_spec.rb
> [1310] Fix validation messages for course enrichments

- app/controllers/api/v2/sites_controller.rb
- spec/requests/api/v2/providers/sites_spec.rb
Adding new locations.
This stop the backend from blowing up and instead sending down the validation errors.
> [1496] Use site.save instead of save! when creating

- azure-pipelines.yml
- docker-compose.az.yml
Reduce build time by implementing layer caching
Add task to push master builds as latest tags
Add task to pull latest tag for each build
> Implement layer caching

- lib/mcb/commands/users/list.rb
#384 introduced some linting breakages but the Travis build wasn't failing.
Correct the linting violations.
> [1502] Fix linting

- app/serializers/search_and_compare/course_serializer.rb
- spec/serializers/search_and_compare/course_serializer_spec.rb
- spec/serializers/search_and_compare/mappings.yaml
- spec/serializers/search_and_compare/test_data.json
search and compare serialiizer part 2
Changed the json to a different course that will exercise more touch points
Extracted the json and hardcoded to tests (address part 1 PR feedback)
Added default salary mapping (value is not in used by is still serialized)
part 2 ot x
FYI 
Part 1
> 1429 snc serializer part 2

- spec/models/course_spec.rb
https://dfe-ssp.visualstudio.com/Become-A-Teacher/_build/results?buildId=8381&view=ms.vss-test-web.build-test-results-tab
> [1514] Fix spec that's failing on VSTS

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/courses_controller.rb
- app/controllers/api/v1/providers_controller.rb
- app/controllers/api/v2/providers_controller.rb
- app/models/course.rb
- app/models/course_subject.rb
- app/models/subject.rb
- config/environments/test.rb
- spec/models/course_spec.rb
- spec/models/subject_spec.rb
- spec/spec_helper.rb
We should add bullet and stomp out any n+1 queries before our app gets too big.
* Add bullet
* Fix anything raised by bullet
> [1515] Add bullet and fix n+1 queries

- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/serializers/api/v2/serializable_provider.rb
- spec/requests/api/v2/providers_spec.rb
`course#preview`
Expose provider contacts on provider endpoint
Example - `/api/v2/providers/2AT`
> 1503 expose provider contacts

- app/controllers/api/v2/access_requests_controller.rb
- app/models/access_request.rb
- app/policies/access_request_policy.rb
- config/routes.rb
- spec/models/access_request_spec.rb
- spec/policies/access_request_policy_spec.rb
- spec/requests/api/v2/access_request_spec.rb
This is needed by the support app.
> [1367] Add show endpoint to access requests

- app/controllers/api/v2/providers_controller.rb
- config/environments/test.rb
- spec/requests/api/v2/providers_spec.rb
Publish users can't currently load the page.
Before:
```
Completed 200 OK in 13733ms (Views: 12721.4ms | ActiveRecord: 985.5ms)
Completed 200 OK in 13739ms (Views: 12755.9ms | ActiveRecord: 981.3ms)
Completed 200 OK in 13950ms (Views: 12982.5ms | ActiveRecord: 965.6ms)
Completed 200 OK in 15763ms (Views: 14690.1ms | ActiveRecord: 1071.0ms)
Completed 200 OK in 14026ms (Views: 13031.5ms | ActiveRecord: 993.1ms)
```
After:
```
Completed 200 OK in 658ms (Views: 582.9ms | ActiveRecord: 48.9ms)
Completed 200 OK in 877ms (Views: 834.7ms | ActiveRecord: 40.8ms)
Completed 200 OK in 580ms (Views: 537.7ms | ActiveRecord: 41.2ms)
Completed 200 OK in 504ms (Views: 459.9ms | ActiveRecord: 42.0ms)
Completed 200 OK in 913ms (Views: 869.3ms | ActiveRecord: 42.5ms)
```
> [1529] Fix providers index n+1 query 

- app/serializers/search_and_compare/course_serializer.rb
- spec/factories/courses.rb
- spec/serializers/search_and_compare/course_serializer_spec.rb
- spec/serializers/search_and_compare/mappings.yaml
search and compare serialiizer part 4
site/campus and related touch points
Added course sites serializer
Added application open date
Added has vacanies
Its going to get mess from henceforth, PR to make it better is welcome
part 4 ot x
FYI 
Part 1
Part 2
https://github.com/DFE-Digital/manage-courses-backend/pull/387
Part 3
https://github.com/DFE-Digital/manage-courses-backend/pull/390
> [1429] snc serializer part 4

- app/models/course.rb
- app/models/dfe_subject.rb
- app/serializers/api/v2/serializable_course.rb
- spec/models/dfe_subject_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
Extend course financial support
- Add `has_early_career_payments`
- Add `bursary_amount`
- Add `scholarship_amount`
Example -`/api/v2/providers/1CS/courses/2DH4`
> [1483] Add early_career_payments to course endpoint

- app/controllers/api/v2/courses_controller.rb
- app/deserializers/api/v2/deserializable_course.rb
- config/routes.rb
- spec/requests/api/v2/providers/courses/update_spec.rb
Frontend sends us data to update a course (or the enrichment rather)
Update endpoint for courses.
> [1464] Add course update

- azure/template.json
- config/settings.yml
- config/settings/new_qa.yml
- config/settings/production.yml
- config/settings/qa.yml
- config/settings/staging.yml
Manage backend and search and compare communication and credentials
Added search and compare communication and credentials to manage backend
Similar to `SETTINGS__MANAGE_API__SECRET`
related to 
https://github.com/DFE-Digital/bat-infrastructure/pull/132
> [1489] Added settings for search api on manage backend

- lib/mcb.rb
We're switching over to use a new QA environment (that's managed by VSTS).
Update `mcb` to connect to the new environment instead of the Travis-managed one.
> [XXX] Update the QA environment config for MCB

- config/database.yml
- config/environments/new_staging.rb
- config/settings/new_staging.yml
Add config bits for new staging env
Add config for database and rails env
> Add new staging env and settings

- spec/factories/providers.rb
- spec/models/provider_spec.rb
- spec/models/site_spec.rb
- spec/policies/site_policy_spec.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/requests/api/v2/providers/sites_spec.rb
- spec/requests/api/v2/providers_spec.rb
- spec/serializers/provider_serializer_spec.rb
We've decided to remove dependencies from the factories where possible. This PR removes site_count from the provider factory.
- Removes site_count from the provider factory.
> 1460 Remove site count from provider factory

- spec/models/course_spec.rb
Test is flaking on master due to a site create list hitting the site model validation which checks for duplicate site code.
Change create list to a build list.
> [1460] Fix flaking test

- Gemfile.lock
I removed this dependency, but forgot to commit the lockfile.
> [XXXX] Run bundle

- spec/factories/provider_enrichments.rb
- spec/factories/providers.rb
- spec/factory_specs/providers_spec.rb
- spec/models/course_spec.rb
- spec/requests/api/v2/providers_spec.rb
Provider and provider enrichments factories usage
Amended the usage of the provider and provider enrichments
> [1460] Amended the usage of the provider and provider enrichments

- spec/factories/course_enrichments.rb
- spec/factories/courses.rb
- spec/factory_specs/course_spec.rb
- spec/models/course/publish_enrichments_spec.rb
- spec/models/course/publishable_spec.rb
- spec/requests/api/v2/providers/courses/publish_spec.rb
- spec/requests/api/v2/providers/courses/sync_with_search_and_compare_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
Pull request no. 5 to clean up the associations in our factories. This PR removes with_course_enrichments from the course factory.
- Remove with_course_enrichments from the course factory
> 1460 Course enrichment factory issues

- app/models/recruitment_cycle.rb
- db/migrate/20190619114150_create_recruitment_cycle.rb
- db/schema.rb
- spec/factories/recruitment_cycles.rb
- spec/models/recruitment_cycle_spec.rb
Rollover 🎉 
Add recruitment cycles to our database
```
$ bundle exec rails c
$ RecruitmentCycle.create(year: '2019', application_start_date: Date.today, application_end_date: Date.today + 30)
$ RecruitmentCycle.last
```
> [1420] Setup db for recruitment cycles

- app/serializers/search_and_compare/course_serializer.rb
- spec/serializers/search_and_compare/course_serializer_spec.rb
Sau has previously opened #440. I'm splitting this will be split into 3 separate PR's
This PR covers changes he made to the serialiser
- Makes the serialiser more robust. 
- Moar tests
> 1489 Refactor search and compare serialiser

- app/controllers/api/v2/courses_controller.rb
- app/models/course.rb
- app/models/course_enrichment.rb
- spec/models/course_spec.rb
- spec/requests/api/v2/providers/courses/update_spec.rb
course enrichment subsequent draft
course enrichment subsequent draft
using data from previous published enrichment
This is probably going to be clone/inspiration for provider enrichment as well
> [1627] Added course enrichment subsequent draft

- README.md
Pairing on support with @davidgisbey 
Cold start on new machine revealed missing dependency.
Add to readme
:ship:
> readme - mcb dependencies

- app/services/search_and_compare_api_service.rb
- spec/services/search_and_compare_api_service_spec.rb
Rebased off of #507 ** Do not merge until first PR has been merged **
Adds in the search and compare service that Sau has created.
> 1489 Add search and compare service

- lib/mcb.rb
Sometimes we use a different email in different environments.
Add `--email` option to the remote connection options.
> [1663] add --email option to mcb

- db/data/20190619144634_add_2019_recruitment_cycle_to_courses.rb
This make the update succeed in <1s (versus ~120s when using AR updates)
Issue caught in product review, so this is a tweak to what's already in master.
> [1640] use raw SQL when updating recruitment_cycle on courses

- app/models/course.rb
- app/serializers/course_serializer.rb
- db/migrate/20190620060536_set_recruitment_cycle_to_not_null.rb
- db/schema.rb
- spec/factories/courses.rb
- spec/models/course_spec.rb
- spec/serializers/course_serializer_spec.rb
Rollover 🎉 
`recruitment_cycle` cannot be null on `courses`
Try and create a course without a recruitment cycle
> 1640 recruitment cycle not null for courses

- app/models/site.rb
- app/serializers/site_serializer.rb
- db/migrate/20190621125905_set_site_recruitment_cycle_to_not_null.rb
- db/schema.rb
- spec/factories/sites.rb
- spec/models/site_spec.rb
- spec/serializers/site_serializer_spec.rb
Rollover 🎉 
`recruitment_cycle` cannot be null on `sites`
Try and create a site without a recruitment cycle
> [1558] Make recruitment cycle not null for sites

- app/models/concerns/allocations_report.rb
*!!! This PR depends on #528 which needs to be merged before this one is !!!*
When generating the subject allocation request report, we need to output one line per subject being requested.
> [AL-6] Generate a separate report line for each course subjects

- app/models/allocation_request.rb
- app/models/allocation_request_collection.rb
- app/models/concerns/allocations_report.rb
- app/models/course.rb
- app/models/nctl_organisation.rb
- app/models/organisation.rb
- app/models/provider.rb
- lib/mcb/commands/nctl/map_urn_to_ukprn.rb
- lib/tasks/comparison.rake
- spec/factories/nctl_organisations.rb
- spec/models/allocation_request_spec.rb
We need the ability to generate different types of allocation reports based on current cycle courses.
- handle mapping URN to UKPRN
- handle most NCTL organsations
> [1670 per provider allocation requests

- db/data_schema.rb
- db/migrate/20190619132129_create_recruitment_cycles.rb
- db/migrate/20190619144634_add_2019_recruitment_cycle_to_courses.rb
- db/migrate/20190620121519_add_2019_recruitment_cycle_to_sites.rb
Broken forward motion due to required mandatory historical data changes
Before this PR left hand and right hand not working in sync.
Fixed broken forward motion due to required mandatory historical data changes
https://github.com/DFE-Digital/manage-courses-backend/pull/506#discussion_r295655977
> [1673] Fixed broken forward motion due to required mandatory historical data changes

- spec/models/subjects/course_level_spec.rb
Dirty code
Clean code
:shipit:
> Fixed linter issues

- lib/mcb.rb
Useful for product reviewing changes to the api
Show response headers & body in verbose mode
bundle exec bin/mcb apiv1 courses list -E qa -v
> [1645] mcb - Add raw response to verbose course list output

- app/serializers/api/v2/serializable_course.rb
- app/serializers/api/v2/serializable_site.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/requests/api/v2/providers/sites_spec.rb
Recruitment cycle year
Expose Recruitment cycle year on v2 API
Courses endpoint with sites included
> [1707] Expose recruitment cycle year on v2 api

- app/serializers/api/v2/serializable_course.rb
- app/serializers/api/v2/serializable_site.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/requests/api/v2/providers/sites_spec.rb
V2 Recruitment Cycle
Rename `recruitment_cycle` to `recruitment_cycle_year`
🚢
> [1706] update recruitment_cycle to recruitment_cycle_year

- config/database.yml
- config/settings/new_prod.yml
Add config bits for new production env
Add config for database and rails env
- updated database.yml file
- created config/settings/new_prod.yml file
> Added new production environment in .yml files

- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/serializers/api/v2/serializable_provider.rb
- spec/factories/provider_enrichments.rb
- spec/models/provider_enrichment_spec.rb
- spec/requests/api/v2/providers_spec.rb
Support https://github.com/DFE-Digital/manage-courses-frontend/pull/458
Extend provider endpoint for frontend features
🚢
> [1769] Support provider enrichments on frontend

- README.md
I had a little trouble setting up, this should avoid that in future.  
Mention the need to start PostgreSQL.
> [1778] Add setup info for Linux

- Gemfile
- Gemfile.lock
- app/models/course.rb
- app/models/course_enrichment.rb
- app/models/provider.rb
- app/models/recruitment_cycle.rb
- app/models/site.rb
- lib/mcb/commands/courses/list.rb
- lib/mcb/commands/providers/list.rb
- lib/mcb/commands/providers/rollover.rb
- lib/mcb/render.rb
- lib/mcb/render/apiv1.rb
- spec/factories/providers.rb
- spec/lib/mcb/commands/courses/list_spec.rb
- spec/lib/mcb/commands/providers/audit_spec.rb
- spec/lib/mcb/commands/providers/edit_spec.rb
- spec/lib/mcb/commands/providers/list_spec.rb
- spec/lib/mcb/commands/providers/rollover_spec.rb
- spec/lib/mcb/commands/providers/show_spec.rb
- spec/lib/mcb/commands/providers/sync_to_find_spec.rb
- spec/lib/mcb/commands/providers/touch_spec.rb
- spec/models/course_spec.rb
- spec/models/provider_spec.rb
- spec/models/site_spec.rb
- spec/policies/recruitment_cycle_policy_spec.rb
- spec/requests/api/v1/provider_spec.rb
Need to copy the things.
Copy the things.
Currently based off of 1564-attach-recruitment-cycle-to-provider. Once that branch is merged to master, this should be rebased onto master.
> [1730] add mcb rollover command

- app/controllers/api/v2/courses_controller.rb
- spec/requests/api/v2/providers/courses/publish_spec.rb
Usefully useless error message
Usable error message 
:shipit:
> [1801] Add information to course sync errors

- app/serializers/provider_serializer.rb
- spec/lib/mcb/commands/apiv1/providers/find_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/serializers/provider_serializer_spec.rb
Reverts DFE-Digital/manage-courses-backend#635  
Needed to wait on merging this PR
> Revert "[1826] Fix mismatch between api v1 docs and api v1 implementation"

- app/models/edit_course_options.rb
- app/serializers/api/v2/serializable_course.rb
- spec/models/edit_course_options_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
- Expose to send to frontend
- Show different options for FE courses
https://bat-design-history.herokuapp.com/find-teacher-training/fe-and-pgde
> [1711] Expose qualification options

- app/controllers/api/v2/providers_controller.rb
- app/deserializers/api/v2/deserializable_provider.rb
- app/models/provider.rb
- app/models/provider_enrichment.rb
- app/serializers/api/v2/serializable_provider.rb
- app/serializers/api/v2/serializable_provider_enrichment.rb
- config/routes.rb
- spec/deserializers/api/v2/deserializable_provider_spec.rb
- spec/factories/provider_enrichments.rb
- spec/models/provider_enrichment_spec.rb
- spec/models/provider_spec.rb
- spec/requests/api/v2/providers/update_spec.rb
- spec/requests/api/v2/providers_spec.rb
Add provider enrichments via update endpoint
Ability to add provider enrichments via update endpoint
> 1782 add provider enrichment update

- spec/requests/api/v2/providers_spec.rb
The request provider spec can be tidier
Tidying up provider request spec, mostly around let blocks and repeated code
> 1808 refactor provider request spec

- app/controllers/api/v2/courses_controller.rb
- app/deserializers/api/v2/deserializable_course.rb
- app/models/edit_course_options.rb
- spec/requests/api/v2/providers/courses/update_age_range_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
Course basic detail editing
Editing age range (in years)
🚢 
P.S. Thanks for kicking this off @fofr 😍
> [1847] Editing age range

- app/models/provider_enrichment.rb
I accidentally added this when I refactored something in this area.
> [1851] Remove validation for provider enrichment address2

- lib/mcb.rb
- spec/bin/mcb_spec.rb
It's a lot easier to just hit up a few times than try to remember and type out a command.  
Add a history file to `~/.mcb_history` which can be loaded.
> [1733] Add persistent history to MCB

- bin/mcb
> Fixed Rubocop issue

- app/controllers/api/v2/providers_controller.rb
- app/models/provider_enrichment.rb
- spec/models/provider_enrichment_spec.rb
PR feedback. https://github.com/DFE-Digital/manage-courses-backend/pull/680#pullrequestreview-270891556
Pairing.
* Set `provider_enrichment.provider_code` in model hook instead of controller.
:ship:
> [1903] Refactor provider_enrichment hook

- app/controllers/api/v2/access_requests_controller.rb
- app/deserializers/api/v2/deserializable_access_request.rb
- app/models/access_request.rb
- config/locales/en.yml
- db/seeds.rb
- spec/requests/api/v2/access_request_spec.rb
These will be used by the frontend for the request access flow.
Add validations to model and test them using a request spec.
:ship: Hide whitespace when reviewing.
Paired with Sau.
> [1908] Add validations to access request

- app/controllers/api/v2/providers_controller.rb
- spec/requests/api/v2/providers/update_accrediting_providers_spec.rb
Was going thro to flush out weirdness
Nothing found
Added more tests as side benefits 
:ship:
> [1933] More tests on updating accrediting providers

- app/models/course.rb
- spec/requests/api/v2/providers/courses/update_application_open_from.rb
Small PR to refactor the validations for applications_open_from to use the current recuritment cycle's start and end dates.
> [1856] Refactor validations for applications_open_from

- app/models/recruitment_cycle.rb
- db/migrate/20190815095339_change_application_start_and_end_date_to_not_null.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/recruitment_cycles.rb
- spec/models/recruitment_cycle_spec.rb
The update applications open logic is reliant on these columns being populated.
> [1856] Set application start and end date to not null

- app/models/concerns/courses/edit_options.rb
- app/models/concerns/courses/edit_options/age_range_concern.rb
- app/models/concerns/courses/edit_options/entry_requirements_concern.rb
- app/models/concerns/courses/edit_options/qualification_concern.rb
- app/models/concerns/courses/edit_options/start_date_concern.rb
- app/models/concerns/courses/edit_options/study_mode_concern.rb
- app/models/concerns/courses/edit_options/study_mode_options.rb
- spec/requests/api/v2/providers/courses_spec.rb
Study mode
Add study mode to course edit options meta
🚢
> [1899] Add study mode to course edit options

- db/migrate/20190816111150_unique_org_access.rb
- db/schema.rb
* No bad data in prod
* Working on admin user, this constraint is now relevant
* Missing unique index on org_user
:ship:
> [1996] Add unique constraint to organisation_user

- azure/template.json
Due to the changes added in #727 - the azure template needs to be updated
**the variables will still need to be added to the azure pipeline**
- Adds the environment variables to the azure template
> [1947] Add env variables to azure template

- app/models/organisation.rb
- app/models/organisation_user.rb
- app/models/user.rb
- spec/models/organisation_spec.rb
- spec/models/organisation_user_spec.rb
- spec/models/user_spec.rb
Give the mcb tool the ability to add/update/remove god access (i.e. access to all organisations). This can be added as an option to the existing `mcb user grant/revoke` command.
> 1865 audit org user

- app/models/course.rb
- config/locales/en.yml
- spec/models/course/publishable_spec.rb
- spec/requests/api/v2/providers/courses/publish_spec.rb
- spec/requests/api/v2/providers/courses/publishable_spec.rb
We shouldn't allow publishing courses without at least one site
Add validation with message, update specs
:shipit:
> [2007] Validate that a course has sites before publishing

- config/database.yml
This is for the new environment that we are deploying tonight.
> [1755] Add prod section to database.yml

- config/settings/production.yml
New URLs to work for the new prod, and any prod, environment.
> update hostnames of manage and search apis for new-prod

- .gitignore
> [xxxx] Added IDE items to be ignored

- spec/requests/api/v2/recruitment_cycle_spec.rb
* Currently diff is truncated so can't see where the problem is.
* https://github.com/DFE-Digital/manage-courses-backend/commit/02b61bd63d59a8ee3816ce791f99a00af663d019
* https://dfe-ssp.visualstudio.com/Become-A-Teacher/_build/results?buildId=20565&view=ms.vss-test-web.build-test-results-tab
* Use equal in flapping test for better output
:ship: if the test still passes
Note that  match_array copes with differences in ordering but I don't
think that matters.
> [2120] Use equal in flapping test for better output

- app/controllers/api/v2/providers_controller.rb
- app/deserializers/api/v2/deserializable_provider.rb
- spec/requests/api/v2/providers/update_ucas_contacts_spec.rb
Providers needs to be able to update their UCAS contacts
- Add the five UCAS contacts to provider #update
> [2099] Update UCAS contacts

- config/environments/new_qa.rb
- config/environments/new_staging.rb
> [XXXX] Delete legacy environment files

- app/controllers/api/v2/users_controller.rb
- app/policies/user_policy.rb
- config/routes.rb
- spec/requests/api/v2/users/accept_terms_spec.rb
Not implemented in Rails... until now
TDD an endpoint into existence
:ship:
> [2117] Add accept terms endpoint

- azure/template.json
- Added an app setting to fix deployment failures during swap slots operation 
- Added a new parameter for sentry DSN for Azure Container Instance
New app settings for MCBE app service with value 0
WEBSITE_SLOT_POLL_WORKER_FOR_CHANGE_NOTIFICATION
Renamed parameter sentryDSN to sentryDSNBackend
Added new parameter sentryDSNBGFindSync
Updated app settings with new sentryDSN parameters
> [143] Added env variable to fix swap slot + sentryDSN parameters for ACI

- app/models/course.rb
- app/models/course_subject.rb
- app/models/subject.rb
- app/models/subjects/discontinued_subject.rb
- app/models/subjects/further_education_subject.rb
- app/models/subjects/modern_languages_subject.rb
- app/models/subjects/primary_subject.rb
- app/models/subjects/secondary_subject.rb
- config/application.rb
- db/migrate/20190912162820_create_subject_table.rb
- db/migrate/20190913112820_create_course_subject_table.rb
- db/migrate/20190913115905_subject_and_ucas_subject_subject_name_indexing.rb
- db/migrate/20190913125905_migrate_subjects.rb
- db/migrate/20190916155318_clean_up_course_subject_data_post_migration.rb
- db/schema.rb
- spec/factories/subjects.rb
- spec/models/course_spec.rb
- spec/models/subject_spec.rb
- spec/serializers/course_serializer_spec.rb
We need a new table for DfE subjects. It uses single table inheritance and follows the layout discussed in the planning meeting.
- Make table
- Populate table
- Add the necessary classes for STI
> [2127] Create new DfE subjects table

- app/serializers/api/v2/serializable_provider.rb
- spec/requests/api/v2/providers_spec.rb
- spec/serializers/api/v2/serializable_provider_spec.rb
UCAS Contacts
- Add `gt12_contact`
- Add `application_alert_contact`
🚢
> [2075] Expand provider ucas contact serialiser

- azure/template.json
- config/settings/qa.yml
- lib/mcb.rb
Need a couple fixes to the setup of the bulk sync container instance.
> [1971] service fixes

- app/jobs/bulk_sync_courses_to_find_job.rb
> [1971] fix error output in bulk sync courses to find job

- db/migrate/20190912162820_create_subject_table.rb
Subject name
Subject name to match `Find`
Subject name to match `Find`
> [2122] Fixed the manage subject naming/casing needs to match search

- Gemfile
- Gemfile.lock
- azure/template.json
- config/environments/production.rb
- config/settings.yml
Applications Insights is insufficient.
Send our logs to logit.io
Still to be proven in QA, but should be no harm done.
> [2078] add logging to logitio

- azure/template.json
* Missed one!
* Configure app service as well as background job
> [2078] Fix logstash config in azure template & extend to app service

- db/migrate/20190912162820_create_subject_table.rb
- db/migrate/20190916155318_clean_up_course_subject_data_post_migration.rb
More subject casing fixes
Fixed subject casing issues
:ship:
> 2130 subject naming update

- db/migrate/20190912162820_create_subject_table.rb
> [2122] Added other as 24

- app/controllers/api/v2/application_controller.rb
- config/initializers/logstash.rb
- config/settings.yml
So we have extra info to effectively track user requests.
Add `user_id`, `sign_in_user_id`, `application` and `environment` to the logstash context that's sent to logit.
Similar to https://github.com/DFE-Digital/manage-courses-frontend/pull/646
> [2223] add additional contextual information for logstash

- app/services/authentication_service.rb
- config/environments/development.rb
- config/environments/production.rb
- config/settings.yml
- config/settings/development.yml
We're trying to chase down a particularly thorny bug which is hard to replicate locally that seems to be related to the auth process.
Build ontop of the recent logstash additions to add optional debug-level output to gain insights of what's happening during a user's authentication process. (i.e. a bunch of debug logging)
The location of the debug output has been "carefully" selected to try to make sense in terms of the login / auth flow. If you see anywhere else that might be especially useful for gaining insight, without flooding the logs with noise let me know.
> [2195] add debug logging for user auth

- app/services/authentication_service.rb
> [XXXX] fix linting

- spec/lib/mcb/commands/apiv1/courses/find_spec.rb
- spec/requests/api/v1/subject_spec.rb
> [xxxx] Fixed bad subjects

- app/controllers/concerns/next_link_header.rb
- app/models/recruitment_cycle.rb
- config/settings.yml
- lib/mcb/cli/course_cli.rb
- spec/factories/recruitment_cycles.rb
- spec/lib/mcb/commands/apiv1/courses/list_spec.rb
- spec/lib/mcb/commands/apiv1/providers/list_spec.rb
- spec/lib/mcb/commands/courses/show_spec.rb
- spec/lib/mcb/commands/providers/audit_spec.rb
- spec/lib/mcb/commands/providers/edit_spec.rb
- spec/lib/mcb/commands/providers/list_spec.rb
- spec/lib/mcb/commands/providers/show_spec.rb
- spec/lib/mcb/commands/providers/sync_to_find_spec.rb
- spec/lib/mcb/commands/providers/touch_spec.rb
- spec/lib/mcb/editor/courses_editor_spec.rb
- spec/models/course/update_valid_spec.rb
- spec/models/course_spec.rb
- spec/models/provider_spec.rb
- spec/models/recruitment_cycle_spec.rb
- spec/requests/api/v1/course/multiple_recruitment_cycles.rb
- spec/requests/api/v1/course_spec.rb
- spec/requests/api/v1/provider_spec.rb
- spec/requests/api/v1/subject_spec.rb
- spec/requests/api/v2/providers/courses/update_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
- spec/requests/api/v2/providers/sites_spec.rb
- spec/requests/api/v2/providers/sync_courses_with_search_and_compare_spec.rb
- spec/requests/api/v2/providers_spec.rb
> 2070 switch to recruitment cycle 2020

- app/models/course.rb
- db/migrate/20191001124753_unique_course_subject.rb
- db/schema.rb
- lib/mcb/editor/courses_editor.rb
- spec/models/course_spec.rb
Dupe records broke ruby bulk publisher.
* Make that impossible, push error earlier.
* Fix all the tests, which involved making the validation not do magic to languages
:ship:
> [2253] Add unique constraint to course_subject

- app/controllers/api/v2/courses_controller.rb
- app/deserializers/api/v2/deserializable_course.rb
- spec/requests/api/v2/providers/courses/create_spec.rb
Update the backend course create to support course creation in its current state
Allows creating a course with a given level
> [2272] Support creating a new course

- app/models/provider.rb
Course count
- Don't include deleted (discarded) courses in the count
🚢
> [2267] Fix course count

- db/migrate/20191004162845_add_missing_fks.rb
- db/schema.rb
One god PR because
https://stackoverflow.com/questions/2979059/rails-is-the-version-number-in-schema-rb-used-for-anything/4047884#4047884
Drop bad data I found in prod backup. Fingers crossed the others are
clean. Staging should answer that before we ship to prod.
* remove orphaned data
* Add all the fks
* :ship:
* :pray:
Resultant relationships:
(generated with [schema explorer](https://schemaexplorer.io/))
> [2275] Add all the missing foreign keys

- app/controllers/health_checks_controller.rb
- config/routes.rb
- spec/requests/health_checks_spec.rb
Just the most basic of basic health checks for the time being.
The two gems we've explored that provider out-of-the-box healtchecks don't work so well. This is the bare minimum we need for the time being.
Add a `/ping` endpoint.
:shipit:
> [2307] add /ping endpoint

- spec/models/concerns/courses/edit_options_spec.rb
- spec/requests/api/v2/providers/courses_spec.rb
Master broke due to https://github.com/DFE-Digital/manage-courses-backend/pull/911
> Fix course specs failing due to presence of additional subjects

- app/services/subject_financial_incentive_creator_service.rb
- db/migrate/20191024143538_add_financial_incentive_to_subjects.rb
- db/schema.rb
- db/seeds.rb
- spec/services/subject_financial_incentive_creator_service_spec.rb
- spec/support/reference_data.rb
Financial incentive data
Added financial incentive data
Based on https://gist.github.com/timabell/ae1af49e44fbb285e544496f57f57d21
> [2358] Added financial incentive data

- app/models/course.rb
- config/locales/en.yml
- db/seeds.rb
- spec/factories/courses.rb
- spec/models/course_spec.rb
- spec/requests/api/v2/build_new_course_spec.rb
- spec/requests/api/v2/providers/courses/update_subject_spec.rb
Validation for course
Added validation for the presence of field where possible
Fixed the inferior level from the course factory
> 2367 add validation for new courses

- app/controllers/api/v2/courses_controller.rb
- spec/requests/api/v2/providers/courses/create_spec.rb
Courses need a title to be created
Create the title when creating the course
> Set title on course creation

- Dockerfile
- azure-pipelines.yml
- docker-compose.yml
- lib/tasks/code_climate.rake
Integration of CodeClimate with MCBE Azure Pipelines
Update Pipeline variables
Update dockerfile and docker-compose for variable pass thru
Add CodeClimate setup task
Add CodeClimate reporter task
CodeClimate badge hasn't updated yet but test_reporter is receiving the status sent by the CI pipeline 
https://codeclimate.com/repos/5cd45a66af3d500177000666/settings/test_reporter
###NOTES: Microsoft documentation is invalid:
`AGENT_JOBSTATUS` doesn't work `AGENT.JOBSTATUS`  is a valid variable for `TRAVIS_TEST_RESULT` replacement
https://docs.microsoft.com/en-us/azure/devops/pipelines/migrate/from-travis?view=azure-devops
> 2457 fix code climate test reported for mcbe

- lib/mcb.rb
Update new prod subscription details in mcb
> [2466] Updated prod subscription in mcb

- azure-pipelines.yml
Remove CC reporter id from the yaml file and move to the pipeline as a variable. 
Regenerate a new reporter id.
> 2457  Update Code Climate ID

- azure-pipelines.yml
- docker-compose.az.yml
- docker-compose.yml
Cleanup and remove references to azure container registry which was used for Travis and az pipelines to co exist.
> 160 cleanup azure build pipeline

- app/controllers/api/v3/providers_controller.rb
- spec/requests/api/v3/providers/show_spec.rb
API::V3 Providers#show
Remove contacts and other data not required outside of PUBLISH
🚢
> [2456] Remove superfluous info from providers show

- app/models/user.rb
- app/policies/course_policy.rb
- app/policies/provider_policy.rb
- app/policies/site_policy.rb
- app/policies/user_policy.rb
- config/routes.rb
- db/migrate/20191101115140_add_admin_to_users.rb
- db/migrate/20191101211119_convert_admin_users.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/users.rb
- spec/lib/mcb/editor/provider_editor_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v2/access_request_spec.rb
Proper admin users aka GOD ACCESS
- Add boolean to existing user model
- Update pundit policy scopes to user new `user.admin?`
- Remove all organisations from current user
- Set `admin: true` on current user
- 🚢
> 2441 add admin users

- app/jobs/bulk_sync_courses_to_find_job.rb
- app/jobs/sync_courses_to_find_job.rb
- app/models/concerns/courses/edit_options/entry_requirements_concern.rb
- app/models/concerns/courses/edit_options/qualification_concern.rb
- app/models/concerns/with_qualifications.rb
- app/models/course.rb
- config/routes.rb
- spec/models/concerns/with_qualifications_spec.rb
- spec/models/course_spec.rb
In order to be able to deliver value it must be easy to understand and work with the code.
This refactors any unclear or non-idiomatic lines.
This PR focuses on Course, its concerns and the jobs.
> [2473] General readability cleanup (part 1)

- azure/template.json
Merging MCAPI deployment tasks into MCBE ARM template
- Add databaseServerHostName and securityAlertEmail parameters
- Create a storage account
- Create manage courses PSQL DB server and DB
- Update psql firewall task
- Update db name and db password app settings for mcbe and mcbg-find-ci
> 2317 Decommission MAPI DB

- docs/api.md
Subjects
Added a list of subjects to v1 docs
:shipit:
> [2513] Added a list of known subjects to docs

- config/database.yml
- config/environments/pentest.rb
- config/settings/pentest.yml
Added a pentest.yaml file in config/settings folder to bring app settings setup inline with other environments.
> 2506-Add a config yaml file for pentest env

- .gitignore
- README.md
- config/settings/development.yml
- lib/mcb.rb
The credentials for the server are now sensitive information and should instead be kept in `config/settings/development.local.yml`
Extract the necessary information from the config yml
> [2486] Remove credentials from mcb

- spec/serializers/api/v2/serializable_subject_spec.rb
Someone, I have no idea who accidentally merged a flaky test into master  
- Fix the test
> fix flaking test

- app/models/provider.rb
- app/models/site.rb
- app/serializers/provider_serializer.rb
- app/serializers/site_serializer.rb
- spec/factories/providers.rb
- spec/factories/sites.rb
- spec/models/provider_spec.rb
- spec/models/site_spec.rb
- spec/serializers/provider_serializer_spec.rb
- spec/serializers/site_serializer_spec.rb
- I forgot to update annotations following adding latitude and longitude columns to Site and Provider tables
> [2552] - Update annotations for latitude and longitude

- config/initializers/geocoder.rb
- Debugging to see if this fixes a Postgres connection issue for background jobs
> Temporarily disable Geocoder caching 

- azure/template.json
Add GCP API Key as env variable for Azure Container Instances
> 2565-Add GCP API Key in CI properties

- azure/template.json
Allow multiple sentryDSN in arm template
> 2644-Add SentryDSN for container instances

- azure/template.json
Adding network profile deployment step in MCBE ARM template as there is a dependency on this step for container instances and should be validated during deployment. 
This is not a fix for the sentry errors for PSQL connection. That issue is still on going investigation by Microsoft Azure Containers Team and PSQL Team.
> 2645 fix sentry errors

- README.md
- docs/adr/0001-record-architecture-decisions.md
We've been talking about using ADRs for some time. Here we go!
Add ADRs for manage and find to this repo.
> Add ADR 1, to add ADRs to this repo

- .adr-dir
- README.md
- docs/adr/0002-use-adr-tools-with-custom-template.md
- docs/adr/index.md
- docs/adr/templates/template.md
Wherever we decide to put ADRs, a little bit of tooling can help us keep things consistent.
Add npryce's adr-tools to help manage ADRs.
> use adr-tools and a custom template for our ADR

- spec/requests/api/v1/provider_spec.rb
- This is to fix the intermittent failures that happen on CI
> [2710] - Add timecop to request spec

- azure/template.json
Add availability test for BE hostname  and custom hostnames in application insight
> 2715-Add availability test in app insight

- app/controllers/api/v3/courses_controller.rb
Allow new FIND to get subjects, properly
Context - https://github.com/jsonapi-rb/jsonapi-rails/issues/113
No change to the JSON output
🚢
> [2339] Fix up course v3 endpoint for subjects

- README.md
New name 🎉 
Update repo names
🚢
> Update rename to new name

- spec/services/subject_financial_incentive_set_subject_knowledge_enhancement_course_available_service_spec.rb
:man_facepalming: 
:face_with_head_bandage: 
:ship:
> [2803] Fixed tests leftovers

- spec/lib/mcb/editor/courses_editor_spec.rb
test is too loose where by its affects #1131 
fix it
:shipit:
> [2832] Fixed loose test

- app/models/subjects/secondary_subject.rb
- db/seeds.rb
- spec/seed_spec.rb
* Seeds file was broken
* CI didn't spot it
* Fix the seeds
* Add a spec to exercise the seeds file
* `bundle exec rails db:reset`
> [2851] Fix seeds.rb and add spec

- azure/template.json
Fix for a connection issue between Azure Container Instance and PSQL that seems to occur whenever there is a deployment.
Add an environment variable that changes on each deployment which forces container instance to reboot.
> 2645-Add build image name to ACI env

- azure-pipelines.yml
- docker-compose.yml
Fix for Postgres password requirement during image build and testing
Supply password along with username in docker-compose.yml
> 2925 Fix TTAPI CI failures

- db/migrate/20200303163136_remove_self_accrediting_provider_on_course.rb
- db/schema.rb
self accrediting provider on course
Remove self accrediting provider on course
> [3002] Remove self accrediting provider on course

- app/jobs/bulk_sync_courses_to_find_job.rb
- app/jobs/geocode_job.rb
- app/jobs/sync_courses_to_find_job.rb
- config/environments/production.rb
- config/initializers/semantic_logger.rb
- docker-compose.yml
We had a large number of errors appearing on Logit but we weren't aware of where they were coming from.
Add job id, queue name and job name when logging.
> [3087] Tag background jobs correctly when logging

- app/views/api_docs/pages/home.md
- config/public-api-v1.yml
> [3073] create openapi spec for courses

- azure-pipelines.yml
Correction to bg_mailer `displayName`
> [3102] - Correction to azure pipeline 

- README.md
The providers endpoint has moved and doesn't work any more
* Update the v2 curl example in the readme
:eyes:
> Update the v2 curl example in the readme

- spec/performance/pre_deploy_spec.rb
We have performance tests against staging. The thresholds need fine tuning.
Update the threshold on the performance test as it was failing at 300.
> Update provider show threshold

- .gitignore
Even though the data is sanitised we should still try to not accidentally
include it in any commits.
> Ignore sanitised production data dumps

- Gemfile
- db/integration_seeds.rb
- docs/adr/0003-integration-tests.md
- lib/tasks/seeds.rake
- spec/factories/courses.rb
- spec/factories/organisations.rb
- spec/factories/providers.rb
- spec/lib/mcb/commands/apiv1/courses/find_spec.rb
- spec/requests/api/v2/organisations_spec.rb
Co-authored-by: De Fong <de_fong2k@yahoo.com>
Co-authored-by: Phil Lee <asmega@gmail.com>
SPIKE: Populating integration test data
Populating integration test data
Added 26 providers and each providers 12 courses.
Should this even go into master?
> [3104] SPIKE: Populating integration test data

- app/controllers/api/v2/sessions_controller.rb
- app/controllers/api/v2/users_controller.rb
- app/mailers/magic_link_email_mailer.rb
- app/models/user.rb
- app/services/generate_and_send_magic_link_service.rb
- azure/template.json
- config/routes.rb
- config/settings.yml
- db/migrate/20200501133532_add_magic_link_tokens_to_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/mailers/magic_link_email_mailer_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v2/sessions/create_by_magic_spec.rb
- spec/requests/api/v2/users/generate_and_send_magic_link_spec.rb
- spec/requests/api/v2/users_spec.rb
- spec/services/generate_and_send_magic_link_service_spec.rb
> [3345] add magic link tokens to users

- app/controllers/api/v2/allocations_controller.rb
- app/services/allocations/update.rb
- spec/factories/allocations.rb
- spec/services/allocations/update_spec.rb
https://trello.com/c/mC7AqJvX/3231-s-11-change-my-allocations-request
* Add update service to set number of places appropriately for allocation
> [3231] Add update service to allocations

- app/controllers/heartbeat_controller.rb
- spec/requests/heartbeat_spec.rb
Sidekiq healtcheck used to check for dead/retry jobs. Not the best healtcheck to see if the system is "up".
Use Sidekiq to check if the queues processes are present or not.
> [3416] change sidekiq healthcheck to check queue processes

- Gemfile
- Gemfile.lock
- README.md
- config/application.rb
- config/settings.yml
- config/settings/production.yml
- config/skylight.yml
- docs/alerting_and_monitoring.md
- spec/controllers/api/v2/application_controller_spec.rb
Skylight adds good performance monitoring.
Add Skylight integration.
See the README for how to enable locally to test.
> [3418] add skylight

- app/models/allocation.rb
- spec/models/allocation_spec.rb
> [3494] Add auditing to allocations

- README.md
- config/database.yml
- config/environments/rollover.rb
- config/settings/rollover.yml
We're creating a rollover env to test rollover.
Add a `rollover` Rails env.
> [3510] add rollover environment

- docs/lib/govuk_tech_docs/open_api/templates/parameters.html.erb
- spec/api/courses_spec.rb
- spec/api/locations_spec.rb
- spec/api/providers_spec.rb
- swagger/public_v1/api_spec.json
- swagger/public_v1/component_schemas/CourseAttributes.yml
- swagger/public_v1/component_schemas/CourseRelationships.yml
- swagger/public_v1/component_schemas/LocationStatusAttributes.yml
- swagger/public_v1/component_schemas/LocationStatusRelationships.yml
- swagger/public_v1/component_schemas/Pagination.yml
- swagger/public_v1/component_schemas/ProviderAttributes.yml
- swagger/public_v1/component_schemas/ProviderRelationships.yml
- swagger/public_v1/component_schemas/RecruitmentCycleAttributes.yml
- swagger/public_v1/component_schemas/SubjectAttributes.yml
- swagger/public_v1/template.yml
- https://trello.com/c/9vJWZOqy/3460-m-api-updates-before-apply-review-part-2
- This PR contains multiple improvements to the API documentation
- Added examples to endpoints
- Added docs for sorting and filtering
- Added descriptions for schemas
- Align schema names
- Remove `?` from ends of attribute names
- Fire up docs, see README
- Should see new improved docs
> [3460] api docs improvements

- app/controllers/api/v3/subject_areas_controller.rb
- https://trello.com/c/6SqF8p2F/3511-optimize-find-courses-by-subject-page
- The subject pages on the find course wizard is not eager loading associations when it hits the api
Before (API)
```
2020-06-09 11:15:24.785430 D [8674:puma threadpool 001] Rails -- API HIT => http://localhost:3001/api/v3/subject_areas?include=subjects
2020-06-09 11:15:24.789229 D [8674:puma threadpool 001] Rack -- Started -- { :method => "GET", :path => "/api/v3/subject_areas?include=subjects", :ip => "::1" }
2020-06-09 11:15:25.048886 D [8674:puma threadpool 001] API::V3::SubjectAreasController -- Processing #index
2020-06-09 11:15:25.069156 D [8674:puma threadpool 001] (0.449ms) ActiveRecord -- SubjectArea Load -- { :sql => "SELECT \"subject_area\".* FROM \"subject_area\" WHERE \"subject_area\".\"typename\" != …
```
> [3511] Eager load associations on subjects page

- README.md
questionable
no longer questionable
:shipit:
> [3410] Amended readme

- app/services/user_associations_service/create.rb
There was a typo.
Remove the typo.
Please check that the typo has been removed.
> Fix typo in UserAssociationService

- spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb
Flaky test 
Fixed flaky tests due to ordering of provider name
:shipit: 
:shipit:
> [xxxx] Fixed flaky tests due to ordering of provider name

- azure/template.json
Spelling mistakes in template :-( 
Variables corrected
> Fix typo in Azure template

- .gitignore
> Ignore node modules needed for api docs

- app/controllers/api/public/v1/application_controller.rb
- app/controllers/api/public/v1/providers_controller.rb
- app/serializers/api/public/v1/serializable_provider.rb
- config/routes.rb
- spec/api/providers_spec.rb
- spec/factories/providers.rb
- spec/requests/api/public/v1/providers/index_spec.rb
- spec/requests/api/public/v1/providers/show_spec.rb
- spec/serializers/api/public/v1/serializable_provider_spec.rb
- swagger/public_v1/api_spec.json
- swagger/public_v1/template.yml
Added documentation for the null provider
> 3736 - implemented the endpoint for the provider

- app/controllers/api/public/v1/subjects_controller.rb
- config/routes.rb
- spec/api/subjects_spec.rb
- swagger/public_v1/api_spec.json
- swagger/public_v1/component_schemas/SubjectAttributes.yml
> [3749] Add API documentation for Subjects endpoint

- .github/workflows/build.yml
- .gitignore
- config/database.yml
- config/initializers/sidekiq.rb
- docker-compose.yml
- terraform/paas/backend.tf
- terraform/paas/data.tf
- terraform/paas/provider.tf
- terraform/paas/resources.tf
- terraform/paas/terraform_qa.tfvars
- terraform/paas/variables.tf
- terraform/paas/versions.tf
> 3477 deploy ttapi govuk paas GitHub actions

- app/services/README.md
- docs/adr/0005-service-entry-points.md
- docs/adr/index.md
Had a conversation in Slack about this, again, which served as a reminder to create this ADR and update the services REAMDE.
https://ukgovernmentdfe.slack.com/archives/CGVNJ2Q2F/p1597310908061300
> add ADR "Service Entry Points"

- docs/adr/0005-controller-structure.md
- docs/adr/index.md
- https://trello.com/c/KSCQ9WJz/3812-adr-for-controller-structure-with-nested-resources
- Raise ADR to document our approach to structuring controllers for nested resources
- Read ADR
> ADR - Controller structure

- app/controllers/api/public/v1/courses_controller.rb
- spec/docs/courses_spec.rb
- swagger/public_v1/api_spec.json
- https://trello.com/c/D1dnSlyF/3777-s-implement-sorting-by-distance
- Course search is already implemented, we are merely documenting this feature 
- Update docs on how to do a location based search
- Look at the docs
- See example of location based search
- Perform the example, should return results sorted by distance from origin
> [3777] Docs add curl example for geo based search

- docs/adr/0007-javascript-linting.md
- docs/adr/index.md
- Raise ADR to document our approach to JavaScript linting and code style tools.
- Read the ADR
> Add ADR for JavaScript Linting and code style.

- docs/config/tech-docs.yml
- docs/source/support.html.md.erb
- Add "Feedback" link to header which takes users to our feedback form
- Add "Feedback" copy to the Support page.
> [98] Add feedback survey link

- azure-pipelines.yml
- azure/template.json
- bg-geocode/Dockerfile
- bg-jobs/Dockerfile
- bg-mailer/Dockerfile
- config/sidekiq.yml
- docker-compose.yml
configure single container instance to listen to multiple queues.
> use single container instance for background jobs

- app/controllers/api/v2/contacts_controller.rb
- app/deserializers/api/v2/deserializable_contact.rb
- app/policies/contact_policy.rb
- app/serializers/api/v2/serializable_contact.rb
- app/serializers/api/v2/serializable_provider.rb
- config/routes.rb
- spec/policies/contact_policy_spec.rb
- spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb
- spec/requests/api/v2/providers/contacts_spec.rb
- spec/requests/api/v2/providers/providers_show_spec.rb
- spec/serializers/api/v2/serializable_contact_spec.rb
- spec/serializers/api/v2/serializable_provider_spec.rb
- https://trello.com/c/NLKqADvh/167-add-update-endpoint-for-ucas-contacts-in-api-v2
- Add a new endpoint to update individual contacts for a provider
- Load the rails server locally and fire a request to update a contact: `PUT 'localhost:3001/api/v2/contacts/:id`
- Assert the contact is updated.
> [167] Implement update endpoint for contacts

- config/settings/production.yml
- config/settings/qa.yml
We have the open source account now so this can be enabled.
* Enable in production
* Remove QA settings and use default
> Enable Skylight in production

- azure/template.json
Parameterise Postgres' database server CPU varaible
Introduced the Parametisation of Postgres' database server CPU varaible
> Add CPU database parameters

- app/services/subjects/financial_incentive_creator_service.rb
- db/migrate/20201013130023_add_missing_2021_financial_incentives.rb
- db/schema.rb
- spec/requests/api/v3/subjects/index_spec.rb
- spec/serializers/api/public/v1/serializable_course_spec.rb
Missing biology bursary
Added biology bursary
:ship:
> [0274] Added biology bursary

- .github/workflows/build.yml
Fix test condition if branch_tag == paas-master
[[ "$BRANCH_TAG" == "paas-master" ]] && docker push $DOCKER_IMAGE-middleman:$BRANCH_TAG
> Fix test condition if branch_tag == paas-master

- .github/workflows/build.yml
- terraform/paas/resources.tf
- terraform/paas/terraform_qa.tfvars
- terraform/paas/variables.tf
Fix terraform download location
> 309 fix terraform cf plugin

- app/controllers/api/v3/courses_controller.rb
This endpoint has some N+1 queries. 
Add them as includes to the parent query.
> [285] Include N+1 queries on courses#show

- Gemfile.lock
Looks like this didn't get committed.
Commit it.
> Commit rspec-benchmark Gemfile.lock

- .github/workflows/paas-database-restore.yml
Keep DB in PaaS in sync with Azure DB (while we are migrating to PaaS)
Scheduled workflow (4:00 AM Mon-Fri) to backup Azure DB(qa, staging)
and restore in the respective PaaS environment.
> Workflow to restore DB from Azure to PaaS

- .github/workflows/deploy.yml
Deploy to staging, after a successful deployment to qa
Will change target branch of this PR to `master` once #1649 is merged.
> Deploy to staging after qa

- .github/workflows/deploy.yml
- terraform/workspace_variables/production_backend.tfvars
> Deploy to production space in PaaS

- .github/workflows/paas-database-restore.yml
Produce db_backup.sql as a build artifact, so devs can download an restore local DB or investigate in case of errors.
> Upload db_backup.sql as a build artifact

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Individual input parameters to control
deployments to qa, staging and production
> Use matrix deployment strategy

- .github/workflows/database-restore.yml
Sanitise the production database and restore it to qa & staging
> Restore sanitised database backup to qa & staging

- .github/workflows/database-restore.yml
- db/scripts/integration_setup.sql
- db/scripts/sanitise.sql
Move db scripts from Azure Repos to this repository.
> Move sanitise db scripts to this repository

- app/controllers/api/public/v1/providers/courses/locations_controller.rb
- app/serializers/api/public/v1/serializable_location.rb
- app/serializers/api/public/v1/serializable_location_status.rb
- app/serializers/api/public/v1/serializer_service.rb
- spec/controllers/api/public/v1/providers/courses/locations_controller_spec.rb
- spec/docs/providers/courses/locations_spec.rb
- swagger/public_v1/api_spec.json
Location status
Location status was missing from original design
http://localhost:3001/api/public/v1/recruitment_cycles/2021/providers/T92/courses/X130/locations?include=location_status
> [624] Add location status to be exposed

- .github/workflows/deploy.yml
Wait for other inprogress run in the matrix selection job.
> Wait for other inprogress runs in matrix job

- README.md
I didn't have `asdf` on my computer so I had to do a bit of setup before I could run `bundle`
> Add asdf instructions to the README

- .github/workflows/build.yml
Add missing turnstyle check in build workflow
> Add turnstyle check to avoid concurrent runs

- app/controllers/api/public/v1/providers/courses_controller.rb
- app/controllers/api/public/v1/subjects_controller.rb
- app/serializers/api/public/v1/serializable_subject.rb
- app/serializers/api/public/v1/serializer_service.rb
- spec/controllers/api/public/v1/subjects_controller_spec.rb
- spec/serializers/api/public/v1/serializable_subject_spec.rb
subjects public v1 endpoint
Added subjects public v1 endpoint, inclusive of sorting by name as per 
https://api.publish-teacher-training-courses.service.gov.uk/api-reference.html#subjects-get
http://localhost:3001/api/public/v1/subjects
http://localhost:3001/api/public/v1/subjects?sort=name
> [634] Added subjects public v1 endpoint

- config/environments/research.rb
- config/environments/rollover.rb
- config/settings/research.yml
- config/settings/rollover.yml
deadweight
research
rollover
environments
remove unneeded environments
Are we using it?
see https://github.com/DFE-Digital/publish-teacher-training/pull/1474
> [xxxx] Removed deadweights

- Makefile
- config/environments/review.rb
- terraform/variables.tf
- terraform/workspace_variables/review.tfvars
- terraform/workspace_variables/review_backend.tfvars
Make commands to deploy to qa, staging and production.
Be able to create and destroy review apps.
> Terraform commands in Makefile

- docs/healthcheck_and_ping_endpoints.md
- spec/smoke/api/v1/courses_spec.rb
- spec/smoke/api/v1/healthcheck_spec.rb
https://github.com/DFE-Digital/teacher-training-api/pull/1728
This didn't make it into master! Merged into old branch.
Reopening to be merged separately.
See https://github.com/DFE-Digital/teacher-training-api/pull/1728
See https://github.com/DFE-Digital/teacher-training-api/pull/1728
> [711] Smoke test for healthcheck and courses index routes

- terraform/modules/paas/data.tf
cf org name is being renamed to dfe
> Rename PaaS org to `dfe`

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/smoke-test.yml
- Makefile
- config/environments/sandbox.rb
- config/settings/sandbox.yml
- terraform/modules/statuscake/resources.tf
- terraform/workspace_variables/production.tfvars
- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/sandbox.tfvars
- terraform/workspace_variables/sandbox_backend.tfvars
- terraform/workspace_variables/staging.tfvars
Create a sandbox environment for the app
Terraform config for sandbox environment.
Workflow to deploy to sandbox environment
> Deploy app to sandbox environment

- docs/source/index.html.md.erb
> Remove API is not implemented statement

- azure/template.json
- config/settings.yml
Configure `MAPIT_API_KEY` environment variable
> Configure mapit_api_key

- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
blue-green-v2 to avoid deployment issues with cf provider.
> Change worker app deployment strategy

- terraform/workspace_variables/production.tfvars
In preparation for going live, update the database to a HA plan.
Update postgres in production to `small-ha-11`
Update redis  in production to `micro-ha-5.x`
Delete existing database service & recreate.
> Update production to HA database plan

- .github/workflows/build.yml
Alert slack channel on build failures
> Alert slack channel on build failures

- .github/workflows/database-restore.yml
api-migration-store-prod-db-backups-in-azure
Take a copy a dump from prod (before) sanitisation and store on Azure storage Account
> Upload PaaS db_dump to Az storage_account

- Makefile
Access the rails console for space developers
`make qa console`
> make console command

- terraform/workspace_variables/production.tfvars
Web app is still facing high memory pressure.
Increase instance count to 4 in Production
> Increase instance count for the web app

- terraform/workspace_variables/qa.tfvars
- terraform/workspace_variables/staging.tfvars
Increase instance count to 2 in qa and staging for HA.
Increase web app instances to 2 in qa and staging.
It is already set to 2 in sandbox
> Increase web app instance count to 2

- Dockerfile
- Gemfile.lock
Bump mimemagic to 0.3.9
Install freedesktop.org.xml package
> Bump mimemagic to 0.3.9

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Test new features in QA with QA data and DSI
Allow manual deployment or deploy from a branch to QA and remove from pipeline so it's not overwritten by changes to master
Check succesful runs:
https://github.com/DFE-Digital/teacher-training-api/actions/runs/690478671
https://github.com/DFE-Digital/teacher-training-api/actions/runs/690511748
> [1370] Take qa out of pipeline

- app/controllers/support/data_exports_controller.rb
- app/controllers/support/providers_controller.rb
- app/controllers/support/users_controller.rb
- app/services/support/data_exports/base.rb
- app/services/support/data_exports/data_export.rb
- app/services/support/data_exports/users_export.rb
- app/views/layouts/provider_record.html.erb
- app/views/support/_menu.html.erb
- app/views/support/data_exports/index.html.erb
- app/views/support/providers/index.html.erb
- app/views/support/providers/users.html.erb
- app/views/support/users/_users.html.erb
- app/views/support/users/index.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/support/users/providers_list_spec.rb
- spec/features/support/users/users_list_spec.rb
- spec/services/support/data_exports/base_spec.rb
- spec/services/support/data_exports/data_export_spec.rb
- spec/services/support/data_exports/users_export_spec.rb
- spec/support/feature_helpers/pages.rb
- spec/support/page_objects/support/users_index_page.rb
https://trello.com/c/JMj5xpVt/1318-m-add-user-list-to-api-ui
https://trello.com/c/U0WdcnYX/1319-s-add-csv-download-feature-to-user-list-on-api-ui
* Users index page added I support, with new menu entry
* Provider users is now a member action on Providers controller
* Export users as CSV button added on users index page
* New Data Exports section added, with `UsersExport` as the first exportable data, a place to add many more exports in the future.
* Visit `/support/users` to see section
* Click export button
> [1318] add user list to api UI

- config/application.rb
> Log skylight to STDOUT

- docs/adr/0008-use-skylight-for-performance-monitoring.md
Add an ADR to record decision around using skylight for performance monitoring.
> Add ADR for performance monitoring

- terraform/workspace_variables/production.tfvars
CPU usage is spiking when the Apply sync job runs
Increase number of webapp instances to 6
> Increase web app instances to 6

- csv/provider_sites_with_urn.csv
- csv/providers_with_urn_and_ukprn.csv
- lib/tasks/backfill_urns_and_ukprns.rake
https://trello.com/c/EJ1iwDGe/1636-backfill-urn-and-ukprns-from-gias
- Two rake tasks to backfill URNs (providers and sites) and UKPRNs (providers)
> [1636] Backfill URN and UKPRN's from GIAS

- terraform/workspace_variables/production.tfvars
We are still seeing CPU spikes when apply sync is running.
Increase web app instances to 8
> Increase web app instances to 8

- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- terraform/modules/paas/data.tf
> Use qa space id for postgres-qa service instance

- app/controllers/support/providers_controller.rb
- app/views/support/providers/new.html.erb
Improve form for creating new provider
- Add URN to site
- Add UKPRN to provider
- Update input labels to match publish service
`/support/providers/new`
> 1769 update new provider form

- .github/workflows/build.yml
- app/controllers/api/v2/allocations_controller.rb
- config/rubocop/layout.yml
- config/rubocop/lint.yml
- config/rubocop/metrics.yml
- config/rubocop/naming.yml
- config/rubocop/rails.yml
- config/rubocop/rspec.yml
- config/rubocop/style.yml
- lib/mcb.rb
- lib/mcb/commands/apiv1/courses.rb
- lib/mcb/commands/apiv1/courses/find.rb
- lib/mcb/commands/apiv1/courses/list.rb
- lib/mcb/commands/apiv1/providers.rb
- lib/mcb/commands/apiv1/providers/find.rb
- lib/mcb/commands/apiv1/providers/list.rb
- lib/mcb/commands/providers/edit.rb
- lib/mcb/commands/providers/list.rb
- lib/mcb/commands/providers/show.rb
- lib/mcb/commands/users/list.rb
- lib/mcb/render.rb
- spec/requests/api/v2/providers/allocations_spec.rb
- spec/requests/api/v2/providers/courses/update_sites_spec.rb
This should need https://github.com/DFE-Digital/teacher-training-api/pull/1982 to be merged before it will pass CI. 
It wasn't running. It is now.
* run it
* Look at the GitHub actions log and see if it ran. https://github.com/DFE-Digital/teacher-training-api/runs/2842537644?check_suite_focus=true (spoilers: it did and failed as we need the PR up there ^ merged)
* In the other apps we specify specific directories that should be linted. I think this belongs in the rubocop config rather than in the build command so I've not done that here.
> [xxx] Run rubocop in CI

- spec/support/page_objects/support/user_new_page.rb
> Fix broken test on master

- .github/workflows/delete-review-app.yml
Delete review app workflow is broken
The id is misplaced, move it under step
See https://github.com/DFE-Digital/teacher-training-api/actions/runs/982340805/workflow
> [2089] Fix delete review app workflow

- docs/rollover.md
There were some typos in the rollover doc, this PR addresses these.
> Fix rollover doc

- .github/workflows/database-restore.yml
Failing workflow: https://github.com/DFE-Digital/teacher-training-api/runs/2948444160?check_suite_focus=true
- Pin minor version
- Enable manual trigger
> [2086] Pin version in DB workflow

- .github/workflows/build.yml
> Deploy master to rollover

- Makefile
Deleting old review apps
Make the Makefile work for command line operations on review apps
> [2145] Makefile for review apps

- .github/workflows/smoke-test.yml
- .tool-versions
- Dockerfile
- Gemfile
- Gemfile.lock
- README.md
- docs/.tool-versions
- docs/Gemfile
- docs/Gemfile.lock
We use Ruby. There is a new version.
Upgrade to it.
Draft until ruby-build is updated.
> [xxx] Upgrade to Ruby 2.7.4

- .github/workflows/database-restore.yml
Current storage account has not lifecycle policy
Configure new storage account for backup.
Archive backup and upload to storage.
Workflow run: https://github.com/DFE-Digital/teacher-training-api/actions/runs/1037053861
> Configure Genv2 storage account for backup

- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- Dockerfile
- docker-compose.yml
Improve build time
- Use head branch as docker tag for review apps
- Move ARG to bottom
- Use cache from master
See successful caching in latest run
> [2313] Use PR head branch as docker build tag

- .github/workflows/build.yml
Pipeline is broken: https://github.com/DFE-Digital/teacher-training-api/runs/3180094482?check_suite_focus=true
Add missing conditionals
> [2313] Add missing conditionals in build workflow

- app/models/provider.rb
- app/serializers/api/v2/serializable_provider.rb
- spec/models/provider_spec.rb
- spec/requests/api/v2/providers/accredited_body_get_providers_spec.rb
- spec/requests/api/v2/providers/providers_show_spec.rb
- spec/serializers/api/v2/serializable_provider_spec.rb
Follow on from this PR - https://github.com/DFE-Digital/publish-teacher-training/pull/1857
> [2339] Remove sites max limit method

- config/settings/production.yml
- config/settings/staging.yml
We are sending web request events to BigQuery. This has been tested on QA and staging now and is ready for release.
Set the feature flag to true in staging and production.
> [2257] Enable BigQuery request logging

- terraform/workspace_variables/production.tfvars
Database plan upgrade scheduled on 23 Sep between 7-8 AM.
Update plan
To be merged after upgrade is completed on 23 Sep.
> Update database plan to medium

- app/lib/big_query/entity_event.rb
- config/analytics.yml
- spec/lib/big_query/entity_event_spec.rb
We need the data from the statistics table in BigQuery.
Add it to analytics.yml so as we send it.
~I've run this locally without error although I'm not seeing them in BigQuery. Would be good to test that as it may be my config.~
I've run this locally and it is working like a charm. Example in the `publish_api_events_test.events`
> [xxx] Add statistics to analytics.yml

- app/lib/big_query/entity_event.rb
- config/analytics.yml
- spec/models/concerns/emits_entity_events_spec.rb
We are sending entities into BigQuery. Some had missing ID fields.
* Add the id field to statistic and subject area
* rename the event to `import_entity` for consistency
> [xxx] update analytics

- config/database.yml
- terraform/workspace_variables/loadtest.tfvars
> loadtest database configuration

- Gemfile.lock
:shipit: 
https://github.com/DFE-Digital/teacher-training-api/pull/2278
> [0364] Update gemfile

- app/controllers/api/v2/access_requests_controller.rb
- app/models/access_request.rb
- spec/models/access_request_spec.rb
- [This trello ticket](https://trello.com/c/W6papRfE/363-visit-code-debt-on-v2)
- Redact V2 controller
> [363] Redact access request controller

- app/components/header/style.scss
- app/components/header/view.html.erb
- app/components/paginated_filter/view.html.erb
- app/components/paginated_filter/view.rb
- app/components/providers/filters/view.html.erb
- app/components/providers/filters/view.rb
- app/views/layouts/provider_record.html.erb
- app/views/support/allocation_uplifts/new.html.erb
- app/views/support/allocations/index.html.erb
- app/views/support/allocations/show.html.erb
- app/views/support/providers/index.html.erb
- app/views/support/providers/new.html.erb
- app/views/support/users/index.html.erb
- app/views/support/users/new.html.erb
- app/views/support/users/show.html.erb
- config/locales/en.yml
- [This trello ticket](https://trello.com/c/85jlRfy9/603-address-minor-design-work-on-ttapi-support-ui)
- Address small UI inconsistencies around the Support UI of TTAPI
> [603] Support UI design fixes

- config/initializers/bigquery.rb
- config/initializers/semantic_logger.rb
Flood log
Build a dam
See `.` dots or angry red `F`
> [xxxx] Flood log

- app/views/support/allocations/show.html.erb
- app/views/support/providers/show.html.erb
:shipit: 
Some one nick these lines
> [xxxx] Fixed stolen lines

- app/services/courses/validate_custom_age_range_service.rb
- config/locales/en.yml
- spec/requests/api/v2/access_request_spec.rb
- spec/requests/api/v2/providers/courses/create/age_range_in_years_spec.rb
- spec/requests/api/v2/providers/sites_spec.rb
- spec/services/courses/validate_custom_age_range_service_spec.rb
Validate errors messages for adding locations to providers, create a new course age range, and access request
Amended validate errors messages for adding locations to providers, create a new course age range, and access request
Review from https://publish-teacher-training-pr-2021.london.cloudapps.digital/
> [0405] Review of error messages and summaries in Publish

- spec/services/support/filters/filter_spec.rb
> [xxx] Use match array in place of eq

- spec/models/provider_spec.rb
> [xxxx] Fixed flakey array

- .codeclimate.yml
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/publish_interface/providers_controller.rb
- app/helpers/application_helper.rb
- app/helpers/provider_helper.rb
- app/helpers/view_helper.rb
- app/models/provider.rb
- app/models/recruitment_cycle.rb
- app/services/providers/visa_sponsorship_service.rb
- app/views/errors/not_found.html.erb
- app/views/publish_interface/providers/details.html.erb
- app/webpacker/styles/_status-box.scss
- app/webpacker/styles/_summary-list.scss
- app/webpacker/styles/application.scss
- config/routes.rb
- config/settings.yml
- spec/requests/api/v3/courses/index_spec.rb
This is the first section of Publish we're migrating across. 
https://trello.com/c/wlq5VfsQ
Add the base page and all dependencies needed to render it. Subsequent PRs will implement the various sub-pages.
- Per commit is probably best
- Feature specs to follow later
- Can be tested locally by authenticating as a persona and navigating to `/publish/organisations/#{provider_code}/2022/details`
> Add About Your Organisation page

- app/models/user.rb
- app/services/access_request_approval_service.rb
- spec/factories/access_requests.rb
- spec/services/access_request_approval_service_spec.rb
- [This trello ticket](https://trello.com/c/rRlaSz79/456-part-2-dual-running-userpermission-along-with-organisation)
> [456] (Part 2) Write UserPermission and OrganisationUser data concurrently

- .rubocop_todo.yml
- spec/requests/api/v2/interrupt_page_acknowlegements_spec.rb
https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
Add parentheses
> [489] Rubocop To Do: Correct API interrupt spec

- .rubocop_todo.yml
- app/services/courses/validate_custom_age_range_service.rb
- docs/lib/govuk_tech_docs/open_api/extension.rb
Clea up of Rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
Remove duplicate branching from rescue block and if/elisf block
> [489] Rubocop ToDo: Remove duplicate branching

- app/controllers/support/locations_controller.rb
- app/views/support/locations/_form.html.erb
- app/views/support/locations/edit.html.erb
- app/views/support/locations/index.html.erb
- app/views/support/locations/new.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/features/support/providers/locations/managing_locations_spec.rb
- spec/support/feature_helpers/support_pages.rb
- spec/support/page_objects/sections/location_form.rb
- spec/support/page_objects/support/provider/location_create_page.rb
- spec/support/page_objects/support/provider/locations_index_page.rb
- https://trello.com/c/ThhZdGGx/506-add-a-location-for-a-provider-in-the-support-console
- Allow support admin to add locations for a provider
Head over to support, login as good ol' Colin, find a provider and add a location for them
> [506] Add a location

- .rubocop_todo.yml
- spec/components/navigation_bar/view_spec.rb
- spec/controllers/api/public/v1/subjects_controller_spec.rb
- spec/factories/apiv2_token.rb
- spec/factories/financial_incentives.rb
- spec/factories/pgde_course.rb
- spec/requests/api/v2/providers/courses/update_accrediting_provider_spec.rb
- spec/requests/api/v2/providers/sites_spec.rb
Clear up of Rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
Remove deprecated factory and add nil values to spec files.
> [489] Rubocop ToDo: Fix Empty block linting errors

- .rubocop_todo.yml
- docs/lib/govuk_tech_docs/open_api/renderer.rb
Clear up of Rubocop to do: https://trello.com/c/UhJu4WFi/489-clear-rubocoptodo-part-2
These are just docs so not sure how important it is that they follow rubocop conventions. Open to discussion.
> [489] Rubocop ToDo: Remove self assignment of variable in renderer

- Gemfile
- Gemfile.lock
tabulo
Remove tabulo gem
Not in use
> [xxxx] Remove tabulo gem

- config/settings/staging.yml
Show copy on the sign in screen related to the ongoing migration.
> Activate display_migration_signin on staging

- .tool-versions
- docs/adr/0010-merge-publish-service-into-ttapi.md
Now that we've decided how the migration is going to happen, we should document this 
decision.
https://trello.com/c/y4Buvmu5
See commits
- Does the ADR cover all relevant detail?
- Is it clear?
> Add ADR for Publish/TTAPI merge

- app/models/user.rb
- app/views/support/providers/_provider_user_list.html.erb
- app/views/support/users/_users.html.erb
- app/views/support/users/index.html.erb
- app/webpacker/styles/_summary-list.scss
- app/webpacker/styles/application.scss
- spec/features/support/providers/viewing_a_user_spec.rb
- spec/features/support/users/users_list_spec.rb
- spec/support/page_objects/sections/user.rb
- spec/support/page_objects/support/users_index_page.rb
- [This trello ticket](https://trello.com/c/BlEpvF93/510-modify-user-interface-on-sc)
- Change first/last name on user list to display fullname
- Display the provider list on the user page
- Log onto support console and see the changes on the User tab
> [510] Display user fullname on support console and include provider list

- app/models/user.rb
- spec/features/support/providers/viewing_a_user_spec.rb
> xxx remove duplicate fullname

- app/controllers/pages_controller.rb
- app/helpers/allocation_cycle_helper.rb
- app/services/performance_dashboard_service.rb
- app/views/layouts/_footer.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/accessibility.html.erb
- app/views/pages/cookies.html.erb
- app/views/pages/guidance.html.erb
- app/views/pages/performance_dashboard.html.erb
- app/views/pages/performance_dashboard/_allocation_content.html.erb
- app/views/pages/performance_dashboard/_allocations_tab.html.erb
- app/views/pages/performance_dashboard/_courses_tab.html.erb
- app/views/pages/performance_dashboard/_initial_performance_indicators.html.erb
- app/views/pages/performance_dashboard/_providers_tab.html.erb
- app/views/pages/performance_dashboard/_rollover_tab.html.erb
- app/views/pages/performance_dashboard/_users_tab.html.erb
- app/views/pages/privacy.html.erb
- app/views/pages/terms.html.erb
- app/webpacker/styles/_card.scss
- app/webpacker/styles/application.scss
- config/routes.rb
- spec/features/view_pages_spec.rb
Footer
Add the footer ad all the related ie, Accessibility Cookies Privacy policy Terms and conditions Service performance 
Ported across, like for like with minimum changes
https://teacher-training-api-pr-2446.london.cloudapps.digital/accessibility
https://teacher-training-api-pr-2446.london.cloudapps.digital/cookies
https://teacher-training-api-pr-2446.london.cloudapps.digital/guidance
https://teacher-training-api-pr-2446.london.cloudapps.digital/performance-dashboard
https://teacher-training-api-pr-2446.london.cloudapps.digital/privacy-policy
https://teacher-training-api-pr-2446.london.cloudapps.digital/terms-conditions
> [562] Migrate all static content linked in the footer

- app/forms/publish_interface/about_your_organisation_form.rb
- app/forms/publish_interface/base_model_form.rb
- app/forms/publish_interface/base_provider_form.rb
The base of all models
BaseProviderForm had all the whistle and bells that is needed by any other thing that is not a `provider`.
general refactor
> [0580] Amended form base

- app/controllers/publish_interface/providers/locations_controller.rb
- app/forms/publish_interface/location_form.rb
- app/policies/provider_policy.rb
- app/validators/postcode_validator.rb
- app/views/publish_interface/providers/locations/_form.html.erb
- app/views/publish_interface/providers/locations/edit.html.erb
- app/views/publish_interface/providers/locations/new.html.erb
- config/locales/en.yml
- spec/features/publish_interface/managing_locations_spec.rb
- spec/support/feature_helpers/publish_interface_pages.rb
- spec/support/page_objects/publish_interface/location_edit.rb
- spec/support/page_objects/publish_interface/location_new.rb
- spec/support/page_objects/publish_interface/locations_index.rb
This PR moves across the location create/update functionality from Old Publish.
These are called Sites in the data model and Locations in the UI. This
change implements the create/update flow for this resource.
Navigate to the locations section with a valid provider code and test adding/editing locations.
> Add create/update locations to New Publish

- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
- config/settings/staging.yml
Turn on new sign in prompt for old publish
> Turn on old publish sign in prompt for prod and sandbox

- app/services/sites/code_generator.rb
Fixes this [error](https://sentry.io/organizations/dfe-teacher-services/issues/3048609984/?environment=production&project=1377944&query=is%3Aunresolved).
- Handle `nils` in `#existing_sequential_codes`
> [694] Handle nils in existing_sequential_codes

- app/views/publish/providers/locations/index.html.erb
Duplicated page title
Fixed duplicated page title
https://teacher-training-api-pr-2571.london.cloudapps.digital/publish/organisations/D87/2022/locations
vs
https://qa2.publish-teacher-training-courses.service.gov.uk/publish/organisations/D87/2022/locations
> [0612] Fixed duplicated page title

- .github/actions/deploy/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy.yml
The workflows that initiate a deployment use workflow_dispatch, this can result in unnecessary failures when subsequent workflow doesn't wait and makes logs harder to read.
https://trello.com/c/grpMynpF
This change refactors the workflow to use reusable actions.
Confirm that workflow conditions and results remain the same.
> Refactor deployment workflows

- Makefile
- docs/disaster-recovery.md
There are some mistakes in the DR documentation.
https://trello.com/c/wx5ad9MF
Fixes the mistakes.
> Fix some issues in DR documentation

- config/routes.rb
- config/settings.yml
- config/settings/qa.yml
- config/settings/staging.yml
- spec/requests/send_data_to_big_query_spec.rb
- terraform/workspace_variables/qa.tfvars.json
- terraform/workspace_variables/staging.tfvars.json
- https://trello.com/c/elvNaWG9/569-switch-www-and-www2
- Updates the base url of the app
- Adds guard for handling redirects in prod behind a flag (currently off)
> Switch new publish on for QA & Staging

- .github/workflows/build-and-deploy.yml
- Makefile
- config/database.yml
- config/environments/rollover.rb
- config/settings/rollover.yml
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/workspace_variables/app_config.yml
- terraform/workspace_variables/rollover.tfvars.json
- terraform/workspace_variables/rollover_backend.tfvars
Create rollover env to do a dry run of the rollover process
https://trello.com/c/N3XXsl9o/946-rollover-environment-for-ttapi-new-publish
Create required config files for the new env
Update Makefile
Add rollover to build-and-deploy workflow
Also,
-updated AZ gh secret
-checked AZ app/infra kv up to date
confirm config/settings/rollover.yml
confirm AZ app secrets 
manual make of rollover env
> Add rollover env

- .github/workflows/deploy.yml
Add rollover to deploy workflow dispatch so it can be deployed manually 
Update deploy.yml
Check deploy.yml
> Add rollover to deploy workflow dispatch

- .github/actions/deploy/action.yml
- .github/actions/smoke-test/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
Updates the slack channel name for build errors.
> [xxx] Update slack channels for build failures

- app/helpers/breadcrumb_helper.rb
- app/views/layouts/application.html.erb
Only remove breadcrumb not backlinks from the new publish navigation
> Only remove breadcrumb not backlinks

- app/views/layouts/application.html.erb
- spec/features/publish/providers_index_spec.rb
Allow admins to use the org switcher
> Allow admins to use the org switcher

- Makefile
- docs/disaster-recovery.md
Review of documentation and update to facilitate testing of the process against the a review environment.
Update to documentation file
> Quick change to support testing

- app/components/header/style.scss
Fix the length of the blue bar in prod.
🚢
> Fix blue bar length in prod

- config/settings/qa.yml
- config/settings/staging.yml
Switch on rollover in QA and staging for testing
> Switch on rollover in QA and Staging

- config/settings/qa.yml
- config/settings/staging.yml
Reverts DFE-Digital/teacher-training-api#2732
> Revert "Switch on rollover in QA and Staging"

- app/views/publish/courses/preview/_train_with_disabilities.html.erb
Bad path
Fixed bad path
this arise from migration
:shipit:
> [0156] Fixed bad path

- config/initializers/semantic_logger.rb
Make logs great again (in dev and prod)
> Fix logging in development and production

- Gemfile.lock
- app/components/application_component.rb
- app/components/flash_banner/view.rb
- app/components/header/view.rb
- app/components/navigation_bar/view.rb
- app/components/notification_banner/view.html.erb
- app/components/notification_banner/view.rb
- app/components/page_title/view.rb
- app/components/persona/view.rb
- app/components/providers/provider_list/view.rb
- app/components/tab_navigation/view.rb
- app/helpers/application_helper.rb
- spec/components/notification_banner/view_spec.rb
- yarn.lock
> Govuk components 3.0.6 fix breaking issue

- app/controllers/concerns/authentication.rb
- spec/features/auth/persona_spec.rb
Fix alternative support login.
> Fix alternative support login

- .github/actions/deploy/action.yml
- .github/actions/smoke-test/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
- .github/workflows/database-restore.yml
- Makefile
- service_unavailable_page/manifest.yml
Some updates required after the TTAPI to Publish rename
- slack messages
- maintenance page
https://trello.com/c/XjcbypcL/588-rename-ttapi-to-publish
Update workflow slack messages
Update Makefile and app manifest
check config and workflows run ok
> Updates for TTAPI rename to Publish

- app/views/cookie_preferences/show.html.erb
- app/views/publish/users/index.html.erb
- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- spec/support/page_objects/publish/allocations/request/number_of_places.rb
- spec/support/page_objects/publish/allocations/request/who_are_you_requesting_a_course_for.rb
- spec/support/page_objects/publish/provider_contact_details_edit.rb
- spec/support/page_objects/publish/provider_details_edit.rb
- spec/support/page_objects/publish/provider_users.rb
- spec/support/page_objects/publish/provider_visa_sponsorships.rb
- spec/support/page_objects/publish/request_access_new.rb
- spec/support/page_objects/support/allocation_uplift_edit.rb
- spec/support/page_objects/support/allocation_uplift_new.rb
- spec/support/page_objects/support/provider/course_edit.rb
- spec/support/page_objects/support/provider_edit.rb
- spec/support/page_objects/support/provider_new.rb
- spec/support/page_objects/support/user_edit.rb
- spec/support/page_objects/support/user_show.rb
Turn on the GA tracking in prod
- Make some content tweaks
- Turn on GA in prod
- Fix a bunch of failing specs due to selector ambiguity
> [xxx] Turn on GA in prod

- docs/rollover.md
A small update to the rollover docs.
- Update the dates that we will be using
- Remove steps refering to google docs as we don't use these anymore
> Update rollover doc

- app/assets/stylesheets/application.scss
- app/views/pages/course_summary_examples.erb
course summary examples
Amended course summary examples
/how-to-use-this-service/course-summary-examples
> [0272] Amended course summary examples

- config/settings.yml
- config/settings/qa.yml
- config/settings/staging.yml
- spec/components/title_bar/view_spec.rb
- spec/features/publish/accepting_terms_spec.rb
- spec/features/publish/primary_nav_spec.rb
Merging this PR will activate rollover in production.
> Activate rollover in production

- app/controllers/publish/access_requests_controller.rb
- spec/features/support/access_requests/managing_requests_spec.rb
https://trello.com/c/kUTUiG7r/276-fix-access-requests
Fix the broken access request logic so recipient is actually linked up to requested providers.
- Create access request for a test user
- Approve and assert user is given access to the requested providers
> [276] Fix access requests logic

- terraform/.terraform.lock.hcl
- terraform/terraform.tf
Update the azurerm provider so we can maintain compatibility and include latest bug fixes.
> Update azurerm provider to 3.12.0

- docs/support_playbook.md
https://trello.com/c/UNUL7UAq/308-roll-over-courses-to-22-23-cycle-1sk
Adding some support content for doing the manual rollover rake task, as it threw me for a bit
> Add support doc for manually rolling over courses

- app/controllers/publish/courses/deletions_controller.rb
- app/views/publish/courses/draft_rollover/edit.html.erb
- spec/features/publish/viewing_a_course_spec.rb
Some small changes left over from  https://github.com/DFE-Digital/publish-teacher-training/pull/2829
> typos and safe operator

- app/models/user.rb
- spec/models/user_spec.rb
Removing user errors out
Fixed removing user errors out
> [0336] Fixed removing user errors out

- config/environments/test.rb
Tries to fix flakey test https://github.com/DFE-Digital/publish-teacher-training/runs/7452055270?check_suite_focus=true
> Eager load app in CI

- .github/workflows/build-and-deploy.yml
- Rakefile
- app/javascript/application.js
- app/javascript/autocomplete.js
- app/javascript/filters.js
- app/javascript/locations-map.js
- app/javascript/map-popup.js
- jest.config.js
- lib/tasks/govuk_lint.rake
- package.json
- yarn.lock
Javascript linting with standard js
Setup javascript linting with standard js
write some dirty js and use
```cmd
bundle exec rake lint:js
yarn run standard
yarn run standard:fix
```
> [0333] Setup javascript linting with standard js

- docs/support_playbook.md
Expands example for updating `program_type` on a course.
> [xxx] Update support playbook

- app/views/support/data_exports/index.html.erb
- app/views/support/users/index.html.erb
- config/routes.rb
> [xxxx] Amended data exports to use recruitmment cycle

- app/controllers/support/courses_controller.rb
- app/controllers/support/locations_controller.rb
- app/controllers/support/providers_controller.rb
- app/controllers/support/support_controller.rb
Fix support updates in next recruitment cycle for courses and locations
> Fix support updates in next recruitment cycle

- .github/workflows/deploy.yml
- Makefile
- config/settings/loadtest.yml
- terraform/workspace_variables/loadtest.tfvars.json
- terraform/workspace_variables/loadtest_backend.tfvars
New loadtest environment for publish in bat-prod space
- same infrastructure as prod
- manual deploy via deploy workflow or make (not automated)
- Add new env to Makefile
- Add to deploy workflow 
- terraform updates
- Add required rails configuration files
Also added outside of this PR
- required gh secrets
- AZ KV secrets
- AZ storage container
- confirm KV app/infra secrets are as expected for a loadtest
- confirm infrastructure requirements
- if dfe-signin required url's will need to be added to dfe-signin
- deploy-plan loadtest
> Create loadtest environment

- app/views/support/_menu.html.erb
> Remove dev comment from view

- Dockerfile
The base package has been updated with r3 therefore we no longer need to
manually add this.
> Remove manual add of zlib r3

- .github/workflows/database-restore.yml
Tech debt
setup-cf-cli has been moved to DFE-Digital/github-actions/setup-cf-cli
Same as all other repos: https://github.com/DFE-Digital/teaching-vacancies/blob/a63bdff7ea58ff86775665aaa315886d017dc2d2/.github/workflows/restore_db.yml#L57
> [565] Replace reference to deprecated action

- app/components/header/view.html.erb
- spec/support/page_objects/publish/header.rb
Active state (blue link) for notification
Amended to having no active state (blue link) for notification
> [0400] Amended to having no active state (blue link) for notification

- Gemfile.lock
- app/views/publish/courses/course_button_panel/_published.html.erb
https://trello.com/c/30wXyVPo/401-update-view-on-find-link
- Add visually hidden text to View on Find link
> [401] Update view on find link

- app/decorators/application_decorator.rb
draft vs empty there can only be one
Fixed draft vs empty there can only be one
> [0406] Amended to read draft vs empty

- app/controllers/find/application_controller.rb
- app/controllers/find/search/age_groups_controller.rb
- app/forms/find/courses_by_location_or_training_provider_form.rb
- app/views/find/application/index.html.erb
- config/locales/en.yml
- config/locales/find.yml
- config/routes/find.rb
- spec/features/find/view_pages_spec.rb
- spec/support/page_objects/find/courses_by_location_or_training_provider.rb
This is the initial form when you come to `/find`. 
JS to follow in separate PR's. 
Add the fundamental Find search page
Is it the same as the current version?
> Course search initial form

- terraform/.terraform.lock.hcl
- terraform/modules/paas/main.tf
- terraform/modules/paas/variables.tf
- terraform/terraform.tf
- terraform/variables.tf
- terraform/workspace_variables/loadtest.tfvars.json
Load tests filled up Logit.io
Make external logging optional and disable it for the loadtest environment
Run terraform plan against the existing environments
https://trello.com/c/7WBnFwdk/292-load-test-find
> [292] Disable external logging in load test environment

- .tool-versions
> [xxxx] Fixed out of date bundler

- app/views/find/application/index.html.erb
- spec/features/find/course_searches_spec.rb
- spec/features/find/view_pages_spec.rb
- spec/support/page_objects/find/courses_by_location_or_training_provider.rb
> [xxxx] Fixed misleading test

- app/assets/stylesheets/find_application.scss
- app/assets/stylesheets/govuk_style_setup.scss
- app/assets/stylesheets/js-enabled.scss
- app/assets/stylesheets/publish_application.scss
> [xxxx] Fixed css issues

- terraform/workspace_variables/production.tfvars.json
- terraform/workspace_variables/sandbox.tfvars.json
- terraform/workspace_variables/staging.tfvars.json
Add www2, staging2, sandbox2 configuration for the find app
> Add the additional configuration for find2 domains

- app/controllers/find/search/locations_controller.rb
- app/forms/find/courses_by_location_or_training_provider_form.rb
- app/javascript/find/application.js
- app/javascript/find/setup-autocomplete.js
- app/views/find/search/locations/index.html.erb
- config/locales/en.yml
- spec/features/find/course_searches_spec.rb
- spec/forms/find/courses_by_location_or_training_provider_form_spec.rb
- spec/support/page_objects/find/courses_by_location_or_training_provider.rb
Course search initial flow - validation
Added Course search initial flow - validation
Clicking `continue` when you have pass validation will error out as the user journey is in complete.
> [0421] Course search initial flow - validation

- app/controllers/find/search/age_groups_controller.rb
- app/forms/find/age_groups_form.rb
- app/views/find/search/age_groups/index.html.erb
- config/locales/en.yml
- config/locales/find.yml
- config/routes/find.rb
- spec/features/find/course_searches_spec.rb
- spec/forms/find/age_groups_form_spec.rb
- spec/support/page_objects/find/age_groups.rb
Course search age group form
Added Course search age group page
> [0384] Course search age group form

- config/analytics.yml
- config/analytics_blocklist.yml
https://trello.com/c/fRgq5XAQ/449-sync-userpermissions-table-to-big-query-for-data-insights-team
- Syncs up the `user_permission` model to give BAs an updated way to query provider users
- Remove redundant org models from the sync list
> [449] Sync user permissions table to big query

- Gemfile.lock
> [xxxx] Fixed gem file

- app/components/find_interface/courses/international_students_component/view.html.erb
- app/components/find_interface/courses/international_students_component/view.rb
- config/locales/find.yml
- spec/components/find_interface/courses/international_students_component/view_preview.rb
- spec/components/find_interface/courses/international_students_component/view_spec.rb
Update international visa component
Amended to use the course vs provider version of `can_sponsor_student_visa` & `can_sponsor_skilled_worker_visa`
Requires  https://github.com/DFE-Digital/publish-teacher-training/pull/2964
> [0438] Update international visa component

- Gemfile.lock
- app/services/subjects/financial_incentive_creator_service.rb
https://trello.com/c/Jgi2ZgGI/485-financial-incentives-new-figures
- Update the financial incentive figures for the next cycle
Check the figures with the trello ticket. This PR doesn't actually seed in the values. We won't be able to do that until we end rollover and begin the new cycle. A follow up PR will occur
> [485] Update financial incentives list

- docs/support_playbook.md
Instructions for transfer of courses to another provider
Update docs with instructions
Trello card [505](https://trello.com/c/SyjMR5lT/505-update-support-playbook)
> [119] Update support playbook

- Gemfile.lock
- app/controllers/publish/courses/apprenticeship_controller.rb
- app/controllers/publish/courses/skilled_worker_visa_sponsorship_controller.rb
- app/services/publish/course_creation_step_service.rb
- app/views/publish/courses/confirmation.html.erb
- app/views/publish/courses/skilled_worker_visa_sponsorship/_form_fields.html.erb
- app/views/publish/courses/student_visa_sponsorship/_form_fields.html.erb
- spec/features/publish/courses/new_visa_sponsorship_spec.rb
New course creation for Scitt and HEI 
New course creation for scitts and hei 
along came the visa
during the visa creation
During the creation of course when apprenticeship is selected as `no` then there is student visa question
During the creation of course when apprenticeship is selected as `yes` then there is skilled worker visa question
A relative link is shown if the provider is HEI and do not sponsor for the visa in question
A relative link is shown if the provider is Scitt and do not sponsor for the skilled visa
> [0433] Handle visa collection in new course flow for scitts/heis

- docs/support_playbook.md
> [xxxx] Fixed spelling 🥴

- app/views/publish/courses/student_visa_sponsorship/edit.html.erb
> [xxxx] Remove dupe inset text

- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
- spec/features/publish/e2e/new_course_spec.rb
Turns on the new visa flow in prod
> [xxx] Enable visa flow in prod

- app/models/course.rb
- app/views/publish/courses/_basic_details_tab.html.erb
- spec/factories/users.rb
- spec/features/publish/viewing_a_course_details_spec.rb
- spec/support/page_objects/publish/provider_courses_details.rb
- https://trello.com/c/fD07l44U/547-add-change-links-to-update-funding-visa-for-scheduled
- Allows providers to update the visa settings for scheduled courses
- Check you can change these settings for scheduled courses
> [547] Allow visa to be updated for scheduled

- spec/smoke/find/course_spec.rb
Temporarily skip for now while find is closed
> [xxx] Skip smoke test as cycle has ended for now

- app/decorators/course_decorator.rb
- config/settings.yml
- spec/decorators/course_decorator_spec.rb
- spec/features/publish/viewing_a_course_preview_spec.rb
- spec/features/publish/viewing_a_course_spec.rb
- spec/helpers/find/subject_helper_spec.rb
> [xxxx] Fixed bursaries and scholarships is not announced

- Dockerfile
For https://security.snyk.io/vuln/SNYK-ALPINE315-EXPAT-3062885
https://trello.com/c/NkBxwoiL
Manually add the fixed version of the expat package
Ensure Snyk does not error
> Expat vulnerability fix

- Gemfile
- Gemfile.lock
- app/controllers/find/location_suggestions_controller.rb
- app/javascript/find/__snapshots__/autocomplete.spec.js.snap
- app/javascript/find/application.js
- app/javascript/find/autocomplete.js
- app/javascript/find/autocomplete.spec.js
- app/services/location_suggestion.rb
- app/views/find/search/locations/index.html.erb
- config/routes/find.rb
- config/settings.yml
- package.json
- spec/fixtures/api_responses/location-suggestions.json
- spec/requests/find/locations_suggestions_spec.rb
- spec/support/stubbed_requests/location_suggestions.rb
- yarn.lock
The js for searching against `By city, town or postcode` 
Added the js for searching against `By city, town or postcode` 
https://publish-teacher-training-pr-3089.london.cloudapps.digital/find
Auto complete pops up when 3 or more characters is typed
Requires `settings.google.gcp_api_key`
> [0563] Course search initial form by city javascript version

- Procfile.dev
- README.md
Had some issues setting up this project on my device.
Updated instructions in readme and procfile to improve setup experience.
Yarn build command is run before starting server.
> Updating readme to improve setup experience

- Gemfile
- Gemfile.lock
> [xxxx] Added ruby lsp to gemfile

- app/components/find_interface/feature_toggle_component.html.erb
- app/components/find_interface/maintenance_banner_component.html.erb
- app/components/find_interface/utility/summary_card_component.html.erb
- app/components/find_interface/utility/summary_list_component.html.erb
- app/views/find/confirm_environment/new.html.erb
- app/views/find/feature_flags/index.html.erb
- app/views/find/pages/maintenance.html.erb
- app/views/layouts/find_layout.html.erb
There are a few erb linting errors which have crept into CI. This is the fix.
> Fix erb linting errors

- swagger/public_v1/api_spec.json
- swagger/public_v1/component_schemas/CourseFilter.yml
Add the campaign_name to the CourseFilter docs in the open API.
What it says on the tin
> Add campaign_name to CourseFilter

- app/models/concerns/with_qualifications.rb
- app/models/course.rb
- app/serializers/api/v3/serializable_course.rb
- spec/requests/api/v3/providers/courses/index_spec.rb
- spec/requests/api/v3/providers/courses/show_spec.rb
We are changing our course qualification abbreviations for the first instance. 
- Expose `extended_qualification_descriptions` method to V3 Serializable Course
- Define `extended_qualification_descriptions` method to use in place of `description` method
- Fix tests
- Pull down this PR and the [respective PR](https://github.com/DFE-Digital/find-teacher-training/pull/1620
) for Find locally. 
- Navigate to courses with different qualification
- Ensure the expanded description is correct.
_________________________________________________________________________________________________________
> Expand qualification abbreviations on first instance eg pgce and qts

- app/services/course_search_service.rb
- app/view_objects/find/results_view.rb
- spec/view_objects/find/results_view_spec.rb
Sorted by
Get sorted
https://publish-teacher-training-pr-3157.london.cloudapps.digital/find/results
> [0583] Course search filters sorted by

- app/views/publish/users/index.html.erb
- config/locales/en.yml
- config/settings.yml
- config/settings/review.yml
Restyle the existing users list in line with the prototype, as part of the new user management work
Put this behind a new feature flag
https://publish-teacher-training-pr-3154.london.cloudapps.digital/publish/organisations/1A4/users
> Restyle existing users list

- docs/support_playbook.md
Instruction to fix visa sponsorship issue in support playbook
> update for visa sponsorship issue

- app/controllers/concerns/error_handlers/base.rb
- app/controllers/publish/courses/gcse_requirements_controller.rb
- docs/lib/govuk_tech_docs/open_api/extension.rb
- spec/models/provider_spec.rb
- spec/requests/api/v3/courses/index_spec.rb
- spec/services/v3/course_search_service_spec.rb
- spec/support/with_stubbed_stdout.rb
:ship: 
Fixes this foolishness https://github.com/DFE-Digital/publish-teacher-training/pull/3174
> [xxxx] Fixed linter issues

- app/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view.rb
- config/locales/find.yml
- spec/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view_preview.rb
- spec/components/find_interface/courses/financial_support/scholarship_and_bursary_component/view_spec.rb
- spec/factories/subjects/secondary_subjects.rb
Information about bursaries and scholarships
Added scholarships info for applicable subjects
The same as https://github.com/DFE-Digital/find-teacher-training/pull/1641
- Chemistry
- https://publish-teacher-training-pr-3179.london.cloudapps.digital/find/course/2CG/Q774
- Computing
- https://publish-teacher-training-pr-3179.london.cloudapps.digital/find/course/2CG/D526
- Mathematics
- https://publish-teacher-training-pr-3179.london.cloudapps.digital/find/course/2CG/A949
- Physics
- https://publish-teacher-training-pr-3179.london.cloudapps.digital/find/course/2CG/M064
- French
- https://publish-teacher-training-pr-3179.london.cloudapps.digital/find/course/2CG/A568
- German
- https://publish-teacher-training-pr-3179.london.cloudapps.digital/find/course/2AL/L288
- Spanish
- …
> [0866] Updating information about bursaries and scholarships

- config/settings/qa.yml
Activating user management in QA to test the feature as a whole before going live.
> Activate user management in QA

- app/assets/stylesheets/components/find/_filter.scss
- app/views/find/result_filters/_all.html.erb
- app/views/find/result_filters/_salary_filter.html.erb
apply filters button
To improve usability, move the 'Apply filters' button to the top of the filters panel.
Same as https://github.com/DFE-Digital/find-teacher-training/pull/1664
> [0908] Amended apply filters button to top of filters panel

- spec/smoke/find/course_spec.rb
Fixes an issue with the smoke test not being able to find any courses to check
> [xxx] Return all primary courses for smoke test

- app/controllers/publish/users_check_controller.rb
- app/controllers/publish/users_controller.rb
- app/controllers/support/providers/users_check_controller.rb
- app/controllers/support/providers/users_controller.rb
> [xxxx] Fixed case sensitivity

- app/components/find/results/search_result_component.rb
Removing unnecessary full stops.
> Remove full stops

- spec/services/course_search_service_spec.rb
Course search service
Affixed with more tests as the api uses course search underneath
Is there enough tests?
> [0962] Added more tests

- app/views/errors/not_found.html.erb
Updating the 404 page content in line with the prototype
> Update 404 page content

- app/views/errors/internal_server_error.html.erb
Updating the 500 page content in line with the prototype
> Update 500 page content

- service_unavailable_page/web/public/internal/index.html
> Update 503 page content

- app/components/find/location_subject_filter_component.html.erb
A small content tweak.
Search for a course by location and check that the new content shows.
> Content tweak

- terraform/workspace_variables/review.tfvars.json
Enable find route for review apps
Set "enable_find" to true in review.tfvars.json
Deploy review app
> Enable find route for review apps

- app/components/find/results/search_result_component.html.erb
- app/components/find/results/search_result_component.rb
- config/locales/find.yml
Ports this PR https://github.com/DFE-Digital/find-teacher-training/pull/1620 into New Find
> [xxx] Port over missing accessibility stuff

- .gitignore
- app/services/find/result_summary_service.rb
- app/views/find/results/index.html.erb
- spec/services/find/result_summary_service_spec.rb
This PR mostly ports over https://github.com/DFE-Digital/find-teacher-training/pull/1651/files.
> [1004] Port over missing Find bits

- terraform/workspace_variables/production.tfvars.json
For the Findpub merge, add the find routes to production.
To be merged AFTER the find routes have been mapped to publish,
and imported into terraform state.
Add or update required variables in production.tfvars.json
deploy-plan
> Add find routes to production

- config/settings/production.yml
- config/settings/qa.yml
- config/settings/sandbox.yml
- config/settings/staging.yml
Fixes https://dfe-teacher-services.sentry.io/issues/3920148348/?project=1377944&query=is%3Aunresolved&referrer=issue-stream
> Fix referrers list

- app/controllers/find/application_controller.rb
- app/controllers/find/courses_controller.rb
Fixes the following Sentry errors:
https://dfe-teacher-services.sentry.io/issues/3920146794/?project=1377944&query=is%3Aignored&referrer=issue-stream
https://dfe-teacher-services.sentry.io/issues/3920210013/?project=1377944&query=is%3Aignored&referrer=issue-stream
> A few fixes for some Find Sentry errors

- app/decorators/course_decorator.rb
> [xxxx] Fixed nil issues

- app/views/cookie_preferences/show.html.erb
- app/views/find/cookie_preferences/show.html.erb
- config/application.rb
- config/settings.yml
https://trello.com/c/ZBahxUh0/1024-bug-truck-load-of-cookies
> [1024] Update cookie settings to be aligned

- app/services/publish/course_creation_step_service.rb
> [xxxx] Removed old workflow step

- app/decorators/course_decorator.rb
- app/views/publish/courses/confirmation.html.erb
- spec/features/publish/course_confirmation_spec.rb
- spec/features/publish/courses/new_start_date_spec.rb
- spec/features/publish/courses/new_visa_sponsorship_spec.rb
- spec/support/page_objects/publish/course_confirmation.rb
Content changes on the check your answers page
Removed course description
Removed course preview
Removed unneeded text
Added cancel link
Amended course name to be course title
Amended page title
Added page caption
> [0998] Content changes on the check your answers page

- Dockerfile
Fix libcrypto1.1 vulnerability in the docker image
Update Dockerfile
Check build workflow completes without errors
> Update libcrypto1.1 to fix snyk vulnerability

- Dockerfile
SNYK vulnerabilities
https://security.snyk.io/vuln/SNYK-ALPINE315-PKGCONF-3244398
https://security.snyk.io/vuln/SNYK-ALPINE315-GIT-3319831
Add fixed version to Dockerfile
check build SNYK scan
> Fix SNYK vulnerability for pkgconf and git

- spec/features/publish/courses/new_modern_languages_spec.rb
Fix flakey test.
Remove EFL from the language sample as the subject was previously removed
🚢
> Remove EFL from the test language sample

- app/controllers/concerns/filter_parameters.rb
- app/services/course_search_service.rb
- spec/services/course_search_service_spec.rb
A couple of Sentry fixes for:
- https://dfe-teacher-services.sentry.io/issues/3952984227/?project=1377944&query=is%3Aignored&referrer=issue-stream
- https://dfe-teacher-services.sentry.io/issues/3922486907/?project=1377944&query=is%3Aignored&referrer=issue-stream
> [xxx] A few more Sentry fixes

- guides/setup-development.md
Slight doc update to allow correct cmd sequence in gias_import to allow console output.
> 1117 another doc update

- Gemfile
- Gemfile.lock
- app/components/find/deadline_banner_component.html.erb
- app/components/find/header/view.html.erb
- app/components/find/maintenance_banner_component.html.erb
- app/components/find/utility/summary_list_component.html.erb
- app/components/flash_banner.html.erb
- app/components/header.html.erb
- app/components/providers/provider_list/view.html.erb
- app/helpers/application_helper.rb
- app/views/layouts/_cookie_banner.html.erb
- app/views/layouts/find_layout.html.erb
- app/views/magic_links/new.html.erb
- app/views/publish/courses/_basic_details_tab.html.erb
- app/views/publish/courses/_copy_content_warning.html.erb
- app/views/publish/courses/_description_content.html.erb
- app/views/publish/courses/confirmation.html.erb
- app/views/publish/courses/preview.html.erb
- app/views/publish/users/show.html.erb
- app/views/publish/users_check/show.html.erb
- app/views/publish/users_edit_check/show.erb
- app/views/support/providers/users/show.html.erb
- app/views/support/providers/users_check/show.html.erb
- app/views/support/users/show.html.erb
Upgrading govuk components to 4.0.0a2 as the alpha version has code that we can use to build our summary card. It's due for release soon, so we may as well get ahead of the curve. 
- Upgrade govuk components to 4.0.0a2
- Fix breaking changes 
- Fix breaking tests
- Have a play around with the app in areas where components are heavily used and check that everything still works as expected.
> [1108] Amended govuk components and related dependency

- package.json
- yarn.lock
Bump govuk-frontend to 4.5.0 as we require some of the CSS from a more recent version.
Visually inspect as many pages as possible on the review app and check if everything looks in order and correct.
> Bump govuk-frontend to 4.5.0

- app/views/pages/performance_dashboard.html.erb
> [xxxx] Amended `tab` to `with_tab"`

- yarn.lock
We upgraded govuk-frontend to 4.5.0 in #3423. These changes should have been commited in that PR. 
:shipit:
> Add updated yarn file to codebase

- .github/workflows/build-and-deploy.yml
> [xxxx] Removed db:setup

- .github/workflows/build-and-deploy.yml
> [xxxx] Removed curl

- .github/PULL_REQUEST_TEMPLATE.md
Data insights team
Data insights team need to know 
Inform data insights team due to database changes is on checklist
> [xxxx] Added data insights team to PR checklist

- config/initializers/canonical_rails.rb
> [xxxx] Amended host

- app/views/support/providers/locations/new_multiple/show.html.erb
> [xxxx]  Fixed back links that breaks after validation

- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
- spec/features/support/providers/locations/creating_multiple_locations_spec.rb
Activate add multiple locations in production
:shipit:
> Activate add multiple locations in production

- Gemfile
- Gemfile.lock
Ruby LSP
Remove it
https://github.com/Shopify/vscode-ruby-lsp#migrating-from-bundle
> [xxxx] Removed Ruby LSP

- app/components/find/courses/fees_component/view.html.erb
> [1152] Fixed linter issue

- app/controllers/concerns/goto_preview.rb
- app/controllers/publish/courses/base_funding_type_controller.rb
- app/controllers/publish/courses/course_information_controller.rb
- app/controllers/publish/courses/degrees/grade_controller.rb
- app/controllers/publish/courses/degrees/start_controller.rb
- app/controllers/publish/courses/degrees/subject_requirements_controller.rb
- app/controllers/publish/courses/gcse_requirements_controller.rb
- app/helpers/find/goto_preview_helper.rb
- app/views/publish/courses/course_information/edit.html.erb
- app/views/publish/courses/degrees/grade/edit.html.erb
- app/views/publish/courses/degrees/start/edit.html.erb
- app/views/publish/courses/degrees/subject_requirements/edit.html.erb
- app/views/publish/courses/fees/edit.html.erb
- app/views/publish/courses/gcse_requirements/edit.html.erb
- spec/controllers/concerns/goto_preview_spec.rb
- spec/helpers/find/goto_preview_helper_spec.rb
There is a duplications
There is no duplications
Nothing is broken?
DRY principle
> [1153] Clean up duplications with regards to `goto_preview`

- config/settings.yml
Feedback link
Amended the form to ms version
> [1205] Amended the form to ms version

- app/forms/form.rb
- app/services/stores/base_store.rb
- app/services/stores/course_store.rb
- app/services/stores/provider_store.rb
- app/services/stores/user_store.rb
- spec/services/stores/shared_examples/store.rb
Clean up
Removing it
Nothing is broken
> [1194] Remove store and form tech debt

- Dockerfile
SNYK recommendations for the build image
Updates to the Dockerfile
Check snyk scan in build workflow
> SNYK fixes added to Dockerfile

- app/views/publish/providers/schools/new.html.erb
- config/settings/qa.yml
Turn on in QA for product demos.
> [xxx] Switch on Gias school search in QA

- app/javascript/find/autocomplete.js
- app/javascript/find/autocomplete.spec.js
- app/javascript/publish/autocomplete.js
- app/javascript/publish/autocomplete.spec.js
- app/javascript/utils/request_helper.js
- app/javascript/utils/request_helper.spec.js
- app/views/publish/providers/school_search/new.html.erb
- config/settings.yml
- config/settings/development.yml
- config/settings/qa.yml
- config/settings/review.yml
- spec/features/publish/managing_schools_spec.rb
- spec/features/publish/searching_for_a_school_spec.rb
Switches on the school search for prod. Also cleaned up some of the duplicated javascript and added a debounce to the lookup.
> [xxx] Turn on Gias search for prod

- guides/setup-development.md
I ran into some issues setting up caddy
I've added some suggestions if anyone gets an error message using caddy run
> updated read me to help with caddy error

- app/controllers/support/providers/onboarding/checks_controller.rb
- app/controllers/support/providers/onboarding/contacts_controller.rb
- app/controllers/support/providers/onboardings_controller.rb
- app/forms/support/provider_contact_form.rb
- app/forms/support/provider_form.rb
- app/helpers/support/goto_confirmation_helper.rb
- app/models/provider.rb
- app/views/support/providers/onboarding/checks/show.html.erb
- app/views/support/providers/onboarding/contacts/new.html.erb
- app/views/support/providers/onboardings/new.html.erb
- config/locales/en.yml
- config/routes/support.rb
- spec/features/support/providers/onboarding_a_new_provider_spec.rb
- spec/forms/support/provider_contact_form_spec.rb
- spec/forms/support/provider_form_spec.rb
- spec/helpers/support/goto_confimation_helper_spec.rb
- spec/models/provider_spec.rb
Provider check your answers page
Added provider check your answers page
The journey is complete
> [1196] Added provider check your answers page

- app/views/publish/providers/accredited_providers/index.html.erb
- spec/features/publish/accredited_provider_spec.rb
> [1272] Fixed broken merge

- config/settings.yml
> Turn on magic link

- config/settings.yml
> [xxx] Disable magic link

- app/views/cookie_preferences/show.html.erb
- app/views/find/cookie_preferences/show.html.erb
- config/initializers/content_security_policy.rb
- config/settings.yml
- config/settings/production.yml
https://trello.com/c/AuIsS50G/1302-replace-gtm-container-and-update-cookies-page
- Update tiny copy in cookie pages for Find / Publish
- Whitelist floodlight tags
- Update GTM container id
Publish - https://publish-teacher-training-pr-3591.london.cloudapps.digital/cookies
Find - https://find-pr-3591.london.cloudapps.digital/cookies
> [1302] Add floodlight tags to CSP

- app/controllers/publish/courses/withdrawals_controller.rb
- app/forms/publish/course_withdrawal_form.rb
- app/views/publish/courses/application_status/new.html.erb
- app/views/publish/courses/withdrawals/edit.html.erb
- spec/features/publish/courses/withdrawing_a_course_spec.rb
- spec/forms/publish/course_withdrawal_form_spec.rb
Course Withdrawal
Removed the course code check method
Added additional text to show to user when they try to withdraw an open course
it works?
> [1288] Updated course withdrawal

- config/settings/qa.yml
Activate open closed course in QA
> [xxxx] Activate open closed course in QA

- app/views/find/courses/show.html.erb
- app/views/publish/courses/accredited_provider/new.html.erb
- app/views/publish/providers/accredited_providers/_can_remove.html.erb
- app/views/support/providers/accredited_providers/_can_remove.html.erb
- config/settings.yml
- spec/features/find/search/viewing_a_course_spec.rb
Fixes some of the issues spotted in the snag.
> [xxx] A few snag fixes

- app/views/find/switcher/cycles.html.erb
Prevent updates to cycle switcher in prod
> [1366] Prevent updates to cycle switcher in prod

- spec/factories/site_statuses.rb
- spec/features/find/search/viewing_a_course_spec.rb
- spec/features/publish/viewing_a_course_preview_spec.rb
- spec/models/course/publish_sites_spec.rb
- spec/models/course/publishable_spec.rb
- spec/models/course/withdraw_spec.rb
- spec/models/course_spec.rb
- spec/models/site_status_spec.rb
- spec/services/courses/copy_to_provider_service_spec.rb
- spec/view_objects/find/results_view_spec.rb
pointless traits
Remove it
:shipit:
> [1332] Remove pointless traits

- config/settings/rollover.yml
Activating rollover in the rollover environment for testing purposes. The script has already been run.
> [1354] Activate rollover in rollover environment

- app/components/find/courses/about_schools_component/view.html.erb
`and vacancies`
Remove it
:shipit:
> [1332] Remove `and vacancies` from view

- app/models/recruitment_cycle.rb
Update dates on course page title. 
:shipit:
> [xxxx] Update dates on course page title

- config/settings/qa.yml
> [1372] Activate rollover in QA

- app/controllers/publish/courses/applications_open_controller.rb
- app/controllers/publish/courses/study_sites_controller.rb
- app/controllers/publish/courses_controller.rb
- app/decorators/course_decorator.rb
- app/models/concerns/publish/course_basic_detail_concern.rb
- app/models/course.rb
- app/services/courses/creation_service.rb
- app/services/workflow_step_service.rb
- app/views/publish/courses/confirmation.html.erb
- app/views/publish/courses/study_sites/new.html.erb
- config/locales/en.yml
- config/routes/publish.rb
- spec/controllers/publish/courses_controller_spec.rb
- spec/features/publish/course_confirmation_spec.rb
- spec/features/publish/courses/new_schools_spec.rb
- spec/features/publish/courses/new_visa_sponsorship_spec.rb
- spec/features/publish/courses/publishing_a_course_spec.rb
- spec/features/publish/e2e/new_course_spec.rb
- spec/models/course/publishable_spec.rb
- spec/services/courses/creation_service_spec.rb
- spec/services/workflow_step_service_spec.rb
- spec/support/feature_helpers/new_course_param_helper.rb
- spec/support/page_objects/publish/course_confirmation.rb
- spec/support/page_objects/publish/courses/new_study_sites.rb
For this ticket we’ll need to add a new study site step in the add course flow
Done when
When creating a new course, i am presented with a question about adding study sites
The study sites should be sourced from my provider
Addition of study site step to course flow
add a course, study site step is after school step
> [1328] study sites course step

- app/views/find/courses/financial_support/_salaried.html.erb
Update content for financial information of salaried courses
Update financial information content for salaried courses so that candidatea better understand how much money they will receive
> Update Salaried Course Content on Find

- app/views/find/courses/financial_support/_salaried.html.erb
Reverts DFE-Digital/publish-teacher-training#3681
> Revert "Update Salaried Course Content on Find"

- app/controllers/publish/courses/study_sites_controller.rb
- app/helpers/view_helper.rb
- app/views/publish/courses/_basic_details_tab.html.erb
- app/views/publish/courses/index.html.erb
- app/views/publish/providers/study_sites_check/show.html.erb
- config/locales/en.yml
- spec/features/publish/add_course_button_spec.rb
- spec/features/publish/courses/editing_study_sites_spec.rb
Fixing a few snags before the release of the study sites feature.
See commits
:shipit:
> [302] Fix study sites snags

- app/views/find/courses/financial_support/_salaried.html.erb
The translation incorrect is not referenced correctly. 
Update it
:shipit:
> Update reference to translation

- app/controllers/pages_controller.rb
Skip before action on study sites/schools guidance page
Navigate to the study sites guidance page and ensure you don't need to be authenticated.
> Skip before action on study_sites guidance page

- config/settings.yml
- config/settings/qa.yml
This PR will activate rollover in all environments, including production.
🚢 🚢 🚢
> Activate rollover in all envs

- app/forms/support/school_form.rb
Remove validation for code as code is no longer in use and this is causing Sentry errors.
https://dfe-teacher-services.sentry.io/issues/4312626004/?alert_rule_id=11137790&alert_type=issue&project=1377944&referrer=slack
> Remove validation for code

- Dockerfile
Snyx vulnerability monitor detected a vulnerability in a dependency in the Docker image.
https://security.snyk.io/vuln/SNYK-ALPINE315-NGHTTP2-5788360
`nghttp2` and `nghttp2-libs` need to be upgrade to a version greater or equal to `1.46.0-r1`
> Update nghttp2-libs in the Dockerimage

- app/views/find/courses/_advice.html.erb
- config/locales/en.yml
- config/locales/find.yml
- These 2 URLs have changed
- I've updated these 2 URLs
- Have the URLs updated?
> Update URLs on Find and Publish to reflect new GIT Links

- app/views/personas/index.html.erb
The persona "Susy" no longer works. This is the fix.
Update the persona to one that is active this cycle. 
Login as Susy on the review app.
> [542] Fix the persona Susy

- app/views/find/result_filters/_all.html.erb
- spec/features/find/result_page_filters/applications_open_spec.rb
- spec/features/find/result_page_filters/degree_required_spec.rb
- spec/features/find/result_page_filters/qualifications_spec.rb
- spec/features/find/result_page_filters/salary_spec.rb
- spec/features/find/result_page_filters/send_spec.rb
- spec/features/find/result_page_filters/study_type_spec.rb
- spec/features/find/result_page_filters/visa_spec.rb
https://ukgovernmentdfe.slack.com/archives/C05CFF8M8KA/p1693556736917369
| Before     | After |
| ----------- | ----------- |
| ![image (23)](https://github.com/DFE-Digital/publish-teacher-training/assets/35870975/f4158d4f-c8db-48fc-9d8e-f6a31dcf1bcb)   |  ![image (24)](https://github.com/DFE-Digital/publish-teacher-training/assets/35870975/8c5815d7-9e13-4051-b34c-a0f159e6a7f5) |
> Changing results filter order

- spec/features/find/search/viewing_a_course_spec.rb
- spec/features/publish/viewing_a_course_preview_spec.rb
Tests are failing on main because at the current point in time the apply link is (correctly) no longer showing. This is a fix.
:shipit:
> Fix tests failing on main

- app/services/subjects/financial_incentive_creator_service.rb
2024 bursaries - based on the following announcement from midnight.
https://www.gov.uk/government/publications/funding-initial-teacher-training-itt/funding-initial-teacher-training-itt-academic-year-2024-to-2025
> Update the 2024 financial incentives

- terraform/aks/workspace_variables/production_aks.tfvars.json
- terraform/aks/workspace_variables/sandbox_aks.tfvars.json
Reduce usage to reduce the bill
The web application and worker were very quiet during peak time. Setting to the same parameters as Apply.
> [723] Reduce AKS pod usage

- app/services/workflow_step_service.rb
- spec/services/workflow_step_service_spec.rb
Creating further education courses
Fixed the ordering of conditions
Can create further education courses for provider `B38`
https://publish-review-3887.test.teacherservices.cloud/publish/organisations/B38/2024/courses/level/new
> [2294] Fixed the ordering of conditions

- Dockerfile
> Update dockerfile nghttp2

- app/components/find/results/results_component.html.erb
Visible if you inspect the source.
> Remove comment

- app/views/find/search/visa_status/new.html.erb
- config/locales/find.yml
- spec/features/find/search/across_england/further_education_spec.rb
- spec/features/find/search/across_england/primary_spec.rb
- spec/features/find/search/across_england/secondary_spec.rb
- spec/features/find/search/editing_a_search_spec.rb
Updating the visa sponsorship question on Find in an effort to reduce rejection rates.
Link to the page in the review app: https://find-review-3906.test.teacherservices.cloud/visa-status?age_group=secondary&l=2&subjects%5B%5D=&subjects%5B%5D=C1
> [859] Update content on visa question

- .github/workflows/build-and-deploy.yml
Let dependabot create review apps
Add secrets
Allow dependabot to run required steps in build workflow, so it can run the snyk scan.
check workflows
> Add dependabot review apps

- app/views/find/courses/_advice.html.erb
- app/views/layouts/_find_footer.html.erb
https://trello.com/c/ExTBmged/453-edit-get-help-content-on-prototype-and-prod
Remove free of charge.
> Remove free of charge

- terraform/aks/.terraform.lock.hcl
- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/staging_aks.tfvars.json
Add evaluation_total_count to postgres in the staging env
> Add evaluation_total_count to postgres

- terraform/aks/databases.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/staging_aks.tfvars.json
Add alert window size to postgres and redis
> Add alert window size to postgres and redis

- .tool-versions
- Dockerfile
- docs/.tool-versions
- package.json
Fix Docker build
- Update Ruby base image version to ruby:3.1-alpine3.19
- Update Nodejs version to 20.x
> Docker build: Update Ruby base image and Nodejs version

- Gemfile.lock
Reverts DFE-Digital/publish-teacher-training#3962
> Revert "Bump sidekiq-cron from 1.10.1 to 1.12.0"

- .github/actions/restore/action.yml
upload-artifact has been updated to v4, and this requires download-artifact to be at the same version
update in github actions
check change looks ok
> Update download-artifact to v4

- app/controllers/find/feature_flags_controller.rb
- app/services/find/cycle_timetable.rb
- app/views/find/switcher/cycles.html.erb
- config/application.rb
- config/rubocop/rails.yml
- spec/rails_helper.rb
The production env under AKS is `production_aks`, not `production`
> Refactor production check

- app/controllers/api/public/v1/application_controller.rb
- app/controllers/api/public/v1/courses_controller.rb
- app/controllers/api/public/v1/providers/courses/locations_controller.rb
- app/controllers/api/public/v1/providers/courses_controller.rb
- app/controllers/api/public/v1/providers/locations_controller.rb
- app/controllers/api/public/v1/providers_controller.rb
- spec/controllers/api/public/v1/courses_controller_spec.rb
- spec/controllers/api/public/v1/providers/courses/locations_controller_spec.rb
- spec/controllers/api/public/v1/providers/courses_controller_spec.rb
- spec/controllers/api/public/v1/providers/locations_controller_spec.rb
- spec/controllers/api/public/v1/providers_controller_spec.rb
- spec/docs/courses_spec.rb
- spec/docs/providers/courses/locations_spec.rb
- spec/docs/providers/courses_spec.rb
- spec/docs/providers/locations_spec.rb
- spec/docs/providers_spec.rb
- swagger/public_v1/api_spec.json
Reverts DFE-Digital/publish-teacher-training#4011
> Revert "Support getting resources from the current recruitment cycle"

- .github/actions/restore/action.yml
- .github/workflows/database-restore.yml
Failure after adding RBAC: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/7720580172/job/21045712676
Add the kubelogin install step
Same as the deploy workflow
> [937] Add missing kubelogin to DB restore workflow

- Dockerfile
> upgraded libxml

- .tool-versions
Update the Azure version so that it is the same as Apply. I was getting errors with the current version.
> Update azure version to align with Apply

- guides/support_playbook.md
Documentation for adding admin users via support.
> [1481] Add documentation for adding an admin user via support

- app/views/find/search/visa_status/new.html.erb
- config/locales/find.yml
Updating the link on the Find visa page to be the correct one. 
🚢
> [1437] Update link on Find visa page

- spec/components/find/courses/financial_support/fees_and_financial_support_component/view_preview.rb
The preview is not rendering because subjects is undefined, this is the fix.
Try it on the review app: https://publish-review-4121.test.teacherservices.cloud/view_components/find/courses/financial_support/fees_and_financial_support_component/view/scholarship_and_bursary
> The preview is not rendering because subjects is undefined

- app/view_objects/find/results_view.rb
- spec/features/find/search/location_options_spec.rb
Reverts DFE-Digital/publish-teacher-training#4071
This requires additional functionality first.
> Revert "Decrease the find radius search range to 50 miles"

- terraform/aks/statuscake.tf
- terraform/aks/variables.tf
- terraform/aks/workspace_variables/production_aks.tfvars.json
- terraform/aks/workspace_variables/qa_aks.tfvars.json
- terraform/aks/workspace_variables/sandbox_aks.tfvars.json
- terraform/aks/workspace_variables/staging_aks.tfvars.json
The statuscake contact group was out of date
Add infra team StatusCake contact group
The Find-Apply contact group contact details are being updated
Check in statuscake
> [1654] Add infra team StatusCake contact group

- guides/adr/0011-tda-courses.md
Changes reflect the decisions that we have to make around where to store TDA data on the Course model
> Updated TDA ADR document

- terraform/aks/workspace_variables/app_config.yml
Reverts DFE-Digital/publish-teacher-training#4246
> Revert "Add a BigQuery maintenance window"

- app/helpers/recruitment_cycle_helper.rb
- app/views/pages/roll_over_courses_to_a_new_recruitment_cycle.html.erb
Updating our rollover guidance page so it makes more sense to providers this rollover.
- Update recruitment cycle in the guidance
- Update the academic cycle period in the guidance
- Make these dynamic so they will update itself going forward
[Page on the review app](https://publish-review-4305.test.teacherservices.cloud/how-to-use-this-service/roll-over-courses-to-a-new-recruitment-cycle)
> [1782] Update recruitment cycle/academic cycle period

- .github/actions/deploy_v2/action.yml
- .github/actions/restore/action.yml
Some github workflows are using old versions of actions
Update to current versions
Check workflows run ok
> Update github actions versions

- config/settings/qa_aks.yml
Activating rollover in the QA environment for testing purposes.
> Activate rollover in QA

- config/settings/production_aks.yml
This PR will activate rollover and TDA in production. 
We will activate these in the other environments once we have "rolled over" the respective databases. 
🚢 🚢 🚢
> [2039] Activate TDA and rollover in production

- spec/components/find/results/search_result_component_spec.rb
A failing spec got merged in #4381 
Updates spec to perform correct assertion
> Fixes broken spec

- spec/components/find/courses/about_schools_component/view_preview.rb
These view previews are broken, they should be fixed so that we can view them.
> Fix view previews

- app/assets/stylesheets/components/shared/_accordion.scss
- app/assets/stylesheets/find_application.scss
- app/assets/stylesheets/publish_application.scss
- app/components/find/courses/entry_requirements_component/view.html.erb
- config/locales/find.yml
- spec/components/find/courses/entry_requirements_component/view_spec.rb
This is part of a redesign of the course page to make it more user friendly
Changed the entry requirements component.
| -- | -- |
| ![Screenshot from 2024-07-22 14-25-29](https://github.com/user-attachments/assets/9d4b7cb5-72c2-443c-abdb-443ed2f7192f) | ![Screenshot from 2024-07-22 14-25-43](https://github.com/user-attachments/assets/b1a93413-d280-4640-acf6-0984f69f4dc7) |
Review code and the course show\preview page on find and publish on the review app
> Accordion for non UK citizen section course page

- app/components/find/courses/contents_component/view.html.erb
- app/views/find/courses/show.html.erb
- app/views/publish/courses/preview.html.erb
This is part of the course details pages redesign
| -- | -- |
| ![Screenshot from 2024-07-24 11-28-13](https://github.com/user-attachments/assets/adc24571-4001-4f61-9f73-5d99d2b0ba26) | ![Screenshot from 2024-07-24 11-29-40](https://github.com/user-attachments/assets/64bb98ae-a784-4e52-b89d-eaf07e755ff1) |
View the course show page on find and the preview page on publish
> Move salary before fees on course show pages

- .github/PULL_REQUEST_TEMPLATE.md
Having different PR templates is confusing and we sometime miss checks that are detailed in Apply
Aligned PR Template with the Apply repo https://github.com/DFE-Digital/apply-for-teacher-training/pull/9620
> Aligns PR Template with Apply

- terraform/aks/workspace_variables/staging_aks.tfvars.json
See errors in thread https://ukgovernmentdfe.slack.com/archives/C05D5S8C6PJ/p1722586681771429?thread_ts=1721698836.895399&cid=C05D5S8C6PJ
Upgrade staging DB instance to B_Standard_B2s
CPU is maxed out every night during DB refresh. Upgrade to increase CPU capacity, but also get a fresh instance.
This may be reverted later on as the current cheap instance should be able to handle the load, as QA does.
Already applied manually
Run terraform plan, it should show no change
> [1957] Upgrade staging database

- app/views/pages/add_schools_and_study_sites.html.erb
We will shortly be sending out comms and will link to this page. We want to ensure the information is as accurate as possible.
Update guidance page content
**Link to page**: https://publish-review-4433.test.teacherservices.cloud/how-to-use-this-service/add-schools-and-study-sites
> [2112] Update guidance page content

- config/settings.yml
Following #4437, we now have the code set up to use the new `funding` column we can activate the feature flag.
Once the feature flag is activated, we will continue to use our old implementation until the backfill is complete. Once the backfill has been done we will then switch to the using the database backed funding column.
The feature flag needs to be active before the backfill is done, otherwise the column will get out of sync very quickly.
Activate the feature flag in all environments.
Does the approach make sense to you?
> [2208] Activate the `db_backed_funding` feature flag in all envs

- spec/features/publish/courses/editing_a_levels_tda_course_spec.rb
This test is flaky and has failed in CI, we should use more targeted assertions.
> Fix flaky test

- config/settings/qa_aks.yml
Now that the bug party finished, this PR rollback the 2025 cycle.
> Rollback cycle in QA

- .github/actions/deploy_v2/action.yml
- .github/actions/restore/action.yml
- .github/workflows/database-restore.yml
Updated pipeline to use shared action
Updated pipeline to use shared action
> Updated pipeline to use shared action

- config/settings/qa_aks.yml
Indentation in the yml file is slightly off.
> Fix indentation

- terraform/aks/databases.tf
We need to update the postgres version to the latest stable one - however before this we need to make sure all services pin the postgres version so it’s not updated unexpectedly
Set Postgres server version to 14
https://trello.com/c/4PBO6Miu/834-change-default-postgres-version-to-16
> Pin postgres version

- spec/features/find/search/undergraduate/course_results_spec.rb
We will skip these tests for now to get the cycle open and fix it later
> Skip tests

- terraform/aks/workspace_variables/production_aks.tfvars.json
Increase publish postgres db to GP_Standard_D8ds_v5
due to high cpu usage after find opening
Update tfvars
make production deploy-plan CONFIRM_PRODUCTION=yes
> Increase prod postgres db to GP_Standard_D8ds_v5

- .github/CODEOWNERS
Whoops...
- Change `@publish-and-find` to `@DFE-Digital/publish-and-find`.
It _should_ work now 😁
> Correct the codeowners team name

- db/data/20241011081455_update_accredited_providers.rb
We have identified Providers which have incorrect Accredited Provider data. 
We will update the Accredited Provider for given Providers and their Courses for the 2024 Recruitment Cycle
Requires #4589
> Updates accredited provider data

- config/skylight.yml
Allow us to see deployments in the Skylight interface
> Track deploys in Skylight

- config/initializers/inflections.rb
"Qa" makes me cringe a bit 😅 
- Add "QA" to acronyms.
> Add QA acronym to inflections

- terraform/aks/workspace_variables/production_aks.tfvars.json
We made changes to the web replicas and database CPU for start of cycle to handle the increased level of activity. This PR reverts those two changes.
Reverts changes 
- https://github.com/DFE-Digital/publish-teacher-training/pull/4563 
- https://github.com/DFE-Digital/publish-teacher-training/pull/4552
This requires coordination with dev ops as there will be downtime with the db change. I've tagged in the publish team to manage this.
> Revert scaling done for start of cycle

- .github/actions/deploy/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/deploy-review-app.yml
Review app seeds with the sanitised db backup, so need to update the workflows as this has moved to azure storage.
Workflow updates
see https://github.com/DFE-Digital/publish-teacher-training/actions/runs/12065815523
> Update review app seed to use azure backup file

- app/models/provider_partnership.rb
- config/analytics.yml
- db/migrate/20241129151352_add_provider_partnership.rb
- db/schema.rb
Create the `ProviderPartnership` model. This model is going to replace the AccreditedProviderEnrichment "association"
Following PRs will build out the functionality and associations.
Create the `ProviderPartnership` model.
> Create `provider_partnership` table

- app/models/provider.rb
- app/models/provider_partnership.rb
- config/locales/en.yml
- spec/factories/provider_partnerships.rb
- spec/models/provider_partnership_spec.rb
- spec/models/provider_spec.rb
We have created the database tables for the `ProviderPartnership`.
This PR creates the associations and validations on those associations.
Next will be the controllers and routing
> Im/Create ProviderPartnership association

- .gitignore
- guides/aks_modules.md
- terraform/custom_domains/environment_domains/terraform.tf
- terraform/custom_domains/infrastructure/terraform.tf
Finalise migration from terrafile
- Update docs and gitignore
- Update domains terraform for consistency
Code review
Update domains in all environments
> [2158] Terrafile migration updates

- app/views/find/v2/results/index.html.erb
- spec/system/find/v2/results/search_results_enabled_spec.rb
Add "Apply filters" to the bottom of the filters.
2. Is the style correct?
> Add apply filters button to the bottom of the filters

- app/components/header_component.html.erb
- app/views/layouts/find.html.erb
- config/locales/en/layouts/find.yml
- config/settings.yml
We want to update the feedback link of the Find service.
- Add feedback link to the Find header.
- Takes us to the right form :)
> Update feedback link on the Find service

- .github/actions/deploy/action.yml
- .github/actions/restore/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/database-restore.yml
- .github/workflows/deploy-review-app.yml
- guides/setup-development.md
Sanitised db backups are required to be used to create database in lower environments. 
Add sanitised db backup and restore workflow
The workflow can be executed manually. Restore is also tested when the review app is deployed
Review App - https://github.com.mcas.ms/DFE-Digital/publish-teacher-training/actions/runs/13263404536/job/37025071451
Manual Database Backup & Restore - https://github.com.mcas.ms/DFE-Digital/publish-teacher-training/actions/runs/13262915669
> Add sanitised db backup and restore

- .github/actions/deploy/action.yml
- .github/actions/restore/action.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build-nocache.yml
- .github/workflows/database-restore.yml
- .github/workflows/delete-review-app.yml
- .github/workflows/deploy-review-app.yml
- .github/workflows/deploy.yml
- .github/workflows/disable-maintenance.yml
- .github/workflows/enable-maintenance.yml
- Makefile
- guides/aks-cheatsheet.md
- terraform/aks/providers.tf
https://trello.com/c/FWUebqgi
Deploy to AKS using Github actions and OIDC instead of service principals
Enable gh workflows to use OIDC instead of azure credentials
review app deploy via OIDC: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13367059540/job/37327229745
delete review app: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13366722810
deploy review app wf: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13386219111
manual deploy-plan to all envs: https://github.com/DFE-Digital/publish-teacher-training/actions/workflows/deploy.yml
db backup and restore: https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13388937132
> Enable OIDC for GitHub actions

- .github/workflows/database-restore.yml
- Makefile
- guides/setup-development.md
Update backup and restore workflow so a backup can be run manually, and use the backup-postgres github action.
- Updates to workflow
- Remove old restore command from Makefile
- documentation update
manual qa backup https://github.com/DFE-Digital/publish-teacher-training/actions/runs/13408978551
> Enable manual postgres backup

- .github/workflows/build-and-deploy.yml
Add all urls to the deploy review app pull request comments
Update build-and-deploy workflow
Look at the comment in this PR
> Add all urls to review app PR deploy comment

- db/data/20250303121528_backfill_provider_partnerships.rb
Committed a linting error before merging
> Correct linting error

- .tool-versions
https://github.com/Azure/kubelogin/releases/tag/v0.2.6
> Latest kubelogin version is 0.2.6

- guides/alerting_and_monitoring.md
Make reference to our logging system in our documentation.
Add link to our logging workshop
Update documentation
> Update logging docs

- .github/PULL_REQUEST_TEMPLATE.md
We need a checklist to refer to in order to remind developers to perform cleanup tasks as they are working on existing files.
- Add checklist to the PR template.
View the new template [here](https://github.com/DFE-Digital/publish-teacher-training/blob/dd/update-checklist/.github/PULL_REQUEST_TEMPLATE.md).
> Add temporary checklist to pull request templates

- spec/services/authentication_service_spec.rb
We are seeing flaky tests in our test suite in Publish. (see details in the Trello card below). 
This fix attempts to fix the flakey test.
1. Pull locally
2. Run multiple times (e.g `for i in {1..100}; do echo "Run #$i"; rspec spec/services/authentication_service_spec.rb || break; done`)
> Fix flakey test

- config/locales/en/components/find/courses/about_schools_component.yml
- spec/components/find/courses/about_schools_component/view_spec.rb
We are changing 120 days to 24 weeks spent in schools to be consistent with GIT .
> Change time spent in schools text

- app/views/support/recruitment_cycles/index.html.erb
Make the table full width on recruitment cycles support page.
> Make the table full width on recruitment cycles page

- app/controllers/application_controller.rb
- app/controllers/find/application_controller.rb
Adding the session id to the logging we are able to trace requests through the application. This will help us debug issues. 
Anything we need to be careful of here as regards PII or peformance?
> Add session id to logging

- .github/workflows/build-nocache.yml
Add a description of the values in the Snyk level setting in the Build No Cache workflow
> Add description of Snyk level in build-no-cache workflow

- config/settings.yml
- config/settings/qa.yml
- config/settings/review.yml
Part 2 of https://github.com/DFE-Digital/publish-teacher-training/pull/5257
This removes the feature flag after the code is removed.
> Clean up apisummarycontentchange feature flag part 2

- .github/workflows/delete-review-app.yml
A couple of issues with delete review app workflow previous updates
- if statement causes workflow to run regardless
- missing permissions
updates to workflow
closed with no deploy label (should skip) https://github.com/DFE-Digital/publish-teacher-training/actions/runs/15065692405  
closed with deploy label https://github.com/DFE-Digital/publish-teacher-training/actions/runs/15066887153
> Update if and permissions for del review workflow

- app/controllers/support/feedbacks_controller.rb
- app/views/layouts/support.html.erb
- app/views/support/feedbacks/_list.html.erb
- app/views/support/feedbacks/index.html.erb
- app/views/support/feedbacks/show.html.erb
- config/locales/en/activerecord.yml
- config/locales/en/layouts/support.yml
- config/locales/en/support/feedbacks.yml
- config/routes/support.rb
- spec/system/support/feedbacks_spec.rb
Trello: https://trello.com/c/ijgOzXAH/529-feedback-form-link-up-to-the-support-console
Previously we worked to turn our 'Find teacher training courses' feedback form from a Microsoft form into a proper service based form (as per best practice / design principles). We would now like to view user feedback/responses via the support console.
The gov style feedback form has been created here: https://github.com/DFE-Digital/publish-teacher-training/pull/5217
This PR links the feedback submitted via the new gov style form on Find, to the support console (in Publish); for the MVP we are creating a table where the responses can be viewed. 
- create `FeedbacksController` (with an index action)
- routes: `resources :feedbacks, only: %i[index], path: "feedback", as: :feedback`
- create a view: …
> Feedback form - link up to the support console

- terraform/aks/workspace_variables/qa.tfvars.json
QA is very slow and affecting smoke tests and deployment.
So let's upgrade postgres plan - this will help to unblock pipeline and make QA faster
> Upgrade QA DB

- .rubocop.yml
- .rubocop_todo.yml
- config/rubocop/naming.yml
- spec/system/support/providers/accredited_partnerships_spec.rb
- spec/system/support/providers/courses/editing_a_course_spec.rb
- spec/system/support/providers/courses/editing_visa_sponsorship_spec.rb
- spec/system/support/providers/courses/reverting_a_withdrawal_spec.rb
- spec/system/support/providers/courses/viewing_providers_courses_spec.rb
- spec/system/support/providers/editing_a_provider_spec.rb
- spec/system/support/providers/editing_a_user_from_a_provider_spec.rb
- spec/system/support/providers/onboarding_a_new_provider_spec.rb
- spec/system/support/providers/provider_courses_list_spec.rb
- spec/system/support/providers/provider_users_list_spec.rb
- spec/system/support/providers/providers_filter_spec.rb
- spec/system/support/providers/providers_list_spec.rb
- spec/system/support/providers/removing_user_from_provider_spec.rb
- spec/system/support/providers/schools/add_school_to_provider_spec.rb
- spec/system/support/providers/schools/creating_multiple_schools_spec.rb
- spec/system/support/providers/schools/delete_school_spec.rb
- spec/system/support/providers/users/adding_user_to_provider_spec.rb
- spec/system/support/providers/viewing_a_user_spec.rb
Next step in migrating all feature specs to the system specs directory
Move `spec/features/support` => `spec/system/support`
> Move spec/feature/support/* specs to system tests

- .github/workflows/build-and-deploy.yml
Remove domains apply from cicd while we configure rate limiting, so publish team can continue merging
Comment out section from build-and-deploy-workflow
Check workflow
> Temporary removal of domains-apply from cicd

- spec/controllers/api/school_suggestions_controller_spec.rb
Make sure the test search query doesn't match randomly generated properties of the test case.
> Search looks in town and postcode, make them blank when not found

- app/controllers/publish/courses/fields/school_placement_controller.rb
- config/locales/en.yml
- spec/system/publish/courses/long_form_content/school_placement_spec.rb
Kellie found a success message that wasn't correct. Here is the fix.
> [Longform] Changing the success message on provider school placement page

- app/decorators/course_decorator.rb
- app/views/find/courses/v2/_components.html.erb
- app/views/find/courses/v2/_where_you_will_train.html.erb
- spec/system/find/courses/long_from_content/wher_you_will_train_spec.rb
Adding WHere you will train to find course page
Adding all the field entries from the where youwill train page from publish into find
Check the code, then approve
> [Longform] Adding where you will train to find

- app/helpers/application_helper.rb
- app/helpers/view_helper.rb
> [Longform] Fix fees error url

- app/components/course_preview/missing_information_component.rb
- app/controllers/publish/courses_controller.rb
- app/views/find/courses/v2/_components.html.erb
- app/views/find/courses/v2/_school_placement.html.erb
- app/views/find/courses/v2/_train_with_us.html.erb
- app/views/find/courses/v2/_where_you_will_train.html.erb
- app/views/find/courses/v2/financial_support/_fees_and_financials.html.erb
- app/views/find/courses/v2/interview_process/_interview_process.html.erb
- app/views/find/courses/v2/what_you_will_study/_what_you_will_study.html.erb
- config/locales/en.yml
- config/locales/en/find/courses.yml
Adding the school box which shows potential schools and how far they are away from your location.
Adding the existing schools box to where you will train for the long form course content
> [Longform] Adding the school section to where you will train

- app/controllers/publish/providers/course_fields/disability_support_controller.rb
- app/views/publish/providers/course_fields/disability_support/edit.html.erb
- spec/system/publish/providers/last_cycle_training_with_diabilities_spec.rb
We were asked to implement the last cycle banner to training with disability. 
Adding last cycle banner to training with disability
> [Longform] Adding last cycle banner to training with disability

- config/settings/production.yml
Enable one_login in production
> Release Candidate Accounts in production

- load_testing/find/scenarios/baseline.js
- load_testing/find/scenarios/peak-surge.js
- load_testing/find/scenarios/stress-test.js
Adjust load testing scenarios: update target users for baseline, peak surge, and stress test scenarios
Reducing the VU to more accurately imitate requests to service
> [Loadtest ] Reduce number of VU for Load Test scenarios

- app/components/find/maintenance_banner_component.html.erb
We are planning DB maintenance tomorrow. 
So we need to change the maintenance banner content
> Change maintenance banner content

- app/views/find/pages/accessibility.html.erb
- config/locales/en/find/pages/accessibility.yml
The accessibility statement must be reviewed and updated at least every 12 months, even if no interim testing or audits happen. This regular review process shows ongoing compliance with accessibility standards. It also demonstrates a commitment to maintaining an accessible digital product for all users."
- update accessibility statement
- refactor code / move content into locale file: `config/locales/en/find/pages/accessibility.yml`
- check content 
- check that you are happy with the reformatting of code to use locale file
> Update accessibility statement
